### ISSUE TITLE
Custom state in GridCell components when using TypeScript

### ISSUE THREAD

**Issue by PaitoAnderson** [telerik/kendo-react#10]
## I'm submitting a...
Suggestion for improvement

## Current behavior
When using TypeScript to create a component that extends `GridCell` that is no way that I can see to use your own state properties.

## Expected behavior
TypeScript friendly way to create and use your own state in a component that extends `GridCell`.

## Minimal reproduction of the problem with instructions
```ts
import { GridCell } from '@progress/kendo-react-grid';
import * as React from 'react';

type State = {
  show: boolean;
}

export class ActionCell extends GridCell<{}, State> {
  public render() {
    return (
      <td>
        Popup here that uses this.state.show
      </td>
    );
  }
}
```

## Possible Solution (GridCell.d.ts)
UPDATE: I realized this won't work as the GridColumn component complains it can't use them.
```ts
export default class GridCell<GridCellProps, S = {}> extends React.Component<GridCellProps, S> {
    /**
     * @hidden
     */
    render(): JSX.Element;
}
```

## Environment

Package versions:

```
+-- @progress/kendo-react-grid@0.4.0
```

Browser:
- Chrome (desktop) version 65.0.3325.146

System:
- TypeScript version: 2.7.2
- Node version: v8.9.4, v5.7.1
- Platform:  Windows

**Comment by Xizario** [comment]
I am not sure if generalizing `props` is possible, since the grid does not know what values to pass when instantiating cells that are implementing custom interface.

It is possible for the `state`, but in this case the cells need to have not only a unique `key` per column, but the `key` need to persist during column reordering and on adding or removing columns. This require columns to have additional `key` parameter that to be required.
The above will also put more strict requirement on row keys, that are currently something like `skip + rowIndex` they will need to have unique key coming from the actual data the grid is bound to.

It is still something worth the consideration, especially if there is a use case, that can not be implemented in different way.

**Comment by PaitoAnderson** [comment]
Thanks for the response @Xizario, good point about `props`, I have only run across a need for generalizing `state` anyway.

**Comment by abhaygitty** [comment]
@PaitoAnderson : Hey! I was wondering if you had a working implementation of kendo-react-grid using typescript. I have also emailed you the stack-overflow post about the same. Could be of a great help if you could proviude insight

**Comment by PaitoAnderson** [comment]
@abhaygitty Hello, I really didn't run into any issues using kendo-react-grid with typescript, maybe post your specific issues on stackoverflow or open a support ticket with Telerik?

You should be able to just create a new react app (https://create-react-app.dev/docs/getting-started#creating-a-typescript-app) and then follow this (https://www.telerik.com/kendo-react-ui/components/grid/get-started/).

Hope that helps!

**Comment by vladimirivanoviliev** [comment]
This is already fixed on our side and you can expect the fix in next releases.

**Comment by Xizario** [comment]
Fixed in 4.2.0

**Comment by PaitoAnderson** [comment]
Thanks for getting this in, great stuff! I'm curious when it comes to TypeScript am I still able to use React and Functional Components? I just got around to updating and I'm seeing this error with React Components.

<img width="864" alt="Screen Shot 2021-02-25 at 9 13 38 AM" src="https://user-images.githubusercontent.com/4108718/109165717-de403580-7749-11eb-8a4e-43293dc629a0.png">

https://www.telerik.com/kendo-react-ui/components/grid/cells/#toc-grid-cells

**Comment by Xizario** [comment]
Yes, you can still use class. We changed the default GridCell implementation, but the actual interface for what grid works with is the same `ComponentType<GridCellProps>` so it can be class or functional component, as long as its props are GridCellProps.
```ts
export class ReferenceCell extends React.Component<GridCellProps>{
 public render(){
...
}
```
The above will work in previous versions as well. I think it was error in our documentation that in some examples we were showing extends of the GridCell, GridDetailRow, etc.
