### ISSUE TITLE
Grid component GridNoRecords not working after version 2.2.0

### ISSUE THREAD

**Issue by tienlx93** [telerik/kendo-react#100]
## Current behavior
Adding the `GridNoRecords` component to `Grid` component is not working after version 2.2.0

Demo: https://www.telerik.com/kendo-react-ui/components/grid/api/GridNoRecords/

Browser:

- Chrome (desktop)

**Comment by Xizario** [comment]
I updated the link. Essentially adding this line should help:
```GridNoRecords.displayName = 'KendoReactGridGridNoRecords';```

**Comment by Xizario** [comment]
Fixed in `v2.3.0-dev.201810171100`
https://www.telerik.com/kendo-react-ui-develop/components/grid/api/GridNoRecords/
