### ISSUE TITLE
Drawer Keyboard Support

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-react#1004]
Currently, only tabbing through items is supported. Enabling selection via `Enter | Space` keys will make the component navigatable through the keyboard only.

Reported in ticket ID: 1528390

**Comment by filipKovachev** [comment]
Requested again in Ticket 1603523

**Comment by silviyaboteva** [comment]
The feature is implemented in the current dev version [v8.1.0-develop.1](https://www.npmjs.com/package/@progress/kendo-react-layout/v/8.1.0-develop.1). It will be available in the upcoming official release.
