### ISSUE TITLE
grid with selectable options brake resizable functionality, and override virtual scrolling Bevier

### ISSUE THREAD

**Issue by eliranYit** [telerik/kendo-react#1007]
version @progress/kendo-react-grid: 4.7.0

grid with selectable options brake resizable functionality, and override virtual scrolling Bevier
selectable={ {cell: false, enabled: true, mode: 'single', drag: false }}

- when scrolling to the buttom pageSize   the onDataStateChange/onPageChange not invoked
- resizing the column break the table

![image](https://user-images.githubusercontent.com/85220340/126628928-3dd5b414-9354-4d79-8270-2cddd4986f26.png)

![image](https://user-images.githubusercontent.com/85220340/126628777-3e8d6e09-c9c2-4bdb-ad3a-9e7a5b810644.png)

**Comment by vladimirivanoviliev** [comment]
Fixed in `4.8.0`
