### ISSUE TITLE
Grid with virtual scroll and selectable doesn't work after changing total count 

### ISSUE THREAD

**Issue by mrozu** [telerik/kendo-react#1010]
## I'm submitting a...
* Bug report

## Current behavior
Grid with virtual scroll and selectable enabled.
Render grid with 100 items.
Change number of items to 99 (e.g. by filtering)

Virtual scroll does not work, only first page is loaded.

## Expected behavior
Virtual scroll works, next pages are displayed when scrolling

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-tfjv3e?file=app%2Fmain.tsx

**Comment by Xizario** [comment]
Fixed in 4.8.0
