### ISSUE TITLE
Using Chart component in React.StrictMode results in 'Can't call setState on a component that is not yet mounted.''

### ISSUE THREAD

**Issue by tygrysmalajski** [telerik/kendo-react#1011]
## I'm submitting a...

* Bug report 

## Current behavior
Using `Chart` component in `React.StrictMode` results in console warning:
```
Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the DonutCenter component.
```

## Expected behavior
No console warning.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-rsqu4x?file=app/main.tsx

## Environment

Package versions:

```
@progress/kendo-react-charts@4.7.0
```

**Comment by Lumpenstein** [comment]
+1 getting the same error. Issue is in DonutCenter.js:57

**Comment by PekoPPT** [comment]
The issue is no longer replicable in the latest version of the KendoReact suite - https://stackblitz.com/edit/react-rsqu4x-kmxc7s?file=app%2Fapp.tsx,index.html.
