### ISSUE TITLE
Very glitchy Virtual Scroll on Safari

### ISSUE THREAD

**Issue by eakelb** [telerik/kendo-react#1013]
## I'm submitting a...
* Bug report

Safari can't handle virtual scrolling in grids - just adding `scrollable={"virtual"}` makes it very glitchy.
On the bottom a huge empty space is left and sometimes you can't even scroll to the top.

Example is basic virtual scroll usage from docs, section Getting Started: https://www.telerik.com/kendo-react-ui/components/grid/scroll-modes/virtual/
I limited data count to 10 to make the bug more clear

https://user-images.githubusercontent.com/21054555/127002552-97d3b67a-bf2d-4c39-8954-6ce2218c62ab.mov

Browser:
- Safari (desktop) version 14.1.1

**Comment by simonssspirit** [comment]
@eakelb  thank you for the video.

One of the requirements is to have pageSize larger than the visible records. In the demo, I see that the pageSize is smaller than that.

`(Required) pageSize—To avoid unexpected behavior during scrolling, set pageSize to at least the number of the visible Grid elements. The number of the visible Grid elements is determined by the height and rowHeight settings of the Grid.`

**Comment by Guria** [comment]
We have pageSize much bigger than scrollable area. in above example on screenshot pageSize is 20.

**Comment by Guria** [comment]
We are paying clients and would like to have it fixed in a prioritized way. Do we have any support submit form to inform about our needs?

**Comment by simonssspirit** [comment]
@Guria After more tests we assume that it is connected to this item that we have logged here: https://github.com/telerik/kendo-react/issues/847

I already escalated that one and add it to our ToDo list.

**Comment by nstoychev** [comment]
Fixed in version 5.10.0.

Note that grid's `rowHeight` prop is required now and the `pageSize`/`take` props need to be at least 2 times the count of the visible rows.
