### ISSUE TITLE
Feature request: onClear event for AutoComplete component.

### ISSUE THREAD

**Issue by kosimas** [telerik/kendo-react#1015]
A onClear event for the AutoComplete component would be pretty awesome. The event should fire on clearButton click.

**Comment by Xizario** [comment]
Is there any issue using the onChange event, it fires when the AutoComplete clear button is pressed?

**Comment by kosimas** [comment]
There is no issue with the onChange event. It's more like an rare edge case where something has to happen only if the clearButton was pressed. The onChange event dosen't know if the user manually deleted everything, or if someone pressed the clearButton(correct me if I'm wrong).

**Comment by Xizario** [comment]
The onChange callback contains all information from the native DOM event and the React Synthetic Vvent so you can determinate the original target from which the event propagated. You can distinguish the button by class, type, title, ref or anything that would suite your needs. For example:
```jsx
const onChange = (event) => {
    if (event.nativeEvent.target.classList.contains("k-clear-value")){ 
    } 
  }
// or
onChange = (event) => {
    if (event.syntheticEvent.type == "click"){  
    } 
  }
```
We follow the same concept for components with bigger nesting. Take a Grid for example. The [onFilterChange](https://www.telerik.com/kendo-react-ui/components/grid/filtering/) can originate from various actions: column menu, filter row, or even filter row with custom cell with autocomplete with clear button inside.
Now if you want to determinate if end user has changed the filter using the clear button inside an autocomplete box in a custom filter menu, you can do it the same way as the[ synthetic event is in the callback](https://www.telerik.com/kendo-react-ui/components/grid/api/GridFilterChangeEvent/). This also allows you to distinguish different user actions, like drag, deleting with keyboard or mouse etc.

**Comment by kosimas** [comment]
Okay thanks for your reply and help! I will close this issue now.
