### ISSUE TITLE
Fix NumericTextBox behaviour when min and max are set.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#102]
Fix NumericTextBox behavior when min and max are set.

In the following example, a valid value can only be set using copy-paste and cannot be written into the NumericTextBox:

https://stackblitz.com/edit/react-byth3m-hr6snb?file=app/main.js

A possible workaround

https://stackblitz.com/edit/react-byth3m-x2xp9q?file=app/main.js

**Comment by vladimirivanoviliev** [comment]
Note: Try to type 50

**Comment by vladimirivanoviliev** [comment]
Fixed in latest dev version `3.10.0-dev.202001150733`.
