### ISSUE TITLE
DateTimePicker keeps the focus style around the input even after the `Cancel` button is clicked.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1022]
DateTimePicker keeps the focus style around the input even after the `Cancel` button is clicked.

https://www.telerik.com/kendo-react-ui/components/dateinputs/datetimepicker/

1) Open the picker.

2) Click the Cancel button.

3) Notice how the focus styles are still visible:

![image](https://user-images.githubusercontent.com/11087921/128026351-d9788de6-4319-4f4c-8576-be94c631736f.png)

**Comment by kspeyanski** [comment]
The issue has been fixed in version [4.9.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/) of the `@progress/kendo-react-dateinputs` package.
