### ISSUE TITLE
Row Reordering Doesn't Move The "Hover" State

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#1023]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
When re ordering rows, the "hover" effects including background colour stay on the initially clicked row, rather than following the row that we are dragging. In the screenshot below I'm moving Chai but the hover highlight has been left behind.

![image](https://user-images.githubusercontent.com/12272970/128102892-96d53718-3ed2-4f1b-b924-8b24c94c7043.png)

## Expected behavior
Hover effects should apply to the hovered row even while dragging.

## Minimal reproduction of the problem with instructions
https://www.telerik.com/kendo-react-ui/components/grid/rows/row-reordering/

1. Drag an item to another place.
2. The hover highlight remains on the old index instead of following the dragging row.

## What is the motivation or use case for changing the behavior?
We have drag ordering of rows on many of our grids, and this makes it more difficult to keep track of the item being ordered.

## Environment

Browser:
- Chrome (desktop) Version 92.0.4515.131 (Official Build) (64-bit)

System:
- Platform:  Windows

**Comment by kdikov82** [comment]
The drag-and-drop functionality is not part of the Grid, so any customizations should be added in the custom logic for the reordering.

We have also updated our demo for displaying an insert indicator while dragging:
[https://www.telerik.com/kendo-react-ui/components/grid/rows/row-reordering/#toc-kendoreact-dragdrop](https://www.telerik.com/kendo-react-ui/components/grid/rows/row-reordering/#toc-kendoreact-dragdrop)
