### ISSUE TITLE
MultiSelect item goes outside of the MultiSelect box if it is larger than the MultiSelect.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1026]
MultiSelect item goes outside of the MultiSelect box if it is larger than the MultiSelect:

![image](https://user-images.githubusercontent.com/11087921/128193262-44ed045b-5332-4161-a15a-dc19a72a9a6a.png)

**Comment by kdikov82** [comment]
Seems to be fixed in the latest version (tested with 5.11.0):
https://stackblitz.com/edit/react-xo8px2?file=app%2Fmain.jsx
