### ISSUE TITLE
Grid ColumnMenu cannot be closed by clicking the menu icon.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1028]
Grid ColumnMenu cannot be closed by clicking the menu icon:

![image](https://user-images.githubusercontent.com/11087921/128304828-931d951a-cd4e-48ee-af83-89b3d6b0e83c.png)

**Comment by kdikov82** [comment]
Reported again in Ticket ID: 1542843

**Comment by kdikov82** [comment]
Reported again in Ticket ID: 1553739

**Comment by simonssspirit** [comment]
reported again 1530533 adding in ToDo lists

**Comment by vveesseelliinnaa** [comment]
Reported again in Ticket ID: 1570202

**Comment by nstoychev** [comment]
Fixed in our development channel version 5.5.0-dev.202206280851. See the following article about obtaining the development builds - https://www.telerik.com/kendo-react-ui/components/installation/development-builds/.
