### ISSUE TITLE
React multiselect with custom value plus icon not working as expected

### ISSUE THREAD

**Issue by sfc-gh-vchandran** [telerik/kendo-react#1035]
I am using macOS Big Sur version 11.4. Here the custom item in kendo react multiselect is not added on clicking plus icon.
When I use macOS Big Sur version 11.5, clicking on plus icon adding the custom item but the dropdown keep on showing after select. Even on clicking outside, it not disappearing.
Screenshot and  code sample given bellow.

<img width="962" alt="Screenshot 2021-08-09 at 4 59 27 PM" src="https://user-images.githubusercontent.com/85836497/128700339-0f75d3db-2d98-4e53-bc98-0ec06f166123.png">

`import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { MultiSelect } from '@progress/kendo-react-dropdowns';
const sports = ["Baseball", "Basketball", "Cricket", "Field Hockey", "Football", "Table Tennis", "Tennis", "Volleyball"];

const App = () => {
  const [value, setValue] = React.useState([]);

  const handleChange = event => {
    const values = event.target.value;
    const lastItem = values[values.length - 1];

    if (lastItem) {
      values.pop();
      const sameItem = values.find(value => value === lastItem);

      if (sameItem === undefined) {
        values.push(lastItem);
      }
    }

    setValue(values);
  };

  return <div>
      <div className="example-config">
        Selected Values: {JSON.stringify(value)}
      </div>
      <MultiSelect data={sports} onChange={handleChange} value={value} allowCustom={true} />
    </div>;
};

ReactDOM.render(<App />, document.querySelector('my-app'));`

**Comment by nstoychev** [comment]
The issue has been fixed in version [4.9.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/).
