### ISSUE TITLE
Some of the anchor tags in the Scheduler are missing preventDefault and can cause a page to reload.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1036]
Some of the anchor tags in the Scheduler are missing preventDefault and can cause a page to reload.

**Comment by kspeyanski** [comment]
The issue has been fixed in version [4.9.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/) of the `@progress/kendo-react-scheduler` package.
