### ISSUE TITLE
MultiSelect add custom value button is not adding the new value.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1038]
MultiSelect add custom value button is not adding the new value:

![image](https://user-images.githubusercontent.com/11087921/129143333-8e79dd6c-999a-4a3c-959e-39b7c1a0668c.png)

I noticed that may the blur is fired before that and the list is closed. If the list is always open with the opened prop, it button is working correctly.

**Comment by nstoychev** [comment]
The issue has been fixed in version [4.9.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/).
