### ISSUE TITLE
Docs Typo: Dialog - Keyboard Navigation (Tap vs Tab)

### ISSUE THREAD

**Issue by jbristowe** [telerik/kendo-react#104]
## I'm submitting a...

* Documentation issue or request

## Current behavior

The word, `Tab` is misspelled on the page, [Keyboard Navigation](https://www.telerik.com/kendo-react-ui/components/dialog/keyboard-navigation/):

>When the Dialog is opened, the initial focus is set on the `Dialog` element. This approach enables the user to immediately select or navigate between the action buttons by using the `Tap` and `Shift`+`Tap` keys, and to close the Dialog with the `Esc` button.
>
>You can set the initial focus to one of the action buttons by using the [`autoFocus`](http://www.jackcallister.com/2014/11/25/autofocus-in-react-js.html) attribute.
>
>| SHORTCUT                            | DESCRIPTION                                        |
>|:---                                 |:---                                                |
>| `Esc`                               | Calls the `onClose` event handler.                 |
>| `Shift`+`Tap`                       | Moves the focus to the previous focusable element. |
>| `Tap`                               | Moves the focus to the next focusable element.     |

## Expected behavior

>When the Dialog is opened, the initial focus is set on the `Dialog` element. This approach enables the user to immediately select or navigate between the action buttons by using the `Tab` and `Shift`+`Tab` keys, and to close the Dialog with the `Esc` button.
>
>You can set the initial focus to one of the action buttons by using the [`autoFocus`](http://www.jackcallister.com/2014/11/25/autofocus-in-react-js.html) attribute.
>
>| SHORTCUT                            | DESCRIPTION                                        |
>|:---                                 |:---                                                |
>| `Esc`                               | Calls the `onClose` event handler.                 |
>| `Shift`+`Tab`                       | Moves the focus to the previous focusable element. |
>| `Tab`                               | Moves the focus to the next focusable element.     |

## Minimal reproduction of the problem with instructions

Not applicable

## What is the motivation or use case for changing the behavior?

Fix spelling for documentation

## Environment

Package versions: N/A
Browser: N/A
System: N/A

**Comment by simonssspirit** [comment]
Fixed with : https://github.com/telerik/kendo-react-private/pull/431
