### ISSUE TITLE
Header misalignment in the GanttYearView.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1041]
Header misalignment in the GanttYearView.

![image](https://user-images.githubusercontent.com/11087921/129305873-593f6637-3de5-4011-b4ec-a393b5908f30.png)

**Comment by kdikov82** [comment]
The issue could not be replicated with the latest versions (tested with 5.11.0)
https://stackblitz.com/edit/react-e9vien?file=app%2Fmain.jsx
