### ISSUE TITLE
Pressing decimal separator symbol when the entire value is selected will clear the NumericTextBox

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1042]
Pressing the decimal separator symbol when the entire value is selected will clear the NumericTextBox:

Step 1 : user entered the value X in the numeric text box.

Step 2 : Focus out the numeric text box

Step 3: Now focus the NumericTextBox component and press Ctrl + A to select all and enter a decimal symbol (. , etc) using the keyboard then the expected result is “0.00”, but the NumericTextBox becomes empty.

Possible workaround: [https://stackblitz.com/edit/react-wz3gxr-dmffjp?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-wz3gxr-dmffjp?file=app%2Fmain.jsx)

**Comment by zyconskarthi** [comment]
Hi Team,

This is a critical Bug for our clients. Can you Please fix this issue. If required I will share the license details.  I have posted the same in React kendo forum.

**Comment by zyconskarthi** [comment]
If any workaround also welcome.

**Comment by WissamProgress** [comment]
Reported in Ticket ID: 1587296

**Comment by elena-gancheva** [comment]
The fix is available in the latest official version: https://github.com/telerik/kendo-react-private/releases/tag/v5.18.0
