### ISSUE TITLE
TreeView indeterminate state can only be set initially.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1043]
TreeView Indeterminate state can only be set initially.

The other two state can be changed when the data passed to the component is updated in the state.

https://stackblitz.com/edit/react-fqt12n-l8fvcq?file=app/main.jsx

In the example notice how the initially set indeterminate state cannot be changed to another state later on. Also, noticed how even clicking the Check checkIndeterminate button will not set the respective items to an indeterminate state.

**Comment by ksdc-grantw** [comment]
@simonssspirit 
Thanks for logging this. Do you have an ETA on when it will be started or added to the library? I have a project design that has a feature dependent on this.
Thanks

**Comment by simonssspirit** [comment]
@ksdc-grantw We will plan this after the current release (mid September) as all of the tasks until the release are already planned.

**Comment by ksdc-grantw** [comment]
@simonssspirit Has there been any progress on this issue yet? THanks.

**Comment by InaGlushkova** [comment]
Raising priority.
1531350

**Comment by jsedlak** [comment]
We are also facing this issue - is there any known workaround to force the TreeView to update or re-render?

**Comment by filipKovachev** [comment]
Raising priority.
1589943

**Comment by keymakerpl** [comment]
Any progress or workaround?

**Comment by kdikov82** [comment]
Just a note for the example. The "data" property should be set to the "data" state variable

**Comment by alwendt4** [comment]
Any update on this bug?  When it will be fixed?
