### ISSUE TITLE
MultiSelect `k-state-focused` class is added but the component is not focused

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#1047]
Example demonstrating behavior:
https://stackblitz.com/edit/react-uyf4mz-kkxwzt?file=app/main.jsx

Steps to reproduce:
1. Select value in MultiSelect (tag/chip is created)
2. Click into the Input (input gains focus)
3. Click on the remove icon on the MultiSelect chip

OR

1. Select value in MultiSelect
2. Click outside the MultiSelect to focus out
3. Click on the remove icon on the MultiSelect chip (MultiSelect gains k-state-focused)
4. Click into Input (Input is focused)

Result: MultiSelect has a `k-state-focused` class but the focused element is the Input.

Expected behavior: When MultiSelect gains the `k-state-focused` class the MultiSelect must be focused.

**Comment by kdikov82** [comment]
Tested with version 5.11.0 and the issue with the focused state is resolved.
