### ISSUE TITLE
Scheduler Timeline view event drag editing with inconsistent values.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1050]
Scheduler Timeline view event drag editing with inconsistent values.

If we have an event Start 12: 03 PM - End 12: 13 PM and we start and start dragging the event, the new time will be inconsistent. Sometimes they will be around time like 12: 15, sometimes 12: 17.

More details and a video can be seen in ticket: 1532291

**Comment by kspeyanski** [comment]
In the case with `slotDuration={15}` and `slotDivisions={2}` a single cell actually represents a 7 minutes and 30 seconds - the half of the duration of 15 minutes. 

In the provided configuration of with `12:03` starting time, we're actually incrementing/decrementing the start date with `7:30` or `450 000` milliseconds, it's the formatting that's somehow misleading.

We would have to gather more feedback before changing how the dragging currently work, so i'm encouraging anyone to post their scenarios so we can further discuss how to improve it.
