### ISSUE TITLE
Pressing Esc in the open DatePicker does not return the focus to the input.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1051]
Pressing Esc in the open DatePicker does not return the focus to the input.

https://www.telerik.com/kendo-react-ui-develop/components/dateinputs/datepicker/keyboard-navigation/

`Esc	Closes the popup and moves the focus to the input element.`

**Comment by kspeyanski** [comment]
The issue has been fixed in version [4.9.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/) of the `@progress/kendo-react-dateinputs` package.
