### ISSUE TITLE
MultiColumnCombox `defaultValue` is not correctly set

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#1054]
Current behavior:
https://stackblitz.com/edit/react-qe8vpd?file=app/main.jsx 

Expected behavior:
The `defaultValue` prop should set the value of the input element as inside the ComboBox:
https://stackblitz.com/edit/react-rspxcp?file=app/main.jsx

**Comment by nstoychev** [comment]
The defaultValue should be a dataItem as the data passed to the component - https://stackblitz.com/edit/react-qe8vpd-zooyqs?file=app%2Fmain.jsx.

If defaultValue is a different instance, the [`dataItemKey`](https://www.telerik.com/kendo-react-ui/components/dropdowns/api/MultiColumnComboBoxProps/#toc-dataitemkey) prop should be set in order the value to be highlighted in the popup list.
