### ISSUE TITLE
Issue with sorting grid columns on iOS devices

### ISSUE THREAD

**Issue by AFSJuanBello** [telerik/kendo-react#106]
## I'm submitting a...
* Bug report

## Current behavior
On an iOS device, running either mobile Safari or Chrome, when tapping on a column header to dispatch the sort event, the grid fails to sort by that column.

## Expected behavior
The grid should sort on column where its header was tapped.

## Minimal reproduction of the problem with instructions
  1. Access the following StackBlitz editor on an iOS device:
https://stackblitz.com/edit/react-nraojq?file=app/main.js
  2. Click on any column in the rendered UI preview.
![img_0001](https://user-images.githubusercontent.com/44374916/47311031-bafb9d80-d606-11e8-8943-19b18aa3fe61.PNG)

  3. You should observe an error as presented in screenshot below:
![img_0002](https://user-images.githubusercontent.com/44374916/47311015-b20acc00-d606-11e8-8269-1713c7b17fb0.PNG)

## What is the motivation or use case for changing the behavior?
Address broken functionality with regards to sorting a grid column on an iOS enabled device.
```

```

Browser:
- Safari (iOS) version 12.0.1
- Chrome (iOS) version 70

**Comment by Xizario** [comment]
Fixed in `v2.3.1-dev.201810291338`

**Comment by simonssspirit** [comment]
The official version 2.3.1 one with the fix is already available.
