### ISSUE TITLE
Treeviews item have touch-action none even if draggable is false

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-react#1064]
This effectively, blocks the scrolling on mobile devices.
Expected behaviour: the scroll should not be prevented if draggable is false. 
Furthermore touchAction should not be set in the default rendering, since the client could want to control both dragging and scrolling at the same time. This should be optional style.

**Comment by kdikov82** [comment]
Reported again in ticket 1661528.
I am increasing the priority since this makes the TreeView unusable on mobile

**Comment by kdikov82** [comment]
Temporary workaround: 
```
            <style>
                .k-treeview-leaf{
                    touch-action: auto!important;
                }
```
