### ISSUE TITLE
Scheduler - reduce items width to allow underneath slots clicking

### ISSUE THREAD

**Issue by kspeyanski** [telerik/kendo-react#1070]
The current version of the Scheduler renders it's items with `100%` width. This is not optimal as a user can not easily click on the slot underneath.
Because of this, we want to further enhance the component by allowing at-least `20px` right margin to enable clicking on the slots under an item:

![image](https://user-images.githubusercontent.com/30626787/131792288-45294d07-37b9-46b3-8aaa-13e2487e91c1.png)

**Comment by kspeyanski** [comment]
The issue has been fixed in version [4.9.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/) of the `@progress/kendo-react-scheduler` package.

**Comment by richherb** [comment]
Thank you team - this is perfect!

**Comment by simonssspirit** [comment]
@kspeyanski Please share your view on this feature for the TimeLineView: https://stackblitz.com/edit/react-asermz?file=app/main.jsx

Currently, it seems like the event is finishing earlier than its end time. Should we disable this feature for that view?

**Comment by Micah-S** [comment]
> @kspeyanski Please share your view on this feature for the TimeLineView: https://stackblitz.com/edit/react-asermz?file=app/main.jsx
> 
> Currently, it seems like the event is finishing earlier than its end time. Should we disable this feature for that view?

Thanks Stefan, I brought this issue up on the forum and would love to see a way to override the feature. I'm trying to implement the TimelineView with 15 minute intervals, and it certainly gives the impression that events end at a different time than they do.
