### ISSUE TITLE
Clicking the Select files button of the Upload will trigger a Form validation for the field.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1074]
Clicking the Select files button of the Upload will trigger a Form validation for the field.

This can be observed here: Clicking the Select files button of the Upload will trigger a Form validation for the field.

**Comment by kdikov82** [comment]
I have tried the scenario with version 5.11.0 and the validation is not triggered:
https://stackblitz.com/edit/react-yutese?file=app%2Fmain.jsx
