### ISSUE TITLE
NumericTextBox typing nonnumeric chars triggers change when the value is selected.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1075]
NumericTextBox typing non-numeric chars trigger change when the value is selected.

Retro steps using this example https://stackblitz.com/edit/react-eriqm7-r6ek4g?file=app/main.tsx

1. Focus NumericTextBox 

2. Type valid char (eg. number 1)

3. Select typed value

4. Press non-numeric character (eg. key 'd').

Result: Selected value is deleted and Change event was triggered with e.value == null

**Comment by kdikov82** [comment]
I am reopening the issue, because the same behavior is observed when you have selected the value and you press "-". It still clears the value, but pressing "-" again will set "-0" as the current value, which should be the result after the first time.

**Comment by kdikov82** [comment]
Related with #1042

**Comment by nstoychev** [comment]
The fix is available in the latest official version: https://github.com/telerik/kendo-react-private/releases/tag/v5.18.0
