### ISSUE TITLE
Using the "and" operator to render multi-column headers produce false columns.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#108]
Using the "and" operator to render multi-column headers produce false columns.

This can be observed here: https://stackblitz.com/edit/react-2b8ek7

We can think of an approach of how to optimize this use case. Currently, the column configuration can be kept in JSON array which will be modified based on the state values.

Any feedback and suggestions are welcomed.

**Comment by Xizario** [comment]
There is no solution for this, it is just invalid configuration. Passing 'false' for a column is not something we can handle.
