### ISSUE TITLE
Drawer title is not part of the messages.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1080]
Drawer title is not part of the messages.

We have added a title to the Drawer component in version 4.8.0, but it is not customizable. Each title has to be part of the component messages. The issue is that now this message is showing a tooltip over the component and the developer cannot set a more user-friendly message.

Connected with https://github.com/telerik/kendo-react/issues/962

**Comment by InaGlushkova** [comment]
Existing workaround:
https://stackblitz.com/edit/react-rakkfd?file=app/DrawerWorkaround.tsx
