### ISSUE TITLE
Bigger pageSize in Grid (virtual scroll) sometimes results in skipping of few top rows when scrollbar is dragged to top 

### ISSUE THREAD

**Issue by maiiaKey** [telerik/kendo-react#1081]
## I'm submitting a...

* Bug report 

## Current behavior

When using a grid with virtual scrolling and dynamic height (f.e. 100%) it is not possible to calculate the exact amount of visible items, however setting pageSize to more than the number of visible rows sometimes results in scrollbar jumping a few rows down when scrollbar is being dragged to the very top and released when mouse goes over the top of scrolling top arrow.
(From technical point of view skip returned by Grid in onPageChange event.page is > 0)
The issue occurs more often the bigger the pageSize is compared to height/rowHeight.

## Expected behavior

Since virtual scrolling is said to sometimes produce unexpected behavior when pageSize < number of visible items, the excepted behavior is that in all other cases (including pageSize > number of visible items) virtual scrolling produces no unexpected behavior.
So, if pageSize is set to > number of visible items expected behaviour is that dragging the scrollbar to the top scrolls the grid to the first row (skip returned in onPageChange event should be 0)  in all cases (including when scrollbar is released after mouse goes over the top arrow button).

## Minimal reproduction of the problem with instructions

Here is the demo for the issue: https://stackblitz.com/edit/react-oysy88?file=app/main.jsx
In the demo a grid with height 100% is used, but the issue is reproducible on static heights too.
The scrolling action that needs to be performed to reproduce the action is:
1. Grab the scrollbar and drag it slightly down 
2. Without releasing the scrollbar drag it all the way to the top and slightly over the top arrow
3. Repeat steps 1&2 until the scrollbar jumps 1 or few rows down resulting in the row at the top of the grid being different than the first item in the data (wrong skip returned). 

Static height:

https://user-images.githubusercontent.com/59762050/133278077-ce914b1e-20d7-4292-a5f0-4049d45cb1f3.mp4

Dynamic height with a bigger pageSize

https://user-images.githubusercontent.com/59762050/133278190-c260df43-bdd1-42b5-8501-895a79b69dc3.mp4

## What is the motivation or use case for changing the behavior?

The return of wrong skip when dragging the scrollbar may cause more visible issues, like instead of jupming scrollbar there will be empty space instead of first few rows in the grid:
![bug_variation](https://user-images.githubusercontent.com/59762050/133279835-c21e387c-3e61-4d06-b47f-b063b66fadfe.png)

## Environment

Package versions:

```
@progress/kendo-react-grid@3.18.0
```

Browser:

- Chrome (desktop) version 93.0.4577.63

System:
- TypeScript version: 1.0.3.0
- Node version: v14.15.4
- Platform:  Windows 

Might be related to #1013 although this issue was experienced in Chrome browser.

**Comment by nstoychev** [comment]
Fixed in version 5.10.0.

Note that grid's `rowHeight` prop is required now and the `pageSize`/`take` props need to be at least 2 times the count of the visible rows.
