### ISSUE TITLE
Grid with scrollable='none' and navigatable results in error.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1086]
Grid with scrollable='none' and navigatable results in error.

`Cannot read properties of undefined (reading '0')`

The issue can be observed here:

https://stackblitz.com/edit/react-yfu5wu?file=app/main.jsx

**Comment by simonssspirit** [comment]
reported again in 1549204

**Comment by nstoychev** [comment]
Fixed in a previous release - https://stackblitz.com/edit/react-yfu5wu-mzitem?file=app%2Fmain.jsx.
