### ISSUE TITLE
Provide a built-in drag and drop functionality of the Grid

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1088]
- [x] - Provide a [built-in](https://www.telerik.com/kendo-react-ui/components/utils/drag-and-drop/) drag and drop functionality

Demos:

- [x] Drag and drop of single/[multiple rows inside the same Grid](https://www.telerik.com/kendo-react-ui/components/grid/rows/row-reordering/#toc-multi-select-reordering).
- [ ] Drag and drop from single/multiple rows between Grids.
- [x] The user should be able to scroll the table using the mouse wheel to reach the bottom rows.
- [x] The table should auto-scroll when near the end of the visible table.

**Comment by aasigaaccenture** [comment]
Hi Kendo Team,

Good Day! Algie here from Nature's Bounty. Would just like to ask if you have a target start date on this issue?

Thanks in advance for your response.

Regards,
Algie Asiga

**Comment by simonssspirit** [comment]
Hello, Algie,

This is planned in two phases. First, we had to update our own drag and drop utility to support these functionalities. This is already on a pull request and it is being tested. After this is done, we will proceed to use it inside the Grid to achieve the listed requirements. 

As we spoke at the meeting, our aim is for this release cycle (September-January). Based on the current status of the related task, we are on the right track.

**Comment by aasigaaccenture** [comment]
Hi Simon,

Good Day! Thank you and apologies for this very late response. By the way, I can see that the Linked Pull Requests has something stated that "Successfully merging a pull request may close this issue." Does it mean you are nearing on the closure of this issue?

Regards,
Algie Asiga

**Comment by simonssspirit** [comment]
@aasigaaccenture Yes, the second phase is already on a pull request as well and you can expect a demo that uses [our new drag and drop functionality](https://www.telerik.com/kendo-react-ui/components/utils/drag-and-drop/) to cover the requirements listed in the issue.

**Comment by simonssspirit** [comment]
@aasigaaccenture We have just made a demo in the develop site with the new drag and drop functionality:

https://www.telerik.com/kendo-react-ui-develop/components/grid/rows/row-reordering/

Please give it a try and advise if it covers the requirement and if there is something missing, please demonstrate which part specifically is missing.

**Comment by aasigaaccenture** [comment]
@simonssspirit  We did give it a try and we are good on the scrolling. 
By the way, would just like to ask if the fix includes the multi select scenario. 
If yes, can you also give us a demo on that one? We cant execute multi select on the current demo site.

Thanks in advance for your response.

Regards,
Algie Asiga

**Comment by aasigaaccenture** [comment]
Hi @simonssspirit,

Good Day! Would just like to follow up on our inquiry above if its possible on your end to give us a demo on Multi-Select scenario.

Thanks!

Regards,
Algie Asiga

**Comment by simonssspirit** [comment]
@aasigaaccenture apologies for the late response we are short-staffed during the holidays.

This will be possible yes, we can plan a demo on this as well next month.

@kspeyanski

**Comment by aasigaaccenture** [comment]
Hi @simonssspirit,

Good Day! Apologies for the late response. Yeah, it's actually fine. 
We will just wait for you then to come up on that multi-select scenario demo.

Happy New Year, by the way.

Thanks!
Algie

**Comment by aasigaaccenture** [comment]
Hi @simonssspirit ,

Good Day! Hope everything is well on your end. Would just like to get an update on this one? Is it possible for this demo to be given to us this month?

Thanks!

Regards,
Algie Asiga

**Comment by simonssspirit** [comment]
Hello, @aasigaaccenture,

As we just had the release, we will probably be focused on the release-related tasks after it. We will most probably start working on it after that.

@kspeyanski can also share information on a possible ETA after we start it.

**Comment by aasigaaccenture** [comment]
Hi @simonssspirit ,

Good Day! May we know the target date or ETA of our request?

Thanks in advance for your response.

Regards,
Algie Asiga

**Comment by aasigaaccenture** [comment]
Hi @simonssspirit,

Good Day! Would just like to ask if where are we now on this request of ours?

Thanks!

Regards,
Algie Asiga

**Comment by simonssspirit** [comment]
The example is almost ready, we are testing all different cases to ensure we are covering the requirements.

**Comment by simonssspirit** [comment]
We really apologize for the very large delay. We hit some issues during the testing and we are working on fixing them. This is a top priority for the assigned engineer and we will share the example as soon as it is ready.

**Comment by aasigaaccenture** [comment]
Hi @simonssspirit ,

Good Day! Do we have a  target date on this one? The business wants to know on the state of the request or on when can we get the demo.

Thanks!

Regards,
Algie Asiga

**Comment by simonssspirit** [comment]
The example is already available on the dev site. It uses the features from the official version, so you should be able to achieve it with version 5.2.0 as well:

https://www.telerik.com/kendo-react-ui-develop/components/grid/rows/row-reordering/#toc-multi-select-reordering

**Comment by aasigaaccenture** [comment]
Hi Simon,

Good Day! Hope all is well on your end. The team is now trying to implement this feature on our end.
Anyways, would just like to ask if this feature also works on the scenario of dragging and dropping from one grid to another grid?

Thanks!

Regards,
Algie Asiga

**Comment by simonssspirit** [comment]
> Hi Simon,
> 
> Good Day! Hope all is well on your end. The team is now trying to implement this feature on our end. Anyways, would just like to ask if this feature also works on the scenario of dragging and dropping from one grid to another grid?
> 
> Thanks!
> 
> Regards, Algie Asiga

@kspeyanski @filipKovachev Could you please take a look at this scenario.

**Comment by aasigaaccenture** [comment]
Hi @simonssspirit,

Good Day! Would just like to follow up on our inquiry above.

One of the requirement state about,
1. Drag and drop from single/multiple rows between Grids.

So would just like to confirm on your end if this solution covers one grid to another. If yes, do you have any sample of it?

Thanks!

Regards,
Algie Asiga

**Comment by filipKovachev** [comment]
Thank you for the provided requirement clarification. This scenario is possible and we are currently working on an example that will showcase this behavior.  I will post it here once it is ready.

Regards,
Philip

**Comment by aasigaaccenture** [comment]
Thanks for your response @filipKovachev . Will wait for your sample.

Regards,
Algie Asiga

**Comment by aasigaaccenture** [comment]
Hi @filipKovachev ,

Good Day! Hope everything is well. Do we have an update on this request of ours?

Thanks.

Regards,
Algie Asiga

**Comment by filipKovachev** [comment]
Hello, Algie,

We are experiencing some issues that need to be fixed, we will share the example as soon as it is ready. This is currently a top-priority task for me.

Regards,
Philip

**Comment by aasigaaccenture** [comment]
Hi @filipKovachev 

Thanks for your response. Will wait for your sample then.

Regards,
Algie Asiga

**Comment by aasigaaccenture** [comment]
Hi @filipKovachev ,

Good Day! Any updates on the sample?

Regards,
Algie Asiga

**Comment by filipKovachev** [comment]
Hi @aasigaaccenture,

The sample is ready and it can be found here:

https://stackblitz.com/edit/react-kkucf8-sqcmsj?file=app/main.tsx

Regards,
Filip
