### ISSUE TITLE
Double click on the Grid column resize handler is cause the column to shring to 0 px

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1089]
Double click on the Grid column resize handler causes the column to sharing to 0 px. This occurs only on Safari:

https://www.telerik.com/kendo-react-ui/components/grid/columns/resizing/

**Comment by vladimirivanoviliev** [comment]
In latest Safari `getBoundingClientRect` started reporting 0px which seems as a bug. The issue is workarounded and the fix will be available in next few days in dev channel.
