### ISSUE TITLE
Ability to render the pager or another Grid component on customization position.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#109]
Based on a couple of requests about rendering the Grid pager at the top.

We have a couple of solutions which we need to evaluate:

1) Expose a Pager component - This will allow the user to place the pager at the desired place.
2) Have a setting for the pager - bottom, top and both. The issue here is where to place the pager, on the top of the Grid over the toolbar, the grouping header or below them.
3) Exposing a render prop for the Grid which will allow customizing the Grid elements, their order and it will allow cloning them and placing them on the desired place.

**Comment by vladimirivanoviliev** [comment]
`Pager` component is officialy released and can be used to customize it's position in the Grid:
- https://www.telerik.com/kendo-react-ui/components/datatools/pager/
