### ISSUE TITLE
A Key prop warning is shown if there are two duplicate values in the ChipList data.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1090]
A key prop warning is shown if there are two duplicate values in the ChipList data:

https://stackblitz.com/edit/react-5kyivb-dxrexr?file=app/main.tsx

Even if each item has a different key. This occurs as we internally wrap this inside an internal component that uses a key based only on the value:

````
              {data.map((item) => {
                            return (
                              <ChipComponent
                                role={'option'}
                                dataItem={item}
                                key={item[props.valueField || defaultProps.valueField]
````

**Comment by silviyaboteva** [comment]
Fixed in `v5.1.0-dev.202202101059`.
