### ISSUE TITLE
Grid group aggregates do not work

### ISSUE THREAD

**Issue by Gillibald** [telerik/kendo-react#1093]
* Bug report 

## Current behavior
There are no group footers at all. There is also no way to customize the group footer etc.
There is an example here: https://www.telerik.com/kendo-react-ui/components/grid/grouping/grouping/ but that doesn't work. It looks like this was never implemented.

## Expected behavior

The group footer should show up and there should be a way to customize it in the same way the footer row is customizable.
https://www.telerik.com/kendo-angular-ui/components/grid/grouping/aggregates/
## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by kdikov82** [comment]
The group footers are not available:
https://stackblitz.com/edit/react-yxrqjg?file=app%2Fmain.jsx
