### ISSUE TITLE
Infinite scroll with virtualization

### ISSUE THREAD

**Issue by araasryan** [telerik/kendo-react#1096]
## I'm submitting a...

* Bug report 

I made an example of Infinite scroll with `scrollMode="virtual"`
https://stackblitz.com/edit/react-dc7vv7?file=app/main.tsx

At first, it seems to work, but while scrolling there are some cases where the scroll will jump to the top.
The `fixedScroll` prop is set to true.

I'm using Macbooks Trackpad to scroll.

**Comment by nstoychev** [comment]
Resolved in 5.12.0

Example: https://stackblitz.com/edit/react-dc7vv7-aix2eb?file=app%2Fmain.tsx.
