### ISSUE TITLE
Scrolling DropDownList items using scrollbar doesn't work in IE11

### ISSUE THREAD

**Issue by georgeri** [telerik/kendo-react#11]
## I'm submitting a...
* Bug report

## Current behavior
Scrolling DropDownList items using scrollbar doesn't work in IE11 in kendo-react-dropdowns DropDownList.

## Expected behavior
User should be able to use the dropdownlist's scroll bar to scroll through the items in IE11.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/EhrJMld2Zn6skN5ytQS8
This is reproducible on the "Basic Usage" demo code in https://www.telerik.com/kendo-react-ui/components/dropdowns/
1. Click on the dropdown so that the item list pops up, 
2. Click on the scrollbar in the item list and try to scroll down
Expected: item list scrolls 
Actual: the item list popup closes.

## What is the motivation or use case for changing the behavior?
It is a bug that affects user experience as it limits user to either use mouse scroll wheel or up and down arrow keys to scroll through list items in IE11.

## Environment
Reproducible on the latest demo code at https://www.telerik.com/kendo-react-ui/components/dropdowns/ 
Package versions:
progress/kendo-data-query: ^1.2.0,
progress/kendo-dateinputs-react-wrapper: ^2018.1.131,
progress/kendo-react-dropdowns: ^0.3.0,
progress/kendo-react-layout: ^0.3.0,
progress/kendo-ui: ^2018.1.117,

Browser:

- IE version 11 (11.0.9600.18893)

System:
- Node version: v6.11.5,  3.10.10(npm)
- Platform:  Windows 7 Professional SP1.

**Comment by nstoychev** [comment]
@georgeri - Fixed in `v0.5.0-dev.201803220834`.
Please refer to the [this article](https://www.telerik.com/kendo-react-ui/components/installation/development-builds/) on how to obtain the development builds.
