### ISSUE TITLE
Clicking MultiSelect the add custom value button does not add the value every time.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1102]
Clicking MultiSelect the add custom value button does not add the value every time:

https://www.telerik.com/kendo-react-ui/components/dropdowns/multiselect/custom-values/

In most cases, the list is closed, before the click is completed. This results in closing the list before the custom value is added to the component.

More details with a video can be found in ticket 1538730

**Comment by InaGlushkova** [comment]
The fix is introduced with version [v4.11.0](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#be637ab5-74d0-5d30-b4cb-ecf78c7a32f2)
