### ISSUE TITLE
SVG is not exported to PDF on Firefox

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1103]
SVG is not exported to PDF on Firefox

https://stackblitz.com/edit/react-yfmvuw?file=app/main.jsx

The SVG is correctly exported on Chrome.

**Comment by tsvetomir** [comment]
Fixed in @progress/kendo-drawing 1.16.1, see [updated demo](https://stackblitz.com/edit/react-yfmvuw-ud1xq6?file=app/main.jsx).
