### ISSUE TITLE
Stacked Area Chart incorrect result when one of the series has negative values.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1104]
Stacked Area Chart incorrect result when one of the series has negative values:

https://stackblitz.com/edit/react-frxi5s?file=app/main.jsx

**Comment by kdikov82** [comment]
I do not see correlation with the negative values since the same result can be observed with positive values only:
https://stackblitz.com/edit/react-frxi5s-6i3xvj?file=app%2Fmain.jsx

I can also see the current behavior as correct for some scenarios. @nstoychev @zdravkov any opinion on this?

**Comment by tsvetomir** [comment]
This is the expected behavior for stacked area series. See reference from MS Excel:
<img width="604" alt="image" src="https://user-images.githubusercontent.com/247917/221638906-fd7124b7-2bb3-45b3-87b3-7e479f2a6950.png">

Removing stacking will display negative values separately.
