### ISSUE TITLE
Provide an option to select the DateInputs value on double click

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1111]
Provide an option to select the DateInputs value on double click.

This will allow the end-user to easily select the full date for copy or paste.

**Comment by iadnonov** [comment]
The KendoReact  DateInput provides an option for selecting the segment of the date on double click and enabling the whole date selection will automatically turn off this feature. 
Currently, the date value can be selected using a native triple click or the keyboard combination of `Ctrl/Cmd + A`, which are effective alternatives for achieving the same functionality.
