### ISSUE TITLE
Scheduler - "Controlling the Editing" example throws error on drag

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1117]
[https://www.telerik.com/kendo-react-ui/components/scheduler/customization/items/edit-item/#toc-controlling-the-editing](https://www.telerik.com/kendo-react-ui/components/scheduler/customization/items/edit-item/#toc-controlling-the-editing)

In some cases "event.value" is undefined, which throws an error at "event.value.start":

    if (
      event.value === null ||
      (minWorkHour <= event.value.start.getUTCHours() &&
        event.value.end.getUTCHours() < maxWorkHour &&
        minWorkDate <= event.value.start.getUTCDate() &&
        event.value.start.getUTCDate() <= maxWorkDate)
    ) {
      setDragItem(event.value);
    }

Should be changed to:
```
      if (
        event.value === null ||
        event.value === undefined ||
```

or 
```
      if (
        !event.value ||
```

**Comment by kspeyanski** [comment]
The issue has been fixed in version `4.11.1` of the `@progress/kendo-react-scheduler` package.

Please refer to the changelog for the full list of changes in this version:
https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#be637ab5-74d0-5d30-b4cb-ecf78c7a32f2
