### ISSUE TITLE
Add the ability to load local data in the PivotGrid.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1119]
Add the ability to load local data in the PivotGrid.

Currently, the data can be loaded only from a Cube.

**Comment by nstoychev** [comment]
Published in develop channel - https://www.telerik.com/kendo-react-ui-develop/components/pivotgrid/data-binding/local-binding/.

**Comment by oreznichenko** [comment]
@nstoychev is it under development now ? The code provided in the article invalid since local binding is not defined in 4.13 version

**Comment by nstoychev** [comment]
@oreznichenko - It is ready but not officially published yet. You can install it by adding `dev` tag at the end of the package name:

```npm install @progress/kendo-react-pivotgrid@dev```

See also the following article for obtaining our development builds - https://www.telerik.com/kendo-react-ui/components/installation/development-builds/.

If you have any feedback, feel free to share it.
