### ISSUE TITLE
Style property is ignored for NumericTextBox

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1120]
version 4.9.0

The "style" property does not render anything in the NumericTextBox wrapper nor in the input element:
https://stackblitz.com/edit/react-urdngr?file=app/main.jsx

Might be a good idea to consider adding inputStyle property as well, which could add style directly to the input element.

**Comment by vladimirivanoviliev** [comment]
Currently the `className` prop can be used to apply custom styles to the NumericTextBox.
