### ISSUE TITLE
columnMenu not rendering when headerCell is specified in GridColumn component

### ISSUE THREAD

**Issue by thebetternewt** [telerik/kendo-react#1123]
## I'm submitting a...

* Regression report 

## Current behavior

In `@progress/kendo-react-grid@4.10.0`, the `columnMenu` prop/component for a `<GridColumn>` is never rendered in the case that a `headerCell` prop is also specified.

## Expected behavior

In `v4.9.0` and prior, the `columnMenu` would still be rendered if specified, even when a custom `headerCell` was specified.

## Minimal reproduction of the problem with instructions

See the first column here: 

<https://stackblitz.com/edit/react-mtbmdq?file=app/main.tsx>

Added a custom `headerCell` and the `columnMenu` isn't rendering.

## What is the motivation or use case for changing the behavior?

We want to be able to specify both a custom header cell and a column menu component.

## Environment

Package versions:

```
// See StackBlitz link
```

Browser:

- Chrome (desktop) version 94.0.4606.81
- Edge version 95.0.1020.30

System:
- TypeScript version: 4.3.5
- Node version: Node v14.17.3, npm v7.20.0
- Platform:  Linux/Windows

**Comment by kdikov82** [comment]
Reported again in Ticket ID: 1543120

**Comment by simonssspirit** [comment]
this can be connected with https://github.com/telerik/kendo-react/issues/957.

We can fix this issue by providing the icon as the props.children. This will provide a fix to this issue and allow the requested customization in issue number 957.

**Comment by vladimirivanoviliev** [comment]
The change in question was related to fix for our columns header which required different rendering. This new rendering required the column menu to be moved inside the default header cell, which is the reason for current behavior. For your convenience we exposed the `GridColumnMenuWrapper` component which can be used to show the column menu inside your custom header cell renderer:
- https://www.telerik.com/kendo-react-ui-develop/components/grid/api/GridColumnMenuWrapper/
- https://www.telerik.com/kendo-react-ui-develop/components/grid/api/GridHeaderCellProps/#toc-columnmenuwrapperprops

Here is small example:
```
              <Column
                field="UnitPrice"
                filter={'numeric'}
                headerCell={(props) => {
                  return <>{props.field}<GridColumnMenuWrapper {...props.columnMenuWrapperProps} /></>;
                }}
              />
```
