### ISSUE TITLE
Props through React.Context

### ISSUE THREAD

**Issue by kspeyanski** [telerik/kendo-react#1126]
The `Props Context` feature is currently available for:
- [x] [`@progress/kendo-react-dateinputs`](https://www.telerik.com/kendo-react-ui-develop/components/dateinputs/props-context/)
- [x] [`@progress/kendo-react-inputs`](https://www.telerik.com/kendo-react-ui-develop/components/inputs/props-context/)
- [x] [`@progress/kendo-react-dropdowns`](https://www.telerik.com/kendo-react-ui-develop/components/dropdowns/props-context/)
- [x] `@progress/kendo-react-dialogs`

---

As many of you know, most KendoReact components render multiple internal components, which are hidden by the end user. For example, the `Grid` component would render multiple components like `DropDowns`, `DatePickers` etc. While some of the internal components are accessible through a `render prop` (e.g. the [`cell`](https://www.telerik.com/kendo-react-ui/components/grid/api/GridColumnProps/#toc-cell) property of the `GridColumn`), others are deeply nested in the tree and hardly customizable.

We want to overcome this limitation through introducing per-component `React.Context` which can be utilized to override the properties of a deeply nested component.

Please let us know what you think&mdash;any feedback would be greatly appreciated. 

## Previous exploration
With [`v4.2.0`](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#f91bd6b1-d1ea-53d1-98cc-48c0148cf6b9) of the `@progress/kendo-react-popup` package, we've introduced the [`PopupPropsContext`](https://www.telerik.com/kendo-react-ui/components/popup/global-context/) and we've received positive feedback with it &mdash; now we want to do this for most of the KendoReact components.

## Syntax
We're happy with how the `PopupContext` behaves, as we're providing a `function`  as a value, which should return the new props, instead of passing an `object`. This allows us to provide dynamic properties, based on the other properties of the component, or state variables:
```jsx
<PopupPropsContext.Provider 
    value={(props) => ({ 
        ...props, 
        appendTo: state.shouldAppendToBody && props.animate
                ? document.body 
                : null 
            })
    } 
/>
```

The Context value can further be memoized through `React.useCallback` in functional components:
```jsx
const popupProps = React.useCallback(
    (props) => ({ 
        ...props, 
        appendTo: state.shouldAppendToBody && props.animate
                ? document.body 
                : null 
     }),
    [state.shouldAppendToBody]
)
// ...
<PopupPropsContext.Provider value={popupProps}>
```

## Sample usage
The usage is pretty straight forward&mdash;Every single occurrence of the said `component` underneath the `context` will receive the defined properties.

```jsx
<PopupPropsContext.Provider value={(props) => ({ ...props, appendTo: document.body })}>
    <DatePicker />
</PopupPropsContext.Provider>
```

With the above code, the `Popup`(rendered internally by the `DatePicker`) will receive the new `appendTo` property. Scaling this to a more-complex tree structure, might look like this:

```jsx
const Sidenav = () => {
    render (
        // ... other components
        <DatePicker />
    )
}
const App = () => {
    return (
        <PopupPropsContext.Provider value={(props) => ({ ...props, appendTo: document.body })}>
            <Header />
            <main>
                <Sidenav />
                <Content />
            </main>
            <Footer />
        </PopupPropsContext.Provider>
    );
```

## ~~Props priority~~ **EDIT**: Check discussion in the comments
~~The above example will render all `Popup` components to the `document.body` element, unless a specific `Popup` has directly defined `appendTo` prop. The properties should have the following priority~~

1. Directly set properties&mdash;
```jsx
<Popup appendTo={document.body} />
```
2. Closest Context Inherited property
```jsx
<PopupPropsContext.Provider value={(props) => ({ ...props, appendTo: document.body })}>
    // ...
    <Popup />
    // ...
 </PopupPropsContext.Provider>
```
3. Default component properties (defined internally)
```jsx
Popup.defaultProps ={ 
    appendTo: document.body
}
```

**Comment by kspeyanski** [comment]
The `Props Context` features have been added in the latest `dev` version of the `dateinputs`, `inputs` and `dropdowns` packages. Please refer to the full changelog for a detailed list of supported components: https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/

We will be updating this issue with more packages as we implement them.

**Comment by kdikov82** [comment]
Since all tasks in this issue are completed, I am closing it. If new ideas or requests arise, we can open separate issues.
