### ISSUE TITLE
Scheduler repeat on Day X input reset on blur.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1129]
Scheduler repeat on Day X input reset on blur:

![image](https://user-images.githubusercontent.com/11087921/139662988-c146ebe0-2440-455d-8bb4-41629e737dd7.png)

After changing the input value and leaving the input, the value is reset to 1.

**Comment by kspeyanski** [comment]
The issue has been fixed in version `4.11.1` of the `@progress/kendo-react-scheduler` package.

Please refer to the changelog for the full list of changes in this version:
https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#be637ab5-74d0-5d30-b4cb-ecf78c7a32f2
