### ISSUE TITLE
IE 9. Unable to get value of the property 'badInput': object is null or undefined

### ISSUE THREAD

**Issue by andalt** [telerik/kendo-react#113]
```
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/shim';
import 'raf/polyfill';

import React from 'react';
import { Input } from '@progress/kendo-react-inputs';

const Search = () => (
    <div className="row">
        <div className="col-xs-6">
            <Input />
        </div>
    </div>
);

export default Search;
```

--------------------------------------

"@progress/kendo-react-inputs": "^2.3.1",

![2018-11-01_14 49 35_o7iqb](https://user-images.githubusercontent.com/8655528/47850193-84cbd400-dde5-11e8-8e18-fcd213dcf4f6.png)

**Comment by vladimirivanoviliev** [comment]
I tested the following polyfill and it worked on our side:

- https://css-tricks.com/form-validation-part-3-validity-state-api-polyfill/
