### ISSUE TITLE
Scheduler incorrect Day/Month Labels on fixed timezone

### ISSUE THREAD

**Issue by kspeyanski** [telerik/kendo-react#1131]
The scheduler is rendering incorrect labels on the `Day` and `Month` view, due to incorrect parsing of the `date` and `time` parts with `Date` object, instead of `ZonedDate`. The `slots` and `items` are unaffected and show correct `aria-label` properties.

![image](https://user-images.githubusercontent.com/30626787/140701136-4ff1a053-c75a-425a-9e56-2fb34c0ebe2a.png)

**Comment by Mathdrquinn** [comment]
@kspeyanski thank you for creating the issue.  I too found the slots to have the correct values associated with them.
[Here is a link to the stackblitz](https://stackblitz.com/edit/react-wagauk?file=app/main.jsx) which will reproduce the issue.

**Comment by kspeyanski** [comment]
@Mathdrquinn Thank you for the additional example. It's somewhat easier to fix the formatting, than to fix the timezone calculations for the slots, so this shouldn't take too long.

We already have a fix ready to be deployed and we're running a QA pass before publishing it to the latest `dev` version.

Will update the issue once the update is available.

**Comment by kspeyanski** [comment]
The issue has been fixed in version `4.11.1` of the `@progress/kendo-react-scheduler` package.

Please refer to the changelog for the full list of changes in this version:
https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#be637ab5-74d0-5d30-b4cb-ecf78c7a32f2

**Comment by Mathdrquinn** [comment]
@kspeyanski thank you for the update 🥳
