### ISSUE TITLE
Problem with <GridColumnMenuCheckboxFilter /> and submit filter without any selection

### ISSUE THREAD

**Issue by buglessir** [telerik/kendo-react#1133]
I'm using `"@progress/kendo-react-grid": "3.14.0",` to implement a grid for our React application.
In this grid we have used `<GridColumnMenuCheckboxFilter />` to implement a Multi-Select filter for a specific column. This filter works without any error when I select one or multi checkboxes of the list and by clicking on the Filter button... but it has error when I un-select all previous selected checkboxes and click on the Filter button without any selected checkboxes:

![Error](https://i.imgur.com/RmpKycb.jpg)

I think this feature has a bug and after reset (un-select) active filters doesn't find field's property to handle grid's data without filter...

**Comment by simonssspirit** [comment]
@buglessir  This is working in the latest version: https://www.telerik.com/kendo-react-ui/components/grid/columns/column-menu/

Please confirm if the issue still occurs in the latest version>
