### ISSUE TITLE
Inside Shadow DOM - Grid column reordering doesn't work

### ISSUE THREAD

**Issue by xarety** [telerik/kendo-react#1136]
## I'm submitting a...

* Bug report 

## Current behavior
Column reordering in the KendoReact Data Grid doesn't work in the Shadow DOM.

## Expected behavior
Column reordering in the KendoReact Data Grid does work in the Shadow DOM.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-sq2mck?file=app/main.jsx

## What is the motivation or use case for changing the behavior?
https://github.com/telerik/kendo-react/issues/626

```
Browser:
- Chrome (desktop) version 95.0.4638.69 
- Safari (desktop) version 15.1 (17612.2.9.1.20)
```

**Comment by xarety** [comment]
The same issue is with grouping.

**Comment by simonssspirit** [comment]
@xarety The issue is still in our DoTo list and is not officially planned.

**Comment by kdikov82** [comment]
Works correctly with the latest versions (tested with 5.11.0):
https://stackblitz.com/edit/react-sq2mck-tcz3cs?file=package.json,app%2Fmain.jsx

**Comment by majakudlicka** [comment]
I can see that column reordering now works with the shadow DOM 🎉  Grouping still does not seem to work though 😞 

https://stackblitz.com/edit/react-sq2mck-nvbqrf?file=app%2Fmain.jsx
