### ISSUE TITLE
TypeScript typings of Typography component not working as expected

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1139]
When passing a nonexistent property as fontSize in the Typography component, the build should fail, but currently, it does not. 

Ticket ID for reference: 1542725

**Comment by Xizario** [comment]
Please elaborate how this is a bug.
From what I see the property have correct Type and PropTypes. and I do see warning in both js and ts world.

**Comment by PieterBoeren** [comment]
Code like:

`<Typography.h4 fontSize={"xssssssmall"}>Headline 4</Typography.h4>`

compiles fine, but the font-size is not defined in the "TypographyProps" interface:

`fontSize?: 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge';`
