### ISSUE TITLE
DatePicker with MultiViewCalendar as custom calendar fails to change view after a value is selected

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1140]
version 4.10.0
Example replicating the issue:
https://stackblitz.com/edit/react-wvdnwu?file=app%2Fmain.jsx

Steps to reproduce: 
1) Select value from the MultiViewCalendar
2) Open the MultiViewCalendar and click on the "month year" 
3) Select different from the currently selected date month
4) The days view will be for the month of the selected date and not the newly selected month

**Comment by kspeyanski** [comment]
The issue has been fixed in version `4.11.1` of the `@progress/kendo-react-dateinputs` package.

Please refer to the changelog for the full list of changes in this version:
https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#be637ab5-74d0-5d30-b4cb-ecf78c7a32f2
