### ISSUE TITLE
Grid onColumnReorder event contains the old order of the columns

### ISSUE THREAD

**Issue by vladimirivanoviliev** [telerik/kendo-react#1142]
After investigation regarding the below ticket it seems that the `onColumnReorder` does not contain the latest order of the columns. Please check the following demo where the state does not correspond to the rendered columns:

https://stackblitz.com/edit/react-qn73g9-7dnz3z?file=app/main.jsx

Ticket: 1542599

**Comment by Xizario** [comment]
They are in the same order. Visually they differ by their OrderIndex
