### ISSUE TITLE
Title attribute causes tooltip to appear in the Drawer component

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1145]
When hovering over an item in the Drawer component, а tooltip appears. It is caused by the `title` attribute in the `ul` element. 
Replacing the `title` attribute with the `aria-label` instead will solve the tooltip issue but still do not cause an accessibility issue.

TicketID: 1543700

**Comment by silviyaboteva** [comment]
Duplicate of https://github.com/telerik/kendo-react/issues/1080
