### ISSUE TITLE
Scheduler preselects previous day instead of the one selected when user's timezone is CST and one set is UTC

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1146]
When trying to create a new event on Tuesday, before 6AM and then select Repeating Weekly, the preselected days is Monday instead of Tuesday.

Ticket: 1544138

**Comment by kspeyanski** [comment]
The issue has been fixed with version `4.13.0` of the `@progress/kendo-react-scheduler` package. For the full list of changes please refer to the changelog: https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#9400a842-ffe7-52e2-b647-15d16143e9c2
