### ISSUE TITLE
[Inputs] w3c validation errors for MultiSelect and DatePicker

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1149]
version 4.12.0

1) DatePicker is adding "autocorrect" attribute which gives:
_Error: Attribute autocorrect not allowed on element input at this point._
![_picker](https://user-images.githubusercontent.com/11787141/143575323-25476174-2721-4521-89bd-4c427e171147.png)
 

- [X] 2) MultiSelect is rendering DIV elements within SPAN elements:

_Error: Element div not allowed as child of element span in this context._
![_multiselect](https://user-images.githubusercontent.com/11787141/143575326-e5e2a65e-eb43-4fb0-829f-076985ef30c7.png)

**Comment by kdikov82** [comment]
The MultiSelect issue is resolved, but both components still render "autocorrect" attribute

**Comment by PekoPPT** [comment]
The "autocorrect" issue is no longer replicable while testing KendoReact version 5.17.0 + AXE 4.7.2:
- DropDownList -  https://codesandbox.io/s/bold-http-mwr7pp
- DatePicker - https://codesandbox.io/s/jolly-sky-gwn6t4
