### ISSUE TITLE
OnClick event gets triggered twice in the Chip component

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1150]
When adding an onClick event in the Chip component, the event gets fired twice:

https://stackblitz.com/edit/react-fdzbra?file=app/main.jsx

Ticket ID: 1544333

**Comment by InaGlushkova** [comment]
Introduced with version [4.13.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#9400a842-ffe7-52e2-b647-15d16143e9c2).
