### ISSUE TITLE
Scheduler: adding a new recurring event after 6pm while being in CST timezone omits last day of the week

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1153]
When using the Scheduler component and the timezone on your machine is CST, setting a recurring event after 6 pm does not show up for the last day of the week.

Ticket ID: 1544138

**Comment by kspeyanski** [comment]
The issue has been fixed with version `4.14.0` of the `@progress/kendo-react-scheduler` package. For the full list of changes please refer to the changelog: https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#a04c4700-cebf-570e-8b74-a1601f6ddc15
