### ISSUE TITLE
Issue with DropdownList virtualization with filtering demo with Hooks

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-react#1156]
There is an issue with the virtualization with filtering demo only with Hooks approach. If you filter the items, let's say these containing '33' and try to scroll, the items start from Item 0. The demo with classes works as expected.

Demo link: https://www.telerik.com/kendo-react-ui/components/dropdowns/dropdownlist/virtualization/#toc-virtualization-with-filtering

cc/ @simonssspirit @filipKovachev

**Comment by simonssspirit** [comment]
This should be the working version: https://stackblitz.com/edit/react-yoie5s?file=app/main.jsx

@silviyaboteva @nstoychev Please confirm

**Comment by silviyaboteva** [comment]
@simonssspirit yes, it's working fine in the example. Can you please update the docs with it? :)

**Comment by simonssspirit** [comment]
Yes, I will update it for the ComboBox and the MultiSelect as both of them, have the same issue.

**Comment by simonssspirit** [comment]
The article is fixed
