### ISSUE TITLE
RTL issue in Stepper component

### ISSUE THREAD

**Issue by shiffyB** [telerik/kendo-react#1159]
Hi,
I am using the Stepper component from  "@progress/kendo-react-layout"
and I am facing a problem of inconsistency when showing the Stepper in RTL mode. 

I assigned the "rtl" property to the component by setting  dir="rtl"(as documented):
```
<Stepper
        value={value}
        items={items}
        onChange={handleChange}
        dir="rtl"/>

```
The issue is that the "rtl" prop only impacts the steps but doesn't impact the progress-bar. which looks pretty bad. 
as you can see in attached image: (this happens when changing the valu to the third step)
![image](https://user-images.githubusercontent.com/62942456/145845036-482500b3-2223-4598-8879-fd56aabf78b3.png)

what I did in order to fix this issue was adding a rotate of 180deg to the progress-bar:
.rtl  .k-progressbar-horizontal {
    transform: rotate(180deg);
}
which gave me the expected result:
![image](https://user-images.githubusercontent.com/62942456/145847326-f9e7b26c-d1cf-499a-adbe-5c989d692b6a.png)

this fix should be very simple and easy for you to fix. and I think it is very important for all the RTL users.

* Bug report 

## Expected behavior
I expect the component to be fully adjusted for RTL users.

## Environment

Package versions:
+-- @progress/kendo-react-layout@4.13.0

Browser:
- Chrome (desktop) version 96.0.4664.93

System:
- TypeScript version: 3.6.4
- Node version: v14.16.0.
- Platform:  Windows

Thank you!!

**Comment by InaGlushkova** [comment]
The issue is fixed under the current newest version - [v5.0.1](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#cebe5817-9fae-5728-8745-00f4c1547df3)

Example reference:
https://stackblitz.com/edit/react-ghevcp?file=app/main.jsx
