### ISSUE TITLE
DatePicker & TimePicker - Manual keyboard input issue.

### ISSUE THREAD

**Issue by citems** [telerik/kendo-react#116]
## I'm submitting a...

* Suggestion for improvement

## Current behavior

Using the demo from the documentation, once a time is set, it becomes difficult to change the hour or minute via the keyboard (using the keypad).  The arrow keys work flawlessly, but as an example, if we have 10:30 freshly set via the set button (in its drop-down), I can type two keystrokes and it'll keep.  However, once set by the keystrokes, if I return focus on the minute and type two new digits/keystrokes, it only accepts the first digit/keystroke and loses focus.

## Expected behavior

Allow two digit keystrokes to be accepted and retained before losing focus or advancing to the next option.

## Minimal reproduction of the problem with instructions

https://www.telerik.com/kendo-react-ui/components/dateinputs/timepicker/
https://www.telerik.com/kendo-react-ui/components/dateinputs/datepicker/

## What is the motivation or use case for changing the behavior?

Manual override of hour and time without invoking the popup panel

## Environment

Package versions:

```
2.3.1
```

Browser:

- Chrome (desktop) version XX

**Comment by Xizario** [comment]
Fixed in `3.0.0`
