### ISSUE TITLE
Add "sideEffects" property to package.json

### ISSUE THREAD

**Issue by xarety** [telerik/kendo-react#1162]
## I'm submitting a...
* Suggestion for improvement

## What is the motivation or use case for changing the behavior?

Webpack is experiencing issues with tree shaking in the case of the React libraries with a single entry point that exports all internals. So the `sideEffects` will help to solve these issues with tree shaking. We've significant bundle size changes in our project when adding this property to your packages.

In this [repository](https://github.com/xarety/tree-shaking), you can find that the `Bar` component hasn't been tree shaken:
https://github.com/xarety/tree-shaking/blob/master/dist/main.js#L18

For reference information:
https://blog.theodo.com/2021/04/library-tree-shaking/

**Comment by kspeyanski** [comment]
Thank you @xarety 

Indeed having the `sideEffects` field set to `false` makes sense for the `kendo-react-*` packages. We will further proceed with double checking to confirm that there are no side effects and add the field.

As the checking process is manual, we can not provide an estimate on when this will be available, but we will do our best to publish a version containing them soon.

**Comment by kspeyanski** [comment]
Hello @xarety 

We've added the `sideEffects` filed to all `kendo-react-*` packages with the latest `v4.14.0@dev` version.

Please refer to the changelog for the full list of changes in this version:
https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#1773ccac-4847-567a-a5fe-ad07fa10bef7

And to the `Obtaining Development Release` article for additional instructions on how to get the `dev` version:
https://www.telerik.com/kendo-react-ui/components/installation/development-builds/

I will be leaving this issue Open until we've deployed the changes to the `latest` version of the packages, but please let us know if you encounter any issues and we will do our best to address them in a timely manner.

**Comment by xarety** [comment]
Thank you so much!
