### ISSUE TITLE
Change the DropDownButton item role from menuItem to menuitem

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1163]
Change the DropDownButton item role from `menuItem` to `menuitem`. All letters should be lowercase:

https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html

![image](https://user-images.githubusercontent.com/11087921/146497666-42eb1cbe-4ef1-4f80-84a1-cbabc86c5dbc.png)

**Comment by nstoychev** [comment]
Fixed in [v5.0.2-dev.202201241659](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#00162092-d567-545e-a9da-5ce74d2f080a).
