### ISSUE TITLE
Add the missing @progress/kendo-react-buttons dependency to the @progress/kendo-react-inputs package

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1169]
Add the missing @progress/kendo-react-buttons dependency to the @progress/kendo-react-inputs package.

This gives an error when using yarn 2.

The buttons package is used in `packages\inputs\src\colors\ColorInput.tsx`

**Comment by InaGlushkova** [comment]
The fix is introduced with version [v4.14.0-dev.202201141457](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#3f29bb34-9e26-55a0-b719-34a2e6dbd9aa)
