### ISSUE TITLE
When the proportion of a certain item is too small, such as one millionth level, the fan chart with too small proportion cannot be drawn

### ISSUE THREAD

**Issue by ChrisYuXian** [telerik/kendo-react#1171]
Version 4.9 or  Version 4.13
When the proportion of a certain item is too small, 
such as one millionth level, 
the fan chart with too small proportion cannot be drawn
![can't display](https://user-images.githubusercontent.com/95512532/147897855-6ac82728-a8c5-41e3-9bf8-c4b42072155a.png)

**Comment by simonssspirit** [comment]
This seems to be connected to the format used in the labelContent.

Please share an example and I will take a look.
