### ISSUE TITLE
sass and math.div warning

### ISSUE THREAD

**Issue by SebastianStehle** [telerik/kendo-react#1177]
## I'm submitting a...
* Bug report

## Current behavior
We use telerik scss files with bootstrap themes and newer versions of scss output a lot of warnings like this:

```
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($padding-y, 2) or calc($padding-y / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

      ╷
24013 │ $padding-y-sm: $padding-y / 2 !default;
      │                ^^^^^^^^^^^^^^
      ╵
    src\style\libraries.scss 24013:16  root stylesheet
```

## Expected behavior
No warnings

**Comment by simonssspirit** [comment]
This sounds like an issue in the themes. They have a separate repository for them:

https://github.com/telerik/kendo-themes
