### ISSUE TITLE
Add alt rows to Treelist

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-react#1180]
In Default and Bootstrap themes there are specific grey styles for the alt rows of the Treelist component. We should add the `k-alt` class as well. 

We do have it in our Grid and Gantt components.

**Comment by nstoychev** [comment]
Fixed and published in [v4.14.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#a04c4700-cebf-570e-8b74-a1601f6ddc15).
