### ISSUE TITLE
Fix MultiSelectTree Accessibility issues

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1182]
For MultiSelectTree there are the below accessibility issues:

- Ensures ARIA attributes are allowed for an element's role
- WCAG 4.1.2: Ensures every ARIA input field has an accessible name
- WCAG 1.3.1: Ensures elements with an ARIA role that require child roles 

Could be related to: https://github.com/telerik/kendo-react/issues/996

**Comment by vveesseelliinnaa** [comment]
Reported again in Ticket ID: 1581451

**Comment by Frenemee2020** [comment]
Any idea when this would be picked up? we need to be compliant on Accessibility

**Comment by nstoychev** [comment]
We made a lot of accessibility improvements for the 5.6.0 release and now testing this using Axe in Chrome no issues are found.

Example: https://stackblitz.com/edit/react-7snabd?file=app%2Fmain.tsx

@Frenemee2020 - Could you check it as well and let us know if the issue is resolved on your side?
