### ISSUE TITLE
Add options to provide an accessible name for the TabStrip tabs

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1184]
Add options to provide an accessible name for the TabStrip tabs

More details in ticket 1549272

**Comment by Frenemee2020** [comment]
Any idea when this would be picked up?

**Comment by InaGlushkova** [comment]
We made a lot of accessibility improvements for version [5.6.0](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#505f3368-11ff-55d8-baea-489d40b75d92).
I have tested this issue again using Axe in Chrome and no issues were found. 

Example: https://stackblitz.com/edit/react-hbqd2i?file=index.html
