### ISSUE TITLE
ColumnMenu does not render for Column filled with checkboxes in versions 4.10.0, 4.11, 4.12, 4.13

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1185]
The ColumnMenu does not render for grid columns with checkboxes in versions 4.10.0, 4.11, 4.12, 4.13. When reverting back to 4.9.0 it renders. The issue can be reproduced in the following example: https://stackblitz.com/edit/react-dfwz3q-azfha3?file=app%2Fmain.tsx

Ticket ID: 1549012

**Comment by filipKovachev** [comment]
Issue fixed in the following PR: https://github.com/telerik/kendo-react-private/pull/1633

**Comment by InaGlushkova** [comment]
The behavior is working correctly under the current newest version - [ v5.0.1](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#cebe5817-9fae-5728-8745-00f4c1547df3).

Example reference:
https://stackblitz.com/edit/react-dfwz3q-tt6xch?file=app/main.tsx
