### ISSUE TITLE
[v5.0.0] Grid uses Buttons but does not declare a dependency. Breaks yarn PnP.

### ISSUE THREAD

**Issue by rally25rs** [telerik/kendo-react#1188]
## I'm submitting a...

* Regression report 

## Current behavior

Attempting to import `@progress/kendo-react-grid@5.0.0` with `yarn` with pnp enabled results in:

```
/{long path omitted}/node_modules/@progress/kendo-react-grid/dist/es/cells/GridFilterCell.js
Module not found: @progress/kendo-react-grid tried to access @progress/kendo-react-buttons, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

version 4.* did not have this issue.

`kendo-react-grid` does not have a direct dependency or peerDependency on `kendo-react-buttons` so should not attempt to import it.

```
  dependencies:
    "@progress/kendo-react-common": 5.0.0
    prop-types: ^15.6.0
  peerDependencies:
    "@progress/kendo-data-query": ^1.0.0
    "@progress/kendo-drawing": ^1.2.0
    "@progress/kendo-licensing": ^1.0.1
    "@progress/kendo-react-animation": ^5.0.0
    "@progress/kendo-react-data-tools": ^5.0.0
    "@progress/kendo-react-dateinputs": ^5.0.0
    "@progress/kendo-react-dropdowns": ^5.0.0
    "@progress/kendo-react-inputs": ^5.0.0
    "@progress/kendo-react-intl": ^5.0.0
    "@progress/kendo-react-popup": ^5.0.0
    react: ^16.8.2 || ^17.0.0
    react-dom: ^16.8.2 || ^17.0.0
```

## Expected behavior

The `@progress/kendo-react-grid` library should declare a dependency on all libraries that it imports, including `@progress/kendo-react-buttons`

Based on the existing peerDependencies, I am guessing there was suposed to be an additional peerDep on `kendo-react-buttons`?

## Minimal reproduction of the problem with instructions

* Install yarn v3 (i am using 3.0.2)
* create a basic react project
* `yarn add @progress/kendo-react-grid`
* `import { Grid } from '@progress/kendo-react-grid'`
* results in the above error

## What is the motivation or use case for changing the behavior?

Properly declare dependencies to support [yarn PnP](https://yarnpkg.com/features/pnp)

## Environment

Package versions:

`yarn 3.0.2`

```
    "@progress/kendo-data-query": "^1.5.5",
    "@progress/kendo-drawing": "^1.16.1",
    "@progress/kendo-licensing": "^1.2.1",
    "@progress/kendo-react-animation": "^5.0.0",
    "@progress/kendo-react-buttons": "^5.0.0",
    "@progress/kendo-react-data-tools": "^5.0.0",
    "@progress/kendo-react-dateinputs": "^5.0.0",
    "@progress/kendo-react-dropdowns": "^5.0.0",
    "@progress/kendo-react-grid": "^5.0.0",
    "@progress/kendo-react-inputs": "^5.0.0",
    "@progress/kendo-react-intl": "^5.0.0",
    "@progress/kendo-react-popup": "^5.0.0",
    "@progress/kendo-react-treeview": "^5.0.0",
    "@progress/kendo-theme-bootstrap": "^5.0.1",
    "@progress/kendo-theme-default": "^5.0.0",
```

Browser:

- n/a (error will occur during webpack build when yarn attempts to resolve packages)

System:
- yarn 3.0.2
- TypeScript version: XX 
- Node version: 12.18.3
- Platform: Mac

-----

## Workaround:

For anyone who smacks into this issue and still wants to make yarn pnp work, you can override and add the peerDependency by:

add a file named `.yarnrc.yml` to your project root.

add the contents:
```yaml
packageExtensions:
  '@progress/kendo-react-grid@5.0.0':
    peerDependencies:
      '@progress/kendo-react-buttons': '^5.0.0'
```

re-run `yarn install`

Yarn pnp will now recognize the peer dependency and allow `grid` to load `buttons` 🚀

**Comment by silviyaboteva** [comment]
fixed in `v5.0.1-dev.202201200659`
