### ISSUE TITLE
Fix unique "key" warning in MultiSelectTree when a custom tag is used.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1189]
Fix unique "key" warning in MultiSelectTree when a custom tag is used:

https://stackblitz.com/edit/react-z69nvp?file=index.html

**Comment by nstoychev** [comment]
Fixed in [v5.0.2-dev.202201241659](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#00162092-d567-545e-a9da-5ce74d2f080a).
