### ISSUE TITLE
Add support for frozen columns

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#119]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
Frozen columns isn't supported in React.

## Expected behavior
Setting the GridColumn prop locked={ true } should freeze the column so the table scrolls underneath.

## Minimal reproduction of the problem with instructions
This is currently supported in the JQuery version but not the React version.
https://demos.telerik.com/kendo-ui/grid/frozen-columns

## What is the motivation or use case for changing the behavior?
We have a very large grid that can have an unknown amount of columns depending on the data. The user could lose track of what row they are looking at without an identifying column being fixed.

**Comment by simonssspirit** [comment]
The is already requested in our portal and the developer team is working on it:

http://kendoui-feedback.telerik.com/forums/908425-kendoreact-feedback/suggestions/33909391-frozen-column-in-react-grid

We will update the issues once the feature is available.

**Comment by Xizario** [comment]
`v2.6.0` is published.
