### ISSUE TITLE
MultiColumnComboBox group labels not visible in version 5.0.0

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1191]
MultiColumnComboBox group labels not visible in version 5.0.0

This is how they looked before 5.0.0
![image](https://user-images.githubusercontent.com/11087921/150473199-e2c66fa0-364d-4741-9e48-0c5e90e6272e.png)

**Comment by InaGlushkova** [comment]
The issue does not exist.
The labels are visible, but they are changed.

For reference:
https://www.telerik.com/kendo-react-ui/components/dropdowns/multicolumncombobox/grouping/
![image](https://user-images.githubusercontent.com/40406043/150540715-1f440e4f-ddd7-4e9c-abdf-4a27737adb9f.png)

**Comment by nstoychev** [comment]
The labels indicating the beginning of the groups in the list items are not styled properly.

**Comment by silviyaboteva** [comment]
Fixed in `v5.1.0-dev.202202240928`. Demos:
- https://www.telerik.com/kendo-react-ui-develop/components/dropdowns/multicolumncombobox/grouping/
- https://www.telerik.com/kendo-react-ui-develop/components/dropdowns/combobox/grouping/
