### ISSUE TITLE
The links to the new appearance properties in all Buttons in the documentation are broken (404)

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1193]
All links to the following new properties (within the articles and in the Suggested Links) are broken for all components in the Buttons section:

- size
- shape
- rounded
- fillMode
- themeColor

https://www.telerik.com/kendo-react-ui/components/buttons/button/appearance/
https://www.telerik.com/kendo-react-ui/components/buttons/chip/appearance/
etc.

**Comment by InaGlushkova** [comment]
Fixed under the current latest dev version - [v5.1.0-dev.202201271252](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#1f803430-424b-5a96-bf22-9fcb4adb5460)
