### ISSUE TITLE
themeColor in ButtonProps is missing "error" as available option

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1194]
v5.0.0
The "themeColor" of the ButtonProps (Button.tsx) should include "error" as well. Currently it is missing:
`export interface ButtonProps extends ButtonInterface, React.ButtonHTMLAttributes<HTMLButtonElement> {
        ...
        ...
        themeColor?: null | 'base' | 'primary' | 'secondary' | 'tertiary' | 'info' | 'success' | 'warning' | 'dark' | 'light' | 'inverse';
    }`

It is already included in the propTypes of the Button:
`export default class Button extends React.Component<ButtonProps, ButtonState> {
    static propTypes = {
        ...
        themeColor: PropTypes.oneOf([null, 'base', 'dark', 'error', 'info', 'inverse' ,'inverse', 'light', 'primary', 'secondary','success','tertiary','warning'])
    };`

**Comment by InaGlushkova** [comment]
Fixed under the current latest dev version - [v5.1.0-dev.202201271252](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#1f803430-424b-5a96-bf22-9fcb4adb5460)
