### ISSUE TITLE
Grid with "scrollable" none throw error when you click on the column headers

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1195]
Observed in version v5.0.1

Just setting "scrollable" to "none" will throw an error (_e.getBoundingClientRect is not a function_) after clicking on any of the column headers:
[https://stackblitz.com/edit/react-rv1awd-ga44r9?file=app/main.jsx](https://stackblitz.com/edit/react-rv1awd-ga44r9?file=app/main.jsx)

Here is a temporary fix for removing the scrollbar with CSS: 
[https://stackblitz.com/edit/react-rv1awd-dytang?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-rv1awd-dytang?file=app%2Fmain.jsx)

**Comment by simonssspirit** [comment]
reported again in 1553505

**Comment by simonssspirit** [comment]
reported again in 1553902

raising priority.

**Comment by ryansolomon-unite** [comment]
Also experiencing this issue in our app. Any workarounds or progress updated would be appreciated. Thank you

**Comment by filipKovachev** [comment]
reported again in 1567381

**Comment by nstoychev** [comment]
Fixed in our dev channel version 5.4.0-dev.202206090823 - https://stackblitz.com/edit/react-rv1awd-zyqvfm?file=app%2Fmain.jsx. 

See the following article about obtaining the development builds - https://www.telerik.com/kendo-react-ui/components/installation/development-builds/.
