### ISSUE TITLE
Window removes classes on blur.

### ISSUE THREAD

**Issue by Tommuh** [telerik/kendo-react#1196]
I was searching for animated window, I came across this article: 
https://www.telerik.com/kendo-react-ui/knowledge-base/window-animations/

Did the implementation the same, only with hooks.
But when the window losses its focus it resets its class names back to k-widget & k-window.

`reference.current.windowElement.classList.add('shown');`

This doesn't happen in the example provided. Any idea how I can solve this.
Now I have fixed it with setting a state on timeout to prevent direct rerender.

**Comment by simonssspirit** [comment]
We recommend using the Support system for questions like this as we have 24, 48, or 72 hours response time there. Here this is an issue tracking mostly and we may miss a question like this one.

Please share an example where the issue is reproduced and I will be happy to take look.
