### ISSUE TITLE
NumericTextBox currency format is cumbersome to edit

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#120]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
Deleting the existing value to type a new one doesn't behave as expected. It replaces the values with 0 instead of allowing space for new numbers.

## Expected behavior
Pressing backspace or delete in the text box should delete the value. Formatting and validation should be applied on blur instead of on change.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-6tetzy

**NumericTextBox:**
1. Try to change the cents from 53 to 10 by pressing backspace. The cents becomes 00, and then it will add 10 to the start of the 00 making it $101.1000 which doesn't make sense.
2. Try to change the entire value to $95 flat by pressing backspace to remove the existing value. The total value becomes $0.00, and 95 will be added to the start making it $950. If you press backspace all the way to the $ sign it replaces the first digit with 9, but this is counter to user expectation for textboxes.

**Standard HTML input:**
1. Try to change the cents from 53 to 10 by pressing backspace. The cents will be cleared and the new value can be entered normally.
2. Try to change the entire value to $95 flat by pressing backspace to remove the existing value. The total value will be cleared and become blank, and the new value can be added normally.

## What is the motivation or use case for changing the behavior?
We have a lot of money type textboxes in our app, which are adjusted and edited frequently. It's also an international app and we really like Kendo UI's globalisation features and would like to use them but the Numeric Text Box is a bit difficult to use on a frequent basis.

Browser:
- Chrome (desktop) version 70.0.3538.77 (Official Build) (64-bit)

System:
- Platform: Windows

**Comment by DanielHTpg** [comment]
I've also encountered this when using the component and it does feel akward to use and the reason why I've not implemented it in any apps. I'm using the kendo angular suite in other apps and the implementation of the formatting in the angular version works on blur events. I don't see a reason why the same component behaves differently between kendo frameworks.

Might this be changed in the feature?

**Comment by vladimirivanoviliev** [comment]
Fixed in latest dev version `3.10.0-dev.202001150733`.
