### ISSUE TITLE
Menu component displays  Each child in a list should have a unique "key" prop.Check the render method of `MenuItemInternal` error when being rendered.

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1200]
When using the Menu component the following error appears in the console: Each child in a list should have a unique "key" prop.Check the render method of `MenuItemInternal` error when being rendered.

 Reproducible example: https://stackblitz.com/edit/react-5g1mqm-ichbi5?file=app/main.jsx, open the dev tools to see the error.

Ticket ID: 1550721

**Comment by kdikov82** [comment]
Reported again in Ticket ID: 1557044

**Comment by fhanggi** [comment]
Could we please have an update as to when this will be fixed?

**Comment by kdikov82** [comment]
The error is not reproduced with the latest version (5.11.0):
https://stackblitz.com/edit/react-5g1mqm-vptjhx?file=app%2Fmain.jsx
