### ISSUE TITLE
Fix  `TypeError: Cannot read properties of null` error while scrolling the Scheduler

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1202]
Fix  `TypeError: Cannot read properties of null` error while scrolling the Scheduler.

The error occurs after scrolling the Scheduler, but not all of the time. For example, after editing an item.

It could be connected with https://github.com/telerik/kendo-react/issues/1166 as it behaves better in 5.0.0

**Comment by simonssspirit** [comment]
Same error occurs when scrolling the Grid details in 1553305

**Comment by kdikov82** [comment]
I tested various scenarios with the Grid and the Scheduler, but I was not able to replicate the error with version 5.11.0
