### ISSUE TITLE
Drag selection in Grid breaks on scrolling

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1206]
tested with version 5.0.1

When you start drag-to-select from particular cell/row and you move the selection in a way that forces the Grid to scroll causes the initial starting point to be changed (only the items underneath the drag selector will be selected. The drag selector does not take into account the scrolling):
[https://stackblitz.com/edit/react-pqrhrz-harfev?file=app/main.jsx](https://stackblitz.com/edit/react-pqrhrz-harfev?file=app/main.jsx)

Expected behavior:
The drag selector element should expand on scroll

**Comment by kdikov82** [comment]
Reported in Ticket ID: 1551364

**Comment by zdravkov** [comment]
A fix for getting the correct selection is applied in the latest dev version - we select all the cells from the press to the up position - https://stackblitz.com/edit/react-pqrhrz-vagdsh?file=app%2Fmain.jsx

Currently the selection hint is with fixed position and can't expand with the scroll yet we we think of possible selection of cells while dragging in some of the future version s of KendoReact.
