### ISSUE TITLE
Charts only renders white dots

### ISSUE THREAD

**Issue by nelsontrangithub** [telerik/kendo-react#1207]
## I'm submitting a...
* Bug report 

## Current behavior
![image](https://user-images.githubusercontent.com/45767865/151853805-a62fb7e5-04ea-40c1-ae9f-3d30e7a21635.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/45767865/151853854-48baf581-c7ea-4836-9706-6e634acbf09f.png)

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by simonssspirit** [comment]
This can occur if there is no theme loaded. If that is not the case, please attach an example.
