### ISSUE TITLE
IE11 clicking on Multiselect does not always open dropdown list

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#121]
## I'm submitting a...
* Bug report

## Current behavior
In Internet Explorer 11. Click inside the multiselect. The list drops down. Click the multiselect again. The list closes. Click the multiselect again. The list does not open. You must click towards the middle or right hand side of the component.
Keep clicking the multiselect over and over and you will see the list does not open all the time.

(If you click elsewhere on the screen first, and then back to the multiselect again, it will display the list items correctly. Or if you click the multi select multiple times it will display the list correctly)

A summary is: When clicking on the k-multiselect-wrap while the k-input is already focussed, the dropdown list does not toggle. 

## Expected behavior
When clicking the Multiselect it should open the list. When clicking it again it should close the list. Then when clicking it again it should open the list again.

## Minimal reproduction of the problem with instructions
Step 1. Use Internet Explorer 11.
Step 2 Click the Multi Select. The list drops down.
Step 3. Click the Multi Select again, or Select an Item. The list closes.
Step 4. Click the Multi Select again one time. The list does not open.
NB! You must click towards the middle or right hand side of the component. 
If you click close to the left, or close to any existing tags it will work fine

This is the same as the demo site demo:
https://stackblitz.com/edit/react-uydchp?file=package.json

## What is the motivation or use case for changing the behavior?
Whenever a user selects a Multi Select item, they experience buggy behavior, having to click the multiselect multiple times

## Environment
Same as demo site

Browser:
- IE version 11

System:
- Platform:  Windows

**Comment by bronsonmt** [comment]
same issue for me !

**Comment by nstoychev** [comment]
@k290, @bronsonmt - We have published a fix in our dev channel - [2.4.0-dev.201811211721](https://www.npmjs.com/package/@progress/kendo-react-grid/v/2.4.0-dev.201811211721). Please refer to the following [article](https://www.telerik.com/kendo-react-ui/components/installation/development-builds/) about obtaining the development builds.

**Comment by k290** [comment]
Thank you @nstoychev !

**Comment by k290** [comment]
Tested 2.4.0-dev.201811231621 in IE11 on our side. Seems fixed.

**Comment by nstoychev** [comment]
We have just published version [2.4.0](https://www.npmjs.com/package/@progress/kendo-react-grid/v/2.4.0) and I am closing the issue.
