### ISSUE TITLE
Grouping with virtualization.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#122]
Add support for Grouping with virtualization.

**Comment by andr-xxx** [comment]
Hi! Any news about this feature?

**Comment by Xizario** [comment]
It is in the roadmap for January.

**Comment by Xizario** [comment]
https://www.telerik.com/kendo-react-ui/components/grid/grouping/grouping-virtual/

**Comment by andr-xxx** [comment]
unfortunately there are still many problems 
https://www.telerik.com/forums/grid-with-virtualscroll-doesn't-work-with-grouping-feature-properly#fngKQjTJF0KpTsiwn8gBxQ

**Comment by andr-xxx** [comment]
> https://www.telerik.com/kendo-react-ui/components/grid/grouping/grouping-virtual/

unfortunately there are still many problems 
https://www.telerik.com/forums/grid-with-virtualscroll-doesn't-work-with-grouping-feature-properly#fngKQjTJF0KpTsiwn8gBxQ

**Comment by andr-xxx** [comment]
> https://www.telerik.com/kendo-react-ui/components/grid/grouping/grouping-virtual/

unfortunately there are still many problems 
https://www.telerik.com/forums/grid-with-virtualscroll-doesn't-work-with-grouping-feature-properly#fngKQjTJF0KpTsiwn8gBxQ
