### ISSUE TITLE
Fix ComboBox error when one of the values is undefined.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1220]
Fix ComboBox error when one of the values is undefined.

https://stackblitz.com/edit/react-qpiphs?file=app/main.jsx

More details in ticket 1553481

**Comment by nstoychev** [comment]
Please, make sure the value which will be rendered is string type. We will update the documentation accordingly.

Examples:
`const sports = [ "Baseball",  "Basketball", ... ];`
or
`const sports = [ {text: "Basketball", id: 1}, {text: "Football" id: 2}, ... ];`

If you need null. undefined or 0, map them in the [String constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/String).
