### ISSUE TITLE
Improve DatePicker and TimePicker accessibility. 

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1221]
Improve DatePicker and TimePicker accessibility. 

Currently, both components how errors for invalid attributes:

`Error: Attribute autocorrect not allowed on element[ input](https://html.spec.whatwg.org/multipage/#the-input-element) at this point`

`Error: Attribute aria-expanded not allowed on element[ input](https://html.spec.whatwg.org/multipage/#the-input-element) at this point.`

Please research if and where these attributes have to be changed.

**Comment by kdikov82** [comment]
Diplicate: https://github.com/telerik/kendo-react/issues/1149
