### ISSUE TITLE
Line graph when the value is 0, only half of the dots are displayed

### ISSUE THREAD

**Issue by ChangBaiMonster** [telerik/kendo-react#1225]
When I draw a line graph and the value is 0, why does the bottom dot show only half of it?
https://stackblitz.com/edit/react-7tbpcw?file=app/main.tsx

## Current behavior
The red line, with a value of 0, only shows half of the dots

## Expected behavior
The red line, with a value of 0, displays a complete dot

**Comment by simonssspirit** [comment]
That is expected as the middle of the marker is considered the point value, not the bottom of the dot.

**Comment by ChangBaiMonster** [comment]
hello ,  But I look at the official echarts website, they can show a full circle when the value is 0.
![image](https://user-images.githubusercontent.com/19709711/169936627-183a259c-b95b-45ed-a5a5-409174207ce8.png)

**Comment by ChangBaiMonster** [comment]
> That is expected as the middle of the marker is considered the point value, not the bottom of the dot.

hello , But I look at the official echarts website, they can show a full circle when the value is 0.
