### ISSUE TITLE
RangeSlider fix `RangeSlider.js:101 Unable to preventDefault inside passive event listener invocation.`

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1227]
RangeSlider fix `RangeSlider.js:101 Unable to preventDefault inside passive event listener invocation.`

That can be seen in our demos when changing the value:

https://www.telerik.com/kendo-react-ui/components/inputs/rangeslider/

**Comment by InaGlushkova** [comment]
Introduced with dev version [v5.4.0](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#861151b6-4033-51db-8a3f-1e84d4991fd3)

More information about obtaining the development builds - 
https://www.telerik.com/kendo-react-ui/components/installation/development-builds/
