### ISSUE TITLE
KendoReact Stepper step text is not responsive

### ISSUE THREAD

**Issue by yousafnawaz** [telerik/kendo-react#1228]
## I'm submitting a...

* Bug report 

## Current behavior
![image](https://user-images.githubusercontent.com/91653057/156194385-575d211f-7e8c-4f46-ace1-39de22607547.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/91653057/156194589-2e66bae7-c241-4d44-8c81-223b5a66caee.png)

## Minimal reproduction of the problem with instructions

Stackblitz example on: [https://www.telerik.com/kendo-react-ui/components/layout/stepper/](https://www.telerik.com/kendo-react-ui/components/layout/stepper/)

**Comment by kdikov82** [comment]
The styles can be customized with CSS or with custom rendering of the steps:
https://www.telerik.com/kendo-react-ui/components/layout/stepper/custom_rendering/
