### ISSUE TITLE
Removing all but one resource will merge all items from all the other resources into the remaining resource.

### ISSUE THREAD

**Issue by mkhlightspeed** [telerik/kendo-react#1229]
## I'm submitting a...

* Bug report 

## Current behavior

If you create a Scheduler and bind 2 resources with items for each resource and then remove all of the resources except for 1, the items for all resources get combined into the last remaining resource.

For example. If you show a view of 2 employees that each have their own items, The view will separate the items into the employee bucket that the items belong to. If you then remove one of the employees, leaving just one, the events for the removed employee will display for the remaining employee. 

If you have 4 employees and remove 1 leaving 3 the items for the employee that was removed do NOT show up on another employee's timeline as expected. This only happens if you remove all of the employees leaving just 1. 

## Expected behavior

I expected that if I removed all but 1 of the resource groups, It would only show items that belong to that last group and not ALL of the items assigned to the other groups. 

## Minimal reproduction of the problem with instructions

Test component that includes 2 employees and a button that removes one of the employees from resources in the state.

[Stackblitz Link](https://react-vbbvjf.stackblitz.io)

## What is the motivation or use case for changing the behavior?

The use case is that we want to list the employee's schedule to see all of them side by side. If there are a lot of employees or if you want see a specific employee, you will be able to remove the other employees and their calendar from the view. 

## Environment

Package versions:

```
├── @progress/kendo-date-math@1.5.4
├── @progress/kendo-licensing@1.2.2
├── @progress/kendo-react-buttons@5.0.1
├── @progress/kendo-react-common@5.0.1
├── @progress/kendo-react-dateinputs@5.0.1
├── @progress/kendo-react-dialogs@5.0.1
├── @progress/kendo-react-dropdowns@5.0.1
├── @progress/kendo-react-form@5.0.1
├── @progress/kendo-react-inputs@5.0.1
├── @progress/kendo-react-intl@5.0.1
├── @progress/kendo-react-popup@5.0.1
├── @progress/kendo-react-scheduler@5.0.1
├── @progress/kendo-theme-default@5.2.0
├── @testing-library/jest-dom@5.16.2
├── @testing-library/react@12.1.3
├── @testing-library/user-event@13.5.0
├── cldr-core@40.0.0
├── cldr-dates-full@40.0.0
├── cldr-numbers-full@40.0.0
├── react-dom@17.0.2
├── react-scripts@5.0.0
├── react@17.0.2
└── web-vitals@2.1.4
```

Browser:

- Chrome (desktop) Version 98.0.4758.109 (Official Build) (x86_64)

System:

- Node version: v17.5.0 NPM 8.5.0  
- Platform:  Mac

**Comment by kdikov82** [comment]
The example can't be open and from the description of the issue it seems that the problem is with the events in the "data" and removing the resource should be combined with removing the events for that resource in the "data" as well. If I am misunderstanding the issue, please try sharing the example again, so we can inspect the behavior.
