### ISSUE TITLE
Improve customization of the filter.

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-react#123]
Make filter operators per type (or per column) to be configurable.
Requested in https://github.com/telerik/kendo-react/issues/28

**Comment by IreneMarquet** [comment]
Hello @Xizario do you have any updates if this enhancement is being worked on? thanks a lot.

**Comment by Xizario** [comment]
@IreneMarquet we are preparing some changes internally that will allow changing(like injection) of the components in tree for all the components, and this will affect the dropdowns inside the filter menu as well. 

Additionally we plan to allow the filter cell to be placed inside the column menu, by extracting some common logic. This way the user will be able to customize the filter easier and use the same components for the filter row and the column menu. So in case someone is implementing custom filter with custom operators dropdown they can at-least reuse it.

I could not give exact estimations for this item in particular, since we are pushing lots of improvements for the official release in January, but around the time of the release operators will be configurable, hopefully in more than a one way.

**Comment by IreneMarquet** [comment]
Hello @Xizario were these changes released in January release? I've been checking documentation but dont find it. If they were release, will you have some example or reference documentation so that we can implement the customization to our filters? thanks in advance.

**Comment by Xizario** [comment]
Update to my previous in https://github.com/telerik/kendo-react/issues/28. As 2.7.0 is live and the classes are now exported, the following example of reducing the operator will work:
https://stackblitz.com/edit/react-zsehvh?file=app/columnMenu.js
```jsx
const CustomFilterUI = (props) => {
  const operators = props.operators.filter((o) => {
    return o.operator != 'isnull'
  });
  return <GridColumnMenuFilterUI {...props} operators={operators} />
}
```

```jsx
        <GridColumnMenuFilter
          {...this.props}
          filterUI={CustomFilterUI} />
```
It is not limited to the operators, everything else in the [FilterUI](https://www.telerik.com/kendo-react-ui/components/grid/api/GridColumnMenuFilterUIProps/) can be changed using this approach.

**Comment by IreneMarquet** [comment]
Thanks a lot! We are going to test this.

**Comment by IreneMarquet** [comment]
Works very good @Xizario we have implemented it, thanks so much for your support!
