### ISSUE TITLE
The ColumnMenu of the Grid does not close if you click on a scrollbar

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1230]
Clicking on a scrollbar does not trigger the blur event of the ColumnMenu and the menu is not closed. In scenarios with horizontal scrollbar, this forces the ColumnMenu to stay open and at the same horizontal position while scrolling horizontally:

- [https://stackblitz.com/edit/react-xt28vp?file=app%2FcolumnMenu.tsx](https://stackblitz.com/edit/react-xt28vp?file=app%2FcolumnMenu.tsx)

Expected behavior: the column menu should close when a scrollbar outside of it is clicked

Tested with version 5.0.1

**Comment by WissamProgress** [comment]
Reported in Ticket ID: 1597476

The same issue is present for the DropDowns of the filter rows - [https://www.telerik.com/kendo-react-ui/components/grid/filtering/#toc-filter-rows](https://www.telerik.com/kendo-react-ui/components/grid/filtering/#toc-filter-rows)

**Comment by filipKovachev** [comment]
Reported in Ticket ID: 1625076
