### ISSUE TITLE
Add the `k-invalid` class to the Input component instead of the `k-state-invalid`

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1232]
Add the `k-invalid` class to the Input component instead of the `k-state-invalid`.

Currently, the invalid styles are not correctly applied to the Input component:

https://www.telerik.com/kendo-react-ui/components/inputs/input/forms/#toc-setting-validation-requirements

**Comment by silviyaboteva** [comment]
Fixed in `v5.1.1-dev.202203280712`.
Demo: https://www.telerik.com/kendo-react-ui-develop/components/inputs/input/forms/
