### ISSUE TITLE
document.execCommand doesn't retain styling for single line outputs

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#1235]
## I'm submitting a...
* Bug report

## Current behavior
When using execCommand, it only seems to keep the styling (bold, font colour) when there is more than 1 line of text.

## Expected behavior
Styling is pasted in even for single line texts.

## Minimal reproduction of the problem with instructions
1. Go to the demo site https://www.telerik.com/kendo-react-ui/components/editor/
2. Right click the rich text editor and click Inspect Element to ensure that the element is focused and also the JavaScript console is in the correct context
5. In the JavaScript console, paste `document.execCommand('insertHTML', false, '<p><strong>bold text</strong></p>');`
6. You will notice that it is plain text with no styling. Now paste `document.execCommand('insertHTML', false, '<p><strong>bold text</strong></p><p><br ></p>');`
7. You will notice that this time it works

## What is the motivation or use case for changing the behavior?
We are trying to implement a "quick text button" shortcut feature in our application for merge tags and typing the same content repeatedly. This bug is holding back this feature.

Browser:
- Chrome (desktop) version 99.0.4844.51 (Official Build) (64-bit) (cohort: 99_Win_51)

**Comment by nstoychev** [comment]
I would advise you to use the editor's API instead of the browser's `document.execCommand`. Here is how to insert bolded text - https://stackblitz.com/edit/react-tgiyoo?file=app/main.jsx.

I hope this helps.

**Comment by GeoMarkou** [comment]
Is there a function to insert a lot of html at once? These quick buttons are user configurable so I need to be able to insert arbitrary HTML (not always bold text).

**Comment by nstoychev** [comment]
The inserted HTML needs to be parsed to prose-mirror node and then can be inserted into the Editor. The inserted HTML also needs to conform to the [Editor's schema](https://www.telerik.com/kendo-react-ui/components/editor/schema/). The HTML tags which are not described in the schema will be stripped.

During the parsing, the inline content has been wrapped in a paragraph, so I made two (tools) buttons, one for inserting block content and the other for inline content - https://stackblitz.com/edit/react-tgiyoo-xnqfyf?file=app/main.jsx. Depending on the inserted content, you can choose the proper approach.

**Comment by GeoMarkou** [comment]
Thank you for the samples, they helped greatly. Providing my full solution here in case it helps anyone else. It checks if the element is an `<Editor />` or a plain `<input />` which continues to use execCommand. It also checks whether the inserting content is "inline" or "multi line":

```ts
/** Check if the selected element is an Editor */
const detailEle = document.activeElement.closest('.detail') as HTMLDivElement;
if (detailEle.dataset['type'] === '1') {
    /** Get the View from child component */
    const editorView = DetailRefs.get(parseInt(detailEle.dataset['id'])).current
        .EditorRef.current.view;
    
    const editorState = editorView.state;
    const tr = editorState.tr;
    const newDoc = EditorUtils.createDocument(editorState.schema, mergedStr);

    /** Check if this is an "inline" or a "multi line" button */
    if (newDoc.content.childCount > 1) {
        tr.replaceSelectionWith(newDoc, true);
    }
    else {
        const contentWrapper = newDoc.content.firstChild;
        const selection = editorState.selection;
        tr.replaceWith(selection.from, selection.to, contentWrapper.content);
    }

    editorView.dispatch(tr);
    return;
}

document.execCommand(qButton.is_html ? 'insertHTML' : 'insertText', false, mergedStr);
```
