### ISSUE TITLE
Add globalization message for the Grid Checkbox column menu `selected items` text

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1240]
Add globalization message for the Grid Checkbox column menu `selected items` text:

![image](https://user-images.githubusercontent.com/11087921/158190065-d5212566-2b17-48b8-9247-d869065ec64d.png)

**Comment by kdikov82** [comment]
Already available through "grid.filterSelectedItems":
https://stackblitz.com/edit/react-qop1uv-xftrdh?file=app%2Fmain.jsx,app%2Fes.json
