### ISSUE TITLE
When the popup of the DropDownList is opened through the arrow icon, blurring the component does not close the popup

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1244]
To observe the issue:
- Open the example: [https://stackblitz.com/edit/react-qzlfar?file=app/main.tsx](https://stackblitz.com/edit/react-qzlfar?file=app/main.tsx)
- Click on the arrow icon and then click somewhere else on the page
- The popup remains open

If you open the popup by not clicking on the arrow, it is closed correctly when the focus is lost

Tested with version 5.1.0

Workaround :
  ```
  <DropDownList
    onOpen={(e) => {
        e.target.focus();
    }}
```

**Comment by nstoychev** [comment]
Fixed in our development channel version 5.5.0-dev.202206280851. See the following article about obtaining the development builds - https://www.telerik.com/kendo-react-ui/components/installation/development-builds/.
