### ISSUE TITLE
SplitButton focus items with keyboard navigation

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-react#1251]
#### Problem
In this example: https://www.telerik.com/kendo-react-ui/components/buttons/splitbutton/keyboard-navigation/ when the popup opens, the focused item is not indicated.

#### Solution
The `k-focus` class must be added to the li element instead of the inner span.
Reference: https://github.com/telerik/kendo-themes/issues/2839

**Comment by InaGlushkova** [comment]
The issue does not seem to exist with the newest versions.

Link reference:
https://stackblitz.com/edit/react-qynoq4?file=app/main.jsx
