### ISSUE TITLE
Button: `defaultProps.size` type is wrong resulting in imcompatibility with `@emotion/styled`

### ISSUE THREAD

**Issue by srmagura** [telerik/kendo-react#1254]
**Hello, Emotion contributor here. This bug was originally reported to us here: https://github.com/emotion-js/emotion/issues/2672, but it seems to be an issue with the Kendo React types.** When looking at the original issue, make sure to check out the TS playground by Andarist.

## I'm submitting a...

Bug report 

## Current behavior

When using the `Button` component in TypeScript, the type of `defaultProps.size` is `string` while `ButtonProps['size']` is `'small' | 'medium' | 'large' | null | undefined`. `string` is not assignable to `'small' | 'medium' | 'large' | null | undefined`.

This results in a TS error when using `@emotion/styled`.  

## Expected behavior

`defaultProps.size` is assignable to `ButtonProps['size']`.

## Minimal reproduction of the problem with instructions

See CodeSandbox and TS playground in original issue in Emotion repository.

## What is the motivation or use case for changing the behavior?

Ability to use `Button` with `@emotion/styled`.

## Environment

Package versions:
![image](https://user-images.githubusercontent.com/801549/159698083-face8fa8-afc8-47d8-a52c-44b326cddd5d.png)

Browser: Irrelevant

System:
- TypeScript version: 4.6.2
- Node version: N/A
- Platform: N/A

**Comment by kdikov82** [comment]
Could you please confirm that you are still facing issues with the latest versions (5.11.0)?

I have checked the types and the propTypes are as following:
`size: PropTypes.oneOf([null, 'small','medium', 'large']),`

And the defaultProps:
```
    static defaultProps = {
        togglable: false,
        size: 'medium',
```
