### ISSUE TITLE
[BUG][Tabstrip] Tabstrip does not render the ARIA aria-controls, aria-labelledby and aria-disabled

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1255]
Currently, the Tabstrip does not render the ARIA attributes listed in the "Accessibility" help article:

- [https://www.telerik.com/kendo-react-ui/components/layout/tabstrip/accessibility/](https://www.telerik.com/kendo-react-ui/components/layout/tabstrip/accessibility/)

The expected behavior can be seen in the Kendo UI for Angular Tabstrip:

- [https://www.telerik.com/kendo-angular-ui/components/layout/tabstrip/keyboard-navigation/](https://www.telerik.com/kendo-angular-ui/components/layout/tabstrip/keyboard-navigation/)

**Comment by iadnonov** [comment]
Fixed in dev version v7.0.0-develop.4
