### ISSUE TITLE
PivotGrid with local data throws error if all columns are removed from the Configurator

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1258]
To reproduce:
1) Open the following example: [https://stackblitz.com/edit/react-xs7kmy-jbvxp2?file=app/main.jsx](https://stackblitz.com/edit/react-xs7kmy-jbvxp2?file=app/main.jsx)
2) Open the configurator and remove the fields from the Columns
3) Apply the changes

An error will be throws: "e.displayValue is not a function"

With OLAP there is no error and the user is able to remove all columns without any problems.

Tested with version: 5.1.0

**Comment by vveesseelliinnaa** [comment]
Reported again in Ticket ID: 1594509

**Comment by nstoychev** [comment]
The issue has been resolved in version [6.1.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#v6.1.0).

Example: https://www.telerik.com/kendo-react-ui/components/pivotgrid/data-binding/local-binding/#toc-basic-usage
