### ISSUE TITLE
Fix Scheduler grouped TimelineView alignment 

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1259]
Fix Scheduler grouped TimelineView alignment when we change days.

Steps: https://stackblitz.com/edit/react-kuydyb-amfwhf?file=app%2Fmain.jsx

1) Go to the previous date.
2) Go back to the same date.
3) Notice the misalignment:

![image](https://user-images.githubusercontent.com/11087921/160100650-d4c54f08-44bc-44ad-b23e-f25b40e13aa1.png)

**Comment by kdikov82** [comment]
It seems that the alignment issue is resolved in version 5.11.0:
https://stackblitz.com/edit/react-kuydyb-8tau6d?file=app%2Fmain.jsx

There is some glitch while moving through the dates, but it is a separate issue.
