### ISSUE TITLE
Opening the Grid pagination via the arrow and clicking outside does not close the popup

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1261]
If you open the grid pagination by clicking the arrow and then click anywhere else on the page, the popup remains open:

https://stackblitz.com/edit/react-wuskz5-w4nqkn?file=app/main.jsx
This does not reproduce if you open the popup using the keyboard keys.
Reported in Ticket: 1558761

Possibly related to https://github.com/telerik/kendo-react/issues/1244

**Comment by zhangdandan-eel** [comment]
In most cases, users operate with the mouse. It is inconvenient to use the keyboard while using the mouse, which affects the use experience. Is there a way to improve?
