### ISSUE TITLE
Scheduler renders one less time slot for days with daylight saving.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1268]
Scheduler renders one less time slot for days with daylight saving.

That occurs only in some localization settings and slot durations:

https://stackblitz.com/edit/react-sdtpkg-jkftxb?file=app%2Fmain.tsx

**Comment by kspeyanski** [comment]
The issue has been fixed in the latest `dev` version of the `@progress/kendo-react-scheduler` package.

Please refer to the example with an updated dependency:
https://stackblitz.com/edit/react-sdtpkg-qbrgpn?file=app/main.tsx
