### ISSUE TITLE
Grid - filter input loses focus on a grid with applied grouping

### ISSUE THREAD

**Issue by yarmolovichalex** [telerik/kendo-react#127]
## I'm submitting a...
* Bug report

## Steps to reproduce
1. Go to https://www.telerik.com/kendo-react-ui/components/grid/grouping/ (or to the fork https://react-zvb7mh.stackblitz.io/).
2. Enter any value into Product Name filter, so all data are filtered out.

## Current behavior
Filter input loses focus. User have to put cursor into the filter input manually to continue filter editing.

## Expected behavior
Focus must be kept.

## Additional
1. Reverse actions (clearing filter, until data starts to appear in the grid) also causes losing focus.
2. Unit Price filter behaves differently - when all data is filtered out, the focus switches to Units in Stock filter:
![image](https://user-images.githubusercontent.com/5493641/48468941-64950f80-e7fe-11e8-8cc2-c764fb3f6084.png)
(here I tried to enter `333333` into Units Price filter).
3. I believe, this is somehow related to additional column(s) when there are some data in the grid and grouping is applied:
![image](https://user-images.githubusercontent.com/5493641/48469046-b76ec700-e7fe-11e8-80bc-22aeebc5e64c.png)
Without data it's absent:
![image](https://user-images.githubusercontent.com/5493641/48469064-cb1a2d80-e7fe-11e8-9c43-3edde4f16c2f.png)

## What is the motivation or use case for changing the behavior?
Filtering on a grid with applied grouping.

## Environment

Chrome (desktop) Version 70.0.3538.102 (Official Build) (64-bit)
Windows 10 Pro 1803

**Comment by Xizario** [comment]
Will be part of [todays](https://www.npmjs.com/package/@progress/kendo-react-grid) `v2.4.0-dev`

**Comment by Xizario** [comment]
Fixed in `v2.4.0`
