### ISSUE TITLE
Problem will importing DOM Element or react Component to PDF using Kendo-react PDF

### ISSUE THREAD

**Issue by nelsonmandeladev** [telerik/kendo-react#1271]
Hello there, I'm using Kendo-react PDF in my new application but I have this problem: Special characters are not showing up in the exported document as they are in the DOM element. Please someone to help me. The documents to be generated will be in the French language so will contain many special characters.
![DOM Element](https://user-images.githubusercontent.com/69842489/161676551-e348cd87-d772-4ef1-89c1-452f53119e77.png)
![output file](https://user-images.githubusercontent.com/69842489/161676557-d77637e5-b136-45b7-9927-18df71d06fbf.png)

**Comment by kdikov82** [comment]
For Unicode Characters you need to embed a font that supports them. Detailed information on this topic is available in the following help article:
https://www.telerik.com/kendo-react-ui/components/drawing/pdf-output/embedded-fonts/
