### ISSUE TITLE
Grid with virtual scroll looks empty after applying filter that does not change items count

### ISSUE THREAD

**Issue by da1z** [telerik/kendo-react#1278]
https://user-images.githubusercontent.com/4012422/163505416-45f1dfbe-7cef-42a3-905b-9e5b1c07f712.mov

When you apply filter that does not change total items count grid looks empty until you scroll again

To reproduce:
1) Go to example https://stackblitz.com/edit/react-bjqfye?file=app/main.jsx

2) Scroll a little

3) Apply filter on last column with select all

4) See empty state until you scroll

Also initial skip value being reset to zero once you scroll. For example if set initial skip as 250 and start scroll it will be reset to 0

Example: https://stackblitz.com/edit/react-plfvjb?file=app/main.jsx

**Comment by InaGlushkova** [comment]
The issue is going to be resolved under https://github.com/telerik/kendo-react/issues/1270
