### ISSUE TITLE
Breadcrumb does not fire onItemSelect if an icon is clicked

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1280]
Clicking on the icon in the Breadcrumb item does not trigger the onItemSelect event.
Example demonstrating the issue:
[https://stackblitz.com/edit/react-fhpf6m?file=app/main.tsx](https://stackblitz.com/edit/react-fhpf6m?file=app/main.tsx)

Workaround until the fix:
[https://stackblitz.com/edit/react-qy4zls?file=app/main.tsx](https://stackblitz.com/edit/react-qy4zls?file=app/main.tsx)

Tested with version 5.2.0

**Comment by InaGlushkova** [comment]
Introduced with version [v5.3.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#ce8acda4-4843-57d6-be59-4e1c3f75abdc)
