### ISSUE TITLE
The placeholder of the MultiSelectTree does not render when there is no selected value

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1284]
Setting the "placeholder" property of the MultiSelectTree does not have any effect even when there is no value selected.

An example demonstrating the issue:
[https://stackblitz.com/edit/react-3crp9n?file=app/main.jsx](https://stackblitz.com/edit/react-3crp9n?file=app/main.jsx)

Tested with version 5.2.0

**Comment by WissamProgress** [comment]
Reported in Ticket ID: 1595204
