### ISSUE TITLE
An additional line break is added to existing default content line breaks on initialization of the editor component

### ISSUE THREAD

**Issue by GilWard** [telerik/kendo-react#1285]
## I'm submitting a...

* Bug report 

## Current behavior
Adds a single line break to the end of default content line breaks.

## Expected behavior
No added line breaks.

## Minimal reproduction of the problem with instructions
**STEPS TO REPRODUCE**

1. Initialize component with default content HTML containing a line break in between paragraphs of text.
2. Observe the extra line break.

![image](https://user-images.githubusercontent.com/63768987/164626571-aaaaf959-dcbf-422f-a864-1b1bb1190173.png)

https://stackblitz.com/edit/react-ivgw3y?file=app/main.jsx

## What is the motivation or use case for changing the behavior?
Have the default content maintain consistent line break formatting.

## Environment

Browser:
- Chrome (desktop) version 100.0.4896.127 (Official Build) (64-bit)

**Comment by nstoychev** [comment]
The additional BR element is not rendered by the browser and is not part of the editor value. I think, it should not affect you.

There is also a discussion here - https://discuss.prosemirror.net/t/parser-adds-br-tag-to-every-paragraph/1539.

**Comment by GeoMarkou** [comment]
> The additional BR element is not rendered by the browser and is not part of the editor value. I think, it should not affect you.

The `<br>` elements are definitely being rendered, and causing issues when displaying the results of the HTML in other parts of our application. For example `<div dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(HtmlData) }} />`. Every time a user edits their data it's widening the spaces between lines, which is causing problems.

The linked discussion mentions bypassing the Kendo Editor and using ProseMirror functions directly. Shouldn't the `EditorUtils.getHtml(event.target.view.state)` or `onChange.event.html` properties of the Editor be giving us valid HTML in the first place? I've tried implementing one of the functions in the discussion and it doesn't solve the problem.

**Comment by nstoychev** [comment]
> Every time a user edits their data it's widening the spaces between lines

This looks like a different issue to me.

Can you provide a stackblitz example where it can be seen and I'll investigate it for you?

Getting the HTML with `EditorUtils.getHtml(event.target.view.state)` or `onChange.event.html` will give you valid HTML without the additional BR element.
