### ISSUE TITLE
Scrolling within the TimePicker popup changes the items too fast (too many at a time)

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1290]
Currently, more items that are visible in the default view are scrolled at a time, which makes it impossible to go to some values only by scrolling:

- [https://stackblitz.com/edit/react-2zyjqe?file=app/main.jsx](https://stackblitz.com/edit/react-2zyjqe?file=app/main.jsx)

My guess is that the issue is due to the maxScrollDifference={this.listHeight} for the virtualization in TimeList.tsx. We can easily reduce the number of values that will be scrolled by half.

It is also reported that the number of the scrolled values differs in Firefox and Chrome

**Comment by ianzone** [comment]
Hi there, how is it going?

**Comment by kspeyanski** [comment]
The issue has been fixed with version `v5.5.0` of the `@progress/kendo-react-dateinputs` package. Please refer to the [Changelog](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#f41e9a37-40fc-55bf-b714-f3c8c7455a4e) for the full list of changes.
