### ISSUE TITLE
lack of children in <PDFExport>,<FloatingLabel>,<Grid>,<Sparkline>, <LocalizationProvider> and <IntlProvider>

### ISSUE THREAD

**Issue by ianzone** [telerik/kendo-react#1291]
The IDE is reporting errors because the components lack children props.

**Comment by nstoychev** [comment]
Fixed in our dev channel - version 5.4.0-dev.202205200719. See the following article about obtaining our development builds - https://www.telerik.com/kendo-react-ui/components/installation/development-builds/.
