### ISSUE TITLE
Dialog loses focus if last "focusable" item is disabled

### ISSUE THREAD

**Issue by mlloydwilliamson1** [telerik/kendo-react#1293]
## I'm submitting a...
Bug report

## Current behavior
If you have a dialog with some number of buttons/controls and are tabbing through them, if the last one is disabled, the whole dialog loses focus to the background document/page.

## Expected behavior
Dialog should maintain focus, and move focus back to the beginning (or focus the disabled element, if that makes any sense to do).

## Minimal reproduction of the problem with instructions
1. Open the below stackblitz demo
2. Focus on the dialog
3. Hit tab (continue til it loses focus out of the dialog)

https://stackblitz.com/edit/react-zzwfex

## What is the motivation or use case for changing the behavior?
It makes navigating the dialog unfriendly for the user, if the last control is disabled. I think the `Dialog.js` `onKeyDown` handler should maybe ignore `disabled` elements? Unsure what the solution telerik would prefer is.

![Screenshot from 2022-05-05 13-14-32](https://user-images.githubusercontent.com/102987074/167018142-ef097d20-beb9-40b2-9e7a-d2719a80ce3a.png)

**Comment by PekoPPT** [comment]
The issue is not replicable in the latest version of KendoReact. An edited version of the provided project(that uses KendoReact 8.1.1) can be tested here - https://stackblitz.com/edit/react-zzwfex-d9vdxq?file=index.html,app%2Fmain.jsx
