### ISSUE TITLE
hasRelativeStackingContext in the utils package violates CSP with an inline style

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1294]
The violation error is the following:
"_Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-Y+wsDh+eE='), or a nonce ('nonce-...') is required to enable inline execution_"

```
export const hasRelativeStackingContext = (elementSource?: HTMLElement) => {
    ...
    parent.innerHTML = `<div style="position: fixed; top: ${top}px;">child</div>`;
```

The ways of setting styles to an element that do not violate the CSP can be found in the following article:

- [https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src)

**Comment by nstoychev** [comment]
Fixed in [5.5.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#f41e9a37-40fc-55bf-b714-f3c8c7455a4e).
