### ISSUE TITLE
docs(pivotgrid): add Globalization article

### ISSUE THREAD

**Issue by kspeyanski** [telerik/kendo-react#1305]
Add `globalization` article to the [PivotGrid](https://www.telerik.com/kendo-react-ui/components/pivotgrid/) similar to all other packages.

We should be featuring both the `internationalization` and `localization` features of KendoReact. The overview example could be something like the following stackblitz:
https://stackblitz.com/edit/react-ed5en6-3529td?file=app%2Fes.json,app%2Fmain.tsx

**Comment by nstoychev** [comment]
Here it is: https://www.telerik.com/kendo-react-ui-develop/components/pivotgrid/globalization/
