### ISSUE TITLE
npx create-kendoreact-app doing nothing

### ISSUE THREAD

**Issue by iqoOopi** [telerik/kendo-react#1307]
![image](https://user-images.githubusercontent.com/46897552/169112841-37cd1d38-c328-4d63-89b2-2152eb575f1b.png)

I'm on node v16.15.0. Running npx create-kendoreact-app doing nothing, not creating anything for me.  However, npx create-react-app works. So something wrong with create-kendoreact-app

**Comment by simonssspirit** [comment]
reported again in 1567586

**Comment by Xizario** [comment]
Should work now, feel free to reopen if something is still not okay.
