### ISSUE TITLE
Setting appendTo for the DropDownList popupSettings throws error that the element is not a ReactElement

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1310]
The Popup expects an HTMLElement for the appendTo property, but when such is set to the DropDownList, it throws an error: "Failed prop type: Invalid prop `popupSettings.appendTo` of type `object` supplied to `DropDownList`, expected a single ReactElement",

When the same element is set to appendTo through the PopupPropsContext, no error is thrown:

- [https://stackblitz.com/edit/react-dtq1ex-adsxwb?file=app%2Fmain.tsx](https://stackblitz.com/edit/react-dtq1ex-adsxwb?file=app%2Fmain.tsx)

**Comment by kdikov82** [comment]
Note: The error seems to be thrown initially. In stackblitz you need to refresh the page with the refresh button in order to see the error again.

The error was also reported in Ticket ID: 1564798, but at that time I was not able to replicate it

**Comment by nstoychev** [comment]
Fixd in [v5.4.0-dev.202205271059](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#30baff50-dbc3-51b1-9593-a10bafe6ede1)
