### ISSUE TITLE
MultiColumnComboBox className property doesnt work any more.

### ISSUE THREAD

**Issue by Tommuh** [telerik/kendo-react#1313]
MultiColumnComboBox className property doesnt work any more since we upgraded from 5.1 to 5.3.

`<MultiColumnComboBox className="input-pickup" />`

![image](https://user-images.githubusercontent.com/2089879/169643729-0f81d0cd-7db9-4038-9ac6-ded0b27f529e.png)

**Comment by nstoychev** [comment]
Fixed in [v5.4.0-dev.202205271059](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#30baff50-dbc3-51b1-9593-a10bafe6ede1).

**Comment by Tommuh** [comment]
Thank you.
