### ISSUE TITLE
resizing grid locked columns shows content on the background when scrolling

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1315]
The issue is that if we resize (make smaller) any of the locked columns but the last one, the column content will get smaller, but the actual column will not get resized (the column to the right won't change position). This will cause the space between the smaller content and the edge of the column to show the scrolled content.  Can be reproduced here: https://stackblitz.com/edit/react-afhst2?file=app%2Fmain.tsx

Ticked ID: 1566183

**Comment by iadnonov** [comment]
Reported again in ticket: 1594875

**Comment by tmeindle** [comment]
This has already been reported here in December of 2019: https://github.com/telerik/kendo-react/issues/413.
