### ISSUE TITLE
Inconsistency in the "id" types between the DataModel and BreadcrumbLinkProps, BreadcrumbLinkMouseEvent, etc.

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1323]
This is the current interface of the DataModel accepted by the Breadcrumb:

The DataModel interface:
```
export interface DataModel {
    /**
     * Represents the `id` of the data object. Used for setting the key of the BreadcrumbListItem component and the `id` of the BreadcrumbLink component.
     */
    id: string;
```

Here is the BreadcrumbLinkProps:
```
export interface BreadcrumbLinkProps {
    /**
     * Sets the `id` property of the top `div` element of the BreadcrumbLink.
     */
    id?: string;
```

BreadcrumbLinkMouseEvent:
```
export interface BreadcrumbLinkMouseEvent extends BaseEvent<BreadcrumbLinkHandle> {
    /**
     * Represents the `id` of the `BreadcrumbLinkMouseEvent`.
     */
    id?: string;
}
```
Since the **data** property of the Breadcrumb is mandatory and the "**id**" of the DataModel is required, the "id" in the other interfaces should not be optional.

The optional "id?" is present in many of the interfaces, not only in the one listed above.

**Comment by nstoychev** [comment]
Fixed in our development channel version 5.5.0-dev.202206280851. See the following article about obtaining the development builds - https://www.telerik.com/kendo-react-ui/components/installation/development-builds/.
