### ISSUE TITLE
Form needs the children prop too

### ISSUE THREAD

**Issue by Jodelopa** [telerik/kendo-react#1325]
react 18 needs children props, in 5.4.0-dev.202205271059 its still missing

**Comment by nstoychev** [comment]
@Jodelopa - It's fixed in 5.4.0-dev.202206061009 and should be fine everywhere.

**Comment by Jodelopa** [comment]
in 5.4.0 realease this is still missing for me

**Comment by nstoychev** [comment]
Can you share a code snippet/example where the issue can be observed?

**Comment by Jodelopa** [comment]
solved, the problem was:
`<Form ...></Form>` 

i have to use the self closing variant:
`<Form ... />` 

even if no children exist
