### ISSUE TITLE
Switching between virtual scroll and pagination creates an empty space on top

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1327]
Steps to reproduce:

1.  With paging disabled, drag the scrollbar to scroll to the middle of the grid.

2.  Enable paging.  Notice that the scrollbar scrolls all the way to the bottom.  And if you scroll up, it's just an empty white space.

This can be reproduced in the following example:

https://stackblitz.com/edit/react-i16qtl-dkr2xu?file=app/main.tsx

**Comment by nstoychev** [comment]
Resolved in 5.12.0.
