### ISSUE TITLE
The virtualizationUtils.tsx in grids virtualization demo generate invalid number of columns at random

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-react#1329]
Can be replicated here:
https://www.telerik.com/kendo-react-ui/components/grid/examples/column-virtualization-headers/func/?theme=default-ocean-blue&themeVersion=5.4.1
Refresh several times.

The columns are randomly generated with intent to be 1000, but the function used can generate more than 1000 columns in its corner case. When this happens it looks like broken, because there are no data for these columns.

Expected behaviour: The `getColumns` to return array with exact length as `numberOfColumns`

**Comment by zdravkov** [comment]
Here is an updated version of the demo until we update the docs - https://stackblitz.com/edit/react-owa9xd?file=app%2FvirtualizationUtils.tsx

**Comment by bptodorova** [comment]
Fixed in version 5.10.0.
