### ISSUE TITLE
Add ability to add custom className to all components.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#133]
- [x] Button
- [x] ButtonGroup
- [x] DateInput
- [x] DatePicker
- [x] TimePicker
- [x] Calendar
- [x] Dialog
- [x] AutoComplete
- [x] ComboBox
- [x] DropDown
- [x] MultiSelect
- [x] Grid
- [x] Input
- [x] NumericTextBox
- [x] MaskedTextBox
- [x] Popup
- [x] Tooltip
- [x] Splitter
- [x] Upload
- [x] TreeView

**Comment by Weffe** [comment]
I support this ability too! I was looking to add a custom classname to the `Grid` component and realized it was not supported which sucks because I am trying to avoid inline styles for accessibility concerns.

**Comment by simonssspirit** [comment]
Available in the latest dev version: 2.8.0 

https://www.telerik.com/kendo-react-ui/components/installation/development-builds/
