### ISSUE TITLE
Fix `use-resize-item.js:55 Unable to preventDefault inside passive event listener invocation.` error while resizing an item in Scheduler

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1332]
Fix the `use-resize-item.js:55 Unable to preventDefault inside passive event listener invocation.` error thrown when resizing an item in Scheduler.

That can be reproduced in our demos when resizing a longer task:
[https://stackblitz.com/edit/react-drk6cf?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-drk6cf?file=app%2Fmain.jsx)

Reported in ticket: 1568523

**Comment by kspeyanski** [comment]
The issue has been fixed with `v5.5.0` of the `@progress/kendo-react-scheduler` package. Please refer to the [`Changelog`](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#f41e9a37-40fc-55bf-b714-f3c8c7455a4e) for the full list of changes.
