### ISSUE TITLE
Cannot delete the first digit in NumericTextBox when editing a big number in currency format

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1335]
Ticket ID: 1569331

NumericTextBox does not allow the deletion of the first digit when the format={c} and the number has more than 10 digits.

Reproduction steps:
1. Open [https://stackblitz.com/edit/react-thhbwq-5gvcnf?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-thhbwq-5gvcnf?file=app%2Fmain.jsx)
2. Focus NumericTextBox
3. Type a big number (e.g. $1,234,567,890.00)
4. Place the cursor after the first digit ($1) and try to delete it.

**Comment by kdikov82** [comment]
Duplicate: https://github.com/telerik/kendo-react/issues/1289
