### ISSUE TITLE
The filter components in the Grid restore deleted value when the filter operator is changed

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1338]
Steps to reproduced:
1) Open the following example: [https://stackblitz.com/edit/react-cwc4jd?file=app%2Fmain.tsx](https://stackblitz.com/edit/react-cwc4jd?file=app%2Fmain.tsx)
2) Enter 5 in the "UnitPrice" filter input
3) Clear the "UnitPrice" filter with the clear icon
4) Change the "UnitPrice" operator to "not equal to"

You will see that "5" is set back to the input element, even though the filter expression does not contain any value

**Comment by nstoychev** [comment]
Fixed in our development channel version 5.5.0-dev.202206280851. See the following article about obtaining the development builds - https://www.telerik.com/kendo-react-ui/components/installation/development-builds/.
