### ISSUE TITLE
colorPickerProps link is throwing 404

### ISSUE THREAD

**Issue by jrmcdona** [telerik/kendo-react#1339]
May I get the updated link to the colorPickerProps ?

You can find the broken link on this page:
https://www.telerik.com/kendo-react-ui/components/editor/tools/

![image](https://user-images.githubusercontent.com/4327773/175137399-d3b1bb5e-92ef-47b9-a90c-ecf077e02b01.png)

**Comment by Xizario** [comment]
https://www.telerik.com/kendo-react-ui/components/inputs/api/ColorPickerProps/

**Comment by nstoychev** [comment]
Fixed in our development channel version 5.5.0-dev.202206280851.

**Comment by nstoychev** [comment]
[5.5.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#f41e9a37-40fc-55bf-b714-f3c8c7455a4e) has been published.
