### ISSUE TITLE
Window onMove event has been raised incorrectly

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-react#1341]
Steps to reproduce:
1. Click "Change position" button
2. Click on the window title bar

Example: https://stackblitz.com/edit/react-4y29jj-sk9dxc?file=app%2Fmain.jsx

Actual: Clicking on the title bar triggers onMove event and the window change its position.

Expected: Window should not change its position

cc/ @kvelikov

**Comment by kdikov82** [comment]
Could be related with https://github.com/telerik/kendo-react/issues/1222
