### ISSUE TITLE
Lack of children in ChartSeriesItem

### ISSUE THREAD

**Issue by ShriHumrudha** [telerik/kendo-react#1342]
I am using 5.4.0 build with React 18.

![image](https://user-images.githubusercontent.com/89320816/175879122-65c6516a-e02c-4066-915e-8ddbf933ce94.png)

**Comment by nstoychev** [comment]
Fixed in our development channel version 5.5.0-dev.202206280851. See the following article about obtaining the development builds - https://www.telerik.com/kendo-react-ui/components/installation/development-builds/.

**Comment by nstoychev** [comment]
[5.5.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#f41e9a37-40fc-55bf-b714-f3c8c7455a4e) has been published.
