### ISSUE TITLE
How can the scale on the Y-axis of StockChart get rid of the $ sign？

### ISSUE THREAD

**Issue by yanglingnan** [telerik/kendo-react#1346]
![image](https://user-images.githubusercontent.com/36141906/176392669-e4713dcd-f78a-4b0a-9eeb-512f960e85e4.png)

**Comment by kdikov82** [comment]
The axis label can be customized through ChartValueAxis:
https://stackblitz.com/edit/react-etjtih?file=app%2Fmain.jsx
https://www.telerik.com/kendo-react-ui/components/charts/chart/elements/labels/#toc-setting-the-appearance
