### ISSUE TITLE
I can't export to PDF

### ISSUE THREAD

**Issue by rsshilli** [telerik/kendo-react#1351]
## I'm submitting a:
* Bug report 

## Current behavior
The KendoReact `<Editor>` component as well as the `<PDFExport>` component don't seem to work with the latest library versions. Specifically, I tried:
- Creating an Editor with the PDF export button on the toolbar
- Using the PDFExport React component with a div with the content

In both cases, I get the following error:
```
TypeError: Cannot assign to read only property 'saveAs' of object '#<KendoDrawingAdapter>'
```

## Expected behavior
I expect a PDF document to be downloaded.

## Minimal reproduction of the problem with instructions
I tried to create a minimal example but StackBlitz spins forever trying to setup a dev server with the latest versions. Here's my example, in case it works for you:

https://stackblitz.com/edit/kendo-react-editor-start-lzpwnf?file=src%2FApp.js

## Environment

Package versions:
<details> 
  <summary>Package versions for my entire project are below.</summary>
+-- @babel/cli@7.14.8
+-- @babel/core@7.15.0
+-- @babel/plugin-transform-runtime@7.15.0
+-- @babel/preset-env@7.15.0
+-- @babel/preset-react@7.14.5
+-- @babel/register@7.15.3
+-- @babel/runtime@7.15.3
+-- @cherrycircle/fda-docs@0.1.5 (github:CherryCircle/fda-docs#300d06ad1ae021f7bf013aee0e34a8d7654265b4)
+-- @cucumber/cucumber@7.2.1
+-- @dnd-kit/core@4.0.3
+-- @dnd-kit/modifiers@4.0.0
+-- @dnd-kit/sortable@5.1.0
+-- @dnd-kit/utilities@3.0.1
+-- @egjs/hammerjs@2.0.17
+-- @fortawesome/fontawesome-svg-core@1.2.17
+-- @fortawesome/free-regular-svg-icons@5.8.1
+-- @fortawesome/free-solid-svg-icons@5.14.0
+-- @fortawesome/react-fontawesome@0.1.4
+-- @okta/okta-sdk-nodejs@3.3.2
+-- @opentelemetry/api@0.14.0
+-- @opentelemetry/tracing@0.14.0
+-- @opentelemetry/web@0.14.0
+-- @progress/kendo-data-query@1.6.0
+-- @progress/kendo-drawing@1.16.3
+-- @progress/kendo-licensing@1.2.2
+-- @progress/kendo-react-animation@5.4.0
+-- @progress/kendo-react-buttons@5.4.0
+-- @progress/kendo-react-data-tools@5.4.0
+-- @progress/kendo-react-dateinputs@5.4.0
+-- @progress/kendo-react-dialogs@5.4.0
+-- @progress/kendo-react-dropdowns@5.4.0
+-- @progress/kendo-react-editor@5.4.0
+-- @progress/kendo-react-grid@5.4.0
+-- @progress/kendo-react-inputs@5.4.0
+-- @progress/kendo-react-intl@5.4.0
+-- @progress/kendo-react-layout@5.4.0
+-- @progress/kendo-react-pdf@5.4.0
+-- @progress/kendo-react-popup@5.4.0
+-- @progress/kendo-react-progressbars@5.4.0
+-- @progress/kendo-react-treeview@5.4.0
+-- @progress/kendo-theme-bootstrap@5.5.0
+-- @progress/kendo-theme-default@5.5.0
+-- @wdio/cli@7.7.3
+-- @wdio/cucumber-framework@7.7.7
+-- @wdio/dot-reporter@7.7.7
+-- @wdio/junit-reporter@7.7.8
+-- @wdio/local-runner@7.7.8
+-- @wdio/spec-reporter@7.7.7
+-- ajv@6.5.0
+-- amazon-cognito-identity-js@5.1.1
+-- archiver@5.0.2
+-- aws-sdk@2.991.0
+-- axios@0.24.0
+-- babel-eslint@10.1.0
+-- babel-loader@8.2.2
+-- babel-plugin-add-module-exports@1.0.4
+-- babel-plugin-i18next-extract@0.8.3
+-- bootstrap@4.5.2
+-- bootstrap-loader@3.0.4
+-- bootstrap-validator@0.11.9
+-- cheerio@0.22.0
+-- chromedriver@102.0.0
+-- cls-hooked@4.2.2
+-- component-emitter@1.3.0
+-- compression-webpack-plugin@6.1.1
+-- cryptr@6.0.2
+-- css-loader@3.4.2
+-- datatables.net@1.10.22
+-- datatables.net-bs4@1.10.22
+-- datatables.net-buttons@1.6.2
+-- datatables.net-scroller@2.0.3
+-- datatables.net-select@1.3.1
+-- decimal.js@10.2.0
+-- diff@3.5.0
+-- diff-match-patch@1.0.1
+-- docx4js@3.1.13
+-- dompurify@2.2.6
+-- dottie@2.0.2
+-- ejs@2.6.1
+-- escape-html@1.0.3
+-- eslint@7.5.0
+-- eslint-plugin-react@7.20.5
+-- extract-zip@2.0.1
+-- fflate@0.6.10
+-- file-loader@6.2.0
+-- fs-extra@6.0.1
+-- glob@7.1.7
+-- gojs@2.0.12
+-- googleapis@39.2.0
+-- highcharts@8.2.2
+-- html-pdf-chrome@0.5.0
+-- i18next@19.0.0
+-- i18next-browser-languagedetector@4.0.1
+-- i18next-xhr-backend@3.2.1
+-- jasmine@3.7.0
+-- jira-connector@2.8.0
+-- jquery@3.5.1
+-- jquery-datatables-checkboxes@1.2.11
+-- jquery-ui@1.12.1
+-- js-cookie@2.2.0
+-- js-levenshtein@1.1.6
+-- json-loader@0.5.7
+-- jsonwebtoken@8.5.1
+-- jwk-to-pem@2.0.4
+-- keycharm@0.4.0
+-- lambda-muhammara@1.0.0
+-- mathjs@5.4.1
+-- mini-css-extract-plugin@1.3.1
+-- moment@2.24.0
+-- moment-timezone@0.5.27
+-- muhammara@2.4.0
+-- mysql2@2.3.3
+-- node-sass@6.0.1
+-- npm@6.14.6
+-- pdf-parse@1.1.1
+-- pdfjs-dist@2.2.228
+-- pluralize@7.0.0
+-- png-to-jpeg@1.0.1
+-- prop-types@15.7.2
+-- propagating-hammerjs@1.5.0
+-- puppeteer-core@10.0.0
+-- raw-loader@4.0.2
+-- react@16.11.0
+-- react-bootstrap-typeahead@3.4.7
+-- react-datepicker@3.3.0
+-- react-dom@16.11.0
+-- react-draggable@4.2.0
+-- react-i18next@11.0.1
+-- react-radio-group@3.0.3
+-- react-split@2.0.7
+-- react-step-wizard@5.3.0
+-- react-switch@5.0.1
+-- redoc-cli@0.12.3
+-- replace-in-file-webpack-plugin@1.0.6
+-- request@2.87.0
+-- request-promise-native@1.0.5
+-- resolve-url-loader@2.3.0
+-- sass-loader@7.0.1
+-- sequelize@5.21.3
+-- serverless@2.72.2
+-- serverless-associate-waf@1.2.1
+-- serverless-offline@8.2.0
+-- serverless-openapi@1.1.2
+-- serverless-plugin-bind-deployment-id@2.0.2
+-- serverless-plugin-split-stacks@1.11.2
+-- serverless-plugin-tracing@2.0.0
+-- serverless-provisioned-concurrency-autoscaling@1.2.0
+-- serverless-prune-plugin@1.5.1
+-- serverless-s3-remover@0.6.0
+-- simple-statistics@7.0.2
+-- sockette@2.0.6
+-- stimulsoft-reports-js@2020.2.2
+-- style-loader@0.21.0
+-- stylelint@13.6.1
+-- stylelint-config-standard@20.0.0
+-- svgtodatauri@0.0.0
+-- terser-webpack-plugin@4.2.3
+-- timsort@0.3.0
+-- umzug@2.3.0
+-- url-loader@4.1.1
+-- uuid@7.0.3
+-- vis-data@7.1.0
+-- vis-network@8.5.3
+-- vis-timeline@7.4.2
+-- vis-util@4.3.4
+-- wdio-chromedriver-service@7.2.0
+-- wdio-cucumberjs-json-reporter@4.0.0
+-- webdriverio@7.10.1
+-- webpack@4.46.0
+-- webpack-cli@4.9.0
+-- webpack-dev-server@4.3.1
+-- xlsx@0.12.13
-- xml2js@0.4.19
</details>

Browser:

- Chrome (desktop) version 103.0.5060.66 (Official Build) (64-bit)

System:
- Node version: v14.19.0
- Platform:  Windows

**Comment by rsshilli** [comment]
I've recorded a bit of extra information here in a Loom: https://www.loom.com/share/5eda8329b2124d80a384a0bdce467d83?from_recorder=1&focus_title=1

**Comment by nstoychev** [comment]
Stackblitz does not work for some reason today. I run the example locally by downloading it, and then typed 'npm i && npm start' in the console, and did not see an issue.

Here is a CodeSandbox example which can also be tested- https://codesandbox.io/s/zealous-franklin-jq2oxw?file=/app/main.tsx.

As you can see, the export works as expected. Can you try to investigate it further on your side and provide example where the issue exists?

**Comment by rsshilli** [comment]
Thank you so much @nstoychev. That was very helpful. I had an old JS library (Stimulsoft) on the page and that was causing the problem. After removing it, everything works fine. Thank you!
