### ISSUE TITLE
Drawer does not inherit the RTL text direction of its parent elements

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1357]
Ticket ID: 1571566

Drawer does not inherit the text direction of its parent elements, keeping its `dir='rtl'` unless the `dir` prop is set directly in the component.

![image](https://user-images.githubusercontent.com/6196386/177600573-639e2b61-a5cc-4850-92c4-428a006a7a48.png)

Can be reproduced here: [https://stackblitz.com/edit/react-2n74ya-wjgbo4?file=app%2Fmain.jsx,app%2FDrawerRouterContainer.jsx](https://stackblitz.com/edit/react-2n74ya-wjgbo4?file=app%2Fmain.jsx,app%2FDrawerRouterContainer.jsx)

**Comment by silviyaboteva** [comment]
It is fixed in `v8.3.0-develop.7`. Will be abailable in the next official version.
