### ISSUE TITLE
ExcelExport "collapsible" property is ignored for grouped data

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1358]
Currently, the "collapsible" property of ExcelExport does not have any effect and does not render collapsible grouped rows in Excel:

- [https://stackblitz.com/edit/react-9cw5ko-3wyyhc?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-9cw5ko-3wyyhc?file=app%2Fmain.jsx)

The same works correctly for Kendo UI for jQuery/Angular:

- [https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/excel.collapsible](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/excel.collapsible)

**Comment by vveesseelliinnaa** [comment]
Reported again in Ticket ID: 1571856

**Comment by nstoychev** [comment]
Fixed in our dev channel version 5.5.1-dev.202207140841.

Example - https://stackblitz.com/edit/react-9cw5ko-vczqy2?file=app%2Fmain.jsx.

**Comment by nstoychev** [comment]
It looks like I did not save the example. It should be fine now.

Can you open it again (refresh it)?
