### ISSUE TITLE
How can the elements in the Chart be highlighted and displayed with Tooltip after being clicked?

### ISSUE THREAD

**Issue by yanglingnan** [telerik/kendo-react#1361]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by kdikov82** [comment]
Currently there is no built-in option for highlighting elements on click, but you can use the onSeriesClick event to display a tooltip/popup:
https://stackblitz.com/edit/react-lswrhf?file=app%2Fmain.tsx
https://www.telerik.com/kendo-react-ui/components/charts/api/ChartProps/#toc-onseriesclick
