### ISSUE TITLE
Drawer does not change rtl position dynamically 

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1362]
When trying to dynamically change the position of the Drawer to rtl the position does not change, because the absolute position is not being reset. 

This can be reproduced here:

https://stackblitz.com/edit/react-cj3axb-fndqfy?file=app%2FDrawerContainer.jsx,app%2Fstyles.css

related to this item: https://github.com/telerik/kendo-react/issues/1357

**Comment by kdikov82** [comment]
The entire Drawer must be re-mounted in order for the "dir" property of the component to change and in my opinion this is expected. Changing the "key" value of the Drawer after changing the "dir" value works correctly:
https://stackblitz.com/edit/react-cj3axb-bzt5ls?file=app%2FDrawerContainer.jsx
