### ISSUE TITLE
DateRangePicker doesnt open Calendar correctly in controlled mode

### ISSUE THREAD

**Issue by Jodelopa** [telerik/kendo-react#1366]
If the show propery is used in conjuction with onBlur and onFocus, a click on start date opens the calendar correcty. But if then directly is clicked on end-date input field, the calendar closes and is not opened again correctly

kendo 5.5.0
react 18

	import * as React from "react";
	import * as ReactDOM from "react-dom";
	import { DateRangePicker } from "@progress/kendo-react-dateinputs";

	const App = () => {
	  const [open, setOpen] = React.useState(false);

	  return (
		<div className="example-wrapper">
		  <DateRangePicker
			onBlur={() => setOpen(false)}
			onFocus={() => setOpen(true)}
			show={open}
		  />

		  <p>
			(use Alt+<code>↓</code> to open the calendar, <code>←</code> and{" "}
			<code>→</code> to navigate, <code>↑</code> to increment and{" "}
			<code>↓</code> to decrement the value)
		  </p>
		</div>
	  );
	};

	ReactDOM.render(<App />, document.querySelector("my-app"));

**Comment by kdikov82** [comment]
I have tested the scenario with the latest version and the issue could not be observed:
https://stackblitz.com/edit/react-vel7ra?file=app%2Fmain.jsx
