### ISSUE TITLE
DateTimePicker has misplaced numbers when using the latest theme version

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1368]
Steps to reproduce:

https://stackblitz.com/edit/react-eu79fc-ma2syw?file=package.json

- Open the DateTimePicker

- Navigate to "Time"

- Scroll down the list of minutes to minute 59

Expected:

- The minute "59" is located in the middle between the lines, like the minute "00"

Actual:

- The minute "59" is located near the bottom line

Reported in Ticket: 1572255

**Comment by kspeyanski** [comment]
The provided stackblitz example is using a customized version of the `@progress/kendo-theme-default`, and the issue is not reproducible with the standard distribution of the theme.

https://stackblitz.com/edit/react-eu79fc-yn9z3p?file=app/main.jsx

Please re-validate the issue or change the title.

**Comment by filipKovachev** [comment]
Tested again, the issue does indeed not reproduce with the standard distribution of the theme.
