### ISSUE TITLE
Resizing a column in the TreeList throws Unable to preventDefault inside passive event listener invocation error

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1372]
This can be reproduced in our Resizing demo here after a column has been resized:

https://www.telerik.com/kendo-react-ui/components/treelist/columns/resizing/

https://stackblitz.com/edit/react-xj9psf?file=app%2Fmain.tsx

Reported in Ticket: 1573278

**Comment by zdravkov** [comment]
fixed in the latest KendoReact version.
