### ISSUE TITLE
Flickering and undesired scroll glitch in Grid with virtual scrolling when using createRoot

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1374]
To observe the issue, open the following example and scroll using the mouse wheel:
[https://stackblitz.com/edit/react-ikkgsq-ffxlg5?file=app%2Fmain.jsx,app%2FrowRender.js](https://stackblitz.com/edit/react-ikkgsq-ffxlg5?file=app%2Fmain.jsx,app%2FrowRender.js)

Replacing createRoot with ReactDom.render resolves the issue:
[https://stackblitz.com/edit/react-ikkgsq-ffxlg5?file=app%2Fmain.jsx,app%2FrowRender.js](https://stackblitz.com/edit/react-ikkgsq-ffxlg5?file=app%2Fmain.jsx,app%2FrowRender.js)

**Comment by pao95** [comment]
Please, Is there a solution to this? I have the same issue. Using ReactDom.render works fine but shows a warning in the console "react-dom.development.js:86 Warning: ReactDOM.render is no longer supported in React 18."

**Comment by robv8r** [comment]
I've also replicated the issue (right before finding this issue)

Works in React 17
https://stackblitz.com/edit/react-hejynz?file=app%2Fmain.jsx

Flickers in React 18
https://stackblitz.com/edit/react-hejynz-pn7umx?file=app%2Fmain.jsx

**Comment by nstoychev** [comment]
Fixed in dev channel version 5.11.1-dev.202302071533.

Examples:
- https://stackblitz.com/edit/react-hejynz-hr2upm?file=app%2Fmain.jsx
- https://stackblitz.com/edit/react-ikkgsq-tomdrj?file=app%2Fmain.jsx,app%2FrowRender.js
