### ISSUE TITLE
React Virtual Grid with fixedScroll: after changing the data and scrolling, the grid scrolls back to top

### ISSUE THREAD

**Issue by L-Blondy** [telerik/kendo-react#1375]
## Current behavior
Kendo React Grid with props `fixedScroll={true} scrollable='virtual'` has its scroll position preserved after changing the data (e.g. adding an item).

**However** when trying to scroll the grid scrolls back to the top (an onPageChange event is fired with skip=0)

NOTE: with `scrollable='scrollable'` the issue does not occur

## Expected behavior

The scrolling position should be preserved, the grid should not scroll back to top

## Demo
See this demo: https://stackblitz.com/edit/react-avvlcm?file=app/main.jsx
- scroll down a bit
- add a row
- try to scroll

forked form kendo docs: https://www.telerik.com/kendo-react-ui/components/grid/scroll-modes/virtual/

**Comment by nstoychev** [comment]
Resolved in 5.12.0

Example: https://stackblitz.com/edit/react-dc7vv7-aix2eb?file=app%2Fmain.tsx.
