### ISSUE TITLE
DropDownButton text value is added to the "aria-label" of the generated Button, but it accepts ReactNode and not a string value

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1379]
This is the configuration of the Button generated by the DropDownButton:
```
            <Button
              ...
              aria-label={`${this.props.text} dropdownbutton`}
                    >
              {this.props.text}
```
This causes problems when the "text" is not a simple string value:
`<DropDownButton text={<div>Test</div>} />`

The above configuration generates the following label:
`aria-label="[object Object] dropdownbutton"`

We should either provide a new property that will be used for the aria-label or extract a text value from ReactNode, which in my opinion might cause more problems.

**Comment by kdikov82** [comment]
Here is an example: https://stackblitz.com/edit/react-e9qgsq?file=app%2Fmain.jsx

**Comment by kdikov82** [comment]
Temporary workaround:
[https://stackblitz.com/edit/react-somkf5?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-somkf5?file=app%2Fmain.jsx)

```
<DropDownButton
          text={<div>Test</div>}
          ref={(el) => {
            el.element.setAttribute(
              'aria-label',
              el.element.textContent + ' dropdownbutton'
            );
          }}
        />
```

**Comment by nstoychev** [comment]
`ariaLabel` prop has been added - https://www.telerik.com/kendo-react-ui/components/buttons/api/DropDownButtonProps/#toc-arialabel.
