### ISSUE TITLE
Grid reordarable is not working in React 18 with StrictMode

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1381]
Ticket ID: 1574563

Grid reordarable is not working in React 18 with StrictMode. This results in an inability to drag and drop columns.

[https://stackblitz.com/edit/react-exwbjg-zi1ajv?file=app%2Fmain.tsx](https://stackblitz.com/edit/react-exwbjg-zi1ajv?file=app%2Fmain.tsx )

**Comment by robv8r** [comment]
Any updates?

**Comment by nstoychev** [comment]
Working on it https://github.com/telerik/kendo-react/issues/1432.

**Comment by iadnonov** [comment]
Fixed in our dev channel version v5.8.1-dev.202210141030.

Example: https://stackblitz.com/edit/react-hai4nx-us6gvb?file=app/main.jsx
