### ISSUE TITLE
NumericTextBox becomes invalid with some decimal values within range

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1382]
In the following example, changing the value with the arrow to 0.70% will make the NumericTextBox state invalid, even though the value is valid:
[https://stackblitz.com/edit/react-hpnc5e?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-hpnc5e?file=app%2Fmain.jsx)

The issue is observed with 0.70, 0.90, 1.10, etc. 
The pattern seems to be due to the actual value being calculated with the given step, which for 0.70 for example is: "0.006999999999999999"

**Comment by InaGlushkova** [comment]
Introduced with version [v5.7.1-dev.202209200738](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#5b95557a-da96-5efa-983e-a599be810177).
