### ISSUE TITLE
Need customizing the Expand/collapse & selection columns design & order in the TreeList

### ISSUE THREAD

**Issue by lavanyakomarasamy** [telerik/kendo-react#1387]
* Documentation request

## Current behavior
currently I am getting like this
![image](https://user-images.githubusercontent.com/13619132/182929688-180bb0a2-bc38-4e77-8735-9811476c9d67.png)

## Expected behavior
I want to develop like below added screenshot
![image](https://user-images.githubusercontent.com/13619132/182929402-554f3a0f-542d-4ed0-88eb-582ae968efc7.png)

## Minimal reproduction of the problem with instructions
https://www.telerik.com/kendo-react-ui/treelist/

  1. Find an example in [the documentation](http://www.telerik.com/kendo-react-ui/components/) that looks similar to your case.
  2. Open it in Stackblitz by using the **OPEN IN STACKBLITZ** button.
  3. Modify the example, so that the issue is reproducible in it. Try to include the minimum possible amount of code.
  4. Save the example by using the blue **Save** button at the top.
  5. Copy the link from the address bar of the browser.
-->

## What is the motivation or use case for changing the behavior?
Our current requirement is that one.

Browser:
- Chrome (desktop) version  104

kindly provide sample link, please.

**Comment by nstoychev** [comment]
See the following example: https://stackblitz.com/edit/react-gx5elf?file=app%2Fmain.tsx.

It is probably not the same as the example you are looking for but it has similar checkboxes, implementation of a custom selection cell and will help you to implement your scenario.

**Comment by lavanyakomarasamy** [comment]
> See the following example: https://stackblitz.com/edit/react-gx5elf?file=app%2Fmain.tsx.
> 
> It is probably not the same as the example you are looking for but it has similar checkboxes, implementation of a custom selection cell and will help you to implement your scenario.

Really appreciate your fast reply @nstoychev 

I referred this already & implemented the same. But there is no way achieve what I want.
