### ISSUE TITLE
kendo-react grid horizontal scrolling after locked row.

### ISSUE THREAD

**Issue by shanqq** [telerik/kendo-react#1388]
Hello, I am trying to find the concept in which i can add the horizontal scrolling after the Locked columns.
as i can see https://stackblitz.com/run/?file=src%2Fapp%2Fapp.component.ts in this example, but it is in angular and i want it in react.

- Chrome (desktop) version XX
System:
- TypeScript version:
- Node version: 
-  Platform:   Windows
-  #question

**Comment by shanqq** [comment]
can anyone reply to this please.

**Comment by nstoychev** [comment]
The link with the example does not work. Can you check it?

**Comment by shanqq** [comment]
https://www.telerik.com/kendo-angular-ui/components/grid/columns/locked/ 
 how in this example the grid scroll is coming for the unlocked columns. i want this in react grid but i am not able to do this.

**Comment by shanqq** [comment]
https://demos.telerik.com/kendo-ui/grid/frozen-columns see this example

**Comment by nstoychev** [comment]
This is what we have in React - https://stackblitz.com/edit/react-ufhuta?file=app%2Fmain.tsx. More examples here - https://www.telerik.com/kendo-react-ui/components/grid/columns/locked/.

In React, locked columns are rendered with `position: sticky;`, in Angular/jQuery in a separate table.

**Comment by shanqq** [comment]
Yeah can we not achieve this in react as well.

**Comment by kdikov82** [comment]
Since we are rendering only one table for the data, the scrollbar can only be rendered through the entire table element (under all columns)
