### ISSUE TITLE
Sortable onDragEnd is never fired in strict mode

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1397]
Ticket ID: 1575550

In strict mode the onDragEnd event is never fired. In the [`useDraggable` method implementation](https://github.com/telerik/kendo-react-private/blob/6bf92ce64ae1e0baab7229ddcbc8b7d586b9be7a/packages/utils/src/hooks/useDraggable.tsx#L560), the following code is marking the component as unmounted but in StrictMode there is a fake mount/unmount cycle but the unmount variable is never reset back to true:

`React.useEffect(function () {
    return function () {
        unmount.current = true;
    };
}, []);`

The issue can be reproduced here:
https://stackblitz.com/edit/react-oskvw4?file=app%2Fmain.jsx,index.html

Related to: https://github.com/telerik/kendo-react-private/pull/1870

**Comment by vveesseelliinnaa** [comment]
Reported again in Ticket ID: 1592987

**Comment by WissamProgress** [comment]
Reported in Ticket ID: 1606520

**Comment by zdravkov** [comment]
fixed in 5.13.1 of KendoReact - https://stackblitz.com/edit/react-oskvw4-uqxkjf?file=app%2Fmain.jsx,index.html
