### ISSUE TITLE
Cannot open a dropdown if click occurs during transition

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1399]
Ticket ID: 1577275

When you click on a drop down while it's animated it's stuck in a state that it cannot be opened again. The issue is valid for all components that are opening and closing elements with animations like the popup, popover, dropdown button, etc.

Video - http://somup.com/c3jTQAUijY

**Comment by WissamProgress** [comment]
Reported again under - Ticket ID: 1578179

**Comment by iadnonov** [comment]
A fix is on the way. Till it's deployed, here is a workaround for the issue:  https://stackblitz.com/edit/react-y87uu6-4irzyc?file=app/main.tsx

**Comment by nstoychev** [comment]
Fixed in our dev channel version 5.8.0-dev.202210061034.

Example: https://stackblitz.com/edit/react-y87uu6-tp4dqz?file=app%2Fmain.tsx
