### ISSUE TITLE
Validitystyles has no effect on validity styling

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#140]
## I'm submitting a...
* Bug report 

## Current behavior
When applying validityStyles to a component, when the prop is set to false it does not remove the red border.

## Expected behavior
When the validityStyles prop is set to false, the components should not be styled in red

## Minimal reproduction of the problem with instructions

  1. Open the demo for the "Delaying Validity Styles" article. https://stackblitz.com/edit/react-ebmmmv?file=app/main.js
When it opens the inputs are styled red

## What is the motivation or use case for changing the behavior?
To not have form components open in an invalid state as soon as the user opens the page.

## Environment

Package versions:
   "react": "16.6.3",
    "react-dom": "16.6.3",
    "@progress/kendo-data-query": "1.5.0",
    "@progress/kendo-date-math": "1.3.2",
    "@progress/kendo-drawing": "1.5.7",
    "@progress/kendo-file-saver": "1.0.7",
    "@progress/kendo-react-animation": "2.4.0",
    "@progress/kendo-react-buttons": "2.4.0",
    "@progress/kendo-react-charts": "2.4.0",
    "@progress/kendo-react-conversational-ui": "2.4.0",
    "@progress/kendo-react-dateinputs": "2.4.0",
    "@progress/kendo-react-dialogs": "2.4.0",
    "@progress/kendo-react-dropdowns": "2.4.0",
    "@progress/kendo-react-excel-export": "2.4.0",
    "@progress/kendo-react-gauges": "2.4.0",
    "@progress/kendo-react-grid": "2.4.0",
    "@progress/kendo-react-inputs": "2.4.0",
    "@progress/kendo-react-intl": "2.4.0",
    "@progress/kendo-react-layout": "2.4.0",
    "@progress/kendo-react-pdf": "2.4.0",
    "@progress/kendo-react-tooltip": "2.4.0",
    "@progress/kendo-react-popup": "2.4.0",
    "@progress/kendo-react-ripple": "2.4.0",

Browser:

- Chrome (desktop) version 70

System:
- Platform: Windows

**Comment by kspeyanski** [comment]
Hello @k290 

We've published the fix in our `dev` channel under `2.5.0-dev.201812041132
` version, please refer to this article about [obtaining development build](https://www.telerik.com/kendo-react-ui/components/installation/development-builds/).

I've updated the [example](https://stackblitz.com/edit/react-pgagfs?file=app/main.js  to use the latest `dev` version.


Please let us know if you need further assistance.

**Comment by k290** [comment]
Thanks

**Comment by Xizario** [comment]
The official `v2.5.0` is resolving this.
