### ISSUE TITLE
Auto sizing of TextArea does not function properly on delete in controlled mode

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1400]
Ticket ID: 1577319

The text area will not decrease on deleting a row in controlled mode, when `autoSize={true}`.

Can be reproduced here:
[https://stackblitz.com/edit/react-h9mhm8-lnku4e?file=index.html
](https://stackblitz.com/edit/react-h9mhm8-lnku4e?file=index.html)

**Comment by nstoychev** [comment]
Fixed in our dev channel version 5.8.0-dev.202210061034.

Example: https://stackblitz.com/edit/react-h9mhm8-pmeggn?file=index.html
