### ISSUE TITLE
Badge component losing alert colors and shape when using latest theme version

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1407]
When using version 5.7.0 of the material theme, the Badge components loses the colored alert circles. 

This can be reproduced here:

https://stackblitz.com/edit/react-nz3sjb-ygnlvu?file=app/main.jsx

**Comment by kdikov82** [comment]
Seems to work correctly with the latest theme and packages (5.11.0):
https://stackblitz.com/edit/react-nz3sjb-8yuruh?file=index.html,app%2Fmain.jsx
