### ISSUE TITLE
Cannot set decimal separator in NumericTextBox on iPhone(iOS 12)

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#141]
Cannot set decimal separator in NumericTextBox on iPhone(iOS 12).

This occurs as we use input type tel, and on the new iOS, the keyboard that pops up for type tel does not contain a decimal symbol.

**Comment by Xizario** [comment]
`v2.6.0` is published with new property for the `NumericTextBox`. set `inputType="text"` to resolve the problem
