### ISSUE TITLE
Kendo Grid pagination issue

### ISSUE THREAD

**Issue by devenkoli** [telerik/kendo-react#1410]
## Kendo react grid pagination issue after installation of new version.

* We are using kendo react in one of our project. This one is to report the bug, i think is introduced after upgrading to 5.6.0

![grid paging issue](https://user-images.githubusercontent.com/40263137/189095838-129713f0-9cb0-429b-9574-5a1f779fa3eb.png)

Have a look into the following url, the issue can be demonstrated.
https://codesandbox.io/s/mcz7oj

I have looked into this, and found there is the class ` k-pager-wrap` which is not been added to the paging div in the new version and the pager does not align correctly in one line,  if i add that class manually it looks perfect.

Can you please check this one and reply if you guys are investigating this already and what's the status? 
After reverting back to v5.5.0, the issue still persists. how do we solve this, there are many areas in our application, where we are using this component.

**Comment by jchn-codes** [comment]
if you're using a (default) theme: make sure to update your css file. downloading the current version of my theme via the theme builder fixed this issue for me.

**Comment by kdikov82** [comment]
Using the latest theme version and the latest Grid package renders the pager correctly
