### ISSUE TITLE
Sortable with items having different height is causing items to keep switching places in some scenarios

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1411]
To observe the issue, open the following example:
[https://codesandbox.io/embed/gallant-glade-yfiu77?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/embed/gallant-glade-yfiu77?fontsize=14&hidenavigation=1&theme=dark)

Now move item3 slowly to move it above item n2 and after keep moving the mouse upwards slowly (even after the items switch places).

The problem is that we use the middle of the item to determine if it should move up/down, which in the case of items with different height does not work. 

We can introduce a threshold at the beginning and the end of the items (maybe 10px or something that can be set as a property) or use the smaller item height to calculate when the items should be changed.

**Comment by nstoychev** [comment]
Fixed in [v5.10.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#f1407191-3ec7-5f77-b7e8-e7a7305a128c).
