### ISSUE TITLE
Footer cell does not stick for the locked columns in the kendo grid

### ISSUE THREAD

**Issue by bvkavya** [telerik/kendo-react#1414]
Hi,

I have locked the first three columns and added a footer cell for the third column. Upon scrolling horizontally, the three columns in the content area are frozen but the footer cell is not frozen.  Tried it from Telerik example 
Could someone please help how to achieve frozen columns on the footer row in the kendo react code?

file=app%2Fmain.jsx
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { Grid, GridColumn as Column } from '@progress/kendo-react-grid';
import products from './products.json';

const UnitPriceCell = props => {
  const field = props.field || '';
  const min = products.reduce((acc, current) => Math.min(acc, current[field]), Number.MAX_VALUE);
  const max = products.reduce((acc, current) => Math.max(acc, current[field]), 0);
  return <td colSpan={props.colSpan} style={props.style}>
        min: {min}, max: {max}
      </td>;
};

const UnitsInStockCell = props => {
  const field = props.field || '';
  const total = products.reduce((acc, current) => acc + current[field], 0);
  return <td colSpan={props.colSpan} style={props.style}>
        total: {total}
      </td>;
};

const App = () => {
  return <Grid style={{
    height: '420px', width:"500px"
  }} data={products}>
        <Column width="10px" field="ProductID" title="ID" width="50px" locked={true}/>
        <Column width="150px" field="ProductName" title="Product Name" locked={true}/>
        <Column width="150px" field="UnitPrice" title="Unit Price" locked={true}
        footerCell={UnitPriceCell} />
        <Column width="150px" field="UnitsInStock" title="Units In Stock" footerCell={UnitsInStockCell} />
        <Column width="150px" field="Category.CategoryName" title="Category Name" />
      </Grid>;
};

ReactDOM.render(<App />, document.querySelector('my-app'));

**Comment by bptodorova** [comment]
Fixed in v5.17.0.
