### ISSUE TITLE
DropDownList selected list item doesn't have k-focus css class applied

### ISSUE THREAD

**Issue by mcr85** [telerik/kendo-react#1415]
## Current behavior
DropDownList selected list item doesn't have `k-focus` class applied. It only has `k-selected`.
In Kendo UI for Angular, selected item in DropDownList does get both `k-focus` and `k-selected`.
Other controls like ComboBox or MultiSelect in KendoReact also have both css classes applied on selected item in their dropdowns.

Note. When using filterable DropDownList and filtering out selected item, `k-focus` class is applied to first list item matching search term.

## Expected behavior
Selected dropdown list item in DropDownList component should have `k-focus` css class applied.

**Comment by kdikov82** [comment]
Duplicate: https://github.com/telerik/kendo-react/issues/867
