### ISSUE TITLE
Not possible to select Tuesday in DatePicker (triggers scrolling instead)

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1417]
Ticket ID: 1580067

Clicking over any Tuesday triggers scrolling of the DatePicker instead of selection of this day in Material theme.

video: [http://somup.com/c3QqDoUgOa](http://somup.com/c3QqDoUgOa)

Steps to reproduce:
1. Open [https://www.telerik.com/kendo-react-ui/components/dateinputs/datepicker/appearance/](https://www.telerik.com/kendo-react-ui/components/dateinputs/datepicker/appearance/)
2. Try to select any Tuesday from the loaded month.
Result: The calendar is scrolled and no date is selected. The hovering does not work as well.

**Comment by vveesseelliinnaa** [comment]
Reported again in Ticket ID: 1580211

**Comment by vveesseelliinnaa** [comment]
Reported again in BR ID: 1579889

**Comment by kikostadinov** [comment]
_It seems that the latest Chrome version does not handle elements with `overflow: hidden;` properly.
What currently happens is that Chrome thinks that the user clicks on the scrollbar of the `.k-calendar-navigation` element... scrollbar that shouldn't be accessible at all as it is a hidden element:_
![image](https://user-images.githubusercontent.com/27971306/191265984-9fe4862d-fbd3-40fb-bfde-c3c34d03f72c.png)

_A temporary workaround (until we fix it officially in our Kendo Themes) is to use the following CSS code (can be seen in action in [this Stackblitz example](https://stackblitz.com/edit/react-4jadf4?file=app%2Fmain.tsx)):_

`
.k-calendar-navigation {
    z-index: 1;
}
`

[Related to](https://github.com/telerik/kendo-angular/issues/3769#issuecomment-1251132955)
