### ISSUE TITLE
Drag and Drop wont Work on Empty Grid

### ISSUE THREAD

**Issue by aasigaaccenture** [telerik/kendo-react#1420]
Hi Kendo Team,

This is in relation on previous request of ours pertaining to dragging and dropping on grid.
See. [ticket] (https://github.com/telerik/kendo-react/issues/1088)

We have finally integrated your solution into our application. After some testing, we've found out that drag and drop wont work at all on an empty Grid. This scenario can also be recreated on your sample solution.

See. [sample](https://stackblitz.com/edit/react-kkucf8-sqcmsj?file=app/main.tsx) 

Tagging in @filipKovachev 

[Drag and Drop between empty grids.webm](https://user-images.githubusercontent.com/89938709/191261997-7fcfd53f-4c9b-462d-a2a2-c7dcb1a3d423.webm)

Thanks,
Algie Asiga
Nature's Bounty

**Comment by filipKovachev** [comment]
Hello,

I am looking into this scenario and will get back to you once I have a solution.

Regards,
Filip

**Comment by aasigaaccenture** [comment]
Hi @filipKovachev,

Thanks for your response. We've tested the sample above and found an issue on it.
1. Dropping on empty seems to be good only on 1 grid and not on vice versa.

Any thoughts on this? Thanks!
[Darg and Drop Issue.webm](https://user-images.githubusercontent.com/89938709/196477175-787ebc8e-6391-473e-8fcd-627fe5f39b6f.webm)

Regards,
Algie Asiga

**Comment by filipKovachev** [comment]
Thank you for the provided feedback, I will look into it and find a potential fix.

**Comment by aasigaaccenture** [comment]
Hi @filipKovachev,

Good Day! Would just like to ask if you have any updates on this one? 

Thanks,
Algie Asiga

**Comment by filipKovachev** [comment]
Hello @aasigaaccenture 

We have made the drag and drop work for the second empty Grid as well, however in order to fire the event passed via props initially, the items have to be dropped on the lower part of the "Drag items here" div, here is the updated example:

https://stackblitz.com/edit/react-kkucf8-1zwoyw?file=app/main.tsx
