### ISSUE TITLE
DropDownList with virtual scrolling breaks when the total is less than 70

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1421]
To observe the issue:
- Open the example: [https://stackblitz.com/edit/react-kkmsyv-csqwke?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-kkmsyv-csqwke?file=app%2Fmain.jsx)
- Open the popup and slowly scroll down to the bottom of the popup
- Without closing the popup starts scrolling up slowly 

The result - at some point, before reaching the top of the scroll bar the first item will be displayed and scrolling up will retrieve and render the first items again (duplicating items)

**Comment by DanielHTpg** [comment]
Any progress on this?

**Comment by elena-gancheva** [comment]
The fix is available in the latest `dev` version of the package and will be available in an official release version on 15th May
