### ISSUE TITLE
Grid locked rows with virtual scroll results in glitch

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1425]
When having a Grid with locked rows and virtual scroll enabled, locking a row and scrolling down results in repositioning the row.

This can be reproduced here by locking the first top row and then scrolling down:

https://codesandbox.io/s/nifty-tristan-vzumhq?file=/app/main.jsx:1491-1527

**Comment by kdikov82** [comment]
When you scroll down, the previous items are removed from the DOM, so it is expected for them to disappear. Having locked rows with virtual scrolling would be possible if we keep all rows rendered in the DOM, which defeats the purpose of the virtual scrolling. It should be considered as a limitation.
