### ISSUE TITLE
DropDownList is not focused on click if `opened` is set to `true`

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1426]
Ticket ID: 1581787

DropDownList is not focused on click if `opened` is set to `true`. 

Steps to reproduce:
1. Open [https://stackblitz.com/edit/react-rk9bht?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-rk9bht?file=app%2Fmain.jsx)
2. Click the DropDownList element
3. Try to use the up/down arrow keys

Result: The DropDownList element is not focused hence no navigation through its items occurs.

**Comment by bptodorova** [comment]
Fixed in version 5.12.0.
