### ISSUE TITLE
Popup stuck closed if toggled quickly

### ISSUE THREAD

**Issue by vladimirivanoviliev** [telerik/kendo-react#1428]
## I'm submitting a...
* Bug report 

## Current behavior
Currently if you go to the following demo and quickly toggle the show / hide button,  the Popup component stuck invisible and cannot be shown anymore. I reproduce this behaviour with Popup in controlled mode. As seen in the screenshot element is stuck with display none. I hit this issue with the DatePicker component and tabbing between input and picker, but narrowed it down to the Popup component and his animation. Current workaround for us is to disable the animation of the Popup as this is critical issue.

<img width="1736" alt="image" src="https://user-images.githubusercontent.com/2195951/194224635-20421696-2fe3-4c94-915b-d3eca370bd71.png">

## Expected behavior
The Popup controlled mode always work. 

## Minimal reproduction of the problem with instructions
Just open the following demo and toggle fast the Show / Hide button. I can reproduce it even with fewer than 5 clicks.
https://www.telerik.com/kendo-react-ui/components/popup/

## Environment

Package versions:
5.7.0

Browser:
- Chrome (desktop), latest (106.0.5249.91 ARM64)
- Safari (desktop), latest

**Comment by nstoychev** [comment]
Fixed in our dev channel version 5.8.0-dev.202210061034.

Example: https://stackblitz.com/edit/react-y87uu6-tp4dqz?file=app%2Fmain.tsx

**Comment by vladimirivanoviliev** [comment]
Thank you for the fast reaction :)
