### ISSUE TITLE
Autocapitalize doesn't work

### ISSUE THREAD

**Issue by derencel20** [telerik/kendo-react#143]
I tried using autocapitalize with <Input autoCapitalize="words" /> but it doesn't work. The docs also don't say anything on how to use the autoCapitalize props from here: https://www.telerik.com/kendo-react-ui/components/inputs/api/InputProps/

**Comment by simonssspirit** [comment]
@derencel20 These properties come directly from the MDN input specification and are not made from KendoReact:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize

If this property is working on standart HTML input in React, but does not work in our Input component, please let us know.

We are discusing  a way to show that these properties are auto generated based on the MDN specification.

**Comment by Xizario** [comment]
Docs are corrected now
