### ISSUE TITLE
Expected closed parenthesis at line 1, column 5 ( kendo-theme-default )

### ISSUE THREAD

**Issue by Scofez** [telerik/kendo-react#1430]
I'm trying to implement the kendoReact gantt chart in my application. I was using an old version of the kendo-theme-default <4.19.0> since I was also using the kendo-UI gantt chart with the kendo-gantt-react-wrapper. However when I imported the new kendoReact Gantt component, the styling was a little bit messed up so I figured out it should be related to the version of the kendo-theme-default, so I upgraded the version to <5.8.0>. An error popped up which is in the following picture.

![kendobug](https://user-images.githubusercontent.com/58665344/194366966-c4b6d1ab-fff5-4cfd-8d05-d9acc0efe3b2.png)

I commented this part of the code in the 
`\node_modules\@progress\kendo-theme-default\dist\all.scss` & `\node_modules\@progress\kendo-theme-default\dist\all.css` following this [thread](https://www.telerik.com/forums/build-error-1543213). 

![image](https://user-images.githubusercontent.com/58665344/194367528-8f8a281b-5779-4fc1-8e80-a99d23b6f4a5.png)

And everything seems to be working fine, even the Gantt Chart component was correctly imported and implemented without styling issues.
However this doesn't seem to me as an actual resolution to the problem, since every time the node_modules are installed this needs to be readdressed again and again which will create deployment issues.
Do you guys have any suggestion on how to solve it ? I would be really thankful.

**Comment by kdikov82** [comment]
This error could occur with old versions of React-scripts. Please try upgrading to react-scripts version 4+ and it should resolve the issue in question.
