### ISSUE TITLE
Grid column resize and reorder improvements in React 18

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-react#1432]
Currently, column resize and reorder does not work if React 18 API is used and StrictMode

Example: https://stackblitz.com/edit/react-hai4nx?file=app%2Fmain.jsx

**Comment by iadnonov** [comment]
Fixed in our dev channel version v5.8.1-dev.202210141030.

Example: https://stackblitz.com/edit/react-hai4nx-us6gvb?file=app/main.jsx
