### ISSUE TITLE
Scheduler split events when dragged in `DayView`

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1433]
The data passed to the `Scheduler` should have the `isAllDay` property set, or else it will cause the dragged item to split into two items (k-event-drag-hint).
Stackblitz example demonstrating this behavior:
[https://stackblitz.com/edit/react-zcgubd?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-zcgubd?file=app%2Fmain.jsx)

Ticket ID: 1582310

**Comment by filipKovachev** [comment]
Also reported in Ticket ID: 1633673

**Comment by WissamProgress** [comment]
Also reported in Ticket ID: 1654585
