### ISSUE TITLE
TreeList - Resizing a column causes list to scroll up

### ISSUE THREAD

**Issue by TonySixx** [telerik/kendo-react#1437]
When I'm scrolled down in list and then I resize column the list scrolls up, even though the row height is the same, so there is no reason to scroll up.

It can be seen in your demo: https://codesandbox.io/s/ye3yk8

**Comment by kdikov82** [comment]
Reproducible with the latest version (5.11.0) as well:
https://stackblitz.com/edit/react-dftwe6?file=app%2Fmain.jsx

**Comment by kdikov82** [comment]
There are also some scenarios where the scrolling occurs even without enabled resizing while clicking between header cells:
https://www.telerik.com/kendo-react-ui/components/treelist/

**Comment by lenski88** [comment]
the same situation. when is it going to be fixed? or is there some workaround?

**Comment by WissamProgress** [comment]
Reported in Ticket ID: 1615629

**Comment by WissamProgress** [comment]
Also reported in Ticket ID: 1619466

**Comment by WissamProgress** [comment]
Reported again in Ticket ID: 1642073

**Comment by zdravkov** [comment]
The issue is fixed in the latest dev version of [KendoReact](https://www.telerik.com/kendo-react-ui/components/) and will be available in our next offcial release - https://stackblitz.com/edit/react-dftwe6-4h8qtp?file=package.json
