### ISSUE TITLE
DateTimePicker setting year value doesn't work

### ISSUE THREAD

**Issue by dsuchan** [telerik/kendo-react#1439]
## I'm submitting a...
I have the same problem as you solved in [this thread](https://github.com/telerik/kendo-react/issues/251). I am using DateTimePicker component in combination with Field component because I need to communicate with event data object. Whenever I try to manually change the year value to 2023, it always changes to 1903. I've tried to use only DateTimePicker component and it does the exact same behaviour. Even if i try the temporary solution to set `format="g"` to the DateTimePicker component it doesn't work properly. This behaviour is still happening in your official documentation [here](https://www.telerik.com/kendo-react-ui/components/scheduler/customization/form/editor/#toc-extending-the-root-element). Just try to change year in any displayed event. It won't work manually, only through button that triggers the expandable editor for date/time.

## Current behavior
Can't manually set year value inside DateTimePicker component in combination with Field component.

## Expected behavior
To be able manually set year value inside DateTimePicker component in combination with Field component.

## Minimal reproduction of the problem with instructions
Documentation bug: https://www.telerik.com/kendo-react-ui/components/scheduler/customization/form/editor/#toc-extending-the-root-element

**Before editing:** 
![image](https://user-images.githubusercontent.com/87578818/196421651-134e9eed-3bdd-48df-a3fa-7db55002e61b.png)

**After editing:**
![image](https://user-images.githubusercontent.com/87578818/196421718-a38711cd-4e87-40f5-ac56-c416bd22c152.png)

**Actual code snippet:**
`<Field name="startDate" component={props.startEditor || DatePicker} as={DateTimePicker} />`

## What is the motivation or use case for changing the behavior?
Same as in the solved thread, to be able to type the date and time in a fast paced environment.

## Environment

Package versions:
```
    "@progress/kendo-date-math": "^1.5.7",
    "@progress/kendo-drawing": "^1.16.3",
    "@progress/kendo-licensing": "^1.2.2",
    "@progress/kendo-react-animation": "^5.5.0",
    "@progress/kendo-react-buttons": "^5.5.0",
    "@progress/kendo-react-dateinputs": "^5.5.0",
    "@progress/kendo-react-dialogs": "^5.5.0",
    "@progress/kendo-react-dropdowns": "^5.5.0",
    "@progress/kendo-react-form": "^5.5.0",
    "@progress/kendo-react-inputs": "^5.5.0",
    "@progress/kendo-react-intl": "^5.5.0",
    "@progress/kendo-react-popup": "^5.5.0",
    "@progress/kendo-react-scheduler": "^5.5.0",
    "@progress/kendo-react-treeview": "^5.5.0",
    "@progress/kendo-theme-default": "^5.5.0",
```

Browser:

- Chrome (desktop) version 106.0.5249.119
- Safari (desktop) version 16

System:
- TypeScript version: ^4.4.2 
- Node version: v16.14.2 & 8.5.0
- Platform: Mac, Windows

**Comment by kdikov82** [comment]
Since the issue is not reproducible with the DateTimePicker outside of the example, I am assuming that it could be due to the min/max properties that are set within the Scheduler Form for the editors.

**Comment by iadnonov** [comment]
Not reproducible with our latest version [v8.5.0](https://github.com/telerik/kendo-react-private/releases/tag/v8.5.0).

If you are still facing the issue, please do not hesitate to leave a comment with details, and we will investigate it further.
