### ISSUE TITLE
DropDownButton inside shadowRoot does not trigger onItemClick

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1441]
Within on onMouseDown we have the following check:
```
private onItemDown = (event: React.SyntheticEvent) => {
if (document.activeElement === this.element) {
event.preventDefault();
}
};
```

We can include second check for cases with shadowRoot:
`document.activeElement.shadowRoot.activeElement`

More info in ticket (ID: 1584714)

**Comment by veej** [comment]
is it possible to have an estimation of when this bug will be solved?

**Comment by kdikov82** [comment]
The problem can also be observed if you add handler for the "onClose" event:

- https://stackblitz.com/edit/react-azk47p?file=app%2Fmain.jsx
