### ISSUE TITLE
DateTimePicker onBlur Issue

### ISSUE THREAD

**Issue by Jtporter9** [telerik/kendo-react#1442]
## I'm submitting a...
I am seeing an issue where when attempting to select the times in the second step of the DateTimePicker component the `onBlur()` method is firing. This is happening when attempting to select the time, and the assumption is that the `onBlur()` method is used to close the popup when a user clicks outside of the popup or when the element is blurred. When the method fires while selecting the time this can cause the popup to close before a time is ever selected. 
* Bug report 

## Current behavior
`onBlur()` fires when trying to select the time in the DateTimePicker component

## Expected behavior
`onBlur()` should only fire when a user clicks outside of the popup

## Minimal reproduction of the problem with instructions

1. Documentation can be seen here [https://www.telerik.com/kendo-react-ui/components/dateinputs/datetimepicker/](url)
2. Open [https://stackblitz.com/edit/react-ecanfw?file=app%2Fmain.jsx](url)
3. Open DateTimePicker popup, select a date, then when you select any time you will see the onBlur has fired in the console. This should only happen outside of the popup. 

![image](https://user-images.githubusercontent.com/12839274/198137070-99aa8e9f-db1f-4854-8662-dde690afcaaf.png)

## What is the motivation or use case for changing the behavior?
To be able to select a Date and Time before the popup closes. 

## Environment

Package versions:
```
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "@progress/kendo-react-dateinputs": "5.9.0",
    "@progress/kendo-licensing": "1.2.2",
    "@progress/kendo-react-intl": "5.9.0"
```

Browser:
- Chrome (desktop) Version 106.0.5249.120 (Official Build) (64-bit)

System:
- TypeScript version: 4.8.4
- Node version: v16.18.0
- Platform:  Windows, Mac

**Comment by kdikov82** [comment]
The onBlur event, as described in the documention, fires each time any of the elements in the DateInputs is blurred.  
https://www.telerik.com/kendo-react-ui/components/dateinputs/api/DateTimePickerProps/#toc-onblur

For implementing closing of the popup on blur you need to include logic that checks which is the new target element and close the popup only if it is outside of the popup (or the input, depending on the exact requirement).
