### ISSUE TITLE
[BUG] [Upload] onStatusChange progress value issue with React 18

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1443]
The progress value within onStatusChange fails with React 18 (createRoot).
The issue can be observed in the following example:
- [https://stackblitz.com/edit/react-y8fuya-aytykk?file=app%2Fmain.tsx](https://stackblitz.com/edit/react-y8fuya-aytykk?file=app%2Fmain.tsx)

Here is the same with React 17:
- [https://stackblitz.com/edit/react-u2kbu9-ywthns?file=app%2Fmain.tsx](https://stackblitz.com/edit/react-u2kbu9-ywthns?file=app%2Fmain.tsx)

Most likely, the problem is due to the following change in React 18:
[https://github.com/reactwg/react-18/discussions/21](https://github.com/reactwg/react-18/discussions/21)

Public item in feedback portal: [https://feedback.telerik.com/kendo-react-ui/1583378-upload-event-newstate-batches-state-updates](https://feedback.telerik.com/kendo-react-ui/1583378-upload-event-newstate-batches-state-updates)

**Comment by iadnonov** [comment]
This behavior is not reproducible with latest version [v7.1.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#v7.1.0)
Can be tested in the following example: https://codesandbox.io/p/sandbox/optimistic-benz-g8wycp?file=%2Fapp%2Fmain.jsx
