### ISSUE TITLE
Could not resolve dependency progress/kendo-react-popup@"5.3.0-dev.202205041411"

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1445]
Ticket ID: 1585379

Dependency Conflict after Adding Kendo React Maps and the "Could not resolve dependency progress/kendo-react-popup@"5.3.0-dev.202205041411" error is thrown. 

To reproduce the error, add the following packages to the project and execute `npm install`:

`    "@progress/kendo-react-map": "^5.3.0",`
`    "@progress/kendo-react-popup": "^5.2.0",`

![image](https://user-images.githubusercontent.com/6196386/199202418-e804860f-3c86-4598-831f-cc7d3e333963.png)

Could be related to https://github.com/telerik/kendo-react-private/commit/c46d74fa8f4d5735f414c0dc05da902357717017

**Comment by vveesseelliinnaa** [comment]
Reported here as well: Ticket ID: 1585154

**Comment by nstoychev** [comment]
Fixed in version 5.9.1-dev.202211011805.
