### ISSUE TITLE
TabStrip component errors with only one TabStripTab

### ISSUE THREAD

**Issue by gridbox** [telerik/kendo-react#145]
## I'm submitting a...
* Bug report 

## Current behavior
Using TabStrip with only one TabStripTab results in an error of `Cannot read property 'props' of undefined`

## Expected behavior
TabStrip can function with only one tab.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-sdnxrw

## What is the motivation or use case for changing the behavior?
We have an application where we are showing Excel previews with the Kendo React Grid component.  We have a requirement to mimic the look and feel of Excel to include sheets.  My plan is to use the TabStrip component for sheet navigation.  There may not always be > 1 sheet initially and sheets can be dynamically added. I expect the TabStrip component to function with >= 1 TabStripTab.

**Comment by Xizario** [comment]
Fixed in `2.5.0-dev.201812130935`
