### ISSUE TITLE
Editor can't delete text with backspace when opened in StackBlitz or CodeSandBox

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1451]
Editor can't delete text with backspace when opened in StackBlitz or CodeSandBox. This issue only happens with versions `above` @5.7.0 when opened in StackBlitz, and @5.8.0 in CodeSandBox. When run locally, this issue can't be reproduced.

Steps to reproduce:
1. Open any example of the Editor from the documentation in StackBlitz or CodeSandBox
2. Remove all the text that is passed to the `value` or `defaultContent` prop of the Editor like this sample - https://stackblitz.com/edit/react-wfy9lw?file=app%2Fcontent.js,app%2Fmain.jsx
3. Write any text inside the component then try to delete it with backspace

Result: the text will not be deleted

Reported in Ticket ID: 1587327

**Comment by WissamProgress** [comment]
Reported in Ticket ID: 1593040

**Comment by nstoychev** [comment]
Fixed in version 5.11.0-dev.202301301227.

Example: https://stackblitz.com/edit/react-5dwbze?file=app%2Fmain.tsx

**Comment by nstoychev** [comment]
We published v5.11.0.
