### ISSUE TITLE
ColorGradient Slider gets stuck when the RGB values are equal

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1452]
ColorGradient Slider for changing the color gets stuck when Red, Green, and Blue values are equal. This issue is present in ColorGradient, ColorPicker with the `view` prop set to "gradient", and the FlatColorPicker components.

Steps to reproduce this bug:

1. Open an example of one of the above components from the documentation such as this example of the FlatColorPicker -  [https://www.telerik.com/kendo-react-ui/components/inputs/flatcolorpicker/](https://www.telerik.com/kendo-react-ui/components/inputs/flatcolorpicker/)
2. Set the RGB colors to equal values by typing them manually or picking the color with a mouse click
3. Try to move the Slider which normally changes the color

Result: The Slider is stuck in one place and doesn't change the color

Reported in Ticket ID: 1587728

**Comment by vveesseelliinnaa** [comment]
Reported again in Ticket ID: 1626764

**Comment by WissamProgress** [comment]
Also reported in Ticket ID: 1658295

**Comment by InaGlushkova** [comment]
Reported again in Ticket ID: 1666773

**Comment by iadnonov** [comment]
The issue is fixed in our latest develop version 9.1.0-develop.2
