### ISSUE TITLE
SchedulerProportionalViewItem throws error in WeekView on drag

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1456]
Dragging an SchedulerProportionalViewItem throws an error in WeekView:
[https://stackblitz.com/edit/react-rcur2z?file=app%2Fmain.tsx](https://stackblitz.com/edit/react-rcur2z?file=app%2Fmain.tsx)

**Comment by zdravkov** [comment]
fixed in 5.13.1 of KendoReact - https://stackblitz.com/edit/react-rcur2z-j6jzu5?file=app%2Fmain.tsx
