### ISSUE TITLE
Datepicker validation message is not annonce by screen reader 

### ISSUE THREAD

**Issue by Maxim-Malevich** [telerik/kendo-react#1459]
## I'm submitting a...
* Bug report i guess

## Current behavior
Datepicker validation message is not annonce by screen reader (chrome extension). Using screen reader extension and demo from website. Also can't found any properties for announcing validation messages. Browser stack's screen reader read it fine. 

## Expected behavior
When datepicker value is not valid and we havw validation message inside tooltip - it sould be read by screen reader.

## Minimal reproduction of the problem with instructions
https://github.com/MaxMalevich/react-datepicker

It's code without changes from your demo 
https://www.telerik.com/kendo-react-ui/components/dateinputs/datepicker/forms/

## What is the motivation or use case for changing the behavior?
I'm developing some app and want to use your datepicker, but also I need that my app was at hogh level of accessability. So validation message announcement must have for me.

## Environment

Package versions:
4.5.0

Browser:
- Chrome (desktop) version latest with installed screen reader extension. 

Maybe it's problem of screen reader extension?

**Comment by kdikov82** [comment]
I have tested the demo in question with NVDA and it announce the browser validation message correctly.
I have also tested the Form validation demo and the validation messages is announced there as well:
https://www.telerik.com/kendo-react-ui/components/form/validation/#toc-field-validation

Tested with version 5.11.0
