### ISSUE TITLE
Ellipsis is shown next to the checkboxes when using the material theme

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1461]
When using the material theme, an ellipsis is rendered next to the checkboxes in the column:

https://stackblitz.com/edit/react-pywn9x-ep2fic?file=app/main.jsx

If the width of the column is set to a value higher than 60px they disappear.

**Comment by silviyaboteva** [comment]
This is an expected output as the column does not have enough space for the checkbox to fit in. Reproducible in other suites as well: https://stackblitz.com/edit/angular-w13tdd?file=src%2Findex.html,src%2Fapp%2Fapp.component.ts

There are two possible solutions:
1. Shink the column to 40px to hide the ellipsis.
2. Expand the column to 65px so the checkbox has enough space to render.

Demo, demonstrating the above-mentioned approaches: https://stackblitz.com/edit/react-klwuhj-zl1uen?file=index.html,app%2Fapp.tsx
