### ISSUE TITLE
DropDownList with virtualization displays empty rows when last item is selected and is then opened again

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1463]
When enabling virtualization, selecting the last item in the DropDownList and then reopening it displays empty rows until you scroll:

https://stackblitz.com/edit/react-frehuf?file=app%2Fmain.jsx

**Comment by vveesseelliinnaa** [comment]
Duplicated with this one - https://github.com/telerik/kendo-react/issues/1450
