### ISSUE TITLE
Data Grid selection does not work with custom Grid Cells

### ISSUE THREAD

**Issue by samuelcolburn** [telerik/kendo-react#1464]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Current behavior

When using custom grid cells, grid selection doesn't seem to work/be able to select them, especially when selecting multiple.

## Expected behavior

They should work just like other cells.

## Minimal reproduction of the problem with instructions

See stackblitz link. Copy and pasted the "custom cell" example into the "grid selection" example and it does not work.

https://stackblitz.com/edit/react-ygeblv?file=app/main.jsx

## Environment
Win 10
Microsoft Edge
Version 108.0.1462.46 (Official build) (64-bit)

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by kdikov82** [comment]
With custom cell and enabled cell selection (and keyboard navigation) you need to add additional logic that adds the styles for the selected state. Here is an example demonstrating such implementation:
https://stackblitz.com/edit/react-ts-cznggm?file=CustomCell.tsx
