### ISSUE TITLE
Custom fonts works only for DejaVu Sans?

### ISSUE THREAD

**Issue by sumitks866** [telerik/kendo-react#1468]
## I'm submitting a...
* Documentation issue or request

## Current behavior
I am trying to generate a PDF using savePDF method. The file contains Japanese, Korean, Cyrillic and Latin texts. I downloaded Arial Unicode MS and DejaVu Sans  and tried to import from my local. It works fine when declaring DejaVu Sans using `@font-face` but  doesn't works for Arial Unicode MS. Interestingly, when I change font-famliy to DejaVu Sans for Arial Unicode MS it works perfectly fine.

```
/*Doesn't works*/
@font-face {
  font-family: 'Arial Unicode MS';
  src: url('./fonts/arialms.ttf') format('truetype');
}

/*Works only for Cyrillic and Latin texts*/
@font-face {
  font-family: 'DejaVu Sans';
  src: url('./fonts/DejaVuSans.ttf') format('truetype');
} 

/*Works for all texts*/
@font-face {
  font-family: 'DejaVu Sans';
  src: url('./fonts/arialms.ttf') format('truetype');
}

```

## Expected behavior
Should work for all font family.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/github-9ryvpw-vu9c7q?file=src/index.css

## Environment

Package versions:
```
{
  "name": "react-typescript",
  "version": "1.0.0",
  "description": "React and TypeScript example starter project",
  "keywords": [
    "typescript",
    "react",
    "starter"
  ],
  "main": "src/index.tsx",
  "dependencies": {
    "@progress/kendo-drawing": "1.6.0",
    "@progress/kendo-react-pdf": "3.12.0",
    "prop-types": "15.8.1",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-scripts": "4.0.3"
  },
  "devDependencies": {
    "@types/react": "18.0.25",
    "@types/react-dom": "18.0.9",
    "typescript": "4.4.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
```

Browser:

- Chrome (desktop) version 108.0.0.0

System:
- TypeScript version: 4.4.2
- Node version: XX 
- Platform:   Linux, Windows

**Comment by kdikov82** [comment]
I have tested the provided example and it failed to load the font from the cdn. In general, the fonts that will be used within the exported content must support all characters that will be within the export. Detailed information on this topic can be found in the following help article:
https://www.telerik.com/kendo-react-ui/components/drawing/pdf-output/embedded-fonts/
