### ISSUE TITLE
Scheduler does not display recurring events 

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1477]
When setting a monthly recurrence to repeat every second Sunday, the event is not displayed at all.

This can be seen in our overview demo:

https://stackblitz.com/edit/react-yrtqhv?file=app%2Fmain.jsx

Steps to reproduce:

1. Create a recurring event that repeats every second Sunday.

Ticket ID: 1595236

**Comment by saravanan-smartmd** [comment]
Any updates on this, folks? This is a pretty big bug we think. Thank you!

**Comment by filipKovachev** [comment]
Hello, Saravanan,

Once an issue has been logged we prioritize it based on the severity and then plan it accordingly based on our internal planning. The GitHub item can be used to track its progress, if a workaround has been found, the issue will be updated or if it has been fixed it will be closed.

I will reach out to the team in order to determine if we can fix this for our next scheduled release.

Regards,
Filip

**Comment by SaravananSubramanian** [comment]
Just following up to see if there has been any resolution to this matter since it has now been several months since we reported this critical bug. If no resolution is being planned for the time being, it would help us to make the decision to move away from Telerik product to something else. Please let us know. Thanks!

**Comment by Yanko-Georgiev** [comment]
In addition, selecting the Day from the dropdown first and then selecting from the other dropdown is not forking. For instance, first select "Sunday" and then try selecting "Second." Notice that it is not working.
Reported in: 1667746
