### ISSUE TITLE
[TreeList] TreeList with custom headerCell does not provide an option for using a columnMenu

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1478]
We do not expose onFilterChange, onSortChange nor the columnMenuProps (as in the Grid) within the custom header cell, which prevents the implementation of the columnMenu with a custom headerCell:
[https://stackblitz.com/edit/react-ucebku-pptfkn?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-ucebku-pptfkn?file=app%2Fmain.jsx)

Here is how this scenario is handled in the Grid:
[https://stackblitz.com/edit/react-febfzz-lcwc4w?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-febfzz-lcwc4w?file=app%2Fmain.jsx)

**Comment by bptodorova** [comment]
Fixed in version 5.16.0
