### ISSUE TITLE
PDF Viewer returns error in strict mode

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1479]
When using strict mode with the PDF Viewer, the following error is returned: Cannot read properties of undefined (reading 'destroy')

This can be observed in the following example:

https://stackblitz.com/edit/react-ts-zo8zsa?file=index.tsx

If strict mode is disabled everything works as expected.

Ticket ID: 1595693

**Comment by nstoychev** [comment]
Fixed in v5.11.0.
