### ISSUE TITLE
ComboBox filter not cleared on blur

### ISSUE THREAD

**Issue by thejroberts** [telerik/kendo-react#148]
## I'm submitting a...

* Regression report 

## Current behavior
When using the [filter](https://www.telerik.com/kendo-react-ui/components/dropdowns/combobox/filtering/) configuration, if no valid item is selected and the input loses focus, the filter text is cleared but the data is still filtered.

## Expected behavior
Upon losing focus, the filter text should be cleared and a filter change event fired to notify any filtering code that it should restore the data.

## Minimal reproduction of the problem with instructions

This bug can be reproduced using the example on the [filtering page](https://www.telerik.com/kendo-react-ui/components/dropdowns/combobox/filtering/) (or on [StackBlitz](https://82huhn.run.stackblitz.io)) with no modifications. Simply type "d" into the dropdown, click away the dropdown to remove focus and close the list, then click the button to open the list again. Notice that the options remain filtered (only "Medium" appears) while there is no text in the search bar.

## Notes
This is possibly related to issue #84.

**Comment by Xizario** [comment]
`v2.6.0` is published.
