### ISSUE TITLE
Scheduler marks all items selected on week change

### ISSUE THREAD

**Issue by jemunk** [telerik/kendo-react#1483]
## I'm submitting a...
* Bug report 

## Current behavior
When 'selecting' is enabled in the Scheduler and you select an item, then changing to next week and again back to first week, all items in the week are selected.

## Expected behavior
No items are selected after change of week

## Minimal reproduction of the problem with instructions
Issue is recreated in this example
https://stackblitz.com/edit/react-pqpcbx?file=index.html

## What is the motivation or use case for changing the behavior?
Seems to be a very common case, that only requires enabling 'selecting'. I can only imagine that all your customers having this enabled would experience this.

Browser:
Seems to be all browsers

**Comment by kdikov82** [comment]
Seems to be an issue with the WeekView
