### ISSUE TITLE
The target in the onPageChange needed for using custom Pager in the Grid expects Pager type

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1485]
Currently it is not possible to pass Pager as a target when using onPageChange of the custom Pager in the Grid. We need to change the target to accept any:

- https://www.telerik.com/kendo-react-ui/components/datatools/api/PageChangeEvent/

Here is a temporary workaround that can be used:

- https://stackblitz.com/edit/react-trdu4h?file=app%2Fmain.tsx

**Comment by bptodorova** [comment]
Fixed in version 5.12.0.
