### ISSUE TITLE
ClassName provided for Grid is used both on div and table

### ISSUE THREAD

**Issue by Mako217** [telerik/kendo-react#1490]
## I'm submitting a...
* Regression report

## Current behavior
I am not sure whether this is a bug or intentional behavior, but after upgrading from 5.9.0 to 5.10.1 the grid behavior changed. I've checked also in 5.11.0, and the issue persists. When providing a className value for the Grid component, it is used both on the main div of the Grid and in the table in which the data is displayed, so the same className is used twice. I would like to know if this is intentional or will be changed in future versions.

## Expected behavior
The className is used only for the main div of the grid.

**MINIMAL DEMO**
Codesandbox: https://codesandbox.io/s/cranky-tesla-o7ufvr?file=/app/main.jsx

**STEPS TO REPRODUCE**
1. Provide a custom className value for the Grid
2. Inspect the page with devtools
3. Look at the classes of the main div of the Grid, and the table inside the k-grid-container div. They both use the custom className provided earlier.

## What is the motivation or use case for changing the behavior?
It broke some of the selenium tests where we used the grid className as a selector. I would like to know if I should treat this change as intentional, and change our solution to work correctly with it, or to treat it as a bug and expect it to be fixed in the future.

## Environment

Package versions:
First noticed after upgrade to 5.10.1, but still persists in 5.11.0

Browser:
- Chrome (desktop) version 109.0.5414.121
- Firefox version 110.0b9 
- Edge version 109.0.1518.78

System:
- TypeScript version: 4.9.4
- Node version: 16.17.0 | npm: 9.4.0
- Platform:  Windows

**Comment by zdravkov** [comment]
Hey @Mako217 ,

Thank you for reporting the issue, it seems like a bug and we will do our best to add it in the next patch version available.

Greetings,
Plamen

**Comment by bptodorova** [comment]
Fixed in version 5.12.0.
