### ISSUE TITLE
Setting a Minimum Column Width example with Hooks

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1498]
In the example with functions, the columns always have a fixed width and do not expand/collapse when resizing the window - [https://www.telerik.com/kendo-react-ui/components/grid/columns/width/#toc-setting-a-minimum-column-width](https://www.telerik.com/kendo-react-ui/components/grid/columns/width/#toc-setting-a-minimum-column-width)

On the other hand, the example with classes is working properly - [https://stackblitz.com/edit/react-wwto1g?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-wwto1g?file=app%2Fmain.jsx)

**Comment by oasaleh** [comment]
Any updates? This is driving me insane. I tried to implement forceUpdate but it won't refresh, and performance dropped.

**Comment by oasaleh** [comment]
I found a solution. `minGridWidth` is not a number, it's a reference. That means you have to access its `current` property. It's still not behaving like expected (i.e., the last column got more space than needed on bigger screens.) Give this updated `handleResize` function a try.
```
const handleResize = () => {
    if (grid.current.offsetWidth < minGridWidth.current && !applyMinWidth) {
        setApplyMinWidth(true);
    } else if (grid.current.offsetWidth > minGridWidth.current) {
        setGridCurrent(grid.current.offsetWidth);
        setApplyMinWidth(false);
    }
};
```

**Comment by WissamProgress** [comment]
Thank you @oasaleh, that was indeed the issue. Regarding the spacing, it is expected that when the Grid is larger than the combined minimum widths of the columns, the columns will proportionally expand to fill the remaining space.

If you want the columns to have specific widths, I can recommend setting their [width](https://www.telerik.com/kendo-react-ui/components/grid/api/GridColumnProps/#toc-width) props (if it is not set it will default to auto and expand) - [https://stackblitz.com/edit/react-wvaujr?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-wvaujr?file=app%2Fmain.jsx)

If you are referring to a different behavior, could you please provide us with more information or a screenshot/video?
