### ISSUE TITLE
Tooltip with position "auto" goes outside of the visible area in some cases

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1502]
With "position" set to "auto", the Tooltip should change its position based on the available space, but in some cases even if the entire tooltip can be rendered by changing its position, it goes outside of the screen.

In the following example, if you make the iframe small and leave any of the anchor elements to be at the right end of the window and hover over it, the tooltip will be set with position "right" automatically and cut the popup content:
https://stackblitz.com/edit/react-qcnyek?file=app%2Fmain.jsx

![c8a120fc-5376-4de1-8a77-20486d53c61b_reproimg](https://user-images.githubusercontent.com/11787141/223083055-621d3f62-236e-406c-9b65-123c721cb833.png)

**Comment by WissamProgress** [comment]
This is related to the applied styles in the content template. The width in the div wrapper is set to `300px`, and therefore the width will not be set based on the available space.

In addition, the `text-nowrap` class sets the `white-space` CSS property to [nowrap](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#nowrap) which surpressed the line breaks.

When these styles are not present, the Tooltip that has its `position` property set to `auto` will be rendered based on the available space.
