### ISSUE TITLE
Dragging and dropping the same item multiple times from a Grid to a Scheduler displays error

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1504]
The following demo works as expected, however when the user drags and drops the same item more than once, the following error is observed:

https://stackblitz.com/edit/react-ev3kjn?file=app%2Fmain.jsx

```
Warning: Encountered two children with the same key, `1:0:2`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    at div
    at div
    at SchedulerViewContext
 ```
This also affects the overall performance, since dragging and dropping becomes slower after the errors are triggered.

**Comment by zdravkov** [comment]
We could update the demo and assign a guid to the dropped scheduler event id instead of the taskID so that the ids are not duplicated:
```
   let newEvent = {
            id: guid(),
            title: dragItem.title,
            StartTimezone: null,
            start: startDate,
            end: endDate
        };
```
Here is the updated example - https://stackblitz.com/edit/react-ev3kjn-giqtsv?file=app%2Fmain.jsx
