### ISSUE TITLE
SplitButton themeColor missing error option

### ISSUE THREAD

**Issue by PaitoAnderson** [telerik/kendo-react#1514]
<img width="873" alt="Screenshot 2023-03-19 at 3 37 16 PM" src="https://user-images.githubusercontent.com/4108718/226204702-7708c5e1-331d-4d0c-9f6b-2180eb06f7b8.png">

## I'm submitting a...
* Bug report 

## Current behavior
`<SplitButton />` `themeColor` doesn't allow `error` type.

## Expected behavior
You can use `error` as a `themeColor` for `<SplitButton />`

## Minimal reproduction of the problem with instructions
`<SplitButton themeColor='error' />` in TypeScript.

## Environment

Package versions:

```

```

Browser:

System:
- TypeScript version: 4.9.5
- Node version: v19.2.0
- Platform:  macOS

**Comment by PaitoAnderson** [comment]
Also missing on `DropDownButtonProps`.

**Comment by PekoPPT** [comment]
The issue is fixed for both the SplitButton and DropDownButton components in version 6.0.0 of the KendoReact components . Here is a runnable example - https://codesandbox.io/s/small-bush-779g7x?file=/app/main.jsx

**Comment by PaitoAnderson** [comment]
Thank you!
