### ISSUE TITLE
Unable to conditionally render a TabStripTab: Exception is thrown

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#152]
## I'm submitting a...

* Bug report 

## Current behavior
When conditionally rendering a TabStripTab, the parent TabStrip thinks that the expression is a child and tries to render it, leading to the error: Cannot read property 'props' of undefined

## Expected behavior
I would expect expressions for conditional rendering to be allowed inside a TabStrip.

FYI another similar library also had this exact issue and here is how they resolved it:
https://github.com/grommet/grommet/issues/1159

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-4kknwi?file=app/main.js

## What is the motivation or use case for changing the behavior?
Ability to hide tabs and perform other expressions inside tabStrips

## Environment

Package versions:
    "react": "16.7.0",
    "react-dom": "16.7.0",
    "@progress/kendo-react-buttons": "2.5.0",
    "@progress/kendo-react-charts": "2.5.0",
    "@progress/kendo-react-conversational-ui": "2.5.0",
    "@progress/kendo-react-dateinputs": "2.5.0",
    "@progress/kendo-react-dialogs": "2.5.0",
    "@progress/kendo-react-dropdowns": "2.5.0",
    "@progress/kendo-react-excel-export": "2.5.0",
    "@progress/kendo-react-gauges": "2.5.0",
    "@progress/kendo-react-grid": "2.5.0",
    "@progress/kendo-react-inputs": "2.5.0",
    "@progress/kendo-react-intl": "2.5.0",
    "@progress/kendo-react-layout": "2.5.0",
    "@progress/kendo-react-pdf": "2.5.0",
    "@progress/kendo-react-tooltip": "2.5.0",
    "@progress/kendo-react-popup": "2.5.0",
    "@progress/kendo-react-ripple": "2.5.0",

Browser:
- Chrome (desktop) version 71

**Comment by nstoychev** [comment]
@k290 - Fixed in version 2.8.0-dev.201903111629. Here is an updated example: https://stackblitz.com/edit/react-4kknwi-axsvsg?file=app/main.js

**Comment by k290** [comment]
Thank you @nstoychev

**Comment by Xizario** [comment]
Shipped in `2.8.0`
