### ISSUE TITLE
ExternalDropZone events do not fire

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1522]
None of the ExternalDropZone events fire when a file is dragged over the zone or dropped:

- https://stackblitz.com/edit/react-sm7t7h?file=app%2Fmain.jsx

https://www.telerik.com/kendo-react-ui/components/upload/api/ExternalDropZoneProps/#toc-methods

Expected behavior:
 - onDrop should fire when a file is dropped in the drop zone
 - onElementDragEnter should fire when a dragged file enters the zone
 - onElementDragOver should fire when a dragged file leaves the zone

**Comment by WissamProgress** [comment]
Reported in Ticket ID: 1607858
