### ISSUE TITLE
KendoReact GridColumn resize defect with two adjacent locked columns 

### ISSUE THREAD

**Issue by veej** [telerik/kendo-react#1532]
## I'm submitting a...
* Bug report

## Current behavior
Rendering a grid with two adjacent locked columns, the first one with a fixed width, when we try to resize the first column, decreasing its width, the second column doesn't move to follow the first one, being stuck in its place.
Other non-locked columns next to the locked ones will instead follow the resizing, and they will be visible under the second locked column. See the screen recording below:

https://user-images.githubusercontent.com/925635/229077140-b61fc505-d332-4c13-9a07-e75a0bea86c0.mov

## Expected behavior
The second locked columns should follow the first one while resizing.

## Minimal reproduction of the problem with instructions
https://codesandbox.io/s/happy-gauss-pbt3wl?file=/src/App.js

Try to resize the first column decreasing its width, as in the screen recording above.

## Environment

Package versions:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/925635/229078057-6e82f8e8-d246-4816-8dd2-af880aad8441.png">
<img width="395" alt="image" src="https://user-images.githubusercontent.com/925635/229078099-70df39d6-917a-4adb-bc36-81a232b330ef.png">

Browser:
- Chrome (desktop) version 111.0.5563.110 

System:
- Platform:  Mac

**Comment by bptodorova** [comment]
Fixed in v5.17.0.

**Comment by veej** [comment]
Hello. I'd like to reopen the issue as it seems the fix doesn't work well with controlled widths for columns.
See the updated codesandbox [here](https://codesandbox.io/p/sandbox/relaxed-heyrovsky-59l7f8?file=%2Fsrc%2FApp.js%3A26%2C34)

https://github.com/telerik/kendo-react/assets/925635/440cc95d-c41d-49e7-bffc-9e690aa7be81

**Comment by iadnonov** [comment]
Hi @veej ,

After further investigation, it seems that the value of the `width` prop is in the wrong format. In the example below, I first retrieve the data for the desired column and assign it to a constant:

```javascript
const idColumnWidth = columnWidths.find((c) => c.field === 'ProductID');
```

Next, I retrieve the `width` value and pass it in GridColumn:

```javascript
width={idColumnWidth && idColumnWidth.width || 200}
```

This can be seen in action in the following example:
https://stackblitz.com/edit/react-sicvhu-hx4mj1?file=app%2Fapp.jsx
