### ISSUE TITLE
Grid with infinite scrolling and scrollable='virtual' prevents further page loads in Firefox

### ISSUE THREAD

**Issue by plevamatus** [telerik/kendo-react#1541]
## I'm submitting a...
* Bug report

## Current behavior
I'm trying to implement kendo react grid with infinite scrolling and scrollable="virtual". It seems that 2nd page is loaded correctly, but when I'm trying to scroll down again, grid suddenly scrolls to the top by itself and I'm not able to load more pages. It seems that the problem only occurs in Firefox.

Could be related to this issue #1375

![Recording 2023-04-14 143831](https://user-images.githubusercontent.com/11454499/232046587-183a9cee-fd6a-469f-a5ea-57f2e0599d49.gif)

## Expected behavior
It should be possible to load more pages.

## Minimal reproduction of the problem with instructions
Open this demo in Firefox https://codesandbox.io/s/infallible-tereshkova-804nik

Demo based on Infinite scrolling implementation from documentation (https://www.telerik.com/kendo-react-ui/components/grid/scroll-modes/#toc-infinite-scrolling)

## Environment

Package versions:
<img width="203" alt="image" src="https://user-images.githubusercontent.com/11454499/232049217-fb0458e7-49e6-4a54-bce1-cc7fc0e47b2d.png">

Browser:
- Firefox version 112.0

System:
- Platform:  Windows

**Comment by WissamProgress** [comment]
Reported in Ticket ID: 1618713

It appears that setting scrollable="virtual" is enough to reproduce this issue

**Comment by nandor-netfira** [comment]
We have the same issue and only in Firefox. It is also demonstratable on the Kendo React Grid demo page as of today:
https://www.telerik.com/kendo-react-ui/components/grid/scroll-modes/virtual/#toc-getting-started 

I just wonder if there is any update on this ticket since it has been open since April and it is a blocker for our users with Firefox. Thanks in advance.

**Comment by nstoychev** [comment]
@nandor-netfira - I am working on the issue and it is in testing stage. If everything is fine, we will include it in the next official release.

**Comment by nandor-netfira** [comment]
@nstoychev , awesome, thanks for the quick reply

**Comment by nstoychev** [comment]
We published the fix in 5.20.0-dev.202309291254. 

Here is an example: https://stackblitz.com/edit/react-twsmpz?file=app%2Fmain.jsx

**Comment by nandor-netfira** [comment]
Awesome, thanks Nikolay, the example works fine. We'll test it in our production code on Monday (2 Oct). Thanks
