### ISSUE TITLE
The className of a button that is inside a buttonGroup is not set.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#155]
The className of a button that is inside a buttonGroup is not set.

The className of a single button can be set, but once the button is inside a ButtonGroup the class is not set.

An example can be observed here:

https://stackblitz.com/edit/react-wsdxcv-3lyc83?file=app/main.js

**Comment by nstoychev** [comment]
Same thing to button's style.

**Comment by nstoychev** [comment]
Fixed in version 2.8.0-dev.201903111629.
Here is an updated example: https://stackblitz.com/edit/react-wsdxcv-8fnts1?file=app/main.js

**Comment by Xizario** [comment]
Fixed in `2.8.0`
