### ISSUE TITLE
Rating does not set state zero correctly

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1550]
FP item: https://feedback.telerik.com/kendo-react-ui/1606872

The Rating component. It doesn't work properly when the value is set to `0` programatically (behaves like `null` is passed).

**Steps to reproduce:**
1. Open https://codesandbox.io/s/inspiring-nobel-gy20m4?file=/app/main.jsx
2. Click 5 via mouse
3. Set value to 1 via button
4. Set value to 0 via button

Result: the value is se to 5.
Expected: The value is set to 0.

Possible workaround: Set the value to `'0'` as a string - `setState('0')}`

Ticket ID: 1606215

**Comment by vveesseelliinnaa** [comment]
Reported again in Ticket ID: 1606872

**Comment by aarlight** [comment]
Do you know when this bug will be assigned? Do we have a ballpark for a completion date?

**Comment by nstoychev** [comment]
Fixed in [5.14.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#v5.14.0).
