### ISSUE TITLE
Missing styles of the responsive select element of the Pager

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1552]
The Pager select element has different styles in responsive mode.

The problem can be observed here:
https://stackblitz.com/edit/react-7wymyy?file=app%2Fmain.jsx 

The proper styling can be observed here: https://www.telerik.com/kendo-angular-ui/components/pager/responsive/

**Comment by silviyaboteva** [comment]
The `<select>` element is missing `k-picker-solid` class.

**Comment by silviyaboteva** [comment]
Fixed in `v8.0.0`. Updated demo: https://stackblitz.com/edit/react-7wymyy-hy31f1?file=app%2Fmain.jsx
