### ISSUE TITLE
Scheduler performs slow when certain props are added to the WorkWeekView

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1565]
If the slotDuration is set to 60 and slotDivisions, startTime, endTime, workDayStart, and workDayEnd props are set, the Scheduler becomes slow. This can be seen in the following when clicking on the Show Full Day button:

https://stackblitz.com/edit/react-uz43ti-p3tjfe?file=app/main.jsx

Ticket ID: 1607646

**Comment by chadizta** [comment]
hi @filipKovachev  any update on this issue?

**Comment by filipKovachev** [comment]
After further investigation, we found that this is a performance issue that occurs because too many slots are being rendered at once and the browser cannot handle them. We will need virtualization in order to handle this scenario, which is currently not supported, however, we have a logged feature request that can be voted for here:

https://feedback.telerik.com/kendo-react-ui/1514241-requesting-virtualization-support-in-react-scheduler
