### ISSUE TITLE
defaultValue prop of ChipList does not select a default value

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1567]
The defaultValue of the ChipList does not select a default value. This can be seen in our documentation as well:

https://www.telerik.com/kendo-react-ui/components/buttons/chiplist/selection-mode/#toc-default-selection

**Comment by iordanGrancharov** [comment]
Fixed in dev version [v7.1.1-develop.5](https://github.com/telerik/kendo-react-private/releases/tag/v7.1.1-develop.5). Fix will be released with the official version soon.
