### ISSUE TITLE
Grid grouping and row re-ordering throws error

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1571]
Ticket ID: 1609151

When combing grouping and row reordering for the Grid, and dragging a header to group it, an `element.getBoundingClientRect is not a function` error is thrown. This bug is present in version 5.13.0.

An example where this is reproduced: [https://stackblitz.com/edit/react-8eancg?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-8eancg?file=app%2Fmain.jsx)

As a workaround, downgrade to the `5.12.0` version of the Grid of a previous one.

**Comment by alexvb** [comment]
This bug is still present when using @progress/kendo-react-grid in version 5.14.1:
https://stackblitz.com/edit/react-8eancg-fzmerd

**Comment by WissamProgress** [comment]
Also reported in Ticket ID: 1651834

**Comment by silviyaboteva** [comment]
This fix is included in version 8.1.0-develop.26. It will be available in the next official version of Kendo React packages.
