### ISSUE TITLE
Tooltip position is wrong for long titles and `position="auto"`

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1581]
Ticket ID: 1609401

The tooltip position is not calculated properly for long tooltips, when the component's `anchorElement="pointer"` and `position="auto"`.

video: http://somup.com/c0hTXRa30B

Steps to reproduce:
1. Open this demo - https://stackblitz.com/edit/react-4mpy7z?file=app%2Fmain.jsx
2. Hover over the first button

Result - the tooltip is shown shift right from the pointer even if there is enough space to show the whole tooltip.

**Comment by vveesseelliinnaa** [comment]
Reported again in Ticket ID: 1611894

**Comment by WissamProgress** [comment]
Can be resolved by setting the `setCalloutOnPositionAuto` property to `auto`. This property sets the start point of the Tooltip callout (in pixels) when the [position](https://www.telerik.com/kendo-react-ui/components/tooltip/api/TooltipProps/#toc-position) property is set to auto:

- https://stackblitz.com/edit/react-4mpy7z-qcjsy4?file=app%2Fmain.jsx
