### ISSUE TITLE
Add example with drag and drop and detail template.

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-react#1587]
Add example with drag and drop and detail template.

**Comment by zdravkov** [comment]
Here is an example of how row drag and drop with detail template can look - https://stackblitz.com/edit/react-jr94as-ctntzh?file=app%2Fmain.jsx.

**Comment by filipKovachev** [comment]
It seems that we have already added this example: https://www.telerik.com/kendo-react-ui/components/grid/rows/row-reordering/#toc-detail-row-reordering
