### ISSUE TITLE
Multiselect with filtering incorrectly calculating focusedIndex.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#159]
Step to reproduce:

Case 1:
1. Go to documentation page: https://www.telerik.com/kendo-react-ui/components/dropdowns/multiselect/filtering/
2. Type “ar” symbols

Actual result: Focused element is Bulgaria instead Armenia

Expected result: The first element in a list focused - Armenia

Case 2:

1. Go to documentation page: https://www.telerik.com/kendo-react-ui/components/dropdowns/multiselect/filtering/
2. Type “ary” - Hungary is suggested

3. Remove "y" to search "ar"

Actual result: There is no selected element
Expected result: The first element in a list focused - Armenia

**Comment by nstoychev** [comment]
Fixed in 2.8.0-dev.201903081502 version. Please refer to the following article about obtaining the development builds - https://www.telerik.com/kendo-react-ui/components/installation/development-builds/.

**Comment by Xizario** [comment]
Fixed in `2.8.0`
