### ISSUE TITLE
MultiColumnComboBox setting columns field property to an object 

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1592]
When setting the `field` property of the `columns` prop to an object, the MultiColumnComboBox fires a `Objects are not valid as a React child` error when opening it.
Example where the field is set to `hireDate` which refers to Date objects - [https://stackblitz.com/edit/react-biiakp-rkokfq?file=app%2Fmain.tsx](https://stackblitz.com/edit/react-biiakp-rkokfq?file=app%2Fmain.tsx)

As a workaround, stringify the object using `.toString` or `.toDateString` for dates - [https://stackblitz.com/edit/react-biiakp-fkjtxq?file=app%2Fmain.tsx](https://stackblitz.com/edit/react-biiakp-fkjtxq?file=app%2Fmain.tsx)

Related to Ticket ID: 1610939

**Comment by elena-gancheva** [comment]
The fix is available in the latest `dev` version https://github.com/telerik/kendo-react-private/releases/tag/v5.19.0-dev.202309181533
