### ISSUE TITLE
[Bug][TabStrip] Screen readers not reading the content properly

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1602]
When using JAWS screen reader and you press the right arrow key, each letter in the tab is read instead of the whole word or words. When using NVDA, nothing is read at all. This can be reproduced here:

https://stackblitz.com/edit/react-hlaan6?file=app%2Fmain.jsx

Ticket ID: 1612325

**Comment by iadnonov** [comment]
When Tabstrip is `scrollable` axe DevTools generate an `buttons have discernible text` for the previous and next buttons.
Can be tested in the following demo page: https://www.telerik.com/kendo-react-ui/components/layout/tabstrip/scrollable/

Ticket ID: 1640852

**Comment by iadnonov** [comment]
Tabstrip `scollable` generate axe errors `buttons have discernible text` for left ang right navigation arrows. 
Can be tested in the following demo page: https://www.telerik.com/kendo-react-ui/components/layout/tabstrip/scrollable/ 

Ticket ID: 1640852
