### ISSUE TITLE
Flickering in Dropdownlist during scroll of items in React 18

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1605]
Ticket ID: 1609252

There is a flickering when you scroll the DropDownList popup items very slowly. The issue seems to be specific to the `createRoot` method and cannot be reproduced with `ReactDOM.render`.

Video: https://screenpal.com/v/c012XxVBz5V

Steps to reproduce: 

1. Open https://stackblitz.com/edit/react-ijlzpc-w7kmmn?file=index.js in Edge
2. Open the DropDownlist popup and start scrolling the items very slowly

Live URL: https://react-ijlzpc-qzsmpf.stackblitz.io/

**Comment by codal-ashahu** [comment]
Hi , do we have any updates on this bug?

**Comment by jdodiya-codal** [comment]
@vveesseelliinnaa @kdikov82 Can I have rough estimates, when can we expect this to be resolved?

**Comment by WissamProgress** [comment]
Hi @codal-ashahu @jdodiya-codal 

I am really sorry that you did not receive a reply earlier. I triaged this bug and updated its priority based on its severity and how many times it was reported. If you have any concerns or questions on this matter, please let me know.

**Comment by jdodiya-codal** [comment]
**@WissamProgress** 

We've been facing this issue for a very long time almost a year, and we need to have it fixed soon, due to this dropdowns have become unresponsive when we perform a scroll through infinite items.

**Comment by WissamProgress** [comment]
Hi @jdodiya-codal 

I am really sorry for the inconvenience this bug has caused you. We fixed it and the fix is available in the latest dev version:

- https://stackblitz.com/edit/react-ijlzpc-8fvwep?file=package.json

It will also be available in the upcoming official release in May. I will therefore close this issue, but if you have any questions, please let me know.

**Comment by jdodiya-codal** [comment]
Thanks for the fix @WissamProgress
