### ISSUE TITLE
Adding different instances of a keyed plugin (plugin$) RangeError: Adding different instances of a keyed plugin (plugin$)

### ISSUE THREAD

**Issue by nitin-sahu-01** [telerik/kendo-react#1608]
I am submitting a bug in kendo react text editor .
Even in kendo sandbox it shows same issue. 
 providing the link of that sandbox:-
[https://codesandbox.io/s/d57v8y](https://codesandbox.io/s/d57v8y)
versions I am using :

- kendo editor - 5.5.0
- react - 18.2.0
- react-dom -18.2.0

I have tested this in Chrome Browser

**Comment by nstoychev** [comment]
Hello @nitin-sahu-01 

As I see, this is an old problem and has a solution - https://github.com/ueberdosis/tiptap/issues/305#issuecomment-601249611.

Please, see this article describing the same problem - https://www.telerik.com/kendo-react-ui/components/knowledge-base/editor-error-on-enter-press/.
