### ISSUE TITLE
Tooltip: Elements affected by title tag of parent do not get Kendo tooltip styling

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#161]
* Bug report 

## Current behavior
A span with  a `title` attribute, sometimes has subelements (e.g`. <i>, <strong> `etc. Browsers give several subelements a tooltip with the same `title` as the parent. But these do not get the Kendo tooltip styling
## Expected behavior

Display the Kendo tooltip styling on all elements that are affected by the `title`

**or**

Do not display a tooltip on any subelements (in which case the developer must put a `title` on each subelement).  **However this breaks away from current web standards**: http://jsfiddle.net/syxm4j51/

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-mghojh?file=app/main.js
## What is the motivation or use case for changing the behavior?
Consistent styling of elements affected by `title` tag

## Environment

kendo-react: 2.5.0
react: 16.7.0

Browser:

- Chrome (desktop) version 71

**Comment by simonssspirit** [comment]
Thank you for sharing this.

We will make this as an option as there are scenarios in React where the component structure may defer from the real DOM due to elements being rendered with a portal. This may result in incorrect text from the Tooltip this is why we will make it as an option and not default behavior.

**Comment by k290** [comment]
Ok thanks

**Comment by ZiedHf** [comment]
Hi guys,
@simonssspirit could you please tell me when this enhancement will be released ?
Thank you for this topic @k290.

**Comment by simonssspirit** [comment]
@ZiedHf It will strongly depend on the current priority tasks. When I start working on it, I make an update here. It should be in the next couple of weeks. Setting a specific ETA now could be misleading.

Thank you for understanding.

**Comment by KanzariAmine** [comment]
Is this still in progress ?

**Comment by simonssspirit** [comment]
@KanzariAmine  yes, the progress got delayed as there is some higher priority task currently in motion. This is already started, but more tests are needed to ensure it will not affect the current state of the Tooltip.

**Comment by ZiedHf** [comment]
@simonssspirit Sorry for bothering you about this. Is there another estimation date for the release of this enhancement ?

**Comment by simonssspirit** [comment]
@ZiedHf The task is delayed due to some species in the mouseover and mouse leave event which the browser fires and the connection to this case. I`m currently testing different cases to find a better approach to handle them. I will notify you as soon as it is in the dev channel.

**Comment by simonssspirit** [comment]
@ZiedHf @KanzariAmine @k290 This is already in the [dev](https://www.telerik.com/kendo-react-ui/components/installation/development-builds/) version. Here is an example:
https://stackblitz.com/edit/react-eggnqx?file=app/main.js

The functionality is enabled by using the parentTitle property.

Please give it a try and share if this is what was needed.

**Comment by k290** [comment]
Yes it is perfect.

I have updated my original example from the start of this thread for everyone else to look at:
https://stackblitz.com/edit/react-mghojh-aj6qys?file=app%2Fmain.js

**Comment by simonssspirit** [comment]
Officially available in 2.7.1 https://stackblitz.com/edit/react-mghojh-3tgp1c?file=app/main.js
