### ISSUE TITLE
[RadioGroup] is not read properly by screen readers

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1614]
When using the JAWS screenreader and navigating through the RadioGroup with the arrow keys, the items are read letter by letter. This can be reproduced here: 

https://stackblitz.com/edit/react-l1kkru?file=app%2Fmain.jsx

Ticket ID: 1613407

**Comment by iadnonov** [comment]
Can not be reproducible on build in Mac VoiceOver.

**Comment by iadnonov** [comment]
This behavior is not reproducible with NVDA and Mac VoiceOver, which indicates an internal problem with JAWS.
