### ISSUE TITLE
Grouping items and removing them throws error

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1616]
When using the latest version of the components, if you drag a column to be grouped multiple times and then you remove it the following error is thrown:

target.className.indexOf is not a function

This can be reproduced here:

https://stackblitz.com/edit/react-reprz8?file=app%2Fmain.jsx

Ticket ID: 1613749

**Comment by zdravkov** [comment]
fixed with the version 5.16.1 of KendoReact - https://stackblitz.com/edit/react-reprz8-xkxcjn?file=package.json
