### ISSUE TITLE
Grid reorderable prop set to true throws error

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1619]
When reordering columns in the Grid with the reorderable prop set to true, the following error is triggered:

target.className.indexOf is not a function:

https://codesandbox.io/s/nice-pond-k4pgr5

This is reproduced only in the latest version, in version 5.13.0, and below this works as expected.

Ticket ID: 1614151

**Comment by zdravkov** [comment]
Fixed in the latest version of KendoReact - https://codesandbox.io/p/sandbox/happy-liskov-k27xsh
