### ISSUE TITLE
[Chip] elements must only use allowed for an element role error

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1621]
When testing the Chip component using AXE the following error is reproduced:

elements must only use allowed for an element role error:

![image](https://github.com/telerik/kendo-react/assets/92358162/595b4516-b026-4eab-b457-2e0fb869b345)

This can be reproduced in the following example:

https://stackblitz.com/edit/react-ytyhnd-f3dzp4?file=app%2Fmain.jsx

Ticket ID: 1614359

**Comment by iadnonov** [comment]
Fixed in dev version v7.0.0-develop.7
