### ISSUE TITLE
Window with enabled draggable returns wrong left and top coordinates within scrollable container

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1623]
Dragging a Window component displayed in a scrollable container returns wrong coordinates after the first few onMove events and the Window forces the scrollbar to reset. 

In the following example, scroll to the bottom and click the button to open the Window. Start dragging the Window and you will notice the Window moves to the top of the container: 
https://codesandbox.io/s/kendo-react-dialogs-bug-dncgm7?file=/src/App.js

Note that the issue is not replicated in the following example, where the "body" and "my-app" elements have "height: 100%" and relative position:

- https://stackblitz.com/edit/react-u8cjrd?file=app%2Fmain.jsx,index.html

**Comment by iadnonov** [comment]
The issue is fixed in our v8.2.0-develop.24 and will be available in the next official version of Kendo React.
