### ISSUE TITLE
TreeList fires error when pressing its header cell

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1626]
When pressing on the Treelist header cell, an `unable to prevent default inside event handler` error appears in the console:
[https://www.telerik.com/kendo-react-ui/components/treelist/](https://www.telerik.com/kendo-react-ui/components/treelist/)

Ticket ID: 1614640

**Comment by WissamProgress** [comment]
duplicate #1372

**Comment by jusherwood** [comment]
We are experiencing this issue, any update of when a fix will be available, or a suitable workaround to prevent the error in the console?

**Comment by zdravkov** [comment]
fixed in the latest KendoReact version.
