### ISSUE TITLE
Dragging the column menu fires a TypeError

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1629]
This issue can be reproduced when having reorderable columns and rendering a column menu. When dragging the column menu, a `target.className.indexOf is not a function` TypeError appears:
[https://codesandbox.io/s/ecstatic-cohen-k5r68z?file=/app/main.jsx](https://codesandbox.io/s/ecstatic-cohen-k5r68z?file=/app/main.jsx)

Ticket ID: 1614762

**Comment by WissamProgress** [comment]
This error also appears when dragging the group:
[https://somup.com/c0i219zUE2](https://somup.com/c0i219zUE2)

Reported in Ticket ID: 1615527

**Comment by bptodorova** [comment]
Fixed in v5.15.0
