### ISSUE TITLE
JavaScript error is thrown when a column with enabled context menu is dragged

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1631]
Ticket ID: 1614695

JavaScript error is thrown when a column with enabled context menu is dragged in the Grid:
![image](https://github.com/telerik/kendo-react/assets/6196386/9607efff-0ef5-44fa-bc99-08389fa4d7de)
Steps to reproduce:
1. Open the Column menu demo with enabled `reordarable`: https://codesandbox.io/s/trusting-brook-hts3gm
2. Attempt to drag a column

**Actual behavior**: 
A Javascript `CommonDragLogic.js:149 Uncaught TypeError: target.className.indexOf is not a function` error is thrown. Line 142 of CommonDragLogic.js within the Grid project attempts to call target.className.indexOf; however, the svg that is used for the filter icon lacks a class name, so attempting to call indexOf of undefined causes the displayed error in the screenshot.

**Expected behvaior:** 
The check in line 142 of CommonDragLogic should be updated to target.className?.indexOf to guard against the possibility of targets that lack of class name such as the svg element used as the filter button icon.

<hr/>
A possible workaround is to use the Grid with font icons via `IconsContext`:

- https://www.telerik.com/kendo-react-ui/components/styling/migrating-font-svg/#toc-continue-using-font-icons

Working sample: https://codesandbox.io/s/zen-engelbart-ttzfyl

**Comment by zdravkov** [comment]
duplicate  https://github.com/telerik/kendo-react/issues/1629
