### ISSUE TITLE
[BUG] [TreeList] Columns resizing triggers reordering

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1632]
Ticket ID: 1614808

Dragging the resizing border of the column header does not trigger resizing in some scenarios, but drags the whole column and reorders it.

Video - http://somup.com/c0ifjczohw

Steps to reproduce:
1. Open https://codesandbox.io/s/hidden-butterfly-j9ky7h?file=/app/main.jsx:1998-2079
2. Try to resize the first column to the right several times

Result: Sometimes dragging the resize handler triggers resizing, sometimes the column is moved instead.

**Comment by bptodorova** [comment]
Fixed in v.5.18.0
