### ISSUE TITLE
SpreadSheet throws Cannot read properties of null (reading 'render') in StrictMode

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1636]
When using the SpreadSheet in StrictMode, the following error is thrown: 

Cannot read properties of null (reading 'render') in StrictMode

This can be reproduced in the following example once you scroll:

https://stackblitz.com/edit/react-veq2p9-etwj4a?file=app%2Fmain.tsx

Ticket ID: 1614454

**Comment by filipKovachev** [comment]
Also reported in Ticket 1633700

**Comment by bptodorova** [comment]
Fixed in v7.0.0-develop.12.
