### ISSUE TITLE
[BUG] [MultiSelect] Selected items not read properly with NVDA

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1637]
When navigating via tabbing on an already selected item, the screen reader reads {name} not selected not checked even if it is selected.

This can be reproduced here:

https://stackblitz.com/edit/react-bhotxs?file=app%2Fmain.jsx

Ticket ID: 1615277

**Comment by PekoPPT** [comment]
The issue is triggered by the "k-virtual-table" class added in this commit - https://github.com/telerik/kendo-react-private/commit/a8ccec67305f7655e82643bbedfb1e472c7d2410
