### ISSUE TITLE
NumericTextBox doesn't truncate trailing zeros

### ISSUE THREAD

**Issue by jbrianskog** [telerik/kendo-react#165]
## I'm submitting a...

Bug report
## Current behavior

In a NumericTextBox with format 'c', when entering values after the decimal, trailing zeros in the displayed value are not truncated until you enter one more decimal than your maximumFractionDigits.
## Expected behavior

Because the control automatically inserts zeros when entering values before the decimal, I would expect those zeros to be overwritten -- not offset -- when entering the decimal portion. I.e. If i focused the box, typed '5', '.', '2', and '3', I should see '$5.23' in the box, not '$5.2300'
## Minimal reproduction of the problem with instructions

https://react-6tetzy-sc4gxs.stackblitz.io
Click on the box, and type '5', '.', '2', and '3'.
## What is the motivation or use case for changing the behavior?

The displayed value should respect the culture formatting options (i.e. maximumFractionDigits)

**Comment by PaitoAnderson** [comment]
I have noticed this too, and would like it fixed 👍

Another example of this, click on the 70%, press tab, type "5.99" it will be "$5.9900".

https://www.telerik.com/kendo-react-ui/components/inputs/numerictextbox/formats/

**Comment by vladimirivanoviliev** [comment]
Fixed in latest dev version `3.10.0-dev.202001150733`.
