### ISSUE TITLE
[Editor] The styles of content pasted from Excel are stripped

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1650]
Ticket ID: 1617398

While copying the table from Excel, and pasting in Editor and converting to html using 
`EditorUtils.getHtml(editor.current.view.state);`
is removing the styles from the inserted html.

Steps to reproduce:
1. Create a styled table in excel (e.g. with borders, background and bold content)
2. Copy and paste it in the following demo: https://www.telerik.com/kendo-react-ui/components/editor/content/
3. Click the **Get HTML** button

Result: The styles are removed from the pasted table

Additional: Copying the same content in the following demo will strip the whole table: https://www.telerik.com/kendo-react-ui/components/editor/paste/

**Comment by nstoychev** [comment]
The cells styles are placed in a style tag with commented content.

I've come up with this solution - https://stackblitz.com/edit/react-jz2a3h?file=app%2Fmain.jsx and cannot guarantee that it will work on every cases.

The pasted content depends on the operation system, excel version and the browser. So far, I tested it only on my PC.
