### ISSUE TITLE
[SplitButton] SplitButtonProps export from @progress/kendo-react-buttons

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1653]
SplitButtonProps is currently exported from `@progress/kendo-react-buttons/dist/npm/ListButton/models/ListButtonProps`.
However, it should be exported from `@progress/kendo-react-buttons` directly.

Ticket ID: 1617910

**Comment by zdravkov** [comment]
The issue is fixed in the dev channel on KendoReact @progress/kendo-react-buttons package.
