### ISSUE TITLE
[Editor] BackColor and ForeColor are not applied on table cells content if multiple cells are selected

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1656]
If multiple cells/rows are selected in a table, applying changes to the BackColor and ForeColor fails in some scenarios.

To observe the issue, open the following example:

- https://stackblitz.com/edit/react-icvjor?file=app%2Fmain.jsx

Cases that fail:
- select with the mouse from row1cell1 to row2cell2 and changing the ForeColor or the BackColor
- select with the mouse from row1cell2 to row3cell3 and changing the ForeColor or the BackColor
- selecting all cells and changing the ForeColor or the BackColor

**Comment by nstoychev** [comment]
Fixed in v5.17.0.
