### ISSUE TITLE
[QRCode] Swiss Payment Standard String causes unnecessary padding

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1659]
## I'm submitting a...
* Bug report

## Current behavior
Setting the [value](https://www.telerik.com/kendo-react-ui/components/barcodes/api/QRCodeProps/#toc-value) property of the QRCode component to a swiss QR adds unncecessary padding to the QR code.
<img width="206" alt="Screenshot 2023-11-20 at 16 18 56" src="https://github.com/telerik/kendo-react/assets/108671796/3e095908-7a27-46e2-a0e7-6b895eea3273">

## Expected behavior
It is expected that there is no added padding to the QR code, which is the case when setting the `value` to a non swiss QR code.
<img width="209" alt="Screenshot 2023-11-20 at 16 21 35" src="https://github.com/telerik/kendo-react/assets/108671796/3a0d85e0-1bf6-4dd3-bace-2eddef37214b">

## Minimal reproduction of the problem with instructions

Set the value property of the QRCode component to a swiss QR code

This is demonstrated in the following demo - https://stackblitz.com/edit/react-bzfwub-dgmuel?file=app%2Fmain.jsx
Clicking on the button switches the value between a basic QR and a swiss QR.

Reported in Ticket ID: 1618743

**Comment by wuibb** [comment]
Hi Kendo-React Team, is there any update on this issue? Thank you!

**Comment by WissamProgress** [comment]
Hi @wuibb

After some research on this issue, we found out that this is related to the error correction value which generates the QR with a different size. For example, if you set the [errorCorrection](https://www.telerik.com/kendo-react-ui/components/barcodes/api/QRCodeProps/#toc-errorcorrection) property to `L`, there will be no space around the QRCode:

- https://stackblitz.com/edit/react-bzfwub-1zz712?file=app%2Fmain.jsx

Another workaround I can provide would be set the width of the div wrapper to the smallest possible value. For example, in the below demo the errorCorrection is set to `H` but the width is set to `106px`:

- https://stackblitz.com/edit/react-bzfwub-s5unwb?file=app%2Fmain.jsx

Please check the above solutions and let me know if they match what you need.
