### ISSUE TITLE
Pass the information if the button the toggable button is active or not in the click event

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#166]
Pass the information if the button the toggable button is active or not in the click event.
Currently, there is no official way to obtain this information.

**Comment by simonssspirit** [comment]
Also, the button is losing its active state if the state is updated. For example, we click the button to filter data collection. The state is updated after the filter and the button does not appears as active, it resets its toggle state.

**Comment by vladimirivanoviliev** [comment]
This feature is ready on our side but as it require breaking change in `onChange` event handler of the Buttons package it would be released with next major version.
