### ISSUE TITLE
[Grid] Resizing while having custom header cells does not allow resizing

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1660]
When setting `resizable` to true and rendering custom header cells using the `cells.headerCell` prop, the resizing does not work:
[https://stackblitz.com/edit/react-gjyz3m?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-gjyz3m?file=app%2Fmain.jsx)

Reported in Ticket ID: 1613932

**Comment by bptodorova** [comment]
Fixed in v5.17.0.
