### ISSUE TITLE
[Spreadsheet] Custom Functions Feature

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1661]
Custom functions feature which allows defining custom functions for the cells. Example from jQuery:

[https://docs.telerik.com/kendo-ui/controls/spreadsheet/custom-functions](https://docs.telerik.com/kendo-ui/controls/spreadsheet/custom-functions)

Ticket ID: 1618646

**Comment by nstoychev** [comment]
Implemented in our development channel: https://www.telerik.com/kendo-react-ui-develop/components/spreadsheet/custom-functions/
