### ISSUE TITLE
Column Grid DateTime Editor

### ISSUE THREAD

**Issue by gabrielcerutti** [telerik/kendo-react#1662]
I tried to implement a DateTime editor following the DateCell editor sample found [here ](https://www.telerik.com/kendo-react-ui/components/grid/editing/editing-custom/) but for some reason the onChange event is not triggered, so changes are not detected for that column in the grid.

This is the component:

```javascript
export const DateTimeCell = props => {
  const {
    dataItem,
    field,
    render
  } = props;
  const isInEdit = field === dataItem.inEdit;
  const value = field && dataItem[field] ? dataItem[field] : new Date();
  const handleChange = e => {
    if (props.onChange) {
      props.onChange({
        dataIndex: 0,
        dataItem: props.dataItem,
        field: props.field,
        syntheticEvent: e.syntheticEvent,
        value: e.target.value
      });
    }
  };
  const defaultRendering = <td>
      {isInEdit ? <div>
          <DateTimePicker value={value} format="yyyy-MM-dd hh:mm:ss a" onChange={handleChange} />
        </div> : value ? value.toISOString().substring(0, 19).replace('T', ' ') : ''}
    </td>;
  return render?.call(undefined, defaultRendering, props);
};
```
There is a sample here [https://react-5fltiw.stackblitz.io](https://react-5fltiw.stackblitz.io).

Any issue in this implementation?

Thanks in advance :)

**Comment by zdravkov** [comment]
It seems like the different UI of the DateTimePicker triggers the change a bit later and that is why the change is not executed. After I delayed a bit the exit of the edit mode the change started to trigger correctly:
```
const exitEdit = () => {
    const newData = data.map((item) => ({
      ...item,
      [EDIT_FIELD]: undefined,
    }));
    setTimeout(() => {
      setData(newData);
    }, 250);
  }; 
```
Here is an updated example - https://stackblitz.com/edit/react-5fltiw-jakgaj?file=app%2FcustomCells.jsx,package.json,app%2Fmain.jsx

Hope this will help you solve the issue. :)
As a side note - our main support channel is our ticketing system so if you have other questions please create a trail Telerik account and submit a ticket so we could be faster with our answer. https://www.telerik.com/kendo-react-ui

Greetings,
Plamen

**Comment by gabrielcerutti** [comment]
Hey Plamen, it's working fine. Thanks! 

Best regards,
Gabriel.-
