### ISSUE TITLE
Kendo scheduler events rounding to half hour 

### ISSUE THREAD

**Issue by relitodea** [telerik/kendo-react#1666]
## I'm submitting a...
The appointments are every 45 mins yet they are displayed as a half hour slots. I would expect regardless of the side guides that the events would be displayed correctly. thanks

* Bug report 

## Current behavior
Rounding events to the nearest half hour.

## Expected behavior
I would expect the events to be displayed in their correct size relative to the side measure.
Related to https://github.com/telerik/kendo-angular/issues/2025 

## Minimal reproduction of the problem with instructions
all examples

## What is the motivation or use case for changing the behavior?
it is related to clarity of displayed information. 

## Environment

Package versions:
[@progress/kendo-react-scheduler](https://www.npmjs.com/package/@progress/kendo-react-scheduler)
```

```

Browser:
- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:

**Comment by kdikov82** [comment]
By default, the SchedulerViewItem will fill the entire slot space and based on the slotDivisions and slotDuration values, the rounding will differ. If you want to display the exact position of the events you can take a look at the custom SchedulerProportionalViewItem:

- https://www.telerik.com/kendo-react-ui/components/scheduler/customization/items/view-item/#toc-extending-the-positioning
