### ISSUE TITLE
Kendo-editor

### ISSUE THREAD

**Issue by jadrehaoui** [telerik/kendo-react#167]
I was trying the free version of the kendo ui, and i was not able to find any text editor input.
I am searching for an input where i can change the style of the text like make it bold, italic and it's direction. 
i couldn't find anything similar, I am using the kendo react package. can you please help ?

**Comment by vladimirivanoviliev** [comment]
Currently the React Editor is in active development and should be ready for 2019 R2 release (expected for mid-May) or sooner.
Until the Editor is ready you can use the old Editor wrapper found here:
- [Editor wrapper](https://www.telerik.com/kendo-react-ui/wrappers/editor/)

**Comment by Xizario** [comment]
Closing this as the [Editor](https://www.telerik.com/kendo-react-ui/components/editor/) is live now
