### ISSUE TITLE
[Calendar] Calendar navigation is broken on zoomed browser

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1670]
Calendar layout is broken when navigating through the years on 80% zoom rate of the browser.

Video:  http://somup.com/c0jo2tAX1h

Steps to reproduce:
1. Open https://codesandbox.io/s/kendo-datepicker-bug-forked-6q8r4w
2. Resize this window to 80%
3. Click on August 2023 at top of calendar

Result: Empty calendar and unreliable controls

**Comment by WissamProgress** [comment]
Fixed in the [6.1.1-dev.202311061144](https://www.npmjs.com/package/@progress/kendo-react-dateinputs/v/6.1.1-dev.202311061144) dev version:

https://codesandbox.io/s/kendo-datepicker-bug-forked-sqn74z?file=/package.json
