### ISSUE TITLE
Upload component is using an old version of Axios

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1675]
The Upload component has the `0.22` version of Axios as a dependency while the latest version is `1.14.0`.

Related to Ticket ID: 1620424

**Comment by martinsvanstrom** [comment]
Axios v0.22.0 has a security problem https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459
And needs to be updated to at least v1.6.0

Related to Ticket ID 1629131

**Comment by nstoychev** [comment]
We updated it to v1.6.0 in our dev channel version 6.1.0-dev.202310310855.

Example: https://codesandbox.io/s/qxvgdq

The fix will be available in the next official release.

**Comment by nstoychev** [comment]
We published [6.1.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#v6.1.0).
