### ISSUE TITLE
AgendaView : Step Prop

### ISSUE THREAD

**Issue by nitin-sahu-01** [telerik/kendo-react#1677]
I am submitting a bug in kendo react scheduler AgendaView Date step .
Even in kendo sandbox it shows same issue.
if I I am setting step to 1 then it take 2 step just because in onofdays I have set 2.
Step prop does not work as it should work. 
providing the link of that sandbox:-
[AgendaView](https://stackblitz.com/run/?file=app%2Fmain.tsx)
versions I am using :

kendo editor - 5.5.0
react - 18.2.0
react-dom -18.2.0
I have tested this in Chrome Browser
```[tasklist]
### Tasks
```

**Comment by filipKovachev** [comment]
Hello, nitin-sahu-01,

I tried to open the provided example, however, I was not able to it seems that it wasn't saved properly. Can you please fork it again and send it so that I can inspect it?

Regards,
Filip

**Comment by kdikov82** [comment]
The issue is reproducible with TimelineView as well and the step property is not respected:
https://stackblitz.com/edit/react-hecxyx?file=app%2Fmain.jsx

The Prev/Next buttons in the navigation take the numberOfDays value and not the step value

**Comment by PekoPPT** [comment]
The **step** property is now added to all Scheduler views and the **numberOfDays** is available for the **Agenda**, **Timeline**, and **Day** views. 

The fix will be available with version 8.1.0 of the KendoReact suite. If a specific scenario is required, the onDateChange event can be used and through its handler, we can dynamically set the **day** we want to switch to or the **numberOfDays** we need to display.
