### ISSUE TITLE
[Menu] It is not possible to navigate with Tab through items

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1681]
It is not currently possible to navigate between several menu items using keyboard navigation with the tab key. 

This can be reproduced in the following example:

https://stackblitz.com/edit/react-dapymn-dhmcvu?file=app%2Fmain.jsx

Steps to reproduce:

1. Press the Tab key and try to reach Item2 or Item3 in the menu
2. Notice how you can access only Item1 and moving further is not possible.

When inspecting the elements it seems that this is a tabIndex issue.

Ticket ID: 1621698

**Comment by silviyaboteva** [comment]
For our Menu component, we implement [Roving tab index strategy](https://opensource.adobe.com/spectrum-web-components/tools/roving-tab-index/). This allows keyboard users to quickly tab through a page without having to stop on every element in a large collection.

So, this is a desired behavior. You can use the arrow keys to navigate through the menu items.
