### ISSUE TITLE
ConversationalUi - Custom Message box

### ISSUE THREAD

**Issue by abhinav-juneja** [telerik/kendo-react#169]
It would be helpful if user is able to pass custom message box in ConversationalUi component. 

* Suggestion for improvement

**Comment by asen-arizanov** [comment]
Thank you for sharing this.

What exactly do you want to customize? For example, the [`placeholder` can be easily changed](https://www.telerik.com/kendo-react-ui/components/conversationalui/api/ChatProps/#toc-placeholder).

**Comment by abhinav-juneja** [comment]
I want to pass an input box component with an upload attachment button.

**Comment by asen-arizanov** [comment]
Unfortunately, this cannot be achieved trivially now. We will consider adding a messageBoxTemplate similar to the [`messateTemplate` prop](https://www.telerik.com/kendo-react-ui/components/conversationalui/api/ChatProps/#toc-messagetemplate).

A workaround is to manipulate the DOM via adding the upload button next to `.k-button-send`.

**Comment by silviyaboteva** [comment]
Added in `3.5.0`. You might check a demo here: https://www.telerik.com/kendo-react-ui/components/conversationalui/custom-rendering/
