### ISSUE TITLE
[DropDownButton] OnClose event is not triggered properly in controlled mode 

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1690]
`OnClose` event is not triggered after `onClick` and `onBlur` in controlled mode as of version 5.14.0.

Video: http://somup.com/c0QflcABtz

Steps to reproduce:
1. Open https://stackblitz.com/edit/react-cvzgsc-zfsyjg?file=package.json,app%2Fmain.jsx
2. Click the `user settings` button
3. Click the button / its child items / some empty space around

Actual behavior: The onClose event is not triggered if you click over or outside the items, hence the dropdown is not closed.

Previous behavior up to version 5.13.1 (and [of the DropdownList as well](https://www.telerik.com/kendo-react-ui/components/dropdowns/dropdownlist/events/)) - https://stackblitz.com/edit/react-cvzgsc-zfsyjg?file=package.json,app%2Fmain.jsx

--

Possible workaround: Update the `open` state also in the `onItemClick` and `onBlur` events - https://stackblitz.com/edit/react-cvzgsc-zwdovt?file=app%2Fmain.jsx

**Comment by bptodorova** [comment]
Fixed in version 5.18.0.
