### ISSUE TITLE
[Grid] Virtual scroll does not work in Firefox

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1698]
Scrolling by clicking and dragging the scroll bar works as expected, but using the mouse wheel keeps pushing you back to where you were. This can be seen in the following example:

Steps to reproduce:
1. Open the example in Firefox
2. Scroll using the mouse wheel
3. Observe that you are being pushed to the same place you were before

https://stackblitz.com/edit/react-dacwap?file=app%2Fmain.jsx

Ticket ID: 1623377

**Comment by nstoychev** [comment]
We published the fix in 5.20.0-dev.202309291254.

Here is an example: https://stackblitz.com/edit/react-dacwap-rflds7?file=app%2Fmain.jsx
