### ISSUE TITLE
Grid - toggle resizeable not working 

### ISSUE THREAD

**Issue by jannhofman** [telerik/kendo-react#17]
## I'm submitting a...

* Bug report 

## Current behavior

Resizable toggle, after the table rendering doesnt work. 
Active -> Deactive works. 
Deactive -> Active doesnt work. The handle is shown, but not draggable.

## Expected behavior

After setting resizeable = true -> columns are resizeable

## Minimal reproduction of the problem with instructions

i attached a small sample Site

## What is the motivation or use case for changing the behavior?

we tried a workaround for another issue and found this by accident. :)

## Environment
0.5.0

Browser:
- Firefox 

Sample
[kendoReactTest.zip](https://github.com/telerik/kendo-react/files/1943389/kendoReactTest.zip)

open console and run
npm install
npm run dev

**Comment by simonssspirit** [comment]
This could be observed in the following isolated example as well: https://plnkr.co/edit/njAZEeJAhZaP5wkfESil?p=preview

**Comment by Xizario** [comment]
Fixed in version [0.6.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/)
