### ISSUE TITLE
Ripple effect stutters

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#170]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
When clicking a button with the Ripple effect, if the result of the button requires high CPU usage, it will freeze the animation of the Ripple and jump to when it is complete.

## Expected behavior
Ripple effect completes while the DOM is busy.

## Minimal reproduction of the problem with instructions
Editor:
https://stackblitz.com/edit/react-amde8z

Viewer:
https://react-amde8z.stackblitz.io

Click the change tab button. When loading the light tab, it displays the animation smoothly. When loading the resource-heavy tab, the animation will freeze. I've provided an example animation that doesn't use DOM-affecting CSS styles which continues to play during the transition.

## What is the motivation or use case for changing the behavior?
We have a tab based layout for our more complex forms that have too much content for a single page. When switching between tabs the ripple animation freezes with makes the page appear unresponsive.

## Environment
Browser:
- Chrome (desktop) Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by Xizario** [comment]
We can not fix this, the browser itself prioritizes the JS thread in favor of the layout update, effectively blocking the css animation.
