### ISSUE TITLE
[Spreadsheet] Fires a type error when adding data with Internationalization enabled

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1700]
This bug can be reproduced in the following example where the Spreadsheet is wrapped by the `IntlProvider` component:
https://codesandbox.io/s/heuristic-villani-xs3jmf?file=/app/main.tsx

Steps:
1. Add a value to one of the cells
2. Focus out of the cell
(The bug can also be reproduced when adding data by setting the [`defaultProps.sheets`](https://www.telerik.com/kendo-react-ui/components/spreadsheet/api/SpreadsheetOptions/#toc-sheets) property.

Result:
`Cannot read properties of undefined (reading 'symbol')` type error appears crashing the application

Ticket ID: 1623962
(See also: 1630548)

**Comment by kdikov82** [comment]
Other errors that might be related with the IntlProvider:
ticket: 1630548

**Comment by nstoychev** [comment]
The following code snippet can be used for a workaround: https://codesandbox.io/s/wild-currying-wfkgv8?file=/app/main.tsx

```tsx
  const intl = React.useRef<IntlProvider>(null);
  React.useEffect(() => {
    if (intl.current) {
      intl.current.getIntlService().parseNumber("5");
    }
  }, []);

  return (
    <IntlProvider ref={intl} locale={"en-GB"}>
```

Calling parseNumber function of intl service initializes the needed data.

**Comment by elena-gancheva** [comment]
Fixed with the latest official version of the package.
