### ISSUE TITLE
[PdfViewer] Wide Pdfs are not loaded on MAC

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1701]
PDFs with width larger than 3500px are not loaded in the PdfViewer on MAC. The problem is reproducible as of version 5.17.0. The problem is specific to KendoReact and cannot be reproduced neither in jQuery, nor in PdfJS.

![image](https://github.com/telerik/kendo-react/assets/6196386/4116b73a-5160-4f49-8156-5d6baf751410)

Steps to reproduce:
1. Open https://codesandbox.io/s/relaxed-cannon-w87g8x in Chrome on MAC
2. Load the attached PDF.

Result: The PDF is not loaded at all.
Expected: Repeat the same steps with `"@progress/kendo-react-pdf-viewer": "5.16.0",` - https://codesandbox.io/s/trusting-cohen-jwph2g?file=/package.json 

Ticket ID: 1623832
[testpdf.pdf](https://github.com/telerik/kendo-react/files/12664018/testpdf.pdf)

**Comment by nstoychev** [comment]
Fixed in version 6.1.0.
