### ISSUE TITLE
[Map] Mouse wheel scroll more than the +/- buttons

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1706]
This bug can only be reproduced locally where scrolling the mouse wheel zooms in much more than the +/- buttons:

https://somup.com/c0Q3ILBhwq

It is expected that both the +/- buttons and the mouse wheel scroll the same distance. This is not happening in the overview demo, or if you open the example in Stackblitz:

https://www.telerik.com/kendo-react-ui/components/map/

Reported in Ticket ID: 1624189

## Update with a solution: Control the zoom value using the [onZoomStart](https://www.telerik.com/kendo-react-ui/components/map/api/MapProps/#toc-onzoomstart) event:

- https://stackblitz.com/edit/react-5rgwqz-dkvvsb?file=app%2Fmain.jsx

```
const handleZoomStart = (e) => {
    const mapInstance = mapRef.current.mapInstance;
    const zoom = mapInstance.zoom();
    e.preventDefault();

    if (e.originalEvent.delta > 0) {
      console.log('+ button');
      mapInstance.zoom(zoom + 1);
    } else {
      if (e.originalEvent.wheelDelta && e.originalEvent.wheelDelta > 0) {
        mapInstance.zoom(zoom + 1);
        console.log('mouse zoomin');
      } else {
        console.log('mouse zoomout or - button');
        mapInstance.zoom(zoom - 1);
      }
    }
  };
```

**Comment by miazhu-ADS2** [comment]
Hi,

Are there any updates you can share regarding this bug? Thanks!

Mia

**Comment by WissamProgress** [comment]
Hi @miazhu-ADS2 
This bug is still in an unplanned phase, therefore, I will forward it to the team in order to increase its priority.

**Comment by WissamProgress** [comment]
@miazhu-ADS2 
Below is an example how we can prevent the default zoom and set a custom one. This is achieved in the `handleZoomStart` function. Can you please test if this solution matches what you need?

-  https://stackblitz.com/edit/react-5rgwqz-tiwcgw?file=app%2Fmain.jsx

**Comment by miazhu-ADS2** [comment]
> @miazhu-ADS2 Below is an example how we can prevent the default zoom and set a custom one. This is achieved in the `handleZoomStart` function. Can you please test if this solution matches what you need?
> 
> * https://stackblitz.com/edit/react-5rgwqz-tiwcgw?file=app%2Fmain.jsx

@WissamProgress Thanks for the demo. However, it appears that the map can only be zoomed out and cannot be zoomed in on mouse scroll.

**Comment by WissamProgress** [comment]
@miazhu-ADS2 It appears that `e.originalEvent.delta` is not working in some browsers (possibly deprecated), and therefore causing this behavior.
However, we updated and tested the example to use `e.originalEvent.wheelDelta` instead. Can you please test it to check it it's working on your side:

- https://stackblitz.com/edit/react-5rgwqz-grqrxp?file=app%2Fmain.jsx

**Comment by miazhu-ADS2** [comment]
@WissamProgress Thank you so much, the mouse scroll is working correctly now. But the +/- is not working correctly, both +/- can only zoom out. Is the fix only going to allow one of these zoom controls to work properly?

**Comment by WissamProgress** [comment]
You are welcome, @miazhu-ADS2,  I am glad that the mouse scroll is now working.

For the +/- buttons, you can add an additional condition that handles `e.originalEvent.delta`.
I updated the demo such that both the +/- buttons as well as the mouse zooming in and out are handled:

- https://stackblitz.com/edit/react-5rgwqz-dkvvsb?file=app%2Fmain.jsx

**Comment by miazhu-ADS2** [comment]
@WissamProgress Thanks again, so glad this is fixed.

**Comment by WissamProgress** [comment]
You are welcome @miazhu-ADS2. I am also glad that the provided solution fixed the faced issue.

I will close this GitHub issue and update its description with the solution. If you need further help with the Map component, you can submit a support ticket and we will be glad to assist you further.
