### ISSUE TITLE
[Bug][Grid] Grid's footerCell misaligns with the columns on horizontal scrolling and the footer row is not sticky at the bottom

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1708]
When horizontal scrollbar is introduced along with a footer, scrolling horizontally misaligns the footer cells (latest dev version 5.19.0-dev.202309211913):

- https://stackblitz.com/edit/react-xlg5xv-c3mjpe?file=package.json

Additionally, the footer row was previously rendered as a sticky row along with the pager, but it is now rendered as standard data row. Here the previous behavior:

- https://stackblitz.com/edit/react-ryqqbg-dzdpkf?file=app%2Fmain.jsx

**Comment by bptodorova** [comment]
Fixed in version `5.19.0`.
