### ISSUE TITLE
Add HTML Editor component

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#171]
Add Editor component.

This is an issue for the new Editor component.

Here you can share your ideas for features that will be essential for the component as this will help us prioritize them.

**Comment by PaitoAnderson** [comment]
@simonssspirit - are you thinking something like https://draftjs.org/?

**Comment by simonssspirit** [comment]
@PaitoAnderson Yes, the core idea of the Editor component will be similar. Still, the UX and the functionalities may differ. We will try to add more complex functionalities over time to improve it.

You can take a look at our Editor component for jQuery, to see in what direction we are going in terms of looks and functionalities:

https://demos.telerik.com/kendo-ui/editor/index

**Comment by morpheis91** [comment]
Will the Editor component come with the image browser on its initial release? Do you know the core Editor features that will roll out with its initial release compared to the original jquery one?

**Comment by nstoychev** [comment]
Initial dev version is live - https://www.telerik.com/kendo-react-ui-develop/components/editor/

Here is how to obtain the development releases - https://www.telerik.com/kendo-react-ui-develop/components/installation/development-builds/

Additionally, we plan to release in the first version table insert/edit, paste clean functionality and a few more demos showing customizing all the rendering, inline editing and markdown editing.

[Image and File browser dialogs](https://demos.telerik.com/kendo-ui/editor/imagebrowser) could be the next.

**Comment by PaitoAnderson** [comment]
Just checking out the new editor, looks impressive!

Is there a way to programmatically get the HTML as a string for the current editor state?

**Comment by Xizario** [comment]
@PaitoAnderson, 

Thanks for the positive feedback, all credits go to @nstoychev.

There is a [bit easier](https://www.telerik.com/kendo-react-ui/components/editor/api/Editor/#toc-contentelement) way.
```jsx
this.editor.contentElement.innerHTML
```

**Comment by nstoychev** [comment]
@PaitoAnderson - Good question. We will make a demo showing how to get and set HTML to the editor. The above is valid, but by design it should be something like this:
```
import { EditorUtils } from '@progress/kendo-react-editor';

const editorRef = this.editor;
const view = editorRef.state.view;

// gets the html
const html = EditorUtils.getHtml(view.state);

// sets the html
EditorUtils.setHtml(view, html);
```

**Comment by morpheis91** [comment]
WHen will the image editor be rolled out in react?
