### ISSUE TITLE
[Bug][Grid] Wrapping DragAndDrop over a Grid with enabled reordering throws error when the header cell is dragged 

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1711]
The Grid uses Draggable for handling the reordering of the columns and if DragAndDrop is used for reordering rows, the columns reordering throws an error due to the double initialization for drag&drop:
https://stackblitz.com/edit/react-3cenyq-xtigta?file=app%2Fmain.tsx

To reproduce the issue, try to reorder any columns from the header cell.

Something that we can investigate as a possible solution is to add "filter" option for the DragAndDrop (useDraggable, useDroppable) to avoid specific elements (maybe a callback function for manually filtering the elements)

**Comment by iadnonov** [comment]
Reported in Ticket ID: 1626615

**Comment by WissamProgress** [comment]
Also reported in Ticket ID: 1647410

**Comment by zdravkov** [comment]
fixed in the latest version of KendoReact 8.1.1 - https://stackblitz.com/edit/react-3cenyq-hvxpzz?file=package.json
