### ISSUE TITLE
[ComboBox] - Screen readers don't read selected items properly

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1723]
Currently, screen readers read the value 1 of 12 instead of 1 of total when virtualization is enabled. This can be seen in the following demo:

https://www.telerik.com/kendo-react-ui/components/dropdowns/combobox/virtualization/

Ticket ID: 1626667

**Comment by iadnonov** [comment]
Fixed in dev version v7.0.0-develop.4
