### ISSUE TITLE
[Grid] Grid reordable causes an error when is in DragAndDrop component

### ISSUE THREAD

**Issue by iadnonov** [telerik/kendo-react#1724]
Currently when you use Grid with reordable=true in DragAndDrop component, clicking over the Grid header cells throws an error `element.getBoundingClientRect is not a function`.

This can be reproduced in the following example:

https://codesandbox.io/s/clever-alex-c7fxkm

Steps to reproduce:
1. Open the demo
2. Try to drag the Grid with some of the header cells

Ticket ID: 1626615

**Comment by kdikov82** [comment]
Duplicate: https://github.com/telerik/kendo-react/issues/1711
