### ISSUE TITLE
[ColorPicker] Gradient Popup Slider Doesn't Work When "#FFFFFF"

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1726]
When the color picker value is set to #FFFFFF the slider on the right doesn't do anything when used. This is reproducible on the website.

1. Go to https://codesandbox.io/s/priceless-platform-97vhsc?file=/public/index.html
2. Try and use the slider to select a "blue" color, which doesn't work
3. Click somewhere in the grid to change the color to e.g. "red"
The slider will work now and you can go to "blue" but it's weird that it has to be in this order

Ticket ID: 1626764

**Comment by filipKovachev** [comment]
Reported again in Ticket ID: 1652973

**Comment by vveesseelliinnaa** [comment]
Duplicate of this one - https://github.com/telerik/kendo-react/issues/1452
