### ISSUE TITLE
[Bug][PDFViewer] The "pages" value within the onLoad event is undefined

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1727]
It is not possible to retrieve the total number of pages, which value should be available within the PDFViewerHangle:
https://www.telerik.com/kendo-react-ui/components/pdfviewer/api/PDFViewerHandle

Tested with version 6.0.0:
https://www.telerik.com/kendo-react-ui/components/pdfviewer/events/

const onLoad = ev =>{
  ev.target.pages.length  is undefined
}

**Comment by nstoychev** [comment]
Fixed in our dev channel version 6.0.3-dev.202310161202.
