### ISSUE TITLE
MultiSelect closes upon selection (autoClose)

### ISSUE THREAD

**Issue by Nodios** [telerik/kendo-react#173]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
When the item is selected in MultiSelect, a list with items closes and you have to open it again to select another one. You do not have the option to disable that behaviour.

## Expected behavior
Have the ability to choose if we want MultiSelect to autoClose or no.

## What is the motivation or use case for changing the behavior?
MultiSelects that close everytime you select an item are generally considered as bad UX. Also, you are supporting autoClose feature in the [jQuery implementation of MultiSelect](https://docs.telerik.com/kendo-ui/api/javascript/ui/multiselect/configuration/autoclose)

**Comment by simonssspirit** [comment]
We have an item logged for this, please cast your vote to increase its chances to be implemented sooner. The link also contains an example of how it can be achieved in the current version by controlling the opened state:

https://feedback.telerik.com/kendo-react-ui/1384494-kendoreact-multiselect-request-to-add-the-autoclose-property

**Comment by nstoychev** [comment]
Implemented in 2.8.0-dev.201903081502 version. Please refer to the following article about obtaining the development builds - https://www.telerik.com/kendo-react-ui/components/installation/development-builds/.

**Comment by Xizario** [comment]
Fixed in `2.8.0`
