### ISSUE TITLE
TreeViewDragClue impossible to show insert bottom icon

### ISSUE THREAD

**Issue by More4ever** [telerik/kendo-react#1731]
## I'm submitting a...

* Bug report 

## Current behavior
When we call TreeViewDragClue.show function with such class name `k-i-insert-down` ui display cancel icon

## Expected behavior
UI should show correct icon (insertBottomIcon)

## Minimal reproduction of the problem with instructions

STEPS TO REPRODUCE: Try to drug any item after
Demo: [Official demo of DnD (minor changes)](https://codesandbox.io/s/strange-drake-pj2rm7?file=/app/main.jsx:2191-2252)

## What is the motivation or use case for changing the behavior?
It is a bug and should be fixed

## Environment

Package versions:
- 6.0.2
- 5.19.0
- 5.14.1

Browser:
- Chrome (desktop) Version 117.0.5938.149 (Official Build) (x86_64)

System:
- TypeScript version: 10.9.1 (ts-node)
- Node version: 18
- Platform:  Mac

```
    TreeViewDragClue.prototype.render = function () {
        var dynamicStyle = { top: this.state.top + 'px', left: this.state.left + 'px' };
        return this.state.visible && (React.createElement("div", { className: "k-header k-drag-clue", style: __assign(__assign({}, this.props.style), dynamicStyle) },
            React.createElement(IconWrap, { className: classNames('k-drag-status'), name: this.state.operationClassName && toIconName(this.state.operationClassName), icon: this.state.operationClassName === 'k-i-plus' ? plusIcon
                    : this.state.operationClassName === 'k-i-insert-up' ? insertTopIcon
                        : this.state.operationClassName === 'k-i-insert-up' ? insertBottomIcon
                            : this.state.operationClassName === 'k-i-insert-middle' ? insertMiddleIcon
                                : cancelIcon }),
            this.state.text));
    };
    ```

**Comment by kdikov82** [comment]
A fix for the issue should be available in the next official release
