### ISSUE TITLE
[BUG][Spreasheet][NextJS] Multiple uses of browser API during SSR

### ISSUE THREAD

**Issue by elena-gancheva** [telerik/kendo-react#1732]
There are multiple uses of browser API in the root of a module inside through the `@progress/kendo-spreasheet-common` package, which results in an error during SSR env (e.g. NextJS or Gatsby).

### Steps to reproduce
Run the [overview demo of the spreadshteet](https://www.telerik.com/kendo-react-ui/components/spreadsheet/) in a nextjs app with the `use client` directive.

I managed to find the following occurrences so far, but they keep popping one after another after commenting them out:
- https://github.com/telerik/kendo-spreadsheet-common/blob/develop/src/eventlistener.js#L21
- https://github.com/telerik/kendo-spreadsheet-common/blob/e3a5f20af04b84d47a08e03aaa8164e365648258/src/kendo.dom.js#L200
- https://github.com/telerik/kendo-spreadsheet-common/blob/e3a5f20af04b84d47a08e03aaa8164e365648258/src/range.js#L983

Related to: https://github.com/telerik/kendo-react-private/issues/3096

**Comment by WissamProgress** [comment]
Fixed in the latest dev version of kendo-spreadsheet-common:
https://www.npmjs.com/package/@progress/kendo-spreadsheet-common/v/1.1.1-develop.1

**Comment by elena-gancheva** [comment]
Fixed in the latest official version of the package
