### ISSUE TITLE
[Bug][MultiColumnComboBox] Styling issue when no scrollbar is present.

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1747]
Currently, if the data set is not large enough for the MultiColumnComboBox component and no scrollbar is present, the header still adjusts for the scrollbar, while the list does not, leading to a misalignment between the two.

This can be observed in the following example:

https://stackblitz.com/edit/react-btev6u-jekxdf?file=app%2Fmain.jsx

Steps to reproduce:
1. Open the MultiColumnComboBox
2. Observe the misalignment

Ticket ID: 1628739

**Comment by WissamProgress** [comment]
duplicate - #1593
