### ISSUE TITLE
DatePicker popup calendar is behind Dialog

### ISSUE THREAD

**Issue by madani2010** [telerik/kendo-react#175]
I would like to report an issue similar to this:
https://github.com/telerik/kendo-react/issues/45

But for DatePicker calendar view being behind Dialog.I am using the workaround as mentioned in the post.
My environment is:

`"dependencies": {
    "@progress/kendo-data-query": "^1.5.0",
    "@progress/kendo-react-dateinputs": "^2.6.1",
    "@progress/kendo-react-dialogs": "^2.6.1",
    "@progress/kendo-react-dropdowns": "^2.6.1",
    "@progress/kendo-react-grid": "^2.6.1",
    "@progress/kendo-react-inputs": "^2.6.1",
    "@progress/kendo-react-intl": "^2.6.1",
    "@progress/kendo-theme-default": "^3.2.0",
    "@progress/kendo-ui": "^2019.1.115",
    "@tinymce/tinymce-react": "^2.3.0",
    "bootstrap": "^3.3.7",
    "deep-diff": "^1.0.2",
    "jquery": "^3.3.1",
    "react": "^16.7.0",
    "react-bootstrap": "^0.32.4",
    "react-dom": "^16.7.0",
    "react-redux": "^5.0.6",
    "react-router-bootstrap": "^0.24.4",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^5.0.0-alpha.8",
    "react-scripts": "2.1.3",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0",
    "rimraf": "^2.6.2"
  },`

**Comment by simonssspirit** [comment]
This is added to the docs: https://www.telerik.com/kendo-react-ui-develop/components/popup/stack-order/
