### ISSUE TITLE
[Combobox] Items with the same name lead to broken keyboard navigation

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1752]
## I'm submitting a...
* Bug report

## Current behavior
Keyboard navigation no longer works properly in combo boxes if at least two entries have the same text. This worked fine in version 5.16.0, but since the changes in version 5.17.0 it no longer works.

Video: http://somup.com/c0X1IMgQbt

## Expected behavior
The user is able to navigate through all items in the Combobox Dropdown.

## Minimal reproduction of the problem with instructions
1. Go to https://stackblitz.com/edit/react-fk5jba-vdc9zb?file=app%2Fdata.ts,app%2Fmain.tsx 
2. Click the ComboBow arrow icon to open the dropdown
3. Start navigating with the arrow keys and try to select "item 11"

Reported in  Ticket ID: 1629830

**Comment by PekoPPT** [comment]
The bug fix will be available in the next version of KendoReact(v. 7.3.1).

**Comment by YKlos** [comment]
> Also reported in Ticket ID: 1640116
> 
> The keyboard navigation is also broken when setting the data to an array of objects and having values of the duplicate textField values. This is the case for all components in the dropdowns package:
> 
> * https://stackblitz.com/edit/react-z7esrx?file=app%2Fmain.tsx
> 
> It is expected in this case that the unique `idField` is taken into consideration when navigation through the keyboard.

This case is still not fixed! The Keyboard navigation is still broken in this case. Please reopen.

**Comment by WissamProgress** [comment]
Hi @YKlos 
Please accept our apologies for missing this in the bug fix. I opened a new issue for fixing it. You can track it here:

- #2179
