### ISSUE TITLE
[Bug][Editor] Toolbar keyboard navigation stops working

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1757]
## I'm submitting a...

* Regression report 

## Current behavior
The user is not able to navigate between the different dropdowns in the Editor with the keyboard. 

## Expected behavior
The user should be able to navigate between the different dropdowns in the Editor with the keyboard as used to be. 

## Minimal reproduction of the problem with instructions
 1. Go to the overview demo of the Editor - https://stackblitz.com/edit/react-av4xv3?file=app%2Fmain.tsx
 2. Try to navigate back and forward between the dropdown buttons via the arrow keys.

## Environment

Package versions:
6.1.0

Reported in Ticket ID: 1630649

**Comment by WissamProgress** [comment]
Also reported in Ticket ID: 1630953

**Comment by iadnonov** [comment]
The issue has been resolved in version [6.1.1](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#v6.1.1).
