### ISSUE TITLE
Dialog Window - Controls are not editable

### ISSUE THREAD

**Issue by MrVJones** [telerik/kendo-react#176]
There is a bug in the dialog component. The Controls on it - also on your demo - are not editable

https://www.telerik.com/kendo-react-ui/components/dialogs/window/

**Comment by simonssspirit** [comment]
This is fixed in the dev version 2.7.0:

https://www.telerik.com/kendo-react-ui-develop/components/dialogs/window/

https://www.telerik.com/kendo-react-ui/components/installation/development-builds/
