### ISSUE TITLE
[Bug][Spreadsheet] File do not load an error is thrown on scrolling when using StrictMode and 

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1761]
With enabled StrictMode, an error is thrown when scrolling the Spreadsheet and it is also not possible to load files:

- https://stackblitz.com/edit/react-tdxgla-wf5tft?file=app%2Fmain.jsx

(removing the StrictMode resolves the error on scroll and loads the file correctly)

**Comment by bptodorova** [comment]
Fixed in v7.0.0-develop.12.
