### ISSUE TITLE
[Bug][ColorPicker] Using IntlProvider with "," for decimal separator prevents "alpha" from being set

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1763]
When locale with comma decimal separator is set, the alpha input value could not be set (the value can't be parsed and an error is thrown).

To reproduce, open the following example:
https://codesandbox.io/s/wonderful-kare-lr3x4h?file=/app/es.json

Open the popup of the picker and switch the input to RGBA and try setting an alpha value.

**Comment by iadnonov** [comment]
The issue is fixed in our latest develop version 9.1.0-develop.3
