### ISSUE TITLE
[Bug][Grid] Scrolling horizontally leaves blank space when using column virtualization in Safari

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1774]
## I'm submitting a...

* Bug report 

## Current behavior
If you scroll horizontally the Grid in Safari with enabled virtualization, a blank space appears.

## Expected behavior
No blank space should appear when scrolling

## Minimal reproduction of the problem with instructions
1. Open the following demo in Safari: https://stackblitz.com/edit/react-5fgu89-cct9zu?file=app%2Fmain.jsx
2. Scroll horizontally and observe the blank space that is appearing.

https://github.com/telerik/kendo-react/assets/92358162/3d0ecea5-4492-45d3-9d6c-8293c9335ee6

## Additional Information
Reported in Ticket 1631991

**Comment by zdravkov** [comment]
Fixed in the latest version of KendoReact - https://stackblitz.com/edit/react-5fgu89-2pkvas?file=index.html
