### ISSUE TITLE
[Bug][Grid] Switching a column from "locked" to "unlocked" state keeps the "left" value in the inline style

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1786]
To observe the issue:
1) Open the following example: https://stackblitz.com/edit/react-y7cf51?file=app%2Fmain.jsx
2) Click the button to lock the last column and then unlock it

Result - the layout in the header is broken due to the "left" value being kept within the TH element.

**Comment by kdikov82** [comment]
Please check the following example as well with the fix, which breaks the layout when additional locked columns are added:
https://stackblitz.com/edit/react-hsvj4z?file=app%2Fmain.jsx

Steps to reproduce: 
1. Click on Lock button will freeze following fields ID and Name.
2. After that click on Lock Extra button to freeze additional fields  CategoryName and Price. 
Result - Now you will see column Name is overlapping.

*The issue can be resolved by re-mounting the Grid by changing its key value when the locked state is changed:
https://stackblitz.com/edit/react-hsvj4z-tlgczc?file=app%2Fmain.jsx

**Comment by iadnonov** [comment]
Probably related to: https://github.com/telerik/kendo-react/issues/1745

**Comment by iadnonov** [comment]
Fixed in dev version [v7.2.4-develop.1](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#v7.2.4-develop.1)
