### ISSUE TITLE
[Bug] [Signature] Color is not applied for the signature

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1794]
## I'm submitting a...
* Bug report

## Current behavior
Creating a signature then setting the color applies only visually, but not in the export after pressing the save button.

## Expected behavior
The color is applied in the export like in the Kendo UI for Angular signature - https://www.telerik.com/kendo-angular-ui/components/inputs/signature/

## Minimal reproduction of the problem with instructions
1. Open the overview demo - https://www.telerik.com/kendo-react-ui/components/inputs/signature/
2. Draw a signature
3. Change the brush color which causes the signature to change color
4. Press save or click on the upload button and click again on the signature button in the ButtonGroup

Reported in Ticket ID: 1634057

**Comment by PekoPPT** [comment]
Closing this issue as the reported behavior is no longer replicable.
