### ISSUE TITLE
[Bug][ToolTip] ToolTip does not show when hovering the Button text

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1798]
## I'm submitting a...

* Bug report 

## Current behavior

The KendoReact ToolTip is only shown when hovering above the Button element and not its text.

## Expected behavior

The ToolTip is shown when hovering any element of the Button component.

## Minimal reproduction of the problem with instructions

1. Open this demo - https://stackblitz.com/edit/react-2vgze7-wnpupu?file=app%2Fmain.tsx
2. Hover above the Button text "save"
3. The ToolTip is not shown

## Workaround

Use the html button and set its className to `k-button k-button-md k-button-solid k-button-solid-base k-rounded-md` to have the same visual appearance.

- https://stackblitz.com/edit/react-2vgze7-jkzbqn?file=app%2Fmain.tsx

Reported in Ticket ID: 1634142

**Comment by kdikov82** [comment]
The Tooltip should have "parentTitle" to true in order to show the tooltip:
https://stackblitz.com/edit/react-2vgze7-1uhxxq?file=app%2Fmain.tsx
