### ISSUE TITLE
@progress/kendo-react-pdf-viewer missing in @progress/kendo-react-all

### ISSUE THREAD

**Issue by Tommuh** [telerik/kendo-react#1801]
The title says it all.

When using @progress/kendo-react-all the pdf viewer is missing can this be added?

**Comment by nstoychev** [comment]
@Tommuh It should be there. Can you check in version 7.0.2 - https://unpkg.com/browse/@progress/kendo-react-all@7.0.2/

**Comment by Tommuh** [comment]
Sorry for the very late response. The PDF viewer is still not present in the all build 7.1

![image](https://github.com/telerik/kendo-react/assets/2089879/f4691eb8-3856-4d79-bb97-6e517ced5d51)

**Comment by Tommuh** [comment]
@WissamProgress could you please re-open this issue?

**Comment by nstoychev** [comment]
Hi @Tommuh,

I checked it again and found out that the pdf-viewer is missing in the peerDependencies of `@progress/kendo-react-all`. I made a PR with a fix.

As a workaround, you can install the `@progress/kendo-react-pdf-viewer` package along with the `@progress/kendo-react-all`. The `@progress/kendo-react-all` package re-exports the `@progress/kendo-react-pdf-viewer`, so this should be enough.

**Comment by Tommuh** [comment]
Thank you for re-opening. 

Yes I did exactly what you said as work around. Thanks for the support.

**Comment by elena-gancheva** [comment]
The fix is provided in the latest `dev` version of the package
