### ISSUE TITLE
[TypeScript] Missing types for packages

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1802]
The interfaces are not exported in the packages with versions 7.0.0 and 7.0.1
```
import { SplitButtonProps, ToolbarSeparatorProps } from "@progress/kendo-react-buttons";
import { CardBodyProps, CardFooterProps, CardHeaderProps, CardImageProps, CardSubtitleProps, CardTitleProps } from "@progress/kendo-react-layout";
etc.
```
(https://github.com/telerik/kendo-react-private/pull/3295)

**Comment by vveesseelliinnaa** [comment]
The fix is available in version 7.0.2 of KendoReact:
https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#v7.0.2
