### ISSUE TITLE
[Bug][Checkbox] A JS error is thrown when the Checkbox is loaded from scripts

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1809]
## I'm submitting a...
* Regression report 

## Current behavior

There are JavaScript errors thrown on the page when the Checkbox is loaded from scripts:
![image](https://github.com/telerik/kendo-react/assets/6196386/10c0fb79-8bda-4649-b993-ecfea3bc63c3)

## Expected behavior
All components should be loaded without errors.

## Minimal reproduction of the problem with instructions
1. Go to [https://dojo.telerik.com/oBEsasaH](https://dojo.telerik.com/oBEsasaH)
2. Open the console and run the page

## Environment

Package versions: 7.0.2

## Additional information

Reported in Ticket ID: 1632828

**Comment by elena-gancheva** [comment]
The fix is available in the latest dev version of the package
