### ISSUE TITLE
axios is locked to 1.6.0 in peer dependencies of @progress/kendo-react-upload

### ISSUE THREAD

**Issue by BCaspari** [telerik/kendo-react#1810]
## Current behavior
@progress/kendo-react-upload7.0.2 locks the peer depency axios to 1.6.0 which breaks npm i for our project that uses axios 1.6.2

## Expected behavior
Peer dependency should be `"axios": "^1.6.0"`, not `"axios": "1.6.0"`.

**Comment by WissamProgress** [comment]
This was fixed in the following dev version:

- https://www.npmjs.com/package/@progress/kendo-react-upload/v/7.0.3-develop.7
