### ISSUE TITLE
[Bug][MultiViewCalendar] Incorrect selection when navigating the component

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-react#1815]
## I'm submitting a...
* Bug report 

## Current behavior
The MultiViewCalendar navigation is not working correctly 

## Expected behavior
Clicking on the months/years in the component should navigate us to the selected year or month 

## Minimal reproduction of the problem with instructions
1. Go to https://www.telerik.com/kendo-react-ui/components/dateinputs/multiviewcalendar/
1. Click on months' label
![image](https://github.com/telerik/kendo-react/assets/41293735/79c1c012-2487-4180-8907-2d60709a3bfc)
1. Click any other month that is different from the one you were in
![image](https://github.com/telerik/kendo-react/assets/41293735/df3989dd-f8f1-4e58-a82c-94762bcc3451)
1. The result is that the component shows the wrong (previous) month
![image](https://github.com/telerik/kendo-react/assets/41293735/f1495247-5d14-4b9a-bcfb-10f9b2229b01)

**Comment by elena-gancheva** [comment]
The fix is available in the latest `dev` version of the package.
