### ISSUE TITLE
Broken links in the homepage and in the 404 page

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-react#1817]
1) I wanted to showcase the **KendoReact** Drag&Drop functionality to a friend of mine.  The first google result points to 
https://www.telerik.com/kendo-react-ui/drag-and-drop
Where there is big link "Docs & Demos":
https://www.telerik.com/kendo-react-ui/components/utils/drag-and-drop/
![404](https://github.com/telerik/kendo-react/assets/9458606/61200bcf-2498-44ce-ad8a-c51526acf683)

2) And the "Homepage" link on this 404 page does not work either.

**Comment by zdravkov** [comment]
It's great to hear from you, Vasko!. Thanks for the PR and the report! We will add a redirect as soon as possible.

**Comment by zdravkov** [comment]
Redirect is applied,
