### ISSUE TITLE
Resizable Grid with columns with width set to "" or undefined will set the column width to mimResizableWidht on click

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#182]
Resizable Grid with columns with width set to " " or undefined will set the column width to mimResizableWidht on click.

**Comment by Xizario** [comment]
If the Grid is resizable, columns are fixated to specific width based on their current width and the [minResizableWidth](https://www.telerik.com/kendo-react-ui/components/grid/api/GridColumnProps/#toc-minresizablewidth) works this way by design.
