### ISSUE TITLE
Missing types for kendoReact Form ref

### ISSUE THREAD

**Issue by Jodelopa** [telerik/kendo-react#1829]
I'm submitting a Bug report 

## Current behavior
Missing types for React.Form ref since Kendo.React v7

## Minimal reproduction of the problem with instructions
Open it in Stackblitz by using
https://stackblitz.com/edit/vitejs-vite-kw2cau?file=src%2Fform.tsx

**Comment by zdravkov** [comment]
In v7 of KendoReact the is a slight change in this API and we can use [FormHandle](https://www.telerik.com/kendo-react-ui/components/form/api/FormHandle/).
