### ISSUE TITLE
Dropdown class name applied on parent & child <span>

### ISSUE THREAD

**Issue by Nodios** [telerik/kendo-react#183]
This is more of a general question: 

When you pass `className` property to a Dropdown component, provided value is applied on 2 spans.

Consider this example: [link](https://stackblitz.com/edit/react-ldklub?file=app%2Fmain.js)

If you inspect dropdown element, you'll see this: 
![image](https://user-images.githubusercontent.com/7250398/52219051-2eff4000-289c-11e9-969f-3bc351814bf3.png)

Is there a purpose behind this or this is a bug?

**Comment by nstoychev** [comment]
Fixed in 2.8.0-dev.201903081502 version. Please refer to the following article about obtaining the development builds - https://www.telerik.com/kendo-react-ui/components/installation/development-builds/.

**Comment by Xizario** [comment]
Fixed in `2.8.0`
