### ISSUE TITLE
Currency symbols are missing with CLDR 44.1.0

### ISSUE THREAD

**Issue by Jodelopa** [telerik/kendo-react#1838]
## I'm submitting a...
* Bug report

## Current behavior
With CLDR 44.1.0 some currencies have no symbol and instead shows an `undefined`

## Expected behavior
Show the correct symbol

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-pwvbhp?file=app%2Fmain.jsx

**Comment by WissamProgress** [comment]
Reported in Ticket ID: 1637323

**Comment by WissamProgress** [comment]
Fixed with the latest dev version of `kendo-intl`:

- https://stackblitz.com/edit/react-pwvbhp-e4u7sy?file=package.json

npmjs link:

- https://www.npmjs.com/package/@progress/kendo-intl/v/3.1.2-dev.202401081506

**Comment by Jodelopa** [comment]
fix still not realeased after 2 weeks

**Comment by WissamProgress** [comment]
@Jodelopa Apologies for that. We contacted the `kendo-intl` team in order to push an official release that includes the bug fix.

**Comment by WissamProgress** [comment]
@Jodelopa Apologies for that. We released a new official version of the `kendo-intl` package:

- https://www.npmjs.com/package/@progress/kendo-intl/v/3.1.1

Here is an example with the latest `3.1.1` kendo-intl package version:

- https://stackblitz.com/edit/react-x2ksex-vynmb1?file=package.json
