### ISSUE TITLE
CheckBoxLabel is wrapped inside k-checkbox-wrap element

### ISSUE THREAD

**Issue by kvelikov** [telerik/kendo-react#1839]
The Checkbox inputs are not rendered as expected for KendoReact.

There is a class mismatch between the Checkbox implementation and [test specs](https://github.com/telerik/kendo-themes/blob/develop/tests/checkbox/checkbox.html).

The CkeckBoxLabel is wrapped inside <span class="k-checkbox-wrap">

Current behavior
![image](https://github.com/telerik/kendo-react/assets/5024892/01d4fbd6-dc22-4086-afd2-dc84adaa6e80)

Expected/desired behavior
To follow the [test specs](https://github.com/telerik/kendo-themes/blob/develop/tests/checkbox/checkbox.html) the k-checkbox-label element should be outside the k-checkbox-wrap
![image](https://github.com/telerik/kendo-react/assets/5024892/08b06b28-9c3a-4df2-8cea-dae91488e1ad)

**Comment by kvelikov** [comment]
@elena-gancheva

**Comment by elena-gancheva** [comment]
This issue is fixed in the latest version of the package
