### ISSUE TITLE
Part of the typed text is hidden if the symbols are larger.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#184]
Part of the typed text is hidden if the symbols are larger.

The following video demonstrates it: 
https://www.screencast.com/t/ZX6fs6gS

Notice how there is a remaining space, but some of the characters are hidden. This is because we use dynamic logic for the input size, as part of the space can be taken from already chosen items.

We should improve the internal calculation logic.

**Comment by kdikov82** [comment]
Resolved in latest versions
