### ISSUE TITLE
Page is scrolling to the top on resizing columns 

### ISSUE THREAD

**Issue by vkutsenkoYangaroo** [telerik/kendo-react#1850]
Strange behavior happens only when we resize any columns for Kendo-react grid component
no extra re-render during that was not spotted
so seems like something is happening in the component

might be related to issues:
https://github.com/telerik/kendo-react/issues/1437
https://github.com/telerik/kendo-react/issues/1664

**Example:**
![example](https://github.com/telerik/kendo-react/assets/156244501/e306cd27-d2cf-470b-be77-6c9303d0e037)

**lib version**
@progress/kendo-react-grid": "^7.0.2

**Code I used for the example**

```ts
<div style={{ paddingTop: 300 }}>
    <Grid resizable data={Array.from({ length: 100 }, (_, i) => ({ id: i }))}>
        <GridColumn
            field="id"
            title="ID"
            width="45px"
            minResizableWidth={30}
        />
        <GridColumn
            field="id"
            title="ID2"
            width="45px"
            minResizableWidth={30}
        />
    </Grid>
</div>
```

**Comment by WissamProgress** [comment]
Related to https://github.com/telerik/kendo-react/issues/1664
