### ISSUE TITLE
[Bug][Grid] `All` pagesize option is not displayed after selecting it

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1853]
## I'm submitting a...

* Bug report

## Current behavior
When using the `onDataStateChange` event, it adding the `All` value as a pageSize, selecting it is not applied to the pageSize DropDownList.

## Expected behavior
Selecting the `All` value should display it in the DropDown.

## Minimal reproduction of the problem with instructions
1. Open the overview demo and set `pageable.pageSize` to `[5, 10, 14, 'All']` - https://stackblitz.com/edit/react-emapav?file=app%2Fmain.jsx
2. Click on the `All` option in the Pager DropDownList

Reported in Ticket ID: 1636929

**Comment by spatil77937** [comment]
Also selecting all should hide buttons as well of pages. We are having this issue in production , can you please give priority to it...

**Comment by WissamProgress** [comment]
It appears that this is not a bug as this functionality is achieved in the `onDataStateChange` event handler where you can set the `take` property to `products.length` when `targetEvent.value` equals `All`, or whatever string you set in the `pageSizes`.

Here is an example with the `onDataStateChange` event and the `process` method:

- https://stackblitz.com/edit/react-kaq9oq?file=app%2Fmain.tsx

Nevertheless, this information should be added to the documentation, which we will do.

**Comment by WissamProgress** [comment]
@spatil77937 does [this demo](https://stackblitz.com/edit/react-kaq9oq?file=app%2Fmain.tsx) match what you need?
