### ISSUE TITLE
@progress/kendo-react-upload@7.0.2 has a hard dependency on axios 1.6.0 and breaks my build.

### ISSUE THREAD

**Issue by gregbrant2** [telerik/kendo-react#1854]
## I'm submitting a...

* Bug report 

## Current behaviour
@progress/kendo-react-upload@7.0.2 has a hard dependency on axios 1.6.0 and breaks my build

kendo-react-private/packages/upload/package.json
``` 
...
  "peerDependencies": {
    "@progress/kendo-licensing": "^1.3.4",
    "@progress/kendo-react-buttons": "0.0.0-PLACEHOLDER",
    "@progress/kendo-react-common": "0.0.0-PLACEHOLDER",
    "@progress/kendo-react-intl": "0.0.0-PLACEHOLDER",
    "@progress/kendo-react-progressbars": "0.0.0-PLACEHOLDER",
    "@progress/kendo-svg-icons": "^2.0.0",
    "axios": "1.6.0",
    "react": "^16.8.2 || ^17.0.0 || ^18.0.0",
    "react-dom": "^16.8.2 || ^17.0.0 || ^18.0.0"
  },
...
```

Output from build
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @progress/kendo-react-upload@7.0.2
npm ERR! Found: axios@1.6.5
npm ERR! node_modules/axios
npm ERR!   axios@"^1.6.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer axios@"1.6.0" from @progress/kendo-react-upload@7.0.2
npm ERR! node_modules/@progress/kendo-react-upload
npm ERR!   @progress/kendo-react-upload@"^7.0.2" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: axios@1.6.0
npm ERR! node_modules/axios
npm ERR!   peer axios@"1.6.0" from @progress/kendo-react-upload@7.0.2
npm ERR!   node_modules/@progress/kendo-react-upload
npm ERR!     @progress/kendo-react-upload@"^7.0.2" from the root project
npm ERR! 
```

## Expected behavior
I should be able to use any compatible version (minor/patch at least) of axios. The dependency in package.json should probably be an at-least constraint

```
    "^axios": "1.6.0",
```

## What is the motivation or use case for changing the behavior?

Because I want to keep my packages up to date.

## Environment

Package versions:

Browser:

N/A this is a build-time issue

System:
- Github actions runner on `ubuntu-latest`
- Node version: 20.9
- Platform:  Linux

**Comment by vissnxk** [comment]
I am getting the same Error. latest version of axios is 1.6.5

**Comment by WissamProgress** [comment]
The axios version was changed from `1.6.0` to `^1.6.0`, and this fix is available from the following dev version up to the latest one:

- https://www.npmjs.com/package/@progress/kendo-react-upload/v/7.0.3-develop.7

This fix will also be available in the upcoming official release.
