### ISSUE TITLE
[Bug][Grid] Columns slightly misaligned with the column header

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1856]
## I'm submitting a...

* Bug report

## Current behavior
The GridColumns are slightly misaligned with the column header
<img width="1728" alt="Screenshot 2024-01-12 at 10 06 25" src="https://github.com/telerik/kendo-react/assets/108671796/167e1823-50a4-403d-984c-d818a70e9f5f">

## Expected behavior
The columns should be aligned properly

## Minimal reproduction of the problem with instructions
It can be seen in the getting started demo for the Price column - https://www.telerik.com/kendo-react-ui/components/grid/get-started/

However, it is clearer in the overview demo after horizontally scrolling the Grid to the right - https://www.telerik.com/kendo-react-ui/components/grid/
In that case, all the columns after the `Engagement` column get misaligned with the column header:
<img width="875" alt="Screenshot 2024-01-12 at 10 04 37" src="https://github.com/telerik/kendo-react/assets/108671796/ec80c578-7f13-427d-9b54-25b5dca48904">

Reported in Ticket ID: 1633865

**Comment by vveesseelliinnaa** [comment]
Reported also in Ticket ID: 1642490

The problem can be seen very easily when the browser is zoomed (e.g. to 150-200%) or the OS is scaled (e.g. 150% for Windows).

**Comment by vveesseelliinnaa** [comment]
Reported again in Ticket ID: 1646392

**Comment by zdravkov** [comment]
Fixed in the lates KendoReact version.
