### ISSUE TITLE
[Bug][DatePicker and DateRangePicker] Today button does not update the input when format is set

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1863]
## I'm submitting a...
* Bug report

## Current behavior
When setting the format prop such that the format do not include the year value, pressing the Today button does not update the input element with today's date.
Nevertheless, the correct value is set to the component and the correct date is received in the `onChange` event handler.

## Expected behavior
Pressing the Today button updates the input element with the correct date.

## Minimal reproduction of the problem with instructions
set the date to "MM-dd"
https://stackblitz.com/edit/react-hxv8oe-7kb1pb?file=app%2Fmain.tsx

## Workarounds

Handle the component in controlled mode, and set initial values
https://stackblitz.com/edit/react-hxv8oe-ivygic?file=app%2Fmain.tsx

Include the year in the format
https://stackblitz.com/edit/react-hxv8oe-ayutvq?file=app%2Fmain.tsx

Ticket ID: 1636933

**Comment by WissamProgress** [comment]
This bug is not reproducible with the same example included in the description even when not changing the versions and dependencies. Therefore, the issue might be specific to today's date.

**Comment by iadnonov** [comment]
Not reproducible with our latest version [v8.5.0](https://github.com/telerik/kendo-react-private/releases/tag/v8.5.0).

If you are still facing the issue, please do not hesitate to leave a comment with details, and we will investigate it further.
