### ISSUE TITLE
[Bug][Grid] Selection checkboxes do not have labels

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1866]
## I'm submitting a...
* Bug report 

## Current behavior
The grid row selection checkboxes have empty/hidden labels being found by accessibility checkers (Axe)

## Expected behavior
Each checkbox must have a label.

## Minimal reproduction of the problem with instructions
1. Open this demo to a[ new tab](https://codesandbox.io/p/sandbox/morning-violet-ytwzdm) - https://ytwzdm.csb.app/
2. Open AXE DevTools and scan the page

Result: 
![image](https://github.com/telerik/kendo-react/assets/6196386/be68673d-6484-40a1-a4c6-8d0682dc03eb)

## What is the motivation or use case for changing the behavior?

Reported in Ticket ID: 1637040

**Comment by silviyaboteva** [comment]
This pull request is included in version 7.2.0.
