### ISSUE TITLE
zoomable functionality is not working.

### ISSUE THREAD

**Issue by shellsk** [telerik/kendo-react#1867]
When I want to zoom the Radar plot,the zoomable functionality is not working.
## I'm submitting a...

My code:
import React from "react";
import {
  Chart,
  ChartLegend,
  ChartSeries,
  ChartSeriesItem,
  ChartTitle,
  ChartValueAxis,
  ChartValueAxisItem,
  exportVisual,
} from "@progress/kendo-react-charts";
import { exportImage, exportPDF, exportSVG } from "@progress/kendo-drawing";
import { saveAs } from "@progress/kendo-file-saver";
import { useRef } from "react";
import data from "./radar-data.json"; 
import "hammerjs";
const RadarChat = () => {
  const chartRef = useRef();
 
  const transformedData = data.flatMap((item) =>
    item.test.map((testValue, index) => ({
      name: item.name,
      test: testValue,
      index, // Include an index to distinguish multiple values for the same name
    }))
  );
  const uniqueFields = Array.from(
    new Set(transformedData.map((item) => item.index))
  );
  return (
    <div>
      <button onClick={onImageExportClick}>Export as Image</button>
      <Chart zoomable={true} ref={chartRef}>
        <ChartTitle text="Market Value of Major Banks /bln/" />
        <ChartSeries>
          {uniqueFields.map((field) => (
            <ChartSeriesItem
              key={field}
              type="radarLine"
              data={transformedData.filter((item) => item.index === field)}
              field="test"
              categoryField="name"
              name={`Test ${field + 1}`} // Adjust the naming as needed
            />
          ))}
        </ChartSeries>
        <ChartValueAxis>
          <ChartValueAxisItem
            labels={{
              format: "£0.00",
            }}
          />
          <ChartValueAxisItem min={6618} max={9999} />
        </ChartValueAxis>
        <ChartLegend position="bottom" />
      </Chart>
    </div>
  );
};
export default RadarChat;

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Current behavior
I f I want to expand the chart by making zoomable=true, it is not zooming in.

## Expected behavior

Radar plot should have the functionality like , zoomable functionality islike linear types
## Environment

Package versions:

```
React18
```"hammerjs": "2.0.8",
data:

[
  { "name": "HSBC", "test": [200, 500] },
  { "name": "Credit Suisse", "test": [215] },
  { "name": "Goldman Sachs", "test": [75] }
]

Browser:
<!-- Leave only the browsers that you tested the issue with. -->
- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX <!-- run tsc --version -->
- Node version: XX  <!-- run "node --version" and "npm --version"-->
- Platform:  <!-- Mac, Linux, Windows -->

<!-- Add any additional information that might be relevant. -->

**Comment by zdravkov** [comment]
Hello @shellsk ,

Thank you for reaching out to us.

With the current implementation of the Chart component, zoomable functionality is only applicable to linear types, where the range on the X axis can be changed based on the zoom level. 

However, I do agree that in some cases it would be useful to have the zoomable functionality for radial types as well, so you can log a feature request about it in our [feedback portal](https://feedback.telerik.com/kendo-react-ui). 

Greetings,
Plamen
