### ISSUE TITLE
If the value of the TimePicker is null, clicking the NOW button sets the year to 1980 

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#187]
If the value of the TimePicker is null, clicking the NOW button sets the year to 1980.

This can be observed here:

https://stackblitz.com/edit/react-feh9v4?file=app/main.js

**Comment by Xizario** [comment]
If you are using TimePicker the date should be irrelevant to you.

**Comment by vladimirivanoviliev** [comment]
Fixed in latest version
