### ISSUE TITLE
TreeView onFocus scrolls up

### ISSUE THREAD

**Issue by antoniosZil** [telerik/kendo-react#190]
## I'm submitting a...

* Bug report 

## Current behavior
When TreeView data is more than what fits in the TreeView render area and a vertical scrollbar appears, before clicking/focusing on the TreeView, if we scroll down the tree and then focus/click, the scroll position is lost and the TreeView component scrolls to the top, selecting/focusing the first element. Even if a data item has selected:true, this still happens on the first focus. Note. it happens only on the first focus.

## Expected behavior
On focus, initial or subsequent, the scroll position should not get affected and the item clicked, should get focused/selected, not the first item in the data list.

## Minimal reproduction of the problem with instructions
To reproduce, simply go to any example, like this one:
https://twj8am.run.stackblitz.io
(which was taken from here)
https://www.telerik.com/kendo-react-ui/components/treeview/
then, resize the browser window height to be small enough so that a vertical scrollbar appears.
scroll down to the last treeView item and then click it.

## What is the motivation or use case for changing the behavior?
any scenario where there are more data items than can fit into the view, cause this on initial click/focus... it requires the user to click twice just to select one item.

## Environment
latest chrome browser

Package versions:

```

```

Browser:
- Chrome (desktop) version 72

System:
- Platform:  Mac

**Comment by asen-arizanov** [comment]
Thank you for reporting the issue. We have started working on the fix.
