### ISSUE TITLE
[Bug][DropDownButton] className not applied

### ISSUE THREAD

**Issue by zoran995** [telerik/kendo-react#1915]
When trying to `className` on the DropDownButton it won't be applied. Property that can be used of it is `buttonClass` but that change is not communicated in nor documentation nor changelog. Documentation is still listing a `className` as valid property (check [here](https://www.telerik.com/kendo-react-ui/components/buttons/api/DropDownButtonProps/#toc-classname)). Also `className` is valid prop per typescript definition. This is a breaking change and we had to dig into source code to figure out what is going on.

## I'm submitting a...
* Regression report 
* Bug report 
* Documentation issue or request

## Current behavior
- className not applied

## Expected behavior
- Classname applied to dropdown button, or breaking change communicated through documentation and changelog with type definition updated

**Comment by zdravkov** [comment]
Hi @zoran995 ,

Thank you for reporting the issue - you are right we needed to update the rendering and the className prop was not applied correctly to the root element.

We will do our best to resolve the issue as soon as possible.

Greetings,
Plamen

**Comment by zdravkov** [comment]
fixed in version 7.1.0 of KendoReact
