### ISSUE TITLE
Create a function callback for the Upload saveUrl.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#193]
https://feedback.telerik.com/kendo-react-ui/1388637-create-a-function-callback-for-the-upload-saveurl

**Comment by simonssspirit** [comment]
This is already in dev https://www.telerik.com/kendo-react-ui-develop/components/upload/api/UploadProps/#toc-saveurl

**Comment by simonssspirit** [comment]
This is an example with mocking the requests: https://stackblitz.com/edit/react-bvfjbb?file=app/main.jsx

**Comment by ryancole** [comment]
@simonssspirit I don't see in the links how to set the upload URL. I see the event handler and such but I don't see where to set the URL to which it uploads each file. I'm uploading to Azure blob storage and each file needs its own URL to POST to. How can I set this using this saveUrl method?

**Comment by simonssspirit** [comment]
When the saveURL is a function, the developer makes to request programmatically and has full control over the URL.

**Comment by ryancole** [comment]
Oh I see! Thank you.

**Comment by ryancole** [comment]
@simonssspirit I'm trying to figure out how to get data from the `onBeforeUpload` event into the `saveUrl` function. When I add data to the `additionalData` object, in `onBeforeUpload`, I can't seem to locate it in the `saveUrl` method. I'm fetching some Azure Shared Access Signatures in the `onBeforeUpload`.

I figure I can just fetch those in the `saveUrl`, instead.

**Comment by robin-netizen** [comment]
using Spring boot as backend, frontend as react, db as mysql.

i have "uploadFile" variable as axios request parameter



        uploadFile = e.affectedFiles[0].name;

e.affectedFiles[0].name do not allocate any value to uploadFile




2021-01-29 10:26:27.741  WARN 10756 --- [io-9002-exec-10] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.multipart.support.MissingServletRequestPartException: Required request part 'uploadFile' is not present]

 

@RestController
@CrossOrigin
public class MemberController {

@Autowired
MemberMapper mapper;


MultipartFile upload;
String photoname;

 

 

@PostMapping(value = "/member/upload", consumes = {"multipart/form-data"})
public Map<String, String> fileUpload(@RequestParam MultipartFile uploadFile, HttpServletRequest request){
String uploadPath = request.getSession().getServletContext().getRealPath("/WEB-INF/photo");
System.out.println(uploadPath);


int pos = uploadFile.getOriginalFilename().lastIndexOf("."); 
String ext = uploadFile.getOriginalFilename().substring(pos);


Date date = new Date();
SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMddHHmmss");
photoname = "jeju" + sdf.format(date) + ext;

upload = uploadFile;

Map<String, String> map = new HashMap<String, String>();
map.put("photoname", photoname);
return map;
}

 

 

 

and 

for react

const fileStatuses = [
    'UploadFailed',
    'Initial',
    'Selected',
    'Uploading',
    'Uploaded',
    'RemoveFailed',
    'Removing'
];




let uploadFile = null;

class SignupPageComp extends Component {


    constructor(props) {
        super(props);

        console.log("SignupPageComp constructor", props);
        
        this.state={
            id:'',  
            pass:'',
            pwCheck: "",
            name : '',
            gender: '',
            photo: null,
            photoname: '',
            address : '',
            addrdetail: '',
            email : '',
            hp : "",
            idcanUse: false,
            files: [],
            events: [],
            filePreviews: {},
        };

    
        this.onIdChk=this.onIdChk.bind(this);
    }

    
    changeEvent=(e)=>{
        
        console.log(e.target.id+":"+e.target.value);
    
        this.setState({
            [e.target.name]:e.target.value
        })
    }


    onIdChk=(e)=>{
        e.preventDefault();
        console.log(this.state.id);
        const data = {
            id: this.state.id
        }
       
        let url = URL + '/member/checkid?id=' + this.state.id;
        axios.get(url)
        .then(response=>{

            if(response.data.idcanUse === "true")
            {
                alert("id okay");
                this.setState({
                    idcanUse: true
                })
            }
            else if(response.data.idcanUse === "false")
            {
                alert("id already exists");
                this.setState({
                    id: '',
                })
            }
        }).catch(err => {
            console.log("id checking error:"+err);
        })
    }

    onSubmitHandler = (e) => {
        e.preventDefault();
        this.onInsertMember();
    };

    
    imageUpload=(e)=>{
        const uploadFile = e.target.files[0];

       
        const memberFile = new FormData();
        memberFile.append("uploadFile",uploadFile);

        axios({
            method: 'post',
            url: URL + '/member/upload',
            data: memberFile,
            headers: {'Content-Type':'multipart/form-data'}
        }).then(response=>{
            alert(response.data.photoname+" => save as this name");

            this.setState({
                photoname: response.data.photoname
            })
        }).catch(err=>{
            console.log("photo upload error:"+err);
        })
    }

    

    onInsertMember = () => {
        let data = this.state;
        let url = URL + "/member/insert";

        axios.post(url, data)
        .then(response => {
           
            this.setState({
                id:'',  
                pass:'',
                pwCheck: "",
                name : '',
                gender: '',
                photo: null,
                photoname: '',
                address : '',
                addrdetail: '',
                email : '',
                hp : "",
                idcanUse: false,
            })

            
            this.props.history.push("/login");
        }).catch(err=>{
            console.log("Sign up error:"+err);
        })
    }

    handleChange = (event) => {
        this.setState({
            gender: event.target.value,
        });
    };

    onAdd = (event) => {
        const afterStateChange = () => {
            event.affectedFiles
                .filter(file => !file.validationErrors)
                .forEach(file => {
                    const reader = new FileReader();

                    reader.onloadend = (ev) => {
                        this.setState({
                            filePreviews: {
                                ...this.state.filePreviews,
                                [file.uid]: ev.target.result
                            }
                        });
                    };

                    reader.readAsDataURL(file.getRawFile());
                });
        };

        this.setState({
            files: event.newState,
            events: [
                ...this.state.events,
                `selected file: ${event.affectedFiles[0].name}`
            ],
        }, afterStateChange);

        uploadFile = event.affectedFiles[0].name;
    }

    onRemove = (event) => {
        const filePreviews = {
            ...this.state.filePreviews
        };

        event.affectedFiles.forEach(file => {
            delete filePreviews[file.uid];
        });

        this.setState({
            files: event.newState,
            events: [
                ...this.state.events,
                `file removed: ${event.affectedFiles[0].name}`
            ],
            filePreviews: filePreviews
        });
    }

    onProgress = (event) => {
        this.setState({
            files: event.newState,
            events: [
                ...this.state.events,
                `on progress: ${event.affectedFiles[0].progress} %`
            ]
        });
    }

    onStatusChange = (event) => {
        const file = event.affectedFiles[0];

        this.setState({
            files: event.newState,
            events: [
                ...this.state.events,
                `File '${file.name}' status changed to: ${fileStatuses[file.status]}`
            ]
        });
    }
    
    render() {
        const { classes } = this.props;
        console.log("SingupPageComp render()", this.props);
        return (
            <div>
                <form
                className={classes.root}
                noValidate autoComplete="off"
                onSubmit = { this.onSubmitHandler.bind(this) }
                >
                <h1>Sing Up</h1>
                <div>
                    <h4 className="showIdResult">{this.state.showIdResult}</h4>
                </div>
                <br />
                <TextField id="standard-secondary" label="email" color="secondary" 
                type="email" name="email" value={ this.state.email }
                onChange = { this.changeEvent.bind(this) } />
                
                
                <br />
                
                
                
                <TextField id="standard-secondary" label="name" color="secondary" 
                type="text" name="name" value={ this.state.name }
                onChange = { this.changeEvent.bind(this) } />

                <br />
                
                <TextField id="standard-secondary" label="id" color="secondary" 
                type="text" name="id" value={ this.state.id }
                onChange = { this.changeEvent.bind(this) } />

                <button type="button"
                onClick={this.onIdChk.bind(this)}>
                    Id Check
                </button>
                <br />
                
                <TextField id="standard-secondary" label="pass" color="secondary" 
                type="password" name="pass" value={ this.state.pass }
                onChange = { this.changeEvent.bind(this) } />

                <br />
                
                <TextField id="standard-secondary" label="passwordcheck" color="secondary" 
                type="password" name="pwCheck" value={ this.state.pwCheck }
                onChange = { this.changeEvent.bind(this) } />

                <br />
                

                <InputLabel id="demo-simple-select-label">gender</InputLabel>
                <Select
                    labelId="demo-simple-select-label"
                    id="demo-simple-select"
                    value={this.state.gender}
                    onChange={this.handleChange}
                >
                    {genders.map((gender) => (
                        <MenuItem key={gender} value={gender}>
                            {gender}
                        </MenuItem>
                    ))}
                </Select>

                <br />
                photo : &nbsp;
                <input type="file" name="photo"
                onChange={this.imageUpload.bind(this)}
                ></input>

                <div>
                    <InputLabel id="demo-simple-select-label">photo</InputLabel>
                    <br />
                    <Upload 
                        batch={false}
                        multiple={true}
                        files={this.state.files}
                        onAdd={this.onAdd}
                        onRemove={this.onRemove}
                        onProgress={this.onProgress}
                        onStatusChange={this.onSatusChange}
                        withCredentials={false}
                        saveUrl={URL + '/member/upload'}
                        removeUrl={'https://demos.telerik.com/kendo-ui/service-v4/upload/remove'}
                        onChange={this.imageUpload.bind(this)}
                    />
                    <div className={'example-config'} style={{ marginTop: 20 }}>
                        <ul className={'event-log'}>
                            {
                                this.state.events.map(event => <li key={event}>{event}</li>)
                            }
                        </ul>
                    </div>
                    {
                        this.state.files.length ? 
                        <div className={'img-preview example-config'}>
                            <h3>photo previews</h3>
                            {
                                Object.keys(this.state.filePreviews)
                                    .map((fileKey, index) => (<img 
                                        src={this.state.filePreviews[fileKey]} 
                                        alt={index}
                                        style={{ width: 200, margin: 10 }} 
                                    />))
                            }
                        </div> : undefined
                    }
                </div>


                <br />
                

                <TextField id="standard-secondary" label="address" color="secondary" 
                type="text" name="address" value={ this.state.address }
                onChange = { this.changeEvent.bind(this) } />

                
                
                <TextField id="standard-secondary" label="addrdetail" color="secondary" 
                type="text" name="addrdetail" value={ this.state.addrdetail }
                onChange = { this.changeEvent.bind(this) } />

                <br />
                

                <TextField id="standard-secondary" label="phone" color="secondary" 
                type="text" name="hp" value={ this.state.hp }
                onChange = { this.changeEvent.bind(this) } />
                <br />
                
                <RippleBtn2 />
                </form>
            </div>
        );
    }

}

SignupPageComp.propTypes = {
    classes: PropTypes.object.isRequired,
};

export default withStyles(styles)(SignupPageComp);

**Comment by samaybhavsar** [comment]
@simonssspirit - The link https://stackblitz.com/edit/react-bvfjbb?file=app/main.jsx works well but it works for only single file. I tried changing and used promise all but does not seem to work as expect. Esp the upload progress is keep flickering. Can you we have an example where I can drag and drop multiple files ?

**Comment by samaybhavsar** [comment]
Here is the piece of code.

```
  const onSaveRequest = (files, options, onProgress) => {

        console.log(files)
        let promiseArray = []
        function processUpload(file) {
            let uid = file.uid
            let p = new Promise((resolve, reject) => {
                        onProgress(uid, {
                            loaded: progressRef.current[uid],
                            total: 100
                        })
                        if (progressRef.current[uid] === 100) {
                            resolve({ uid: uid })
                            delete progressRef.current[uid]
                        } else {
                            reject({ uid: uid })
                            progressRef.current[uid] =
                                progressRef.current[uid] + 1
                        }               
            })
            promiseArray.push(p)
        }
        files.forEach(processUpload)
        return Promise.all(promiseArray)
    }
```
