### ISSUE TITLE
MultiSelect onBlur dosen't fire if initially set to opened = true

### ISSUE THREAD

**Issue by shaibam** [telerik/kendo-react#194]
## I'm submitting a Bug
* When rendering a MultiSelect component and setting it's "opened" prop to true, the "onBlur" event will never be fired.

`   <div>
          <button className="k-button" onClick={this.handleOpen}>Open</button>
          <div>Favorite sports:</div>
          <MultiSelect
            data={sports}
            onChange={this.onChange}
            value={this.state.value}
            onOpen={this.handleOpen}
            opened={this.state.opened}
            onBlur={this.handleClose}
          />
        </div>
`

 Example at stackblitz:
https://stackblitz.com/edit/react-tdaasc-23sbhb?file=app/main.js

**Comment by nstoychev** [comment]
Fixed in 2.8.0-dev.201903081502 version. Please refer to the following article about obtaining the development builds - https://www.telerik.com/kendo-react-ui/components/installation/development-builds/.

**Comment by Xizario** [comment]
Fixed in `2.8.0`
