### ISSUE TITLE
[Grid] Filter icon

### ISSUE THREAD

**Issue by TDJ-Modality** [telerik/kendo-react#1953]
## I'm submitting a...
* Documentation issue or request

## The question
I have a question regarding the grid filter icon. I noticed that in the version 7.1.0 update, the k-more-vertical class name has been changed to k-i-filter. Why was this change made, and is there a possibility to modify this?

**Comment by Tommuh** [comment]
This is closed without answer, but is there a possibility to modify it?

**Comment by PekoPPT** [comment]
Hi, @Tommuh. 
We're sorry for not providing details about this issue. With our latest release from this week, the Filter and Column menu icons can be customized based on users' preferences. 

Here is a demo you can check: https://www.telerik.com/kendo-react-ui/components/grid/filtering/#toc-column-menu-filter

**Comment by Tommuh** [comment]
Very nice! Thank you.
