### ISSUE TITLE
Upload component conditional dropZoneHint

### ISSUE THREAD

**Issue by baranseldinc** [telerik/kendo-react#1956]
Hi, I would like to have [update](https://www.telerik.com/kendo-react-ui/components/upload/) component rendered dropzonehint text conditionally.
For instance, 

if multiple prop sets as true then text is rendered "Drag and drop files here to upload." which is plural
if multiple prop sets as false then text is rendered "Drag and drop file here to upload." which is singular

Actually this is not only about `<Upload />` component but also localization strucutre.
So I would like to hear that is it possible to make locales dynamic or any another workaround for this issue ?

## Current behavior
Just static definitions for locales

## Expected behavior
Dynamical locale definitions

Thanks for your attention.

**Comment by PekoPPT** [comment]
Hello, @baranseldinc.

Thank you for the shared details about the functionality you want to implement with the Upload component. 

[Here is a CodeSandbox example](https://codesandbox.io/p/sandbox/inspiring-darwin-67mzln?file=%2Fapp%2Fmain.tsx) demonstrating how the targeted functionality can be implemented. 

The above example defines two objects containing the language messages for the Singular and Plural messaging inside the Upload component. 

The following definition dynamically loads the component's messaging based on the value of the **multiple** prop:
```
<LocalizationProvider
  language={!multiple ? "en-US-singular" : "en-US-plural"}
>
.........
```

I've logged an internal issue about discussing the functioanlity of providing the discussed scenario internally for the component. Thank you for raising the discussion. 

Please let me know if you have questions related to the suggested solution.

**Comment by PekoPPT** [comment]
Closing the issue due to inactivity. If additional questions arise, please reopen the thread and continue the discussion.
