### ISSUE TITLE
[Bug][DropDownList] No Slide-up animation for the adaptive view (regression)

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1957]
## I'm submitting a...
* Regression report

## Current behavior
Only the slide-down animation on closing the adaptive view works. The slide-up animation on opening the adaptive view is missing.

## Expected behavior
Opening and closing the adaptive view should have animation (was working with version 7.0.1

## Minimal reproduction of the problem with instructions
Make the view small so the adaptive view can be shown:
https://stackblitz.com/edit/react-yyamyx-kn7u79?file=app%2Fmain.jsx

## Environment

Package versions:
7.1.0

**Comment by PekoPPT** [comment]
Hey, @kdikov82. We've tried to replicate the issue in this Vite-based runnable example - [vite-react-dropdownlist-animation.zip](https://github.com/telerik/kendo-react/files/15010119/vite-react-dropdownlist-animation.zip) but with no success. 

The reported behavior seems to be related to StackBlitz specifics or something else that we currently cannot reproduce. If you or someone else manages to replicate the issue with the animation in the linked example, please share with us more details and we will furhter investigate the case.
