### ISSUE TITLE
[DateTimePicker & TimePicker] Rendering mismatch for the "NOW" button (k-time-now)

### ISSUE THREAD

**Issue by NickIliev** [telerik/kendo-react#1958]
Describe the bug
The **DateTimePicker** and the **TimePicker*8 components in Kendo React have rendering differences compared to the source of truth tests in Kendo Themes. As a result, their "NOW" button uses flat-primary styles instead of flat-base styles.

To Reproduce

- Use the React Overview demos for **DateTImePicker** and **TimePicker** and observe the rendering for the "NOW" button
- Compare the rendering with the source of truth tests
https://github.com/telerik/kendo-themes/blob/develop/tests/datetimepicker/datetimepicker-adaptive.html#L326 (DateTImePicker)
https://github.com/telerik/kendo-themes/blob/develop/tests/datetimepicker/datetimepicker-opened.html#L530 (DateTImePicker)
https://github.com/telerik/kendo-themes/blob/develop/tests/timepicker/timepicker-adaptive.html#L65 (TimePicker)
https://github.com/telerik/kendo-themes/blob/develop/tests/timepicker/timepicker-opened.html#L47 (TimePicker)

**DateTimePicker** (uses flat-primary instead of flat-base)
![image](https://github.com/telerik/kendo-react/assets/18008302/53c5cbb8-ae06-414e-ad57-53a44441e1bd)

**TimePicker** (uses flat-primary instead of flat-base)
![image](https://github.com/telerik/kendo-react/assets/18008302/00a6fd99-a1f9-4a05-987b-a3d054430bb0)

Reported through t.1639915

**Comment by PekoPPT** [comment]
Hey, @NickIliev. 

Thank you for the shared details. We are currently in the process of unifying the rendering of all KendoReact components with the reference rendering in the https://github.com/telerik/kendo-themes repository. 

The issue you logged will surely be fixed in the next few weeks.

**Comment by PekoPPT** [comment]
Hey, @NickIliev. 
The rendering inconsistency is fixed. The fix is part of bigger rendering changes and will be released with our May release.
