### ISSUE TITLE
Popup position incorrect on mobile when child element uses translate from `react-localize-redux`

### ISSUE THREAD

**Issue by mokkymiah** [telerik/kendo-react#196]
## I'm submitting a...

* Bug report

## Current behavior

The `popup` component's position is incorrect on mobile only when the popup contains a child element that is using `react-localize-redux`.

Example, the following will position properly on mobile
```js
<Popup anchor={this.anchor} show={this.state.show}>
        <li>option 1</li>
        <li>option 2</li>
        <li>option 3</li>
        <li>option 4</li>
</Popup>
```

On screen:
![image](https://user-images.githubusercontent.com/12134052/53102494-b0ed9b00-3523-11e9-90dd-154ccfbc15a5.png)

However when using `Translate` in the above popup, the position is incorrect on mobile;

```js
  <Popup anchor={this.anchor} show={this.state.show}>
        <li>option 1</li>
        <li>option 2</li>
        <li>option 3</li>
        <li>option 4</li>
        <li>
          <Translate id="sample" />
        </li>
      </Popup>
```

on screen;
![image](https://user-images.githubusercontent.com/12134052/53102651-03c75280-3524-11e9-8ab8-10aa33406e66.png)

## Expected behavior

The calcution for `left` should match when not using translate. This issue only happens on mobile and doesn't seem to affect larger screens.

## Environment

Package versions:

```
  "react-localize-redux": "^3.5.1",
"@progress/kendo-data-query": "^1.5.0",
    "@progress/kendo-react-dateinputs": "^2.6.1",
    "@progress/kendo-react-dropdowns": "^2.6.1",
    "@progress/kendo-react-grid": "^2.6.1",
    "@progress/kendo-react-inputs": "^2.6.1",
    "@progress/kendo-react-intl": "^2.6.1",
    "@progress/kendo-react-popup": "^2.6.1",
    "@progress/kendo-theme-default": "^3.3.1"
```

Browser:

- Chrome (desktop) version 72.0.3626.10

System:
- TypeScript version: 3.1.6
- Node version: 11.7.0
- Platform:  Mac

**Comment by simonssspirit** [comment]
@mokkymiah apologies missing the reply to this. We can suggest submitting ticket trought the official support system for 24 hours guaranteed response. We are trying to respond here within 24 hours as well, but we somehow missed this one.

As we are not experts to react-localize-redux, could you please extend this example to reproduce the issue to ensure that we are testing the same case: https://stackblitz.com/edit/react-qmanjr?file=app/main.jsx

**Comment by vladimirivanoviliev** [comment]
I'm still not reproducing this issue with latest versions of all packages in the above demo, so I'm closing the issue.
- https://stackblitz.com/edit/react-qmanjr-kzoyfy?file=app/main.jsx
