### ISSUE TITLE
[Bug] KendoReact not compatible with NodeNext

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1962]
## I'm submitting a...

* Bug report

## Current behavior

Setting module and moduleResolution in tsconfig.json causes the following error when importing the components:

<img width="709" alt="MicrosoftTeams-image (6)" src="https://github.com/telerik/kendo-react/assets/108671796/46ebeb9f-8481-455f-9a18-21ce0f825916">

Currently, only the ES and CommonJS modules work with KendoReact.

## Expected behavior

KendoReact works with the NodeNext module.

## Minimal reproduction of the problem with instructions

1. Create a typescript React project
2. Navigate to `tsconfig.json`
3. Set the module and moduleResolution properties to `NodeNext`

Ticket ID: 1639099

**Comment by kspeyanski** [comment]
Fixed in the latest `dev` version of kendo-react.
