### ISSUE TITLE
[Bug][Checkbox] Wrong aria-checked

### ISSUE THREAD

**Issue by iadnonov** [telerik/kendo-react#1984]
## I'm submitting a...
* Bug report 

## Current behavior
CheckBox generate axe error with value={null} and `aria-checked="mixed"` 

## Expected behavior
CheckBox should not generate axe error with value={null} 

## Minimal reproduction of the problem with instructions
  1. Open the following link: https://www.telerik.com/kendo-react-ui/components/inputs/checkbox/
  2. Make axe DevTools test of the demo.

Ticket ID: 1640852

**Comment by silviyaboteva** [comment]
This pull request is included in version 8.2.0.
