### ISSUE TITLE
[Bug][MultiColumnComboBox] Filtering throws error when only one item is present

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1989]
## I'm submitting a...

* Bug report 

## Current behavior
If we have only one item in the MultiColumnComboBox and press the down arrow key the following error is thrown: `Cannot read properties of undefined (reading 'name')`

## Expected behavior
No error should be thrown and the item should be selected.

## Minimal reproduction of the problem with instructions
1. Open the following StackBlitz: https://stackblitz.com/edit/react-mlsru7-tppiem?file=app%2Fmain.tsx
2. Type vega, then press the down arrow key
3. Observe the thrown error

Reported in Ticket ID: 1641192

**Comment by zdravkov** [comment]
fixed in version 8.0.0 - https://stackblitz.com/edit/react-mlsru7-he3yqn?file=app%2Fmain.tsx
