### ISSUE TITLE
[Bug][Grid] GridColumnMenuWrapperProps does not fire onCloseMenu event

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1991]
## I'm submitting a...
* Bug report 

## Current behavior
Currently, it is not possible to handle the close event of the ColumnMenu of the Grid.

In the API for the GridColumnMenuWrapperProps we have onCloseMenu, but it is not used internally, thus does not fire when the menu closes:

- https://www.telerik.com/kendo-react-ui/components/grid/api/GridColumnMenuWrapperProps/#toc-onclosemenu

## Expected behavior
The onCloseMenu should fire and we should pass the original handler in the props as well

## Minimal reproduction of the problem with instructions
The following example demonstrates that it is not possible to handle the onCloseMenu event
https://stackblitz.com/edit/react-hcfgpn-punczt?file=app%2Fmain.jsx

Package versions:
7.1.0

**Comment by elena-gancheva** [comment]
The fix is available in the latest official version of the package.
