### ISSUE TITLE
Grid - Performance Issue with column resizing 

### ISSUE THREAD

**Issue by jannhofman** [telerik/kendo-react#20]
## I'm submitting a...

* Feature requests 

## Current behavior

The resizing Event is triggered multiple times. 

## Expected behavior

We would like to have some columnResized-event / columnResizeEnd-Event. Similar to columnResize-event, but it should only to be triggered once at the end of the resize process (Handle drop). The current implementation of columnResize-event triggers multiple times during the actual resize process.

**Comment by Xizario** [comment]
Thank you for the idea, I will add it.

**Comment by Xizario** [comment]
We have added `end` bool parameter into the `columnResize` event, which indicates if the user is dropped the handler.

It will be available in the `0.6.0` version. Currently usable in the latest dev version `0.6.0-dev.201805081109`. Can be tested here: [https://stackblitz.com/edit/kendo-grid-sync](https://stackblitz.com/edit/kendo-grid-sync)

**Comment by Xizario** [comment]
Version [0.6.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/) is live
