### ISSUE TITLE
IE related issue with getComputedStyle

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-react#200]
In IE and Edge `getComputedStyle` can return `null` or `undefined` without actual reason, looks like browser bug. Anyway we should double check before trying to access `getComputedStyle(element).direction`

**Comment by Xizario** [comment]
@simonssspirit Did we received new reports for this? If not I will close it, since it was never reproduced locally after the initial report,

**Comment by simonssspirit** [comment]
There are no new reports for this.

If we have any, we will link them.

**Comment by Xizario** [comment]
If we ever get new reports, we will reopen this
