### ISSUE TITLE
[Bug][Grid] When searching a column name in Safari, the header and body is misaligned

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#2020]
## I'm submitting a...

* Bug report 

## Current behavior
In Safari when searching a column name via CMD + F  sometimes the header and body are misaligned. This occurs from time to time and it is not always reproducible.

## Expected behavior
When searching for a column name there should not be misaligned.

## Minimal reproduction of the problem with instructions
1. Open the following stackblitz in Safari: https://stackblitz.com/edit/react-yujam2?file=app%2Fmain.tsx
2. Search for some columns using CMD + F and after a while you will observe the following misalignment:

![image](https://github.com/telerik/kendo-react/assets/92358162/58943f16-934e-4000-a54d-67d67ac28f9b)

## What is the motivation or use case for changing the behavior?

Reported in Ticket ID: 1641471

**Comment by iadnonov** [comment]
Fixed in dev version [v7.2.4-develop.1](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#v7.2.4-develop.1)
