### ISSUE TITLE
minResizableWidth is not applied if resizing the browser initially

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-react#203]
## Description
- Scenario 1 - In Grid when the user resizes the window the columns become very small
- Scenario 2 - If  the user resizes a column and then resizes the window, the widths are preserved and we have a horizontal scroll.
- Behavior is inconsistent between scenario 1 and 2
- Behavior is not related to minResizableWidth prop

## Resources
https://www.screencast.com/t/j9mrXBnvfjFn
https://stackblitz.com/edit/react-duhj9f?file=app%2Fmain.js

## Current behavior - Scenario 1

1 - open your  stackblitz
2 - make the html page inside the stackblitz smaller
3 - the columns are super small

## Current behavior - Scenario 2
1 - open your  stackblitz
2 - resize one of the grid columns (as done in the video)
3 - resize the window again
4 - all the columns are rendered as expected persisting their width in a small screen with a horizontal scroll

## Expected behavior
1 - open your last stackblitz
2 - make the html page inside the stackblitz smaller
3 - all the columns are rendered as expected persisting their width in a small screen with a horizontal scroll

**Comment by Xizario** [comment]
@zdravkov,

I think it works as expected and documented. 

https://www.telerik.com/kendo-react-ui/components/grid/api/GridColumnProps/#toc-minresizablewidth
> minResizableWidth? number
The width of the column (in pixels) below which the user is not able to resize the column through the UI. Defaults to 10.

**Comment by zdravkov** [comment]
Thanks @Xizario ,

Yes indeed - minResizableWidth is working correctly - its rather the scenario itself here that is a bit inconsistent - initially when we resize the browser the columns are splashed and if we resize a single column and then we decrease the width of the browser the columns preserve their width.  If we don't want to hard code a particular initial width do we have a recommended setting or solution that I am missing?

**Comment by Xizario** [comment]
Setting min-width to the table could be some solution if you don't want to set widths based on the free space for the grid.
pseudoCss:
`table { min-width: SumForEachColumn(min(minWidth, width)) }` 
But it will come with some limitations later on resizing: making some column bigger can result in other columns becoming smaller, instead of the whole table to grow.

I am open for ideas, it is more or less something that impacts all kendo suites, since the rendering and themes are similar.

**Comment by shekerev-progress** [comment]
Hey, guys

In addition to above, we have 2 feature requests:
- https://feedback.telerik.com/kendo-react-ui/1360879-react-grid-needs-to-support-minscreenwidth
- https://feedback.telerik.com/kendo-react-ui/1360888-kendo-ui-react-gridcolumn-component-needs-minwidth-and-maxwidth-properties

This is still under consideration but one possible approach is to rely on the suggestions of the above requests.
