### ISSUE TITLE
Table insert and editing tools

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-react#204]
- [x] Create table tool similar to `Create a table` of [Kendo UI Editor](https://demos.telerik.com/kendo-ui/editor/all-tools) but without TableWizard dialog.
- [x] Table editing tools using the commands of [prosemirror-tables](https://github.com/ProseMirror/prosemirror-tables) package.
- [x] Update tools article

**Comment by nstoychev** [comment]
Implemented in 2.8.0-dev.201903131319 version.

Example containing table tools - https://www.telerik.com/kendo-react-ui-develop/components/editor/tools/

**Comment by Xizario** [comment]
Fixed in `2.8.0`
