### ISSUE TITLE
Datepicker missing translation

### ISSUE THREAD

**Issue by Tommuh** [telerik/kendo-react#2053]
Datepicker missing translation of the "today" button.
All other values are translated.

DE
![image](https://github.com/telerik/kendo-react/assets/2089879/e3722039-ed3e-44d0-bd29-e782831758a5)

NL
![image](https://github.com/telerik/kendo-react/assets/2089879/15ddc3a2-abc5-4f34-9f74-01607bae04f6)

Did not test with other languages.

**Comment by iadnonov** [comment]
Hey @Tommuh ,

This appears to be a bug. Thank you for reporting it and please excuse us for the inconvenience caused. Our team will fix it as soon as possible. 

If you have any other questions, please don't hesitate to submit a ticket in [our support system](https://www.telerik.com/account/support-center).

Greetings,
Ivaylo

**Comment by Tommuh** [comment]
Any ETA on this? It seems like a small fix.

**Comment by Tommuh** [comment]
@iadnonov do you know when this is getting fixed?

**Comment by iadnonov** [comment]
Hi, @Tommuh. This bug is no longer reproducible with our latest version of the package [v8.5.0](https://github.com/telerik/kendo-react-private/releases/tag/v8.5.0)

The following example illustrates a working configuration of the component.: https://stackblitz.com/edit/react-tvt76x?file=app%2Fapp.tsx

**Comment by Tommuh** [comment]
No it is not. I though using "loadMessages" was not mandatory?
Because everything gets translated without "loadMessages" except that one word.

https://react-tvt76x-daahx8.stackblitz.io

![image](https://github.com/user-attachments/assets/496f4517-764a-4352-9466-208d0c978abd)

**Comment by iadnonov** [comment]
For date/time related translations, we use https://www.npmjs.com/package/cldr-dates-full. However, they do not provide translations for the term `Today`, so we need to use an additional source by loading it with `loadMessages()`.

**Comment by Tommuh** [comment]
Ah ok - understandable, I did not know that. Thank you for your time.
