### ISSUE TITLE
add demo showing how to customize the rendering

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-react#207]

**Comment by nstoychev** [comment]
Added in version [2.9.0-dev.201904011527](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#toc-290-dev201904011527).

Here is the demo: https://www.telerik.com/kendo-react-ui-develop/components/editor/custom-rendering

**Comment by simonssspirit** [comment]
The demo with Material UI integration is also live: https://www.telerik.com/kendo-react-ui-develop/components/integration/material-ui/#toc-editor-integration
