### ISSUE TITLE
Grid: Date Filtering Options buggy

### ISSUE THREAD

**Issue by jannhofman** [telerik/kendo-react#21]
## I'm submitting a...

* Bug report 

## Current behavior

When filtering a Date the options "is before" & "is before or egual to" are switched in their outcome.

![telerik_datefilter](https://user-images.githubusercontent.com/37375676/39522689-851c7fe0-4e02-11e8-90d7-40fc15a609dc.PNG)

## Environment

Version 0.5.0

**Comment by Xizario** [comment]
Fixed in version [0.6.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/)
