### ISSUE TITLE
ReactJs grid has no footer .Is there any solution for it? (for example client sum template)

### ISSUE THREAD

**Issue by mdeirdar** [telerik/kendo-react#213]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by simonssspirit** [comment]
@mdeirdar we have the following discussion for this:

https://github.com/telerik/kendo-react/issues/47
