### ISSUE TITLE
Multiselect popup list item keeps focused state

### ISSUE THREAD

**Issue by Nodios** [telerik/kendo-react#214]
## I'm submitting a...
* Bug report 

## Current behavior
Last selected item in the multiselect keeps focused state in the item popup list after the list has been closed. 

## Expected behavior

There should be no focused items when opening item list.

## Minimal reproduction of the problem with instructions
Can be seen on [basic](https://www.telerik.com/kendo-react-ui/components/dropdowns/multiselect/) multiselect example on your site.

**Comment by nstoychev** [comment]
@Nodios - While researching the issue, I have found out that there is a simple workaround for the case when virtual scrolling is not used, just two lines of code https://stackblitz.com/edit/react-x6a2lz?file=app/main.jsx.

Hopefully you can use it.

**Comment by kdikov82** [comment]
The focused index is kept in the state, so that if the popup is opened again, the navigation will continue from the same place. 
Closing due to existing solution for resetting the index.
