### ISSUE TITLE
[Bug][Grid] Removing the grouping of locked columns shows content on the background when scrolling 

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#2141]
## I'm submitting a...

* Bug report 

## Current behavior
Removing the grouping of locked columns shows content on the background when scrolling. the bug is introduced in v5.17.0 of the components - [working](https://stackblitz.com/edit/react-syfjwj-cbuyp1?file=app%2Fmain.tsx,package.json,index.html) (5.16.0), [not working](https://stackblitz.com/edit/react-syfjwj-ucbkkb?file=package.json) (5.17.0).

Video: https://somup.com/cZeto6C01n 

## Expected behavior
The space previously taken by the expand column should not be transperant.

## Minimal reproduction of the problem with instructions

  1. Open: https://stackblitz.com/edit/react-syfjwj-axcvnv?file=app%2Fmain.tsx
  2. Remove the grouping column from the toolbar
  3. Scroll the Grid horizontally.

## Additional details

Reported in Ticket ID: 1646451

**Comment by zdravkov** [comment]
Fixed in the latest dev version of KendoReact - https://stackblitz.com/edit/react-syfjwj-8u6nzw?file=package.json. Will be included in the next official release.
