### ISSUE TITLE
[Bug][Grid] Only the first expand column is locked when scrolling a grid with multi columns grouping

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#2142]
## I'm submitting a...

* Bug report 

## Current behavior
Only the first expand column is locked when scrolling a grid with multi columns grouping, even if more than one columns are locked - [working](https://stackblitz.com/edit/react-syfjwj-oopf7g?file=package.json) (5.16.0), [not working](https://stackblitz.com/edit/react-syfjwj-oopf7g?file=package.json) (5.17.0).

Video: https://somup.com/cZetozC0jM 

## Expected behavior
Both expand columns has to be locked.

## Minimal reproduction of the problem with instructions

  1. Open: https://stackblitz.com/edit/react-syfjwj-ocwald?file=package.json
  2. Add one more column to the grouping toolbar
  3. Scroll the Grid horizontally.

## Additional details

Reported in Ticket ID: 1646451

**Comment by zdravkov** [comment]
Fixed in the latest dev version of KendoReact - https://stackblitz.com/edit/react-syfjwj-5wazhv?file=package.json. Will be included in the next official release.
