### ISSUE TITLE
[Bug][Grid] With horizontal scrollbar, adding filter expression that returns no items makes it impossible to scroll to the hidden columns

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#2143]
## I'm submitting a...
* Bug report 

## Current behavior
If you have a Grid with a horizontal scrollbar and columns that are not visible unless you scroll, if the Grid is filter so it returns no data, the scrollbar disappears and it is impossible to go all columns (and clear the filter)

## Expected behavior
The horizontal scrollbar should remain even with no data

## Minimal reproduction of the problem with instructions
Open the following example:
https://stackblitz.com/edit/react-tesdni?file=app%2Fmain.jsx

Scroll to the last column (UnitPrice) and enter 1 in the filter
The Grid will remove the scrollbar.

Package versions:
7.3.0

**Comment by iadnonov** [comment]
Fixed in dev version 7.4.0-develop.12.
