### ISSUE TITLE
Incorrect rendering for Breadcrumb root item

### ISSUE THREAD

**Issue by kvelikov** [telerik/kendo-react#2146]
The Breadcrumb root item has inconsistent rendering with the specified in the kendo-themes repo.
![image](https://github.com/telerik/kendo-react/assets/5024892/338452c9-b8c3-4905-a843-03b0fa2b4411)
![image](https://github.com/telerik/kendo-react/assets/5024892/f8a20312-0a57-4ac4-b488-90fe2ef465c7)

It seems that by specification the class should be k-breadcrumb-container. Currently it is k-breadcrumb-root-item-container

Version: Q1, 2024

**Comment by PekoPPT** [comment]
Hey, @kvelikov. 

The KendoReact Bradcrumb works in 'wrap' mode only and according to the [reference rendering](https://github.com/telerik/kendo-themes/blob/21de9a744378113e5c7b4cfd5d303a921298aa45/tests/breadcrumb/breadcrumb.html#L160-L174), the discussed class should be there. 

In addition to the above, the [rendering test for the Breadcrumb's wrap mode](https://github.com/telerik/kendo-themes/blob/develop/packages/html/src/breadcrumb/templates/breadcrumb-collapsing-wrap.tsx) is the only place where the [BreadcrumbRootItemContainer](BreadcrumbRootItemContainer) is used.

The same class is also available in the Angular suite and can be tested in [this demo](https://www.telerik.com/kendo-angular-ui/components/navigation/breadcrumb/collapse-modes/). 

Based on the above details, I would say that the Breadcrumb rendering is correct in the context of KendoReact. Of course, if you think, no matter the above, we should apply some changes, we will be happy to continue the discussion.
