### ISSUE TITLE
DropdownTree with always `200px`

### ISSUE THREAD

**Issue by zoran995** [telerik/kendo-react#2159]
## I'm submitting a...
* Regression report 
* Bug report 

## Current behavior
When adding a dropdown tree the dropdown won't fill the width of the available container but will take a width of `200px` as it is defined in the `defaultProps` for the kendo dropdown tree. This only occurs if we don't set the `width` on  
<img width="349" alt="image" src="https://github.com/telerik/kendo-react/assets/19208948/b73e039d-1d5d-4966-8b0b-862c56d1a6ab">

## Expected behavior
The dropdown tree should fill the available width (same as input).
<img width="358" alt="image" src="https://github.com/telerik/kendo-react/assets/19208948/694ca7d3-ef80-41dc-9f7f-d572d721fb0d">

## Minimal reproduction of the problem with instructions
1. Open the https://stackblitz.com/edit/react-amvz3h?file=app%2Fmain.tsx
2. open the dropdown tree
3. observe tree doesn't take the same width as input
The same can be noticed on the adaptive rendering demo https://www.telerik.com/kendo-react-ui/components/dropdowns/dropdowntree/adaptive-rendering/

## Analysis 
It worked correctly in v7.2.3
After debugging and looking in the kendo dropdown tree source code I noticed that the issue is coming from bad comparison code in `useDropdownWidth` hook. It will compare the computed width of input and `defaultProps.popupSettings.width`. The computed width is `number` and the value in default props is "200px".

**Comment by PekoPPT** [comment]
Hi, @zoran995. 

Thank you for reporting the issue with the DropDownTree's popup and also for the analysis. The bug fix is already planned and will be fixed next week.

**Comment by PekoPPT** [comment]
Hi, @zoran995.
The bug is fixed and the fix can be tested in [this StackBlitz example](https://stackblitz.com/edit/react-amvz3h-gjrtu8?file=package.json,app%2Fmain.tsx) that uses version [7.5.0-develop.5](https://www.npmjs.com/package/@progress/kendo-react-common/v/7.5.0-develop.5) our the KendoReact components.

**Comment by zoran995** [comment]
Thanks for the heads up. When can we expect the 7.5.0 to be released with general availability? Also, I noticed that there is still no documentation in the changelog for 7.4.0 and it is already available on npm for 7+ days
