### ISSUE TITLE
Kendo React Menu: Sub menus <MenuItem> URL, not clickable in IE (not redirecting), However works fine in chrome

### ISSUE THREAD

**Issue by LetMeTryItOut** [telerik/kendo-react#216]
## I'm submitting a...

Issue regarding Kendo React Menu
Please follow the link for reference:
https://www.telerik.com/kendo-react-ui/components/layout/menu/items/properties/#toc-url

Here, the item1.1 is not working in IE, however works fine in chrome.

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Current behavior

The current behaviour of Kendo Menu > sub menu with url navigation works only in chrome, not in IE.
Is there any specific version of IE, in which it works.

## Expected behavior

The link should be clickable, it is working only in Chrome but in IE edge, IE 10 it is not navigating to another page
## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version 71.0.3578.98
- IE version Edge, 10

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by asen-arizanov** [comment]
Thank you for reporting the bug. The specified URL navigation does not work in IE and we have started working on it. However, it works in Edge on my side. If Edge is problematic could you please specify your Edge version?

**Comment by LetMeTryItOut** [comment]
Hi,

Sorry for the confusion, by Edge I am referring to Edge mode in Internet explorer.
Also, it will be really helpful if you can let us know by when this issue will be fixed?

**Comment by asen-arizanov** [comment]
Hi again,

The fix should be ready in a week or two.

**Comment by LetMeTryItOut** [comment]
Thanks.
