### ISSUE TITLE
[Bug][DatePicker] Setting the "valid" property throws a warning message in the console

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#2188]
## I'm submitting a...
* Bug report 

## Current behavior
Setting the "valid" property throws a warning message in the console:
```
preview-afd2289b8907a.js:2 Warning: Received `false` for a non-boolean attribute `valid`.
If you want to write it to the DOM, pass a string instead: valid="false" or valid={value.toString()}.
If you used to conditionally omit it with valid={condition && value}, pass valid={condition ? value : undefined} instead.
```

## Minimal reproduction of the problem with instructions
Open the browser console and run the example:
https://stackblitz.com/edit/react-4a39ds?file=app%2Fmain.jsx

Version:
7.4.0

**Comment by WissamProgress** [comment]
Also reported in Ticket ID: 1650835

**Comment by bdbvb** [comment]
I'm still seeing this issue with Kendo React version 8.

**Comment by WissamProgress** [comment]
Hi @bdbvb 

This should not happen with the 8th version of KendoReact. I also tested it and the warning was not present:

- https://stackblitz.com/edit/react-4a39ds-qohxj9?file=app%2Fmain.jsx,package.json

Therefore, can you please send us an example where the warning is present with version 8?
