### ISSUE TITLE
Editor toolbar buttons are submit type buttons

### ISSUE THREAD

**Issue by johnpreed** [telerik/kendo-react#219]
## I'm submitting a...
* Bug report

## Current behavior
Clicking any button in the toolbar renders as a submit type button instead of a button, which causes the form to be submitted if your editor is inside of an html form.

## Expected behavior
Toolbar buttons should be rendered as a "button" type button.  Clicking a toolbar button should not cause a form submission or trigger validation.

## Minimal reproduction of the problem with instructions
  1. Add an Editor component as a child of an html form.
  2. Define at least 1 button for the toolbar: bold/italic/underline.
  3. Launch a browser and navigate to your form with the Editor.
  4. Click one of the buttons in the toolbar: bold, italic, or underline.
  5. Inspect one of the toolbar buttons and note that it renders as a button without an attribute type="button".
  6. Note that clicking the button will result in a form submission.

## What is the motivation or use case for changing the behavior?
Editors will most likely be a child of a Form component. Toolbar buttons submitting the form is a critical bug.

## Environment
Browser:
- Chrome (desktop) version 72.0.3626.121

System:
- TypeScript version: 2.9.1
- Node version: 8.9.4
- Platform:  Mac

**Comment by simonssspirit** [comment]
As a current workaround, a HOC can be used to add additional attributes to the Tools:

https://stackblitz.com/edit/react-kmths6-ek3pos?file=app/main.js

**Comment by Xizario** [comment]
Fixed in `2.8.0`
