### ISSUE TITLE
How a user can open a link inserted in <Editor /> component

### ISSUE THREAD

**Issue by baranseldinc** [telerik/kendo-react#2194]
Hi,

The question is quite simple, I am looking for the way how a user can open a link just by clicking ?

Thanks for your attention.

**Comment by silviyaboteva** [comment]
Hello @baranseldinc,

Thanks for the question. Our [KendoReact Editor](https://www.telerik.com/kendo-react-ui/components/editor/) component implements both `click` and the combination `Ctrl + click` (`Command + click` on Mac) for different operations, such as: 
 - Upon click, the cursor moves to the target place in the text, so the user can edit from there. In case, there is a inserted link, it will allow you to edit the text. 
 - Another command is `Ctrl + click` which by default, selects the text.

So, if you want to open the link, you can use the `right click` and _'Open Link in New Tab'_ or _'Open Link in New Window'._
