### ISSUE TITLE
[Bug][DatePicker] Warnings for the adaptive and adaptiveTitle properties

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#2195]
## I'm submitting a...

* Regression report 

## Current behavior
Setting the adaptive and adaptiveTitle props shows the following warnings in version 7.4.0:

```
react-dom.development.js:86 Warning: Received `true` for a non-boolean attribute `adaptive`.
```
```
react-dom.development.js:86 Warning: React does not recognize the `adaptiveTitle` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `adaptivetitle` instead.
```
Nevertheless, these props work as expected.
These warnings are not present in previous versions.

## Expected behavior
No warnings shown.

## Minimal reproduction of the problem with instructions
Set the adaptive and adaptiveTitle props - https://stackblitz.com/edit/react-et5axw?file=app%2Fmain.tsx

Ticket ID: 1649163

**Comment by kdikov82** [comment]
Seems related in a way with this: https://github.com/telerik/kendo-react/issues/2188
