### ISSUE TITLE
[Bug][Chart] Chart is broken for numbers with a lot of symbols after point

### ISSUE THREAD

**Issue by russyDev** [telerik/kendo-react#2198]
I encountered an issue with the Kendo Chart when using values with many decimal places; I received a NaN error. Here's an example: https://stackblitz.com/edit/react-szsprm-wmbfmy?file=app%2Fmain.tsx . However, if there are more than two values and one of them is 1, everything works without any issues.

**Comment by PekoPPT** [comment]
Hi, @russyDev.
Thank you for the shared details and example. After investigating the case, what we can share about it is that the reported behavior is triggered by the limitation of the number format in JavaScript. 

What I mean here is that the minimum value that the number format can handle is **2e-1022**. This number, written in decimal notation looks like this:
![image](https://github.com/telerik/kendo-react/assets/41293735/ae402970-48ea-41bc-bd3e-6e83c5ccafec)
The above number has 10 digits after the decimal number. 

The value of the number in your example looks like this in decimal notation:
![image](https://github.com/telerik/kendo-react/assets/41293735/e4c3cfd3-b52d-4097-b7ec-e0956b1141cb)

The resulting number is outside the range of the **number** type.
In addition to the above, if we change **4.10874935795417321312312e-12** to **4.10874935795417321312312e-10** the Chart is working properly as can be seen in [this StackBlitz example](https://stackblitz.com/edit/react-szsprm-7kxepb?file=app%2Fmain.tsx). 

If we take the 4.10874935795417321312312e-10 value here is how it looks in decimal notation:
![image](https://github.com/telerik/kendo-react/assets/41293735/75c52869-21b4-441c-a5b8-b21e6969a0bf)
Here the first digit different from 0 is 4, and it is located in the 10th position after the decimal point, which is also the last meaningful digit for the small values of the number type. 

As the reported behavior is a limitation of the number format, I am afraid that we cannot provide a workaround that will make the Chart work as expected when having such small values. 

If the value precision is not that important in your scenario, you can think about a custom logic that will handle the values that are smaller than the minimum value the number type can handle. If precision is important in your scenario, the only thing I can suggest to you is to submit a [feature request](https://feedback.telerik.com/kendo-react-ui) about the discussed functioanlity.

**Comment by russyDev** [comment]
Hey @PekoPPT Thx for your response. As I understand it, there is no workaround for fixing this issue, but why does this work in this example?

https://stackblitz.com/edit/react-szsprm-vkjf4m?file=app%2Fmain.tsx

**Comment by russyDev** [comment]
Hey @PekoPPT Thx a lot for your response. That helped me to solve my issue.
