### ISSUE TITLE
Combobox will not lose focus when the suggestion option is set only (IE11)

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#22]
## I'm submitting a

* Bug report 

## Current behavior

Combobox will not lose focus when the suggestion option is set.

## Minimal reproduction of the problem with instructions

The issue can be observed in the demo https://www.telerik.com/kendo-react-ui/components/dropdowns/combobox/suggestions/

Click in the input and then click on the search bar:

![image](https://user-images.githubusercontent.com/11087921/39525262-2cb164d4-4e24-11e8-9c98-13864e7275d2.png)

## Environment

Browser:
- IE version 11

**Comment by Xizario** [comment]
Happens only when `placeholder` is defined. Workaround for now is simply not setting a placeholder.

**Comment by nstoychev** [comment]
Fixed in `v1.0.1-dev.201805290749`.
Please refer to the [this article](https://www.telerik.com/kendo-react-ui/components/installation/development-builds/) on how to obtain the development builds.

**Comment by mitagg** [comment]
The fix is available in the v1.0.1 of the package
