### ISSUE TITLE
Grid filter menu not closing (bug?)

### ISSUE THREAD

**Issue by Tommuh** [telerik/kendo-react#2215]
Version 7.4.

Grid filter menu not closing when clicking outside of the menu. The menu only closes with the clear/filter button.
Below an example of what previously was not possible:

![image](https://github.com/telerik/kendo-react/assets/2089879/72123eb3-6393-4986-84a2-54c9a8a100c3)

**Comment by PekoPPT** [comment]
Hey, @Tommuh. 
Thank you for the shared details. I've tried to replicate the reported behavior in [this StackBlitz example](https://stackblitz.com/edit/react-ozgnx5?file=app%2Fmain.jsx) but with no success. 

The shared example uses KendoReact 7.4.0 and version 7.2.1 of the KendoThemes. Can you please check the provided example and let me know if you are able to replicate the reported issue in it? If you can reproduce the issue, please share with us the step-by-step instructions we should follow to replicate the unexpected behavior.

If you are not able to replicate the reported behavior, here is what I can suggest:
1. Compare the implementation of the shared example with the implementation in the application you are working on. You may notice something that should be configured in different way.
2. If the above suggestion doesn't work, to be able to help you with the case, we will need a runnable example in which it can be tested. Can you use the shared above example as a basis and edit it in a way the issue you experience can be replicated in the StackBlitz project? When you are ready with the editing, send us the edited project back and we will be happy to help you furhter.

**Comment by Tommuh** [comment]
Hi @PekoPPT ,

Thank you for your reply. I used your info to debug mine. It is a bug I introduced myself 🤣 

I found the problem, in my CSS I do the following to hide "Filter".

This is for some reason also responsible for closing on outside click. It is probably used to attach an event to this element. 
This may have been different in previous versions.

```
.k-grid-columnmenu-popup .k-columnmenu-item {
    display: none;
}
```

![image](https://github.com/telerik/kendo-react/assets/2089879/24785af6-2758-4ec5-9e91-47b8368ac1b8)

Any ideas on how I can hide this?

**Comment by PekoPPT** [comment]
Hi, @Tommuh. 
The reason why the popup functionality breaks is that by hiding the highlighted element, we hide the focused element in the column menu.

The simplest solution I can suggest is a CSS definition like this:
```
.k-grid-columnmenu-popup > div > div > div > .k-columnmenu-item {
  font-size: 0px;
  padding: 0px;
}

.k-columnmenu-item * {
  height: 0px;
}
```

The above possible approach is demonstrated in [this StackBlitz example](https://stackblitz.com/edit/react-ozgnx5-8ozj9b?file=app%2Fstyle.css,app%2Fmain.jsx).  I hope it will help you achieve what you need :)

**Comment by Tommuh** [comment]
Thank you for your quick response and help.
I tried your CSS,  I had to remove one "div" to get it working.

```
.k-grid-columnmenu-popup > div> div > .k-columnmenu-item {
  font-size: 0px;
  padding: 0px;
}

.k-columnmenu-item * {
  height: 0px;
}
```
