### ISSUE TITLE
Calendar - append to body

### ISSUE THREAD

**Issue by TDJ-Modality** [telerik/kendo-react#2218]
## I'm submitting a...

* Question

## Current behavior
I'm trying to append the Calendar component to the body so that it no longer remains inline but rather centralized. However, I'm encountering the error ```Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.``` Is there a way to append it elsewhere using a different method?
```javascript
useEffect(() => {
	if(calendar) {
		const element = document.getElementById('calendar');
		
		if(element) {
			document.body.appendChild(element);
		}
		
		return () => {
			if(document.body.contains(element)) {
				document.body.removeChild(element);
			}
		};
	}
}, [calendar]);
```
Browser:
- Chrome (desktop) 

System:
- Platform:  Windows

**Comment by PaskalevStoyan** [comment]
Hi @TDJ-Modality 

This repository is exclusively dedicated to addressing bugs, handling feature requests, and discussing product enhancements. If you need help with setting up a specific scenario or configuring a KendoReact component, please don't hesitate to open a ticket in our [support system](https://www.telerik.com/account/support-tickets).
