### ISSUE TITLE
Edge left property calculation issue 

### ISSUE THREAD

**Issue by niyazhussain** [telerik/kendo-react#222]
**Microsoft EdgeHTML 18.17763
Microsoft Edge 44.17763.1.0**

Stretches to the whole screen , the left and right position set to 0

![image](https://user-images.githubusercontent.com/12608545/54846685-6e75d480-4d02-11e9-9850-48002dbd43ac.png)

**Chrome (It works fine)**

![image](https://user-images.githubusercontent.com/12608545/54846668-674ec680-4d02-11e9-8686-923222b8f70a.png)

**Comment by kspeyanski** [comment]
Hello @niyazhussain ,

Thank you for reporting this.
I couldn't reproduce it on version **42.17134.1.0** of Edge, so i will follow up once i setup the mentioned version above.

Gretings,
Kiri

**Comment by kspeyanski** [comment]
It seems to be a strange bug with Edge not calculating the width of a display-flex element correctly. 
Even stranger is the fact that after applying _any_ style property to the `k-calendar-weekdays` element, and then remove it (though the Edge DevTools) the width is calculated properly.

Anyway, i suggest adding the following CSS rule to avoid problems with the Calendar width
```css
.k-calendar-infinite .k-calendar-weekdays { display: flex; }
```

Please let me know if you need further assistance!

**Comment by niyaza3** [comment]
@kspeyanski  the design in chrome gets collapsed with the above solution 
![Untitled](https://user-images.githubusercontent.com/48091946/54899699-ae051200-4ef6-11e9-9d86-534d4188f108.png)

**Comment by kspeyanski** [comment]
Will be taking a look ASAP

**Comment by kspeyanski** [comment]
Hello @niyaza3,
Please excuse me for taking so long to respond!

After trying a whole bunch of things, i have found that the following css rule resolve the issue:
```css
.k-calendar-infinite .k-calendar-weekdays {
    table-layout: auto;
}
```

Please let me know if this solution works for you, and once again, sorry for taking so long to respond!

**Comment by niyaza3** [comment]
@kspeyanski Still noluck
![Untitled](https://user-images.githubusercontent.com/48091946/55673528-bed66000-58c6-11e9-800f-f633b7e9dcc0.png)

**Comment by kspeyanski** [comment]
@niyaza3 Is it possible for you to send the SASS/CSS file so i can inspect further?

Otherwise, can you try to change your css rule from:
```css
table-layout: auto !important: ;
```

to:
```css
table-layout: auto !important;
```

I'm seeing an excessive ':' symbol in the screenshot you sent.

**Comment by niyaza3** [comment]
@kspeyanski Thanks mate , that : at the end caused the problem. It works
