### ISSUE TITLE
Docs Improvement: Retaining Sort & Look and Feel on custom HeaderCell in Grid

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#223]
## I'm submitting a...
* Documentation suggestion

## Current behavior
When searching how to retain the ability to Sort a grid when customising the headerCell, after lots and lots of searching I eventually found out how to do it in the **Tooltip** docs here: https://www.telerik.com/kendo-react-ui/components/tooltip/how-to/tooltip-in-grid/

 I am just lucky it happens to show an example of how to retain the sort functionality and look and feel of the headercell.  I feel like this information would be valuable to include in the customHeaderCell docs. 

I then slighty modified the example to not include the tooltips, implement all the sorting, and to have the anchor tag have href="#" so that you can still see that it is a clickable link. See my example here: 
https://stackblitz.com/edit/react-4yvdr4?file=app/main.jsx

## Suggestion: 
Include the above example, or similar, in the headerCell customisation docs/example here: https://www.telerik.com/kendo-react-ui/components/grid/api/GridHeaderCell

Alternatively maybe it is suitable in the Sort docs? 
 Its a bit difficult to decide where to put the example because it relates to both Cell Customisation  and Sorting

**Comment by simonssspirit** [comment]
@k290  Thank you for the feedback. This is added to the Styling section of the Grid, so it is easier to find:
https://www.telerik.com/kendo-react-ui/components/grid/styling/

**Comment by k290** [comment]
Looks like there's a regression in Kendo React 2.10 where the k-link class isn't working or the onclick isn't firing. Affects your styling example and the tooltip one in the first post in this issue. Haven't created a separate issue yet.

**Comment by simonssspirit** [comment]
@k290 The click should be working as expected. Please have in mind that the examples in question do not have sorting enabled. They only show the custom rendering, adding sorting to them fires the onSortChange event as expected: https://stackblitz.com/edit/react-kxgvfj?file=app/main.jsx

**Comment by k290** [comment]
Oh yes of course. Sorry that's right
