### ISSUE TITLE
Upload component not displaying correct progress for multiple files when using React 18 with createRoot

### ISSUE THREAD

**Issue by khanamiryan** [telerik/kendo-react#2238]
**Description:**
**Issue Summary:**
When utilizing React 18 with the `createRoot` API,  instead of the deprecated `ReactDOM.render`, the Upload component shows inconsistent behavior, when uploading multiple files. The file list does not accurately reflect the progress of each item, resulting in some files appearing as uploaded while others remain stuck.

**Steps to Reproduce:**
1. Use React 18 with the `createRoot` API for rendering.
2. Integrate the Upload component.
3. Attempt to upload multiple files simultaneously.

**Expected Behavior:**
The Upload component should display an accurate progress indicator for each uploaded file, reflecting the status of each item as it is being processed.

**Actual Behavior:**
When uploading multiple files, the Upload component fails to display the correct progress for each file. Some files may correctly show as uploaded, while others remain stuck or display inaccurate progress information.

[Stackblitz](https://stackblitz.com/edit/vitejs-vite-nqvpqg?file=src%2FApp.tsx)

![image](https://github.com/telerik/kendo-react/assets/6542341/ff29e34b-01d6-4771-86de-c30e0b9ef3d9)

**Comment by iadnonov** [comment]
Hello @khanamiryan ,

Thank you for reaching out to us. This is a known issue, and it is logged in our public repository [here](https://github.com/telerik/kendo-react/issues/2154). We will do our best to prioritize the task and fix it as soon as possible.

Please excuse us for any inconvenience caused and if we can assist you with anything else, do not hesitate to submit a ticket in [our support system](https://www.telerik.com/account/support-center).

Cheers, 
Ivaylo
