### ISSUE TITLE
[Bug][Grid] Applying filtering to the GridColumnMenuColumnsList sets and returns wrong columns

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#2240]
## I'm submitting a...
* Bug report

## Current behavior
When you apply filter expression in the GridColumnMenuColumnsList in the column menu, the column list uses indexes of previously checked columns and applies the checked state to the same indexes even though the columns will differ after the filtering.

After clicking on the "Apply" button, the wrong columns are returned to the new column state (the columns that will be at the checked position but without the filter)

## Expected behavior
The correct columns should be checked/unchecked if filtering is applied to the GridColumnMenuColumnsList

## Minimal reproduction of the problem with instructions
Open the following example:
https://stackblitz.com/edit/react-z6kprw-7tkx5s?file=app%2Fmain.tsx,app%2FColumnMenu.tsx

Open a column menu and:
1) Unselect all
1) Select ProductID and ProductName
2) Filter by "st" (you will notice that test and test 1 columns will be checked because ProductID and ProductName were at those positions)
3) Click apply (ProductID and ProductName will be visible)

**Comment by zdravkov** [comment]
Fixed in the latest 'dev' version of KendoReact (https://stackblitz.com/edit/react-z6kprw-snapy3?file=app%2Fmain.tsx,package.json) and will be officially release in the next couple of days.
