### ISSUE TITLE
The Polar and the Radar Charts are throwing JS errors on zoom.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#225]
The Polar and the Radar Charts are throwing JS errors on zoom.

This can be observed in the following demos:

[https://www.telerik.com/kendo-react-ui-develop/components/charts/series-types/polar](https://www.telerik.com/kendo-react-ui-develop/components/charts/series-types/polar)
[https://www.telerik.com/kendo-react-ui-develop/components/charts/series-types/radar](https://www.telerik.com/kendo-react-ui-develop/components/charts/series-types/radar)

**Comment by vladimirivanoviliev** [comment]
Waiting 
telerik/kendo-charts#139

**Comment by vladimirivanoviliev** [comment]
fixed in latest kendo-charts dev version:
v1.13.4-dev.201910151431
