### ISSUE TITLE
Docs Issue: Tooltip anchor example is broken

### ISSUE THREAD

**Issue by kodamasama** [telerik/kendo-react#227]
## I'm submitting a...

* Documentation issue

## Current behavior

Example does not load. Stackblitz shows an extra \<strong> tag.

## Expected behavior

Example should load. 

## Minimal reproduction of the problem with instructions

Open this page:
https://www.telerik.com/kendo-react-ui/components/tooltip/anchor-elements/

**Comment by kspeyanski** [comment]
Hello @kodamasama ,
Thank you for reporting this.

The example has been fixed and is now properly loading:
https://www.telerik.com/kendo-react-ui/components/tooltip/anchor-elements/

Greetings
