### ISSUE TITLE
[Bug][Dropdownlist] Component has less height in 8.0.0 with material theme

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#2274]
## I'm submitting a...

* Regression report 

## Current behavior

In 8.0.0, with the kendo material theme, when the component has no value set, the height of the component is decreased

- https://stackblitz.com/edit/react-ggngqq-5m1sdf?file=app%2Fmain.jsx

This is not the case with previous versions like 7.4.0:

- https://stackblitz.com/edit/react-ggngqq-4m4lpb?file=package.json

Or with different themes like the default one:

- https://stackblitz.com/edit/react-25yyfq?file=app%2Fmain.jsx,index.html

## Expected behavior

The height remains the same with or without a value.

## Minimal reproduction of the problem with instructions

1. Remove any value or defaultValue props
2. Add the material theme
3. Use the latest KendoReact version

https://stackblitz.com/edit/react-ggngqq-5m1sdf?file=app%2Fmain.jsx

## Workaround

Set style.height

- https://stackblitz.com/edit/react-ggngqq-rother?file=app%2Fmain.jsx

Reported in Ticket ID: 1652781

**Comment by silviyaboteva** [comment]
Fixed in https://github.com/telerik/kendo-themes/pull/5047. It will be available in the next dev version of Kendo Themes.
