### ISSUE TITLE
[Bug][Scheduler] Selecting year on scheduler defaults to 1906 when user starts typing

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#2276]
## I'm submitting a...

* Bug report 

## Current behavior

When changing the year by focusing it then typing with the keyboard, it automatically switches to 1906. This is only the case with the DatePicker inside the Scheduler, and is not reproduced in the DatePicker alone.

https://somup.com/cZhtQl5EMj

## Expected behavior

The same behaviour as in the DatePicker - https://www.telerik.com/kendo-react-ui/components/dateinputs/datepicker/controlled-state/#toc-controlling-the-date-value

## Minimal reproduction of the problem with instructions

Can be reproduced on any editable Scheduler example - https://www.telerik.com/kendo-react-ui/components/scheduler/
You can make the Scheduler editable by setting its [editable](https://www.telerik.com/kendo-react-ui/components/scheduler/api/SchedulerProps/#toc-editable) prop to `true`.

Reported in Ticket ID: 1653222

**Comment by christopherjohnpaul** [comment]
Any update on this issue?

**Comment by silviyaboteva** [comment]
Hi @christopherjohnpaul,
The fix is available with the latest [8.1.1](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#v8.1.1) official version
Working demo in docs: https://www.telerik.com/kendo-react-ui/components/scheduler/editing/
