### ISSUE TITLE
[Enhancement][Editor] Add a name property to be able to use with Formik

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#2290]
## I'm submitting a...

* Suggestion for improvement

## Current behavior

The Editor does not have a name or id prop, and it is not possible to use it with Formik

https://stackblitz.com/edit/react-ej6o7e-pxrtna?file=app%2Fmain.tsx

It results in this warning:
"Formik called `handleChange`, but you forgot to pass an `id` or `name` attribute to your input: undefined
Formik cannot determine which value to update."

## Expected behavior
The Editor has the name property.

## Minimal reproduction of the problem with instructions

Render the component as a Formik input.

https://stackblitz.com/edit/react-ej6o7e?file=app%2Fmain.tsx

Ticket ID: 1654233

**Comment by Xizario** [comment]
Once I tried to use the Spreadsheet with Formik and had the same issue.

**Comment by WissamProgress** [comment]
Hi @Xizario :)

For the Editor we found a solution. The handleChange method is expecting the name and value properties while the event of the KendoReact Editor onChange is only passing the new value.

It can be passed as following:
```
 onChange={(e) =>
  handleChange({ target: { name: 'description', value: e.value } })
}
```
Here is an example - https://stackblitz.com/edit/react-ej6o7e-uzqatj?file=app%2Fmain.tsx

Another option would be to render a hidden input element with the value and name attribute.

I will also check the Spreadsheet component, but I believe that it can be handled in the same manner.

**Comment by WissamProgress** [comment]
For the Spreadsheet,`e.sender.sheets()` can be passed as a value:

https://stackblitz.com/edit/react-ri3p5w?file=app%2Fmain.tsx

We will close the GitHub issue, and we will recommend this approach for similar scenarios.
