### ISSUE TITLE
The DropDown is returning the nativeEvent and the syntheticEvent as undefined in its change event.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#23]
## I'm submitting a...

* Bug report 

## Current behavior

The DropDown is returning the nativeEvent and the syntheticEvent as undefined in its change event.

This can be observed in our events demo: https://www.telerik.com/kendo-react-ui-develop/components/dropdowns/dropdownlist/#toc-events

This is causing other components as the Grid which are utilizing the events to break.

Browser:

- All

**Comment by Xizario** [comment]
Fixed in version [0.6.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/)
