### ISSUE TITLE
[Bug][PDF] GridPDFExport and TreeListPDFExport ReactDOM import errors in react 17 and 19

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#2306]
Related to https://github.com/telerik/kendo-react/issues/2286

## I'm submitting a...

* Regression report

## Current behavior

After version `7.2.3`, the GridPDFExport and TreeListPDFExport components are causing the following errors.
<img width="1304" alt="Screenshot 2024-06-13 at 17 05 12" src="https://github.com/telerik/kendo-react/assets/108671796/1d913709-e1a9-4e0b-b39f-dca4cfc58507">

In Next 15 RC with React 19 RC

```
../../packages/pdf/src/grid/provideSaveGridPDF.tsx
Attempted import error: 'render' is not exported from 'react-dom' (imported as 'ReactDOM').
../../packages/pdf/src/treelist/provideSaveTreeListPDF.tsx
Attempted import error: 'render' is not exported from 'react-dom' (imported as 'ReactDOM').
```

These component are using either ReactDOM.render or createRoot based on the React version.

## Solution for React 17

Until this bug is fixed, you can use version `7.2.3` of `@progress/kendo-react-pdf` that does not import `react-dom/client`

## Expected behavior

No errors in all React versions.

## Minimal reproduction of the problem with instructions

Use the GridPDFExport or TreeListPDFExport component in React 17, or Next 15 RC.

**Comment by zdravkov** [comment]
Fixed in the latest 'dev' npm version. It will also be in included in the offical version of KendoReact that is expected next week

**Comment by jamesryan-dev** [comment]
which version was this fixed in? 

I've upgraded to React 18 now but getting this error when trying to use Kendo:

```
 ⨯ ./node_modules/@progress/kendo-react-pdf/KendoDrawingAdapter.mjs:10:1
Module not found: Package path ./server.js is not exported from package C:\Users\svc_appsrdp\Documents\Code\Journey\aadigital.journey.fe\node_modules\react-dom (see exports field in C:\Users\svc_appsrdp\Documents\Code\Journey\aadig
ital.journey.fe\node_modules\react-dom\package.json)

```
