### ISSUE TITLE
[Bug][Editor] Pressing Enter does not insert a new row every time

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#2307]
Pressing Enter does not insert new row every time. If the inserted <p> element has parent wrappers, every new Enter press moves the <p> tag one parent upper, unless the <p> element is moved outside the outer most parent.

Steps to reproduce:

Open https://codesandbox.io/p/sandbox/epic-blackwell-5xvpy8?file=%2Fapp%2Fmain.tsx
Click at the end of the row and Press enter 3-4 times
Result: Only one new row is inserted and on every new "Enter" the same <p> tag is just moved upper in the DOM tree,

Reported in Ticket ID: 1654529

Private issue - https://github.com/telerik/kendo-editor-common/issues/390

**Comment by nstoychev** [comment]
The observed behavior—where pressing "Enter" at the end of a paragraph causes the cursor to jump up one level in the DOM if the new paragraph is left empty—is actually expected in KendoReact Editor. This is a mechanism to allow users to exit nested block elements structures when reaching their end. Unfortunately, there's no straightforward solution to this without potentially affecting other aspects of the editor's functionality.

### Suggested Workarounds

For now, here are two approaches that may help:

1. **Avoid Leaving Paragraphs Empty**: By entering any character (even a space) in the new paragraph created by pressing "Enter," the issue of moving up a level in the DOM is avoided. This will ensure that the newly created paragraph remains at the same level within the `div`.
2. **Enable `isolating` on `div` Elements**: Another approach is to set [`isolating: true`](https://prosemirror.net/docs/ref/version/0.21.0.html#model.NodeSpec.isolating) on the [`div` elements in the Editor schema](https://www.telerik.com/kendo-react-ui/components/editor/schema/#toc-modifying-the-default-schema), which prevents the editor from moving up in the DOM hierarchy. However, this does come with a trade-off: if `isolating` is enabled, the user will be unable to continue typing beyond the last `div` in the editor. This limits their ability to add content after that structure.

Given the complexity of this behavior and the trade-offs of possible workarounds, we do not currently have plans to address this directly in the editor. We encourage users to consider these workarounds to achieve the best results in their specific use cases.
