### ISSUE TITLE
Arrow click is a bit buggy in the MultiViewCalendar

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#231]
* Bug report 

## Current behavior
When you click on the side arrows in the MultiViewCalendar, if you click directly on the icon it does not transition to the next month

## Expected behavior
Transition should happen no matter where inside the circle you click

## Minimal reproduction of the problem with instructions
See the custom rendering demo:
https://www.telerik.com/kendo-react-ui/components/dateinputs/datepicker/custom-rendering/#toc-customizing-the-calendar

See video:https://www.loom.com/share/c9c465f2d5e94d389ae2e5bb593bdcb7

## What is the motivation or use case for changing the behavior?
Less frustrating experience for the user

## Environment

Browser:

- Chrome (desktop) version 73

System:

- Platform:  Windows

**Comment by Xizario** [comment]
@kspeyanski we had on-site conversation with the other Kendo UI products, and the buttons for the material theme will be changed more or less similar to default and bootstrap. So I guess this issue will disappear. 

I thought it is directly related to https://github.com/telerik/kendo-themes/pull/675, but seems to be another issue I can't find. @hadjieva do we have issue about the changes we talked about?

**Comment by eeasss** [comment]
Related issue in kendo-themes:
https://github.com/telerik/kendo-themes/issues/688

**Comment by hadjieva** [comment]
@Xizario indeed we were discussing such change, however, it will be applied for all products once Lili submits the final design for the multiview calendar. This is the respective issue: [#26](https://github.com/telerik/kendo-ux-private/issues/26)

**Comment by k290** [comment]
This now seems to have been resolved. Can someone from Kendo please indicate which version this was fixed in so that we can plan an upgrade path in our software?

**Comment by Xizario** [comment]
@k290, 
It is fixed with https://github.com/telerik/kendo-themes/pull/711 

Works correct with: `kendo-theme-material@2.5.0` and it is broken with `kendo-theme-material@2.4.0`

You just need to update the theme that you are using, updating the react packages is not needed.

**Comment by k290** [comment]
Thanks
