### ISSUE TITLE
GridColumnMenuFilter's active filter not returning true when we select more than 3 option in GridColumnMenuCheckboxFilter

### ISSUE THREAD

**Issue by biratsapkota** [telerik/kendo-react#2314]
## I'm submitting a...
* Bug report

## Current behavior
`GridColumnMenuFilter` `active` property not returning true when we select more than 3 options in GridColumnMenuCheckboxFilter

## Expected behavior
`GridColumnMenuFilter`'s `active` should return correct value

## Minimal reproduction of the problem with instructions
for example: 
[reproduce here](https://stackblitz.com/edit/react-hqtubh?file=app%2Fmain.tsx)

## Environment

Package versions:
7.3.0

**Comment by iadnonov** [comment]
Hello @biratsapkota ,

Thank you for reaching out to us. This is a known issue, and it is logged in our public repository https://github.com/telerik/kendo-react/issues/1167. Our team will do their best to fix it, but till then a temporary workaround can be found in the following example:
https://stackblitz.com/edit/react-skkquv-ytekuc?file=app%2Fmain.tsx

Please excuse us for any inconvenience caused and if we can assist you with anything else, do not hesitate to submit a ticket in [our support system](https://www.telerik.com/account/support-center).

Cheers, 
Ivaylo
