### ISSUE TITLE
RectDom 19 findDomNode removed by team

### ISSUE THREAD

**Issue by coreybain** [telerik/kendo-react#2324]
I get the following build error when compiling nextjs 15 rc with react 19 rc.

**Note**: according to the React 19 upgrade guide this has now been fully removed: 
https://react.dev/blog/2024/04/25/react-19-upgrade-guide

./node_modules/@progress/kendo-react-sortable/Sortable.mjs
Attempted import error: 'findDOMNode' is not exported from 'react-dom' (imported as 'N').

Import trace for requested module:
./node_modules/@progress/kendo-react-sortable/Sortable.mjs
./node_modules/@progress/kendo-react-sortable/index.mjs
./node_modules/@progress/kendo-react-spreadsheet/SheetsBar.mjs
./node_modules/@progress/kendo-react-spreadsheet/Spreadsheet.mjs
./node_modules/@progress/kendo-react-spreadsheet/index.mjs
./src/app/(mainApp)/[lang]/(editorLayout)/editor/[key]/_components/editorUIHelpers/topBar/spreadSheetBlockEditorToolbar.tsx

### React 19 Update Guide Excerpt:

Removed: ReactDOM.findDOMNode 
ReactDOM.findDOMNode was [deprecated in October 2018 (v16.6.0)](https://legacy.reactjs.org/blog/2018/10/23/react-v-16-6.html#deprecations-in-strictmode).

We’re removing findDOMNode because it was a legacy escape hatch that was slow to execute, fragile to refactoring, only returned the first child, and broke abstraction levels (see more [here](https://legacy.reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage)). You can replace ReactDOM.findDOMNode with [DOM refs](https://react.dev/learn/manipulating-the-dom-with-refs):

// Before
import {findDOMNode} from 'react-dom';

function AutoselectingInput() {
  useEffect(() => {
    const input = findDOMNode(this);
    input.select()
  }, []);

  return <input defaultValue="Hello" />;
}
// After
function AutoselectingInput() {
  const ref = useRef(null);
  useEffect(() => {
    ref.current.select();
  }, []);

  return <input ref={ref} defaultValue="Hello" />
}

**Comment by zdravkov** [comment]
Thank you for reporting it. We are aware of the issue and will do our best to fix it as soon as possible.

**Comment by silviyaboteva** [comment]
This fix is included in version 8.1.0-develop.27. It will be available in the next official version.

**Comment by coreybain** [comment]
@silviyaboteva Tested and working well - thanks for the awesome work!
