### ISSUE TITLE
Material Theme - Input's underscore misaligned, obvious if next to other controls like NumericTextBox

### ISSUE THREAD

**Issue by VirtualDestructor777** [telerik/kendo-react#234]
## I'm submitting a...

* Bug report 

## Current behavior

Underlining is misaligned between Input and other input field types when using material scheme.

## Expected behavior

All controls aligned to the same baseline horizontally, as in a row, should have underlines in the same vertical position.

## Minimal reproduction of the problem with instructions

Open stack blitz from here:
https://www.telerik.com/kendo-react-ui/components/inputs/floating-labels/

add material theme

notice mis-alignment (you may have to squint or take a screenshot and zoom in - very noticeable if you pop into chrome tools and simulate iPhone etc., or have no spacing between components).

Could not save stackblitz for some reason.

## What is the motivation or use case for changing the behavior?

Make kendo usable with material scheme in commercial setting.

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Firefox version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:  Linux

ran into it while evaluating kendo-react, a bit of showstopper naturally as I do not see easy way to fix it up without hacking.

**Comment by Xizario** [comment]
@VirtualDestructor777 , I have logged it into our themes repository to have better visibility for the front-end developers and designers. please follow the item there:
https://github.com/telerik/kendo-themes/issues/698
