### ISSUE TITLE
how to configure grid to work with virtual scroll, loading data on demand and grouping?

### ISSUE THREAD

**Issue by da1z** [telerik/kendo-react#2345]
basically I am trying to display grouped data with virtual scroll that being loaded page by page. I am trying to implement combination of this example https://www.telerik.com/kendo-react-ui/components/grid/scroll-modes/virtual/#toc-using-virtualization-with-grouping and this https://www.telerik.com/kendo-react-ui/components/grid/scroll-modes/virtual/#toc-debouncing-pagechange-events . please advice how to do it?

**Comment by iadnonov** [comment]
Hello, @da1z ,

Keep in mind that the repository is exclusively dedicated to addressing bugs, handling feature requests, and discussing product enhancements. If you require assistance with setting up a specific scenario or configuring a KendoReact component, please do not hesitate to open a ticket in our [support system](https://identity.telerik.com/login?redirect_uri=https:%2F%2Fwww.telerik.com%2Ftracking%2Flogin%3Fredirect_uri%3Dhttps%253a%252f%252fwww.telerik.com%252faccount%252fsupport-tickets&response_type=code&client_id=http:%2F%2Fwww.lean.telerik.com.v2&state=AEA9C89ED92720CB154865EF614CE64637BFEE080CF2F5338044700089EE7BA4).

Greetings, 
Ivaylo
