### ISSUE TITLE
Prevent MultiSelect searchKey to be removed on any item selected

### ISSUE THREAD

**Issue by baranseldinc** [telerik/kendo-react#2346]
Hi everyone,

I would like to have [MultiSelect](https://www.telerik.com/kendo-react-ui/components/dropdowns/multiselect/)  component prevented the searchKey to be removed on any item selected.

## Current behavior
![image](https://github.com/telerik/kendo-react/assets/6670970/1ac0f02c-838f-41b9-a0e9-65eb06304493)
After select any item from popover, the searchKey gets resetted.
![image](https://github.com/telerik/kendo-react/assets/6670970/1a30a0d6-4ee4-4a70-a8fe-2d4530dfedcc)

## Expected behavior
![image](https://github.com/telerik/kendo-react/assets/6670970/140bf31f-0c7e-4d55-a9fb-56fe8ce50b18)
As seen above, I would like to have searchKey to be leaved as it is when any item selected.

Not sure if we are able to achieve the controlled state of textfield for searchkey.

Thanks for your atteniton.
Best regards.

**Comment by iadnonov** [comment]
Hi @baranseldinc, 

Keep in mind that the repository is dedicated solely to addressing bugs, handling feature requests, and discussing product enhancements. If you need help with setting up a specific scenario or configuring a KendoReact component, please don't hesitate to open a ticket in our [support system](https://www.telerik.com/account/support-tickets).
Before doing that, I recommend checking the MultiSelect `filter` prop on our [documentation page](https://www.telerik.com/kendo-react-ui/components/dropdowns/api/MultiSelectProps/#toc-filter).

Greetings, 
Ivaylo
