### ISSUE TITLE
[Bug][TreeList] TreeListNumericFilter will create filter descriptor with null if the value is deleted

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#2348]
## I'm submitting a...
* Bug report 

## Current behavior
When you enter a value within the TreeListNumericFilter and then delete it, a filter descriptor with "null" value will be created instead of clearing the filter for the field.

## Expected behavior
When the value within the TreeListNumericFilter is deleted, no filter descriptor should be passed.

## Minimal reproduction of the problem with instructions
Open the example:
https://stackblitz.com/edit/react-5abjcu?file=app%2Fmain.jsx

Enter "2" in the filter of the "Years in position" column and then delete it. You will notice that no records will be shown.

Temporary Workaround:
If the "eq" operator is created with "null" value, we can remove it from the filter descriptor
https://stackblitz.com/edit/react-s1hjak?file=app%2Fapp.jsx

```
  const handleDataStateChange = (event) => {
    let newDataState = { ...event.dataState };
    if (newDataState.filter && newDataState.filter.length > 0) {
      newDataState.filter = newDataState.filter.filter(
        (filter) => !(filter.operator == 'eq' && filter.value == null)
      );
    }
    setState({
      ...state,
      dataState: newDataState,
    });
  };
```

**Comment by silviyaboteva** [comment]
This pull request is included in version 8.2.0.
