### ISSUE TITLE
[BUG] Rendering mismatch for the TimePicker (opened) > action button (k-actions)

### ISSUE THREAD

**Issue by NickIliev** [telerik/kendo-react#2359]
**Bug Report**

The TimePicker (opened) > Action buttons are rendered with different CSS selectors than the source of truth tests. This results in ThemeBuilder producing styles that are incompatible with other Kendo/Telerik suites.

Source of truth tests: https://www.telerik.com/kendo-react-ui/components/dateinputs/timepicker/ (note that the k-timeselector and the k-actions selector are on the same level)

![image](https://github.com/telerik/kendo-react/assets/18008302/7679d376-1190-4203-9ace-f071d03ab6f3)

However, that is not the case in TimePicker for Kendo React

![image](https://github.com/telerik/kendo-react/assets/18008302/c3d95442-1af2-4803-8477-fadad104d91f)

## Expected behavior
The timepicker rendering follows the unified rendering per the source of truth tests.

Package versions:
Kendo React Q2 2024

Reported through t.1657408

**Comment by PekoPPT** [comment]
Hey, @NickIliev, thank you for the report. The issue was added to our planning and will be fixed in Q4.
