### ISSUE TITLE
Cannot read property 'optionsStore' of undefined in Chart when React.StrictMode is used.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#236]
Cannot read property 'optionsStore' of undefined in Chart when React.StrictMode is used.

This can be observed in the following demo:

https://stackblitz.com/edit/react-czl5og?file=app/main.jsx

**Comment by simonssspirit** [comment]
This is connected to the use of old context.api

**Comment by vladimirivanoviliev** [comment]
Charts and Gauges are updated with new context API - waiting unit tests support to release it.

**Comment by simonssspirit** [comment]
As our tests and using Enzyme, we are currently blocked by the following issue:

https://github.com/enzymejs/enzyme/issues/1553

The fix in the KendoReact Charts is on PR, once the enzyme issue is resolved or there is a workaround available, we will proceed.

**Comment by kspeyanski** [comment]
This issue is no longer reproducible after the update to the new Context API:
https://github.com/telerik/kendo-react/issues/548
