### ISSUE TITLE
[Bug][Splitter] SplitterPane className and style props do not work

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#2364]
## I'm submitting a...

* Bug report

## Current behavior

The component provides two props to style the panes, the className and style prop. However, both do not work

https://www.telerik.com/kendo-react-ui/components/layout/api/SplitterPaneProps/#toc-classname
https://www.telerik.com/kendo-react-ui/components/layout/api/SplitterPaneProps/#toc-style

## Expected behavior

These properties work as expected.

## Minimal reproduction of the problem with instructions

set the style or className prop. For example, the following array is passed to the `panes` prop of the component:

```
  const [panes, setPanes] = React.useState<Array<any>>([
    { style: { color: 'red' }, className: 'test' },
 
  ]);
```

## Workaround
Style the pane components using CSS, using the `.k-pane.k-scrollable` class.

Reported in Ticket ID: 1658152

**Comment by silviyaboteva** [comment]
The issue is fixed and will be available in the next official version.
