### ISSUE TITLE
NumericTextBox does not apply form attribute

### ISSUE THREAD

**Issue by apocer** [telerik/kendo-react#237]
## I'm submitting a...

* Bug report 
* Suggestion for improvement

## Current behavior
When using `<NumericTextBox form={someFormId} />` the attribute is not added to the resulting input html tag.

## Expected behavior
Using `<NumericTextBox form={someFormId} />` should result in `<input form={someFormId}>`.

## What is the motivation or use case for changing the behavior?

One is able to nest forms with NumericTextBoxes by using `<form id="abc"></form><NumericTextBox form="abc />`. Then submitting the form "abc" from the NumericTextBox is possible.

## Environment

Package versions:
@progress/kendo-react-inputs@2.10.0

Browser:

- Chrome (desktop)

System:
- TypeScript version: XX
- Node version: 6.4.1
- Platform:  Windows

**Comment by Xizario** [comment]
We can add it for the other inputs as well. But it should be noted into the docs that this attribute does not work in IE.

**Comment by simonssspirit** [comment]
Until this is officially implemented, any desired attributes can be added to the element using the component ref and the setAttribute function.

This is an example: https://stackblitz.com/edit/react-kuc9hx?file=app/main.jsx

**Comment by InaGlushkova** [comment]
A new article about how to apply custom Form attributes on the Inputs is added in the latest dev 4.7.0-dev.20210609065.

**Comment by InaGlushkova** [comment]
Link to the article:
https://www.telerik.com/kendo-react-ui/components/inputs/custom-attributes/
