### ISSUE TITLE
First grouped row should not contain k-alt class

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-react#239]
## I'm submitting a...

* Bug report 

## Current behavior
https://stackblitz.com/edit/react-aqpkng?file=app/main.jsx
The row that starts with 'Chang' contains k-alt class and  appears darker instead light 
## Expected behavior
The row that starts with 'Chang' does not contain k-alt class and appears light

**Comment by Xizario** [comment]
This is the correct behaviour. In the last few versions the alt row is absolute index based, rather than local group based. This is required for virtualization with grouping to work. If the alt is group based, it is not consistent across pages.
