### ISSUE TITLE
i cant paste persian number in NumericTextBox in kendo react 

### ISSUE THREAD

**Issue by Basiiil** [telerik/kendo-react#2394]
## Current behavior

i use <IntlProvider locale="fa"><LocalizationProvider language="fa"> but when paste persian number like ۲۷۱۵۰ not paste anything,how can fix it?

## Environment

Package versions:

```
4.14.1
```
```[tasklist]
### Tasks
```

**Comment by silviyaboteva** [comment]
This repository is exclusively dedicated to addressing bugs, handling feature requests, and discussing product enhancements. If you need help with setting up a specific scenario or configuring a KendoReact component, please don't hesitate to open a ticket in our [support system](
https://www.telerik.com/account/support-tickets).

Up to your question, the NumericTextBox supports formatting the value via the [format](https://www.telerik.com/kendo-react-ui/components/inputs/api/NumericTextBox/#toc-format/) property. Please keep in mind that Number formatting converts a Number object into a human-readable string using the locale specific settings.

I have also prepared a demonstration on how to import the `cldr-package` for the Persian format:
https://stackblitz.com/edit/react-rt2bfp-vthjux?file=app%2Fmain.jsx

For more information on the date and number formats KendoReact supports, refer to the [kendo-intl](https://github.com/telerik/kendo-intl/blob/master/docs/num-formatting/index.md) GitHub repository.

**Comment by Basiiil** [comment]
no my problem is not about date,i cant input number in numeric with copy paste
[Screencast from 24-08-05 09:21:43.webm](https://github.com/user-attachments/assets/a3220ad4-d4ad-4d26-abf5-9212801b8bf5)
