### ISSUE TITLE
[Bug][Sparkline] Cannot read properties of undefined (reading 'format') when pressing tab

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#2396]
## I'm submitting a...

* Bug report

## Current behavior

Pressing tab results in an error in `/turbo_modules/@progress/kendo-charts@2.4.1/dist/npm/main.js (15000:41)
` that is `Cannot read properties of undefined (reading 'format')`

## Expected behavior

No errors when tabbing.

## Minimal reproduction of the problem with instructions

Open any Sparkline Chart and press tab
https://stackblitz.com/edit/react-cg2sit?file=app%2Fapp.jsx

Reported in Ticket ID: 1658832

**Comment by vveesseelliinnaa** [comment]
The issue is fixed and will be available in version 9.0.0 of KendoReact.
