### ISSUE TITLE
[Bug][Grid] The buttons inside GridColumnMenuColumnsList cannot be localized

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#2399]
## I'm submitting a...

* Bug report 

## Current behavior
The values of the `Apply` and `Reset` buttons inside the tabbed ColumnList menu are hard coded and cannot be localized.

https://github.com/telerik/kendo-react-private/blob/a2acafa87c2ce214472d8045396a9bdf715cab50/packages/grid/src/columnMenu/GridColumnMenuColumnsList.tsx#L109

![image](https://github.com/user-attachments/assets/20aa8c11-5f14-482c-8fd7-d29d7c8d4677)

## Minimal reproduction of the problem with instructions

1. Open https://stackblitz.com/edit/react-twvbj9-nsyijg?file=app%2Fmain.jsx,app%2FColumnMenu.jsx
2. Click on the column menu of any of the columns
3. Click on the right most tab inside the menu popup (the column list)

Result: the Apply/Reset buttons are not translated

## Additional information

Reported in Ticket ID: 1659559

**Comment by marclindsaynvx** [comment]
I would add those labels also:

- (Select all)
- selected items
