### ISSUE TITLE
Grid Component Hardcoded Colors

### ISSUE THREAD

**Issue by PaitoAnderson** [telerik/kendo-react#241]
## I'm submitting a...
* Bug report

## Current behavior
There are a couple #f6f6f6 (rgb(246,246,246)) hardcoded colors in the grid which prevents me from fully giving it a dark theme.

<img width="867" alt="Screen Shot 2019-04-30 at 9 25 34 AM" src="https://user-images.githubusercontent.com/4108718/56965104-7bb88700-6b2a-11e9-997c-844c8dd891a5.png">

## Expected behavior
Allow customizing all background colors on the grid

## What is the motivation or use case for changing the behavior?
Allow a full dark theme

## Environment

Package versions:
```
├── @progress/kendo-data-query@1.5.1
├── @progress/kendo-react-buttons@2.10.0
├── @progress/kendo-react-dateinputs@2.10.0
├── @progress/kendo-react-dialogs@2.10.0
├── @progress/kendo-react-dropdowns@2.10.0
├── @progress/kendo-react-excel-export@2.10.0
├── @progress/kendo-react-grid@2.10.0
├── @progress/kendo-react-inputs@2.10.0
├── @progress/kendo-react-intl@2.10.0
├── @progress/kendo-react-layout@2.10.0
├── @progress/kendo-react-popup@2.10.0
```

Browser:

- Chrome (desktop) version 74.0.3729.108

System:
- TypeScript version: 3.2.2
- Node version: v11.10.0 and v6.9.0
- Platform:  macOS

**Comment by simonssspirit** [comment]
This is already logged in our themes, so we can remove the inline styles. In the issue there are also styles shared for dark theme and how to overwrite the current elements with inline styles:

https://github.com/telerik/kendo-themes/issues/630

**Comment by Xizario** [comment]
I know it is bad practice, but currently can be styled using `!important` rule since it overrides the inline styles.
https://www.w3.org/TR/CSS2/cascade.html#important-rules

**Comment by PaitoAnderson** [comment]
Thanks @simonssspirit ! that resolves my issue, feel free to close if this issue doesn't belong here.

**Comment by silviyaboteva** [comment]
In order to work, it would be required to install the latest version of the used theme.
