### ISSUE TITLE
[Bug][Breadcrumb] BreadcrumbLink does not set custom class names added through the className property

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#2410]
## I'm submitting a...
* Bug report

## Current behavior
The className property of the BreadcrumbLink is ignored

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-qjsung?file=app%2Fapp.jsx
As you will notice in the example, the className is not added to the BreadcrumbLink element

(temporary workaround is to add a wrapping element with the class name)

Package versions:
8.1.1

**Comment by elena-gancheva** [comment]
The fix is available in version 8.2.0-develop.29 and will be released soon in an official version
