### ISSUE TITLE
Grid - Virtual Scrolling leaves blank space at bottom when horizontal scroll is enabled

### ISSUE THREAD

**Issue by seangolob** [telerik/kendo-react#242]
## I'm submitting a...
* Bug report 

Found in Chrome version `73.0.3683.103`

## Current behavior
* Virtual Scrolling leaves blank space at bottom of grid when horizontal scroll is enabled

## Expected behavior
* I expect there to be no whitespace at the bottom of the grid

## Minimal reproduction of the problem with instructions
1. Go to https://stackblitz.com/edit/react-ljptvp?file=app/main.jsx
2. Scroll to the bottom of the grid
 
You should see a blank space at the bottom of the grid

NOTE: If you raise the width to remove horizontal scrolling, the behavior is as expected.

**Comment by Guria** [comment]
https://user-images.githubusercontent.com/36270/128492266-d98b1114-e721-45ca-b179-17b49b87853c.MP4

**Comment by simonssspirit** [comment]
probably connected to https://github.com/telerik/kendo-react/issues/1013 and https://github.com/telerik/kendo-react/issues/847

**Comment by nstoychev** [comment]
Fixed in version 5.10.0.

Note that grid's `rowHeight` prop is required now and the `pageSize`/`take` props need to be at least 2 times the count of the visible rows.
