### ISSUE TITLE
locked columns don't work on IE11

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-react#245]
## I'm submitting a...

* Bug report 

## Current behavior
https://stackblitz.com/edit/react-bnpz4r?file=app/main.jsx

## Expected behavior
Locked columns are working correctly

Browser:

- IE version 11

**Comment by Xizario** [comment]
Works in latest Edge.
Also:
https://www.zdnet.com/article/microsoft-security-chief-ie-is-not-a-browser-so-stop-using-it-as-your-default/
