### ISSUE TITLE
[Bug][Calendar] Calendar body disappears in StrictMode

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#2456]
## I'm submitting a...

* Regression report 

## Current behavior
When rendering the Calendar component in `StrictMode` and next to a Grid, the body of the Calendar is missing. This behavior is observed in version `8.1.0` of the components and above. In version `8.0.0` the Calendar is rendered as expected:

https://stackblitz.com/edit/react-mec2dy-v45w4q?file=package.json

## Expected behavior
When the Calendar is rendered in `StrictMode` and next to a Grid, its body should be rendered.

## Minimal reproduction of the problem with instructions
1. Open this example with version `8.1.0` of the components and observe the missing body: https://stackblitz.com/edit/react-mec2dy-qq5l5a?file=app%2Fapp.tsx
2. Remove either `StrictMode` or the Grid definition and observe that the body of the Calendar is now visible.

## Workaround

https://stackblitz.com/edit/react-mec2dy-9cp97e?file=app%2Fapp.tsx

Reported in Ticket ID: 1658012

**Comment by iadnonov** [comment]
Fixed in dev version v8.3.0-develop.11
