### ISSUE TITLE
Kendo-react-pdf 8.1.1 doesnt work with Emotion v11

### ISSUE THREAD

**Issue by jamesryan-dev** [telerik/kendo-react#2458]
## I'm submitting a bug outlined in this post here: https://www.telerik.com/forums/styling-issues-after-upgrading-kendo-react-pdf

* Bug report: Using latest versions of both Kendo-react-pdf and Emotion breaks our PDF templating

## Current behavior
https://www.telerik.com/forums/styling-issues-after-upgrading-kendo-react-pdf

## Expected behavior
It keeps the styling / works 

## Minimal reproduction of the problem with instructions
See link attached as part of this conversation - https://www.telerik.com/forums/styling-issues-after-upgrading-kendo-react-pdf

## What is the motivation or use case for changing the behavior?
Working PDFs

## Environment

Package versions:
    "@emotion/react": "^11.9.3",
    "@emotion/styled": "^11.9.3",
    "@progress/kendo-react-pdf": "8.1.1",
    "@progress/kendo-theme-default": "^8.0.1",

We used latest for all 

Browser:
Chrome & Edge

System:
Windows and Mac

**Comment by PaskalevStoyan** [comment]
hi @jamesryan-dev,

Thanks for coming to us with this issue. 

![image](https://github.com/user-attachments/assets/44b72853-ba6a-47fb-b060-7bb9242b97e9)

In the forum thread which you've linked, our technical support engineer explains very thoroughly that this is not an issue related to the KendoReact PDF package but rather related with emotion. What I would suggest is to open an issue in the public repository of [EmotionJS](https://github.com/emotion-js).

I hope this information helps.
