### ISSUE TITLE
[Bug][Form] utils.mjs try to focus on null object 

### ISSUE THREAD

**Issue by filipc-tq** [telerik/kendo-react#2461]
## I'm submitting a...
* Bug report 

## Current behavior
Script @progress/kendo-react-data-tools/navigation/utils.mjs throwing error when editable grid inside Form.Field element is changing value programmatically. It is try to invoke focus() function on "void 0" when variable t is null. 
There should be a null check before invoking function. 

```
oe = (e) => {
  const t = e.querySelector(".k-grid-edit-cell"), r = t && t.querySelector("input");
  r ? r.focus() : (t == null ? void 0 : t.firstChild).focus();
}
```

## Environment

Package versions:

```
@progress/kendo-react-data-tools@8.2.0
```

**Comment by silviyaboteva** [comment]
Thank you for reporting this. It is considered as bug and we will fix it as soon as possible.

**Comment by silviyaboteva** [comment]
Hello again, @filipc-tq 

The null check is introduced in `v8.3.0-develop.9` and it will be available in the next official version.

Still, it would be of great help if you share with us a reproducible demo project that demonstrates the scenario with the integration of the Grid in a Form Field.

Thank you!
