### ISSUE TITLE
Browser throws warning messages for non-existent src folder for all components.

### ISSUE THREAD

**Issue by prajwalmr62** [telerik/kendo-react#25]
## I'm submitting a...

* Bug report 

## Current behavior
Browser throws warning messages, 
`(Emitted value instead of an instance of Error) Cannot find source file '../../../src/barcode/index.tsx': Error: Can't resolve '../../../src/barcode/index.tsx' in '<app-path>\node_modules\@progress\kendo-barcodes-react-wrapper\dist\es\barcode'`

## Expected behavior
No warning messages should be thrown.

## Minimal reproduction of the problem with instructions
Run the application in dev mode with warnings enabled.

## What is the motivation or use case for changing the behavior?

We flag warning messages in build log, this contributes to large amount of warnings.

## Environment

Package versions:

```
"@progress/kendo-barcodes-react-wrapper": "^2018.1.221",
    "@progress/kendo-react-buttons": "^0.5.1",
    "@progress/kendo-react-common": "^0.5.1",
    "@progress/kendo-react-ripple": "^0.5.1",
    "@progress/kendo-theme-default": "^2.51.0",
    "@progress/kendo-ui": "^2018.1.503",
    "@progress/kendo-window-react-wrapper": "^2018.1.221",
```

Browser:

- Chrome (desktop) version XX

System:
- TypeScript version: 2.8.1 
- Node version: 8.9.1 
- Platform:  Windows

**Comment by Xizario** [comment]
@prajwalmr62, Could you extend the the reproduction steps with more details. 
>Run the application in dev mode with warnings enabled.

I don't see an application linked in this issue.

**Comment by Xizario** [comment]
If it works fine then you are already using it correctly and it is not a but in the package itself.

There is no `index.tsx` in the [barcode package](https://unpkg.com/@progress/kendo-barcodes-react-wrapper@2018.1.221/dist/es/barcode/). And the code in the `index.js`

The warnings could be from `webpack` configuration or old version of [source-map-loader](https://github.com/webpack-contrib/source-map-loader/issues) that is trying to find and `.tsx` file to maintain the source map in debug. Even if the package already have `js.map`

**Comment by simonssspirit** [comment]
The issue seems to be connected to the Webpack configuration or the source map version.

If the issue still occurs, please send us a ticket with the example in our support system and we will inspect it locally.
