### ISSUE TITLE
Able to customize "Expanding Icon" to show DetailsRow (Children Row) of Grid.

### ISSUE THREAD

**Issue by casonlebusiness** [telerik/kendo-react#250]

**Comment by simonssspirit** [comment]
@casonlebusiness This can be done using a custom expand collapse column and will allow full control over the visual and logic part of the functionality.

This is an example of how it can be achieved:


https://stackblitz.com/edit/react-abh1id-cqcryg?file=app/main.jsx

**Comment by simonssspirit** [comment]
https://www.telerik.com/kendo-react-ui/knowledge-base/custom-expand-collapse-column/
