### ISSUE TITLE
KendoReact Editor Arabic PDF Export Issue

### ISSUE THREAD

**Issue by Genesis671230** [telerik/kendo-react#2511]
**Description**: 

We are facing a critical issue with the KendoReact Editor when exporting content containing Arabic text to PDF. The exported PDFs do not render Arabic text correctly, resulting in formatting issues and incorrect character display. Notably, this issue only occurs with Arabic text, as English text exports without any problems.

**Issue Details**:
1.     Component: KendoReact Editor
2.     Issue: Arabic text is not rendering correctly in exported PDFs.

**Observed Behavior**:

-     Arabic characters appear as symbols or are replaced by boxes.
-     Text alignment is incorrect (Arabic should be right-to-left).
-     Only a few characters display correctly, while others are distorted.

**Expected Behavior:**

-       Proper right-to-left alignment.
-       Correct font rendering with all Arabic characters displayed as intended.

Steps to Reproduce:

1. Create a new document in the KendoReact Editor.
2. Add Arabic text content.
3. Export the content as a PDF using the savePDF function.
4. Open the exported PDF to observe the rendering issues.

**Approaches Tried:**

Custom Fonts: We integrated custom fonts to support Arabic characters, but the issue persists.

Configuration Adjustments: We adjusted various settings in the savePDF function (margins, scaling, resolution), with no success.

Environment Testing: The issue was consistent across different browsers and environments.

savePDF(editorContent, {
    paperSize: 'A4',
    margin: { top: '2cm', bottom: '2cm' },
    scale: 0.8,
    forcePageBreak: '.page-break',
    fileName: 'document.pdf',
    font: {
        family: 'CustomArabicFont',
        size: 16
    }
});

**Packages in Use:**
@progress/kendo-data Arabic Content With Issue.pdf-query: ^1.7.0
@progress/kendo-drawing: ^1.20.2
@progress/kendo-file-saver: ^1.1.1
@progress/kendo-inputs-common: ^3.1.1
@progress/kendo-intl: ^3.1.2
@progress/kendo-licensing: ^1.3.5
@progress/kendo-popup-common: ^1.9.2
@progress/kendo-react-animation: ^8.0.0
@progress/kendo-react-buttons: ^8.0.0
@progress/kendo-react-common: ^8.0.0
@progress/kendo-react-data-tools: ^8.1.1
@progress/kendo-react-dateinputs: ^8.1.1
@progress/kendo-react-dialogs: ^8.0.0
@progress/kendo-react-dropdowns: ^8.0.0
@progress/kendo-react-editor: ^8.0.0
@progress/kendo-react-excel-export: ^8.1.1
@progress/kendo-react-form: ^8.0.0
@progress/kendo-react-gantt: ^8.1.1
@progress/kendo-react-gauges: ^8.1.1
@progress/kendo-react-grid: ^8.1.1
@progress/kendo-react-indicators: ^8.1.1
@progress/kendo-react-inputs: ^8.0.0
@progress/kendo-react-intl: ^8.0.0
@progress/kendo-react-labels: ^8.2.0
@progress/kendo-react-layout: ^8.0.0
@progress/kendo-react-listbox: ^8.1.1
@progress/kendo-react-listview: ^8.1.1

**Environment Details:**

KendoReact Version: ^8.0.0
React Version: 18.2.0
Browser/OS: Tested on Chrome, Windows 11, macOS
Additional Information: This issue is severely impacting our ability to generate accurate Arabic PDFs, while English text exports without issues. We need a resolution or workaround as soon as possible to ensure proper functionality for our users.

**Attachments**:
Sample HTML Arabic content (before export) [ Expected Arabic Content.pdf ]
PDF file (after export showing the issue) [ Arabic Content With Issue.pdf ]
Priority: High (Affects production usage)

Thank you for your assistance.
Best regards,

**Comment by silviyaboteva** [comment]
Hello @Genesis671230,

We noticed that you have duplicated ticket in our [support system](
https://www.telerik.com/account/support-tickets) with ID: 1664750. Please check my colleague's response there. Also, you may continue the discussion in the support thread as this repository is exclusively dedicated to addressing bugs, handling feature requests, and discussing product enhancements. 

I'm closing this one.
