### ISSUE TITLE
Can not export PDF file in IE 11

### ISSUE THREAD

**Issue by yellowjian** [telerik/kendo-react#252]
Can not export PDF file in IE 11,
IE save unsuccessful (disable save and open button)

Package versions:
    "@progress/kendo-drawing": "^1.5.12",
    "@progress/kendo-react-pdf": "^2.11.0",

Browser:

- IE version 11

System:
- Node version: 6.xx  
- Platform:

**Comment by asen-arizanov** [comment]
The PDF code depends on common functions like `Object.assign` which are not included in IE 11 by default. 

Could you please add shims (e.g. <script src="https://unpkg.com/core-js@2.6.6/client/shim.js"></script>) and try again?

**Comment by yellowjian** [comment]
@asen-arizanov 
kendo-react-pdf is for export pdf file in react code, i can export in chrome, but can not export successful in IE 11

**Comment by yellowjian** [comment]
@asen-arizanov  could you give me a demo ? thanks.

**Comment by asen-arizanov** [comment]
Try [https://stackblitz.com/edit/react-jh1axf](https://stackblitz.com/edit/react-jh1axf).

**Comment by yellowjian** [comment]
@asen-arizanov many thanks. but it not work for me, maybe my IE 11 have some problems.

**Comment by asen-arizanov** [comment]
Moving the script tag with the shim inside the body tag - [https://stackblitz.com/edit/react-jh1axf-nr9lxy](https://stackblitz.com/edit/react-jh1axf-nr9lxy). If it still does not work, verify that the shim HTTP request is successful.

**Comment by yellowjian** [comment]
i am so sorry for this issue, the reason is my company IE problem.
