### ISSUE TITLE
kendo-react-gauges Range interface is incorrect

### ISSUE THREAD

**Issue by manav-razr** [telerik/kendo-react#253]
## I'm submitting a...

* Bug report 

## Current behavior

In kendo-react-gauges, range.interface.d.ts defines `color` as a `number`.

## Expected behavior

`color` should be either `string` or `string|number`.

## Environment

Package versions:

```
    "@progress/kendo-react-gauges": "^2.11.0",

```

**Comment by manav-razr** [comment]
Any update on this?

**Comment by vladimirivanoviliev** [comment]
@manav-razr Already fixed on our side, the fix will be released with next dev version (till the end of the week).

**Comment by vladimirivanoviliev** [comment]
Fix is released in v3.5.0-dev.201910141223: 
- https://www.telerik.com/kendo-react-ui-develop/components/gauges/api/Range/
