### ISSUE TITLE
Date Input controls prevent bubbling the key event when Escape key is pressed

### ISSUE THREAD

**Issue by YKlos** [telerik/kendo-react#254]
## I'm submitting a...
* Bug report

## Current behavior
The Date Input controls are not bubbling the keydown event if the "Escape" key was pressed.

## Expected behavior
The date input controls should not prevent the key event from bubbleing up when the "Escape" key is pressed.

## Minimal reproduction of the problem with instructions
https://react-dubyfk.stackblitz.io

  1. Open the stackblitz example and focus the DateInput field.
  2. Press the "Escape" key.

## What is the motivation or use case for changing the behavior?
I implemented the KendoReact grid with incell edit mode. The edit mode of the cell should close when pressing the "Escape" key.

## Environment

Package versions:
2.11.0

Browser:
- Chrome (desktop) version 74

**Comment by asen-arizanov** [comment]
The issue will be fixed shortly.

**Comment by asen-arizanov** [comment]
Fixed in 3.2.2
