### ISSUE TITLE
getData is called on scrolling even if Grid column virtualization is false

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-react#256]
getData is called each time when scrolling horizontally back and forth even if Grid column virtualization is false.

## Bug report 

1. Configure the Grid with columnVirtualization false and scrollable virtual:
```
   <Grid
                style={{ width: '720px', height: '400px' }}
                columnVirtualization={false}

                scrollable="virtual"
                data={this.getData(this.state.skip, this.state.take)}
                skip={this.state.skip}
                take={this.state.take}
                total={this.numberOfRows}
                onPageChange={this.pageChange}
            >
                {this.columns}
            </Grid>
```
2. Scroll horizontally

## Current behavior
getData is called

## Expected behavior
getData is not called when column virtualization is false

Note: if setting scrollable="scrollable" the getData is not called when scrolling both horizontally and vertically.

## Environment

Package versions:
@progress/kendo-data-query1.5.1
@progress/kendo-drawing1.5.12
@progress/kendo-react-animation2.11.0
@progress/kendo-react-buttons2.11.0
@progress/kendo-react-dateinputs2.11.0
@progress/kendo-react-dialogs2.11.0
@progress/kendo-react-dropdowns2.11.0
@progress/kendo-react-excel-export2.11.0
@progress/kendo-react-grid2.11.0
@progress/kendo-react-inputs2.11.0
@progress/kendo-react-intl2.11.0
@progress/kendo-react-layout2.11.0
@progress/kendo-react-pdf2.11.0
@progress/kendo-react-popup2.11.0
prop-types15.7.2
react16.8.6
react-dom16.8.6
react-transition-group4.0.1

**Comment by Xizario** [comment]
During the scroll event we don't really know if horizontal, vertical or both happened at the same time. (for example you can scroll diagonally or in any direction on mac or touch device as well)

If `scrollable="virtual"` the event will be fired on scroll regardless if dY is 0. User can make further checking on his event handler if he want to bypass is
