### ISSUE TITLE
Date range picker - input separator enhancement

### ISSUE THREAD

**Issue by Nodios** [telerik/kendo-react#260]
## I'm submitting a...
* Suggestion for improvement

## Current behavior

Currently, we do not have an option to customize a separator between start & end date inputs, but rather it renders a `<span>&nbsp;</span>`.

## Minimal reproduction of the problem with instructions
Can be seen in a simple example of usage
https://www.telerik.com/kendo-react-ui/components/dateinputs/daterangepicker/

We would like to have the possibility to render whatever between the inputs. Right now we don't have the ability to render even "-" between them.

**Comment by silviyaboteva** [comment]
Added in `3.5.0`. You can now have the ability to add date range picker separator using `daterangepicker.separator` message key: https://www.telerik.com/kendo-react-ui/components/dateinputs/globalization/.
