### ISSUE TITLE
[Bug][MultiSelect] Primitive data type should support `number` values

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#2601]
## I'm submitting a...
Bug report
## Current behavior
Currently, when we use a numbers array we have an error `t.text.replace is not a function` 

## Expected behavior
We should support `array []` data type.
https://www.telerik.com/kendo-react-ui/components/dropdowns/api/MultiSelectProps/#toc-data 

## Minimal reproduction of the problem with instructions

  1. Open it in Codesandbox example [HERE](https://codesandbox.io/p/sandbox/frosty-star-mxcz5q?workspaceId=d8efdd02-a74e-40b5-8444-7c4c22bdeb09 )
  3. Select any number value
  4. The error occurs 

Workaround available [HERE](https://codesandbox.io/p/sandbox/polished-http-k4m9gr?workspaceId=d8efdd02-a74e-40b5-8444-7c4c22bdeb09
)

Reported in ticket ID: 1668045

**Comment by silviyaboteva** [comment]
Duplicated bug. Closing in favor of https://github.com/telerik/kendo-react/issues/1389
