### ISSUE TITLE
Render Grid pager, top, bottom and both.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#263]
Provide a property that will allow the Grid pager to be rendered, at the bottom, at the top or at both places at the same time.

**Comment by simonssspirit** [comment]
Until the feature is ready, this can be achieved with a simple CSS rule:

````
    .k-grid-pager {
      order: -1;
      border-width: 0 0 1px;
    }
````

https://stackblitz.com/edit/kendo-react-grid-pager-on-top?file=index.html

**Comment by simonssspirit** [comment]
The item for the styles: https://github.com/telerik/kendo-themes/issues/767

**Comment by vladimirivanoviliev** [comment]
In latest official release the `Pager` component is exposed as stand-alone one which can be used to achieve the above behavior.
