### ISSUE TITLE
Grid customise grouping header

### ISSUE THREAD

**Issue by Tommuh** [telerik/kendo-react#2673]
Is it possible to customise the grouping header? 
For example, to change the chips and icons and context menu or is only styling possible using css?

![Image](https://github.com/user-attachments/assets/dec0128a-aead-487f-9536-de44dd5295d2)

https://www.telerik.com/kendo-react-ui/components/knowledge-base/render-a-custom-content-inside-the-grid-group-header/

**Comment by silviyaboteva** [comment]
Hello @Tommuh,

This repository is exclusively dedicated to addressing bugs, handling feature requests, and discussing product enhancements. If you need help with setting up a specific scenario or configuring a KendoReact component, please don't hesitate to open a ticket in our [support system](
https://www.telerik.com/account/support-tickets).

The article you mentioned explains how to render custom content inside the group header of the Grid, so feel free to use it in your scenario.

Although, you can customize the styles of the group header via CSS or Sass variables: https://www.telerik.com/design-system/docs/themes/kendo-themes/default/customization/
Here is the full list of Grid's variables: https://www.telerik.com/design-system/docs/components/grid/styles/
