### ISSUE TITLE
can i export pdf with different height in each page.

### ISSUE THREAD

**Issue by yellowjian** [telerik/kendo-react#269]
can i export pdf with different height in each page.

**Comment by simonssspirit** [comment]
@yellowjian The height of the page depends on its paperSize property, but this is applied to all pages for consistency. There is an **auto** option for the paperSize, which will make the exported pages with different size based on the content:

https://www.telerik.com/kendo-react-ui/components/pdfprocessing/api/PDFExportProps/#toc-papersize

**Comment by simonssspirit** [comment]
Closing the questions seems resolved. Please re-open if needed.
