### ISSUE TITLE
The value of the Grid pager input is not changed when changing the page with the arrows.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#27]
## I'm submitting a...

* Bug report

## Current behavior

The value of the Grid pager input is not changed when changing the page with the arrows.

## Expected behavior

The value has to be changed based on the newly selected page.

## Minimal reproduction of the problem with instructions

This can be observed in our demo: https://www.telerik.com/kendo-react-ui/components/grid/paging/#toc-paging

Browser:
All

System:
All

**Comment by simonssspirit** [comment]
The fix is available in the following dev version: v1.0.1-dev.201805231115

**Comment by mitagg** [comment]
The fix is available in the v1.0.1 version of the package.
