### ISSUE TITLE
[Bug][DropDowns] Popup detaches from the dropdown when the page is scrolled

### ISSUE THREAD

**Issue by Yanko-Georgiev** [telerik/kendo-react#2703]
## I'm submitting a...
* Bug report 
 
## Current behavior
When you open a dropdown and scroll outside of it, the popup detaches.

## Expected behavior
The popup should stay attached to the dropdown.

## Minimal reproduction of the problem with instructions
1. Open the following StackBlitz example: https://stackblitz.com/edit/react-zxeavr?file=app%2Fapp.tsx
2. Open the DropDownList and scroll outside of it.
3. Notice the popup detaches from the DropDownList.

Reported in: 1670752

**Comment by zdravkov** [comment]
Fixed in latest develop version of KendoReact - https://stackblitz.com/edit/react-zxeavr-hsrced?file=package.json
 Will be available in the next official release.
