### ISSUE TITLE
DatePicker/DateInput: change onInput -> onChange to remove React warning message

### ISSUE THREAD

**Issue by amoebaworks** [telerik/kendo-react#271]
## I'm submitting a Bug

* DatePicker & DateInput (@progess/kendo-react-dateinputs v3.2.0)
* React v16.8.6
* Chrome (desktop)

Using DatePicker, which uses DateInput, which uses onInput instead of onChange.

Generated DataInput code:
> React.createElement("input", __assign({ tabIndex: this.props.tabIndex, disabled: this.props.disabled, title: this.props.title || currentText, type: "text", spellCheck: false, autoComplete: "off", autoCorrect: "off", className: "k-input", id: inputId, onWheel: this.wheel, onClick: this.elementClick, **onInput: this.elementChange**, onKeyDown: this.elementKeyDown, value: currentText, name: name }, ariaProps, { ref: function (input) { return _this._element = input; } })),

The onInput causes:

> Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
    in input (created by DateInput)
    in span (created by DateInput)
    in span (created by DateInput)
    in DateInput (created by DatePicker)
    in span (created by DatePicker)
    in span (created by DatePicker)

Please change **onInput** to **onChange** to remove warning message.

**Comment by kspeyanski** [comment]
Hello, the issue has been fixed in the [3.2.1@dev](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#toc-321-dev201906121128) version of `@progress/kendo-react-dateinputs` and we will be publishing an official version shortly.

**Comment by amoebaworks** [comment]
Thanks for the quick turn-around! Got 3.2.1 and no longer see warning message.
