### ISSUE TITLE
Input label colour not changing properly with (in)validation

### ISSUE THREAD

**Issue by amoebaworks** [telerik/kendo-react#272]
## I'm submitting a Bug

* @progress/kendo-react-inputs v3.2.1
* React 16.8.6
* Chrome (desktop)

This example is contrived but illustrates the point:

```JSX
import React, { useState } from 'react'
import { Input } from '@progress/kendo-react-inputs'

export default (props) => {
  const [ value, setValue ] = useState('')

  return (
    <div>
      <Input id='1' value={value} label='Label' required />
      <Input id='2' value={value} onChange={event => setValue(event.target.value)} />
    </div>
  )
}
```

**Scenario 1:** Both inputs are empty. Input1's label & input box are red because it is invalid. Type **only 1 char** into Input2 to make Input1 valid. **Actual:** Input1's input box goes black but label stays red. **Expected:** label to be black too.

**Scenario 2:** Have a value in Input2 so that both Input1's label and input box is black. Delete Input2's value to make Input1 invalid. **Actual:** Input1's input box goes red but label stays black. **Expected:** label to be red too.

IIRC, this was working correctly in @progress/kendo-react-inputs v2.10.0

**Comment by amoebaworks** [comment]
Not sure if this the best way to fix, but this is way I found that works. In @progress/kendo-react-inputs/dist/es/Input.js:

```
        _this.setValidity = function () {
            if (_this._input && _this._input.setCustomValidity) {
                if (_this.validity.valid || !_this.validityStyles) {
                    _this._input.classList.remove('k-state-invalid')
                    if (_this.props.label) {
                      _this._input.parentElement.classList.remove('k-state-invalid')
                    }
                } else {
                    _this._input.classList.add('k-state-invalid')
                    if (_this.props.label) {
                      _this._input.parentElement.classList.add('k-state-invalid')
                    }
                }
                _this._input.setCustomValidity(_this.validity.valid
                    ? ''
                    : _this.props.validationMessage || '');
            }
        };
```

Added the `if (_this.props.label)` code to add/remove k-state-invalid to the enclosing span.k-textbox-container when there is a label.

**Comment by simonssspirit** [comment]
@amoebaworks Thank you for sharing this workaround.

We are aware that in some cases the validity state in standard HTML form has some limitations, which on the other hand create issues like this one when we try to work around them.

This is why we have created our own Form component which handles such cases more intuitively for React developers:

https://www.telerik.com/kendo-react-ui/components/form/
