### ISSUE TITLE
[Bug][DateInput] `formatPlaceholder` is not working in v9.0.0

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#2729]
## I'm submitting a...
* Bug report 
 
## Current behavior

The `formatPlaceholder` functionality is not working as of version 9.0.0 due to [this rendering change](https://www.telerik.com/kendo-react-ui/components/updates/rendering-changes/9-0-0#dateinput).

## Expected behavior
The DateInput should not interfere with the values that are not directly changed.

## Minimal reproduction of the problem with instructions
1. Open https://stackblitz.com/edit/react-skgvsp-ewtyb6?file=app%2Fmain.jsx
2. Click in DateInput and observe that the placeholder is not set

Expected: Repeat the same steps in v8.5.0 of the components here - https://stackblitz.com/edit/react-skgvsp-m5nqff?file=package.json 

## Additional information

Reported in: 1670841

**Comment by PaskalevStoyan** [comment]
Hi @nm-ivanbasic,

Can you please provide a reproducible demo as using [the demo](https://www.telerik.com/kendo-react-ui/components/dateinputs/dateinput/placeholders#format-sections-description) in our official documentation, the warning is not reproducible.
