### ISSUE TITLE
Batch file upload results in multiple files form parameters, leaving only the last file to be passed.

### ISSUE THREAD

**Issue by alxvallejo** [telerik/kendo-react#274]
I would expect that the file param is an array of files uploaded to the saveUrl, however the form data reveals multiple files params of binary data. Thus the last specified overwrites all the others.

You can confirm this behavior here: https://stackblitz.com/run/?file=app%2Fmain.jsx

By setting bulk to true and observing the formData in the network request.

**Comment by vladimirivanoviliev** [comment]
The request in question is valid and when we tested it with the  .NET MVC framework (as back-end) the collection was bind as expected. Could you please make sure the parameter at the back-end is array type and let us know of the result? In case it still doesn't work please share more info about what is your current sever framework as well as the current implementation that you use to handle the upload requests.


Here is example MVC implementation:
```
      public async Task<ActionResult> SaveAsync(IEnumerable<IFormFile> files)
        {
            // The Name of the Upload component is "files"
            if (files != null)
            {
                foreach (var file in files)
                {
                    var fileContent = ContentDispositionHeaderValue.Parse(file.ContentDisposition);

                    // Some browsers send file names with full path.
                    // We are only interested in the file name.
                    var fileName = Path.GetFileName(fileContent.FileName.ToString().Trim('"'));
                    var physicalPath = Path.Combine(HostingEnvironment.WebRootPath, "App_Data", fileName);

                    // The files are not actually saved in this demo
                    //using (var fileStream = new FileStream(physicalPath, FileMode.Create))
                    //{
                    //    await file.CopyToAsync(fileStream);
                    //}
                }
            }

            // Return an empty string to signify success
            return Content("");
        }
```

**Comment by Tommuh** [comment]
This problem still exists. 
When using PHP as backend the batch function doesn't work. 

The files are normally attached to "$_FILES" but the last file always overwrites the previous file.
