### ISSUE TITLE
[Bug][Grid] Hydration issue when using Grid with NextJS

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#2744]
## I'm submitting a...
* Regression Bug 

## Current behavior

Hydration issue when using Grid with NextJS

## Expected behavior

The warning doesn't show up.

## Minimal reproduction of the problem with instructions
1. add a gird to s simple NextJs project or run the one attached [in this ticket](https://supportheroes.telerik.com/ticket/1671846).
2. `npm install`
3. `npm run dev`

## Additional information

Internal issue: https://github.com/telerik/kendo-react-private/issues/4751 

Reported also in tickets: 1671846, 1671474

**Comment by PaskalevStoyan** [comment]
The bug is resolved and can be obtained via the develop version - `v9.1.0-develop.9`
