### ISSUE TITLE
Do not add "k-state-invalid" styling to the input when the form field is not touched

### ISSUE THREAD

**Issue by Smau5** [telerik/kendo-react#276]
## I'm submitting a bug/suggestion

React v16.8.6
Chrome (desktop)
Kendo-forms required validations

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Current behavior

When a field is required, but still not touched it gets styled as invalid

## Expected behavior

consistent approach for invalid, but untouched form fields across the themes.

**Comment by Xizario** [comment]
The `validityStyles` property can be used to disable the styles initially and you can enable them after touch/change/submit try, etc.. Adding this built-in will make the work of this property inconsistent, and it will have more limited use. At the current moment it is customizable and the desired behaviour can be achieved.

**Comment by Smau5** [comment]
ty for the solution! it makes sense.
