### ISSUE TITLE
Multi View Calendar Doesn't Change View If Value Is Set

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#277]
## I'm submitting a...
* Bug report

## Current behavior
Selecting a value in Multi View Calendar, then trying to change the date via another View, does not change the view.

## Minimal reproduction of the problem with instructions
This is reproducible on the demo site.
https://www.telerik.com/kendo-react-ui/components/dateinputs/multiviewcalendar

1. Click any date to set the value.
![image](https://user-images.githubusercontent.com/12272970/59990390-1f816780-9682-11e9-913f-bba00040484f.png)

2. Click the month at the top left to change "Zoom level" and Change month to February.
![image](https://user-images.githubusercontent.com/12272970/59990408-2e681a00-9682-11e9-9bc2-90858b077410.png)

3. The date will stay in June - July when it should now show February - March.

## What is the motivation or use case for changing the behavior?
Pressing the left and right month arrows is very inconvenient when trying to go back several months or years.

Browser:
- Chrome (desktop) version 75.0.3770.100 (Official Build) (64-bit)

**Comment by kspeyanski** [comment]
Hello @GeoMarkou ,
Thank you for reporting this.

We've published a `@dev` version of the `@progress/kendo-react-dateinputs` package with the fix, and an official version will follow shortly.

Please check the [changelog](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#toc-330-dev201906191342) and install the latest `@dev` version:
```
npm install @progress/kendo-react-dateinputs@dev
```
