### ISSUE TITLE
DatePicker in adaptive mode does not set date (kendo 9.1.0)

### ISSUE THREAD

**Issue by Jodelopa** [telerik/kendo-react#2770]
### Description

DatePicker in adaptive rendering mode does not set the date

### Steps To Reproduce

1. navigate on a small screen to your example at: https://www.telerik.com/kendo-react-ui/components/dateinputs/datepicker/adaptive-rendering
2. open picker (adaptive mode) and try to set or change a date

### Actual Behavior

no date set

### Expected Behavior

date should be set!

### Browser

Chrome, Safari, All

### Browser version

latest

### OS type

Windows, iOS

**Comment by PaskalevStoyan** [comment]
Hi, @Jodelopa ,

Thanks for bringing this to our attention. I've confirmed that this is a bug on our side. We will do our best to fix this as soon as possible.

Have a nice day!

**Comment by PaskalevStoyan** [comment]
Hi, @Jodelopa,

I'm happy to say that we fixed the bug and the DatePicker component works as expected in adaptive mode. The fix can be obtained in `v9.1.1-develop.2`.

Have a nice day!
