### ISSUE TITLE
[Bug][NumericTextBox] Received true for a non-boolean attribute `visited`/`touched`/

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#2774]
## I'm submitting a...

* Regression report 

When the  NumericTextBox is wrapped in a form field within a Kendo Form component it throws errors in the console where touched / visited / modified are attached directly to an HTML element as attributes. Setting the adaptive and adaptiveTitle props shows the following warnings in version 9.1.0:

```
Warning: Received `true` for a non-boolean attribute `visited`.
```
```
Warning: Received `true` for a non-boolean attribute `touched`.
```
Nevertheless, these props work as expected.
These warnings are not present in previous versions.

### Steps To Reproduce

1. Open https://stackblitz.com/edit/react-1wfsmq9u?file=app%2Fapp.jsx
2. Open the console and click inside the NumericTextBox
3. Observe the thrown warnings

### Screenshots or video

![Image](https://github.com/user-attachments/assets/d9ae6073-b9ef-42d6-a5ee-fc43f4dc87f1)

### Actual Behavior

When where we want to use a NumericTextBox wrapped in a form field within a Kendo Form component. However, this throws errors in the console where touched / visited / modified are attached directly to an HTML element as attributes. 

### Expected Behavior

No warnings shown.

### Browser

Chrome

### Browser version

latest

### OS type

MacOS

### Additional informaiton

Reported in Ticket ID: 1673477

Similar to https://github.com/telerik/kendo-react/issues/2272 and https://github.com/telerik/kendo-react/issues/2195

**Comment by silviyaboteva** [comment]
The fix is included in `v9.2.0-develop.2`.
