### ISSUE TITLE
Charts embedded in attachment of Conversational UI

### ISSUE THREAD

**Issue by IreneMarquet** [telerik/kendo-react#281]
Hello,

I'm doing a discovery and will like to know if is possible to embed Kendo React Charts and Grids into Kendo React Conversational UI, as we will like to have some responses in graphic visualization. 

Thanks in advance.

**Comment by Xizario** [comment]
Yes it is possible using the [messageTemplate](https://www.telerik.com/kendo-react-ui/components/conversationalui/message-templates/). 

Here is simple example:
https://stackblitz.com/edit/react-plzgwk

Let us know if you need further information.
