### ISSUE TITLE
Add page number to pdf export

### ISSUE THREAD

**Issue by nero2009** [telerik/kendo-react#283]
Is it possible to add page numbering to the pdf? if yes, how can I do this, please

**Comment by kspeyanski** [comment]
Hello @nero2009 ,
Yes, this can be done though the [`pageTemplate`](https://www.telerik.com/kendo-react-ui/components/pdfprocessing/api/PDFExportProps/#toc-pagetemplate) property of the `PDFExport` component, which receives the `pageNum` and `totalPages` as a properties.

I've prepared a stackblitz examples showcasing how this can be achieved: 
https://stackblitz.com/edit/react-tydde5

I'm closing this issue for now, but please let me know if you need further assistance.

**Comment by nero2009** [comment]
Thanks a lot @kspeyanski  for taking time to create that example.
