### ISSUE TITLE
Wrong charset on exported pdf, characters like éáçíãõ comes on another format.

### ISSUE THREAD

**Issue by iamferreirajp** [telerik/kendo-react#286]
## I'm submitting a...

* Documentation issue or request

## Current behavior
I'm trying to use the kendo-react-pdf savePDF method. The special characters like êçéã sent in the html parameter keep coming as ŒªÆØœ.

## Expected behavior

It should have retrieve the right characters after pdf download.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/react-kf1cev?embed=1&file=app/products.json

Attention to the first beverage name and the same name on the exported pdf.

## Environment

Package versions:

```
{
  "name": "u8vnlt.run",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "react": "16.8.6",
    "react-dom": "16.8.6",
    "@progress/kendo-react-pdf": "3.2.2",
    "@progress/kendo-react-grid": "3.2.2",
    "@progress/kendo-data-query": "1.5.1",
    "@progress/kendo-react-dropdowns": "3.2.2",
    "@progress/kendo-react-inputs": "3.2.2",
    "@progress/kendo-react-dateinputs": "3.2.2",
    "@progress/kendo-react-animation": "3.2.2",
    "@progress/kendo-react-popup": "3.2.2",
    "prop-types": "15.7.2",
    "react-transition-group": "4.2.1",
    "@progress/kendo-drawing": "1.5.12",
    "@progress/kendo-react-intl": "3.2.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "react-scripts": "latest"
  }
}
```

Browser:

- Chrome (desktop) Version 75.0.3770.100 (Official Build) (64-bit)

System:
- TypeScript version: none
- Node version: v8.10.0
- Platform:  Ubuntu

**Comment by Xizario** [comment]
If you declare no fonts, the PDF generator will fall back to the standard PDF fonts which support only ASCII characters.
For more information see this help article:
https://www.telerik.com/kendo-react-ui/components/drawing/pdf-output/embedded-fonts/

Here is modified version of your sample where I have added the fonts in `index.html`. Note that the rest part of the code is not changed:
https://stackblitz.com/edit/react-kf1cev-qsijhr?file=index.html

**Comment by iamferreirajp** [comment]
Thank you for the reply. Solved!
