### ISSUE TITLE
Incorrect group headers for the boolean column.

### ISSUE THREAD

**Issue by xarety** [telerik/kendo-react#287]
## I'm submitting a...
Bug report

## Current behavior
Empty group headers for boolean columns.

## Expected behavior
Group headers should be `true` or `false` for the boolean column.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-mrevpa?file=app/main.jsx

## What is the motivation or use case for changing the behavior?
Incorrect behavior.

**Comment by Xizario** [comment]
Please see this issue for explanation why it works this way and for possible resolutions: https://github.com/telerik/kendo-react/issues/53

**Comment by xarety** [comment]
What kind of additional information do you need?

**Comment by simonssspirit** [comment]
@xarety Sorry for the misleading tag, the idea of the tag is that we need a reply for the issue creator to see if this is resolved or not.

In this case, my colleague @Xizario suggested a possible solution, and we need more information if this was enough to resolve the case, or we need to provide additional assistance.
