### ISSUE TITLE
 Translation for sorting asc / desc is not working

### ISSUE THREAD

**Issue by AndreiF13** [telerik/kendo-react#288]
Hi,
translation for sorting (Sort Ascending / Sort Descending) is not working in column menu. (React UI)
Please check.
Thank you.

**Comment by simonssspirit** [comment]
@AndreiF13 Thank you for the report.

We have already fixed it.

I will let you know once we release a new version with the fix.

**Comment by AndreiF13** [comment]
Thank you!

**Comment by simonssspirit** [comment]
The fix is live

**Comment by maximMeta** [comment]
> The fix is live

What variables must be entered to change the names Sort Ascending / Sort Descending?

**Comment by vladimirivanoviliev** [comment]
You can use the `grid.sortDescending` and `grid.sortAscending` keys to translate the messages. More information can be found [here](https://www.telerik.com/kendo-react-ui/components/grid/globalization/#toc-messages)
