### ISSUE TITLE
Set max number of characters in GridColumn

### ISSUE THREAD

**Issue by JosipTomaic** [telerik/kendo-react#289]
I'm using React and I want to set max number of characters to 50 in GridColumn but I can't find any attribute that does that functionality.
Is there any attribute for GridColumn component that will set maximum number of characters?

Thanks in advance!

**Comment by Xizario** [comment]
@JosipTomaic I am not sure how this is expected to work. Currently the cells in the grid will display the text from your data items that are passed to the data property.

You need this to be trimmed to 50 characters? If this is the request, you can trim the data before passing it to the grid or during the rendering if you are using custom cell for the column. 

If this is not the case, please give us further details about the problem. An example of your grid, the data and what is expected to happen would be nice.

**Comment by JosipTomaic** [comment]
I have solved it by trimming data before passing it to the grid. Thanks for the advice.
