### ISSUE TITLE
The PanelBar keyboard navigation is not compatible with inputs and form inside the PanelBar. 

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#29]
* Bug report 

## Current behavior

Inputs do not allow spaces, and forms cannot be submitted when pressing enter.

This is caused by the keyboard navigation as it is listening for space and enter keypress events:

`   case Keys.space:
                action = NavigationAction.Toggle;
                break;`

 ` case Keys.enter:
                action = NavigationAction.Toggle;
                break;`

## Minimal reproduction of the problem with instructions

The issue can be observed in the following Plunker:

https://plnkr.co/edit/mgd7FRGLjAvWpEULu883?p=preview

## Environment

Package versions:
All
Browser:
All

**Comment by dalingrin** [comment]
I'm having the same issue and do not have a workaround.

**Comment by simonssspirit** [comment]
@dalingrin we are going to prioritize this in the next weeks.
@kspeyanski Please advise if we can offer a temporary workaround until the fix?

**Comment by mitagg** [comment]
@dalingrin - we have released a dev version of the layout package containing the fix for this issue. You could refer to the following article on how to obtain these development builds - https://www.telerik.com/kendo-react-ui/components/installation/development-builds/
