### ISSUE TITLE
Errors in MultiSelect tags

### ISSUE THREAD

**Issue by ZiedHf** [telerik/kendo-react#290]
Bug.
Version : 3.2.2 @progress/kendo-react-dropdowns

Description : 
The component does not show the selected options when tags are equal to an empty array.
(unless we set tags to undefined to make it work)

To reproduce the bug :
Link : https://stackblitz.com/run/?file=app%2Fmain.jsx
1- Replace the tags props value by an empty array : []
2- Select options

**Comment by nstoychev** [comment]
This behavior is by design. If you want to control the rendered tags, you should pass an array of tags. Empty array means no tags. If tags prop is undefined, the MultiSelect will manage the tags.

**Comment by ZiedHf** [comment]
@nstoychev I thought it's a bug because in the previous versions I use an empty array to let the multiselect manage the tags. Now I will use undefined instead.
Thanks for this clarification.
