### ISSUE TITLE
Input cursor position is incorrect when typing in numeric input filter value which is formatted

### ISSUE THREAD

**Issue by marcinkowal2015** [telerik/kendo-react#291]
## I'm submitting a...
Bug report

## Current behavior
When using a grid with numeric filter input, alter typing a value which results in formatting number e.g 1234 - fortmatted to -> 1,234. Input cursor is placed incorrectly e.g 1,23|4 , where | is cursor position

## Expected behavior

Cursor position should not change position and should be at the end of input e.g: 1,234| in described example

## Minimal reproduction of the problem with instructions

This behavior can be reproduced using example in official docs:
https://www.telerik.com/kendo-react-ui/components/grid/data-operations/odata-server-operations/
https://stackblitz.com/run/?file=app%2Fmain.jsx

Type in id filter value 1234

## What is the motivation or use case for changing the behavior?

Filtering big numeric values has very bad UX, as user is forced to notice that value is incorrect and then fix cursor position after each change which results in formatting value in input

## Environment

Package versions:

Ommiting as problem is reproducible on demo site

Browser:
Chrome (desktop) version 75.0.3770.100
IE version 11

however issue seems not to be browser related and was reproducible on other machines

System:
- TypeScript version: 3.3.4000
- Node version: node v8.12.0 npm 6.4.1
- Platform:  Windows

Issue seems to be related to rendering order, when data change triggers both changes to input element(numeric input field) and outer element (grid and/or loading indicator). In our production code it was found when we started usign hooks and there were a lot of states(separate for grid filters and sorting, separate for data and separate for loading indicator), as a workaround all states were merged to one object and it helped to fix this incorrect behavior

**Comment by vladimirivanoviliev** [comment]
Fixed in latest dev version `3.10.0-dev.202001150733`.
