### ISSUE TITLE
It is possible to enter incorrect numeric value in numeric input field 

### ISSUE THREAD

**Issue by marcinkowal2015** [telerik/kendo-react#292]
## I'm submitting a...
Bug report

## Current behavior

In numeric input field user is able to bypass validation and enter incorrect value e.g. (abc.)

## Expected behavior

Validation in numeric fields should not allow to enter incorrect values

## Minimal reproduction of the problem with instructions

Issue can be reproduced on demo pages:
https://www.telerik.com/kendo-react-ui/components/grid/data-operations/odata-server-operations/

In id filter input, type following characters:
- . (decimal separator)
- 'a' character - notice that after typing it cursor changes position before '.' and validation is triggered which is probably different bug, however needed step to reproduce, if that would not happen cursor is need to be placed manually before '.'
- text value which is incorrect e.g 'abc'

## What is the motivation or use case for changing the behavior?

Current validation is not restricting incorrect values, which results in separate additional check in logic to avoid errors

## Environment

Package versions:

Ommiting as reproducible on demo

Browser:

Chrome (desktop) version 75.0.3770.100
IE version 11

System:
- TypeScript version: 3.3.4000
- Node version: node v8.12.0 npm 6.4.1
- Platform: Windows

**Comment by vladimirivanoviliev** [comment]
Fixed in latest dev version `3.10.0-dev.202001150733`.
