### ISSUE TITLE
Datepicker unusable when inside Window

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#293]
## I'm submitting a...
* Bug report 

## Current behavior
Problem 1: The datepicker animates and opens behind the window.
Problem 2: When defaultshow is used the datepicker is not rendered correctly on page load

## Expected behavior
Datepicker should render correctly and not be behind the Window

## Minimal reproduction of the problem with instructions
Please see minimal demo:  https://stackblitz.com/edit/react-e6qjri

## What is the motivation or use case for changing the behavior?
Component is unusable

## Environment

Package versions:
3.2.2

Browser:

- Chrome (desktop) version 75 

Environment:
Windows

**Comment by simonssspirit** [comment]
@k290 This is due to the z-index of the Popup used in the DatePicker:

https://stackblitz.com/edit/react-e6qjri-rfwuvx?file=app/main.jsx

This is described here:

https://www.telerik.com/kendo-react-ui/components/popup/stack-order/

**Comment by k290** [comment]
Thanks. Sorry, did not realise that,
