### ISSUE TITLE
Grid without VirtualScroll affected by it

### ISSUE THREAD

**Issue by xarety** [telerik/kendo-react#294]
## I'm submitting a...
* Bug report

## Current behavior
After dynamic row addition, the table `DOM` element gets the `transform` style which brokes the behavior of the components with dropdowns.
![cur](https://user-images.githubusercontent.com/17852627/61291199-79370680-a7d6-11e9-8e14-983362d80f44.png)

## Expected behavior
Components with dropdowns should work correct independent of addition.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/kendo-virtual-scroll

1. Try to open dropdown for one of the last rows - everything would work correctly
2. Click the add button
3. Check dropdowns again - they will be broken

**Comment by nstoychev** [comment]
Fixed and published in version [3.9.0](https://k2build.openstack.progress.com/kendo-react-ui/components/changelogs/ui-for-react/#toc-390).
