### ISSUE TITLE
When datepicker icon is clicked, when inside the Window React wrapper, onmouseup the Datepicker reopens

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#295]
## I'm submitting a...

* Bug report 

## Current behavior

Logging the mouse-up issue separately as it seems to only be an issue when inside the Window Wrapper. 

## Expected behavior
When clicking the icon the calendar should remain closed. But as soon as you let go of the mouse it reopens

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-mlt3df

1. Click the calendar to open it
2. Click the calendar icon on the right side of the control to close it. Do not mouse up yet. You will see it closes.
3. Release your mouse. Calendar reopens
## What is the motivation or use case for changing the behavior?
Mouse-up should not reopen calendar

Also see video here:
https://www.loom.com/share/5b65c0ae18784c208b1e8e96afaad88a

## Environment

Package versions:
    "@progress/kendo-react-dateinputs": "3.2.2",
    "@progress/kendo-react-intl": "^2.7.0",
    "@progress/kendo-ui": "^2019.2.710",
    "@progress/kendo-window-react-wrapper": "^2019.2.606",
    "prop-types": "15.7.2",
    "react": "16.8.6",
    "react-dom": "16.8.6",

Browser:

- Chrome (desktop) version 75

System:
- Platform:   Windows >

**Comment by Xizario** [comment]
The logic that opens and closes the DateInput rely on React event mechanisms. The window wrapper is blocking them. 
We already have React Window in the Dialogs package:
https://www.telerik.com/kendo-react-ui/components/dialogs/window/
You can use it instead of the wrapper.

**Comment by k290** [comment]
@Xizario Unfortunately we have to use the wrapper since a legacy part of our application uses Kendo UI, so we use the wrappers to keep things consistent and prevent CSS conflicts

**Comment by simonssspirit** [comment]
@k290  Thank you for the details on why the wrapper Window is used.

The same result can be achieved with the native Window by rendering a single div element that will add the overlay:

https://stackblitz.com/edit/react-ivwabq?file=app/main.jsx

As this is a valid feature, I will convert this to enhancement, and add this as a configurable property to the Window component.

Please let me know if this removes the need to use the wrapper?

**Comment by k290** [comment]
@simonssspirit Yes this will remove the need to use the wrapper and we would then be able to migrate away from it

**Comment by simonssspirit** [comment]
This is already in the dev channel: https://www.telerik.com/kendo-react-ui-develop/components/dialogs/api/WindowProps/#toc-modal

**Comment by k290** [comment]
Thanks!
