### ISSUE TITLE
Calendar/DateRangePicker: allow hiding tooltip/formatting tooltip content

### ISSUE THREAD

**Issue by tif-p-st** [telerik/kendo-react#298]
## I'm submitting a...

Suggestion for improvement

## Current behavior

When hovering over a date on the Calendar component, a tooltip always displays and there seems to be no way to hide it/format the content.

## Expected behavior

Provide an API to hide the tooltip or format the content.

## Minimal reproduction of the problem with instructions

1. Open the Calendar/Date Range Picker sample: https://www.telerik.com/kendo-react-ui/components/dateinputs/daterangepicker/custom-rendering/
2. Open the date range picker control and hover over any date on the Calendar control to open the tooltip showing the date.

## What is the motivation or use case for changing the behavior?

I want to allow users to select a date range from the control, and the date range will be repeated every year so I don't want to show any year related information. I am able to apply a custom `headerTitle` through the `calendarSettings` to hide the year info, and I am able to limit the min and max dates to Jan1 - Dec1 of the current year. However, there seems to be no way to format to not show the year info, or to hide the tooltip completely. Thanks in advance for looking into this enhancement request.

## Environment
(the problem is reproducible on the demo site)
```
    "react": "16.8.6",
    "react-dom": "16.8.6",
    "@progress/kendo-react-dateinputs": "3.2.2",
    "@progress/kendo-react-intl": "3.2.2",
    "@progress/kendo-react-tooltip": "3.2.2",
    "@progress/kendo-react-common": "3.2.2",
    "@progress/kendo-react-popup": "3.2.2",
    "@progress/kendo-date-math": "1.4.1",
    "@progress/kendo-react-dropdowns": "3.2.2",
    "prop-types": "15.7.2",
    "react-transition-group": "4.2.1"
```

Package versions:

```

```

Browser:
- Chrome (desktop) version 75.0.3770.100

System:
- Platform:  Windows

**Comment by kspeyanski** [comment]
Hello @tif-p-st 

This tooltip you're seeing on cell hover is the default browser tooltip which is initialised when an element has a `title` property.

The title property of the `CalendarCell` can be changed by providing a `cell` property to the Calendar, and a `title` property to the provided `CalendarCell`.

I've prepared the following example demonstrating how to change `title` (which will reflect on what is displayed in the tooltip) to show only the `day/month` part of the selection. To completely remove the title, simply set the `title` property to `undefined`.

[Calendar Custom Cell Title Example](https://stackblitz.com/edit/react-ajmfpp)

Please let me know if this is what you're looking for.

**Comment by tif-p-st** [comment]
Thanks for your prompt response, @kspeyanski, this is exactly what I am looking for! Big kudos to you and the rest of your team!!
