### ISSUE TITLE
Add a detailRowHeight prop for the Grid.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#299]
Add a detailRowHeight prop for the Grid.

This property can be useful for virtualized Grid and can be set together with the rowHeight property.

A similar setup is available in the Kendo UI for Angular as well:

https://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-detailrowheight

**Comment by WissamProgress** [comment]
https://www.telerik.com/kendo-react-ui/components/grid/api/GridProps/#toc-detailrowheight
