### ISSUE TITLE
Grid - Filterrow - selecting operator triggers filtering & makes wide tables unusable

### ISSUE THREAD

**Issue by jannhofman** [telerik/kendo-react#30]
## I'm submitting a...

* Bug report 

## Current behavior
Create a table, resize a column - sidescrolling activates, and select in "Unit Price" e.g. "less than"
![bug1](https://user-images.githubusercontent.com/37375676/40672637-aa871b28-636f-11e8-8469-3a72dda0ec62.PNG)
![grafik](https://user-images.githubusercontent.com/37375676/40672658-bd8eddd2-636f-11e8-8f1a-1bf213f6407a.png)

Changing the operator, without having any filter value triggers the filter, the result is empty and the scrollbar disapears. The user cant even reset oder change the filter in this case.

## Expected behavior
We have 2 Issues.
- filtering should not trigger if there is no value.
- even in a table without rows, only displaying the table header, scrolling has to be possible

## Environment
Package versions: 1
Browser: Firefox

**Comment by Xizario** [comment]
Changing the operator triggers filter always for some reasons:
- Some operators works without value: isNull, isNotNull, isEmpty etc.
- The programmer could handle the filter event and decide if he wants to process the new filters or not. Modify the value automatically or to ignore them. Thus the coder have full control.
- Empty input is still a value for the string columns. 
- You could could always set back the `filter` prop to the grid, without new `data` prop.
- If we fire events conditionally

The second one is real issue. We will fix it by adding ensuring the width of the data container is set even if there is no data to match the header.

**Comment by jannhofman** [comment]
Yeah, you are right its in between. We have full control, so i will add some consistency checks in the callback.

**Comment by Xizario** [comment]
We have added empty message, localizated by default, and can be further customized with custom components using the <GridNoRecords> inside the Grid. It is spanned thru the whole body of the grid, so the scroll will not disappear anymore after filtering returns empty data.

Will be available shortly in next uploaded [dev version](https://www.telerik.com/kendo-react-ui-develop/components/installation/development-builds/).
