### ISSUE TITLE
Need a way to compare two JSON strings and/or objects and highlighting the differences.

### ISSUE THREAD

**Issue by Pryorite** [telerik/kendo-react#301]
Need a way to compare two JSON strings and/or objects and highlighting the differences.

Something like this https://www.npmjs.com/package/react-gh-like-diff

**Comment by simonssspirit** [comment]
@Pryorite KendoReact is a UI library that provides UI components for React, like Data Grid, Charts, Editors and many others. The described functionality can be achieved using a third-party tool.

Is there anything we can assist regarding the KendoReact components?

**Comment by Pryorite** [comment]
> @Pryorite KendoReact is a UI library that provides UI components for React, like Data Grid, Charts, Editors and many others. The described functionality can be achieved using a third-party tool.
> 
> Is there anything we can assist regarding the KendoReact components?

I guess not if you guys will or are not going to build a component that will do this or don't have any components currently that will compare json and highlight differences.  I was trying to use you guys more, but that doesn't look like an option.

**Comment by rafdy-rayan** [comment]
@Pryorite did you find a solution? i am looking for the same thing

**Comment by Pryorite** [comment]
> @Pryorite did you find a solution? i am looking for the same thing

We ended up going with react-diff-viewer and have been using it for a couple years now with no issues.

**Comment by rafdy-rayan** [comment]
okay thank you!
