### ISSUE TITLE
NumericTextbox does not remove trailing zeroes when losing focus

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#302]
## I'm submitting a...

* Bug report 

## Current behavior
If the supplied format is n2, and the number in the textbox can be set to 12.9900. The decimal format should  be obeyed. See the Kendo UI or React Wrapper numeric textbox. When you click out of the NumericTextBox in Kendo UI the trailing zeroes are removed. 

## Expected behavior

Similar to Kendo UI it should remove the trailing zeroes to obey the format when focus is lost.
Or similar to the Kendo React wrapper it should remove the trailing zeroes as the user types.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-vgvrdb?file=app/main.jsx

Follow these steps in the above demo:
1. Position cursor after the '.'
2. Type 99
3. Click outside textbox to lose focus
4. 12.9900 remains displayed

See below video comparing functionality of Kendo React to Kendo UI/wrappers

https://www.loom.com/share/f188d8fc18d3420c816680645f8cc722

First example is Kendo React Wrapper
Second example is Kendo UI
Third example is Kendo React

## What is the motivation or use case for changing the behavior?
Two reasons:
1. Supplied format should be obeyed. Makes the user think that more decimal places are stored than are allowed.
2. Consistency for users as we migrate away from Kendo UI  React wrappers  to the native Kendo components

## Environment

Package versions:
    "react": "16.8.6",
    "react-dom": "16.8.6",
    "@progress/kendo-react-inputs": "3.2.2",
    "@progress/kendo-react-intl": "3.2.2",

Browser:

- Chrome (desktop) version 75

**Comment by simonssspirit** [comment]
@k290 The NumericTextBox has planned a major focus for improvement soon after the newly planned Scheduler component is ready.

We will try to address all of the issues in that revision.

**Comment by vladimirivanoviliev** [comment]
Fixed in latest dev version `3.10.0-dev.202001150733`.
