### ISSUE TITLE
Date range picker - support customized keyboard navigation

### ISSUE THREAD

**Issue by tif-p-st** [telerik/kendo-react#304]
## I'm submitting a...

Suggestion for improvement

## Current behavior

As described in [the doc](https://www.telerik.com/kendo-react-ui/components/dateinputs/calendar/keyboard-navigation/), Currently in the `DateRangePicker` input, if I press the right arrow key, it sets the focused day to 1 day after the date range's start date. If I press the left arrow key it takes the focused day to 1 day before the start date.

## Expected behavior

I want to be able to override the keyboard navigation behavior. For example, if I have selected 5 days (Aug1 - Aug5) from the `DateRangePicker`, I want to capture the right arrow key press so I can shift the `SelectionRange` to a new 5-day window with the new start day = the previous end date (i.e. Aug5 - Aug10). Similar I want to use the left arrow key press to shift to a previous date window.

## Minimal reproduction of the problem with instructions

Can be reproduced using the sample [here](https://www.telerik.com/kendo-react-ui/components/dateinputs/daterangepicker/keyboard-navigation/)

## What is the motivation or use case for changing the behavior?

I want to be able to quickly select a date range by shifting the time window without reselecting an entire date range

## Environment

Browser:

- Chrome (desktop) version 75.0.3770.142

System:
- Platform:  Windows

**Comment by kspeyanski** [comment]
Hello @tif-p-st ,

The provided scenario can be achieved by providing a [`CustomCalendar`](https://www.telerik.com/kendo-react-ui/components/dateinputs/api/DateRangePickerProps/#toc-calendar) Component to the `DateRangePicker` and handle the `onKeyDown` event.

I've prepared the following StackBlitz example demonstrating how it can be achieved with the current set of features of the `DateRangePicker`:

https://stackblitz.com/edit/react-fxgajv?file=app/main.jsx

If the following approach does work for you, please let us know and we would be happy to discuss what features are needed to achieve it.

Greetings,
Kiril

**Comment by tif-p-st** [comment]
Thank you for your quick reply @kspeyanski ! Your sample works exactly as what I expected. Thank you and your team for building this really great library!
