### ISSUE TITLE
AutoComplete does not have a way to programatically set focus

### ISSUE THREAD

**Issue by PaulInglis** [telerik/kendo-react#305]
## I'm submitting a...

* Bug report 

## Current behavior

When programatically setting the focus of to the AutoComplete it appear to have any way to do it, other than clicking or touching on to the field (maybe tabbing too.

## Expected behavior

To be able to set the focus via a `focus()` method

## Minimal reproduction of the problem with instructions

I have recreated a working example to show how an in put handles setting focus and then when the same is attempted for an AutoComplete how it fails and causes an error
https://stackblitz.com/edit/react-dqhc9l

## What is the motivation or use case for changing the behavior?

I need after a user has entered details into a form for the focus to go back to the autocomplete, so they can continue entering more information, without having to click back to the control.  This is essential for rapid, keyboard only data entry

Browser:
any

System:
- TypeScript version: 3.5.1 
- Node version: 10.16.0  
- Platform: Windows

**Comment by vladimirivanoviliev** [comment]
We are planning to expose the focusable element of each component on it's `ref`, however this change is planned for after current release (expected at mid September). Until this element is exposed you can use the following workaround:
* https://stackblitz.com/edit/react-1ux1vr?file=app/main.jsx

**Comment by vladimirivanoviliev** [comment]
@siliconeidolon Why are you confused? How you would like to focus our components? We choose to expose the element as is this is the way the native components are focused in React.

**Comment by nstoychev** [comment]
Currently, the autocomplete provides its HTML element and the component can be focused using it:
`autocomplete.element.querySelector('input').focus();`

After exposing a focusable element, the focusing will be:
`autocomplete.focusableElement.focus();`

I don't see much difference.

**Comment by nstoychev** [comment]
@PaulInglis - Here is how the AutoComplete can be focused programmatically: https://stackblitz.com/edit/react-cjkps6.

**Comment by vladimirivanoviliev** [comment]
All formComponents have `focus` method on their reference which can be used for focusing it. Can be checked in latest dev version `3.7.x`.
