### ISSUE TITLE
Grid - customizing a tr

### ISSUE THREAD

**Issue by jannhofman** [telerik/kendo-react#31]
## I'm submitting a...
* Suggestion for improvement

## Expected behavior

We would like to have more control over the tr for two reasons. 
- Attaching additional Event Handler
- Adding CSS Classes 

In our case we have an implementation for single click, double click, right click and on top of that shift & strg click zu manage all possible ways of selecting rows. i can attach them to the cells by using custom cells, but is painful to do.
Same for css - sometimes possible by using cumstomcells. Our use case for this, is changing the border on specific table rows - depending on the dataitem - to implement some sort of visual grouping.

**Comment by andreastoermer** [comment]
Works perfect. Thanks for this informations. Maybe you can put an example on your website outside of the Editing, so other can find it easier than we do.

**Comment by simonssspirit** [comment]
The article is added: https://www.telerik.com/kendo-react-ui-develop/components/grid/styling/
