### ISSUE TITLE
Grid filter options appear underneath parent dialog

### ISSUE THREAD

**Issue by DavidWFarley** [telerik/kendo-react#310]
## I'm submitting a...
* Bug report

## Current behavior
When a Grid is included inside a dialog and filters are enabled, clicking on a drop down list displays a list of options beneath the dialog.  If the dialog is large enough, it completely obscures the menu.

## Expected behavior
Filter options should appear above a dialog when they are children of that dialog.

## Minimal reproduction of the problem with instructions
Just take the filter example, add: import { Dialog} from '@progress/kendo-react-dialogs'; Then add a Dialog tag wrapping the grid.  Click on any of the filter buttons/drop downs to observe the behavior.

## What is the motivation or use case for changing the behavior?
Filters aren't operable inside a dialog unless this is fixed.

## Workaround
I was able to work around this issue by applying the following CSS:

.k-list-container {
    z-index: 9999999 !important;
}

```

Browser:
- Chrome (desktop) Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by simonssspirit** [comment]
@DavidWFarley This is expected as in the current version of the Popup the z-index is not calculated dynamically. More details can be found here:

https://www.telerik.com/kendo-react-ui/components/popup/stack-order/

We have a task to improve the Popup behavior added in our ToDo list.
