### ISSUE TITLE
Regression: Some propTypes typings are not correct

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#311]
* Regression report 

## Current behavior
Error "types of property 'propTypes are incompatible" when using Prop typings for a generic HOC
![image](https://user-images.githubusercontent.com/5611876/63168616-f4d5de80-c034-11e9-970e-70db51239514.png)

## Expected behavior
Typings should be correct

## Minimal reproduction of the problem with instructions
1. Pull down https://github.com/k290/kendo-timepicker-issue and pull to latest commit
2. Run npm install in root directory
3. Open in VS Code
4.  Open "src/components/withValidation.component.tsx"

Observe that the affected components are:
DateInput
DatePicker
TimePicker
Combox
DropdownList
MultiSelect
MaskedTextbox

While AutoComplete, NumericTextBox and Input are fine

This used to be working in Kendo React version 2.11
  
Package versions:
    "@progress/kendo-react-dateinputs": "3.2.2",
    "@progress/kendo-react-dropdowns": "3.2.2",
    "@progress/kendo-react-inputs": "3.2.2",
    "@progress/kendo-react-intl": "3.2.2",
    "@types/react": "16.9.2",
    "@types/react-dom": "16.8.5",
    "react": "16.8.6",
    "react-dom": "16.8.6"

System:
- TypeScript version: 3.5.3
- Node version: 10.15.1
- Platform:  Windows

**Comment by simonssspirit** [comment]
Thank you for the example.

Wha we could suggest is using the following format for the withPipValidation component.

`const withPipValidation = <P extends Object>(Component: typeof React.Component) =>`

If this is not possible in the application, please let us know and we will research further.

**Comment by k290** [comment]
Thanks. I'll have a look  next week and let you know if that works for us

**Comment by k290** [comment]
No that doesn't work. If you do that in the example you get a typescript error in rendering <Component> ("no construct or call signature") and errors passing all the kendo components into the HOC ("argument of type DateInput is not assignable to paramater of type Component<{},{},any?"). Even If upgrading to the latest typescript

**Comment by k290** [comment]
Ok changing it to React.ComponentType instead of React.Component works

**Comment by k290** [comment]
I think you meant Component: typeof React.ComponentType which does work for us. Thanks

**Comment by k290** [comment]
Think you meant `const withPipValidation = <P extends Object>(Component: typeof React.ComponentType)`

This does work for us as we still get the strong typing when using the wrapped component e.g. <PipDropDownList>  on the props that are specified in the props objects at least e.g (DropDownListProps)
