### ISSUE TITLE
Disable source maps generation

### ISSUE THREAD

**Issue by kspeyanski** [telerik/kendo-react#313]
Hey Team,
This issue was raised in a couple of support tickets, so i suggest we discuss it further.

The source maps files are unusable if the original source code is not available.

The only benefit of having them by default is if the developer has obtained the source code and build the distribution by himself. Then linking the package through `npm link` rather than getting it trough npm.

Another possible solution is keep the build as it is, but do not publish the js.map files to npm.

Looking forward your suggestions

**Comment by Xizario** [comment]
Up!
