### ISSUE TITLE
Kendo Grid uses the lifecycle method componentWillReceiveProps, which is deprecated

### ISSUE THREAD

**Issue by siliconeidolon** [telerik/kendo-react#318]
## I'm submitting a...
* Bug report

## Current behavior
React will generate warnings related to the use of componentWillReceiveProps in the Grid component:

```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: KendoReactGrid
printWarning @ react-dom.development.js:12029
```

## Expected behavior
No warnings when using the component. The lifecycle method should be prefixed with `UNSAFE_` or replaced with a non-deprecated method.

## Minimal reproduction of the problem with instructions
Use grid component in an environment that will show React warnings - eg: locally, using `npm start` in a Create React App project and view the error in the browser console.

## What is the motivation or use case for changing the behavior?
`componentWillReceiveProps` is deprecated and will stop working in React version 17+

## Environment

Package versions:
```
 "@progress/kendo-react-grid": "^3.2.2",
```

Browser:
- Chrome (desktop) version 76.0.3809.100 (Official Build) (64-bit)

**Comment by nstoychev** [comment]
Fixed in version 3.12.0.
