### ISSUE TITLE
Locked prop doesn't work for multi column headers

### ISSUE THREAD

**Issue by xarety** [telerik/kendo-react#319]
## I'm submitting a...
* Bug report

## Current behavior
Locked prop working only on leaf columns

## Expected behavior
Locked prop working for all columns

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-bidzf2
Product column scrolling however it's locked

**Comment by simonssspirit** [comment]
Reported again in 1451403
Raising priority.

**Comment by simonssspirit** [comment]
The second user reported it on the ticket: 1451403

@nstoychev @Xizario  Please take a look at this and advise if we can plan it for the next release.

**Comment by nstoychev** [comment]
@xarety - The issue is fixed in our dev channel, version 3.12.0-dev.202003091534.

https://stackblitz.com/edit/react-bidzf2-yvujty?file=app/main.jsx
