### ISSUE TITLE
Export PDF don't support Arabic language

### ISSUE THREAD

**Issue by EmanMohammad** [telerik/kendo-react#32]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by eeasss** [comment]
Hey Eman,

Unfortunately we cannot add support for Arabic atm. Unfortunately OpenType.js that we internally use to render the letters in the PDF does not fully support the different shapes Arabic letters can take, depending on the surrounding letters.

Should the support gets better int he future we will consider it.

**Comment by joseprakash1990** [comment]
@eeasss Hi KendoReact Team, is there any update regarding Arabic font support in PDF export?
