### ISSUE TITLE
Pass Props to pageTemplate

### ISSUE THREAD

**Issue by nero2009** [telerik/kendo-react#323]
Please is it possible to pass props to the pageTemplate props. I need to pass some data that will be as a template for the pdf or am I limited to only The number of the current page (pageNum) and the total number of pages (totalPages) ?

**Comment by nstoychev** [comment]
Here is how you can extend the PageTemplate component with additional props: https://stackblitz.com/edit/react-r2awq2?file=app/main.jsx

**Comment by cozziad** [comment]
This example seems to only work though for static data. What if you want to dynamically load data into the pageTemplate component?

It seems like you can't pass dynamic data via the props to pageTemplate or load it in the pageTemplate as it is rendered straight away before data returns.

**Comment by Xizario** [comment]
@cozziad You can pass everything and change it dynamically, as in regular react component. Here is modified version of the example with property that changes:
https://stackblitz.com/edit/react-r2awq2-3cxzqv?file=app/main.jsx

**Comment by cozziad** [comment]
That did it, thank you!

**Comment by Naveenkant93** [comment]
Hi, I have a query related to the mentioned thread. I have to print 20/30 users' data in one pdf. Some users can have one page some can 2 and so on. I want UserName in the header and Employee Id in the bottom of every page. Can we handle this?   

Kindly help.
