### ISSUE TITLE
Collapse groups by default

### ISSUE THREAD

**Issue by JosipTomaic** [telerik/kendo-react#324]
I have seen example in jQuery how to collapse groups by default on this link:
https://docs.telerik.com/kendo-ui/knowledge-base/grid-collapse-groups

How it can be done in Reactjs?

I have tried to find example in react for this scenario but I haven't managed to find it.

Any help or advice is appreciated. Thanks in advance.

**Comment by nstoychev** [comment]
The expand/collapse state of each group is controlled by the value in each data item expand field. Here is an example for collapsing all groups initially - https://stackblitz.com/edit/react-uewe2d?file=app/main.jsx

You should loop through the data items and set `false` to their `expand` field. In the example above, it is `dataItem.expand = false;`

**Comment by JosipTomaic** [comment]
thanks :)
I couldn't find what field should be set on data items to collapse them.
This helped a lot.
