### ISSUE TITLE
Closeable tab

### ISSUE THREAD

**Issue by amerkoleci** [telerik/kendo-react#325]
## I'm submitting a...
* Documentation issue or request

## Current behavior
The TabStripTab has a title which is of type string.

## Expected behavior
Would like to have close 'X' button to allow closing tabs when pressed.

## Minimal reproduction of the problem with instructions
None

## What is the motivation or use case for changing the behavior?
Need to have dynamic pages being loaded and allow user to close the unwanted tabs, then they are persisted somewhere.

## Environment

Package versions:

```

```

Browser:
- Chrome (desktop) version 76.0.3809.132 x64.

System:
- Node version: v10.16.0 & 6.11.3
- Platform:  Windows

**Comment by simonssspirit** [comment]
This is live: https://www.telerik.com/kendo-react-ui/components/layout/tabstrip/tabs/#toc-closable-tabs
