### ISSUE TITLE
Make the onMessageSend event in the Conversation UI preventable.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#330]
Make the onMessageSend event in the Conversation UI preventable.

The use case is the following - Make a local and server validation of the message before adding it. In the current case, we can make validation, but the actual message will be lost, and the user has to retype it again.

**Comment by Xizario** [comment]
Preventing the event will not fix the async validation of the message. For example the user can type several messages before the first one gets validated. If one prevent the event and wait for server response he will just freeze the client side app. 
Better approach will be to correct the binding data for the client (merge server side with client side) data and updating the component.
