### ISSUE TITLE
The labels of the input components are not affected by the rtl prop.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#332]
The labels of the input components are not affected by the rtl prop.

The text inside the input components respects the dir="rtl" prop, but their labels do not.

https://stackblitz.com/edit/react-mkmiv6-quvh7g?file=app/main.jsx

This affects the Input, the MaskedTextBox, and the NumericTextBox.

**Comment by Xizario** [comment]
I see @kspeyanski already fixed this in upcoming dev.

But as part of the discussion:

> Setting `dir` for component without children does not change the layout and at the same time breaks the correct work of unicode-bidi.
Use `<body dir="rtl" class="k-rtl">` to forget issues, and never place `dir` inline.

On a side note, my personal opinion is `k-rtl` should be left entirely for the developer to place it whenever he decides, and we should be theme independent.

**Comment by Xizario** [comment]
Fixed in `3.5.0`
