### ISSUE TITLE
Slider Doesn't Snap to Steps

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#335]
## I'm submitting a...
* Bug report

## Current behavior
Dragging the handle of the Slider can leave you half way between two steps.

## Expected behavior
The slider should snap to the closest step to the cursor.

## Minimal reproduction of the problem with instructions
Compare the two links

https://www.telerik.com/kendo-react-ui/components/inputs/slider/controlled/
https://www.telerik.com/kendo-react-ui/wrappers/inputs/slider/steps/

In the old wrapper, when dragging the slider, it would snap to 21, 22, 23, etc. In the new Slider, you can end up with 2.58283 if you let go halfway between a step.

## What is the motivation or use case for changing the behavior?
We have many sliders on a page which is used to show someone's system access. It can be level 1, 2, 3, or 4. It worked well with the old Wrapper but we would like to upgrade to the full React component since it's been released.

Browser:
- Chrome (desktop) version 77.0.3865.90 (Official Build) (64-bit)

**Comment by Xizario** [comment]
It is by design. Snapping can be easily done if you round the number in controlled mode.

**Comment by simonssspirit** [comment]
This is expected behaviour as the Slider always returns the precise value.

In this case, I can suggest using Math.Round on the onChange event to get a whole number:

https://stackblitz.com/edit/react-8ta5y7?file=app/main.jsx

**Comment by rendmath** [comment]
This is trivial to implement, especially for simple cases (step are evenly spaced).

Nevertheless, that's an expected feature for any slider component, especially from a commercial library. And it makes the onChange event harder to work with. Please reconsider this and add a "snap" mode.
