### ISSUE TITLE
Clicking the Now button in the DateTimePicker does not set the current time.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#336]
Clicking the Now button in the DateTimePicker does not set the current time.

When the button is clicked, the time is set to the one currently selected in the picker, not to the current time.

This can be observed in our demo:

https://www.telerik.com/kendo-react-ui/components/dateinputs/datetimepicker/#toc-basic-usage

**Comment by vladimirivanoviliev** [comment]
Fixes in latest official release.
