### ISSUE TITLE
KendoReact all script error in version 3.4.1*

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#337]
KendoReact all script error in version 3.4.1*.

The script trowns an error as it has a dependency on date-math.

Importing the date-math will not resolve the issue as date-math depends on the tslib package, which does not have a UMD distribution.

**Comment by Xizario** [comment]
This will work correctly `@progress/kendo-date-math`, `1.5.0` version is published

**Comment by nstoychev** [comment]
[`@progress/kendo-date-math -1.5.0` version](https://github.com/telerik/kendo-date-math/releases/tag/v1.5.0) is published.

**Comment by simonssspirit** [comment]
The fix is actually available in 1.5.1
