### ISSUE TITLE
The Grid wrapper filterMenuOpen event is not fired.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#34]
## I'm submitting a...

* Bug report 

## Current behavior

The Grid wrapper filterMenuOpen event is not fired.

## Expected behavior

The event is fired in the jQuery version.

## Minimal reproduction of the problem with instructions

This can be observed in the following example: https://plnkr.co/edit/gLYYUOI93nr0FDm7959A?p=preview

## Environment

Package versions:

Browser:
All
System:

**Comment by zenit1scada** [comment]
+1

**Comment by simonssspirit** [comment]
The same issue occurs for the columnMenuOpen event

**Comment by simonssspirit** [comment]
fix: https://github.com/telerik/kendo-react-wrappers/pull/149/commits/293842d890a5cb483f6c16b8c40fa7b452193bad

**Comment by simonssspirit** [comment]
fix is live and available in version: 2018.2.612
