### ISSUE TITLE
Editing a Grid breaks the selection of the second Grid

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-react#341]
If the page contains two identical Grids by following the approach from the documentation - https://www.telerik.com/kendo-react-ui/components/grid/editing/editing-in-cell/, and the user edits a cell in one of them - the selection of the second one breaks.

This can be observed here - https://stackblitz.com/edit/react-yff3li?file=app/main.jsx

The same behavior looks good in inline edit mode - https://stackblitz.com/edit/react-cevsfa?file=app/main.jsx

**Comment by Xizario** [comment]
Adding this to the renderer should resolve it:
```jsx
 let inputP = input;
 while(inputP && inputP !== document.activeElement){
     inputP = inputP.parentNode;
 }
 if (inputP!== document.activeElement){
     return;
 }
```
https://stackblitz.com/edit/react-yff3li-1mev1h?file=app/renderers.jsx

Can be cleared a bit before updating the docs.
