### ISSUE TITLE
Slider need some improvements

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-react#342]
Some issues:

* Slider does not implement formComponents interface
* Values outside the min-max range are displayed outside the scale. Including null value.

**Comment by vladimirivanoviliev** [comment]
@Xizario What about the first point?

**Comment by InaGlushkova** [comment]
The Slider is implementing the FormComponent interface and it is working as expected.
For reference, check here:
[https://stackblitz.com/edit/react-xz56dt-qyytln?file=app/form-components.jsx](https://stackblitz.com/edit/react-xz56dt-qyytln?file=app/form-components.jsx)
