### ISSUE TITLE
Pressing enter in the MultiSelect when the typed value is not in the data causes a JS error

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#345]
Pressing enter in the MultiSelect when the typed value is not in the data causes a JS error.

This can be observed in our demo: 

https://www.telerik.com/kendo-react-ui/components/dropdowns/multiselect/filtering/

**Comment by silviyaboteva** [comment]
Also, if you enter a non-existing value and press enter, it will select the first value in the dropdown. - https://telerik.com/kendo-react-ui/components/dropdowns/multiselect/

**Comment by Xizario** [comment]
Fixed in `3.5.0`
