### ISSUE TITLE
Popup component children ignore provided context value on first render

### ISSUE THREAD

**Issue by oceantume** [telerik/kendo-react#347]
## Current behavior
When using a context `Consumer` in the children tree of Kendo's `Popup` component, the context value will be the default context value (the value passed to `React.createContext()`) on first render instead of the value provided by a context `Provider` higher in the tree. A second render is done soon after with the right provided context value, but if the default context is invalid (which is often the case when we assume that a provider should be present), the application can get into an unexpected state or even crash in some cases.

## Expected behavior
The context `Consumer` should always receive the value set by the `Provider` on every render.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-nqwaey?file=app%2Fmain.jsx

## What is the motivation or use case for changing the behavior?
This may not always have apparent effects, but in the worst cases it leads to unexpected application state or even application crashes. The most obvious use-case where this is problematic is when using StyledComponents themes.

## Environment

Browser:
- Chrome (desktop) version 77.0.3865.90
- Firefox version 69.0.1
- Edge version 44.18362.329.0

System:
- Platform:  Windows

## Additional details
This is possibly an issue with the way Popup is implementing its React portal. This may also be a problem if the same implementation is used for portals in other Kendo components.

**Comment by oceantume** [comment]
Additionally, here's a workaround I have found to work that will ensure the Popup's children are not rendered whenever context providers are ignored.

```
import React, { FC, createContext } from 'react';
import { Popup, PopupProps } from '@progress/kendo-react-popup';

/**
 * Wrapper around Kendo's Popup component that fixes an issue with all contexts not being provided
 * on first render, causing crashes in some cases. This can be used exactly like the original, the only 
 * difference is that children will automatically be "null" in renders where Kendo ignores providers.
 */
const KendoPopup: FC<PopupProps> = ({ children, ...props }) => {
  return (
    <FixContext.Provider value={true}>
      <Popup {...props}>
        <FixContext.Consumer>
          {shouldRender => shouldRender && children}
        </FixContext.Consumer>
      </Popup>
    </FixContext.Provider>
  )
}

export default KendoPopup;

const FixContext = createContext(false);
```

**Comment by nstoychev** [comment]
@oceantume - We have made a change of the Popup in our dev channel and the Popup renders only once now - https://stackblitz.com/edit/react-nqwaey-8sjckt?file=app/main.jsx. This should resolve the issue.
