### ISSUE TITLE
Make conversation ui buttons customizable

### ISSUE THREAD

**Issue by lekhasy** [telerik/kendo-react#348]
## Current behavior
We have no way to add one or several buttons next to the send message button

## Expected behavior
Be able to customize the send message button group

## What is the motivation or use case for changing the behavior?
A conversation have more than just text message. We need a way to add buttons for file/image/video selection, emoji selection, restart conversation, like button, setting ... All those button should reside next to the send button.

**Comment by Xizario** [comment]
Fixed in `3.5.0`
