### ISSUE TITLE
Material labels move strangely when a value exists

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#349]
## I'm submitting a...
* Regression report

## Current behavior
The labels move up about 50% higher when you click into it, than when a value exists. This causes a jumpy experience for users. Also it appears that there is now a background-colour on the label, as a white box appears on our website (which has a grey background).

## Expected behavior
Label when focused, and when has a value, moves to the same position. Should not have a background colour so it fits in with the rest of the website.

## Minimal reproduction of the problem with instructions
https://www.telerik.com/kendo-react-ui/components/dropdowns/dropdownlist/forms/
https://www.telerik.com/kendo-react-ui/components/inputs/floating-labels/

1. Set the background colour of the website to `#DDD` in the element inspector.
2. Click into the input. The label will move up quite high, and display a white box around it.
3. Select a value. The label will jump back down about 50%.
4. Click into the input again. The label will jump back up again.

## What is the motivation or use case for changing the behavior?
Our website has a background colour of a light grey, which makes the labels appear out of place. The spacing of the website also accounted for the labels, but now they go higher up and get cut off in many situations.

Browser:
- Opera Version 63.0.3368.107

**Comment by otacilioMota** [comment]
Dear, I also have the same problem as the floatlabel color background. Here's a link to the problem statement: [https://stackblitz.com/edit/floatlabel](https://stackblitz.com/edit/floatlabel)

**Comment by silviyaboteva** [comment]
- The alignment is already fixed with Material theme `v3.3.5`.
- Fixed in Material theme `v3.3.6` The background of the focused floating label can be changed via `$floating-label-focused-bg` variable.
