### ISSUE TITLE
grid pageChange event documentation and or typo

### ISSUE THREAD

**Issue by nelsonomuto** [telerik/kendo-react#35]
## Current behavior
- The react grid onPageChangeEvent is not firing when using virtual scroll and the page is scrolled to its limit.

## Expected behavior
 The react grid onPageChangeEvent is not firing when using virtual scroll and the page is scrolled to its limit.

## Minimal reproduction of the problem with instructions
- I cannot reproduce this in plunker https://plnkr.co/edit/dWc90J?p=preview but locally when I npm install kendo react grid using the virtual scroll example code.

## Environment

Package versions:
```
├── @babel/runtime@7.0.0-beta.49
├── @material-ui/core@1.1.0
├── @material-ui/icons@1.1.0
├── @progress/kendo-data-query@1.3.1
├── @progress/kendo-dateinputs-react-wrapper@2018.2.516
├── @progress/kendo-drawing@1.5.5
├── @progress/kendo-editor-react-wrapper@2018.2.516
├── @progress/kendo-layout-react-wrapper@2018.2.516
├── @progress/kendo-react-dateinputs@0.4.0
├── @progress/kendo-react-dropdowns@0.4.0
├── @progress/kendo-react-excel-export@0.5.1
├── @progress/kendo-react-grid@0.4.0
├── @progress/kendo-react-inputs@0.4.0
├── @progress/kendo-react-intl@0.4.0
├── @progress/kendo-react-layout@0.5.1
├── @progress/kendo-react-pdf@1.0.0
├── @progress/kendo-theme-default@2.53.2
├── @progress/kendo-ui@2018.2.516
├── abortcontroller-polyfill@1.1.9
├── babel-eslint@8.2.3
├── babel-preset-env@1.7.0
├── babel-preset-flow@6.23.0
├── babel-preset-react@6.24.1
├── babel-runtime@6.26.0
├── classnames@2.2.5
├── cldr-data@32.0.1
├── cypress@3.0.1
├── enzyme@3.3.0
├── enzyme-adapter-react-16@1.1.1
├── eslint@4.19.1
├── eslint-config-airbnb@16.1.0
├── eslint-config-prettier@2.9.0
├── eslint-plugin-flowtype@2.47.1
├── eslint-plugin-import@2.12.0
├── eslint-plugin-jsx-a11y@6.0.3
├── eslint-plugin-prettier@2.6.0
├── eslint-plugin-react@7.8.2
├── express@4.16.3
├── express-http-proxy@1.2.0
├── husky@0.14.3
├── jest@23.0.0
├── jquery@3.3.1
├── lint-staged@7.1.2
├── lodash@4.17.10
├── material-ui@0.20.1
├── meteor-node-stubs@0.3.3
├── moment@2.22.1
├── prettier@1.12.1
├── query-string@6.1.0
├── react@16.4.0
├── react-dom@16.4.0
├── react-number-format@3.3.4
├── react-router-dom@4.2.2
├── react-spinkit@3.0.0
├── react-toastify@4.0.1
└── whatwg-fetch@2.0.4
```

Browser:
- All

System:
- All

**Comment by nelsonomuto** [comment]
The workaround that works for me currently is using `pageChange` instead of `onPageChange` which is in the documentation and example in the site. 

Therefore either we need a documentation update and or change to reflect that the prop is `pageChange`

**Comment by mitagg** [comment]
The `pageChange` event is deprecated in v.1.0.0 of the packages in favor of the `onPageChange` event. This is mentioned in our [backlog](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#toc-features).
