### ISSUE TITLE
Not Able to create Custom MultiSelect dropdown filter using Kendo React: Please Provide the multi select dropdown filter example: I want to use in Sharepoint Framework React Webpart

### ISSUE THREAD

**Issue by ankit1609-cyber** [telerik/kendo-react#356]
I am using typescript code(.tsx). I am binding the data dynamically in grid(through rest api).I have seen the example you have given for category filter but its in jsx, which is throwing error in my SPFX project.Please open the file notepad++ for refrence of my grid implementation
![TasksView](https://user-images.githubusercontent.com/53405555/66897231-2c044400-f014-11e9-8b18-2328e9a9506e.png)

**Comment by Xizario** [comment]
Please use our support system for such kind of requests https://www.telerik.com/account/support-tickets
