### ISSUE TITLE
Sparkline does not re-render when the props' values are changed.

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-react#357]
## I'm submitting a...
* Bug report

## Current behavior
Sparkline does not re-render when the props' values are changed.

## Expected behavior
Sparkline to trigger re-render after the props' values are changed.

## Minimal reproduction of the problem with instructions
  1. Open the following demo in Stackblitz: https://stackblitz.com/edit/react-h8aze4-quqnrp?file=app/main.jsx
  2. Clicking on the 'UPDATE' button, the Sparkline chart does, not trigger a refresh.

## Workaround
Demo: https://stackblitz.com/edit/react-h8aze4-j9atax?file=app/main.jsx

The Sparkline exposes key prop, which is updated on every button click.

**Comment by vladimirivanoviliev** [comment]
Fixed on our side - will be shipped with next dev version.
