### ISSUE TITLE
Editor InsertTable tool does not work with defaultEditMode set to div.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#358]
Editor InsertTable tool does not work with defaultEditMode set to div.

The table element is added, but it is very shrunk and with no borders. 

This can be observed in the following demo:

https://stackblitz.com/edit/react-ebpbvp?file=app/content.js

**Comment by nstoychev** [comment]
The problem here is that the styles are not loaded. We should add a demo for defaultEditMode="div".

**Comment by cwdata** [comment]
Ok, so how could we load the styles in that case?

**Comment by nstoychev** [comment]
Here is an example - https://stackblitz.com/edit/react-rqoasa?file=index.html

The styles of the editor content are placed in the index.html file. Feel free to modify them as you need.

**Comment by cwdata** [comment]
Thanks Nikolay, it is working for me now.

**Comment by nstoychev** [comment]
Here is the new demo showing how to style the content in DIV mode - https://www.telerik.com/kendo-react-ui-develop/components/editor/rendering-mode/.
