### ISSUE TITLE
Switch component with Material theme doesn't slide properly

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#36]
## I'm submitting a...
* Bug report 

## Current behavior

The Switch does not slide(only in Material theme)

## Minimal reproduction of the problem with instructions

The issue can be observed here:  https://next.plnkr.co/edit/0fuYDpHRBKfdr19t

Browser:
-All

**Comment by simonssspirit** [comment]
Similar case in Angular Switch: https://github.com/telerik/kendo-angular/issues/1577

**Comment by vanderleisilva** [comment]
Hey @kspeyanski do you have an idea of how long will take to solve this issue?

**Comment by kspeyanski** [comment]
Hello @vanderleisilva , sorry for the delayed response.

The issue has been resolved, and once it passes our QA tests, we will publish it in our `@dev` channel.
I'll keep you updated once it has been released.
