### ISSUE TITLE
There is a blank space at the bottom of the Grid when the column and row virtualization is on.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#363]
There is a blank space at the bottom of the Grid when the column and row virtualization is on.

It can be observed in our demo as well:

https://www.telerik.com/kendo-react-ui/components/grid/columns/column-virtualization/

Adding rowHeight does not resolve the issue.

**Comment by Xizario** [comment]
Duplicate of https://github.com/telerik/kendo-react/issues/242
