### ISSUE TITLE
Scheduler: Allow blocking specific dates

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#365]
Scheduler: Allow blocking specific dates

The use case is when for example, an event can be scheduled only from Tuesday to Thursday.

**Comment by kspeyanski** [comment]
The scheduler `items` and `slots` can be customised through the corresponding `item`, `viewItem`, `editItem` and `slot`, `viewSlot`, `editSlot` properties.

A similar to the described behaviour can be observed in our [`SchedulerEditItem customisation`] (https://www.telerik.com/kendo-react-ui/components/scheduler/customization/items/edit-item/) article.
