### ISSUE TITLE
Improve the HTML tables support of the Editor

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-react#366]
The Editor should support tables with sizes, styles, css classes and other tables related attributes listed here - https://docs.telerik.com/kendo-ui/controls/editors/editor/table-wizard-dialog.

Example with extended schema - https://stackblitz.com/edit/react-f4qb39-1wedpk

Requested in ticket: 1435391

**Comment by simonssspirit** [comment]
The table border styles tool is requested in 1508339

**Comment by nstoychev** [comment]
Implemented in 4.9.0.
