### ISSUE TITLE
Invalid ARIA attribute in Grid Component

### ISSUE THREAD

**Issue by dejimarquis** [telerik/kendo-react#369]
## I'm submitting a...

* Suggestion for improvement

## Current behavior

Given I have a Grid component in my web application, when I run FastPass using Accessibility Insights for Web, I get the follow error message for each of the columns in the grid:

**Fix the following:Invalid ARIA attribute value: aria-sort=""**

## Expected behavior

Given I have a Grid component in my web application, when I run FastPass using Accessibility Insights for Web, then every column header should a valid ARIA attribute when in its unsorted

**aria-sort="none"**

## Minimal reproduction of the problem with instructions

[https://stackblitz.com/edit/react-bv7zsp?file=package.json](url)

## What is the motivation or use case for changing the behavior?

This enables components in your library be accessible.

**Comment by cuete** [comment]
Facing the same problem here. using `kendo-react-grid 2.11.0 `
Is there a workaround to populate the attribute with "none" or some value that is not ""?

**Comment by nstoychev** [comment]
@cuete - There is not a good workaround but here is how the empty aria-sort attributes can be populated

`document.querySelectorAll('.k-grid th[aria-sort=""]').forEach(th => th.setAttribute('aria-sort', 'none'))`

**Comment by nstoychev** [comment]
Fixed in dev version [3.7.0-dev.201911061216](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#toc-370-dev201911061216). 

Example - https://www.telerik.com/kendo-react-ui-develop/components/grid/columns/column-menu/
