### ISSUE TITLE
Allow the Splitter panes to stay mounted after collapse.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#371]
Allow the Splitter panes to stay mounted after collapse.

We can add a prop that will keep the Splitter panes mounted after collapse, similar to the TabStrip tabs:

https://www.telerik.com/kendo-react-ui/components/layout/api/TabStripProps/#toc-keeptabsmounted

**Comment by vladimirivanoviliev** [comment]
Ready on our side, will be shipped with next dev version.

**Comment by vladimirivanoviliev** [comment]
3.7.0-dev.201910311300
