### ISSUE TITLE
Cancel button does not work for DateTimePicker

### ISSUE THREAD

**Issue by daniel-beretta** [telerik/kendo-react#375]
## I'm submitting a...
* Bug report 

## Current behavior

Clicking the cancel button on a DateTimePicker popup does nothing. Hitting `esc` key or clicking outside the popup closes it.

## Expected behavior

Clicking the cancel button should close the popup, just like when clicking outside of it.

## Minimal reproduction of the problem with instructions

Can reproduce on official documentation page:
https://www.telerik.com/kendo-react-ui/components/dateinputs/datetimepicker/

## What is the motivation or use case for changing the behavior?

The button doesn't work.

## Environment

Package versions:

```

```
Omitting as it's reproducible on demo page.

Browser:

- Chrome (desktop) version 78.0.3904.87
- Firefox version 70.0.1
- Safari (desktop) version 13.0.3

System:
- Platform: Mac OS X 10.14.6

First noticed on `@progress/kendo-react-dateinputs` v3.4.1

**Comment by kspeyanski** [comment]
Hello @daniel-beretta,
The issue has been fixed. Please update the `@progress/kendo-react-dateinputs` package to version [`@3.7.0`](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#toc-370).

The fix can also be observed in the following stackblitz example:
https://stackblitz.com/edit/react-u2v5ft?file=app/main.jsx

Thank you for reporting it, and please let me know if you need further assistance.

**Comment by daniel-beretta** [comment]
Looks good, many thanks @kspeyanski
