### ISSUE TITLE
Setting columnMenu to null on column level does not overwrite the columnMenu set on the Grid level.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#377]
Setting columnMenu to null on column level does not overwrite the columnMenu set on the Grid level.

Based on the docs, the columnMenu props accepts null, and should not display columnMenu for that column:

https://www.telerik.com/kendo-react-ui/components/grid/api/GridColumnProps/#toc-columnmenu

**Comment by Xizario** [comment]
Fixed in `3.11.0`
