### ISSUE TITLE
Focus not kept on other components after selecting file in upload component

### ISSUE THREAD

**Issue by AFSAlexS** [telerik/kendo-react#378]
## I'm submitting a...

* Bug report 

## Current behavior

If you have both the upload component and another component (like Input or textarea), you will need to take the following steps:

 - Upload a file
- Select that file after it is uploaded so it is focused 
- Select another component to focus on (like the Input component)

You'll notice the selected file does not seem to lose focus (k-state-focused class stays), but you will also still be focused on the other component. 

If you then try making a change in the other component, like by keying in a character to the Input component, that component loses focus after pressing the key. If you try to focus on the component again and key in another character, you lose focus again. The only way to stop this is to select the file, and then tab out so the file loses focus.

This issue seems to only take place when passing in the value and onChange props. If the component is maintaining it's own state, then it does not seem to lose focus.

## Expected behavior

The other component should not be losing focus when a file is selected in the upload component.

## Minimal reproduction of the problem with instructions

Please see https://stackblitz.com/edit/react-9rjkzf?file=app/main.jsx

Steps to take:

- Upload file
- Select the uploaded file so it is focused 
- Click on input so it is focused
- Start typing

In the first example where the component maintains it's own state, there are no issues.
In the second example where we are passing the value and onChange props, the input will lose focus after you start typing.

Browser:

- Chrome (desktop) version 78.0.3904.87
- Firefox version 70.0.1
- IE version 11.418.18362.0
- Edge version 44.18362.387.0

System:
- Node version: 10.15.3  
- NPM version: 6.11.3
- Platform:  Windows

**Comment by simonssspirit** [comment]
@vladimirivanoviliev could you please take a look at this?

**Comment by vladimirivanoviliev** [comment]
Fixed on our side, expected to be released with next dev version. I will follow up when we have exact version.

**Comment by vladimirivanoviliev** [comment]
Released with 3.7.0
