### ISSUE TITLE
Grid > "No data" label

### ISSUE THREAD

**Issue by Jezvin** [telerik/kendo-react#38]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
When the grid data source is empty, the grid is "just" emtpy

## Expected behavior
I didn't find a way to easily set  a "no data" text that would be displayed when the grid datasource is empty

## Minimal reproduction of the problem with instructions
Set up a Kendo React Grid, with an empty data source

## What is the motivation or use case for changing the behavior?
I would like to be able to let the user know that the grid is functionning correctly, and that their search simply didn't come up with any results.

## Environment
Latest kendo grid version

**Comment by Xizario** [comment]
Will work in the next uploaded [dev version.](https://www.telerik.com/kendo-react-ui-develop/components/installation/development-builds/) later today.
