### ISSUE TITLE
Opening dropdown upwards

### ISSUE THREAD

**Issue by lukavuletic** [telerik/kendo-react#382]
Is there a way to make dropdown open upwards?

**Comment by nstoychev** [comment]
Currently no. The dropdown will open upwards if there is not enough space downwards and this cannot be configured.

**Comment by lukavuletic** [comment]
Could I make a class that will tell my dropdown that there is not enough space downwards and get it to open upwards then?

**Comment by kdikov82** [comment]
This is already available by configuring the position of the Popup (either through the popupSettings of the DropDownList or by using PopupPropsContext:

- [https://www.telerik.com/kendo-react-ui/components/popup/aligning-positioning/#toc-positioning](https://www.telerik.com/kendo-react-ui/components/popup/aligning-positioning/#toc-positioning)
- [https://www.telerik.com/kendo-react-ui/components/popup/global-context/](https://www.telerik.com/kendo-react-ui/components/popup/global-context/)
