### ISSUE TITLE
tabIndex property does not work for some disabled components.

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-react#384]
`tabIndex` prop should have higher priority than any internal logic that defaults it. Per the concept that if something is explicitly set by the developer, he needs it.

Proposed solution:
* Components that have tabIndex as `defaultProps`, should not have it there, and it must be checked inline in the render. with props.tabIndex as most priority and then enable/disabled etc as lower.
* Components that don't use `defualtProps` for initialization, should just use tabIndex with highest priority for the output.
* End user will not be affected if they don't use `tabIndex` at this point.
* End users that have `tabIndex` set to 0 or -1 and it does not work, will get a fix, thus it will become to work.
* End users that want to remove the tabIndex of html output should use `tabIndex={null}` or `tabIndex=""`

**Comment by nstoychev** [comment]
We don't need to change the tabIndex prop type to accept null or string. We can use the `in` operator to check it the tabIndex prop is set.

**Comment by vladimirivanoviliev** [comment]
The question here is to decide between `-1` and `undefined` as disabled tabindex when user is not providing it.
- https://stackblitz.com/edit/react-uj3b7q?file=app/main.jsx

**Comment by vladimirivanoviliev** [comment]
@nstoychev could you please give an example of using `in` operator to detect if prop is set by `defaultProps` or by the user as regular prop?

**Comment by nstoychev** [comment]
Sure -
`const tabIndex = 'tabIndex' in this.props ? this.props.tabIndex : defaultProps.tabIndex;`

**Comment by vladimirivanoviliev** [comment]
If you check the following example you will see that the above scenario is not working as expected - always reports `true`:

https://stackblitz.com/edit/react-uj3b7q-r1zf3a?file=app/main.jsx

**Comment by vladimirivanoviliev** [comment]
After offline discussion we decided to
1. keep current disabled tabindex in old components
1. refactor old components to support tabindex with higher priority over internal tabindex
1. for future components use tabindex `-1` as disabled tabindex

**Comment by vladimirivanoviliev** [comment]
Updated in:
- [ ] Inputs
- [ ] Upload
- [ ] Sortable
