### ISSUE TITLE
Missing `*.d.ts` files for the `es` distribution of the `kendo-data-query` package

### ISSUE THREAD

**Issue by xarety** [telerik/kendo-react#385]
## I'm submitting a...
* Bug report

## Current behavior
`*.d.ts` files existing only for `npm` distribution

## Expected behavior
`*.d.ts` files existing for `es` as same as `npm` distribution.

## What is the motivation or use case for changing the behavior?
We're using some of the internal functions and interfaces and have to import them from `es` distribution.

## Environment
Package versions:
"@progress/kendo-data-query": "^1.5.2",

**Comment by Xizario** [comment]
Typings are located in `dist/npm/main.d.ts`, as defined in the package.json.

```"typings": "dist/npm/main.d.ts",```
https://unpkg.com/browse/@progress/kendo-data-query@1.5.2/package.json

There there is no need to be placed more than once in the package. Some people are adding them into the `root` or `/typings` folder, but it really does not matter if the path is defined in the package.json

Is there any specific problem that this is causing that we are not aware of?

**Comment by xarety** [comment]
We're using webpack, it uses `es` distributions by default and importing from the `npm` distribution leads to code duplication in the resulting bundle. Also, `kendo-react-grid` package has typings for the `es` distribution.

**Comment by xarety** [comment]
Hey folks, any updates related to this issue?

**Comment by Xizario** [comment]
@tsvetomir any suggestions?

**Comment by tsvetomir** [comment]
@xarety can you please share samples of the `import` statements in your project?

Normally, imports should not include deep paths, but only the package name:
`import { process, orderBy, filterBy } from '@progress/kendo-data-query';`

The TypeScript compiler would then locate the type information according to the metadata in `package.json`. WebPack would also do the same in order to fetch the correct module format.

**Comment by xarety** [comment]
We have our own wrapper around `@progress/kendo-data-query` with extended functionality as we have imports like:
```
 import {
    exec,
    skip as skipTransformer,
    take as takeTransformer,
    filter as filterTransformer,
    concat as concatTransformer
} from '@progress/kendo-data-query/dist/npm/transducers';
```
so, it's not regular package usage.

**Comment by tsvetomir** [comment]
I guess we could export the methods from `transducers` and save you some trouble. They're just utilities, but so is the rest of the library.

**Comment by xarety** [comment]
It was just an example of our deep imports we have also other imports if you wanna I can list all of them.

**Comment by tsvetomir** [comment]
Okay, I'll let you know if we decide to make them public or not. Worst case, you could copy the code for these helpers from [the source code](https://www.telerik.com/kendo-react-ui/components/installation/source-code/).
