### ISSUE TITLE
Default filtered Multiselect options to first item, rather than first startsWith match.

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#388]
* Suggestion for improvement

## Current behavior
In the filtering with remote data demo, if the default selected item in the list starts with the same characters as the search term you can hit "Enter" to immediately add it. 

However, if it simply _contains_ your search term (e.g. when a user searches by surname), then no item is selected by default, or an item that is out of view is selected. Hitting Enter on keyboard will add that invisible item unexpectedly or it will do nothing. 

## Expected behavior
Rather, when filtering select the first item in the list by default, similar to other autocomplete libraries.

## Minimal reproduction of the problem with instructions
Demo used is here: https://stackblitz.com/run/?file=app%2Fmain.jsx.

 1. Search for "Maria" and hit Enter. Good user friendly behavior
2.  Search for "Sommer" and hit Enter. Nothing happens. You have to down-arrow first. 

A different example:
1. Search for "E"
2. Press Enter
3. Elizabeth Sommers was added but that name wasn't even visible. Its a bit unexpected.  

Compare this to the multi select here: https://react-select.com/async (3rd drop down on page).
If you search for "s" then "Forest" will be selected by default and hitting Enter will add it. 

## What is the motivation or use case for changing the behavior?
With autocomplete controls where someone searches on Surname and needs to add many items to the list, it is nice to default selection to first item. 

If users wants the "startsWith" matches to be defaulted, then they just need to order their data alphabetically

We are migrating from a separate Autocomplete library to try to leverage the kendo multiselect for the same purpose so that our UI looks consistent with our other Kendo components. However, the multiselect is not able to allow users to use their keyboard to very quickly add emails when they are searching for email addresses in the multiselect, like other Autocompletes. 

Browser:

- Chrome (desktop) version 78

System:
Platform: Windows

**Comment by nstoychev** [comment]
@k290 - We have just published in our dev channel a new prop of the dropdowns called `focusedItemIndex`. Here you can check it - https://stackblitz.com/edit/react-h65hyw?file=app/main.jsx.

Changing the internal focusing logic from "startsWith" to "contains" is not a bad idea but it will also be a breaking change.

**Comment by k290** [comment]
Brilliant! Thank you very much.
