### ISSUE TITLE
Using custom input to type the text in the Chat components throws an error.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#389]
Using custom input to type the text in the Chat components throws an error.

The following example is showcasing this:

https://stackblitz.com/edit/react-bjkmiu?file=app/main.jsx

The issue is caused by the internal use of the reference to the built-in input:

https://github.com/telerik/kendo-react-private/blob/develop/packages/conversational-ui/src/components/NewMessage.tsx#L138

https://github.com/telerik/kendo-react-private/blob/develop/packages/conversational-ui/src/components/NewMessage.tsx#L107

**Comment by Xizario** [comment]
Fixed in `3.11.0`
