### ISSUE TITLE
Conversational UI Message Date Cropped

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#391]
## I'm submitting a...
* Bug report 

## Current behavior
When you click on a message to see the date of the message, often the date gets cut off if the message is longer than 1 or 2 words.

## Expected behavior
The date would wrap or display differently if there isn't enough space for it.

## Minimal reproduction of the problem with instructions
Replicatable in the demo
https://www.telerik.com/kendo-react-ui/components/conversationalui/

1. simply click on the default message example and it will be cropped.
![image](https://user-images.githubusercontent.com/12272970/69585817-b20ea400-1030-11ea-8584-b8dedb59c797.png)

## What is the motivation or use case for changing the behavior?
Our users like to see the date of messages they received, but are unable to see the time in certain cases.

Browser:
- Chrome (desktop) version 78.0.3904.108 (Official Build) (64-bit)

**Comment by Xizario** [comment]
Even if styling using the `.k-message-time` is possible resolution, I suggest we need to make k-message-time's format optional, because it is currently to `'g'` and someone would like to see time-only there.

**Comment by InaGlushkova** [comment]
Hello @GeoMarkou ,

We have added new feature in version `3.13` of the `@progress/kendo-react-conversational-ui` which allows to customize the [ChatMessage ](https://www.telerik.com/kendo-react-ui-develop/components/conversationalui/api/ChatMessageProps/)component through the [message ](https://www.telerik.com/kendo-react-ui-develop/components/conversationalui/api/ChatProps/#toc-message)prop of the Chat component. 
For more information about customizing the ChatMessage please reffer to the [Chat customization article](https://www.telerik.com/kendo-react-ui-develop/components/conversationalui/custom-rendering/#toc-customizing-the-message).

I have prepared an example which is showcasing the feature and customization of the dateFormat:
https://stackblitz.com/edit/react-bhgz4e-f8qytp
