### ISSUE TITLE
Grid/TreeList with column virtualization over 1000 columns, hits the colspan limit.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#395]
Grid/TreeList with column virtualization over 1000 columns, hits the colspan limit.

The colspan limit is 1000:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td

"_This attribute contains a non-negative integer value that indicates for how many columns the cell extends. Its default value is 1. Values higher than 1000 will be considered as incorrect and will be set to the default value (1)._"

As a workaround, a frozen column with no field and no width can be added after every 1000 columns as it divides the colspan between and after it.

**Comment by Xizario** [comment]
Should be listed in the known limitations

**Comment by simonssspirit** [comment]
the limitation and the workaround are listed:

https://www.telerik.com/kendo-react-ui-develop/components/treelist/columns/virtualization/#toc-known-limitations
