### ISSUE TITLE
Datepicker and similar do not focus parent input on Esc key

### ISSUE THREAD

**Issue by shekerev-progress** [telerik/kendo-react#396]
**Expected Behavior:**
The Keyboard navigation pages for DatePicker, DateRangePicker, DateTimePicker, TimePicker say that upon Esc Key the popup closes and the focus is moved to the input element

**Current behavior:**
For DatePicker, DateTimePicker, TimePicker, upon Esc Key the popup closes but the focus is not on the input element

DateRangePicker behaves as expected

Reported by client for the datepicker, but I believe it would be best to fix for all components for consistency

Assigning to @kspeyanski for advise

**Comment by kspeyanski** [comment]
The issue has been fixed in version [4.9.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/) of the `@progress/kendo-react-dateinputs` package.
