### ISSUE TITLE
NumericTextBox, Zeroes and % 

### ISSUE THREAD

**Issue by JonisJohnny** [telerik/kendo-react#397]
## I'm submitting a...

* Bug report 

## Current behavior

With the NumericTextBox you can add how many zeros you want after decimal , even though max is added. 

Another issue is that you can not add % sign without it converting the number. even though there is a way described here to do it https://github.com/telerik/kendo-intl/blob/master/docs/num-formatting/index.md

## Expected behavior

The NumericTextBox should not be able to add zeroes like it is with other numbers

You should be able to use % sign without formatting the number

## Minimal reproduction of the problem with instructions

1. Open this: https://stackblitz.com/edit/react-9nmr3f?file=app%2Fmain.jsx
2. On decimal add zeros after decimal, On precentage use the arrows or see the backslash 

## Environment
Windows 10

Browser:

- Chrome (desktop) 
- Firefox

**Comment by vladimirivanoviliev** [comment]
Fixed in latest dev version `3.10.0-dev.202001150733`.
