### ISSUE TITLE
GridInput should use Array.isArray to prevent errors when using iframes

### ISSUE THREAD

**Issue by vatho** [telerik/kendo-react#40]
## I'm submitting a...
* Bug report 

## Current behavior
If you use a GridInput in an iframe and get the data from a parent window, the data is not recognized as an Array because of the issue mentioned here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray

The exact error is `TypeError: Cannot read property 'length' of undefined` (see console output in the reproduction Plunkr)

## Expected behavior
Data should be recognized as an Array. Easiest fix for this is to use `Array.isArray(data)` instead of `data instanceof Array`

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/dzp5ZOdA0GELTiMu1ct8?p=preview
See the console output for the error and difference of Array.isArray vs. instanceof
![image](https://user-images.githubusercontent.com/1861665/42151204-7f5584b2-7ddc-11e8-856b-016fdabe75e0.png)

## What is the motivation or use case for changing the behavior?
We are using GridInputs inside iframes and are running into this issue.

**Comment by Xizario** [comment]
Thank you for the detailed information. We will fix it.

**Comment by Xizario** [comment]
Will work in the next uploaded [dev version.](https://www.telerik.com/kendo-react-ui/components/installation/development-builds/) later today.
