### ISSUE TITLE
How to use customCell and Reorder in Kendo react Grid at the same time ?

### ISSUE THREAD

**Issue by Nassefferjeni** [telerik/kendo-react#400]
So I am using Kendo React Grid and I am setting the reorder to true and also added a custom cell where I can show/hide columns.

when I don't reorder and try to show/hide everything works fine but when I reorder the columns and then try to hide then restore the column everything will get messy and I can't understand where I can control this.

[This is the grid at first][1].

[This is where I reorder the columns][2]

[Now I opened the customCell and tried to hide the first column][3]

[This is the result where I click on Save the order is changing and I don't know why][4]

this is the Telerik documentation and in all examples there is no one where I can find reorder and customCell at the same time: https://www.telerik.com/kendo-react-ui/components/grid/

And this is the reorder section/ I couldn't find details about customizing the reorder: https://www.telerik.com/kendo-react-ui/components/grid/columns/reordering/

  [1]: https://i.stack.imgur.com/PLvUF.png
  [2]: https://i.stack.imgur.com/oKGOL.png
  [3]: https://i.stack.imgur.com/pJ2TO.png
  [4]: https://i.stack.imgur.com/wewfb.png

**Comment by Xizario** [comment]
If the columns are changed dynamically, each column need to have `orderIndex` defined, to be placed in the proper place after reordering.
You can use the `onColumReorder` callback to obtain the proposed `orderIndex` for each of the columns and store them over your original columns.

There are several possible ways to implement this, depending on what you expect to happen. Here is use case:

Columns: **ABCD** , user hide **B**.
Columns: **ACD**, user then reorder **D** before **A**.
Columns **DAC**. User then show **B**. Where **B** should go?

Possible outputs: 
1) **DBAC** - **B** shows on its position where it was before hiding.
2) **DABC** - **B** is in the place where it should have been if it was not hidden during the reordering.
3) **BDAC** - **B** shows first
4) **DACB** - **B** shows last.

Personally I prefer second option as it can be implemented for the order the columns in the Column Menu custom cell as well. And the user will know where the column will be even before showing it.

See in your screenshot from step 3, https://i.stack.imgur.com/pJ2TO.png I would expect `Description` to be above `ID` in the menu as well.

If this is the desired scenario, let us know and we will add it to the docs.

**Comment by Nassefferjeni** [comment]
that's exactly why I am asking: when I try to use `onColumReorder`  and try to set the state of the columns depending on the new order it seems like nothing is changing.
Plus I have another question: I am not setting the order on any column ( at first ) and when I try to `console.log(this.state.columns)` I can't see any orderIndex inside the columns.
So I tried adding the order myself on the state and this is how I did it:
`this.state = {
            columns: props.columns.map((element,i) => ({ ...element, orderIndex: i }))
}`


Do you have any idea how to proceed ?
`_onColumnReorder = (event) => {
        console.log(event)
        console.log(this.state.columns)
    }`

the photo attached is showing the result of the columnreorder event

![1](https://user-images.githubusercontent.com/33683191/69858402-357b0000-1292-11ea-9c49-1de0f5300b93.PNG)

the second photo is showing my columns state and the order is always the one that I set :

![2](https://user-images.githubusercontent.com/33683191/69858708-dc5f9c00-1292-11ea-80e7-12f3e1f4d4a3.PNG)

and this is how my grid is now:

![3](https://user-images.githubusercontent.com/33683191/69858756-f7321080-1292-11ea-94bc-e1278742f46d.PNG)

Although I am typing the `onColumnReorder` myself and not doing anything inside it the kendo Grid is changing.

**Comment by Nassefferjeni** [comment]
Thank you for your response. I used the orderIndex and successfully implemented the first output:
**DBAC** - **B** shows on its position where it was before hiding
