### ISSUE TITLE
Kendo grid column reordering is not scrolling the grid when you move to the edge of it

### ISSUE THREAD

**Issue by Nassefferjeni** [telerik/kendo-react#401]
I am using kendo grid and implementing reorder.
first, I am setting the width of the grid dynamically.
second, I am setting the reorder object to true inside the grid `reorderable={ true }`

I have about 30 columns so that's why I implemented reorder so I can choose the best to order them.
My problem is that I can't scroll to the end of the grid dynamically I will have to move them to the even of the available width then scroll myself then complete the reorder.

**Comment by Xizario** [comment]
This is valid feature request: Auto scroll during drag.

Currently scrolling and drag-to-reorder are working independently. You can scroll using shift+mouse wheel or the arrow keys, multi touch on mobile and mac.

**Comment by Nassefferjeni** [comment]
Is there any other way? 
I mean like using event listeners and forcing the scroll?
I tried using onmousemove event but It doesn't seem to be working
@Xizario

**Comment by Pushpendu112** [comment]
Any updates if this will be implemented in near future?

**Comment by Xizario** [comment]
It is still not planned. Best case we can work on this right after September unless it gains more popularity to justify its prioritization.

**Comment by kspeyanski** [comment]
The `autoScroll` feature has been implemented in the Grid Columns and can be observed in the [following demo](https://www.telerik.com/kendo-react-ui-develop/components/grid/columns/locked/) whenever the viewport width is smaller than the columns width, the grid is horizontally scrollable.

The feature is available with version `4.13.0@dev` of the `@progress/kendo-react-grid` package.
