### ISSUE TITLE
Conversational UI Scrolls Down When Messages Are Loaded

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#403]
## I'm submitting a...
* Bug report

## Current behavior
Scrolling up and loading more messages in a chat, causes the list of messages to scroll back down to the bottom.

## Expected behavior
Chat will only scroll down if messages are added to the end, not the beginning.

## Minimal reproduction of the problem with instructions
Editor URL
https://stackblitz.com/edit/react-zwjel5-zvmdd6

Viewer URL
https://react-zwjel5-zvmdd6.stackblitz.io

1. Scroll to the top of the messages list
2. Click the button "Click me to load more messages" to simulate 'infinite scrolling' behaviour and load more historical messages from an API.
3. The messages list will scroll back down to the bottom, which is jarring for the user.

## What is the motivation or use case for changing the behavior?
We are using an API for chat which charges per historical message. To reduce costs we only load the last 20 messages by default, and if the user scrolls up to load more, it will download more. This is similar to how Facebook Messenger, or other chat programs work.

Browser:
- Chrome (desktop) version 78.0.3904.108 (Official Build) (64-bit)

**Comment by simonssspirit** [comment]
@GeoMarkou Thank you for the report. 

I can agree that this request is a valid one and we will count it as a feature request.

Please share how will you image this to work:

- When messages are added at the beginning no scroll occurs, the position is retained and the user starts scrolling up.

- The Chat is scrolled to the top

**Comment by Xizario** [comment]
@simonssspirit 
I imagine auto-scroll down to work only if the scroll position is already at the bottom, before loading the more items. No matter if the messages are added top, bottom, mid, etc.

If the user have scrolled somewhere we should not touch the scroll.

**Comment by GeoMarkou** [comment]
@simonssspirit I agree with @Xizario. Leaving the scroll if the user has scrolled up would be the ideal behaviour that covers any situation.

**Comment by Xizario** [comment]
Fixed in `3.11.0`
