### ISSUE TITLE
DropDownList inside Dialog rendered behind Dialog

### ISSUE THREAD

**Issue by Padhraic** [telerik/kendo-react#404]
## I'm submitting a...
* Bug report

## Current behavior
When opening DropDownList inside a dialog, the drop down list is rendered behind the dialog

## Expected behavior
The dropped down list should appear over the dialog.

## Minimal reproduction of the problem with instructions
Stackblitz reproduction of the issue [here](https://stackblitz.com/edit/react-eg6993)
1) click show dialog button,
3) Click the DropDownList, -> see drop down list appearing behind the dialog.

## Environment
Package versions:
"@progress/kendo-data-query": "1.5.2",
"@progress/kendo-react-buttons": "3.9.0",
"@progress/kendo-react-dialogs": "^3.9.0",
"@progress/kendo-react-dropdowns": "3.9.0",
"@progress/kendo-react-intl": "3.9.0",
"prop-types": "15.7.2",
"react": "16.12.0",
"react-dom": "16.12.0",
"react-transition-group": "4.3.0"

Browser:
Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

System:
- Node version: 6.5.0-next.0
- Platform:  Windows

**Comment by simonssspirit** [comment]
Dublicate of: https://github.com/telerik/kendo-react/issues/45
