### ISSUE TITLE
Scheduler - Event custom element and click event

### ISSUE THREAD

**Issue by niyaza3** [telerik/kendo-react#405]
Hi
We have integrated scheduler in our project. I have a scenario in which I need to add custom element in the event layout and also add a click event which should trigger some data about the event in popover. The Problem I have is
1. Adding custom element into the event structure
2. Adding a click function to the event.

**Comment by kspeyanski** [comment]
Follow up from https://github.com/telerik/kendo-react/issues/402:

This will be possible once we implement the `dayItem`/`timeItem`/`schedulerItem` custom renders. 

Can you please describe what kind of element would you like to add inside the event?

**Comment by niyaza3** [comment]
@kspeyanski We need to add an info icon at the right end of the event block and also increase the height of the event block a little(around 5px).

**Comment by kspeyanski** [comment]
The SchedulerItem render property have been implemented. Please refer to the [SchedulerItem Customization](https://www.telerik.com/kendo-react-ui/components/scheduler/customization/items/item/) article for more information.
