### ISSUE TITLE
Add option to lock the grouping section of the Grid.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#406]
Add the option to lock the grouping section of the Grid.

More details with screenshots here:

https://www.telerik.com/forums/grouping-and-frozen-columns

**Comment by simonssspirit** [comment]
Also requested in 1543844

The request is to be able to lock only a specific header at the top and the others to be scrollable.

**Comment by cbetancourt** [comment]
How do we get traction on this issue? Thank you

**Comment by filipKovachev** [comment]
Also requested in 1584367

**Comment by nstoychev** [comment]
We published this improvement in our development channel. Here you can see how it behaves: https://stackblitz.com/edit/react-zjmvp9?file=app%2Fmain.jsx.

**Comment by vveesseelliinnaa** [comment]
Available as of version [5.10.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#f1407191-3ec7-5f77-b7e8-e7a7305a128c):
https://www.telerik.com/kendo-react-ui/components/grid/grouping/locked-group-headers/
