### ISSUE TITLE
Editor command for applying multiple inline styles at once.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#407]
Editor command for applying multiple inline styles at once.

This can be done:

- Extending an existing command that will accept multiple styles.
- Command that will add a class attribute over an inline element.

More details for the use-case in the ticket: 1443497

**Comment by kdikov82** [comment]
This can be achieved by creating custom command and adding different marks:
[https://www.telerik.com/kendo-react-ui/knowledge-base/add-custom-tools-to-the-editor-and-customize-built-in-tools/](https://www.telerik.com/kendo-react-ui/knowledge-base/add-custom-tools-to-the-editor-and-customize-built-in-tools/)
