### ISSUE TITLE
Ripple Effect is Offset on Checkboxes and Radio Buttons

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#408]
## I'm submitting a...
* Bug report

## Current behavior
Clicking on a Checkbox or Radio Button displays a ripple effect which is offset by about 50%.

## Expected behavior
Ripple effect would display over the top of the button.

## Minimal reproduction of the problem with instructions
Reproducable on demo
https://www.telerik.com/kendo-react-ui/components/ripple/

1. Click on the text of a checkbox.
2. The ripple effect displays incorrectly.

![image](https://user-images.githubusercontent.com/12272970/70106586-f8e54500-1693-11ea-86ad-773610016837.png)

## What is the motivation or use case for changing the behavior?
We have a lot of checkboxes and radio buttons on our forms. We also like the UX of the Ripple effect, as it makes the page feel more responsive.

Browser:
- Chrome (desktop) Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by simonssspirit** [comment]
This is logged in the themes: https://github.com/telerik/kendo-themes/issues/1111

**Comment by Xizario** [comment]
I am going to close this, and we will track it into the themes repo stated above.
