### ISSUE TITLE
The Switch component shows a warning for onChange not being set.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#409]
The Switch component shows a warning for onChange not being set:

Warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.

**Comment by silviyaboteva** [comment]
Fixed in [v3.10.0-dev.202001081019](https://www.npmjs.com/package/@progress/kendo-react-inputs/v/3.10.0-dev.202001081019).
