### ISSUE TITLE
Column Grid Date Editor 

### ISSUE THREAD

**Issue by gemamreza** [telerik/kendo-react#410]
Hi, 
I want to ask, in Grid > Column there are so many properties, and editor is one of those. And in editor it accepts string like "boolean, text, date, numeric". In my case I want to edit the date and time, but editor="date" is not providing time picker, can somebody help me with this issue? 
Thank you

**Comment by simonssspirit** [comment]
@gemamreza  This will require using a custom editor that will render the DateTimePicker:

https://www.telerik.com/kendo-react-ui/components/grid/editing/editing-custom/

**Comment by gabrielcerutti** [comment]
Is there an example of this? I tried to implement it refactoring the DateCell editor sample but for some reason the onChange event is not triggered, so changes are not detected for that column.

This is the component:

```javascript
export const DateTimeCell = props => {
  const {
    dataItem,
    field,
    render
  } = props;
  const isInEdit = field === dataItem.inEdit;
  const value = field && dataItem[field] ? dataItem[field] : new Date();
  const handleChange = e => {
    if (props.onChange) {
      props.onChange({
        dataIndex: 0,
        dataItem: props.dataItem,
        field: props.field,
        syntheticEvent: e.syntheticEvent,
        value: e.target.value
      });
    }
  };
  const defaultRendering = <td>
      {isInEdit ? <div>
          <DateTimePicker value={value} format="yyyy-MM-dd hh:mm:ss a" onChange={handleChange} />
        </div> : value ? value.toISOString().substring(0, 19).replace('T', ' ') : ''}
    </td>;
  return render?.call(undefined, defaultRendering, props);
};
```
