### ISSUE TITLE
Incompatible date format for Kendo Grid and DatePicker

### ISSUE THREAD

**Issue by pajohns** [telerik/kendo-react#411]
## I'm submitting a 
* Bug report 

## Current behavior
When entering a date format of {0:dd/MM/yyyy} for a ColumnData prop, when in edit mode a calendar picker shows the date format as US date of MM/dd/yyyy. 

## Expected behavior
The date should show as dd/MM/yyyy per the requested date format.

## Minimal reproduction of the problem with instructions
1. Create a Kendo grid with one column with following ColumnData:
```
const settlementDate: ColumnData = {
        field: 'settlementDate',
        title: 'Setlement Date',
        format: '{0:dd/MM/yyyy}',
        filterable: true,
        filter: 'date',
        editor: 'date'
    };
```
2. Note that the date is displayed as MM/dd/yyyy
3. Change the format to "dd/MM/yyyy"
4. Note that when in view mode the date is displayed as "dd/MM/yyyy".

## What is the motivation or use case for changing the behavior?
Currently I have to create a custom date cell for every instance of using a date field in my grid which is less than ideal. 

## Environment

Package versions:
@progress/kendo-data-query@1.5.2
@progress/kendo-dateinputs-react-wrapper@2019.4.1014
@progress/kendo-base-component-react-wrapper@2019.2.606
@progress/kendo-drawing@1.6.0
@progress/kendo-dropdowns-react-wrapper@2019.4.1014
@progress/kendo-base-component-react-wrapper@2019.2.606 deduped
@progress/kendo-react-data-tools@3.9.0
@progress/kendo-react-common@3.9.0
@progress/kendo-react-dateinputs@3.9.0
@progress/kendo-date-math@1.2.0
@progress/kendo-react-buttons@3.9.0
@progress/kendo-react-common@3.9.0
@progress/kendo-react-popup@3.9.0
@progress/kendo-react-dropdowns@3.9.0
@progress/kendo-react-common@3.9.0
@progress/kendo-react-popup@3.9.0
@progress/kendo-react-grid@3.9.0
@progress/kendo-react-common@3.9.0
@progress/kendo-react-inputs@3.9.0
@progress/kendo-react-common@3.9.0
@progress/kendo-react-popup@3.9.0
@progress/kendo-react-intl@3.9.0
@telerik/kendo-intl@1.5.2
@progress/kendo-react-pdf@3.9.0
@progress/kendo-file-saver@1.0.7
@progress/kendo-theme-default@4.7.0
@progress/kendo-theme-material@3.5.0
@progress/kendo-ui@2019.3.1113

Browser:
- Chrome (desktop) version 78.0.3904.108

System:
Platform: Windows

Other information:
It appears that there is an incompatibility as to what a text display field requires as opposed to what a date picker requires. For text display it requires a format of '{0:dd/MM/yyyy}' whereas the datepicker requires a format of "dd/MM/yyyy".

**Comment by simonssspirit** [comment]
I have provided an answer to the same question here. Please take a look at it:

https://feedback.telerik.com/kendo-react-ui/1445146-bug-in-react-grid-component
