### ISSUE TITLE
DropdownButton submits the form when clicked

### ISSUE THREAD

**Issue by gordonc247** [telerik/kendo-react#412]
## I'm submitting a...

* Bug report 

## Current behavior
If a DropdownButton is hosted in a form control, the button submits the form when it is clicked.

## Expected behavior
The button should not submit the form since the user is expected to select an option for the dropdown items. I should be able to either set the type of the DropdownButton to "button", or the component should set "type=button" when rendering the button control.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-36hzv1

## What is the motivation or use case for changing the behavior?
Clicking the dropdown button should display a list of actions that a user will then select. If the dropdown submits the form, the user does not have the opportunity to select the required action.

## Environment

Package versions:
```
@progress/kendo-react-buttons@3.9.0
```

Browser:
- Chrome (desktop) version 78
- Firefox version 70

System:
- TypeScript version: 3.6
- Node version: 6.13.2
- Platform:  Windows

**Comment by nstoychev** [comment]
We published a fix our dev channel - https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#toc-3100-dev202001031511.

Here is the updated demo - https://www.telerik.com/kendo-react-ui-develop/components/buttons/dropdownbutton/
