### ISSUE TITLE
Provide an approach to programmatically highlight the series.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#415]
Provide an approach to programmatically highlight the series.

Similar to the Kendo UI toggleHighlight method:

https://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart/methods/togglehighlight

And the Kendo UI for Angular method:

https://www.telerik.com/kendo-angular-ui/components/charts/api/ChartComponent/#toc-togglehighlight

**Comment by simonssspirit** [comment]
Requested again in 1471153
Raising priority.

**Comment by simonssspirit** [comment]
We can combine this with the showTooltip method as well as both are usually needed together when interacting with the legend items:

https://www.telerik.com/kendo-angular-ui/components/charts/api/ChartComponent/#toc-showtooltip

**Comment by simonssspirit** [comment]
requested in 1480219

**Comment by simonssspirit** [comment]
requested again in 1493795, raising priority.

**Comment by nstoychev** [comment]
Here is how to highlight series and show the tooltip - https://stackblitz.com/edit/react-2jmuho?file=app/main.jsx

The [chartInstance object](https://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart#methods) is public but not documented.

**Comment by kkapitanova** [comment]
Requested again in 1513777

**Comment by kkapitanova** [comment]
Requested again in 1523171

**Comment by simonssspirit** [comment]
this is live in the dev channel: https://www.telerik.com/kendo-react-ui-develop/components/charts/chart/chart-instance/
