### ISSUE TITLE
ContextMenu style mismatch with the original designs

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-react#416]
### Problem
Look at the images below. The styling of the first level of the context menu is different in React ContextMenu component:

![image](https://user-images.githubusercontent.com/17604855/70515006-456dcc00-1b3d-11ea-9cb5-de338936706a.png)

![image](https://user-images.githubusercontent.com/17604855/70515128-7e0da580-1b3d-11ea-84ac-a1e1dc69bd0c.png)

![image](https://user-images.githubusercontent.com/17604855/70515160-8bc32b00-1b3d-11ea-8ead-67bf0bf152cb.png)

For reference: https://www.telerik.com/kendo-react-ui/components/layout/menu/context-menu/

### Solution
There are two missing classes in the rendering:
- there should be a k-context-menu class on the ul element (with k-menu class)
- there should be a k-context-menu-popup class on the wrapper element

**Comment by simonssspirit** [comment]
Currently, these styling differences will require adding extra props to the Menu component to allow adding them on the required elements.

We can introduce new className props or a property called context menu (boolean) that will apply the correct classes internally.

**Comment by silviyaboteva** [comment]
Releasing the out-of-the-box context menu component resolves this.
Demo: https://www.telerik.com/kendo-react-ui/components/layout/contextmenu/
