### ISSUE TITLE
Grid Child selection linked with the parent child selection

### ISSUE THREAD

**Issue by Nassefferjeni** [telerik/kendo-react#417]
Is there any way when I click on the header selection of a child grid I can select that parent column grid also?

**Comment by simonssspirit** [comment]
Currently, the selection of the Grid works on a row level.

Still, this can be achieved with a custom cell for the column in question:

https://www.telerik.com/kendo-react-ui/components/grid/api/GridColumnProps/#toc-cell

1) Once the header of the child Grid is selected, set a flag that determines if the column will be selected.
2) Then inside the custom column render add the `k-state-selected` className conditionally based on the flag value.

**Comment by Nassefferjeni** [comment]
@simonssspirit thank you for your response
I found a way to implement it 
I have added a parent_id in the child grid and when I select the child I can know what is the parent that got selected.
