### ISSUE TITLE
Issue while using "change" Event on React Scheduler wrapper

### ISSUE THREAD

**Issue by ravichandrakollu** [telerik/kendo-react#42]
## I'm submitting a bug report on React Scheduler wrapper

* **Bug report** 
**kendo.ui.Scheduler**

## Current behavior

While using "change" Event on kendo.ui.Scheduler when this.destroy() function is called the toolbar on the top still persists (see in https://dojo.telerik.com/UZUsAtuj).
And also in the browser console it shows an error 
```
Uncaught TypeError: Cannot read property 'find' of null
    at init._mouseDownSelection (kendo.all.js:103091)
    at HTMLTableCellElement.<anonymous> (kendo.all.js:103035)
    at HTMLDivElement.dispatch (jquery-1.12.4.min.js:3)
    at HTMLDivElement.r.handle (jquery-1.12.4.min.js:3)

```
## Expected behavior

When this.destroy() is called in "change" Event the whole scheduler component should be removed. And no error like init._mouseDownSelection is expected.
## Minimal reproduction of the problem with instructions

https://dojo.telerik.com/UZUsAtuj
**Expected solution as per my understanding**

__mouseDownSelection event in kendo.all.js has the line of code shown below. Removing this line could be a potential solution.
```this.toolbar.find('ul > li').removeClass(FOCUSEDSTATE);```

## What is the motivation or use case for changing the behavior?

We want to try Kendo Scheduler React wrapper for a project in our organisation. 
When I am using "change" Event on the Scheduler React wrapper I want to leave the Scheduler React component and display another component without error and breaking the component.
## Environment

Package versions:

```
   "@progress/kendo-scheduler-react-wrapper": "^2018.2.612",
   "@progress/kendo-theme-default": "^2.53.2",
   "@progress/kendo-ui": "^2018.2.613"
```

Browser:

- Safari (iOS) version 11.2, 11.4

System:
- Node version: v9.5.0
- npm: 6.1.0

**Comment by Xizario** [comment]
Since we are working on new native scheduler, I am closing this. You can still follow the related item if you are interested if this gets fixed from the jquery side.
