### ISSUE TITLE
OnRowDoubleClick is not working

### ISSUE THREAD

**Issue by Nassefferjeni** [telerik/kendo-react#420]
I tried adding the onRowDoubleClick event but it doesn't seem to be working. 
https://www.telerik.com/kendo-react-ui/components/grid/api/GridRowDoubleClickEvent/

It is in the documentation but I don't know why it is not being triggered.

this is how I added the double click event:
` <Grid sortable={ sortable } filterable={ filterable } groupable={ groupable } reorderable={ reorderable } pageable={ pageable } onRowDoubleClick={ this.test }>`

and this is my test function:
`test = () => { console.log('test') }`

**Comment by simonssspirit** [comment]
@Nassefferjeni 
The event is introduced in version 3.7.0
Please check the version of the Grid in the package.json and if it is an older one, please update it.

**Comment by Nassefferjeni** [comment]
@simonssspirit 
it's an old version. I will update right now
Thank you

**Comment by Nassefferjeni** [comment]
@simonssspirit when I updated the kendo grid version to 3.7.0 the resizable event doesn't seem to be working, any idea why ?
