### ISSUE TITLE
Resizable doesn't work

### ISSUE THREAD

**Issue by Nassefferjeni** [telerik/kendo-react#422]
When I was using version 3.4.0 for the kendo grid the resizable was working just fine.
When I upgraded to the version 3.7.0 as @simonssspirit suggested so I can make onRowDoubleClick work, the resizable feature of the kendo grid stopped working.

**Comment by simonssspirit** [comment]
After version 3.7.0 the Grid has a new dependency on '@progress/kendo-react-data-tools'.

Please install it, and the resizing should work as expected:

https://www.telerik.com/kendo-react-ui/components/grid/get-started/#toc-dependencies

**Comment by Nassefferjeni** [comment]
@simonssspirit  I saw that online, I installed it but the resizing is still not working.

this is my package.json:
`    "@progress/kendo-react-charts": "3.6.0",
    "@progress/kendo-react-data-tools": "3.7.0",
    "@progress/kendo-react-dateinputs": "3.6.0",
    "@progress/kendo-react-dropdowns": "3.6.0",
    "@progress/kendo-react-excel-export": "3.6.0",
    "@progress/kendo-react-grid": "3.7.0",
    "@progress/kendo-react-inputs": "3.6.0",
    "@progress/kendo-react-intl": "2.8.0",
    "@progress/kendo-react-tooltip": "3.4.1",
    "@progress/kendo-react-treeview": "3.4.1",`

this is the kendo grid rendering:
`import { Grid } from '@progress/kendo-react-grid';`
`<Grid sortable={ sortable } filterable={ filterable } groupable={ groupable } reorderable={ reorderable } pageable={ pageable }
                              resizable={ resizable } selectedField="selected" expandField="expanded" data={ dataResult } { ...parentDataState }
                             onColumnResize={ (event) => (this._onColumnResize(event, false)) }
                              style={ { flex: '1 0 auto', maxHeight: maxHeight ? maxHeight : height } }>
                            { this._renderGridElements() }
                        </Grid>`

**Comment by Lerchar** [comment]
I was using version 3.9.0 for the kendo grid, and add dependency '@progress/kendo-react-data-tools' which version 3.9.0 too. but the resizing doesn't  woking. What should I do ?  This is all my depenndencics: "@progress/kendo-data-query": "^1.5.2",
    "@progress/kendo-drawing": "^1.6.0",
    "@progress/kendo-react-animation": "^3.9.0",
    "@progress/kendo-react-data-tools": "^3.9.0",
    "@progress/kendo-react-dateinputs": "^3.9.0",
    "@progress/kendo-react-dropdowns": "^3.9.0",
    "@progress/kendo-react-grid": "^3.9.0",
    "@progress/kendo-react-inputs": "^3.9.0",
    "@progress/kendo-react-intl": "^3.9.0"
