### ISSUE TITLE
Grid Column : editable  change base on condition

### ISSUE THREAD

**Issue by lordesiah** [telerik/kendo-react#423]
Hi everyone 
i have a grid and i want to edit  my GridColumn  .
so i active grid editable and etc . in normal situation everything is okay 
but i need 'editable' attribute for each field base on condition 
something like this : 
i want field 'age'  change when my condition is true . 
how should i do this ??
`
<Grid  data={data} 
 editField="inEdit"
 onItemChange={this.itemChange} >
<GridColumn field="Id"  editable={false}/>
<GridColumn field="name"   editable={true}/>
<GridColumn field="family"  editable={true} />
<GridColumn field="age"   editable={(props)=>(props.dataItem.age>40 && props.dataItem.Id>0 ) }/>
</Grid>
`

**Comment by simonssspirit** [comment]
@lordesiah This can be achieved with the **cell** render property.
This will provide a render function for each cell. In that function, there is access to all item values, and you can determine to render an editor or a read-only cell.

**Comment by lordesiah** [comment]
> @lordesiah This can be achieved with the **cell** render property.
> This will provide a render function for each cell. In that function, there is access to all item values, and you can determine to render an editor or a read-only cell.

Thanks @simonssspirit . We can do it but when I use cell and check it there , I have another problem 
When I use cell for format 'text'  after every change in textbox cursor lost , we resolve it with force focus after every change but the big problem is here  when your grid has alot of column and scroll to left or right when we focus on text box after every change we sense the page move fast (this happen in chrome not firefox). Because of these problem I wanted to know is there a way to use condition for property editable or not

**Comment by simonssspirit** [comment]
@lordesiah sorry for the late reply. This is a known case when the cell is set as a function inside render. React recreates the component each time and the focus is lost

Please use the approach shown in our documentation:

https://www.telerik.com/kendo-react-ui/components/grid/cells/#toc-customization

Please have in mind that we recommend using the support system for urgent issues as there is a guaranteed 24 business hours response time.
