### ISSUE TITLE
format prop on Date/Time components has wrong type

### ISSUE THREAD

**Issue by stefanhamburger** [telerik/kendo-react#424]
## I'm submitting a...
* Bug report

## Current behavior
Various date and time-related components have a `format` prop, which is defined to be of type `string`. This prop is directly passed to the [`formatDate()` function](https://github.com/telerik/kendo-intl/blob/develop/src/dates.d.ts#L100) from `@telerik/kendo-intl`, which accepts both strings and objects (see [documentation](https://github.com/telerik/kendo-intl/blob/master/docs/date-formatting/index.md#standard)).

Ignoring the type definition and passing an object to the `format` prop renders the component just fine but has the following problems:
- The PropTypes of `format` are set to `string`, so at runtime React will check the type and fill the DevTools console with warnings.
- TypeScript throws a type error, and you have to cast the object to `any` to get it compiled: `<DatePicker format={{ date: "short" } as any } />`

## Expected behavior
Please update the type definitions (`.d.ts` file) of the various components (`DateInputProps`, `DatePickerProps`, `DateRangePickerProps`, `DateRangePickerDateInputSettings`, etc.), so that the type definition of the `format` prop allows not just strings, but also objects:

```
// currently set to:
format?: string;
// should be this instead:
format?: string | DateFormatOptions;
```

(where `DateFormatOptions` is imported from `@telerik/kendo-intl`, so it matches the signature of the [`formatDate()` function](https://github.com/telerik/kendo-intl/blob/develop/src/dates.d.ts#L100))

Also, please update the PropTypes accordingly.

## Minimal reproduction of the problem with instructions
Stackblitz example: https://stackblitz.com/edit/react-8prlmu?file=app/main.jsx

As you can see, I've used a couple Date selector components with various `format` props. As you can see, the prop accepts an object just fine and renders the component as expected. However, when hovering over the prop, the tooltip says that this prop is of type string.

When opening DevTools, you can see various "Failed prop type" warnings in the console even though the components render just fine.

## What is the motivation or use case for changing the behavior?
For our use case, the DatePicker component has the wrong default format. When overriding the format, we do not want to set a format manually (like `dd.mm.y`); we want the format to be taken from the locale's date format.

The workaround of casting to `any` is unacceptable because it fills the console with too many PropTypes error messages. Therefore, please update the type definitions and the PropTypes so we can pass an object to `format` without issues.

## Environment

- React
- TypeScript
- Kendo React

**Comment by simonssspirit** [comment]
@kspeyansk please take a look at this.

**Comment by kspeyanski** [comment]
Hello @stefanhamburger ,

The issue has been resolved in the latest [dev](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#toc-3120-dev202002250859) version of the `@progress/kendo-react-dateinputs` package.

**Comment by stefanhamburger** [comment]
Tested it today and it works great, thanks!
