### ISSUE TITLE
React grid component don't render properly under shadow-dom.

### ISSUE THREAD

**Issue by AndreyLuzinov** [telerik/kendo-react#425]
I'm submitting a 
* Bug report

## Current behavior
When I render grid from sample code snippet under shadow root component I've got this:
![image](https://user-images.githubusercontent.com/8442311/71180941-41038a80-2284-11ea-8c88-649afc555728.png)

## Expected behavior
If I remove shadow root I get this:
![image](https://user-images.githubusercontent.com/8442311/71180598-8ffcf000-2283-11ea-85cd-93ff8a225f6c.png)

## Minimal reproduction of the problem with instructions
Just place grid with filters under shadow dom.

## What is the motivation or use case for changing the behavior?
Shadow dom is increasing trend. You should follow it.

**Comment by Xizario** [comment]
Are you using `react-shadow-root`? If this is the case, loading the styles using `link` as shown in their documentation should work for our theme as well.

**Comment by AndreyLuzinov** [comment]
The real problem is that WebComponentsIcons font are not working inside shadow-dom.
If I attach all.css kendo react styles into root html document then all works fine but if I do the same inside my shadow-root component then icons are broken like on provided images. Please help.

**Comment by Xizario** [comment]
@telerik/kendo-react-team, some ideas here?

**Comment by AndreyLuzinov** [comment]
Looks like it's browser issue not library specific. font-face are not working when declared inside shadow-dom.

**Comment by simonssspirit** [comment]
Yes, currently there are limitations for the font icons used in the shadow dom:

https://stackoverflow.com/questions/28794189/icon-fonts-in-shadow-dom

**Comment by mathiasmah** [comment]
A feasible solution for us would be to include only the iconsets outside of the shadow-dom, this way the icons would also be available inside the shadow-dom.
Is it possible to receive a css file that only contains the icon fonts?

**Comment by kdikov82** [comment]
[Switching to the SVG icons ](https://github.com/telerik/kendo-react/issues/626)
