### ISSUE TITLE
Export nested data grid with the parent grid

### ISSUE THREAD

**Issue by Nassefferjeni** [telerik/kendo-react#427]
I am using kendo grid export with a grid that has a detail component ( that is also a grid itself )
the problem is that I want to export the nested data with the parent's data directly, is that possible?

**Comment by vladimirivanoviliev** [comment]
You can check the following KB for more information about how to achieve the desired behavior:
- https://www.telerik.com/kendo-react-ui/knowledge-base/excel-export-of-both-parent-and-child-grid-data/

**Comment by Nassefferjeni** [comment]
So I checked that one but the workbook doesn't seem to be working: 
package.json:     `"@progress/kendo-react-excel-export": "3.9.0"`
I imported it like this: `import { ExcelExport, ExcelExportColumn, Workbook } from '@progress/kendo-react-excel-export';
`

But I get this error: 
`Attempted import error: 'Workbook' is not exported from '@progress/kendo-react-excel-export'.`

any idea @vladimirivanoviliev?

**Comment by Xizario** [comment]
@Nassefferjeni 
Looks our KB is a bit wrong. Here are the correct imports:
```ts
import { ExcelExport, KendoOoxml } from '@progress/kendo-react-excel-export';
```

Then you can use this: ```new KendoOoxml.Workbook(...)```

Here is an example:
https://stackblitz.com/edit/react-gg7jen?file=app/main.jsx

**Comment by Nassefferjeni** [comment]
@Xizario I don't know why but this stopped working: 

`let workbook = this.exporter.workbookOptions();`

Now I'm getting this message: 

![image](https://user-images.githubusercontent.com/33683191/90510746-66b69b80-e153-11ea-8285-36b83e9e0a1c.png)

I can't even initialize the workhook

**Comment by klsathish** [comment]
but here provided for react.. how about jquery
