### ISSUE TITLE
January 2019 is missing from the Calendar

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#428]
January 2019 is missing from the Calendar:

https://www.telerik.com/kendo-react-ui/components/dateinputs/calendar/

![image](https://user-images.githubusercontent.com/11087921/71657850-47950600-2d4a-11ea-9481-1295b9e3e2f8.png)

**Comment by Xizario** [comment]
https://stackoverflow.com/questions/55461619/how-can-i-add-jan-to-the-kendo-datepicker-angular2-pop-up-left-navigation-it

**Comment by simonssspirit** [comment]
After additional research, I can confirm that this is expected as the Year is actually the placeholder for January.

If you would like to customize it, please use the NavigationItem render:

https://www.telerik.com/kendo-react-ui/components/dateinputs/calendar/custom-rendering/#toc-items-in-the-side-navigation

If this affects other components that use the Calendar as the DatePicker, use a custom Calendar with a template:

https://www.telerik.com/kendo-react-ui/components/dateinputs/datepicker/custom-rendering/#toc-customizing-the-calendar

**Comment by Xizario** [comment]
cc: @telerik/kendo-ux
