### ISSUE TITLE
The Grid editor takes the format from the column directly.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#43]
Currently, the format property of the column is applied only to the read-only data inside the cell. 
Based on the following ticket: 1174726 there is a proposal the format property to be passed down the editor as well.

The current approach is making a custom cell and modifying the editor directly as shown here: https://stackblitz.com/edit/react-dwndnu?file=index.js

**Comment by Xizario** [comment]
A bit more simplified example: https://stackblitz.com/edit/react-grid-custom-cell

**Comment by Xizario** [comment]
I am closing this, since in general the 2 types of formats have incompatibilities. So passing them to the editors will do more problems than it solves. The workaround is simple enough to be used per case if needed.
