### ISSUE TITLE
Mouse events not working on a custom component in header cell of Kendo grid

### ISSUE THREAD

**Issue by anujm249** [telerik/kendo-react#431]
* Bug report

## Current behavior

I have created a custom text field component for search and passed through the props (headerCell) of Column of Grid.
```
HeaderCellComponent = props => (
    <div className="head-dash">
      <span>{DASHBOARD_WIDGET_NAME[props.field].heading}</span>
      <div>
        <input
          type="text"
          key={props.field}
          onChange={event => this.props.onFilterChange(event.target.value)}
          value={this.props.filterValue}
          className="filter-inp"
        />
        {this.props.filterValue ? <span id="u347_img" className="img-close k-icon k-i-close" src={SearchIcon} onClick={() => this.props.onFilterChange('')} /> :  <img id="u347_img" className="img " src={SearchIcon} />}
      </div>
    </div>
  );
```
Usage : 

```
<Grid  data={this.props.recentQuote}>
          <Column
              field={this.props.widget}
              title="Quoting List"
              filterable={true}
              cell={props => this.props.renderCell(props, this.props.widget)}
              headerCell={this.HeaderCellComponent}
          />
</Grid>
```
Mouse click event is not working on the input field, focus not comes over the input and hence user can not type, although when user right click, input focus appears.

On looking into the devtool's element, it is observed that on click, it is adding touch-action: none.
Refer screenshot.

![Capture](https://user-images.githubusercontent.com/5738969/71883798-2a52a400-315d-11ea-9586-bee651cb934f.PNG)

## Expected behavior

It should allow click events.

## Environment

Browser:

- Chrome (desktop) version 79.0

System:
- Node version: 10.16.0
- Platform:  Windows 10

**Comment by simonssspirit** [comment]
@anujm249 Thank you for reporting this:
1) This seems to be an older version as we changed to set the style to the row not the inside elements.
2) Still, this is causing an issue as we internally prevent the click.
3) There is a workaround to programmatically focus the input on click, but it is not ideal:

https://stackblitz.com/edit/react-p6rq3a?file=app%2Fmain.jsx

We will add this to our backlog and plan it accordingly.

**Comment by simonssspirit** [comment]
reported again in: 1479306 raising priority.

**Comment by InaGlushkova** [comment]
The fix is included as part of the release:
[3.17.0-dev.202009021539](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#toc-3170-dev202009041314)
