### ISSUE TITLE
Custom Column menu is not being displayed when I put kendo grid inside a drawer

### ISSUE THREAD

**Issue by Nassefferjeni** [telerik/kendo-react#433]
I have implemented the custom column menu in my kendo grid, the problem now is when I put the kendo grid inside a drawer the custom column doesn't seem to be working as expected.

This is the kendo grid custom column working fine when it's normal:
![2](https://user-images.githubusercontent.com/33683191/72076174-6b7dbc00-32f5-11ea-92c1-69b8545a32ff.PNG)
![4](https://user-images.githubusercontent.com/33683191/72076175-6c165280-32f5-11ea-88f3-739f4b12e45d.png)

as you can see the element is showing just fine

now, when I tried it inside a drawer, it doesn't seem to be showing: When I click on 3 dots the element is being added to the elements(devTools) (for just a 1 sec) then it's gone.
![1](https://user-images.githubusercontent.com/33683191/72076380-b992bf80-32f5-11ea-9c55-bf69c62a1b97.PNG)
![3](https://user-images.githubusercontent.com/33683191/72076381-b992bf80-32f5-11ea-8719-9a3bb0ad6401.PNG)

The difference is the k-animation-container-shown which is not being added to the div when it's on a drawer.

Any idea on how to make it work?

**Comment by Nassefferjeni** [comment]
@simonssspirit @vladimirivanoviliev I am not trying to push or anything, but if an issue doesn't get a response, does that mean it is out of the kendo? or I just need to wait for someone to answer me?

**Comment by simonssspirit** [comment]
@Nassefferjeni, as I can see that the issue occurs inside a custom Drawer component, is it possible to send us a runnable example so we can inspect it.


I assume that something inside the modal is stealing the focus a causing the ColumnMenu blur, which is closing it. Sounds a like case here: 
https://www.telerik.com/forums/datepicker-closes-directly-when-used-in-material-ui-dialog

**Comment by Nassefferjeni** [comment]
Thank you very much. 
I used the material ui solution because it was forcing the customColumn menu to not show. 
I added a prop: `disableEnforceFocus `in the drawer and added a z-index to the class: `.k-animation-container` and it worked.

**Comment by stevenduong-vincere** [comment]
@Nassefferjeni 

i was faced this issue and spent much to solve it.
your solution help me a lot save me much time.

thanks
