### ISSUE TITLE
TreeList cell

### ISSUE THREAD

**Issue by SMaverick78** [telerik/kendo-react#434]
How can I get the column number in the tree list? And can be done in ` const columns = [{Field: field === (logical), title: 'name ' }]; `.   If you tell me it will be very good

**Comment by simonssspirit** [comment]
@SMaverick78 I can assume that you are trying to get the column index. Could you please specify at which point you need that column index? On some of the events or?

Please have more details and I will be happy to assist.

**Comment by SMaverick78** [comment]
Thanks very much. I did it.
