### ISSUE TITLE
TreeList  icon custom Expand

### ISSUE THREAD

**Issue by SMaverick78** [telerik/kendo-react#435]
Hello! I have a question about the expand icon. As far as I understand it can be changed using css. It is possible to replace the icons material-ui ?
In the screenshot below I highlighted the icons with blue dashes.
![ExpandIcon](https://user-images.githubusercontent.com/15866632/72332956-0696dd00-36cc-11ea-810a-baff1f15f1e0.PNG)

**Comment by nstoychev** [comment]
Here is an example showing how to modify the expand/collapse cells rendering:
https://stackblitz.com/edit/react-4wlxeb?file=app/main.jsx

Here is the list of the KendoReact icons that you can also use: https://www.telerik.com/kendo-react-ui/components/styling/icons/#toc-list-of-font-icons

**Comment by SMaverick78** [comment]
Thank you very much for your response. Another small question is how can I find out the total number of columns in the entire table in a custom cell?

**Comment by SMaverick78** [comment]
Thank you very much for your response.
