### ISSUE TITLE
Tooltip opened with openDelay can stay open even after the onMouseOut event.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#436]
Tooltip opened with openDelay can stay open even after the onMouseOut event.

This occurs as the Tooltip is opended internally after that delay, which can happen after mouseout if the user moves the mouse fast enough.

The workaround is to set the openDelay prop to 0.

**Comment by simonssspirit** [comment]
Reported again in: 1450981

**Comment by simonssspirit** [comment]
Reported again in 1461295. 
Raising priority.

**Comment by ChristianGilmanKH** [comment]
We also experienced this problem and need the fix for our products.

Thanks,
Christian

**Comment by Xizario** [comment]
Fixed in 3.13.0
