### ISSUE TITLE
The default property of the DropDown is not changed dynamically.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#44]
The default property of the DropDown is not changed dynamically.

https://next.plnkr.co/edit/1yB8JQSjGfVlZ0RU

**Comment by nstoychev** [comment]
This case works if `null` is used for a value of the defaultItem instead of `-1`.
https://next.plnkr.co/edit/31mMoQOeRka3CJJR

**Comment by nstoychev** [comment]
We have publish version 2.0.0 where the issue is resolved. Release notes can be found here: https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/.
