### ISSUE TITLE
TreeList custom Filter Rows

### ISSUE THREAD

**Issue by SMaverick78** [telerik/kendo-react#440]
Hello! You can tell me how I can customize Filter Rows in Treelist. I will be very grateful for the example. I marked them on the screenshot.
![TreeList custom Filter Rows](https://user-images.githubusercontent.com/15866632/72433694-f9045480-37aa-11ea-9259-f80865b25ebb.PNG)

**Comment by nstoychev** [comment]
You should pass the custom filter row to the TreeList [filterRow](https://www.telerik.com/kendo-react-ui/components/treelist/api/TreeListProps/#toc-filterrow) prop. Here is an example: https://stackblitz.com/edit/react-drtwxy?file=app%2Fmain.jsx
