### ISSUE TITLE
TreeList if сolumn custom field.

### ISSUE THREAD

**Issue by SMaverick78** [telerik/kendo-react#443]
Hello!  I have an object property in the employees array. Which are not described in the columns array with objects as field properties. To do this, I add a custom mycell cell. And I set the condition `const cellData = dataItem[field] | / dataItem.nameTest;` Then I add TreeList / Editing / Inline When editing a row in my cells where the condition  `const cellData = dataItem[field] || dataItem.nameTest; ` no value appears in the input field. I add the link as an example and a screenshot below. How can I fix this? I will be grateful for your help in solving my problem.
https://stackblitz.com/edit/react-ob8y4c?file=app%2Fmain.jsx
![01](https://user-images.githubusercontent.com/15866632/72507840-bcd9fe00-3855-11ea-85fc-530dd85e08f4.PNG)

**Comment by simonssspirit** [comment]
@SMaverick78 Thank you for the example. I observed it, but I did not saw any editing in it.

I added editing to the first row and used the same custom cell to render a custom editor:

https://stackblitz.com/edit/react-ob8y4c-rm9z3z?file=app%2Fmain.jsx

The editCell render prop can also be used if you want to separate the read-only from the editing logic.

Also, please have in mind that we have a dedicated support service with the guaranteed response time. We can recommend using the support system for questions connected with the components. as we are monitoring it daily.

**Comment by simonssspirit** [comment]
Closing the questions seems resolved. Please re-open if needed.
