### ISSUE TITLE
TreeList  / Columns  / Multi-Column Headers  with filtering rows

### ISSUE THREAD

**Issue by SMaverick78** [telerik/kendo-react#444]
Hello! I have a problem when using together TreeList  / Columns  / Multi-Column Headers  with filtering rows. The problem is that not all columns display filtering. How this can be corrected. I attach a link to the example . 

> https://stackblitz.com/edit/react-xp1chh?file=app%2Fmain.jsx

And below is a screenshot for understanding.

![filter cell](https://user-images.githubusercontent.com/15866632/72519291-1ba87300-3868-11ea-8e67-d19f698fe06f.PNG)

**Comment by nstoychev** [comment]
@SMaverick78 - Please check the following example: https://stackblitz.com/edit/react-xp1chh-ywq79t?file=app%2Fmain.jsx.

I've added a custom filterRow which renders the filter cells correctly.

**Comment by SMaverick78** [comment]
Thank you so much.

**Comment by nstoychev** [comment]
We have published a fix in our dev channel. Here you can see how it behaves - https://stackblitz.com/edit/react-xp1chh-7aeqg9?file=app/main.jsx

**Comment by Xizario** [comment]
Fixed in `3.11.0`
