### ISSUE TITLE
TreeList  / custom headerCell 

### ISSUE THREAD

**Issue by SMaverick78** [telerik/kendo-react#445]
Hello! I add a property to the columns array object. 
`const columns = [
  { 
    field: 'name',
    title: 'Name',
    width: 400,
    expandable: true,
    color: 'red', // The property I want to get.
    headerCell: HeaderCustomCell
  },
];`
. And I can't get it props in headerCell customization. If there is a way to get props from the columns array object?

I attach a link to the example and a screenshot.
https://stackblitz.com/edit/react-xp1chh-fygorx?file=app%2Fmain.jsx
![custom props header](https://user-images.githubusercontent.com/15866632/72525074-603a0b80-3874-11ea-8517-96094c4473d5.PNG)

**Comment by simonssspirit** [comment]
I updated the example. Additional props can be passed by using a custom function which will return the default props plus additional props:

https://stackblitz.com/edit/react-xp1chh-2zyhzn?file=app%2Fmain.jsx

**Comment by simonssspirit** [comment]
React have an official way to access information on a different level, called Context. This can also be an option to access different information across components:

https://reactjs.org/docs/context.html
