### ISSUE TITLE
Custom Cell + div disables the onRowClick

### ISSUE THREAD

**Issue by Nassefferjeni** [telerik/kendo-react#446]
So I using the custom cell render in kendo grid.
At first, this was my render of the cell:
```
 cell: ({ value}) => {
  <td title={ value }>
     { value }
  </td>
}

```
with this, the onRowClick event is working fine.

But then I wanted to make  a custom tooltip so I changed the cell render to this:

```
cell: ({ value }) => {
  <td>
    <Tooltip title={ value } classes={ { tooltip: { backgroundColor: 'blue' } } }>
      <div>
        { value }
      </div>
    </Tooltip>
  </td>
}
```

With this, the onRowClick event doesn't get triggered with I hover over the cell.

**Comment by simonssspirit** [comment]
@Nassefferjeni Please check the following forum post on the same subject:

https://supportheroes.telerik.com/ticket/1448590

Also, please have in mind that we have a dedicated support system for questions connected with the product. In the system, there is required response time and the answers are faster:

https://www.telerik.com/kendo-react-ui/support/

4. Use our official support channel and submit [a support ticket](https://www.telerik.com/account/support-tickets)

**Comment by Nassefferjeni** [comment]
@simonssspirit the website is not working: 
![Capture](https://user-images.githubusercontent.com/33683191/72722325-5834e100-3b7e-11ea-9bae-5437ac9e7bf7.PNG)

And my account doesn't seem to have the right privilege:
![1](https://user-images.githubusercontent.com/33683191/72722397-81ee0800-3b7e-11ea-856e-e01dd1f0341a.PNG)

**Comment by simonssspirit** [comment]
@Nassefferjeni Please have in mind that KendoReact is a commercial product. If you had a KendoReact license in the past, please note that only the versions that were released during the valid license can be used in production.
