### ISSUE TITLE
SchedulerItem onFocus and onBlur - only work as onClick - not mouseOver

### ISSUE THREAD

**Issue by kachihro** [telerik/kendo-react#448]
## I'm submitting a...
BUG

* Bug report 

## Current behavior
Within the scheduler component, I'm trying to use the onFocus to show the popup for an item.
But - the example for onFocus is actually working as onClick.

https://www.telerik.com/kendo-react-ui/components/scheduler/items/item/#toc-attaching-callback-handlers

It also means that I cannot DOUBLE-CLICK on an item, as the click is captured (rather than onFocus)

## Expected behavior
onFocus and onBlur work as expected - with mouseover/mouseout.
Not needing to click.

## Minimal reproduction of the problem with instructions
This example doesn't work as expected.   onFocus/onBlur
https://stackblitz.com/run/?file=app%2Fmain.jsx

## What is the motivation or use case for changing the behavior?
Need to have a popup, showing some extra details, in the mouseover

**Comment by kachihro** [comment]
JS code looks like it's using "PointerDown" ;

this._pointerdown = function(e) {
                e.isPrimary && 0 === e.button && (i(document, "pointermove", t._pointermove),
                i(document, "pointerup", t._pointerup),
                i(document, "pointercancel", t._pointerup),
                i(document, "contextmenu", s),
                t._pressHandler(e))
            }

**Comment by kspeyanski** [comment]
Hello @kachihro ,

The `SchedulerItem` component has a `tabIndex` attribute set to `-1`. This means that the element is focusable, either through `click` event, or programatic `focus()` call. This behaviour is needed so we are able to provide keyboard-navigation.

As for the `double-click`, one should simply extend the [editable](https://www.telerik.com/kendo-react-ui/components/scheduler/api/SchedulerProps/#toc-editable) prop and enable `edit`. This way, the double-click functionality will be enabled. Please refer to line `100` in the following example: https://stackblitz.com/edit/react-wypyuv?file=app/main.jsx


If your use case requires you to show popup on `mouse-over`, please let me know and we will export a pair of `onMouseEnter` - `onMouseLeave`, `onMouseOver` - `onMouseOut`.

Please let me know if you need further assistance, or if you would like to request additional `handlers` exposed for the `SchedulerItem`.

**Comment by kachihro** [comment]
Yes - we need to have a mouse over - that would be great.   And a double click also - to edit the item ??

(sent from iPhone)

chris o'connor | senior technical specialist | kachihro | 0403 733 723
________________________________

**Comment by kspeyanski** [comment]
Okay, with the next version `dev` version of the `kendo-react-scheduler` package, we will export the requested `onMouseEnter`, `onMouseLeave`, `onMouseOver` and `onMouseOut` callbacks. While i can not give an exact estimate, i believe it will be by the end of this week, or the beginning of the next. Will update this issues once it has been released. 

As for the double click, please refer to the example i provided in my previous comment.

**Comment by kachihro** [comment]
Thanks - but the edit box just brings up the 'default' edit.   I have some additional fields - it would be good to have a custom edit form - like this in Angular - using kendoSchedulerEditDialogTemplate

https://www.telerik.com/kendo-angular-ui/components/scheduler/editing/custom-reactive-editing/

**Comment by kspeyanski** [comment]
Hello @kachihro ,

Please excuse me for the delayed response. 

We've released a `dev` version of the `@progress/kendo-react-scheduler` package, where the request `onMouse*` callbacks have been implemented. You can observe the additional `props` API here:
https://www.telerik.com/kendo-react-ui-develop/components/scheduler/api/SchedulerItemProps/#toc-onmouseenter

As for customising the edit form, we're looking into ways to allow easy customisation of the edit field, but i've opened a new issue for it, so it's easy to track:
https://github.com/telerik/kendo-react/issues/542
