### ISSUE TITLE
TreeList. Cancel rendering of the TH tag in table header cells.

### ISSUE THREAD

**Issue by SMaverick78** [telerik/kendo-react#449]
It is possible to cancel the rendering of the TH tag in the table header. When adding your custom cell to the table, you need to specify the TD tag.

```
class MyCell extends React.Component {
    render() {
        const { dataItem, field } = this.props;
        const cellData = dataItem[field];
        return (
            <td>
                <span style={{ color: cellData ? 'green' : 'red' }}>{String(cellData)}</span>
            </td>
        );
    }
}
```

When adding your custom cell to the table header, you do not need to specify the TH tag. If you can replace caps in a custom table cell with your own TH tag? This is necessary for styling the TH tag.

**Comment by simonssspirit** [comment]
@SMaverick78 currently, only the inside of the th element can be replaced. Placing custom th element can easily break the rendering of the Grid. I can suggest using CSS to style the th element.

**Comment by SMaverick78** [comment]
This will do. And how you can make your custom cell style TH in the table header. If you add an example I will be very grateful to you.

**Comment by simonssspirit** [comment]
This is an example that customizes the th using CSS:

https://stackblitz.com/edit/react-dmjhin?file=app%2Fmain.jsx
