### ISSUE TITLE
Negative 0 should be considered smaller then 0 when the min prop is set to 0.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#450]
Negative 0 should be considered smaller than 0 when the min prop is set to 0.

If the user sets the min prop to 0, when -0 is typed, it should be considered invalid.

**Comment by Xizario** [comment]
`-0` is not smaller than `0` So the edge case is entirely formatting issue and can be handled by using the same format for negative and positive numbers, thus -0,0,+0 will be always 0 for example `format="##,#;##,#"`
