### ISSUE TITLE
PageSizes in grid throwing error when setting to false

### ISSUE THREAD

**Issue by a2441918** [telerik/kendo-react#453]
## I'm submitting a...

* Bug report 

## Current behavior

if pageSizes is set to false in grid, I get this.props.pageSizes.slice is not a function.

## Expected behavior

Should not display pageSizes
## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/react-4ytgfj

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by nstoychev** [comment]
Fixed in the [dev channel](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#toc-3110-dev202001291608) - https://stackblitz.com/edit/react-4ytgfj-ucsgua.

**Comment by a2441918** [comment]
Thanks
