### ISSUE TITLE
DropDown value and text fields to be set from complex objects.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#46]
Currently, the DropDowns can be bound only to flat data.

There are cases where the desired text or value field could be placed inside a complex object field.

We should consider making an enhancement to support binding to a complex data object as well.

**Comment by mitagg** [comment]
What will be the value of the textField prop then - something with a dot notation `foo.bar`?

**Comment by nstoychev** [comment]
@mitagg - Yes, we will use dot notation. Here is how the textField value will look like.
```
<DropDownList
	textField="Category.CategoryName"
	data={[
		{
			"ProductID" : 1,
			"ProductName" : "Chai",
			"Category" : {
				"CategoryID" : 1,
				"CategoryName" : "Beverages"
			}
		}, {
			"ProductID" : 2,
			"ProductName" : "Chang",
			"Category" : {
				"CategoryID" : 1,
				"CategoryName" : "Beverages"
			}
		}
	]}
/>
```

**Comment by nstoychev** [comment]
We have publish version 2.0.0 where the issue is resolved. Release notes can be found here: https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/.
