### ISSUE TITLE
Popup with NumericTextBox error

### ISSUE THREAD

**Issue by kanoshin** [telerik/kendo-react#463]
## I'm submitting a...

* Bug report 

## Current behavior

During rendering if Popup has NumericTextBox there is a warning in console saying:
```
suppress-context-warnings.js:35 Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
```
## Expected behavior

No warning is shown
## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-wxkhvw?file=app/main.jsx

## What is the motivation or use case for changing the behavior?

Please consider to remove the usage of `ReactDOMServer.renderToStaticMarkup` from Popup component code because it is a hacky solution. 
In order to get HTML markup of popup element you can Render popup to the DOM element which is not yet added to the document and then take that element inner HTML.

**Comment by TrevorHerr** [comment]
Any movement on this? We cannot use the popup because of it, it is causing issues with the styles being re-injected.

**Comment by simonssspirit** [comment]
Reported again in 1462895

Raising priority.

**Comment by nstoychev** [comment]
Resolved in dev channel - https://stackblitz.com/edit/react-wxkhvw-8pcnwj?file=app%2Fmain.jsx
