### ISSUE TITLE
Window component onResize event height property typo

### ISSUE THREAD

**Issue by timglass** [telerik/kendo-react#466]
## I'm submitting a...
* Bug report 

## Current behavior

The [KendoReact Window ](https://www.telerik.com/kendo-react-ui/components/dialogs/window/) component has an onResize event, which should provide the left, top, width and height values of the resized window. This event does not correctly provide the new height value in the "height" property, instead there is a typo and this property is named "hight"

## Expected behavior
The onResize event to have a property named "height" instead of "hight"

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/react-drqhg3

Main.jsx - line 25 has been updated with the current incorrect property. Line 26 event is now logged to the console to show hight property is being returned instead of "height"

## What is the motivation or use case for changing the behavior?
To match the documentation, and prevent unecessary confusion/hacks to fix the issue

## Environment

Browser:

- Chrome (desktop) version 73.0.3683.67

**Comment by simonssspirit** [comment]
This is already fixed in the latest dev version:

https://www.telerik.com/kendo-react-ui/components/installation/development-builds/

https://stackblitz.com/edit/react-drqhg3-ntpxqh?file=app/main.jsx
