### ISSUE TITLE
Grid row height changes upon inline editing

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-react#467]
## I'm submitting a ...
* Bug report 
* Suggestion for improvement

## Current behavior
Upon inline editing and in cell, the height increases.

## Expected behavior
On 'Edit' click to preserve the height of the row.

## Minimal reproduction of the problem with instructions
Refer to: https://www.telerik.com/kendo-react-ui/components/grid/editing/editing-inline/
Works correctly in Kendo Angular Grid: https://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-directives/

## Possible solution
Upon editing, the row an cell elements add additional classes, i.e. `k-grid-edit-row` and `k-grid-edit-cell`. Once we add them, it will fix the glitch.

**Comment by Xizario** [comment]
Try edit 4th row in angular, same issue. row height changes. If the user wants to avoid this he should use the rowHeight property explicitly.

**Comment by silviyaboteva** [comment]
The 4th row has two lines of text, so it is expected to shrink. The issue on our side is when the text is on one line, editing the row must preserve the height. 
As for the material theme, I think if the last column expands its width a bit, it will resolve the issue.

**Comment by Xizario** [comment]
Fixed in `3.11.0`
