### ISSUE TITLE
Tooltip component introducing additional layer with div which is not possible to style

### ISSUE THREAD

**Issue by marcinkowal2015** [telerik/kendo-react#469]
## I'm submitting a...

* Bug report 

## Current behavior
There is no easy possibility to set custom styles for div which is generated by Tooltip component.

## Expected behavior
Tooltip component should provide API for setting styles or do not introduce any DOM elements.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-wsmknb?file=app%2Fmain.jsx

In main.jsx take a look on lines 30 and 31:
```
<div style={{height: "50%"}}>
    <Tooltip openDelay={100} position="right" anchorElement="element" style={{height: "100%"}} className="someTooltipClassName">
        <Grid
                 data={products}
                  style={{height: "100%"}}
           >
```
I'd like to make grid to take 100% height from parent div, however due to fact that Tooltip adds additional div in between there is no easy way to do that without hacks. Style and className props does not work, despite they are in props in docs:
https://www.telerik.com/kendo-react-ui-develop/components/tooltip/api/TooltipProps/#toc-classname

## What is the motivation or use case for changing the behavior?
Being able to programatically set desired styling without introducing css selectors which are basing on internal Tooltip design.

## Environment

Package versions:

```
Ommiting as reproducible on demo site
```

Browser:

- Chrome (desktop) version 80.0.3987.87

**Comment by simonssspirit** [comment]
@marcinkowal2015 Thank you for the report.

In this case, I can suggest using the following approach shown here. This will allow adding the Tooltip handler on a custom DOM element which you can style:

https://www.telerik.com/kendo-react-ui/components/tooltip/tooltip-customization/

Also, the className property is to set the class of the Tooltip element(popup container) not the to div.

**Comment by simonssspirit** [comment]
This seems to be resolved, if there is a future issue with this approach, please open a new issue or re-open this one.
