### ISSUE TITLE
Render global aggregates.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#47]
We have two main options for rendering column aggregates.

1) Having a footer cell where the aggregates will be rendered.
2) Having frozen rows and using one of the frozen rows to display the aggregates.

CC @telerik/kendo-react-team please share your ideas.

**Comment by eeasss** [comment]
I like the frozen rows idea, as aggregates are something useful to be seen when working with the grid. If we keep them exclusively in the footer then scroll may be required in a bigger data set. What is the opinion of our designer, Martin?

**Comment by heyitshannes** [comment]
Option 2 sounds great, especially since it will be using the cell and cellRender props.

**Comment by VirtualDestructor777** [comment]
Hello,

Evaluating kendo-react grid for our requirements:
* sorting
* locked first column
* locked first row with aggregates

Tried a couple of things to work around lack of locked rows:
* sticking totals into header (adding 2nd row of header with aggregate data) did not work as totals become sortable header (not good) 
* trying to position:sticky first row does not seem to work for first column which is already sticky in horizontal direction.

Am I missing something above or we should really wait for locked row feature?

Thanks!

**Comment by Xizario** [comment]
@VirtualDestructor777,  I think this item is older than the locked column feature. Indeed the 'sticky' position will be hard to be applied if already set for the columns.

The above in particular can be achieved via something like:
```css
<style>
td {
    position: sticky;
    background: white;
    top: 50px;
}

tr:first-child td { 
    top: 0px; 
}
</style>
```
An example: https://stackblitz.com/edit/react-jeeanh

We are working on this to be built-in, customizable and flexible, but in order for it to work with virtual scrolling and column virtualization we will add some additional styles to the [themes](https://github.com/telerik/kendo-themes/tree/develop/packages) that will allow us to write the component without too many inline styles.

Ideally the user will able to control the 'locked' state of a row as easily as it is the 'selected' state now. All calculations will be internal and the backgrounds will be themeable.

**Comment by VirtualDestructor777** [comment]
@Xizario thank you for your help, this is very creative work around.

Unfortunately as you scroll up part of row scrolling of the screen gets stuck and mangled together with the row coming up, making it look buggy (our users are picky).

However that got me thinking - I was able to come up with "cleaner" solution by "sticking" first row only and using z-index to overlap it on top of rows being scrolled off.

tr:first-child td { 
  position: sticky;
  top: 0px; 
  z-index: 200 !important;
  background: white;
}

Modified example of yours: https://stackblitz.com/edit/react-jeeanh-uninuw

Hope this helps anybody else who needs a solution.

As you pointed out, this is still a hack so will be looking forward to native functionality in the grid for locked row.   It is appreciated not to be a simple task.

**Comment by simonssspirit** [comment]
This is already available for test in the dev channel, please take a look at it and share feedback: https://www.telerik.com/kendo-react-ui-develop/components/grid/cells/#toc-footer-cells

**Comment by rafiuske** [comment]
@simonssspirit

### footerCell
https://www.telerik.com/kendo-react-ui-develop/components/grid/cells/#toc-footer-cells 

Is there already an estimate of when this feature will be available? I need it! :)

Thanks!

**Comment by simonssspirit** [comment]
@rafiuske  The release of the official version can be expected in the next couple of weeks, around mid-September. Until then the dev version can be used if it is an urgent matter.

This is how to get the dev version: 
https://www.telerik.com/kendo-react-ui/components/installation/development-builds/

**Comment by rafiuske** [comment]
Thanks @simonssspirit

**Comment by easypayua** [comment]
After adding footerCell to Grid resize work not smooth on multi column headers

**Comment by Xizario** [comment]
@easypayua , I confirm this, we will fix this for the official version. cc: @nstoychev

**Comment by Xizario** [comment]
https://www.telerik.com/kendo-react-ui/components/grid/cells/#toc-footer-cells
Available in 3.4.0

**Comment by KhoaRickey** [comment]
Do we have, or planning to have something like this but render in the top instead of bottom? I would use header cells to display my aggregates but that would not look very good.

**Comment by simonssspirit** [comment]
@KhoaRickey  is I understand correctly the desired result to is to have something like a second header row is that correct?

**Comment by KhoaRickey** [comment]
@simonssspirit Yes. Something exactly like the footer cells but render at the top instead of bottom.

**Comment by simonssspirit** [comment]
@KhoaRickey This can be done similarly to the multi-column headers. We pass one more column as children and use a custom headerCell.

This is an example:

https://stackblitz.com/edit/react-75btbp?file=app/main.jsx

**Comment by KhoaRickey** [comment]
@simonssspirit Thank you. I came up with the same idea and already implemented it few days ago. But it doesn't look very good imo. And also, I couldn't make it editable although i put a input box in it. Therefore i think a dedicated aggregate row up top would be useful, at least for me.

**Comment by Thalandor** [comment]
Hi, I was looking an option to put a ROW footer on the grid, is it not possible currently? 
The option implemented in this issue is having a cell footer, not a row footer (for having the total for example).
The grid I'm working on is virtual, we have the total count but obviously no 'pagination', so the pageable option doesn't really work :/

**Comment by simonssspirit** [comment]
@Thalandor 
If the desired result is to put a custom row under the Grid, we can use the GridToolbar with CSS to place it under the Grid:

https://stackblitz.com/edit/react-ccurp4?file=app%2Fmain.jsx

**Comment by Thalandor** [comment]
really nice, at the end I used simply a custom div and manage the height with css and so, but your way  is much better.
Many thanks.
