### ISSUE TITLE
Upload component. Setting custom dropZone?

### ISSUE THREAD

**Issue by namrastanov** [telerik/kendo-react#472]
## Current behavior
When I add  [Upload component](https://www.telerik.com/kendo-react-ui/components/upload/) I can not set custom dropZone.

## Expected behavior
Ability to set custom dropzone element.

## Environment

Package versions:
"@progress/kendo-react-upload": "^3.10.1"

System:
- node --version v12.13.1
- npm --version 6.12.1
- Platform:  Windows

**Comment by Xizario** [comment]
At this point custom dropZone can not be set.

**Comment by silviyaboteva** [comment]
As of [`v4.5.0`](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#0efc49cf-fb41-5e8f-9773-5fc4a4663e58), we have an ExternalDropZone component. You might check it here: https://www.telerik.com/kendo-react-ui-develop/components/upload/external-drop-zone/

**Comment by pranaydevops28** [comment]
External dropzone works good in some cases, however, how can we set dropzone to a div which contains elements, like a Card layout which contains combobox, dateinput or some other components.

**Comment by silviyaboteva** [comment]
Hello @pranaydevops28,

The ExternalDropZone can be placed in a container, either if it's a Card or something else. Here is a simple demo showcasing the scenario: https://stackblitz.com/edit/react-fq7jqh?file=app/main.jsx.

May I ask you to elaborate more on the issue that you have experienced? A runnable demo will help us to investigate further.
