### ISSUE TITLE
Pressing enter in the NumerixTextBox does not trigger Form submit.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#477]
Pressing enter in the NumerixTextBox does not trigger Form submit:

https://stackblitz.com/edit/react-acylcf?file=app/main.jsx

**Comment by Xizario** [comment]
Posting workarownd here, just in case, since it is not only with numericTextBox but any component inside the form that prevents enter will result in the same behaviour. 
```jsx
        <form
          onKeyDown={e => {
            const form = e.currentTarget; 
            if (e.keyCode === 13) {
              setTimeout(() => {
                form.submit()
              });
            }
          }}
```
