### ISSUE TITLE
Scheduler - render one day twice

### ISSUE THREAD

**Issue by dyabol** [telerik/kendo-react#478]
When i use globalization with Scheduler (Month view), **26. October 2020**, render twice.
And 1. October 2021, 31. October 2022, ...

"@progress/kendo-react-scheduler": "3.10.1"

The problem can be caused also in the documentation:

[https://www.telerik.com/kendo-react-ui/components/scheduler/globalization/](url)

**Comment by kspeyanski** [comment]
Hello @dyabol ,

We have published the fix with the latest dev version of the @progress/kendo-react-scheduler package. You can observe the fix in action in the following stackblitz example:
https://stackblitz.com/edit/react-iqg9se?file=package.json

For more information about obtaining development builds, please refer to this article:
https://www.telerik.com/kendo-react-ui/components/installation/development-builds/

Please be advised that all scheduler dependencies should also be updated to the latest dev version.
