### ISSUE TITLE
Kendo-grid-react-wrapper Export to Excel

### ISSUE THREAD

**Issue by amajmundar1** [telerik/kendo-react#48]
## I'm submitting a...

* Bug report 
* Documentation issue or request

## Current behavior

When you add the "export to Excel" feature to the kendo grid toolbar, it does not work. The button appears as "Export to Excel" with the parameter "excel" however the button does not do anything.
It works in JQueary.

## Expected behavior

It is supposed to export the data to an excel file. 
## Minimal reproduction of the problem with instructions

Just add a toolbar to a grid with the parameter "excel" passed in. I am using react wrapper

https://plnkr.co/edit/hYuYDO9KCFHPUgWCdZJY?p=preview

## What is the motivation or use case for changing the behavior?

 It is a feature that is advertised and yet is not supported by one platform.
## Environment

Package versions:

+-- @progress/kendo-data-query@1.4.0
+-- @progress/kendo-drawing@1.5.6
+-- @progress/kendo-grid-react-wrapper@2018.2.620
+-- @progress/kendo-react-dateinputs@1.1.0
+-- @progress/kendo-react-dropdowns@1.1.0
+-- @progress/kendo-react-excel-export@1.1.0
+-- @progress/kendo-react-grid@1.1.0
+-- @progress/kendo-react-inputs@1.1.0
+-- @progress/kendo-react-intl@1.1.0
+-- @progress/kendo-react-pdf@1.1.0
+-- @progress/kendo-ui@2018.2.704
+-- ajv@6.0.0
+-- ansi-regex@2.1.1
+-- balanced-match@1.0.0
+-- bootstrap@4.1.2
+-- brace-expansion@1.1.11
+-- cldr-data@32.0.1
+-- code-point-at@1.1.0
+-- concat-map@0.0.1
+-- console-control-strings@1.1.0
+-- devextreme@18.1.4
+-- devextreme-react@18.1.4-alpha.8
+-- inherits@2.0.3
+-- is-fullwidth-code-point@1.0.0
+-- jquery@3.3.1
+-- minimatch@3.0.4
+-- minimist@0.0.8
+-- minipass@2.2.4
+-- mkdirp@0.5.1
+-- number-is-nan@1.0.1
+-- once@1.4.0
+-- popper.js@1.14.3
+-- react@16.4.1
+-- react-dom@16.4.1
+-- react-scripts@1.1.4
+-- safe-buffer@5.1.1
+-- string-width@1.0.2
+-- strip-ansi@3.0.1
+-- wrappy@1.0.2
`-- yallist@3.0.2

```

```

Browser:

- Chrome (desktop) version 67.0.3396.99 (Official Build) (64-bit)

System:
- TypeScript version: 2.9.2
- Node version:10.0.0 
- NPM version: 6.1.0
- Platform:  Windows

**Comment by Xizario** [comment]
Add this script in your app:
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.4.0/jszip.min.js"></script>
```
It is required for the work of the [export for the jQuery Kendo Grid](https://docs.telerik.com/kendo-ui/controls/data-management/grid/excel-export#enable-export-to-excel), so the same is valid for the wrapper.
