### ISSUE TITLE
MultiSelect does not implement valueRender prop

### ISSUE THREAD

**Issue by stefanhamburger** [telerik/kendo-react#480]
The `MultiSelect` component has a [`valueRender` prop](https://www.telerik.com/kendo-react-ui/components/dropdowns/api/MultiSelectProps/#toc-valuerender), however this prop is not implemented.

Example: https://stackblitz.com/edit/react-3fvuna?file=app/main.jsx

Note how the console contains messages from `DropDownList`'s `itemRender` and `valueRender`, as well as `MultiSelect`'s `itemRender`, but nothing for `MultiSelect`'s `valueRender`. (The StackBlitz preview does not work for me ATM but you can see this behaviour when downloading the project and testing locally.)

Please either implement the `valueRender` prop, or remove it from the `MultiSelectProps` interface.

**Comment by simonssspirit** [comment]
Thank you for this.

The property for the MultiSelect is tagRender:

https://www.telerik.com/kendo-react-ui/components/dropdowns/api/MultiSelectProps/#toc-tagrender

We will investigate the valueRender and remove it if needed.

**Comment by nstoychev** [comment]
The valueRender prop is deprecated and will be removed.
