### ISSUE TITLE
Input Elements Appear Red (Invalid) Before the User Has Interacted With It

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#487]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
On initially loading the page, all required elements are red.

## Expected behavior
The inputs should only turn red once the user has 'touched' it, or tries to submit the form, or we call reportValidity().

## Minimal reproduction of the problem with instructions
https://www.telerik.com/kendo-react-ui/components/inputs/input/forms/

![image](https://user-images.githubusercontent.com/12272970/74882389-ec34db00-53be-11ea-9652-69506127ccf9.png)

## What is the motivation or use case for changing the behavior?
We have a lot of forms in our application, and the bright red colours are jarring in our theme. It also 'punishes' users early which leads to a worse user experience.

## Environment
- Chrome (desktop) Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by vladimirivanoviliev** [comment]
This behavior can be achieved by tracking each input `touched` state manually as shown in the following help article:
- [Native Form: Delaying Validity Styles](https://www.telerik.com/kendo-react-ui/components/forms/getting-started/#toc-delaying-validity-styles)

However I would suggest to check our new `Form` component which tracks these states automatically and allow more control over when the error messages are shown (e.g.: touched, modified or visited). For more information you can check the component documentation:
- [Form component](https://www.telerik.com/kendo-react-ui/components/form/)
- [Form API](https://www.telerik.com/kendo-react-ui/components/form/api/)

For your convenience I updated the previous example to use the `Form` component and show error messages after fields are touched or user try to submit the form:
- [Form component example](https://stackblitz.com/edit/react-a7mxwp?file=app/main.jsx)
