### ISSUE TITLE
Dropdowns Validation Popup Covers The Dropdown Options

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#488]
## I'm submitting a...
* Bug report

## Current behavior
Dropdown validation popup keeps re-appearing and covering the options if you try to submit when it's invalid.

## Expected behavior
Popup disappears when you open the Dropdown to select a valid option.

## Minimal reproduction of the problem with instructions
https://www.telerik.com/kendo-react-ui/components/dropdowns/dropdownlist/forms/

![image](https://user-images.githubusercontent.com/12272970/74889694-bc430300-53d1-11ea-9353-f79076cc69ed.png)

1. Click Submit.
2. Try to select an option in the Dropdown. The first option will be obscured.

## What is the motivation or use case for changing the behavior?
We have a lot of forms with Dropdowns in them. If the user clicks Submit without selecting an option, they're unable to select a valid option because they're obscured.

## Environment
Browser:
Chrome (desktop) Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by vladimirivanoviliev** [comment]
Currently we have no control over the browser validation message and it's position. We will consider improving this bvehavior, however I would suggest to check the new `Form` component as it allows more control over the validation messages. Here is updated example with the new component:
- [DropDownList Form Component validation](https://stackblitz.com/edit/react-x9myan?file=app/main.jsx)
