### ISSUE TITLE
Grouping in Grid with custom cell component in GridColumn create extra cells in group header row.

### ISSUE THREAD

**Issue by huestack** [telerik/kendo-react#489]
## I'm submitting a...
* Bug report 

## Current behavior
When GridColumn has custom cell component assigned, grouping of grid creates extra number of `<td>` along `<td>` with `colspan` in group header row, which is causing nonalignment of master cells with headers. For example, if a grid has 4 columns with 2 GridColumn having custom cell component, Grid adds two extra `<td>`s in group header `<tr class="k-grouping-row">`. This is generated HTML:

```
<tr class="k-grouping-row">
 <td colspan="5" style="left: 0px; right: 0px;" />
 <td colspan="1" />
 <td colspan="1" />
</tr>
<tr class="k-master-row">
 <td class="k-group-cell" style="left: 0px; right: 0px; /">
 <td colspan="1" class="" />
 <td colspan="1" class="" />
 <td colspan="1" class="" /> <!--Custom Cell-->
 <td colspan="1" class="" /> <!--Custom Cell-->
</tr>
```

## Expected behavior
No extra cells should be added in group header row when custom cells are introduced. The master cells should align with headers.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-r3jyrt?file=app%2Fmain.jsx

## Environment

Package versions:
```
"react": "16.12.0",
"react-dom": "16.12.0",
"@progress/kendo-react-grid": "3.11.0",
```

Browser:
- Chrome (desktop) version 80.0.3987.116 (Official Build) (64-bit)
- Firefox version 73.0.1 (64-bit)
- Edge version 80.0.361.56 (Official build) (64-bit)

System:
- TypeScript version: 2.9.2 
- Node version: 10.9.0 
- Platform: Windows 10 (64-bit)

**Comment by simonssspirit** [comment]
@huestack Thank you for the example.

In this case, the issue occurs because the rowType of groupHeader null has to be returned from the cell render.

I updated the example: https://stackblitz.com/edit/react-r3jyrt-dm5udi?file=app/main.jsx

**Comment by huestack** [comment]
@simonssspirit Thank you.

**Comment by simonssspirit** [comment]
This is added as KB - https://github.com/telerik/kendo-react-kb/commit/71bc199816110a082d0057e45d3c68b63767240e
