### ISSUE TITLE
Dropdowns - set focused programmatically

### ISSUE THREAD

**Issue by Nodios** [telerik/kendo-react#490]
In cascading dropdowns scenario, how could one set focus on next dropdown in case of selected item?

I tried using ref and calling handleFocus method, the focus is applied, but you are not able to navigate using keyboard or anything.

**Comment by nstoychev** [comment]
You should call the focus method of the focusable HTML element. In the case, this is the SPAN element which has `tabIndex` set.

```jsx
<DropDownList
   className="orders"
   ...
/>

const ordersDd = document.querySelector('.orders span[tabindex]');
if (ordersDd) {
   ordersDd.focus();
}
```

**Comment by vladimirivanoviliev** [comment]
Another option is to use `setTimeout` to focus the element from the component ref in order to wait the second DropDownList to be enabled:

- [Cascasding DropDownList](https://stackblitz.com/edit/react-cascading-dropdownlist?file=app/main.jsx)

**Comment by Nodios** [comment]
@vladimirivanoviliev @nstoychev thanks for the info! Then handling open/close state has to be done programmatically as well?

**Comment by nstoychev** [comment]
If it is required to control open/close state, you can use the [opened](https://www.telerik.com/kendo-react-ui/components/dropdowns/api/DropDownListProps/#toc-opened) prop, and [onOpen](https://www.telerik.com/kendo-react-ui/components/dropdowns/api/DropDownListProps/#toc-onopen) and [onClose](https://www.telerik.com/kendo-react-ui/components/dropdowns/api/DropDownListProps/#toc-onclose) events.

**Comment by simonssspirit** [comment]
Closing the questions seems resolved. Please re-open if needed.
