### ISSUE TITLE
MultiSelect not clear non-existing value if filterable is true

### ISSUE THREAD

**Issue by deyw** [telerik/kendo-react#491]
Step to reproduce:
Go to documentation page: [https://www.telerik.com/kendo-react-ui/components/dropdowns/multiselect/filtering/](https://www.telerik.com/kendo-react-ui/components/dropdowns/multiselect/filtering/
)

1. Enter non-existing value in text field and leave (onBlur, ...etc);
 -- non-existing value still in input, but actual value is empty array;

2. Set `filterable` prop  `false`. 
 -- non-exisiting value removed from input

Expected result: Non-existing value should be cleared when `filterable` property is true

**Comment by nstoychev** [comment]
@deyw - Please see the following example about how to control the input value - https://stackblitz.com/edit/react-nuwkel?file=app/main.jsx.

I assume that this is the behavior that you expect.

**Comment by deyw** [comment]
@nstoychev Thank you!
