### ISSUE TITLE
Unable to apply custom CSS class to TabStripTab child animation div

### ISSUE THREAD

**Issue by ryancole** [telerik/kendo-react#492]
When using the `TabStripTab` component, it renders a wrapping `div` around my content. That wrapping `div` prevents me from specifying a full-width contents. I must manually add my own CSS. The class on the wrapping div is `k-animation-container`. If you look in the `index.html` file, of the below linked code, you will see that I've highlighted the wrapping `div` in red.

I've created an example here that shows what I'm talking about: https://stackblitz.com/edit/react-vmctrm

It'd be nice if I could somehow add custom class names to that child wrapper, too, so that I can specify a full width.

**Comment by simonssspirit** [comment]
@ryancole There is a property called: contentClassName. This sets the class of parent element of the "k-animation-container". This allows setting CSS rules to all animation containers inside a parent with that className:

https://www.telerik.com/kendo-react-ui/components/layout/api/TabStripTabProps/#toc-contentclassname
