### ISSUE TITLE
The Dialog has to be focused automatically when opened.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#494]
The Dialog has to be focused automatically when opened.

If it is not, this can cause issues with other focusable elements on the page.

A current workaround will be to programmatically focus it when opended:

https://stackblitz.com/edit/react-cjguma-zdfxx4?file=app/main.jsx

**Comment by ryan-nauman** [comment]
Note that the workaround is not valid if a user presses shift+tab.

**Comment by simonssspirit** [comment]
This can be controlled with the new autoFocus prop:

https://www.telerik.com/kendo-react-ui-develop/components/dialogs/api/DialogProps/#toc-autofocus

**Comment by ryan-nauman** [comment]
@simonssspirit this is still broken. https://stackblitz.com/edit/react-uzgecd?file=app%2Fmain.jsx - press shift+tab and you will see the focus go to the input.

**Comment by simonssspirit** [comment]
@ryan-nauman indeed I tested and the logic we added only prevents the focus to leave the component in some of the cases. I re-opened the issue.

**Comment by ryan-nauman** [comment]
bump (almost a 2 year birthday)

**Comment by simonssspirit** [comment]
The fix is on a pull request.

Apologies for the delay.

**Comment by simonssspirit** [comment]
The fix with Shift+tap is available in version 5.1.0
