### ISSUE TITLE
Grid sort functionality not working with hooks

### ISSUE THREAD

**Issue by joshua-arnold-informa** [telerik/kendo-react#497]
## I'm submitting a...
* Bug report 

## Current behavior
Grid sort functionality not working with hooks

## Expected behavior
Sort a column

## Minimal reproduction of the problem with instructions
**https://stackblitz.com/edit/react-rs1hhq**

## What is the motivation or use case for changing the behavior?
Using hooks

Browser:

- Chrome (desktop) version 80.0.3987.122

**Comment by Xizario** [comment]
In the example project, the data is not processed it uses spread operator to pass the products in the same order as they are in attached JSON. I have modified line 19 to:
```jsx
data={process(products, { sort })}
```
and now it is working okay.
https://stackblitz.com/edit/react-rs1hhq-lqffjt?file=app/main.jsx
