### ISSUE TITLE
Grid grouping does not show next group if outside the pagination bounds

### ISSUE THREAD

**Issue by ryancole** [telerik/kendo-react#499]
## I'm submitting a...

* Bug report

## Current behavior

When grouping, with the Grid component, while pagination is enabled, the resulting groups do not properly display if the collapsed group contains more items than the `take` of the pagination. If a group contains more items than would be shown via `take` of pagination, and is then collapsed, the next group does not become visible to take its place.

## Expected behavior

I'd expect that the visible groups either could as 1 item in the `take` or do not count towards `take` at all, of pagination, and so when groups are collapsed the pagination is adjusted to show the items of the next available group.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/react-5vwty7

This is just a fork of one of your grouping examples. I've changed the default group to be one that contains more than the `take` value. If you change pages, you see there are multiple pages of items for the group. If you collapse the group, however, the grid becomes empty and does not show the next available group.

## What is the motivation or use case for changing the behavior?

When users collapse groups, across pages, they expect the next group to become visible. Paging becomes awkward with collapsed groups in the current form.

**Comment by simonssspirit** [comment]
@ryancole  This is because the expanded state has to be kept in the state as well.

We have an example that showcases how this is done, using the TreeList mapTree method as the grouped data is a tree as well.

We will consider removing the method from the TreeList and adding it to a common package:

https://stackblitz.com/edit/react-2ots26-rwa3br?file=app/main.jsx
