### ISSUE TITLE
Add demo with Draggable.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#50]
Add demo with Draggable.

The demo should demonstrate how to integrate the kendo-draggable package in React application.

**Comment by simonssspirit** [comment]
We decided to make a React-draggable package instead of making only a demo.

**Comment by Xizario** [comment]
As the draggable is part of the `@progress/kendo-react-common` now, we can list this in our docs and deprecate the old `@telerik/kendo-react-draggable` package

**Comment by simonssspirit** [comment]
The demo is added: https://www.telerik.com/kendo-react-ui-develop/components/utils/draggable
