### ISSUE TITLE
TreeList filter cell is not locked event if the column is locked.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#501]
TreeList filter cell is not locked even if the column is locked.

This can be seen on the following demo:

https://stackblitz.com/edit/react-cb5m6a?file=app/main.jsx

**Comment by nstoychev** [comment]
Fixed in our dev channel - https://stackblitz.com/edit/react-cb5m6a-yfimmz?file=app/main.jsx.
