### ISSUE TITLE
Window height is wrong after restore from minimalize state

### ISSUE THREAD

**Issue by lkovacs** [telerik/kendo-react#504]
## I'm submitting a...

* Bug report 

## Current behavior

Open a window with initial coordinates. When you minimalize and restore the window everything is fine.
Change the height of the window. Now minimalize and restore the window again.  The height is the initialized not the last one.

## Expected behavior

The windows height will be the last one.

## Minimal reproduction of the problem with instructions

From source code (see my comments):

    // Handle actions
    private handleMinimize = (event: React.SyntheticEvent<any>) => {
        event.preventDefault();
        this.setState({					<- doesn’t save any postion
            stage: windowStage.MINIMIZED,
            height: 0
        });
        dispatchEvent(this.props.onStageChange, event, this, { state: windowStage.MINIMIZED });
    }

    private handleFullscreen = (event: React.SyntheticEvent<any>) => {
        event.preventDefault();
        this.windowCoordinatesState.leftBeforeAction = this.left; 
        this.windowCoordinatesState.topBeforeAction = this.top;
        this.windowCoordinatesState.widthBeforeAction = this.width;
        this.windowCoordinatesState.heightBeforeAction = this.height;   <- save on fullscreen
        this.setState({
            left: 0,
            top: 0,
            width: window.innerWidth,
            height: window.innerHeight,
            stage: windowStage.FULLSCREEN
        });
        dispatchEvent(this.props.onStageChange, event, this, { state: windowStage.FULLSCREEN });
    }

    private handleRestore = (event: React.SyntheticEvent<any>) => {
        event.preventDefault();
        if (this.windowStage === windowStage.FULLSCREEN) {
            this.setState({
                stage: windowStage.DEFAULT,
                left: this.windowCoordinatesState.leftBeforeAction,
                top: this.windowCoordinatesState.topBeforeAction,
                width: this.windowCoordinatesState.widthBeforeAction,
                height: this.windowCoordinatesState.heightBeforeAction
            });
        } else if (this.windowStage === windowStage.MINIMIZED) {
            this.setState({
                stage: windowStage.DEFAULT,
                height: this.windowCoordinatesState.heightBeforeAction  <- it didn’t save before, it restore the original or the saved when it was maximized before
            });
        }

        dispatchEvent(this.props.onStageChange, event, this, { state: windowStage.DEFAULT });
    }

## Environment

Package versions:

@progress/kendo-react-dialogs@3.10.1

Browser:

- Chrome (desktop) version 80.0.3987.132

**Comment by simonssspirit** [comment]
@lkovacs  thank you for the detailed report. We will provide a fix for this.

**Comment by simonssspirit** [comment]
This is already in the latest dev version: 3.13.0-dev.202004090817

https://www.telerik.com/kendo-react-ui/components/installation/development-builds/
