### ISSUE TITLE
Responsive DateRangePicker

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-react#505]
The DateRangePicker component needs to stack one calendar on top of another for mobile.

The issue can be seen on the following demo:
https://www.telerik.com/kendo-react-ui/components/dateinputs/daterangepicker/

**Comment by iadnonov** [comment]
Fixed in [v5.14.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#v5.14.0)
