### ISSUE TITLE
KendoReact Grid Cell Diplay text

### ISSUE THREAD

**Issue by Nesyne** [telerik/kendo-react#507]
I am new to KendoReact Grid. I have a custom cell with a DropDownList. The dropdown list data property is bound to to a collection like this:
sports = [
        { text: 'Basketball', id: 1 },
        { text: 'Football', id: 2 },
        { text: 'Tennis', id: 3 },
        { text: 'Volleyball', id: 4 }
    ];
After editing the cell and using the dropdown to select an item, i would like the cell to display the 'text' and not the value which in this case is 'id'

**Comment by simonssspirit** [comment]
@Nesyne  Inside the custom cell when it is not in edit mode, render the text property of the value.

```
<td>
 {props.dataItem.DropDownListValue.text}
</td>
```

**Comment by Nesyne** [comment]
This is what i have:

import React from "react";
import { DropDownList } from "@progress/kendo-react-dropdowns";
import TagEnums from "../components/TagEnums";
import { GridCellProps } from "@progress/kendo-react-grid";

const TagDataTypeCell: React.FC<{}> = selectedItem => {
  const props = selectedItem as GridCellProps;

  const handleChange = (e: any) => {
    debugger;
    if (props.onChange) {
      props.onChange({
        dataItem: props.dataItem,
        field: props.field,
        syntheticEvent: e.syntheticEvent,
        value: e.target.value.value
      });
    }
  };

  const dataValue =
    props.field == null
      ? ""
      : props.dataItem[props?.field] === null
      ? ""
      : props.dataItem[props.field];

  return (
    <td>
      {props.dataItem.inEdit ? (
        <DropDownList
          textField="label"
          dataItemKey="value"
          onChange={handleChange}
          value={TagEnums.TagDataType.find(c => c.value === dataValue)}
          data={TagEnums.TagDataType}
        />
      ) : (
        props.dataItem.DropDownListValue?.text
        // dataValue
      )}
    </td>
  );
};
export default TagDataTypeCell;


I tried what you said but the DropDownListValue is coming as unidentified. Am I doing something wrong?

**Comment by simonssspirit** [comment]
@Nesyne Apologies for the confusion.

The DropDownListValue was referring to the field that holds the value in the application, and I just used a generic name, as in every Grid it can be a different field.

This should work

```
props.dataItem[props.field].text
```

**Comment by Nesyne** [comment]
So that i understand correctly, the props.dataItem[props.field].text goes on the custom cell or the grid?

**Comment by Nesyne** [comment]
I am using the custom cell in the grid like this:
    <Column
              field="dataType"
              title="Data Type"
              cell={TagDataTypeCell}
              width="200px"
              editor="text"
            />

**Comment by Nesyne** [comment]
for some reason the code i pasted didn't show up previously. My column which is using the custom cell looks like this. <Column
              field="dataType"
              title="Data Type"
              cell={TagDataTypeCell}
              width="200px"
              editor="text"
            />

**Comment by Nesyne** [comment]
my column looks like this:
![column](https://user-images.githubusercontent.com/16142881/76547668-ce511800-644a-11ea-8a5c-0a9a3c1d2997.png)

**Comment by simonssspirit** [comment]
@Nesyne I see that the issue was closed, is the correct text displaying in the cell?

**Comment by Nesyne** [comment]
I ended up replacing dataValue with dataText here:
![image](https://user-images.githubusercontent.com/16142881/76644979-48e66a00-6515-11ea-966b-6035066d6057.png)
