### ISSUE TITLE
React ComboBox with allowCustom set to true doesn't show custom value on load

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#51]
## I'm submitting a...
* Bug report

## Current behavior
Combo box with value set to a custom value, and allowCustom set to true, doesn't display the custom value unless it is an option in the data source array.

## Expected behavior
Display the text even though it's not in the data source.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/wD0zpCTTVSyt41ZF4ndl?p=preview

The 1st combo box should say 'test' as evidenced in app/main.jsx, but only the 2nd combo box with a matching data field shows the value.

## What is the motivation or use case for changing the behavior?
We have a 'title' combo box with options like Mr, Miss, etc, but allow users to enter their own custom title. When the file is saved, and then opened for editing, the title field is blank when they entered a custom title.

## Environment
Browser:
- Chrome (desktop) Version 67.0.3396.99 (Official Build) (64-bit)

System:
- Node version: v8.9.3
- Platform:  Windows

**Comment by nstoychev** [comment]
We have publish version 2.0.0 where the issue is resolved. Release notes can be found here: https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/.
