### ISSUE TITLE
Drawer: DrawerItem is not exported from '@progress/kendo-react-layout'

### ISSUE THREAD

**Issue by n1k1t0ss** [telerik/kendo-react#510]
## I'm submitting a...
* Bug report 

## Current behavior
I got error 

> ./src/app/DrawerContainer.jsx
> Attempted import error: 'DrawerItem' is not exported from '@progress/kendo-react-layout'.

every time I imported DrawerItem in this line:
`import { Drawer, DrawerContent, DrawerItem } from '@progress/kendo-react-layout';`
Tested on several repositories - use your sample with it and checked on other PC (both under Win 10, with VS Code)

## Expected behavior
DrawerItem imported sucsesfully

## Minimal reproduction of the problem with instructions

1. Dowload a sample  https://stackblitz.com/edit/react-vp9ps7?file=app/DrawerContainer.jsx (OR https://stackblitz.com/run/?file=app%2Fmain.jsx ) with Custom DrawerItem. Unzip solution. No changes required, I got error from a box.
2. Run `npm i`
3. Run `npm start`
4. Instead of grid error will be shown.

## Environment

Package versions:

didn't changed package versions in sample

Browser:

- Chrome (desktop) 80.0.3987.132
- Opera
- Edge

System:
- TypeScript version: not installed
- Node version: v12.16.1, npm: 6.13.4
- Platform:  Windows 10 - 1903 (18362.719)

**Comment by simonssspirit** [comment]
@n1k1t0ss The DrawerItem was introduced in the latest dev version 3.12.0:

https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#toc-3120-dev202003091534

Please check if the application is using the dev version:

https://www.telerik.com/kendo-react-ui/components/installation/development-builds/

**Comment by n1k1t0ss** [comment]
@simonssspirit thank you! That fixed a problem.
