### ISSUE TITLE
How to custom the TreeList expandable cell?

### ISSUE THREAD

**Issue by Nassefferjeni** [telerik/kendo-react#512]
So I just began using the kendo TreeList and I am trying things here and there and one of the things that I want to try is to customize the rendering of the columns.

I made it work, but now I have only one problem, the cell that contains the 'expandable' ability is not there when I try to render a custom Cell (the arrow that extends)

is there a way to customize only the cell but at the same time keep the arrows?

` cell: ({ dataItem }) => { 
return ( <td>
                                    <div className={ classes.displayFlex }>
                                        { expandable && dataItem[config.subItemsField] && <IconButton className={ classes.zeroPadding } onClick={ () => this._onExpandChange(dataItem) }><SaveAltIcon/></IconButton> }
                                        <div>{ dataItem[field] }</div>
                                    </div>
                                </td>
                        );
                    }
                } `

I can customize the field but at the same time, I have a problem of aligning them with the other fields since when it's expandable I have to add a margin/padding. Is there any easier or straightforward way to do it?

**Comment by nstoychev** [comment]
If you only need to add styles, you can add className to the expandable column and style the cells - https://www.telerik.com/kendo-react-ui/components/treelist/api/TreeListColumnProps/#toc-classname.

If you need additional customizations, you can use the TreeList cellRender prop - https://www.telerik.com/kendo-react-ui/components/treelist/api/TreeListProps/#toc-cellrender.
cellRender provides the default rendering of the cell, which could be used.

Here is an example showing both cases - https://stackblitz.com/edit/react-gzc5b3?file=app/main.jsx

**Comment by Nassefferjeni** [comment]
Thank you so much @nstoychev.

One last question is there a way to implement a footer? like a row containing the sum with a line separator?

cc @simonssspirit

**Comment by nstoychev** [comment]
Did you try `{cell.props.children}` for the values?

**Comment by Nassefferjeni** [comment]
Yes, it worked. I had to map the `cell.props.children` and use its elements.
Thank you @nstoychev.

Do you have any idea if I can add a footer to the TreeList component?

**Comment by nstoychev** [comment]
The discussion continues here - https://github.com/telerik/kendo-react/issues/519

**Comment by simonssspirit** [comment]
Closing the initial question seems resolved. Please re-open if needed.
