### ISSUE TITLE
Nested Tooltip not working

### ISSUE THREAD

**Issue by namrastanov** [telerik/kendo-react#513]
I need to have a nested Tooltip.

## Current behavior
Nested tooltip is not working

## Expected behavior
Nested tooltip works as usual

## Minimal reproduction of the problem with instructions
Here is the stackblitz implementation of the problem
https://stackblitz.com/edit/react-qitdjv

## What is the motivation or use case for changing the behavior?
I have a popup menu implemented by your really awesome tooltip component but I need to have popup subitems as well.
At the link above I have a component with a tooltip. And used that component as usual and as a another Tooltip content. So the second one is not working.

"dependencies": {
    "@progress/kendo-react-tooltip": "3.11.0",
    "react": "16.13.0",
    "react-dom": "16.13.0"
  }

**Comment by simonssspirit** [comment]
@namrastanov  we do have a fully functional Menu component with Subitems:

https://www.telerik.com/kendo-react-ui/components/layout/menu/

Is there is an issue with it that brings the need to use the Tooltip?

In general, the Tooltip is to designed to provide more customizable functionality than the built-in browser tooltip and it is not designed to be used as a menu.

**Comment by namrastanov** [comment]
@simonssspirit I agree with you. But I have a design like a tooltip. Could I easily customize that menu to look like a tooltip?

**Comment by simonssspirit** [comment]
@namrastanov This depends on the design, but the Menu has a lot of customization options:

https://www.telerik.com/kendo-react-ui/components/layout/menu/items/rendering/

Also, our Themes are highly customizable:
https://www.telerik.com/kendo-react-ui/components/styling/theme-bootstrap/customization/

These are all variables available for customization:

https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/_variables.scss

**Comment by namrastanov** [comment]
@simonssspirit thank you.
