### ISSUE TITLE
DropDowns Popup list positioned incorrectly if the user scrolls very fast as soon after clicking the component.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#515]
DropDowns Popup list positioned incorrectly if the user scrolls very fast as soon after clicking the component.

https://stackblitz.com/edit/react-quswku-prfgta?file=app/main.jsx

![1dcca0b4-7733-4418-b3e6-ac9c03340526_moqa2emlsp](https://user-images.githubusercontent.com/11087921/76872806-91838780-6875-11ea-9165-6a77236a6c9b.gif)

**Comment by jorgmen** [comment]
I have this issue in IE and Edge, happens also when the user scrolls a drop-down-list or a combo-box and reaches the last item in the list, then the scroll moves the entire page (page scrolling) and the pop-up container gets misplaced similar to this https://docs.telerik.com/kendo-ui/knowledge-base/dropdown-position-incorrect-with-scroll

**Comment by simonssspirit** [comment]
@jorgmen  the provided example is from the Kendo UI for jQuery documentation. If the used product is for jQuery please refer to their GitHub repo:

https://github.com/telerik/kendo-ui-core

**Comment by nstoychev** [comment]
This behavior is expected. The position of the Popup has been calculated before the open animation starts, and if the user scrolls during the animation, the Popup will show on a wrong position.

This can be prevented by disabling the animation or closing the popup on scroll event.
