### ISSUE TITLE
Provide an option to remove the negative 0 (-0) from the NumericTextBox.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#516]
Provide an option to remove the negative 0 (-0) from the NumericTextBox.

Even if this is a valid number from a JavaScript perspective, it could be strange from the end-user perspective:

https://medium.com/coding-at-dawn/is-negative-zero-0-a-number-in-javascript-c62739f80114

**Comment by kdikov82** [comment]
Removing -0 will cause problems with the entering of negative values from empty input, so this should be handled manually if needed (within the onChange event)
