### ISSUE TITLE
Problem of DateRangePicker inside a drawer MaterialUI

### ISSUE THREAD

**Issue by selim-ammari** [telerik/kendo-react#517]
When we grab this component inside a Drawer of materialUI there is some troubles and basic functionalities of the components doesn't work anymore like view next or previous month

## I'm submitting a bug report

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by simonssspirit** [comment]
@selim-ammari Is it possible to share an example, so we can see the actual issue?

With Material UI with had an issue with the Modal as they trap the focus, so I`m not sure if this is the case for their Drawer as well:

https://material-ui.com/components/modal/#focus-trap

Also, please check our Drawer, as we also have a Drawer component:

https://www.telerik.com/kendo-react-ui/components/layout/drawer/

**Comment by kdikov82** [comment]
No additional information was provided
