### ISSUE TITLE
(NextJS App) Scheduler throws focus is not defined error.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#518]
(NextJS App) Scheduler throws focus is not defined error.

This occurs only in a NextJS application:

![image](https://user-images.githubusercontent.com/11087921/76959797-02cd4400-6923-11ea-87a5-3f6a0150c57b.png)

**Comment by kspeyanski** [comment]
After testing locally, the issue is no longer present with the latest version of `@progress/kendo-react-scheduler`
