### ISSUE TITLE
Kendo TreeList footer

### ISSUE THREAD

**Issue by Nassefferjeni** [telerik/kendo-react#519]
So I'm still experiencing the kendo Tree List component, and I am looking at the documentation and it doesn't seem to be having a footer.
Is it going to be implemented or is there an alternative now?

**Comment by nstoychev** [comment]
Here is how you can render an alternative of a footer - https://stackblitz.com/edit/react-hadhsy?file=app%2Fmain.jsx

I added additional data to the employees collection and render a custom row using the rowRender prop. Currently, the TreeList does not render an HTML footer element,

Adding a footer to the TreeList is also in our roadmap.

**Comment by Nassefferjeni** [comment]
Thank you very much @nstoychev

**Comment by simonssspirit** [comment]
resolved
