### ISSUE TITLE
LineChart: onSeriesClick does not work for LEFT click (only right click)

### ISSUE THREAD

**Issue by stevenmyhre** [telerik/kendo-react#52]
## I'm submitting a...

* Bug report 

## Current behavior

Setting an onSeriesClick callback function, the function will only be called if right clicking on the chart.

## Expected behavior

onSeriesClick should be called for all click events, leaving up to the user implementing to decide if they would like to handle the left/right click.

## Minimal reproduction of the problem with instructions

1. See PLUNKER https://plnkr.co/edit/mmSFs8COSpFRTXmodPPd

## What is the motivation or use case for changing the behavior?

When a user clicks on a point on the line chart, data in another chart/table is changed/loaded.

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version 67.0.3396.99

System:
- TypeScript version: N/A
- Node version: 8.9.3
- Platform:  Windows

**Comment by simonssspirit** [comment]
The Chart events require importing the hammerjs library. Once the library is imported the left click is also triggering the event.

https://next.plnkr.co/edit/0w8jFDfogoiFHIlg

HammerJS is listed inside the Chart dependencies:

https://www.telerik.com/kendo-react-ui/components/charts/#toc-dependencies

**Comment by simonssspirit** [comment]
A note is added to the documentation: https://github.com/telerik/kendo-react-private/pull/335
