### ISSUE TITLE
DatePicker tranlsates according to locale not language

### ISSUE THREAD

**Issue by marcinkowal2015** [telerik/kendo-react#522]
## I'm submitting a...

* Bug report 

## Current behavior
DatePicker translations are taken from locale, rather than language
## Expected behavior
All texts should be translated according to language settings.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-rxsvcj?file=app/main.jsx

This is slightly modified from example in documentation https://www.telerik.com/kendo-react-ui/components/dateinputs/datepicker/.

Locale are without changes, but in both cases language is English.

## What is the motivation or use case for changing the behavior?
In our system user has possibility to set language independant from format. Due to that when language is not corresponding to locale, text are wrongly translated.

## Environment

Package versions:
Ommiting as reproducible in example

Browser:

- Chrome 80.0.3987.149

**Comment by simonssspirit** [comment]
The language option determines the language of the messages:

https://www.telerik.com/kendo-react-ui/components/dateinputs/globalization/#toc-messages

The localization is for the number and dates. For example, the date Monday 23/03/2020 after localization will be changed to the other locale by translating Monday as well, as Monday is part of the date, and for example, in Spanish, there is no word Monday.

We are using the common standard for localization coming from CLRD:

http://cldr.unicode.org/

This is the expected result, which is observed in other popular React DatePickers:

https://stackoverflow.com/questions/54399084/change-locale-in-react-datepicker

cc: @kspeyanski

**Comment by kdikov82** [comment]
This is indeed the expected behavior and everything within the format is part of the Internationalization. Displaying the names of the month and the names of the week day are all part of the format and the current locale. 

For the requirement in question, the locale can be changed as per the exact requirements and the DatePicker will display it correctly.
