### ISSUE TITLE
feat(scheduler): add RowContent custom-render component property

### ISSUE THREAD

**Issue by kspeyanski** [telerik/kendo-react#524]
Implement a custom-render component property to allow customisation over the following Row inside the Timeline/Day views:

![image](https://user-images.githubusercontent.com/30626787/77328893-def46e80-6d25-11ea-89e7-029903ed7c8f.png)

Similar to the [`jQuery Scheduler DateHeaderTemplalte`](https://docs.telerik.com/kendo-ui/api/javascript/ui/scheduler/configuration/dateheadertemplate#dateheadertemplate).

Due to the high demand of this feature, we will prioritise the `RowContent` over other custom-render properties.

**Comment by kspeyanski** [comment]
We've added a [`dateHeaderCell`](https://www.telerik.com/kendo-react-ui/components/scheduler/api/DayViewProps/#toc-dateheadercell) prop to the `WeekView , `WorkWeekView`, `DayView` and `TimelineView`. In additional [`timeHeaderCell`](https://www.telerik.com/kendo-react-ui/components/scheduler/api/TimelineViewProps/#toc-timeheadercell) is available for the `TimelineView` to allow for more granular customization options.

**Comment by colespencer1453** [comment]
@kspeyanski would it be possible to provide an example of how to use this prop to customize the view. The fields make sense I'm just not sure what to pass to the dateHeaderCell prop.

**Comment by kspeyanski** [comment]
Hello @colespencer1453 

In the following stackblitz example, i've prepared a default configuration for customizing the `dateHeaderCell` of the DayView:
https://stackblitz.com/edit/react-elugvf?file=app/main.tsx
