### ISSUE TITLE
Scheduler: Cannot select start or end date when creating/editing event

### ISSUE THREAD

**Issue by romkaskydreamer** [telerik/kendo-react#527]
## I'm submitting a
* Bug report 

## Minimal reproduction of the problem with instructions
  1. Go to example in https://www.telerik.com/kendo-react-ui/components/scheduler.
  2. Use the existing example on this page or open it in Stackblitz.
  3. Go to any event that is not all-day event or tap to create a not all-day event.
 4. Try to select start or end date.

## Current behavior
DatePicker is not visible and is not clickable. It is overflown by main pop-up window. See attached image.

## Expected behavior
DatePicker is visible and is clickable.

## Notes
You can successfully select start or end date for all-day events(both create and edit)

## What is the motivation or use case for changing the behavior?
Scheduler cannot be used to create or edit non-all-day events while those events are considered to be a key functionality of this component

## Attachments
See an image.
End Date icon clicked.
Datepicker is overflown by main pop-up window:
![image](https://user-images.githubusercontent.com/11699896/77454057-b3928200-6e00-11ea-9928-f7e4ca29a162.png)

## Version
kendo-react-scheduler 3.12.0

Best regards,
Roman

**Comment by kspeyanski** [comment]
The correct `z-index` have been applied to all pickers inside the edit form of the `KendoReact Scheduler` in version [`3.13.0`](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#toc-3130).
