### ISSUE TITLE
The name property on the Checkbox component does not work

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#528]
## I'm submitting a...

* Bug report 

## Current behavior
When you make use of the `name` property, the input HTML element does not get the name property

## Expected behavior

As per the API (https://www.telerik.com/kendo-react-ui/components/inputs/api/CheckboxProps/) 
"Specifies the name property of the input DOM element."

## Minimal reproduction of the problem with instructions
See below fork of current demo:
https://stackblitz.com/edit/react-xqapiy?file=app/main.jsx

Inspect the DOM to see that input does not have a `name` property

## Environment

Package versions:
3.12.0
Browser:

- Chrome (desktop) version  80.0.3987.149

System:

- Platform:  Windows

**Comment by simonssspirit** [comment]
@k290 This was just fixed: https://github.com/telerik/kendo-react/issues/526

The fix will be available in the dev version by the end of the day.
