### ISSUE TITLE
Scheduler: TImeline View SchedulerItem height issues

### ISSUE THREAD

**Issue by kanoshin** [telerik/kendo-react#531]
## I'm submitting a...

* Bug report 
I'm not 100%, might be a feature request, but you have a broken `SchedulerItem` appearance in your own docs.

## Current behavior
`Scheduler` hides multiline content of a `SchedulerItem` component in Timeline view mode because of hardcoded 25px height.

## Expected behavior
`Scheduler` should adjust `Slot` & `SchedulerItem` height to allow content of any height.

## Minimal reproduction of the problem with instructions
It's actually reproducible in your own docs here https://www.telerik.com/kendo-react-ui/components/scheduler/views/timeline/?_ga=2.235460356.425640505.1585192243-1354319202.1585192243. Title of a recurring event is hidden.

## What is the motivation or use case for changing the behavior?
Customize content of `SchedulerItem` in Timeline view mode.

## Environment

Package versions:
@progress/kendo-react-scheduler v3.12

**Comment by kspeyanski** [comment]
This issue is related to the `adaptiveSlotHeight` feature, which is still not available for the `KendoReact Scheduler`. 
I'm closing this in favour of: https://github.com/telerik/kendo-react/issues/460
