### ISSUE TITLE
How to customize the upload on kendo Upload component

### ISSUE THREAD

**Issue by Nassefferjeni** [telerik/kendo-react#534]
So I'm trying to implement the upload component in my application.
1- I will be uploading only images and will be uploading one image at a time
( I did that and the restrictions are working ) 
2- For each image, I want to send a post request to my backend server that is connected to the Azure:
I know that I can create a function in the `saveUrl` the problem is that I can't get the formData(binary in this example) so that I can send it to my backend server

```
<Upload batch={ false } multiple={ false } defaultFiles={ [] } withCredentials={ false }
                                    listItemUI={ this._renderMediaItem } restrictions={ {
                                        allowedExtensions: [ '.jpg', '.png' ],
                                        maxFileSize: 4000000
                                    } } saveUrl={ this._onSaveUrl }   />
```

```
_onSaveUrl = (files, options, progression) => {
        console.log(files, options.formData)
    }
```

And when I console.log the options especially the form data I get an empty object: 
![image](https://user-images.githubusercontent.com/33683191/77759068-5bdc5c80-7034-11ea-86de-e7b60c0447c5.png)

And I tried looking at the details of the file (especially the getrawfile and it didn't contain any form data also) 
any idea how to proceed?

**Comment by simonssspirit** [comment]
@Nassefferjeni  there is a method called getRawFile which can be called for each file of the files collection:
https://www.telerik.com/kendo-react-ui/components/upload/api/UploadFileInfo/#toc-getrawfile

**Comment by Nassefferjeni** [comment]
I tried that function but it will only get me these fields:

![image](https://user-images.githubusercontent.com/33683191/77907367-ccc88200-7289-11ea-84b9-f5fdd0c78997.png)

And they are not enough because I need the binary data of the image itself.

**Comment by simonssspirit** [comment]
@Nassefferjeni The other option is to use the onAdd event, control mode, and autoUpload to false.

This will allow having full control over the request when a new file is added.

https://www.telerik.com/kendo-react-ui/components/upload/modes/

https://www.telerik.com/kendo-react-ui/components/upload/api/UploadProps/#toc-autoupload

**Comment by Nassefferjeni** [comment]
@simonssspirit I already tried it but in the end, it will be always the same because the getRawFile doesn't include the binary data that I need to create formData request.

**Comment by simonssspirit** [comment]
@Nassefferjeni is it possible to show if using a standard input type file, which part of the data that is available there is missing in our Upload?

**Comment by simonssspirit** [comment]
@Nassefferjeni is the issue resolved or assistance is still needed?

**Comment by Nassefferjeni** [comment]
@simonssspirit no no thank you the issue is resolved, I was so focused on the idea of getting the binary but it seems like the component is handling it. I used the onBeforeUpload event to add some options and it worked. Thank you again.
Sorry for the late response.

**Comment by santanu879** [comment]
Can u share the added option in onBeforeUpload Event?

**Comment by iamsirjan** [comment]
Help me with this I am getting the same problem   @Nassefferjeni

**Comment by simonssspirit** [comment]
@iamsirjan  could you please specify the issue that occurs?

Also, we can suggest using our dedicated support system for questions as we monitor it and have guaranteed response time.

**Comment by simonssspirit** [comment]
Also, as mentioned the getRawFile() method returns the original file. Then we can use the standard [FileReader ](https://developer.mozilla.org/en-US/docs/Web/API/FileReader)object to get it as binary:

https://stackblitz.com/edit/react-wy2k7a?file=app/main.jsx

**Comment by iamsirjan** [comment]
@simonssspirit  yes i didnt saw that getRawFIle() helped me 
thanks and sorry for late response
