### ISSUE TITLE
Import messages from Kendo UI

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#536]
As Kendo UI for jQuery has messages for the components collected over many years, we can check if it is possible to write a script that will parse the messages from the Kendo UI for jQuery format to KendoReact one.

This will greatly increase the collection messages that we have for multiple languages.

**Comment by silviyaboteva** [comment]
In addition, we can review if some of our new components don't have their messages included in the https://github.com/telerik/kendo-react-messages repo.

**Comment by simonssspirit** [comment]
After long research and different tests it seems that the message from the Kendo UI widgets is very different than the ones in KendoReact.

What we can do is provide a link to that message collection as this will allow the user to get the transactions and construct the required JSON manually. 

We will keep looking for a way to automate the process.

**Comment by kdikov82** [comment]
Although that it seems possible to make a mapping between the two structures, I have gone through lots of messages in both KendoReact and Kendo UI and there are many cases with different messages for the same UI, which will make using the messages from Kendo UI a huge breaking change. Additionally, some messages are missing and some are part of other components (that could be resolved with the mapping, but it is still inconvenience and might cause problems in the long run).

I am closing this item and in the future we might put more thoughts into unifying the structure and the messages between all products.
