### ISSUE TITLE
Allow returning null from a columnMenu function to not render the column menu.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#539]
Allow returning null from a columnMenu function to not render the column menu.

Currently, we support this:
````
 columnMenu={null}
````
It will be good to support this as well to handle more complex dynamic cases:

````
 columnMenu={()=> null}
````

**Comment by vladimirivanoviliev** [comment]
After additional research on the topic it seems impossible to have dynamic rendering on this level. To have good user experience, we should hide the button for the menu as well, which means its required to execute this component on each render of the Grid to see if it returns something, which doesn't make sense. The best way to achieve this is:
- https://stackblitz.com/edit/react-gqa3ab?file=app/main.jsx
