### ISSUE TITLE
Infinite Scrolling Feature

### ISSUE THREAD

**Issue by IreneMarquet** [telerik/kendo-react#54]
I want to implement infinite scrolling in my web application using Kendo react. 

I saw in the documentation that you have available virtual scrolling, but this will delete the previous page when we scroll to the next one: https://www.telerik.com/kendo-react-ui/components/grid/scroll-modes/

We will like to keep the previous page, as we are implementing a master-detail-grid:https://www.telerik.com/kendo-react-ui/components/grid/advanced-features/hierarchy/
and we want to keep the rows that were already opened previously.

- Do you have any feature that helps with this functionality we request? 
- Otherwise, do you have in the roadmap infinite scrolling feature?

Thanks a lot.

**Comment by Xizario** [comment]
@IreneMarquet , The grid supports dynamically change of the data. To implement infinite scrolling, bind more data when the user have scrolled to the bottom.

Here is a sample of how this works: https://stackblitz.com/edit/react-grid-infinite-scroll?file=index.js

**Comment by lekhasy** [comment]
Hi @Xizario, the sample doesn't work since it handle both vertical and horizontal scroll event.
You can scale down the screen size to see the behavior when horizontal scroll appear.
I have tried to prevent horizontal scroll:
```javascript
  lastScrollTop = null; 

  scrollHandler = (e) => {
    // prevent horizontal scroll
    if (this.lastScrollTop === e.target.scrollTop) { return; }
    this.lastScrollTop = e.target.scrollTop; 
    if (e.target.scrollTop + 10 >= e.target.scrollHeight - e.target.clientHeight) {
      const moreData = availableProducts.splice(0, 10);
      if (moreData.length > 0) {
        this.setState({ gridData: this.state.gridData.concat(moreData) });
      }
    }
  };`

but the problem is still.
I have made some investigation and turn out, the horizontal scroll target element is different to vertical scroll one.

**Comment by Xizario** [comment]
@lekhasy , I have updated the example above, and added some more columns to ensure the horizontal scrollbar is visible.

**Comment by lekhasy** [comment]
@Xizario The sample work with that simple scenario, but with more complex one like expandable row, where there are an detail grid for each row.
The scoll event from detail grid bubble up the div which handle bubble event.
I will find a way to work around this, but i think it's nice if kendo support the scroll api out of the box.

**Comment by Xizario** [comment]
@lekhasy we could `onScroll` event for the Grid, that wraps and re-throws the native scroll event only if the target is the same as the grid's data scroll-able container. 
This should remove the need of further element checks and will work independently for child/parent grids and other scroll-able containers on the page.

Is this sounds okay, or there is something else you like to see in the API as well?

**Comment by lekhasy** [comment]
No thanks @Xizario , the native scroll event listener is what i really want. I don't think we need more extra stuff in the API.

**Comment by simonssspirit** [comment]
The example is already added to the documentation:

https://www.telerik.com/kendo-react-ui-develop/components/grid/scroll-modes/#toc-infinite-scrolling

**Comment by rafageist** [comment]
You must check if the grid have vertical scroll, and that is, compare clientHeight with scrollHeight (**e.target.scrollHeight - e.target.clientHeight**). If you dont do that, the horizontal scrolling will try to load more data.

```
if (
            e.target.scrollTop + 10 >=
            e.target.scrollHeight - e.target.clientHeight
            && e.target.scrollHeight - e.target.clientHeight > 0
        ) {
```
