### ISSUE TITLE
Focuses and selected button in the Pager has barely visible button content. (Bootstrap theme)

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#540]
Focuses and selected button in the Pager has barely visible button content. (Bootstrap theme)

![image](https://user-images.githubusercontent.com/11087921/78145274-58344580-7439-11ea-9d6e-29cf513d7af0.png)

There is a style with higher priority when the button is focused.

In Kendo UI for Angular, this is resolved by making the buttons not focusable.

**Comment by silviyaboteva** [comment]
Reproducible in Bootstrap theme `v4.13.0`. Fixed in `v4.14.0`.
