### ISSUE TITLE
feat(scheduler): allow edit form customisation

### ISSUE THREAD

**Issue by kspeyanski** [telerik/kendo-react#542]
Allow easy customisation of the SchedulerEditor component.

While complete override of the form is possible by passing a custom [`form`](https://www.telerik.com/kendo-react-ui-develop/components/scheduler/api/SchedulerEditItemProps/#toc-form), it's not clear how to extend the current editor with additional fields and/or remove some of the fields.

**Comment by simonssspirit** [comment]
requested also in the ticket: 1462954.
The request is connected to removing most of the fields and leaving only the repeat functionality.

**Comment by simonssspirit** [comment]
Requested again in ticket number 1463660

The request is connected to disabling the AllDaySlot and timezone options

**Comment by InaGlushkova** [comment]
Similar request in ticket: 1466352.
The request is connected to editing the current `edit form` and more particular customization of the fields labels and the label of the dialog - 'Event'.

**Comment by simonssspirit** [comment]
Requested again in 1468140

**Comment by simonssspirit** [comment]
requested again in : 1471570

**Comment by kspeyanski** [comment]
Requested again in: 1472847

**Comment by simonssspirit** [comment]
Requested again in 1473446

**Comment by simonssspirit** [comment]
requested in 1474730

**Comment by simonssspirit** [comment]
requested in 1477096

**Comment by simonssspirit** [comment]
requested again in 1492584

**Comment by metrobpm** [comment]
> requested again in 1492584

This is also needed for our application.

**Comment by kspeyanski** [comment]
A quick update on this: we will be heavily focusing on this feature in the next 3 weeks and while i can not give an estimate on when it will be available, you can expect it by the end of the month.

**Comment by InaGlushkova** [comment]
Requested again in 1497299

**Comment by FesterCluck** [comment]
@kspeyanski Can you give an update?

**Comment by kspeyanski** [comment]
Hi @FesterCluck ,

We're still working on this.

One major showstopper we're facing is exposing the `RecurrenceEditor` as a separate component. It's a complex editor and we are trying to provide full cutomization without sacrificing out-of-the-box functionalities.

As always, we're 100% dedicated to this task at the moment and i will be updating this issue once i have more information on when can we release this.

Thank you for your patience.

**Comment by kmbro** [comment]
Is it reasonable to assume this feature will be available before the end of the year?

**Comment by kspeyanski** [comment]
Hello @kmbro ,

We're working on releasing this feature in our `dev` channel. Given our testing phase pass successfully, we'll do our best to have it released this week.

I will update the issue once i have more information.

Thank you for your patience.

**Comment by kspeyanski** [comment]
Hello,

We've just released the `form` customization feature with our latest `dev` release.

Please refer to the [Scheduler Form Customization](https://www.telerik.com/kendo-react-ui-develop/components/scheduler/customization/form/overview/) and [Scheduler FormEditor Customization](https://www.telerik.com/kendo-react-ui-develop/components/scheduler/customization/form/editor/) articles.

As always, please let us know if you have any feedback in regards to the feature, API or any bugs you encounter.
