### ISSUE TITLE
DateInput doesn't have focus style

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-react#543]
Currently, there is no `k-state-focused` class, applied to the DateInput component. 

To reproduce it, check here: [https://www.telerik.com/kendo-react-ui/components/dateinputs/](https://www.telerik.com/kendo-react-ui/components/dateinputs/). 
The resto of the components have a box-shadow styling when focused.

**Comment by InaGlushkova** [comment]
The issues has been resolved in version [`3.13.0@dev`](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#toc-3130-dev202004130848)
For more information about obtaining development build, please refer to the following article:
https://www.telerik.com/kendo-react-ui-develop/components/installation/development-builds/
