### ISSUE TITLE
feat(scheduler): implement currentTimeMarker

### ISSUE THREAD

**Issue by kspeyanski** [telerik/kendo-react#549]
Implement current-time visual in Timeline and Day views.

**Comment by vladimirivanoviliev** [comment]
As a side note - currently you can highlight today slots by utilizing custom view slots:
- https://stackblitz.com/edit/react-7svkkq?file=app/main.jsx

**Comment by lalithmaddali** [comment]
@Brandon.Quaranto@progress.com

**Comment by kspeyanski** [comment]
The `currentTime` feature have been successfully implemented in version [`3.18.0@dev`](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/) of the `@progress/kendo-react-scheduler` package.

Please refer to the [`DayView currentTimeMarker`](https://www.telerik.com/kendo-react-ui-develop/components/scheduler/views/day/#current-time-marker) and [`TimelineView currentTimeMarker`](https://www.telerik.com/kendo-react-ui-develop/components/scheduler/views/timeline/#current-time-marker) articles for more information.
