### ISSUE TITLE
As replace the + icon with ^ v, Only show the icon (^ v) only when the mouse hovers over the card

### ISSUE THREAD

**Issue by Allandesenvolve** [telerik/kendo-react#550]
In the parameter screen, I need to replace the + icon with ^ v, in order to collect the descriptive text of the kendo React description. Only show the icon (^ v) only when the mouse hovers over the card. This has to be done throughout the column.

I used [link] (https://www.telerik.com/kendo-react-ui/components/grid/advanced-features/detail/) to create the columns. Collapse / expand mode is already activated.

This [image] (https://pasteboard.co/J3W0l28.jpg) shows better what I want to change.

**Comment by simonssspirit** [comment]
@Allandesenvolve 
Please check the following demo on making a custom expand collapse column to allow rendering the desired icons and the desired place:

https://www.telerik.com/kendo-react-ui/knowledge-base/custom-expand-collapse-column/

**Comment by simonssspirit** [comment]
The questions seem resolved.
