### ISSUE TITLE
Time Picker value not being set

### ISSUE THREAD

**Issue by GilWard** [telerik/kendo-react#551]
## I'm submitting a...
* Bug Report

## Current behavior
If the time picker has incremental steps and you type a value that is not available in the time picker popup, opening the popup and clicking "set" will not change the value of the time picker.

## Expected behavior
The value of the time picker changing to what you've set it to.

## Minimal reproduction of the problem with instructions
https://www.telerik.com/kendo-react-ui/components/dateinputs/timepicker/incremental-steps/

![KendoTimePicker](https://user-images.githubusercontent.com/63768987/79416797-aa579800-7fef-11ea-84bc-13c81a787dc5.jpg)

1. Type "33" into the minutes value of the time picker.
2. Click on the clock icon to open the popup.
3. Press "set".
4. The popup will close and the value will not have changed.

## What is the motivation or use case for changing the behavior?
Improving the usability of the time picker widget.

## Environment
Browser:
- Chrome (desktop) Version 81.0.4044.113 (Official Build) (64-bit)

**Comment by kspeyanski** [comment]
The Issues has been resolved in the `dev` version of the `@progress/kendo-react-dateinputs` package, and can be observed in the following stackblitz example:
https://stackblitz.com/edit/react-j4jqrm

For more information about obtaining development builds, please refer to this article:
https://www.telerik.com/kendo-react-ui-develop/components/installation/development-builds/
