### ISSUE TITLE
Make all the rows expanded and disable the pointer cursor

### ISSUE THREAD

**Issue by Nassefferjeni** [telerik/kendo-react#553]
So I am working with KendoTreeList and I already have a custom render for the cells.
Now I am making all the rows expanded by default and I took out the onExpand event handler so the user can't call that funcion.

I just need to know if there is any chance to make the cursor default not on pointer when I am on top of the expand icon 

this is my code for the rendering of the expandable cell:

`
if (props.expandable) {
          return (
                <cell.type { ...cell.props } className={ cell.props.className ?  `expandable expandable2` :'expandable2' }>
                    <div className={ classes.defaultCursor }>{ cell.props.children }</div>
                </cell.type>
          );
        }`

as you can I defined a className default cursor but it doesn't seem to be working

**Comment by simonssspirit** [comment]
@Nassefferjeni I assume that this occurs because the CSS selector of the icon that changes the style is with higher priority.
The following CSS will change it:

````
.k-widget .k-icon.k-i-collapse {
    cursor: default;
}
.k-widget .k-icon.k-i-expand, .k-widget .k-icon.k-i-collapse {
    cursor: default;
}
````

https://stackblitz.com/edit/react-nqlva2?file=index.html

**Comment by simonssspirit** [comment]
The question is considered resolved after one week of inactivity. Please comment if additional assistance is needed.
