### ISSUE TITLE
Tooltips with auto do not get anchored properly

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#555]
## I'm submitting a...

* Bug report 

## Current behavior
When you have a tooltip with position auto, the "arrow" is not anchored to the element.

## Expected behavior
Keep the arrow position above the anchor

## Minimal reproduction of the problem with instructions
Open the following stackblitz example in full screen

https://stackblitz.com/edit/react-vfdvtk-18rxf8?file=app/main.jsx

Note how the tooltip is anchored:
![image](https://user-images.githubusercontent.com/5611876/79878983-677e3180-83ee-11ea-9daa-8a65177bb41a.png)

For smaller icons/buttons the issue is more apparent:
https://stackblitz.com/edit/react-vfdvtk-barcvg?file=app/main.jsx

![image](https://user-images.githubusercontent.com/5611876/79946941-3abf2e00-8471-11ea-9864-8a886409eac7.png)

## What is the motivation or use case for changing the behavior?
When using position auto for long tooltips it should display reasonably

## Environment

Package versions:
3.12.0

Browser:

- Chrome (desktop) version 80

System:
- Platform:  Windows

**Comment by simonssspirit** [comment]
We have added a property to adjust the callout position for similar cases:

https://www.telerik.com/kendo-react-ui/components/tooltip/api/TooltipProps/#toc-setcalloutonpositionauto

More can be found in this issue on a similar subject: https://github.com/telerik/kendo-react/issues/265

**Comment by simonssspirit** [comment]
closing as it is a duplicated of https://github.com/telerik/kendo-react/issues/265
