### ISSUE TITLE
Tooltip with parentTitle shows 2 tooltips (both browser and Kendo)

### ISSUE THREAD

**Issue by joccd** [telerik/kendo-react#556]
Hello,

You can see on this example : 
https://stackblitz.com/edit/react-bmieen

There are two tooltips (one from the browser, one from Kendo)

Regards

**Comment by simonssspirit** [comment]
@joccd Thank you for reporting this.

I tested it and it seems to be connected to the svg element as if the SVG is replaced with another DOM element the issue does not occur.

We will connect this with our issue for the SVG support:

https://github.com/telerik/kendo-react/issues/258

**Comment by joccd** [comment]
@simonssspirit,

Any news ?

Regards,

**Comment by simonssspirit** [comment]
Currently, this not in our short-term ToDo list. We will be monitoring the interest in it and plan it accordingly.

**Comment by Xizario** [comment]
Fixed in 4.7.0
