### ISSUE TITLE
Tooltips in pre-Chromium Edge have a strange block

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#558]
* Bug report 

## Current behavior
There is a strange white block that appears above the tooltip. It only happens the first time you hover over a particular tooltip.
![image](https://user-images.githubusercontent.com/5611876/80099681-295c4b80-856f-11ea-8095-d423d290bb6e.png)
Video attached:
https://www.loom.com/share/9dd602e7f1ce42a495c704555e06b494

## Expected behavior
No strange blocks

## Minimal reproduction of the problem with instructions
Go  to Kendo demo in the latest version of pre-chromium Edge (Microsoft Edge 44.18362.449.0)
-->

## What is the motivation or use case for changing the behavior?
Chromium based Edge is not rolled out to everyone yet

## Environment

Package versions:
Current demo
https://www.telerik.com/kendo-react-ui/components/tooltip/

```

Browser:

- Edge version 44.18362.449.0

<!-- Add any additional information that might be relevant. -->

**Comment by simonssspirit** [comment]
@k290 
We will research this. At first look, the issue seems that Edge decides to show an empty browser tooltip even if the title is set to empty string.

**Comment by kdikov82** [comment]
Working correctly with latest versions
