### ISSUE TITLE
Incorrect placement of close button in ComboBox

### ISSUE THREAD

**Issue by louisnow** [telerik/kendo-react#560]
## I'm submitting a...

* Bug report

## Current behavior
The ComboBox's clear button has incorrect CSS causing it render like this. 
![2020-04-23-185055_259x39_scrot](https://user-images.githubusercontent.com/6024271/80126910-3ac64780-85b1-11ea-8be6-6eb3cde4d3cc.png)

The faulty CSS is here
![2020-04-23-185118_314x199_scrot](https://user-images.githubusercontent.com/6024271/80126979-4d408100-85b1-11ea-8e3d-dffe92217a72.png)

When using calc, all units must match, `0` has to used as `0px`

`right: calc(calc(8px + 16px) + 0px + 4px)`

## Expected behavior

The close button must be on the right

## Minimal reproduction of the problem with instructions
The theme is material UI `@import '~@progress/kendo-theme-material/scss/all';`
Now use a ComboBox and look at the placement of the close button.
The SCSS does not seem to be correctly converting to the right CSS.
```
"sass-loader": "^8.0.2",
"node-sass": "^4.14.0",
```

## What is the motivation or use case for changing the behavior?
It's incorrect

## Environment

Package versions:

```
├── @babel/core@7.8.7
├── @babel/plugin-proposal-class-properties@7.8.3
├── @babel/plugin-proposal-decorators@7.8.3
├── @babel/plugin-proposal-nullish-coalescing-operator@7.8.3
├── @babel/plugin-proposal-optional-chaining@7.8.3
├── @babel/plugin-syntax-dynamic-import@7.8.3
├── @babel/plugin-transform-runtime@7.8.3
├── @babel/preset-env@7.8.7
├── @babel/preset-react@7.8.3
├── @babel/preset-typescript@7.8.3
├── @babel/runtime@7.8.7
├── @babel/runtime-corejs3@7.8.7
├── @hot-loader/react-dom@16.12.0
├── @material-ui/core@4.9.5
├── @material-ui/pickers@3.2.10
├── @progress/kendo-data-query@1.5.3
├── @progress/kendo-drawing@1.6.0
├── @progress/kendo-react-animation@3.12.0
├── @progress/kendo-react-charts@3.12.0
├── @progress/kendo-react-data-tools@3.12.0
├── @progress/kendo-react-dateinputs@3.12.0
├── @progress/kendo-react-dropdowns@3.12.0
├── @progress/kendo-react-excel-export@3.12.0
├── @progress/kendo-react-gauges@3.12.0
├── @progress/kendo-react-grid@3.12.0
├── @progress/kendo-react-inputs@3.12.0
├── @progress/kendo-react-intl@3.11.0
├── @progress/kendo-react-pdf@3.12.0
├── @progress/kendo-react-popup@3.12.0
├── @progress/kendo-theme-default@4.17.0
├── @progress/kendo-theme-material@3.14.0
├── @typescript-eslint/eslint-plugin@2.23.0
├── @typescript-eslint/eslint-plugin-tslint@2.23.0
├── @typescript-eslint/parser@2.23.0
├── array-move@2.2.1
├── autobind-decorator@2.4.0
├── babel-cli@6.26.0
├── babel-core@6.26.3
├── babel-loader@8.0.6
├── babel-preset-react-app@9.1.1
├── classnames@2.2.6
├── color-convert@2.0.1
├── compression-webpack-plugin@3.1.0
├── copy-webpack-plugin@5.1.1
├── core-js@3.6.4
├── css-loader@3.4.2
├── date-fns@2.10.0
├── dotenv@8.2.0
├── dotenv-webpack@1.7.0
├── eslint@6.8.0
├── eslint-config-prettier@6.10.0
├── eslint-plugin-import@2.20.1
├── eslint-plugin-prettier@3.1.2
├── eslint-plugin-react-hooks@2.5.0
├── eslint-plugin-simple-import-sort@4.0.0
├── file-loader@5.1.0
├── hoist-non-react-statics@3.3.2
├── html-webpack-plugin@3.2.0
├── i18next@19.3.2
├── identity-obj-proxy@3.0.0
├── image-webpack-loader@6.0.0
├── node-sass@4.14.0
├── prettier@1.19.1
├── prop-types@15.7.2
├── react@16.13.0
├── react-dom@16.13.0
├── react-hot-loader@4.12.19
├── react-redux@7.2.0
├── react-router@5.1.2
├── react-router-dom@5.1.2
├── react-select@3.0.8
├── redux@4.0.5
├── redux-thunk@2.3.0
├── regenerator-runtime@0.13.3
├── sass-loader@8.0.2
├── serve@11.3.0
├── style-loader@1.1.3
├── ts-loader@6.2.1
├── tslint@5.20.1
├── typesafe-actions@5.1.0
├── typescript@3.8.3
├── webpack@4.42.0
├── webpack-bundle-analyzer@3.6.1
├── webpack-cli@3.3.11
├── webpack-dev-server@3.10.3
```
Browser:

- Chrome (desktop) version 81

System:
- TypeScript version: v3.8.3 
- Node version: v12.16.1  
- Platform:  Linux

**Comment by simonssspirit** [comment]
@louisnow 
This was caused by change in the themes build process.

More details can be found in the following forum post:
 https://www.telerik.com/forums/kendo-theme-scss-build

**Comment by louisnow** [comment]
In my SCSS file, I've changed my import statement to 
`@import '~@progress/kendo-theme-material/dist/all.scss';`

But I still have the problem. I took a look at the code and the problem is here

```
$picker-select-border-width: 0 !default;
...
$picker-icon-offset: calc( #{$picker-select-calc-size} + #{$picker-select-border-width}  + #{$input-icon-offset}) !default;
```
The fix I have now is to set the the value explicitly in my SCSS file
```
$picker-select-border-width: 0px;
```

**Comment by louisnow** [comment]
The problem is different from the forum post. It's actually giving incorrect code. 
The build without my fix outputs this `right: calc(calc(8px + 16px) + 0 + 4px)` right now. 
Trying that line on any browser will fail. You can try the line out on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/calc) 
The forum support you linked to was related to IE11 not supporting advanced usage of `calc`.

**Comment by simonssspirit** [comment]
@louisnow Yes, the issue was originally for IE 11, but the ultimate issue was with the built process. The last reply has a runnable project with the setup, is that project has the same issue?

cc: @silviyaboteva

**Comment by silviyaboteva** [comment]
Hello @louisnow,
To explain further, kendo themes need postcss-calc to reduce nested and calc expressions and [this guide](https://github.com/telerik/kendo-themes/wiki/Compiling-themes) can help you set it up either for webpack or gulp builds.

If you want to see the discussion in themes repository, refer to https://github.com/telerik/kendo-themes/issues/834.

**Comment by louisnow** [comment]
Thanks @silviyaboteva. The guide located on the wiki of the project had what I was looking for. I'm curious why that guide is not linked to from the README of the project or from the kendo website. Github's UI does not offer any indication that a valid wiki exists for a project.

**Comment by silviyaboteva** [comment]
Hi @louisnow,
I agree that this guide has to be included in our docs as well. We already discussed this with the team. 
Still, thank you for the feedback and I'm happy that it helped!
