### ISSUE TITLE
Paste year/date inside DateInput/DatePicker/TimePicker results in incorrect value.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#562]
Paste year/date inside DateInput/DatePicker/TimePicker results in incorrect value.

If we have the value - 04/27/2020 and we paste 2009 in the year portion we will receive the date 04/27/0009 which is not expected.

**Comment by simonssspirit** [comment]
Reported again in 1472405 for the DateRangePicker as well. Raising priority.

**Comment by kspeyanski** [comment]
The issue has been resolved with version `3.16.0` of the `@progress/kendo-react-dateinputs` package:

https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#toc-3160
