### ISSUE TITLE
React Rich Text Editor does not allow spaces on Firefox

### ISSUE THREAD

**Issue by karstenk** [telerik/kendo-react#563]
## Current behavior
The React Rich Text Editor does not allow spaces on Firefox. After typing a space it deletes the space on the next keystroke.

## Expected behavior
Spaces would persist

## Minimal reproduction of the problem with instructions
In Firefox:
https://stackblitz.com/run/?file=app%2Fmain.jsx

## What is the motivation or use case for changing the behavior?
My clients use Firefox and it is causing major issues and complaints.

## Environment
Browser:
Firefox version XX

System:
- Platform:  Mac and Windows

**Comment by simonssspirit** [comment]
This is duplicate of https://github.com/telerik/kendo-react/issues/270
