### ISSUE TITLE
TreeList locked columns styling improvements.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#568]
TreeList locked columns styling improvements.

In the following example: https://stackblitz.com/edit/react-lwp4ua-kfft2x?file=app/main.jsx

1) We have the first column width set to 50px, but its actual size is smaller, causing a white space between the column and the next one.

2) When scrolling to the right the locked columns overlap with each other, losing the border and potentially hiding a part of the content.

**Comment by nstoychev** [comment]
I have increase the columns width and everything seems to work now - https://stackblitz.com/edit/react-lwp4ua-rmcdqy.
The columns width needs to fit the content of the cells.
