### ISSUE TITLE
Selecting date from table filter popup causes to scroll left the table

### ISSUE THREAD

**Issue by furkanilhan** [telerik/kendo-react#569]
- [x] I have searched the [issues](https://github.com/telerik/kendo-react/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Kendo DatePicker Sample](https://stackblitz.com/edit/react-uocfzn)
[Ant Design DatePicker Sample](https://stackblitz.com/edit/react-tukxso?embed=1&file=app/main.jsx)

### Steps to reproduce
There is a "First Date" column on my table at the end of right side.
1. Click the 3 dots next to "First Date" header, you will see the filter popup.
2. Click the "Select Date" input and a DatePicker will be pops up.
3. Choose a date from DatePicker.

When you follow these steps, you will see the table suddenly scrolls to left and DatePicker closes.
When I remove the method 'GridPageChange' on line 148, table still scrolls to left but DatePicker does not close and I can select date.

### What is expected?
Table must not scroll when I select date from DatePicker in the table filter popup.

### What is actually happening?
Selecting date from table filter popup causes to scroll the table to left. If you realize my DatePicker has a time picker. When I select a day from calender, time picker scrolls to current time. I think it triggers the table scroll.

### Kendo DatePicker Has Same Issue
Now I have tested datepicker of kendo-react. The same issue happens. I have added the [sample](https://stackblitz.com/edit/react-uocfzn). When you click to select date, table scrolls to left and datepicker pop up does not display.

![datepicker](https://user-images.githubusercontent.com/21006973/80865453-49d48600-8c92-11ea-8fbf-71a168a49e26.gif)

| Environment | Info |
|---|---|
| Kendo React Grid | 3.13.0 |
| antd | 4.2.0 |
| React | 16.13.1 |
| System | Windows 10 Enterprise 1809 |
| Browser | 81.0.4044.129 |

**Comment by simonssspirit** [comment]
Fix in 3.14.0:

https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#toc-3140

scrollLeft reset on scroll propagation
