### ISSUE TITLE
PanelBar Routing doesn't set active PanelBarItem when navigating back/forward in browser history

### ISSUE THREAD

**Issue by WHI-CH** [telerik/kendo-react#57]
Also seen in the sample here:
https://www.telerik.com/kendo-react-ui/components/layout/panelbar/routing/

**Comment by Xizario** [comment]
@WHI-CH , thank you, indeed the demo is broken.

The value of the `PanelBar` in the demo is not controlled, so it remain the same when going back and forward.
I have modified it here to make this work: [https://stackblitz.com/edit/react-pzmout?file=app/PanelBarNavContainer.js](https://stackblitz.com/edit/react-pzmout?file=app/PanelBarNavContainer.js)

We will update the demo with more clean up version of the code.

**Comment by Xizario** [comment]
It is still not planed, but I will keep this issue opened. I am not sure it will become out of the box, since the `PanelBar` could be used without routing. But we will review the code to see if the integration could become smoother.

**Comment by simonssspirit** [comment]
This is already updated in the documentation. Removing the documentation tag for now.

**Comment by kdikov82** [comment]
Closing due to existing custom implementation and demo. As mentioned previously, since the PanelBar can be used without routing, this will not be added as a built-in feature.
