### ISSUE TITLE
GridColumn filter shows a type error when passing a variable.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#571]
GridColumn filter shows a type error when passing a variable.

When we use a column collection that we render inside the Grid, passing the filter value to the column shows a type error.

https://stackblitz.com/edit/react-ts-emhu8o?file=index.tsx

A current workaround is to cast the value as any:

````
<Column field={column.field} key={index} title={column.title} filter={(column.filter as any)}/>;
````

**Comment by nstoychev** [comment]
This is expected since the columns collection type is not set. This is not an issue of the Grid component.
