### ISSUE TITLE
Add footerCellRender in the Grid.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#572]
Add footerCellRender in the Grid.

We have cellRender, headerCellRender and it will be good to have a footerCellRender as well.

**Comment by kdikov82** [comment]
The use case of cellRender, headerCellRender, etc. is to provide option for overriding the default rendering, but with the footer cell, there is no default rendering and it is defined in the footerCell only.

I am closing the issue, but @simonssspirit & @Xizario feel free to re-open it if you think there is an use case that I am not seeing.
