### ISSUE TITLE
You cannot remove the "-" sign in the Numeric Textbox

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#573]
## I'm submitting a...
>
* Bug report 

## Current behavior
If you type in a negative value into a NumericInput you have delete the whole value if you want to remove the minus sign

## Expected behavior
Allow user to backspace or delete to clear minus sign

## Minimal reproduction of the problem with instructions

1. On demo site enter "-1000"
2. Arrow to the "-" and try to clear it.

See video:
https://www.loom.com/share/74208b7dde5d4a95b7ab6b2601ea81e3

**Comment by vladimirivanoviliev** [comment]
Fixed in latest dev version.

**Comment by k290** [comment]
Thank you very much

**Comment by vladimirivanoviliev** [comment]
Released with 3.16.0-dev.202007130614
