### ISSUE TITLE
min and max attributes doesn't work with cell 

### ISSUE THREAD

**Issue by gine** [telerik/kendo-react#576]
## I'm submitting a...
* Bug report

## Current behavior

min and max attributes doesn't work if cell attribute are present

## Expected behavior

min and max attributes work with cell attribute too

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/react-ayvuky?file=app/main.jsx

## Environment

Package versions:
```
├── @capacitor/android@2.0.2
├── @capacitor/cli@1.5.1
├── @capacitor/core@2.0.2
├── @ionic/app-scripts@3.2.4
├── @ionic/react@5.1.0
├── @ionic/react-router@5.1.0
├── @progress/kendo-react-dateinputs@3.13.0
├── @progress/kendo-react-intl@3.13.0
├── @progress/kendo-theme-bootstrap@4.15.0
├── @types/node@12.12.38
├── @types/react@16.9.34
├── @types/react-dom@16.9.7
├── @types/react-router@5.1.7
├── @types/react-router-dom@5.1.5
├── ionicons@5.0.1
├── react@16.13.1
├── react-dom@16.13.1
├── react-redux@7.2.0
├── react-router@5.1.2
├── react-router-dom@5.1.2
├── react-scripts@3.4.0
└── typescript@3.7.4
```

Browser:
- Chrome (desktop) version  81.0.4044.122 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
- Chrome (Android) version (bundled with cordova?)
- Firefox version 75.0 (64bit)

System:
- TypeScript version: 3.7.4
- Node version: v10.19.0
- Platform:  Linux, Windows

**Comment by kspeyanski** [comment]
Hello @gine ,

The described behavior is due to the override of the `opacity` property in the demo.
I've modified the provided stacklitz example logic to account for the `isDisabled` property accordingly:
https://stackblitz.com/edit/react-ayvuky-ocsx7c?file=app/main.jsx
