### ISSUE TITLE
Unable to clear partial Date Input

### ISSUE THREAD

**Issue by rvramesh** [telerik/kendo-react#578]
## I'm submitting 

* Bug report 

## Current behavior

1. Place a component with DateInput (like Date Picker) as shown in https://www.telerik.com/kendo-react-ui/components/dateinputs/dateinput/placeholders/

2. Let the user enter partial date as in the below screenshot and tab out.
![image](https://user-images.githubusercontent.com/366183/81462466-55fb9e80-91d0-11ea-8195-a68e9a983e7a.png)

3. Currently there is no way to clear the text programatically. Setting the value to null has no effect as the current value is also null.

## Expected behavior

1. Goto https://react-bkktck.stackblitz.io/
2. When the clear button is clicked with partial date input the control should reset to its initial state.

When the user enters partial date / time and tabs out, clear the state of the control

## What is the motivation or use case for changing the behavior?
I have a reset button on the form and unable to clear the user entered values.

## Environment

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

**Comment by simonssspirit** [comment]
@rvramesh Please check the discussion on a similar subject in this issue: https://github.com/telerik/kendo-react/issues/368

**Comment by rvramesh** [comment]
> @rvramesh Please check the discussion on a similar subject in this issue: #368

Can the same be done in blur to reset the values back to masked value and clear the date?

**Comment by simonssspirit** [comment]
Yes , the same logic can be executed on any other event, but please have in mind that with Blur, the value will be reset every time the user leaves the DateInput:

https://stackblitz.com/edit/react-blvusd?file=app/main.jsx

**Comment by rvramesh** [comment]
Understood. Thank a lot! appreciate the help

**Comment by rvramesh** [comment]
I tried to access kendoDate from the element, but in typescript it is throwing an error `Property 'kendoDate' is private and only accessible within class 'DateInput'.ts(2341)`

**Comment by simonssspirit** [comment]
Indeed in a typescript application, this is expected as this variable was not intended to be used publicly, we only suggested it as a workaround.

This can be used to overwrite the TS error, but please have in mind that this a workaround, and we will plan on how it can be improved and to only use public API:
````
(this.endDateInput as any).kendoDate.setValue(null);
````

cc: @kspeyanski

**Comment by rvramesh** [comment]
I did solve it by typing to any. Would love to see this in public API soon.

**Comment by kspeyanski** [comment]
Closing this one in favour of: https://github.com/telerik/kendo-react/issues/705
