### ISSUE TITLE
Setting date limits on TreeListDateEditor in table cell?

### ISSUE THREAD

**Issue by joshmarnold** [telerik/kendo-react#580]
Is it possible to set date limits on a TreeListDateEditor in a table cell?

I'm unable to find any documentation on this. 

Below is a link to stackblitz where I'm testing this functionality. 
https://stackblitz.com/edit/react-3waznw?file=app/main.jsx

**Comment by simonssspirit** [comment]
@joshmarnold

This will require passing a custom cell that has a DatePicker. Then we can use the min and max properties of the DatePicker to set the range:

https://stackblitz.com/edit/react-3waznw-2rjdsi?file=app/main.jsx

**Comment by joshmarnold** [comment]
Got it, thanks.
