### ISSUE TITLE
Caret position is moving to another part if long pressing increase using key up

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-react#581]
Reported reproduction steps (windows/chrome):
Open https://www.telerik.com/kendo-react-ui/components/dateinputs/dateinput/
select year or day part and press and hold up-arrow key. The caret is moving to the beginning (day) part. 

On mac similar issue can be seen if you press up and down arrows very fast together. *Does not happen on scroll up

**Comment by simonssspirit** [comment]
Reported again in 1479934

**Comment by Xizario** [comment]
Fixed in 4.2.0
