### ISSUE TITLE
Unable to specify custom DateInput component for DateTimePicker

### ISSUE THREAD

**Issue by rvramesh** [telerik/kendo-react#582]
## I'm submitting a...

* Bug report 

## Current behavior

I am unable to specify dateInput component to be used for DateTimePicker when using typescript
## Expected behavior

I should be able to specify dateInput in props for DateTimePicker, rest of the date inputs allows this customisation when using typescript. 

Currently it provides the below error
"Failed to compile"
"Property 'dateInput' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<DateTimePicker> & Pick<Pick<Readonly<DateTimePickerProps> & Readonly<...>, "width" | ... 28 more ... | "cancelButton"> & Pick<...> & Pick<...>, "width" | ... 17 more ... | "focusedDate"> & Partial<...> & Partial<...>'.  TS2322"

## What is the motivation or use case for changing the behavior?

Other Date Inputs such as DatePicker, TimePicker and DateTimePicker supports this customisation. This is required in https://github.com/telerik/kendo-react/issues/578 in DateTimePicker

## Environment

Package versions:

```
"@progress/kendo-react-dateinputs": "^3.13.0",
```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:  
"typescript": "latest"
"node": "v12.10.0"
"npm":"6.14.4"

**Comment by kspeyanski** [comment]
I'm closing this in favour of: https://github.com/telerik/kendo-react/issues/559
