### ISSUE TITLE
Add controlled mode for the PannelBar.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#583]
Add controlled mode for the PannelBar.

Currently, the PannelBar has only uncontrolled mode and it doesn't allow dynamically changing the expanded items based that the props or state.

**Comment by simonssspirit** [comment]
requested again in 1510858

**Comment by simonssspirit** [comment]
requested again in 1522694

**Comment by simonssspirit** [comment]
requested again in 1525345

**Comment by Xizario** [comment]
Isn't this already implemented? https://www.telerik.com/kendo-react-ui/components/layout/panelbar/controlling-state/

**Comment by simonssspirit** [comment]
No, the title is misleading. You can only control it initially. If you update the state, the PanelBar is not be affected by it. Currently, the only way is to change the key to re-mount it.

**Comment by InaGlushkova** [comment]
Introduced under version [v4.14.0-dev.202201121250](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#08318a03-7652-56e8-9b66-aed7608019f3)
