### ISSUE TITLE
Expand and Collapse Group of Columns on Button Click

### ISSUE THREAD

**Issue by andreja5** [telerik/kendo-react#584]
## I'm submitting a...

How to expand and collapse group of columns on button click for React UI? I found solution for jQuery (https://docs.telerik.com/kendo-ui/knowledge-base/grid-expand-collapse-columns-group-button-click), is there something similar for React? Thank you

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by nstoychev** [comment]
Here is a similar example in React - https://www.telerik.com/kendo-react-ui/components/grid/api/GridHeaderCell/.

**Comment by kdikov82** [comment]
Here is an example that shows how to show/hide columns from a button in the header cell:
[https://stackblitz.com/edit/react-wqyurc?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-wqyurc?file=app%2Fmain.jsx)
