### ISSUE TITLE
Scheduler support for mobile Safari

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#586]
Scheduler support for mobile Safari.

Currently, the editing, the resizing, and the reordering of events does not work as expected on mobile browsers.

**Comment by kmbro** [comment]
Any update on this?

**Comment by simonssspirit** [comment]
reported again in 1486968, raising priority.

**Comment by kspeyanski** [comment]
We've implemented various improvements to support mobile `drag'n'drop` and `resize` across all web browsers in version [`3.18.0`](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#fe33e841-ad87-5419-80ac-79552cc4dc69) of the `@progress/kendo-react-scheduler` package.

I will close this issue for now, but feel free to reopen it if you encounter any problems with the editing experience on mobile devices.
