### ISSUE TITLE
Editor moves cursor to the end in some cases

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#587]
## I'm submitting a...
* Bug report

## Current behavior
Typing will move the carat to the end of the text.

## Expected behavior
Carat stays where expected unless user moves it.

## Minimal reproduction of the problem with instructions
I've replicated this issue here:
https://stackblitz.com/edit/react-dasyy5

1. Click in the middle of the text "Editor sample content"
2. Type "test"
3. The carat will move to the end of the line, so you get "Editor t sample contentest" instead of "Editor test sample content"

![image](https://user-images.githubusercontent.com/12272970/82166843-f2245480-98f8-11ea-94a9-f1f866384771.png)

![image](https://user-images.githubusercontent.com/12272970/82166851-f8b2cc00-98f8-11ea-8946-493981244ff7.png)

## What is the motivation or use case for changing the behavior?
The new controlled mode's main benefit is it allows you to modify the html as the user types. Currently doing any processing seems to cause the carat to move which is annoying.

Browser:
- Chrome (desktop) version 81.0.4044.138 (Official Build) (64-bit)

**Comment by nstoychev** [comment]
This looks expected to me.

The new HTML is applied with a delay and as a result editor's html has been replaced. The issue also happens if a textarea is used - https://stackblitz.com/edit/react-dasyy5-24zh4r?file=app/main.jsx

**Comment by GeoMarkou** [comment]
Yes on further research it seems this is a common React problem, not a Kendo problem. I installed a new dependency "caret-pos" to record the caret position and reset it after calling setState, and it seems to work correctly now.

https://stackblitz.com/edit/react-dasyy5-141gx9
