### ISSUE TITLE
Scheduler editor start and end dates are always equal to the first edit date.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#589]
Scheduler editor start and end dates are always equal to the first edit date:

Steps To Reproduce:

1) Go to https://www.telerik.com/kendo-react-ui/components/scheduler/

2) Double click on any slot on June 24th in the Scheduler and you get June 24 as your Start and End dates [This is the expected behavior]

3) Now change the date to June 25th

4) Double click on any slot on June 25th in the Scheduler and you get June 24 as your Start and End dates [This is NOT the expected behavior, it should be June 25]

**Comment by simonssspirit** [comment]
Reported again in 1473842, raising priority.

**Comment by simonssspirit** [comment]
reported again in 1478870

**Comment by kspeyanski** [comment]
The issue has been successfully resolved in version [`3.18.0`](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#fe33e841-ad87-5419-80ac-79552cc4dc69) of the `@progress/kendo-react-scheduler` package.

Feel free to reopen this issue if you encounter the problem in any other scenario.
