### ISSUE TITLE
Required Style Not Removed on Input Change

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#59]
## I'm submitting a...
* Bug report

## Current behavior
When required is set to true on an Input, setting the value from code doesn't seem to update the invalid state consistently.

## Expected behavior
Setting the value from code removes the k-state-invalid class.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-faqref?file=app%2Fmain.js
Click the button to set the value of the input. This doesn't remove the invalid class from the input.

## What is the motivation or use case for changing the behavior?
We have a form that is loaded with data depending on what entity they are editing. The input appears red when the existing data is loaded from the database.

## Environment
Browser:

- Chrome (desktop) Version 68.0.3440.106 (Official Build) (64-bit)

System:
- Node version: v8.9.3
- NPM version: 6.3.0
- Platform:  Windows

**Comment by Xizario** [comment]
Confirmed as a bug, here is sample with native input as well:
https://stackblitz.com/edit/react-faqref-vd1i1a?file=app/main.js

**Comment by Xizario** [comment]
Fixed in `1.3.0-dev.201808171015` https://stackblitz.com/edit/react-faqref-ntmg2z?file=app/main.js

**Comment by kspeyanski** [comment]
Hello @GeoMarkou , the issue has been fixed in the latest [`1.3.0`](https://www.npmjs.com/package/@progress/kendo-react-inputs) version of `@progress/kendo-react-inputs`
