### ISSUE TITLE
Making the title empty in kendo Grid messes the customColumnMenu

### ISSUE THREAD

**Issue by Nassefferjeni** [telerik/kendo-react#591]
I'm providing an empty title to the grid and also a customColumnMenu, but providing the empty title makes the customColumnMenu half disappear

![image](https://user-images.githubusercontent.com/33683191/82329607-dcd72500-99e1-11ea-9d6a-2f32afe24986.png)

and this is my columns array: 
```
[
  { field: 'status', title: ' ' },
  { field: 'asn', title: 'ASN ' },
  { field: 'dc', title: ' DC' }
] 
```

as you can see the 3 dots for the customColumnMenu is not the same for the empty title as the others.

**Comment by kdikov82** [comment]
Not reproducible with the latest version (5.10.0)

**Comment by Nassefferjeni** [comment]
Thank you @kdikov82 💯
