### ISSUE TITLE
Custom Monthly Date Picker date defaults to the first. How to default to last day of month?

### ISSUE THREAD

**Issue by joshmarnold** [telerik/kendo-react#592]
I've customized the Date Picker to be a monthly Date Picker. The navigation panel shows years and the calendar shows only months. (Stackblitz example below) Currently, when I select a month, the date shows as 9/1/1999. I'd like the date to be the end of the month instead. Something like 9/28/1999. Is there a built-in Kendo way to have the default date set to the end of the month rather than the first?

https://stackblitz.com/edit/monthly-date-picker-example?file=app%2Fes.json

**Comment by kspeyanski** [comment]
Hello @joshmarnold ,

Indeed, it is possible through the use of the `lastDayOfMonth` method provided by the `@progress/kendo-date-math` package.

Please find the extended example bellow:
https://stackblitz.com/edit/monthly-date-picker-example-ihmpzi

**Comment by joshmarnold** [comment]
Got it, works perfectly. Thanks!
