### ISSUE TITLE
ReactUI File upload localization documentation

### ISSUE THREAD

**Issue by Logang1007** [telerik/kendo-react#594]
Please can you add documentation for the ReactUI file upload on how to localize.

**Comment by silviyaboteva** [comment]
If you mean the KendoReact Upload component, a globalization article is available at https://www.telerik.com/kendo-react-ui/components/upload/globalization/.  There is a demo that demonstrates how to localize the built-in messages of the component.

Please re-open the issue if this is not what you asked for.
