### ISSUE TITLE
GridColumn field property does not support . (dot) in the name

### ISSUE THREAD

**Issue by mkovac-conductive** [telerik/kendo-react#597]
Example:

`const data = [{
    "0": 35,
    "1.35": 22
}, {
    "0": 22,
    "1.35": 22
}]`

`<Column field="0" title="0"/>` // The value is there (35,22)
`<Column field="1.35" title="1.35"/>` // The value is **missing** (22,22 is expected)

![image](https://user-images.githubusercontent.com/46827714/82899578-84f96a80-9f5b-11ea-82a0-186198a10d44.png)

 **Version**: "@progress/kendo-react-grid": "**3.14.0**"

**Comment by simonssspirit** [comment]
@mkovac-conductive 

Apologies for not responding to this.

This is expected as we . is used to supporting nested fields - Category.CategoryID.

We can only support one of them as there is no a reliable way to know if this is the actual name of the field or a nested field.
