### ISSUE TITLE
react combobox doesn't support grouping like how angular does

### ISSUE THREAD

**Issue by ThulaniMakoba** [telerik/kendo-react#598]
I'm submitting a documentation request

Currently in kendo react combobox documentation there's no information on how to add grouping to the dropdown list like how Kendo has done it on Angular  https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/grouping/

**Comment by simonssspirit** [comment]
The ComboBox already support grouping:

https://www.telerik.com/kendo-react-ui/components/dropdowns/combobox/grouping/
