### ISSUE TITLE
Error when scrolling in time picker

### ISSUE THREAD

**Issue by BustaFett** [telerik/kendo-react#599]
I'm submitting a Bug report 

Current behavior
Using the Time Picker, highlight minutes and use mouse scroll wheel, Chrome is throwing the following error: [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.

## Expected behavior
To not get that error message

## Minimal reproduction of the problem with instructions
Add Time Picker to page, highlight minutes and use mouse scroll wheel.

## Environment

Package versions:
orthotom-mds@0.1.0 D:\source-code\orthotom-mds
+-- @fortawesome/fontawesome-svg-core@1.2.27
+-- @fortawesome/free-brands-svg-icons@5.12.1
+-- @fortawesome/free-regular-svg-icons@5.12.1
+-- @fortawesome/free-solid-svg-icons@5.13.0
+-- @fortawesome/react-fontawesome@0.1.8
+-- @kdpw/msal-b2c-react@0.0.3
+-- UNMET DEPENDENCY @progress/kendo-data-query@1.5.3
| `-- tslib@1.9.3
+-- @progress/kendo-drawing@1.6.0
+-- UNMET DEPENDENCY @progress/kendo-react-common@3.14.0
| +-- @telerik/kendo-draggable@2.2.0
| `-- prop-types@15.7.2 deduped
+-- UNMET DEPENDENCY @progress/kendo-react-data-tools@3.14.0
| +-- @progress/kendo-react-common@3.14.0
| `-- prop-types@15.7.2 deduped
+-- UNMET DEPENDENCY @progress/kendo-react-dateinputs@3.14.0
| +-- @progress/kendo-date-math@1.5.1
| +-- @progress/kendo-react-buttons@3.14.0
| +-- @progress/kendo-react-common@3.14.0
| +-- @progress/kendo-react-labels@3.14.0
| +-- @progress/kendo-react-popup@3.14.0
| `-- prop-types@15.7.2 deduped
+-- UNMET DEPENDENCY @progress/kendo-react-dialogs@3.14.0
| +-- @progress/kendo-react-common@3.14.0
| `-- prop-types@15.7.2 deduped
+-- UNMET DEPENDENCY @progress/kendo-react-dropdowns@3.14.0
| +-- @progress/kendo-react-common@3.14.0
| +-- @progress/kendo-react-labels@3.14.0
| +-- @progress/kendo-react-popup@3.14.0
| `-- prop-types@15.7.2 deduped
+-- UNMET DEPENDENCY @progress/kendo-react-editor@3.14.0
| +-- @progress/kendo-editor-common@0.3.0
| `-- prop-types@15.7.2 deduped
+-- UNMET DEPENDENCY @progress/kendo-react-excel-export@3.14.0
| +-- @progress/kendo-file-saver@1.1.0
| +-- @progress/kendo-ooxml@1.5.0
| `-- prop-types@15.7.2 deduped
+-- UNMET DEPENDENCY @progress/kendo-react-gauges@3.14.0
| +-- @progress/kendo-charts@1.14.0
| +-- @progress/kendo-react-common@3.14.0
| `-- prop-types@15.7.2 deduped
+-- UNMET DEPENDENCY @progress/kendo-react-grid@3.14.0
| +-- @progress/kendo-react-common@3.14.0
| `-- prop-types@15.7.2 deduped
+-- UNMET DEPENDENCY @progress/kendo-react-inputs@3.14.0
| +-- @progress/kendo-react-common@3.14.0
| +-- @progress/kendo-react-labels@3.14.0
| +-- @progress/kendo-react-popup@3.14.0
| `-- prop-types@15.7.2 deduped
+-- UNMET DEPENDENCY @progress/kendo-react-intl@3.14.0
| +-- @telerik/kendo-intl@2.2.0
| `-- prop-types@15.7.2 deduped
+-- UNMET DEPENDENCY @progress/kendo-react-layout@3.14.0
| +-- @progress/kendo-react-animation@3.14.0
| +-- @progress/kendo-react-common@3.14.0
| +-- @progress/kendo-react-popup@3.14.0
| `-- prop-types@15.7.2 deduped
+-- UNMET DEPENDENCY @progress/kendo-react-popup@3.14.0
| +-- @progress/kendo-popup-common@1.7.0
| +-- @progress/kendo-react-animation@3.14.0
| +-- @progress/kendo-react-common@3.14.0
| `-- prop-types@15.7.2 deduped
+-- UNMET DEPENDENCY @progress/kendo-react-progressbars@3.14.0
| +-- @progress/kendo-react-common@3.14.0
| `-- prop-types@15.7.2 deduped
+-- UNMET DEPENDENCY @progress/kendo-react-upload@3.14.0
| +-- @progress/kendo-react-common@3.14.0
| +-- axios@0.18.1
| `-- prop-types@15.7.2 deduped
+-- UNMET DEPENDENCY @progress/kendo-theme-bootstrap@4.16.1
+-- axios@0.19.2
+-- connected-react-router@6.7.0
+-- font-awesome@4.7.0
+-- UNMET PEER DEPENDENCY immutable@^3.8.1 || ^4.0.0-rc.1
+-- lodash@4.17.15
+-- moment@2.24.0
+-- moment-timezone@0.5.27
+-- node-sass@4.14.1
+-- prop-types@15.7.2
+-- qs@6.9.1
+-- react@16.12.0
+-- react-azure-adb2c@0.2.0
+-- react-barcode@1.4.0
+-- react-barcode-reader@0.0.1
+-- react-datepicker@2.12.1
+-- react-dom@16.12.0
+-- react-idle-timer@4.2.12
+-- react-moment@0.9.7
+-- react-redux@7.2.0
+-- react-router@5.1.2
+-- react-router-dom@5.1.2
+-- react-scripts@3.4.0
+-- react-signature-canvas@1.0.3
+-- react-to-print@2.5.1
+-- reactstrap@8.4.1
+-- redux@4.0.5
+-- redux-action-creator@3.0.0
+-- redux-saga@1.1.3
`-- UNMET PEER DEPENDENCY seamless-immutable@^7.1.3

npm ERR! missing: @progress/kendo-data-query@1.5.3, required by orthotom-mds@0.1.0
npm ERR! missing: @progress/kendo-react-common@3.14.0, required by orthotom-mds@0.1.0
npm ERR! missing: @progress/kendo-react-data-tools@3.14.0, required by orthotom-mds@0.1.0
npm ERR! missing: @progress/kendo-react-dateinputs@3.14.0, required by orthotom-mds@0.1.0
npm ERR! missing: @progress/kendo-react-dialogs@3.14.0, required by orthotom-mds@0.1.0
npm ERR! missing: @progress/kendo-react-dropdowns@3.14.0, required by orthotom-mds@0.1.0
npm ERR! missing: @progress/kendo-react-editor@3.14.0, required by orthotom-mds@0.1.0
npm ERR! missing: @progress/kendo-react-excel-export@3.14.0, required by orthotom-mds@0.1.0
npm ERR! missing: @progress/kendo-react-gauges@3.14.0, required by orthotom-mds@0.1.0
npm ERR! missing: @progress/kendo-react-grid@3.14.0, required by orthotom-mds@0.1.0
npm ERR! missing: @progress/kendo-react-inputs@3.14.0, required by orthotom-mds@0.1.0
npm ERR! missing: @progress/kendo-react-intl@3.14.0, required by orthotom-mds@0.1.0
npm ERR! missing: @progress/kendo-react-layout@3.14.0, required by orthotom-mds@0.1.0
npm ERR! missing: @progress/kendo-react-popup@3.14.0, required by orthotom-mds@0.1.0
npm ERR! missing: @progress/kendo-react-progressbars@3.14.0, required by orthotom-mds@0.1.0
npm ERR! missing: @progress/kendo-react-upload@3.14.0, required by orthotom-mds@0.1.0
npm ERR! missing: @progress/kendo-theme-bootstrap@4.16.1, required by orthotom-mds@0.1.0
npm ERR! peer dep missing: immutable@^3.8.1 || ^4.0.0-rc.1, required by connected-react-router@6.7.0
npm ERR! peer dep missing: seamless-immutable@^7.1.3, required by connected-react-router@6.7.0
npm ERR! missing: @telerik/kendo-draggable@2.2.0, required by @progress/kendo-react-common@3.14.0
npm ERR! missing: @progress/kendo-react-common@3.14.0, required by @progress/kendo-react-data-tools@3.14.0
npm ERR! missing: @progress/kendo-date-math@1.5.1, required by @progress/kendo-react-dateinputs@3.14.0
npm ERR! missing: @progress/kendo-react-buttons@3.14.0, required by @progress/kendo-react-dateinputs@3.14.0
npm ERR! missing: @progress/kendo-react-common@3.14.0, required by @progress/kendo-react-dateinputs@3.14.0
npm ERR! missing: @progress/kendo-react-labels@3.14.0, required by @progress/kendo-react-dateinputs@3.14.0
npm ERR! missing: @progress/kendo-react-popup@3.14.0, required by @progress/kendo-react-dateinputs@3.14.0
npm ERR! missing: @progress/kendo-react-common@3.14.0, required by @progress/kendo-react-buttons@3.14.0
npm ERR! missing: @progress/kendo-react-popup@3.14.0, required by @progress/kendo-react-buttons@3.14.0
npm ERR! missing: @progress/kendo-react-common@3.14.0, required by @progress/kendo-react-labels@3.14.0
npm ERR! missing: @progress/kendo-react-common@3.14.0, required by @progress/kendo-react-dialogs@3.14.0
npm ERR! missing: @progress/kendo-react-common@3.14.0, required by @progress/kendo-react-dropdowns@3.14.0
npm ERR! missing: @progress/kendo-react-labels@3.14.0, required by @progress/kendo-react-dropdowns@3.14.0
npm ERR! missing: @progress/kendo-react-popup@3.14.0, required by @progress/kendo-react-dropdowns@3.14.0
npm ERR! missing: prosemirror-commands@1.1.4, required by @progress/kendo-editor-common@0.3.0
npm ERR! missing: prosemirror-gapcursor@1.1.5, required by @progress/kendo-editor-common@0.3.0
npm ERR! missing: prosemirror-keymap@1.1.4, required by @progress/kendo-editor-common@0.3.0
npm ERR! missing: prosemirror-state@1.3.3, required by @progress/kendo-editor-common@0.3.0
npm ERR! missing: prosemirror-transform@1.2.5, required by @progress/kendo-editor-common@0.3.0
npm ERR! missing: prosemirror-view@1.14.10, required by @progress/kendo-editor-common@0.3.0
npm ERR! missing: prosemirror-state@1.3.3, required by prosemirror-commands@1.1.4
npm ERR! missing: prosemirror-transform@1.2.5, required by prosemirror-commands@1.1.4
npm ERR! missing: prosemirror-state@1.3.3, required by prosemirror-dropcursor@1.3.2
npm ERR! missing: prosemirror-transform@1.2.5, required by prosemirror-dropcursor@1.3.2
npm ERR! missing: prosemirror-view@1.14.10, required by prosemirror-dropcursor@1.3.2
npm ERR! missing: prosemirror-keymap@1.1.4, required by prosemirror-gapcursor@1.1.5
npm ERR! missing: prosemirror-state@1.3.3, required by prosemirror-gapcursor@1.1.5
npm ERR! missing: prosemirror-view@1.14.10, required by prosemirror-gapcursor@1.1.5
npm ERR! missing: prosemirror-state@1.3.3, required by prosemirror-history@1.1.3
npm ERR! missing: prosemirror-transform@1.2.5, required by prosemirror-history@1.1.3
npm ERR! missing: prosemirror-state@1.3.3, required by prosemirror-inputrules@1.1.2
npm ERR! missing: prosemirror-transform@1.2.5, required by prosemirror-inputrules@1.1.2
npm ERR! missing: prosemirror-state@1.3.3, required by prosemirror-keymap@1.1.4
npm ERR! missing: w3c-keyname@2.2.4, required by prosemirror-keymap@1.1.4
npm ERR! missing: prosemirror-transform@1.2.5, required by prosemirror-schema-list@1.1.2
npm ERR! missing: prosemirror-transform@1.2.5, required by prosemirror-state@1.3.3
npm ERR! missing: prosemirror-keymap@1.1.4, required by prosemirror-tables@0.9.5
npm ERR! missing: prosemirror-state@1.3.3, required by prosemirror-tables@0.9.5
npm ERR! missing: prosemirror-transform@1.2.5, required by prosemirror-tables@0.9.5
npm ERR! missing: prosemirror-view@1.14.10, required by prosemirror-tables@0.9.5
npm ERR! missing: prosemirror-state@1.3.3, required by prosemirror-view@1.14.10
npm ERR! missing: prosemirror-transform@1.2.5, required by prosemirror-view@1.14.10
npm ERR! missing: @progress/kendo-file-saver@1.1.0, required by @progress/kendo-react-excel-export@3.14.0
npm ERR! missing: @progress/kendo-ooxml@1.5.0, required by @progress/kendo-react-excel-export@3.14.0
npm ERR! missing: jszip@3.4.0, required by @progress/kendo-ooxml@1.5.0
npm ERR! missing: @progress/kendo-charts@1.14.0, required by @progress/kendo-react-gauges@3.14.0
npm ERR! missing: @progress/kendo-react-common@3.14.0, required by @progress/kendo-react-gauges@3.14.0
npm ERR! missing: @progress/kendo-react-common@3.14.0, required by @progress/kendo-react-grid@3.14.0
npm ERR! missing: @progress/kendo-react-common@3.14.0, required by @progress/kendo-react-inputs@3.14.0
npm ERR! missing: @progress/kendo-react-labels@3.14.0, required by @progress/kendo-react-inputs@3.14.0
npm ERR! missing: @progress/kendo-react-popup@3.14.0, required by @progress/kendo-react-inputs@3.14.0
npm ERR! missing: @telerik/kendo-intl@2.2.0, required by @progress/kendo-react-intl@3.14.0
npm ERR! missing: @progress/kendo-react-animation@3.14.0, required by @progress/kendo-react-layout@3.14.0
npm ERR! missing: @progress/kendo-react-common@3.14.0, required by @progress/kendo-react-layout@3.14.0
npm ERR! missing: @progress/kendo-react-popup@3.14.0, required by @progress/kendo-react-layout@3.14.0
npm ERR! missing: @progress/kendo-react-common@3.14.0, required by @progress/kendo-react-animation@3.14.0
npm ERR! missing: @progress/kendo-react-animation@3.14.0, required by @progress/kendo-react-popup@3.14.0
npm ERR! missing: @progress/kendo-react-common@3.14.0, required by @progress/kendo-react-popup@3.14.0
npm ERR! missing: @progress/kendo-react-common@3.14.0, required by @progress/kendo-react-progressbars@3.14.0
npm ERR! missing: @progress/kendo-react-common@3.14.0, required by @progress/kendo-react-upload@3.14.0
npm ERR! missing: axios@0.18.1, required by @progress/kendo-react-upload@3.14.0
npm ERR! peer dep missing: eslint-plugin-flowtype@3.x, required by eslint-config-react-app@5.2.0
npm ERR! peer dep missing: typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta, required by tsutils@3.17.1
npm ERR! peer dep missing: typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta, required by tsutils@3.17.1
Browser:
- Chrome (desktop) version 81.0.4044.138 (Official Build) (64-bit)
System:
- TypeScript version: n/a
- Node version: 6.13.6
- Platform:  Windows

**Comment by kspeyanski** [comment]
The issue has been fixed in the latest `dev` version of the `@progress/kendo-react-dateinputs` package.

For the full set of changes, please refer to the [KendoReact Changelog](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/) page.
