### ISSUE TITLE
Header of the grid does not follow the horizontal scroll

### ISSUE THREAD

**Issue by pooya1361** [telerik/kendo-react#6]
## I'm submitting a...
* Bug report 

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/2Ea9lePWieN6HRe6nB0h?p=preview

**Comment by VALIKCOOL** [comment]
Confirm, having the same issue

**Comment by Xizario** [comment]
We have published a fix in our development channel, under a `@dev` tag. Please refer to the following [article ](https://www.telerik.com/kendo-react-ui/components/installation/development-builds/)on how to obtain the development builds.

**Comment by Xizario** [comment]
Fixed in official [v0.4.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/),  already works in the example above since it uses `@latest` version.
