### ISSUE TITLE
GridHeaderSelectionCell Each child in an array or iterator should have a unique "key" prop

### ISSUE THREAD

**Issue by yashpokar** [telerik/kendo-react#60]
![screenshot from 2018-08-14 13-46-16](https://user-images.githubusercontent.com/7402810/44080058-7e233676-9fc8-11e8-83f6-4ec948860c7c.png)

**Comment by Xizario** [comment]
Could you confirm that you are using `v1.2.0` and not some older version?

**Comment by yashpokar** [comment]
"@progress/kendo-react-grid": "^1.2.0",

Yes, I'm using 1.2.0

**Comment by Xizario** [comment]
Thank you

**Comment by Xizario** [comment]
Fixed in `1.3.0-dev.201808171015`
