### ISSUE TITLE
Edit dialog should be rendered outside of the scheduler

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-react#601]
## I'm submitting a...
* Bug report

## Current behavior
Upon opening the edit event dialog of the scheduler, the toolbar is rendered on the top of the overlay and event dialog.

## Expected behavior
The toolbar should stay behind the overlay and edit dialog.

## Minimal reproduction of the problem with instructions
1. Open this demo: https://telerik.github.io/react-coffee-warehouse/#/.
2. Open edit event dialog.

## Suggested solution
If we render the whole edit dialog wrapper that contains the overlay and the dialog outside of the scheduler, this will resolve the issue.

**Comment by kmbro** [comment]
Any update on this? Thanks

**Comment by simonssspirit** [comment]
reported also in 1477299

**Comment by kspeyanski** [comment]
The issue has been resolved in version [`3.16.0`](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#1c33d199-89a5-5f3b-a5f8-e2bbde17601d) of the `@progress/kendo-react-scheduler` package
