### ISSUE TITLE
How can I add "mouse click event" on <GridColumn> ?

### ISSUE THREAD

**Issue by bluesky1225** [telerik/kendo-react#603]
<GridColumn field="card_code" title="Card Code" onClick={this.onGridClick} />

I added onClick... but it doesn't work.

Maybe it has other attribute.

How can I add mouse click event on GridColumn in Grid?

**Comment by simonssspirit** [comment]
This will require a custom cell for the column where we will attach the onClick event over the td:
https://www.telerik.com/kendo-react-ui/components/grid/api/GridColumnProps/#toc-cell
Also, is this will be over one column or all columns?

**Comment by simonssspirit** [comment]
the question seems resolved.
