### ISSUE TITLE
Typing fast (two buttons at the same time) changes the DatePicker focus section.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#604]
Typing fast (two buttons at the same time) changes the DatePicker focus section.

https://stackblitz.com/edit/react-1ave1g?file=app/main.jsx
If we go to the date section and type very fast (click two buttons at the same time) the focus will jump to the milliseconds section.

**Comment by Xizario** [comment]
Possibly related to https://github.com/telerik/kendo-react/issues/581

**Comment by gillerg8** [comment]
Any update on this one?

**Comment by kspeyanski** [comment]
Closing this one in favour of: https://github.com/telerik/kendo-react/issues/705

**Comment by kspeyanski** [comment]
Hello, 

We've fixed this specific issue in version `4.2.0` of the `@progress/kendo-react-dateinputs` package. For the full changelog of version `4.2.0` please refer to the [`KendoReact Changelog`](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#f91bd6b1-d1ea-53d1-98cc-48c0148cf6b9) page.
