### ISSUE TITLE
Tabstriptab is overlapping and content is not inside the tab in IE10

### ISSUE THREAD

**Issue by shololauy** [telerik/kendo-react#613]
tabstriptab content is not inside the tab and overlaps other style in IE 10
plese refer to attached document
![issue](https://user-images.githubusercontent.com/49559093/83420198-47319180-a3f4-11ea-9475-f8e50e4ac767.JPG)

**Comment by simonssspirit** [comment]
@shololauy KendoReact supports only IE 11 and higher and only with specific polyfills required by React as well:

https://www.telerik.com/kendo-react-ui/components/requirements/#toc-browser-support
