### ISSUE TITLE
TabStripTab does not update child view after state change

### ISSUE THREAD

**Issue by haydencrain** [telerik/kendo-react#62]
## I'm submitting a...
* Bug report 

## Current behavior

When a parent's state change occurs, any child components within a TabStripTab do not update/re-render. The children are only updated once a user switches between tabs.

## Expected behavior

Child components within a TabStripTab component should update after state changes

## Minimal reproduction of the problem with instructions

example: [https://stackblitz.com/edit/react-sgaeuy-njkegh?file=app/main.js](https://stackblitz.com/edit/react-sgaeuy-njkegh?file=app/main.js)
1. Create a TabStrip component with 2 TabStripTabs
2. Outside of the TabStrip component, create a textbox, and set it up so that it's value is set to `this.state.value` 
3. In the first tab, add a child element that displays `this.state.value`.
4. run the code
5. inputting values into the textbox does not update the first tab's display.
6. After switching to the second tab, and back to the first tab, `this.state.value` is now correctly displayed in the first tab.

## What is the motivation or use case for changing the behavior?

Creating a multi-tabbed form, with different sets of fields on each tab. 
## Environment

Package versions:

```
├── @progress/kendo-react-layout@1.2.0
```

Browser:

- Chrome (desktop) version 68.0.3440.106 (Official Build) (64-bit)

System:
- TypeScript version: 2.9.2
- Node version: v8.10.0
- npm version: 6.2.0
- Platform:  Mac

**Comment by kspeyanski** [comment]
Hello,
I can confirm that this is indeed a bug. I'll keep you posted once the fix has been published.

**Comment by kspeyanski** [comment]
Hello, the issue was fixed in version `1.3.0-dev.201808171015` of `@progress/kendo-react-layout`.
