### ISSUE TITLE
DatePicker missing months on navigation

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#620]
When we have Date Picker control, with a max, min and show props, some months are hidden from the side bar during navigation.

[Example ](https://stackblitz.com/edit/react-t9xua5-qbng1a?file=app/main.jsx)representing the behavior.

Recreation steps:

- Make a note of all the months in the sidebar ('Apr', 'May', 'June', 'July', 'Aug')
- Click on the 'June 2020' button to navigate to month selection
- From here, click on the 'Today' button
- In the side bar, the only remaining ones are ('June', 'July', 'Aug')

The issue is described under ticket: 1470682.

**Comment by kdikov82** [comment]
Seems like it is not reproducible with the latest version:
[https://stackblitz.com/edit/react-m3jasb?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-m3jasb?file=app%2Fmain.jsx)
