### ISSUE TITLE
Grid: Locked columns causes performance degradation in Chrome

### ISSUE THREAD

**Issue by totaldis** [telerik/kendo-react#628]
## I'm submitting a...
* Documentation issue or request (best match I suppose)

This is simply to inform the **kendo-react** team of this existing bug in Chromium so it can be tracked internally if future _"issues"_ are submitted for scrolling performance. Or perhaps a different implementation could be used for locked columns.

## Current behavior
I've been fighting scrolling performance issues attempting to render a grid with 2500+ rows x 20 columns. I find virtualization is a bit clunky or I simply can't figure out the optimal combination of row height and page size in a dynamic height grid. 

I did some experimenting with our current dhtmlxgrid implementation and compared it to Kendo Grid in Chrome and the FPS drop was significantly worse in Kendo's component vs. our current implementation. That didn't make sense to me because nothing was re-rendering and the browser painting should be equivalent. 

I eventually discovered it's the `locked` prop on the `<GridColumn />` which was causing the perf issue. I tracked it down to to the `position: sticky` style and found a live Chromium bug report and potential remediation:

https://bugs.chromium.org/p/chromium/issues/detail?id=752756
https://bugs.chromium.org/p/chromium/issues/detail?id=1058987

I've confirmed the issue is present in both Chrome and new Edge (chrome based) but not in Firefox. I didn't test IE.

## Expected behavior
Little to no loss in FPS when using locked columns. 

## Minimal reproduction of the problem with instructions
_fps measured in chrome and firefox_

Using a modified stackblitz:
https://stackblitz.com/edit/react-vxhdrz?file=app%2Fmain.jsx

* Scroll through the 2k rows and measure FPS
* Lock the first column `<Column locked field="id" title="ID" width="70px" />`
* Scroll through the 2k rows and measure FPS

### Not Locked Chrome
![image](https://user-images.githubusercontent.com/3299536/84291628-5d85ce80-ab13-11ea-90a3-1b40bc88e805.png)

### Locked Chrome
![image](https://user-images.githubusercontent.com/3299536/84291567-45ae4a80-ab13-11ea-9644-5539f6d5171e.png)

### Locked Firefox
![image](https://user-images.githubusercontent.com/3299536/84292998-2dd7c600-ab15-11ea-9389-c1338f5dd033.png)

## Environment
Browser:
- Chrome (desktop) Version 83.0.4103.97 (Official Build) (64-bit)
- Firefox (desktop) [aurora] 77.0b9 (64-bit)
- Edge (desktop) Version 83.0.478.45 (Official build) (64-bit)

**Comment by vladimirivanoviliev** [comment]
No longer reproduced in latest Chrome with latest version.

<img width="509" alt="image" src="https://user-images.githubusercontent.com/2195951/153163803-8163fd07-04bf-4967-b47e-510dc8a4f6ee.png">
