### ISSUE TITLE
Form component={Checkbox} console error

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#630]
Console error is received when we pass `Checkbox` into the `Field` component:

> Warning: Received `true` for a non-boolean attribute `valid`.
> If you want to write it to the DOM, pass a string instead: valid="true" or valid={value.toString()}.
> in input (created by KendoCheckbox)
> in span (created by KendoCheckbox)
> in KendoCheckbox
> in div (created by KendoReactFieldWrapper)
> in KendoReactFieldWrapper
> in Unknown (created by KendoReactField)
> in KendoReactField (created by KendoReactForm)
> in form (created by KendoReactFormElement)
> in KendoReactFormElement (created by KendoReactForm)
> in KendoReactForm (created by App)
> in App

The issue could be recreated under [example](https://www.telerik.com/kendo-react-ui/components/form/guidelines-with-examples/#toc-checkboxes-&-radiobuttons). 
The issue is described under ticket: 1471328.

**Comment by silviyaboteva** [comment]
Fixed in `v3.15.0-dev.202006220814`.
