### ISSUE TITLE
Scheduler Timeline view, if there are many elements at the same time they will exceed the row height. 

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#634]
Scheduler Timeline view, if there are many elements at the same time they will exceed the row height. 

![image](https://user-images.githubusercontent.com/11087921/84662980-3705d000-af25-11ea-830a-d9e5044ba99e.png)

**Comment by kspeyanski** [comment]
The issue have been successfully fixed in version [`3.18.0@dev`](https://www.npmjs.com/package/@progress/kendo-react-scheduler/v/3.18.0-dev.202010090731) of the `@progress/kendo-react-scheduler` package.
