### ISSUE TITLE
Treelist, virtual scrolling, filter to zero items results in "Cannot read property 'height' of undefined"

### ISSUE THREAD

**Issue by joshmarnold** [telerik/kendo-react#636]
## I'm submitting a...
* Bug report 

## Current behavior
On a Treelist using Virtual Scrolling, when applying a filter that filters out all items, I receive the error "Cannot read property 'height' of undefined".

## Expected behavior
I would expect no error and the usual No Items message. 

## Minimal reproduction of the problem with instructions
typing "test" into the filter bar in the stackblitz below will reproduce the issue. 
https://stackblitz.com/edit/treelist-vs-bug?file=app/main.jsx

**Comment by nstoychev** [comment]
@joshmarnold - We have published a fix in our dev channel - https://stackblitz.com/edit/treelist-vs-bug-ez9s1u?file=app/main.jsx.

Here is how to obtain our development builds - https://www.telerik.com/kendo-react-ui/components/installation/development-builds/.

**Comment by joshmarnold** [comment]
That works. Thanks!
