### ISSUE TITLE
Validation borders not correct for Material theme in Firefox

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#638]
* Bug report 

## Current behavior
All the Kendo controls do not render their invalid borders in the material style. For some controls it only happens when you are using floating labels and you clear the control.
For others, it is all the time.

## Expected behavior
Render the borders correctly in material theme in firefox

## Minimal reproduction of the problem with instructions
See the attached repro (in Firefox)
https://stackblitz.com/edit/react-6oqw7v?file=app%2Fmain.jsx

For the Input, clear it then click anywhere on the screen. Note it only happens when you have a label.
For the Multiselect you do not need to do anything special

![image](https://user-images.githubusercontent.com/5611876/84936385-6dd11700-b0da-11ea-8526-850ed4447b6c.png)

This also affects the other kendo controls

## What is the motivation or use case for changing the behavior?
Looks bad in Firefox

## Environment

Package versions:
3.14.0

Browser:

- Firefox version 77.0.1

System:
- Platform:  Windows

**Comment by joneff** [comment]
Just a quick update, we targeted the issue in telerik/kendo-themes#1642.

As for why it's happening, there are "internal" styles in firefox that add `box-shadow`:

```css
:not(output):-moz-ui-invalid {
    box-shadow: 0 0 1.5px 1px red;
}
```

**Comment by silviyaboteva** [comment]
Fixed in the latest dev version of the themes - `3.17.0-dev.c7f7b320`.
Demo here: https://stackblitz.com/edit/react-6oqw7v-dby9kw?file=index.html
