### ISSUE TITLE
Grid locked group headers, only the outermost group headers lock

### ISSUE THREAD

**Issue by TrevorJamesH** [telerik/kendo-react#640]
In 13.12 is seems you fixed locking group headers. 

But only the outermost group headers lock, the others still move. It's especially bad that they will slide over the top of the other locked group header, incorrectly above a child column that is not their child.

https://stackblitz.com/edit/react-mu6rlr-de3fuv

**Comment by kdikov82** [comment]
Works as expected with the latest version (5.10.0):
[https://stackblitz.com/edit/react-gqehlq?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-gqehlq?file=app%2Fmain.jsx)
