### ISSUE TITLE
Add the collapsible option for the ExcelExport.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#641]
Add the collapsible option for the ExcelExport.

This will add expand/collapse functionality to the export Excel documents when exporting a groupable Grid.

![image](https://user-images.githubusercontent.com/11087921/85387052-076e4d80-b54d-11ea-97e2-88fbcf8effad.png)

**Comment by simonssspirit** [comment]
This is ready in version: 3.16.0

https://www.telerik.com/kendo-react-ui-develop/components/excelexport/api/ExcelExportProps/#toc-collapsible

**Comment by wiznotwiz** [comment]
> This is ready in version: 3.16.0
> 
> https://www.telerik.com/kendo-react-ui-develop/components/excelexport/api/ExcelExportProps/#toc-collapsible

Is there any example for this prop? It doesn't seem to work with data={grouped_data}, group={dataState.group}, collapsible={true}, and a ref, like the below simplified example:
```
                    <ExcelExport
                        data={managerData}
                        collapsible={true}
                        ref={(exporter) => (_export = exporter)}
                        group={dataState.group}
                    >
                      <Grid data={managerData}>
                            <GridColumn field ="test" />
                      </Grid>
                    </ExcelExport>
```

Did I miss a setting somewhere? Thank you!
