### ISSUE TITLE
Increase the number of items displayed in the Scheduler in Month view

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#642]
Month view in the Scheduler component only has 2 items rendered. The request includes increase of the rendering of the items.

The feature request is described under ticket: 1472907.

**Comment by kspeyanski** [comment]
Requested again in: 1478192

**Comment by kspeyanski** [comment]
This can now be achieved through the [`itemsPerSlot`](https://www.telerik.com/kendo-react-ui/components/scheduler/api/MonthViewProps/#toc-itemsperslot) property.
