### ISSUE TITLE
Customizable DateTimePicker component

### ISSUE THREAD

**Issue by clinton-slice** [telerik/kendo-react#644]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
Unable to customize DateTimePicker component

## Expected behavior
Should be able to customize the DateInput in DateTimePicker component just as we can for TimePicker and DatePicker components
## Minimal reproduction of the problem with instructions
Add the `dateInput` on the DateTimePicker component, apparently it does not exist 
https://stackblitz.com/edit/react-hrnusv?file=app/main.jsx

## What is the motivation or use case for changing the behavior?
This would give users the flexibility to customize the input field in order to suit the design of their application

## Environment

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by simonssspirit** [comment]
We already have this logged: https://github.com/telerik/kendo-react/issues/559

I will close this as a duplicate, so the community can follow a single item.
