### ISSUE TITLE
unable to lock (freeze or stick) columns with custom editors in Kendo React Grid

### ISSUE THREAD

**Issue by Nesyne** [telerik/kendo-react#645]
When i set the locked property to true on a column with custom cell editor; only the header part of the column is locked. The rows will still scroll as normal.

**Comment by simonssspirit** [comment]
@Nesyne This is because we apply specific styles and class names to the cells of the locked columns. When the cell is custom we pass the necessary class names and styles as props, and the developer has to apply then to the custom TD element.

**Comment by Nesyne** [comment]
@simonssspirit Do you have an example of how you do this please? Take for instance, the example in telerik website where you are doing inline editing with buttons in a cell. Try locking the column with buttons.

**Comment by simonssspirit** [comment]
@Nesyne I updated our inline editing demo to make the command column locked:
https://stackblitz.com/edit/react-kcjfp4?file=app%2FmyCommandCell.jsx

**Comment by simonssspirit** [comment]
The question seems resolved.

**Comment by Steven-Chorkawy** [comment]
Thanks for the fix @simonssspirit! 

Could the demo be updated to show how this is done?
https://www.telerik.com/kendo-react-ui/components/grid/columns/locked/
