### ISSUE TITLE
Allow placeholder props to the DatePicker, TimePicker and DateTimePicker Input component

### ISSUE THREAD

**Issue by clinton-slice** [telerik/kendo-react#646]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
Input placeholder cannot be added on the DatePicker, TimePicker and DateTimePicker components 

## Expected behavior
Developers should be given the ability to add a placeholder to the input of the DatePicker, TimePicker and DateTimePicker components. This can be done by just passing a prop to the input component which by default has a placeholder prop by default. End product should look like the below screenshoot.
![image](https://user-images.githubusercontent.com/57362152/85613227-a9626880-b627-11ea-9905-f40dbdd2a836.png)

## What is the motivation or use case for changing the behavior?
This would give developers the opportunity to add placeholders to the application.

## Environment

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by miral-zymr** [comment]
@clinton-slice The following is actually my requirement. Is there any way to provide a custom placeholder for the DatePicker? I'm using the @progress/kendo-react-grid v3.9.0.

**Comment by miralkumbhani** [comment]
@clinton-slice The following is actually my requirement. Is there any way to provide a custom placeholder for the DatePicker? I'm using the @progress/kendo-react-grid v3.9.0 and react v16.9.0.

**Comment by clinton-slice** [comment]
> @clinton-slice The following is actually my requirement. Is there any way to provide a custom placeholder for the DatePicker? I'm using the @progress/kendo-react-grid v3.9.0 and react v16.9.0.

@miralkumbhani Yes there is. you have to customize the input by creating a customInput component which would have a label prop and then pass that customInput component to the DatePicker component using the dateInput prop. So you would have something like this in DatePicker component `dateInput={CustomDateInput}`

**Comment by kspeyanski** [comment]
Closing this one in favour of: https://github.com/telerik/kendo-react/issues/705
