### ISSUE TITLE
Console error in KendoReact Scheduler when selecting vertical orientation while grouping

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#649]
The error appears on KendoReact Scheduler with Grouping on orientation in vertical mode.
The issue can be reproduced under the [Demo](https://www.telerik.com/kendo-react-ui/components/scheduler/views/week/#toc-grouping-by-resource) when we switch to vertical mode.

The issue is described under ticket: 1473781.

**Comment by kspeyanski** [comment]
The error is no longer present, so i'm closing this issue for now.
