### ISSUE TITLE
Grid column resizing not working in React.StrictMode.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#651]
Grid column resizing not working in React.StrictMode.

This can be seen in our demo if we add it in React.StrictMode:

https://stackblitz.com/edit/react-yn3ixj?file=app/main.jsx

**Comment by simonssspirit** [comment]
reported again in 1478786

**Comment by simonssspirit** [comment]
reported again in 1483062

**Comment by simonssspirit** [comment]
reported again in 1483792

**Comment by simonssspirit** [comment]
reported again in 1484638

**Comment by simonssspirit** [comment]
reported again in 1485849

**Comment by simonssspirit** [comment]
reported again in 1494945

**Comment by simonssspirit** [comment]
reported again in the documentation feedback.

**Comment by simonssspirit** [comment]
reported again in 1501877

**Comment by bvaughn** [comment]
Drive by comment here, but that suggests to me that `Grid` has a bug and `StrictMode` is making the bug's behavior occur in a reproducible way. (That's one of the main purposes of strict mode. You can read about what it does [here](https://reactjs.org/docs/strict-mode.html). Specifically [this section](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects) is where I think you'd want to focus.)

**Comment by Xizario** [comment]
Fixed in 4.3.0

**Comment by simonssspirit** [comment]
The issue is currently fixed only for the Grid, and we will re-open it as it is affecting also the TreeList and probably the Gantt.

cc @nstoychev, @Xizario, @vladimirivanoviliev

**Comment by nstoychev** [comment]
It is fixed for the TreeList.

**Comment by vladimirivanoviliev** [comment]
In Gantt it was never been an issue.
