### ISSUE TITLE
Controlled Mode on Checkbox doesn't work when user clicks on checkbox itself

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#652]
Steps to reproduce:
1. Go to the [Demo](https://www.telerik.com/kendo-react-ui/components/inputs/checkbox/controlled/#toc-controlling-the-value)
2. On the `Controlling the value` demo, toggle the checkbox from toggle button, then toggle from actual checkbox itself. After that the toggle button is now working.

The issue is described under ticket: 1473954.

**Comment by silviyaboteva** [comment]
Reworked demos: https://www.telerik.com/kendo-react-ui-develop/components/inputs/checkbox/controlled/#toc-controlling-the-value
