### ISSUE TITLE
Only Show "contains" operator in Treelist filter dropdown

### ISSUE THREAD

**Issue by joshmarnold** [telerik/kendo-react#654]
## I'm submitting a...
 * Support requests to https://www.telerik.com/account/support-tickets.

* Documentation issue or request

## Current behavior
Having trouble figuring out how to only show the "contains" operator in the dropdown of the Treelist filter. Seems trivial for the grid but can't seem to get it to work for the Treelist.

https://stackblitz.com/edit/contains-only-filter?file=app/main.jsx

**Comment by simonssspirit** [comment]
@joshmarnold currently, this feature is not available for the TreeList.

I will make this an enhancement request and we will plan it accordingly based on the popularity.

**Comment by joshmarnold** [comment]
Got it, thanks!
