### ISSUE TITLE
KendoReact Grid `onPageChanged` triggered when scrolling in dropdown custom cell

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#656]
Grid with virtual scrolling, fires `onPageChange` event, when we scroll into editor in Grid, like `dropdown`, etc.

The issue has been described under ticket: 1474623.

**Comment by InaGlushkova** [comment]
The same unwanted behavior exists for the `onScroll` event.

The issue has been described under ticket: 1474623.

**Comment by nstoychev** [comment]
Fixed in dev channel.
