### ISSUE TITLE
The name props of the ComboBox component is not set to the input.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#658]
The name props of the ComboBox component is not set to the input.

https://www.telerik.com/kendo-react-ui/components/dropdowns/api/ComboBoxProps/#toc-name

**Comment by InaGlushkova** [comment]
The `name` prop should not be set to the input.

If the ComboBox is used in a form and the form is submitted, the submitted data will not be correct. The submitted value will be the input value and not the value of the ComboBox.
