### ISSUE TITLE
Add an option to append the Editor tools popups and dialog to the Editor DOM element.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#661]
Add an option to append the Editor tools popups and dialog to the Editor DOM element.

Currently, the popups and dialogs of the tools are rendered inside the document.body. This can create an issue when rendering the Editor inside a Modal that traps the focus as clicking on any of these tools will either be prevented or the Modal will automatically close.

**Comment by Xizario** [comment]
available in 4.2.0 dev, see the related issue

**Comment by simonssspirit** [comment]
The issue is for the Popup and for the Dialog, but only the Popup part is ready.

I will re-open the issue to address the Dialog part as well.

**Comment by nstoychev** [comment]
Depends on - https://github.com/telerik/kendo-react/issues/1126.

**Comment by nstoychev** [comment]
Here is how to configure the Editor's dialogs and popups rendering container - https://stackblitz.com/edit/react-ubvf9k?file=app/main.jsx.

The context props are published in [v4.14.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#a04c4700-cebf-570e-8b74-a1601f6ddc15).

**Comment by nstoychev** [comment]
@jemunk - See this example: https://stackblitz.com/edit/react-6kdvyk?file=app%2Fmain.jsx

I'm not sure what has happened to the above example.
