### ISSUE TITLE
Scheduler: item not visible when `start` and `end` are not intersecting with the view range

### ISSUE THREAD

**Issue by kspeyanski** [telerik/kendo-react#666]
With the current implementation of the `DayView` of the Scheduler, items which `start` and `end` are not being shown in the view, even if they are part of the displayed range.

Currently, items which are intersecting with the view range, but both their `start` and `end` values are not intersecting are not visualised properly:
![image](https://user-images.githubusercontent.com/30626787/87393668-2fcef200-c5b7-11ea-9462-2b283b92364e.png)

While the correct behaviour is to shown an item if it is intersecting with the view range at any given point:
![image](https://user-images.githubusercontent.com/30626787/87393767-52f9a180-c5b7-11ea-8781-98e9ebc198da.png)

While a quick fix is possible, additional testing would be required.

**Comment by kspeyanski** [comment]
Fixed in version `3.16.0@dev` of the `@progress/kendo-react-scheduler` package:
https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#toc-3160-dev202008130900

**Comment by yyosifov** [comment]
@kspeyanski great news! Thanks, we'll give it a try right away.
