### ISSUE TITLE
Scheduler side cell min-width with Bootstap

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#667]
When we have:
```
:root {
     font-size: 14px;
}
```
Every time we use item "drag and drop" the whole scheduler move to the right pixel by pixel on every "drop". 
[Example ](https://stackblitz.com/edit/react-tp5ymh)demonstrating the behavior.

The issue exists when we are using Bootstap and have specific `font-size`. For example, it doesn't occur when we have `font-size: 12px`. Connected with the change of the `min-width` of the `k-scheduler-cell k-side-cell`.

The issue is related to ticket: 1475980.

**Comment by kspeyanski** [comment]
We were able to find the root problem that is causing the shift in width on every rerender.
We will be publishing a hotfix as soon as possible.

**Comment by pierrealixt** [comment]
Any update on this bug?

**Comment by kspeyanski** [comment]
Hello @pierrealixt ,

Please excuse me for the delayed response. 
The issue has been resolved with version [3.16.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#1c33d199-89a5-5f3b-a5f8-e2bbde17601d) of the `@progress/kendo-react-scheduler` package.

I'm closing this issue for now, but please let me know if you experience any problems.
