### ISSUE TITLE
Trying to render ChartTooltip on onLegendItemHover

### ISSUE THREAD

**Issue by selim-ammari** [telerik/kendo-react#671]
## I'm submitting a...
  * Support requests to https://www.telerik.com/account/support-tickets.

* Documentation issue or request

## Current behavior
I'm trying to render the ChartTooltip when i'm hovering legend item but can't because i've got this error 
Uncaught TypeError: Cannot read property 'showTooltip' of undefined

##Code

renderTooltip = (context: any) => {
        const { category, value, percentage } = context.point || context;
        let tempPer = GetKPITemplate(eKPIType.Percent);
        let formatValue = (value / 1000).toLocaleString(currentLocal, { minimumFractionDigits: 0, maximumFractionDigits: 2 })
        return (<div>{category} {formatValue + 'k'} {tempPer(Number(percentage) * 100)}</div>);
    };

render() {
        let { series } = this.state;
        if (series?.length === 0) {
            return <div className='no-data-graph'>
                {Trad("no_data_for_filters")}
            </div>
        }

        return (<Chart
            onLegendItemHover={(e :any) => {
                return e.sender.showTooltip((point :any) => point.index === e.pointIndex);
            }}>
            <ChartTooltip render={this.renderTooltip}/>
            <ChartLegend position="bottom"/>
            <ChartSeries>
                <ChartSeriesItem
                    type={this.props.type}
                    data={series || []}
                    field="KPI"
                    categoryField="Label"
                // labels={{ visible: false, content: labelContent }} 
                />
            </ChartSeries>
        </Chart>);
    }

**Comment by simonssspirit** [comment]
This can be tracked here: https://github.com/telerik/kendo-react/issues/415
