### ISSUE TITLE
KendoReact Grid Column menu filter on nested columns

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#674]
The issue exist when we have nested columns and we are trying to implement column menu filter. The filter should be apply to the outside menu column, but it isn't appearing. The filter could be applied in the inside column.

The code example could be find [here](https://stackblitz.com/edit/react-cuhumz-gxb7px).

The issue is described under ticket: 1476247.

**Comment by nstoychev** [comment]
Fixed in dev channel - https://stackblitz.com/edit/react-cuhumz-qtgisg.

**Comment by Xizario** [comment]
Available in 3.16.0
