### ISSUE TITLE
When unary filter operator used as default one is not allowing filtering

### ISSUE THREAD

**Issue by vladimirivanoviliev** [telerik/kendo-react#675]
There are few issues involving unary operators as default ones:
- Currently column menu filter does not apply correct value ('null') for unary operators when used as default ones. We should apply 'null' value if operator is unary in the constructor of GridColumnMenuFilter:
  - [GridColumnMenuFilter](https://github.com/telerik/kendo-react-private/blob/develop/packages/grid/src/columnMenu/GridColumnMenuFilter.tsx#L165) 
  - [IsUnaryFilter](https://github.com/telerik/kendo-react-private/blob/develop/packages/grid/src/filterCommon.ts#L59)
  - [cellOperatorChange](https://github.com/telerik/kendo-react-private/blob/develop/packages/grid/src/filterCommon.ts#L178)
- If unary operator is used as default one it's hard for the end user to tell if filter is applied, we need to think of solution for this. For example provide empty option on the DDL?
- Possibly hiding the text input when unary operator is used.

**Comment by simonssspirit** [comment]
The fix is already available in the dev version: https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#toc-3160-dev202007281055c

**Comment by simonssspirit** [comment]
we will close the issue for now as it is connected to how the ColumnMenu is working with default unary operators.

We can open a separate issue for the UX perspective, as it is a different case.
