### ISSUE TITLE
TileLayout component

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-react#676]
In our Kendo UI for jQuery suite, we introduced a TileLayout component, which has a layout Grid system and on top of that provides resizing and moving the containers: https://demos.telerik.com/kendo-ui/tilelayout/index.

It will be great to have it in our KendoReact suite as well.

**Comment by kmbro** [comment]
Is this in the works for KendoReact too?

**Comment by silviyaboteva** [comment]
Hi @kmbro,
Not yet. We had a feature request from a client and I opened an item in order to be planned.
So, stay tuned!

**Comment by kmbro** [comment]
Could you post the ticketing here so I can +1 it?
Thanks

**Comment by silviyaboteva** [comment]
You can just add a thumbs up reaction on this item :)

**Comment by Xizario** [comment]
https://www.telerik.com/kendo-react-ui/components/layout/tilelayout/
