### ISSUE TITLE
RFC(scheduler): default item positioning behavior

### ISSUE THREAD

**Issue by kspeyanski** [telerik/kendo-react#680]
Currently the default behavior of the position is to `snap` the items to the corresponding `slots` it intersects with.

We also have a demo showcasing how to apply `proportional` positioning by providing a custom `viewItem` to the view/scheduler:
https://www.telerik.com/kendo-react-ui/components/scheduler/customization/items/view-item/

The question here is: which behavior should be the `default` one.

Please leave your comment bellow this issue so we take them into consideration.

cc, @vladimirivanoviliev , @telerik/kendo-react-team

**Comment by vladimirivanoviliev** [comment]
To my optinion we should make `exact time rendering` by default - every other Scheduler that I can think of is using this apporach and I totally agree with this descision: Outlook, Google Calendar, KendoUI jQuery Scheduler, Kendo Angular Scheduler.

**Comment by Mathdrquinn** [comment]
> To my optinion we should make `exact time rendering` by default

I too was surprised that this was not the default and needed additional code to solve.  My team and I would value this as a native feature.  The current work around causes a flickered render where the data item is initially snapped to the whole slot, then pops into proportion.

**Comment by iconag-bbasmer** [comment]
I would definitely second the opinion that this should for sure be the default behavior. As the preople on this topic already mentioned, all the other apps including Outlook or Google Calendar, but also other Frontend UI libraries simliar to Kendo UI offer this behavior by default. Please make it happen!

**Comment by kspeyanski** [comment]
To better facilitate this request and find balance between out-of-the-box functionality and user customisability, we've shipped a new component `SchedulerProportionalViewItem` as part of the [`v5.5.0`](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#f41e9a37-40fc-55bf-b714-f3c8c7455a4e) release of the `@progress/kendo-react-scheduler` package.

Please check the updated [`View Item Customization` article](https://www.telerik.com/kendo-react-ui/components/scheduler/customization/items/view-item/#toc-extending-the-positioning) on instructions on how to achieve the desired behavior.

As a side note, I would like to address the fact that changing the `default` behavior of the component should be considered a `BREAKING CHANGE` and we want to avoid it at this moment. However, we're open to re-evaluating this once we start preparing for the` v6` release of the package.
