### ISSUE TITLE
e.nativeEvent is undefined inside the onPageChange event when scrolling a virtualized Grid.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#689]
e.nativeEvent is undefined inside the onPageChange event when scrolling a virtualized Grid.

This is since version 3.11.0, before that the event was received as expected:

https://stackblitz.com/edit/react-1jcvam?file=app/main.jsx

**Comment by simonterrasson** [comment]
Hi, any idea when that bug might be handled ?
Thanks

**Comment by nstoychev** [comment]
@simonterrasson - The fix is in a PR and will be published in the dev channel in a few days.

**Comment by nstoychev** [comment]
Fixed in dev channel - https://stackblitz.com/edit/react-1jcvam-8pwxue?file=app/main.jsx.

**Comment by Xizario** [comment]
Available in 3.16.0
