### ISSUE TITLE
Docs Typo: Rendering Loading Indicator (Gris vs Grid)

### ISSUE THREAD

**Issue by jbristowe** [telerik/kendo-react#69]
## I'm submitting a...

* Documentation issue or request

## Current behavior

The word, Grid is mispelled on the page, [Rendering Loading Indicator](https://www.telerik.com/kendo-react-ui/components/grid/advanced-examples/loading-indicator/):

> In such cases, a loading indicator is suitable to indicate that the **Gris** is properly functioning and that its data will soon be displayed.

## Expected behavior

The word, Gris would be spelled Grid:

> In such cases, a loading indicator is suitable to indicate that the **Grid** is properly functioning and that its data will soon be displayed.

## Minimal reproduction of the problem with instructions

Not applicable

## What is the motivation or use case for changing the behavior?

Fix spelling for documentation

## Environment

Package versions: N/A
Browser: N/A
System:  N/A

**Comment by Xizario** [comment]
Thank you
