### ISSUE TITLE
AgendaView renders delete button even if the Scheduler is not editable.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#690]
AgendaView renders delete button even if the Scheduler is not editable.

This can be seen in the demo: https://www.telerik.com/kendo-react-ui/components/scheduler/views/agenda/ (hover an item)

**Comment by kspeyanski** [comment]
The issue has been successfully resolved in version [`3.18.0`](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#fe33e841-ad87-5419-80ac-79552cc4dc69) of the `@progress/kendo-react-scheduler` package.
