### ISSUE TITLE
Checkbox enter press prevents form submit.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#692]
Checkbox enter press prevents the form submit.

The Checkbox will change its value on Enter press, but this will prevent form submit which is the default on Enter press.

This can cause issues inside the Form component is the Checkbox if the last used input and inside the Grid CheckboxFilter which is also using a form to filter the data on Enter.

**Comment by silviyaboteva** [comment]
Fixed in `v3.16.0-dev.202008120811`.
Here is the example: https://stackblitz.com/edit/react-iofmsz?file=app/main.jsx
