### ISSUE TITLE
GridColumnMenuCheckboxFilter fails with nested properties

### ISSUE THREAD

**Issue by wespatrick** [telerik/kendo-react#693]
## I'm submitting a...

* Bug report 

## Current behavior

When using the GridColumnMenuCheckboxFilter with a column whose field is a nested property, only one checkbox is rendered and its text is "undefined".  For instance, if the column field is "ProductName", it works.  But if the column field is "Category.CategoryName", it fails.
It looks like GridCell uses getNestedValue() from utils to get the value to display, but GridColumnMenuCheckboxFilter tries to use field directly as a property name when building the list of unique values.
## Expected behavior

The filter should build the list of unique values from the grid data using field as a path to the nested property.
## Minimal reproduction of the problem with instructions

Create a grid with data that has nested objects.  Add a column with a column menu that uses GridColumnMenuCheckboxFilter.  Set the column field to a property of the nested objects.
The demo starts with the Column Menu Filter example.  I duplicated the ProductName column and changed the field value to "Category.CategoryName".
https://stackblitz.com/edit/react-2etlqf?file=app/main.jsx
## Environment

Package versions:

```
@progress/kendo-react-grid@3.15.0
```

Browser:

- Chrome (desktop) version 84.0.4147.105 (Official Build) (32-bit)

System:
- TypeScript version: N/A
- Node version: v14.7  
- Platform: Windows

**Comment by simonssspirit** [comment]
This is already fixed in the dev channel 3.17.0-dev.202008281416

https://stackblitz.com/edit/react-2etlqf-k95xqk?file=app/main.jsx
