### ISSUE TITLE
Custom Grid paging buttons

### ISSUE THREAD

**Issue by kiranrajufixstream** [telerik/kendo-react#694]
How to add the React component(eg., <ReloadIcon />) Icon as a kendo pagination refresh icon?

**Comment by simonssspirit** [comment]
There is a new feature if the dev version that allows rendering a completely custom pager:

https://www.telerik.com/kendo-react-ui-develop/components/grid/paging/#toc-custom-pager

**Comment by kiranrajufixstream** [comment]
As I checked with the custom pager by using the above link, I can't see the code related UI in **StackBiltz**. Please check that if possible share me any working fiddle.
![image](https://user-images.githubusercontent.com/38715425/89787138-9c97c680-db3a-11ea-8846-7729846e4f59.png)

Thanks,
Kiran

**Comment by simonssspirit** [comment]
This is the code replated to the custom pager UI:

````const MyPager = (props) => {
    const currentPage = Math.floor(props.skip / props.take) + 1;
    const totalPages = Math.ceil((props.total || 0) / props.take);
    const handleChange = (e) => {
        props.onPageChange({
            target: null,
            skip: (e.value - 1) * props.take,
            take: props.take,
            syntheticEvent: e,
            nativeEvent: e.nativeEvent
        })
    }
    return <div className={props.className} style={{ borderTop: '1px solid', borderTopColor: 'inherit' }}>
        <div className='row'>
            <div className='col-4'>
                <Slider
                    buttons={true}
                    step={1}
                    value={currentPage}
                    min={1}
                    max={totalPages}
                    onChange={handleChange}
                />
            </div>
            <div className='col-4'>
                <NumericTextBox value={currentPage} onChange={handleChange} min={1} max={totalPages} />
            </div>
            <div className='col-4'>
                {`Page ${currentPage} of ${totalPages}`}
            </div>
        </div>
    </div>
}````

**Comment by kiranrajufixstream** [comment]
You mean.. we need to replace the above with something with custom page UI code or This code is reflecting the custom Pager... Actually, I just want to see the code for the following custom pagination...
![image](https://user-images.githubusercontent.com/38715425/89788391-b76b3a80-db3c-11ea-98c4-89dd4e6a3a65.png)
And let me clear about my workaround.. what I'm trying to figure out is the reload button with my own custom react component.
