### ISSUE TITLE
Support uploading files without FormData

### ISSUE THREAD

**Issue by azavarben** [telerik/kendo-react#696]
## I'm submitting a...

* Documentation issue or request

## Current behavior

```
<Upload saveHeaders={{ "Content-Type": "text/csv" }} />
```

## Expected behavior

The `Content-Type` request header would use `text/csv`, however upon upload it uses `multipart/form-data;`

## What is the motivation or use case for changing the behavior?

I'm uploading to an AWS S3 pre-signed url that only takes the `text/csv` content type header.

## Environment

Package versions:

```
"@progress/kendo-react-upload": "^3.15.0"
```

Browser:

- Chrome (desktop) version 84.0.4147.105 (Official Build) (64-bit)

System:
- TypeScript version: XX 
- Node version: 6.14.5
- Platform:  Windows

**Comment by vladimirivanoviliev** [comment]
The reason for current behavior is that the Upload component currently support only sending the files using FormData out of the box - this is the reason why the content type cannot be changed. Possible solutions with current version of the component is to handle the upload process using custom code as Stefan suggested in his previous reply. The best way this could be done is to utilize the [function overload of the 'saveUrl' property](https://www.telerik.com/kendo-react-ui/components/upload/api/UploadProps/#toc-saveurl) as it receives as arguments all raw files, request options, `onProgress` handler for tracking upload progress and it's expected to return Promise which the component will use for tracking the state of the request. Here is a small example of using the 'saveUrl' overload:

- https://stackblitz.com/edit/react-nqgj95?file=app/main.jsx

Another option is to try setup S3 to support direct upload using POST method as described in the following blog post:

- https://softwareontheroad.com/aws-s3-secure-direct-upload/
﻿

**Comment by kdikov82** [comment]
Closing due to the low demand for this feature and available workarounds
