### ISSUE TITLE
Scrolling quickly in Combobox with virtual scroll in some cases results in empty Combobox

### ISSUE THREAD

**Issue by MirAlbertioni** [telerik/kendo-react#697]
## I'm submitting a...

* Bug report 

## Current behavior

![image](https://user-images.githubusercontent.com/31191749/89782241-2fbe0580-db15-11ea-8a02-96a2dc01eebc.png)
When scrolling very fast from top to end sometimes the dropdown shows blank.

## Expected behavior

![image](https://user-images.githubusercontent.com/31191749/89782283-43696c00-db15-11ea-9cd8-3a32b12327de.png)

Package versions:

```
    "@progress/kendo-react-dropdowns": "^3.6.0",
```

Browser:

- Chrome (desktop) version 84.0.4147.105 

System:
- React version: `"react": "16.3.2"`
- Platform: Windows

**Comment by nstoychev** [comment]
Can you reproduce the issue here - https://www.telerik.com/kendo-react-ui/components/dropdowns/combobox/virtualization/#toc-basic-configuration? Note that dropdown items height needs to be equal. In the image in expected section, there are items with bigger height then others which will result in a wrong calculations.

**Comment by acence** [comment]
The problem may occur when the data source is being replaced with a long list of items, and you open the combobox before it is fully bound?

**Comment by MirAlbertioni** [comment]
@nstoychev 

The problem may occur when the data source is being replaced with a long list of items, and you open the combobox before it is fully bound? That cannot be reproduced in the sample environment you provided

**Comment by nstoychev** [comment]
You can [turn off the animation](https://www.telerik.com/kendo-react-ui/components/dropdowns/api/ComboBoxProps/#toc-popupsettings) and test this. With the animation off, the dropdown will open right away. You can also console.log on the ComboBox [onOpen](https://www.telerik.com/kendo-react-ui/components/dropdowns/api/ComboBoxProps/#toc-onopen) event and the data bind process, and see it this is the case.

Here is a demo showing the virtual scroll with remote data - https://www.telerik.com/kendo-react-ui/components/dropdowns/combobox/filtering/#toc-filtering-with-remote-data-and-virtualization
