### ISSUE TITLE
The MultiSelect uses the text value to general id for the selected items. This can cause item with the same id.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#701]
The MultiSelect uses the text value to general id for the selected items. This can cause item with the same id:

https://stackblitz.com/edit/react-tjshka?file=app/main.jsx

**Comment by nstoychev** [comment]
Fixed in 3.17.0 - https://stackblitz.com/edit/react-tjshka-jhdhvg?file=app/main.jsx.
