### ISSUE TITLE
Virtualized Treelist resulting in error "Cannot read property 'offsetTop' of undefined"

### ISSUE THREAD

**Issue by joshmarnold** [telerik/kendo-react#703]
## I'm submitting a...
Bug Report

## Current behavior
1. On a virtualized tree, when scrolling down and then performing a filter will result in the error "Cannot read property 'offsetTop' of undefined"
2. There's also the solved error when scrolling down and then searching for something not in the table. This will result in the error "Cannot read property 'height' of undefined". That ticket was solved here --> https://github.com/telerik/kendo-react/issues/636. That fix did not fix issue 1 though. 

## Expected behavior
To filter based on the input and display results

## Minimal reproduction of the problem with instructions
Typing y88 into the input when scrolled down will show error. 
https://stackblitz.com/edit/treelist-vs-bug-scroll?file=app/main.jsx

**Comment by nstoychev** [comment]
@joshmarnold - Fixed in dev channel - https://stackblitz.com/edit/treelist-vs-bug-scroll-fzp4fj?file=app/main.jsx.

**Comment by Xizario** [comment]
Available in 3.16.0
