### ISSUE TITLE
`WeekView` (Scheduler) not showing events that start before the display week and end during the display week

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#704]
Based on the example: 
[https://www.telerik.com/kendo-react-ui/components/scheduler/views/week/](https://www.telerik.com/kendo-react-ui/components/scheduler/views/week/)

If we add event that starts at one day and ends at the next day - the event will be shown only for the first day in `WeekView`. 
The event is shown correctly in `MonthView`.
For example of the behavior please refer to:

[https://stackblitz.com/edit/react-wpwphz?file=app/events-utc.js](https://stackblitz.com/edit/react-wpwphz?file=app/events-utc.js) 
    _"Start": "2020-06-08T19:00:00.000Z",
    "End": "2020-06-09T08:30:00.000Z"_

The issue is described under ticket: 1480903.

**Comment by kspeyanski** [comment]
The issue has been resolved with version [`3.16`](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#1c33d199-89a5-5f3b-a5f8-e2bbde17601d) of the `@progress/kendo-react-scheduler` package.

Please note that depending on the current timezone of the scheduler or on your local timezone, the visual representation of the view might differ.
