### ISSUE TITLE
The DropDowns popup is misaligned after filtering when it is open upwards.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#706]
The DropDowns popup is misaligned after filtering when it is open upwards.

This can be seen in the following demo:

https://stackblitz.com/edit/react-zrbazh?file=app/main.jsx

![image](https://user-images.githubusercontent.com/11087921/90606909-5800d080-e1b5-11ea-8411-75b193b230a3.png)

**Comment by Snowcart** [comment]
Do we know if this is on the roadmap of getting fixed anytime soon?

**Comment by nstoychev** [comment]
@Snowcart - The issue is no the roadmap and I will start working on it in a few weeks. I hope this is soon enough.

**Comment by nstoychev** [comment]
Fixed in dev channel version 3.17.1-dev.202009171519 - https://stackblitz.com/edit/react-zrbazh-j6pek9?file=app/main.jsx
