### ISSUE TITLE
toolbarButton error console on strict mode for the findDOMNode

### ISSUE THREAD

**Issue by marcosilvestroni** [telerik/kendo-react#708]
## I'm submitting a...

* Suggestion for improvement

## Current behavior
Using the toolbar and the toolbarButton I notice that in console I've got this error in strict mode
```
findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of ToolbarButton which is inside StrictMode. Instead, add a ref directly to the element you want to reference. 
```

## Expected behavior
I expect to be solved in feature release

## Minimal reproduction of the problem with instructions

  1. Create new project
  2. Add kendo-react-button
  3. render a component with Toolbar ToolbarSpacer ToolbarItem and a ButtonGroup with some Dropdown buttons and some simple Buttons 
  4. look at the console

## Environment

Package versions:

```
├── @progress/kendo-drawing@1.9.0
├── @progress/kendo-react-buttons@3.15.0
├── @progress/kendo-react-dateinputs@3.15.0
├── @progress/kendo-react-dropdowns@3.15.0
├── @progress/kendo-react-form@3.15.0
├── @progress/kendo-react-inputs@3.15.0
├── @progress/kendo-react-intl@3.15.0
├── @progress/kendo-react-labels@3.15.0
├── @progress/kendo-react-layout@3.15.0
├── @progress/kendo-react-progressbars@3.15.0
├── @progress/kendo-theme-material@3.18.0
├── @testing-library/jest-dom@4.2.4
├── @testing-library/react@9.5.0
├── @testing-library/user-event@7.2.1
├── node-sass@4.14.1
├── react@16.13.1
├── react-dom@16.13.1
├── react-router-dom@5.2.0
└── react-scripts@3.4.3

```

Browser:

- Firefox version 79

System:

- Node version: 12.18.2
- Platform:  Linux

**Comment by nstoychev** [comment]
Fixed in dev channel - https://stackblitz.com/edit/react-bcuasq-4jyusn?file=app/main.jsx
