### ISSUE TITLE
The change event of the ComboBox is not fired when the clear buttons is clicked.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#71]
The issue can be reproduced here: https://stackblitz.com/edit/react-fr6wta?file=app/main.js

This is the description of the clear button that states that the event should be fired:

https://www.telerik.com/kendo-react-ui/components/dropdowns/api/ComboBoxProps/#toc-clearbutton

"_Clicking this button resets the value of the component to undefined and triggers the change event._"

**Comment by nstoychev** [comment]
We have publish version 2.0.0 where the issue is resolved. Release notes can be found here: https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/.
