### ISSUE TITLE
ComboBox renders empty value when the value is the number 0.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#715]
ComboBox renders empty value when the value is the number 0:

https://stackblitz.com/edit/react-njqd4j?file=app/main.jsx

As a current workaround, the 0 can be transformed into a string, and it will be rendered as expected.

**Comment by Xizario** [comment]
Additionally it renders the word `true` if `defaultValue={}`

**Comment by nstoychev** [comment]
Make sure the props values for `data`, `value` and `defaultValue` point to strings.
