### ISSUE TITLE
useSchedulerEditSlotPropsContext is not exported from the Scheduler package

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#718]
useSchedulerEditSlotPropsContext is not exported from the Scheduler package

https://www.telerik.com/kendo-react-ui/components/scheduler/api/useSchedulerEditSlotPropsContext/

**Comment by pierrealixt** [comment]
`useSchedulerEditItemPropsContext` is as well not exported.

**Comment by kspeyanski** [comment]
The issues has been resolved with the latest `dev` version of the @progress/kendo-react-scheduler package.
