### ISSUE TITLE
Persian calendar usage problem

### ISSUE THREAD

**Issue by ahmadmrj** [telerik/kendo-react#719]
This error occurs when I try to localize Persian calendar for Datepicker.  
https://stackblitz.com/edit/react-xs7try?file=app/main.jsx

**Comment by simonssspirit** [comment]
@ahmadmrj 

Currently, the KendoReact DatePicker (Calendar) only support the gregorian type calendar:

https://feedback.telerik.com/kendo-angular-ui/1452519-jalali-calendar-is-not-working

**Comment by kdikov82** [comment]
There are no plans for introducing support for different calendars
