### ISSUE TITLE
Cannot choose pagesizes with pager

### ISSUE THREAD

**Issue by joccd** [telerik/kendo-react#720]
Hi,

If you look at your documentation (basic usage) : https://www.telerik.com/kendo-react-ui/components/datatools/pager/
and open the example, you can see you cannot choose pagesizes :
![image](https://user-images.githubusercontent.com/22839734/93015587-f3217600-f5ba-11ea-8e1a-601dfe04cae0.png)

Regards,
Joccd

**Comment by simonssspirit** [comment]
@joccd 

This is how the same article looks on my end:

![image](https://user-images.githubusercontent.com/11087921/93082857-82c03680-f646-11ea-9213-8955762b8460.png)

Please perform a hard refresh of the page and advise if the issue still occurs.

**Comment by joccd** [comment]
Sorry, I meant the example on Stackblitz :

![image](https://user-images.githubusercontent.com/22839734/93086217-14f02b00-f697-11ea-95f1-339aa3721802.png)

**Comment by simonssspirit** [comment]
@joccd could you please share the link to the example.

It is visible on the picture, but it is not loading.

**Comment by joccd** [comment]
I just figured out it's due to the responsive. If I open your stackblitz example on a full page it's working.

Thanks
