### ISSUE TITLE
onColumnResize give -1 as index for splited header cell

### ISSUE THREAD

**Issue by adnenre** [telerik/kendo-react#722]
Hello 
I'm submitting an issue related to the gird onColumnResize handler
when we have a splited column we recive `-1` as `index `of the resized column
here an example where you can resize the test cell and get the behavior : [demo](https://stackblitz.com/edit/react-hy6vcg)
Thank you

**Comment by adnenre** [comment]
hello @simonssspirit  is there any news about this is issue 
thanks

**Comment by simonssspirit** [comment]
@adnenre could you please check if this is connected with the React.Strick mode issue: https://github.com/telerik/kendo-react/issues/651

It is already prioritized.

**Comment by vladimirivanoviliev** [comment]
Now columns have new `id` prop which can be used to identify columns better. Also the `GridColumnResizeEvent` now contain `targetColumnId` which should be used instead of the old index argument.

**Comment by adnenre** [comment]
Hi @vladimirivanoviliev  good job 
that's exactly what was needed 
![image](https://user-images.githubusercontent.com/11591834/128277903-76ac3bf5-fcb0-41a2-b784-82791a587760.png)

**Comment by vladimirivanoviliev** [comment]
Hello,

I tried to reproduce the issue with same setup but everything is working as expected on our side:
![image](https://user-images.githubusercontent.com/2195951/128356873-7b2b982f-7bff-4e0a-908a-cecf1a2a473b.png)
In the above screenshot first I resized the top ID column and than the bottom ID column which resulted in correct ids. Here is the demo I used for testing:
- https://stackblitz.com/edit/react-tdib4t?file=app/main.jsx 
Could you please modify the above example and provide the exact steps I need to reproduce the issue on our side?
