### ISSUE TITLE
TabStrip warnings in React.StrictMode

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#723]
These are the two warnings:

- Legacy context API has been detected within a strict-mode tree.
- findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here:

The issue is most probably connected to the animations:

https://github.com/reactstrap/reactstrap/issues/1833

**Comment by simonssspirit** [comment]
The same issue is reproduced inside the PanelBar and both seem to be connected.

Raising priority - 1493762

**Comment by simonssspirit** [comment]
Also reported in 1498972.

**Comment by simonssspirit** [comment]
reported again 1512746

**Comment by simonssspirit** [comment]
1523608 - raising priority again.

**Comment by simonssspirit** [comment]
a possible workaround is to disable the animation:

https://www.telerik.com/kendo-react-ui-develop/components/layout/api/PanelBarProps/#toc-animation

**Comment by Xizario** [comment]
Fixed in 4.7.0 with the update of the react-transition-group to 4.4.2

**Comment by g-six** [comment]
Still happening on my end.
![image](https://user-images.githubusercontent.com/603961/134850818-53c272f0-1036-449b-b1a1-41d7efb2ed19.png)

Using version 4.8.0.

The workaround suggested by @simonssspirit worked for me but just a temporary solution.   Would need the animation / transition still.

Anything I'm missing?  Let me know.

> Fixed in 4.7.0 with the update of the react-transition-group to 4.4.2

**Comment by filipKovachev** [comment]
Reported again in 1543598:
https://stackblitz.com/edit/react-spmvaf?file=app/main.jsx

**Comment by MattiaMalandrone** [comment]
Got the problem with Transition in version v4.11.0

**Comment by simonssspirit** [comment]
reported again in 1549308

**Comment by nstoychev** [comment]
Fixed in dev channel - [v5.0.2-dev.202201241659](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#00162092-d567-545e-a9da-5ce74d2f080a).

See the following article for obtaining development builds - https://www.telerik.com/kendo-react-ui/components/installation/development-builds/.
