### ISSUE TITLE
PDFExport (savePDF) doesn't retain z-index setting

### ISSUE THREAD

**Issue by fonty422** [telerik/kendo-react#725]
## I'm submitting a...
* Bug report 

## Expected behavior
What you see on the browser screen should resemble what you get in the PDF output.

## Minimal reproduction of the problem with instructions
After setting appropriate css using z-index to ensure that various components are rendered on top of each other, the savePDF method does not seem to retain these settings. The rendered browser screen definitely shows things drawn correctly, but the saved PDF does not. There is little alternative here as I have objects drawn in one container that need to extend beyond the bounds of that container and the next rendered one will sit on top of it by default without css intervention. 

## Environment

Package versions:

```
@progress/kendo-drawing": "^1.9.0
@progress/kendo-react-pdf": "^3.15.0
```

Browser:

- Chrome (desktop) version 85.0.4183.102 (Official Build) (64-bit)
- Firefox

System:
- Platform:  Windows

BROWSER:
![image](https://user-images.githubusercontent.com/18232646/93389787-0335a000-f8b0-11ea-9e25-af864a84dcf9.png)

PDF:
![image](https://user-images.githubusercontent.com/18232646/93389900-337d3e80-f8b0-11ea-8cf9-25188731efe7.png)

**Comment by Xizario** [comment]
We don't control how the pdf viewer and the browser will visualize the gray and blue boxes in this example when they have same z-indexes. And it is not something that we can fix.
