### ISSUE TITLE
Drag and Drop between two Treelists

### ISSUE THREAD

**Issue by vladimirivanoviliev** [telerik/kendo-react#728]
Create a demo of Demo of Drag and Drop between two Treelists.

Requested in ticket: 1485338

Could be similar to this example - https://stackblitz.com/edit/react-egjlmx-yrqwfc?file=app%2Fmain.jsx

**Comment by vladimirivanoviliev** [comment]
Currently the `filterBy` method of the TreeList does not support filtering without considering children, however drag and drop case is requiring this (check the `utils.js` / `filterChildren()`):

- https://stackblitz.com/edit/react-egjlmx?file=app%2Futils.js

We should add option for controlling this in `filterBy`.

**Comment by simonssspirit** [comment]
we made a KB for this: https://www.telerik.com/kendo-react-ui-develop/knowledge-base/treelist-drag-and-drop/
