### ISSUE TITLE
ComboBox with filtering should declare a unique "key"

### ISSUE THREAD

**Issue by thejroberts** [telerik/kendo-react#73]
An error is logged when any text is entered into the ComboBox. 

> Each child in an array or iterator should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.

https://stackblitz.com/edit/react-7xs96u?file=app/main.js
https://react-7xs96u.stackblitz.io

**Comment by nstoychev** [comment]
We have publish version 2.0.0 where the issue is resolved. Release notes can be found here: https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/.
