### ISSUE TITLE
noEvents message is not translated in the Scheduler AgendaView.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#731]
noEvents message is not translated in the Scheduler AgendaView:

https://stackblitz.com/edit/react-fnpj46?file=app%2Fes.json

**Comment by kspeyanski** [comment]
The issues has been resolved with the latest `dev` version of the `@progress/kendo-react-scheduler` package:
https://stackblitz.com/edit/react-fnpj46-ywssjj?file=app/es.json
