### ISSUE TITLE
Popup misaligned with initial position Anchor - (left, middle) and Popup (right, bottom)

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#732]
Popup misaligned with initial position Anchor - (left, middle) and Popup (right, bottom):

https://www.telerik.com/kendo-react-ui/components/popup/aligning-positioning/#positioning

The Popup will be positioned correctly, after setting a different position and returning to this one.

More details with images in ticket 1485940.

**Comment by nstoychev** [comment]
Fixed in dev channel - https://stackblitz.com/edit/react-2sahgk?file=app/main.jsx.
