### ISSUE TITLE
Scheduler header and body are misaligned in Firefox 

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-react#734]
Works correctly in Chrome, but in Firefox the header is wider than it should be (or the body is smaller)

<img width="934" alt="Screenshot 2020-09-24 at 16 52 25" src="https://user-images.githubusercontent.com/9458606/94162506-754d4c80-fe8f-11ea-8ed9-6b9863f210db.png">

**Comment by kspeyanski** [comment]
The issue has been resolved with the latest `dev` version of the `@progress/kendo-theme-*` packages:
(note the `<link rel="stylesheet" />` in the `index.html` file)
https://stackblitz.com/edit/react-fazbbl-ikdupx?file=index.html
