### ISSUE TITLE
[Documentation][TreeList] Using Remote Data demo

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-react#737]
Here is how it can be achieved - https://stackblitz.com/edit/react-xchvii-rx7cfn?file=app%2Fmain.jsx.

Currently the TreeList cell component does not have built-in loading icon. Adding and positioning a loading icon does not look straightforward.

A `loadingField` prop of the TreeList could be introduced and the loading icon can be rendered instead of expand icon when necessary.

**Comment by nstoychev** [comment]
Requested again in Ticket ID: 1511547

**Comment by WissamProgress** [comment]
Also requested in Ticket ID: 1608447 where loading data on demand is needed

**Comment by filipKovachev** [comment]
Requested in Ticket ID: 1632606
