### ISSUE TITLE
MultiSelect with virtualization will not scroll past a selected item when scrolling with the mouse wheel.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#738]
MultiSelect with virtualization will not scroll past a selected item when scrolling with the mouse wheel.

This can be reproduced in the following demo:

https://www.telerik.com/kendo-react-ui-develop/components/dropdowns/multiselect/virtualization/

Steps:

1) Selected item 50.
2) Open the MultiSelect and scroll up with the mouse wheel.
3) The scrolling will stop when item 50 is at the bottom of the list.

**Comment by nstoychev** [comment]
Another case reported in ticket: 1489253.
The MultiSelect scrolls to the last selected item when the app state is changed.

**Comment by kdikov82** [comment]
The issue seems to be resolved with the latest version (5.11.0):
[https://stackblitz.com/edit/react-nakmtg?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-nakmtg?file=app%2Fmain.jsx)

**Comment by elena-gancheva** [comment]
This issue is no longer reproducible
