### ISSUE TITLE
A blue box appears when the corner of DropDown is clicked.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#74]
A blue box appears when the corner of DropDown is clicked.

Refer to the video: https://www.screencast.com/t/ZrYhcVY3

**Comment by kspeyanski** [comment]
In which browser is the bug reproduced? It look's like this is the dummy `<select />` element we render for the Forms Support.

**Comment by nstoychev** [comment]
We have publish version 2.0.0 where the issue is resolved. Release notes can be found here: https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/.
