### ISSUE TITLE
Popup horizontal collision only works with fit.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#749]
Popup horizontal collision only works with fit. The flip option is currently not working correctly.

This can be seen in the following example:

https://stackblitz.com/edit/react-vgcddg-fqf9mz?file=app%2Fmain.jsx

**Comment by vladimirivanoviliev** [comment]
This can be fixed with the upcoming `positionMode` option of the Popup component. 
```
<Popup
    positionMode={'fixed'}
```
