### ISSUE TITLE
React component NumericTextBox formatting does not work with some string literals!

### ISSUE THREAD

**Issue by ikos23** [telerik/kendo-react#751]
[Here](https://github.com/telerik/kendo-intl/blob/master/docs/num-formatting/index.md) is your docs for this component. And there is a section:
> The "string"/'string' specifier—A literal string delimiter. It indicates that the enclosed characters should be copied to the result string.

I have a very simple example, where I provide 'mg.m-3' as literal string delimiter:

```
<NumericTextBox
    format="0.## 'mg.m-3'"
    defaultValue={this.state.value}
/>
```

## Current behavior
When I enter any number cursor position is changed to some weird one. 
Neither formatting nor deletion work. Cursor jumps to the middle of 'mg.m-3' string.

## Expected behavior
I expect my number to be formatted according to 0.## and 'mg.m-3' to be added to the result.
Example 1: I enter `123` and get `123 mg.m-3`
Example 2: I enter `5.61` and get `5.61 mg.m-3`
etc.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-t79kwx?file=app/main.jsx

Browser:

- Chrome (desktop) latest

**Comment by vladimirivanoviliev** [comment]
Currently the NumericTextBox does not support formats that contain decimal separators and numbers inside them. The reason for this behavior is that these symbols are used to validate and parse the user input. In current case possible workaround would be using the power signs to describe this format (if I understand it correctly):

```
format="0.## 'mg/m³'"
```

**Comment by ikos23** [comment]
It would be nice to have this mentioned in the docs somewhere. Because it's a but confusing now. It just says 'string' literal, so I'd consider any string to be OK.

**Comment by vladimirivanoviliev** [comment]
It makes sense to update the documentation to be more clear, thanks for the input.
