### ISSUE TITLE
Popup anchor not working correctly the first time 

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#752]
When context menu is opened the first time the anchor is not used, the popup is shown in the top left corner of the window (or container if appendTo is used)

From the second time and on the popup is aligned correctly to the anchor element.

[Code example](https://stackblitz.com/edit/react-esskvc-oat9gc?file=app/main.jsx).

The isuue is described under: 1489317.

**Comment by nstoychev** [comment]
The Cell component in the example has been unmounted when the popup shows. It should be defined outside the grid - https://stackblitz.com/edit/react-esskvc-oqvewo?file=app%2Fmain.jsx.
