### ISSUE TITLE
MultiViewCalendar doesn't update correctly with range values

### ISSUE THREAD

**Issue by idrydi** [telerik/kendo-react#754]
## I'm submitting a...

* Bug report 

## Current behavior
When changing the selected value externally the MultiViewCalendar selects the new date correctly but does not jump to it if it is a range or array. The calendar seems to update correctly if it only handles single dates.

## Expected behavior
When externally setting the value for the MultiViewCalendar to a range of values, the calendar should jump to the new value.

## Minimal reproduction of the problem with instructions
The issue can be reproduced in the documentation: https://www.telerik.com/kendo-react-ui/components/dateinputs/multiviewcalendar/controlled-state/#dynamically-changing-the-value
  * Click the button "Set Date to Christmas"
  * The calendar will select the date range but not navigate to it
  * Sometimes the calendar will update correctly the first time you click the button, but if you navigate away to select another date range and then click the button a second time, it will fail

## What is the motivation or use case for changing the behavior?
The calendar should behave the same as long as it is provided supported values.

## Environment

Browser:

- Chrome (desktop) version 86

**Comment by rabinage** [comment]
Is there any estimate for when this can be fixed?

**Comment by Xizario** [comment]
You can modify the focused date at any time by the state of the calendar.
https://stackblitz.com/edit/react-4arryq?file=app/main.jsx

**Comment by Xizario** [comment]
If we consider this as a bug, `focusedDate` as currently noted in the documentation behaves more like `defaultFocusedDate` Changing this will likely break most of the existing users of this property. So I am adding this as eventual consideration for v5. But would recommend to use the approach in my previous post.

**Comment by rabinage** [comment]
Refocus when passing in a new value is the default behaviour for the "simple" `Calendar` which makes it confusing. It's also confusing that the `MultiViewCalendar` get focus on the initially set value but not refocusing when the value changes. 
That's why we considered it as a bug.

**Comment by simonssspirit** [comment]
we made a KB with the example: https://www.telerik.com/kendo-react-ui-develop/knowledge-base/multiviewcalendar-control-focus-date/

the example works on StackBlitz (EDIT IN STACKBLITZ)

**Comment by kdikov82** [comment]
https://www.telerik.com/kendo-react-ui/components/knowledge-base/multiviewcalendar-control-focus-date/
