### ISSUE TITLE
The Grid header is remounted when the group row is removed (no data)

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#755]
The Grid header is remounted when the group row is removed (no data).

The other way around is also valid, the header is remounted when grouping the Grid.

This is causing issues with the column menu.

**Comment by adamvan101** [comment]
Is this being worked on? I was under the impression there'd be a fix already

**Comment by simonssspirit** [comment]
Yes, the fix is on a pull request and it is being tested.

**Comment by Xizario** [comment]
available in dev channel https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#9e25de44-23ab-583b-abb6-d226f2af9a20
