### ISSUE TITLE
IS IT POSSIBLE TO EXPORT DATA INTO EXCEL WITH MAP FUNCTION IN REACT?

### ISSUE THREAD

**Issue by ideal22** [telerik/kendo-react#759]
Hello. I am trying to use this package as dynamically, but it returns nothing, here is my source code.

`
import * as React from "react";
import * as ReactDOM from "react-dom";
import {
  ExcelExport,
  ExcelExportColumn,
  ExcelExportColumnGroup,
  ExcelExportFooter,
} from "@progress/kendo-react-excel-export";
import { aggregateBy } from "@progress/kendo-data-query";
import products from "./data.json";
import { connect } from "react-redux";
import moment from "moment";

// const data = products;

const aggregatesForReceiveAmount = [{ field: "sum_in_uzs", aggregate: "sum" }];

const aggregateForSendAmount = [
  { field: "send_amount_in_number", aggregate: "sum" },
];

const aggregateForCommission = [{ field: "commission", aggregate: "sum" }];

const ExportToExcel = ({ filteredData, dates, dataByDate }) => {
  try {
    const exporter = React.useRef(null);
    const [totalReceiveAmount, setTotalReceiveAmount] = React.useState(null);
    const [totalCommission, setTotalCommission] = React.useState(null);
    const [totalSendAmount, setTotalSendAmount] = React.useState(null);
    const [dataToNumberType, setDataToNumberType] = React.useState(null);
    const [groups, setGroups] = React.useState(null);
    const [columns, setColumns] = React.useState(null);

    const exportToExcel = () => {
      exporter.current.save();
    };

    // const save = (component) => {
    //   console.log(component, "component");
    //   const options = component.workbookOptions();
    //   const rows = options.sheets[0].rows;

    //   rows.forEach((row) => {
    //     if (row.type === "data") {
    //       row.cells.forEach((cell) => {
    //         if (cell && cell.textAlign)
    //           cell.value = Number(cell.value).toLocaleString("ru");
    //       });
    //     } else if (row.type === "footer") {
    //       row.cells.forEach((cell) => {
    //         if (cell.value && typeof cell.value === "number")
    //           cell.value = Number(cell.value).toLocaleString("ru");
    //       });
    //     }
    //   });

    //   component.save();
    // };

    React.useEffect(() => {
      if (dataByDate && dataByDate.all) {
        setTotalReceiveAmount(
          aggregateBy(dataByDate.all, aggregatesForReceiveAmount)
        );
        // setTotalSendAmount(aggregateBy(dataByDate.all, aggregateForSendAmount));
        // setTotalCommission(aggregateBy(dataByDate.all, aggregateForCommission));
      }
    }, [dataByDate]);

    const CustomFooterForTotal = () => {
      return "Жами";
    };

    const CustomFooterForReceivedAmount = () => {
      return `${
        totalReceiveAmount && totalReceiveAmount.sum_in_uzs.sum.toFixed(2)
      }`;
    };

    const CustomFooterForCommission = () => {
      return `${totalCommission && totalCommission.commission.sum.toFixed(2)}`;
    };

    const CustomTotalFooterForSendAmount = () => {
      return `${
        totalSendAmount && totalSendAmount.send_amount_in_number.sum.toFixed(2)
      }`;
    };

    return (
      <div>
        <button className="k-button" onClick={exportToExcel}>
          Export to Excel
        </button>

        <ExcelExport
          data={dataByDate && dataByDate}
          fileName="Products.xlsx"
          ref={exporter}
        >
          <ExcelExportColumn field={"1"} title="№" width={30} />
          <ExcelExportColumn
            field="mfo"
            title="Филиаллар"
            // footer={CustomFooterForTotal}
            footerCellOptions={{ textAlign: "right" }}
          />
          {dataByDate &&
            dataByDate.length &&
            dataByDate.map((item) => {
              return item.groups.map((el, i) => (
                <ExcelExportColumnGroup
                  key={i}
                  title="title"
                  headerCellOptions={{ textAlign: "center" }}
                >
                  {el &&
                    el.length &&
                    el.columns.map((entry, ii) => (
                      <ExcelExportColumn
                        key={ii}
                        field={entry.value.toFixed(2)}
                        title={entry.title}
                        footerCellOptions={{
                          wrap: true,
                          textAlign: "center",
                        }}
                        cellOptions={{ textAlign: "center" }}
                        width={150}
                      />
                    ))}
                </ExcelExportColumnGroup>
              ));
            })}
        </ExcelExport>
      </div>
    );
  } catch (error) {
    console.log(error, "error");
  }
};
const mapStateToProps = (state) => {
  return {
    dataByDate: state.transactions.dataByDate,
  };
};

export default connect(mapStateToProps, null)(ExportToExcel);

`

**Comment by ideal22** [comment]
Here is my structure of my  DATA

`const data = [
  {
    mfo: "010101",
    groups: [
      {
        title: "title",
        columns: [
          { title: "title1", value: "value" },
          { title: "title1", value: "value" },
        ],
      },
      {
        title: "title",
        columns: [
          { title: "title1", value: "value" },
          { title: "title1", value: "value" },
        ],
      },
    ],
  },
];`

**Comment by ideal22** [comment]
<img width="436" alt="Screen Shot 2020-10-19 at 12 51 03 PM" src="https://user-images.githubusercontent.com/33810180/96416757-dc012400-1209-11eb-9e04-9cf675e977e0.png">

>

**Comment by simonssspirit** [comment]
@ideal22 

After the options have changed, we have to pass the new options to the save method as shown here:

https://www.telerik.com/kendo-react-ui/components/excelexport/customization/

````
       component.save(options);
````
