### ISSUE TITLE
Resize issue of  kendo-react  grid in rtl mode.

### ISSUE THREAD

**Issue by aliklev** [telerik/kendo-react#76]
Cannot resize kendo-react grid in  rtl mode
Sample with issue:
[https://stackblitz.com/edit/react-oafsmk](url)

**Comment by fkazemi5236** [comment]
When the site is in RTL mode, this is the opposite. When you move the mouse to the right, the fields are pulled, and when we turn left, the fields shrink.
In the case of RTL, the field should be minimized when the mouse is pulled to the right, and when the mouse is pulled to the left, the field will be enlarged.
