### ISSUE TITLE
MultiSelect not closing sometimes when clicking outside of it.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#762]
MultiSelect not closing sometimes when clicking outside of it.

This can be observed in the overview demo as well:

 https://www.telerik.com/kendo-react-ui/components/dropdowns/multiselect/ 

Also, there is a video in ticket: 1489413

The issue could be connected to the logic on the onBlur event:

https://github.com/telerik/kendo-react-private/blob/develop/packages/dropdowns/src/MultiSelect/MultiSelect.tsx#L861

**Comment by nstoychev** [comment]
Fixed with [4.2.0-dev.202012080808 version](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#95156f23-f840-5a62-b1b6-29c0a69a4aaa).
