### ISSUE TITLE
Add an External Drop Zone Component

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#766]
Add an External Drop Zone Component.

**Comment by silviyaboteva** [comment]
Added in [`v4.5.0`](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#0efc49cf-fb41-5e8f-9773-5fc4a4663e58). 
Here is the [docs link](https://www.telerik.com/kendo-react-ui-develop/components/upload/external-drop-zone/).
