### ISSUE TITLE
ColorPicker: add Contrast Color

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#767]
Add `Contrast Color` as a feature of the ColorPicker component.

**Comment by silviyaboteva** [comment]
Added in `4.6.0`. Documentation llinks: 
- https://www.telerik.com/kendo-react-ui/components/inputs/colorpicker/color-contrast/ 
- https://www.telerik.com/kendo-react-ui/components/inputs/colorgradient/color-contrast/
