### ISSUE TITLE
Provide an option to globally set the Popup appendTo option.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#769]
Provide an option to globally set the Popup appendTo option.

Currently, we have many components that internally render a Popup and all of them are rendering the Popup by default inside the body.

This can cause different issues when using portals or modal containers that trap the focus.

One of the many uses cases can be seen in the ticket: 1492122

Another use case is with the Editor: https://github.com/telerik/kendo-react/issues/661

**Comment by rkirilov** [comment]
Hey guys, we need this too. Fingers crossed for a fix !

**Comment by Xizario** [comment]
available in 4.2.0 dev https://stackblitz.com/edit/popups-iframe
