### ISSUE TITLE
Grid selection cell is rendered is group header

### ISSUE THREAD

**Issue by vladimirivanoviliev** [telerik/kendo-react#77]
Grid selection cell is rendered is group header as seen in the following screenshot: 
![selectionwithgroupin1g](https://user-images.githubusercontent.com/2195951/45040319-6740ef00-b06e-11e8-8196-7e4639757908.png)

**Comment by wzc19920413** [comment]
Any update on this issue?

**Comment by nstoychev** [comment]
We have publish version 2.0.0 where the issue is resolved. Release notes can be found here: https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/.
