### ISSUE TITLE
Dragging issue in Grid header in Firefox when sorting is enabled

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#773]
Can be observed in 
https://www.telerik.com/kendo-react-ui/components/grid/grouping/
And https://www.telerik.com/kendo-react-ui/components/grid/sorting/

Steps to reproduce:
1) Ensure Sorting is enabled
2) Try to drag a header cell.
3) Cell is not draggable, instead the text of the sorting is selected.

Additionally in FF, even if the sorting is not enabled, the dragging works, but text of the cell is still selected, and it should not be.

**Comment by Xizario** [comment]
It works perfectly with 81, 64 bit.

Is there information about errors or something that we can check?

**Comment by simonssspirit** [comment]
There were no errors in the console.

The interesting part was that the drag clue was showing that the column cannot be dropped over the group header. I assume that the issue is connected with that logic and the event is not fired.

**Comment by simonssspirit** [comment]
reported again in 1493861

**Comment by billyudi** [comment]
Sent here from the Kendo Forums to post versions where I see the issue:

- Firefox 82.0.2 on Mac OS 10.15.7
- Firefox 82.0.2 (64-bit) on Windows 10

**Comment by Xizario** [comment]
Fixed in 4.2.0
