### ISSUE TITLE
DateRangePicker Calendart switching to next month on hover

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#775]
DateRangePicker Calendart switching to next month on hover.

Steps to reproduce:

1. Pick date range in the DateRangePicker
2. Close popup with calendar
3. Open calendar again and hover on its right part
4. Month is switching to next one

This can be obsered in the overview page: https://www.telerik.com/kendo-react-ui/components/dateinputs/daterangepicker/

**Comment by kspeyanski** [comment]
The issue has been fixed in the latest `dev` version of the `@progress/kendo-react-dateinputs` package.
The fix can be observed in the following stackblitz example:
[https://stackblitz.com/edit/react-rk23oe?file=app/main.jsx](https://stackblitz.com/edit/react-rk23oe?file=app/main.jsx)
