### ISSUE TITLE
Provide a custom render option for the TreeList column menu.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#776]
Provide a custom render option for the TreeList column menu.

The main requirement is to be able to render extra content inside the column menu.

This will allow the achieve the same functionalities as in the Grid:

Column chooser:

https://www.telerik.com/kendo-react-ui-develop/components/grid/columns/column-menu/#custom-components

Lock columns:

https://www.telerik.com/kendo-react-ui-develop/components/grid/columns/locked/#locked-columns-with-column-menu

**Comment by nstoychev** [comment]
Here is how to modify the column menu - https://stackblitz.com/edit/react-ucebku?file=app%2Fmain.jsx

**Comment by nstoychev** [comment]
Implemented in 4.6.0 - https://www.telerik.com/kendo-react-ui/components/treelist/columns/menu/#toc-adding-custom-items-to-the-column-menu.
