### ISSUE TITLE
DropDowns invalid IDs listed in aria-activedescendant and aria-owns

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-react#778]
When the popup is closed, the aria-activedescendant and aria-owns could be set to null as the list of options is not rendered.

Same issue in angular dropdowns: https://github.com/telerik/kendo-angular-dropdowns/issues/649 

Ticket ID: 1493673

**Comment by nstoychev** [comment]
We have published a fix with [4.2.0-dev.202012080808 version](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#95156f23-f840-5a62-b1b6-29c0a69a4aaa).

Here is an example with the ComboBox - https://stackblitz.com/edit/react-ehkaa6?file=app/main.jsx.

**Comment by Xizario** [comment]
Fixed in 4.2.0
