### ISSUE TITLE
DropDownList setting value before data doesn't update the text

### ISSUE THREAD

**Issue by PaitoAnderson** [telerik/kendo-react#78]
## I'm submitting a...
* Bug report

## Current behavior
If you update the dropdown list data property with data and have already set the value property the dropdown text is blank.

## Expected behavior
The dropdown text should update to be the selected text value

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-se8jqi?file=app%2Fmain.js

## What is the motivation or use case for changing the behavior?
I have a remote data source, but when the screen loads I already know what item I would like to select. 

## Environment

Browser:
- Chrome (desktop) version 69.0.3497.81

System:
- TypeScript version: 3.0.1
- Node and NPM versions: 6.4.0 and 10.6.0
- Platform: macOS

## Additional information

I solved this issue by setting the item I would like to select and the data source at the same time, but it would be nice to not have to do that.

**Comment by Xizario** [comment]
Here is modified version.
https://stackblitz.com/edit/react-se8jqi-k19eul?file=app/main.js
Please note that the `valueField` property will be removed from the `v2.0.0` as part of several changes in how the dropdowns work. The corrected version here will work after the update as well.

**Comment by PaitoAnderson** [comment]
Thanks @Xizario! Closing.
