### ISSUE TITLE
MultiSelect selected tag are rendered under the popup.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#781]
MultiSelect selected tags are rendered under the popup.

It is expected the popup list the reposition after new tags are selected:

https://stackblitz.com/edit/react-tdaasc-rbajvj

![image](https://user-images.githubusercontent.com/11087921/98213762-3c080200-1f4e-11eb-9608-352e3d42daed.png)

**Comment by simonssspirit** [comment]
1501246 - Another report for the case probably related to this one.

When deselecting items, the Popup is not repositioned and looks detached from the MultiSelect

**Comment by nstoychev** [comment]
Fixed in dev channel: https://stackblitz.com/edit/react-tdaasc-tzxc8p
