### ISSUE TITLE
Update the SvgIcon demo

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-react#785]
In the following resource:
https://www.telerik.com/kendo-react-ui/components/utils/svgicon/
Using Version `0.1.2` of `@progress/kendo-svg-icons` the icons have `Icon` suffix after each name, so the exports in the current demo are outdated
Open the [SVG Icons List demo](https://stackblitz.com/edit/react-o68sph?file=app/main.jsx) in Stackblitz and update the dependencies to see the new names.

CC: @joneff

**Comment by simonssspirit** [comment]
The demos are updated https://www.telerik.com/kendo-react-ui-develop/components/utils/svgicon/
