### ISSUE TITLE
Passing a React component as Child to the Button cause a PropType warning.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#79]
The PropType checking of the children prop should be set to accept a React component as valid children.

**Comment by rohit-sourcefuse** [comment]
I am also facing the same issue.

**Comment by nstoychev** [comment]
We have published a fix in our dev channel: https://www.npmjs.com/package/@progress/kendo-react-grid/v/2.2.0-dev.201810091021. Please refer to [this article](https://www.telerik.com/kendo-react-ui/components/installation/development-builds/) on how to obtain the development builds.
