### ISSUE TITLE
Provide a configuration option to the Grid virtualization that will work with all data available locally.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#794]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by Xizario** [comment]
Moved to https://github.com/telerik/kendo-react/issues/795
