### ISSUE TITLE
Provide a configuration option to the Grid virtualization that will work with all data available locally.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#795]
Provide a configuration option to the Grid virtualization that will work with all data available locally.

Currently, the Grid virtualization does not require all data to be available in order to work with remote data and improve the rendering performance.

This comes with its limitations, some of which are described here: https://github.com/telerik/kendo-react/issues/188

The new option will solve that by requiring all items to be available to the client, as this is the only way to know the correct height of the container.

This on the other hand comes with some performance drawbacks as it will require the Grid to construct the full DOM tree before rendering. The difference in performance can be seen in our Kendo UI for Angular Grid:

https://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/virtual/#toc-using-virtualization-with-grouping

The other option will be connected with the scroll sync. We currently needed to remove the [browser height limitation](https://stackoverflow.com/questions/10882769/do-the-browsers-have-a-maximum-height-for-the-body-document) when having millions of records. Removing the scroll sync can be removed, but then we height limitation can be hit.

Based on the data and the use case, the developer can choose which is the best performance/usability configuration for their application.

cc: @Xizario

**Comment by ehardesty** [comment]
For my use case, this solution would be a worthwhile compromise. Particularly so, if this enables the ability to collapse/expand groups.

**Comment by dan-drews** [comment]
Would this allow us to use virtual scrolling with variable row heights?

**Comment by nstoychev** [comment]
The issue has been resolved.

Please, see my comment here: https://github.com/telerik/kendo-react/issues/1367#issuecomment-1422889160.
