### ISSUE TITLE
Can't remove elements from Multiselect when passed as object property

### ISSUE THREAD

**Issue by jakubmichalec** [telerik/kendo-react#797]
Can't remove elements from Multiselect when passed as object property.

Repro: https://stackblitz.com/edit/react-henrpa?file=app/main.jsx
Add 3 elements to list, try remove all of them

when state is declared as object `const [state, setState] = useState({ dummyString: "", dummyList: [] });` than removing item works odd (no response to click on item x), but when used as just array `const [state, setState] = useState([])` than it's work ok

**Comment by nstoychev** [comment]
Another important detail is that a function is passed to setState and the MultiSelect value is not correct when it is called. Here is how the issue can be resolved - https://stackblitz.com/edit/react-henrpa-fmxdar?file=app/main.jsx.

**Comment by nstoychev** [comment]
The issue is in the provided example. The multiselect value should be obtained from the event's target without delay.
