### ISSUE TITLE
Window component is missing className prop, so it is not possible to set CSS classes to it.

### ISSUE THREAD

**Issue by ikos23** [telerik/kendo-react#798]
I consider this as a bug!

* Bug report 

## Current behavior
It is not possible to add CSS classes to `Window` component because `className` property is missing.
Docs: https://www.telerik.com/kendo-react-ui/components/dialogs/api/WindowProps/

## Expected behavior
`Window` should work similar to `Dialog` component and have `className` property, so the user could set CSS classes on window DOM element.

## Minimal reproduction of the problem with instructions
```
// Create some Window
<Window title="Hello" className="myClass">
    <div>Some content</div>
</Window>

// have css class available somewhere
.myClass {
    color: red !important;
    width: 60px;
}
```
CSS class has no effect in this case.

## What is the motivation or use case for changing the behavior?
`className` is basic React stuff that all components should support.

## Environment
Any

Browser:
Any

System:
Any

**Comment by nstoychev** [comment]
We have published a fix with [4.2.0-dev.202012080808 version](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#95156f23-f840-5a62-b1b6-29c0a69a4aaa).

Here is an example: https://stackblitz.com/edit/react-ayhtkr?file=app%2Fmain.jsx.
