### ISSUE TITLE
TextArea not working properly using Formik useField hook

### ISSUE THREAD

**Issue by davidkhierl** [telerik/kendo-react#799]
Formik throwing a warning the id or name is not get passed to the input

**Comment by silviyaboteva** [comment]
Thank you for opening a new issue. I agree that an HTMLElement should be returned instead of ref to this element.

**Comment by jchn-codes** [comment]
Hi, is there any progress on this issue or an eta of a fix?

**Comment by silviyaboteva** [comment]
@jchn-codes,
This will be a breaking change for the component. Providing specific ETA could be misleading as the planning is very dynamic and how the other already planned tasks are moving.

**Comment by InaGlushkova** [comment]
The issue does not seem to exist.

For reference, please check the following example:
https://stackblitz.com/edit/react-cgbtoa-3tshnw?file=app/main.jsx

**Comment by davidkhierl** [comment]
@InaGlushkova The issue does still exist, in our case we do use a formik hook `useField` to achieve more customization.
here's the example.
https://stackblitz.com/edit/react-cgbtoa-ukxpjd?file=app/main.jsx

**Comment by davidkhierl** [comment]
> @InaGlushkova The issue does still exist, in our case we do use a formik hook `useField` to achieve more customization.
> here's the example.
> https://stackblitz.com/edit/react-cgbtoa-ukxpjd?file=app/main.jsx

I updated the example to show Input component is working perfectly fine alongside with the `useField` hook.

**Comment by InaGlushkova** [comment]
@davidkhierl  Thank you for clarifying your use case.

Yes, the issue exists in this case. 
We are already moving forward with the implementation.

**Comment by Xizario** [comment]
Fixed in 4.8.0 https://stackblitz.com/edit/react-cgbtoa-8muxqp
