### ISSUE TITLE
Documentation improvement.

### ISSUE THREAD

**Issue by mitagg** [telerik/kendo-react#80]
## I'm submitting a...

* Documentation improvement

## Suggested improvement

List the Gauges components under the [*dataviz components* section](https://www.telerik.com/kendo-react-ui/components/) similar to the [Angular website](https://www.telerik.com/kendo-angular-ui/components/).

### P.S. 

Great work guys, the product is shaping up very well!

**Comment by kspeyanski** [comment]
Hello @mitagg 

Thank you for the suggestion. 
The addition of the `gauges` to the dataviz section is now live in our `dev` channel. https://www.telerik.com/kendo-react-ui-develop/components/

If you have any more suggestions for improvements we will be happy to hear! ^^

Greetings, 
Kiril
