### ISSUE TITLE
Scheduler MonthView - Going a day back from day 1 of the month skips a month.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#800]
Scheduler MonthView - Going a day back from day 1 of the month skips a month.

Steps to reproduce:

1) Go to the demo: https://www.telerik.com/kendo-react-ui/components/scheduler/views/month/

2) Change the day to May 1st:

![image](https://user-images.githubusercontent.com/11087921/100842345-61baf500-3481-11eb-95fa-d6b5d54312fb.png)

3) Go back one day using the arrows and noticed how to go to March instead of April:

![image](https://user-images.githubusercontent.com/11087921/100842421-7e572d00-3481-11eb-9f4f-3a74291cd998.png)

**Comment by kspeyanski** [comment]
The issue has been fixed in version [4.9.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/) of the `@progress/kendo-react-scheduler` package.
