### ISSUE TITLE
MonthViewProps should not have hard-coded WEEK_DAY_FORMAT and DAY_FORMAT

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-react#810]
User should be able to change the format that `k-nav-day` spans have.
[src](https://github.com/telerik/kendo-react-private/blob/749fb8fa726676366ba14b0aab4b145c9958b422/packages/scheduler/src/views/month/MonthView.tsx#L38-L39)

**Comment by simonssspirit** [comment]
It should allow customizing the text (format) similar to this feature: https://docs.telerik.com/kendo-ui/api/javascript/ui/scheduler/configuration/dateheadertemplate

**Comment by Xizario** [comment]
@simonssspirit, Yes exposing a custom component for the whole cell is valid request as well.

**Comment by kspeyanski** [comment]
We've added a [`dateHeaderCell`](https://www.telerik.com/kendo-react-ui/components/scheduler/api/DayViewProps/#toc-dateheadercell) prop to the `MonthView`, `WeekView , `WorkWeekView`, `DayView` and `TimelineView`. In additional [`timeHeaderCell`](https://www.telerik.com/kendo-react-ui/components/scheduler/api/TimelineViewProps/#toc-timeheadercell) is available for the `TimelineView` to allow for more granular customization options.

Format customization can be achieved by providing a custom `dateHeaderCell` or `timeHeaderCell`. I've prepared a small stackblitz example to demonstrate the feature in action:
https://stackblitz.com/edit/react-plxnyc-tr2wsc?file=app/main.jsx
