### ISSUE TITLE
Combobox issue

### ISSUE THREAD

**Issue by VidhyaAditi** [telerik/kendo-react#815]
I have consecutive combo boxes in my page. In Ipad and Tablet onselection of one dropbox value,other dropbox values are getting poped up. Please refer the scren shot. On selceting the value from one combo box immediate combobox values are getting poped up.Please let know the rootcause of this

![image](https://user-images.githubusercontent.com/10175110/103089946-9dc31f00-4615-11eb-8bd8-ed15c364b6b3.png)
<img width="960" alt="Kendo-Combobox_issue" src="https://user-images.githubusercontent.com/10175110/103089981-be8b7480-4615-11eb-9b75-ea1b76cbc9ca.png">

**Comment by kdikov82** [comment]
I was not able to reproduce the issue with the latest version (5.10.0)
