### ISSUE TITLE
Resizing Window component in container is not working as expected

### ISSUE THREAD

**Issue by vladimirivanoviliev** [telerik/kendo-react#816]
There are few issues with Window component nested in container listed below:
- On maximize, it takes the full width / height of the entire body / window, instead of just the container dimensions
- On resize, it 'bounce' and skip due to calculation was based on the body / window

But on move, it does detect the boundaries of the container (which makes me believe it is aware of itself being in a container?)

Demo: https://stackblitz.com/edit/react-zj7syr?file=app/main.jsx
Ticket: #1500295

**Comment by Xizario** [comment]
Fixed in 4.2.0
