### ISSUE TITLE
Allow using custom compare functions inside the orderBy and process methods of kendo-data-query

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#819]
Allow using custom compare functions inside the orderBy and process methods of kendo-data-query.

Similar to the Kendo UI option:

https://docs.telerik.com/kendo-ui/api/javascript/ui/treelist/configuration/columns.sortable.compare

https://github.com/telerik/kendo-data-query/issues/132

**Comment by simonssspirit** [comment]
requested again in 1501394

**Comment by simonssspirit** [comment]
requested again in 1512692

**Comment by simonssspirit** [comment]
requested in 1530830. Adding in ToDo list.

**Comment by simonssspirit** [comment]
requested again in 1534471

**Comment by simonssspirit** [comment]
requested again in 1536447

**Comment by simonssspirit** [comment]
requested again in 1549583

**Comment by joshualan** [comment]
this would be super helpful, like for sorting dates

**Comment by kdikov82** [comment]
Requested again in 1607533

**Comment by filipKovachev** [comment]
Requested again in 1614546

**Comment by nstoychev** [comment]
We implemented 'compare' property of the SortDescriptor in @progress\kendo-data-query package - version 1.7.0, which allows to define a function with custom sort logic.

Example:
```ts
import { orderBy, SortDescriptor } from '@progress/kendo-data-query';

const data = [{ foo: 100 }, { foo: 1 }, { foo: 10 }, {  foo: 5 }];

const sortDescriptor: SortDescriptor[] = [{ 
     field: 'foo',
     compare: (a, b) => (a.foo === b.foo) ? 0 : (a.foo > b.foo ? 1 : -1)
}];

const result = orderBy(data, sortDescriptor);

console.log(result);
// [{ foo: 1 }, { foo: 5 }, { foo: 10 }, {  foo: 100 }
```
