### ISSUE TITLE
Invisible value axis labels are still "rendered" on the chart

### ISSUE THREAD

**Issue by gerrod** [telerik/kendo-react#82]
## I'm submitting a...
Bug Report

## Current behavior
In a kendo chart, if you have a value axis that is invisible, but has a label, the chart renders a gap where that axis would be placed.

## Expected behavior
An invisible axis shouldn't take up any room on the chart surface

## Minimal reproduction of the problem with instructions
See: https://stackblitz.com/edit/react-kadcbq-3ezv4y?file=app/main.js

Notice how the "Degrees" axis on the top chart is not lined up with the "Degrees" axis on the bottom chart. If you remove the label from the (invisible) "Percent" axis in the first chart, the charts then render properly aligned.

## What is the motivation or use case for changing the behavior?
We build charts dynamically and allow the user to turn an axis on/off at runtime - currently we now have to remove the labels for each invisible axis, instead of simply toggling their visiblitiy.

Browser:
- Chrome (desktop) version 68

**Comment by Xizario** [comment]
The `title` have it's own visibility.  
So I think the real issue is that the title is not visible. The space is correctly allocated.
I title should be visible even if the value axis is not.

**Comment by gerrod** [comment]
Ah, ok @Xizario - either way the behaviour was unexpected...

My 2c would be that it seems a *bit* weird to allow the title to show without the axis showing, since the title is a child of the axis - normal HTML would dictate that if a parent element is hidden, the children are also hidden.

**Comment by vladimirivanoviliev** [comment]
Fixed on our side, can be expected in next dev releases.

**Comment by vladimirivanoviliev** [comment]
Fixed in latest dev version:

https://stackblitz.com/edit/react-kadcbq-3yavmb?file=app/main.js
