### ISSUE TITLE
Add a method to the Form that will validate it programmatically.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#820]
Add a method to the Form that will validate it programmatically.

**Comment by DaleyKD** [comment]
When you guys get to this, it'd be nice to have a way to also get the form values programmatically.

**Comment by simonssspirit** [comment]
@DaleyKD there is already a way to get the Form value using the valueGetter method https://www.telerik.com/kendo-react-ui/components/form/advanced-scenarios/#toc-reading-the-field-state

**Comment by samaybhavsar** [comment]
Any ETA on this ?

**Comment by sfc-gh-vpawar** [comment]
Is there a workaround to achieve this?

**Comment by kdikov82** [comment]
This is already available through the "validator" function of the Form component and forcing the validation with "forceUpdate":

- https://www.telerik.com/kendo-react-ui/components/form/api/FormProps/#toc-validator
- https://stackblitz.com/edit/react-qvpbdz?file=app%2Fmain.jsx
- https://www.telerik.com/kendo-react-ui/components/form/validation/#toc-form-validation
