### ISSUE TITLE
DatePicker - Missing Depth

### ISSUE THREAD

**Issue by Phibee** [telerik/kendo-react#822]
DatePicker unable to show Year only.. Or Is there a separate component for Year?

**Comment by kspeyanski** [comment]
Hello @Phibee ,

The `topView` and `botomView` properties are available for the `Calendar` component and cam be modified to allow `year` view only.

Please refer to this example on how to provide customized `Calendar` to the `DatePicker`:
https://stackblitz.com/edit/react-5legz7-txxyll?file=app/main.jsx

**Comment by Xizario** [comment]
```jsx
<DatePicker
  format="yyyy"
  calendar={props => (
    <Calendar {...props} topView={"decade"} bottomView={"decade"} />
  )}
/>
```

**Comment by Phibee** [comment]
> ```js-jsx
> <DatePicker
>   format="yyyy"
>   calendar={props => (
>     <Calendar {...props} topView={"decade"} bottomView={"decade"} />
>   )}
> />
> ```

Thank you very much for the quick response :)

yes that's the solution i made earlier.
