### ISSUE TITLE
Grid is no records show a missing key warning (4.2.0)

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#824]
Grid is no records show a missing key warning (4.2.0).

preview-fef3604083950c709c52b.js:1 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `KendoReactGrid` 

This is reproducible since version 4.2.0. Version 4.1.0 has no warning.

**Comment by simonssspirit** [comment]
reported again in 1501625

**Comment by Xizario** [comment]
Fixed in 4.3.0
