### ISSUE TITLE
Weird popup position

### ISSUE THREAD

**Issue by joccd** [telerik/kendo-react#827]
Hi,

On your example : https://www.telerik.com/kendo-react-ui/components/popup/aligning-positioning/#toc-positioning

If I choose Anchor align point vertical middle :
![image](https://user-images.githubusercontent.com/22839734/104204646-cb89cf80-542d-11eb-8eb7-e61cbfe7d073.png)

As you can see, the top right popup corner is in the anchor, why ?

Regards,
Joccd

**Comment by simonssspirit** [comment]
connected with https://github.com/telerik/kendo-react/issues/732

**Comment by nstoychev** [comment]
Fixed in dev channel - https://stackblitz.com/edit/react-2sahgk?file=app/main.jsx.
