### ISSUE TITLE
Add an option to disable the responsive option of the Pager

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#830]
Add an option to disable the responsive option of the Pager

Similar to the Kendo UI Pager responsive option:

https://docs.telerik.com/kendo-ui/api/javascript/ui/pager/configuration/responsive

**Comment by silviyaboteva** [comment]
Added in `4.6.0.`. Link to the docs: https://www.telerik.com/kendo-react-ui/components/datatools/pager/#toc-responsive-design.
