### ISSUE TITLE
DateTimePicker changing AM/PM values with the arrow keys changes the dates as well.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#833]
DateTimePicker changing AM/PM values with the arrow keys changes the dates as well.

https://www.telerik.com/kendo-react-ui/components/dateinputs/datetimepicker/controlled-state/

1) Highlight the AM/PM section.

2) Press the up arrow key to go from "AM" -> "PM" -> "AM" - note that for each "PM" to "AM" change, the Day value increments

3) Press the down arrow key to go from "AM" -> "PM" -> "AM" - note that for each "AM" to "PM" change, the Day value decrements.

**Comment by rishu73** [comment]
This also applies to other fields. For example if you start with: "12-31-2020 11:59 PM", select the minutes section then press the up arrow, the date will change to "01-01-2021 12:00 AM".

**Comment by pdilillo** [comment]
Upvoting the AM/PM issue.  It seems like the under hood the arrow pressed is always incrementing the time value by 12 and down arrow is always decrementing the time value by 12.

**Comment by Xizario** [comment]
Currently the behaviour is consistent for all of the parts. Increasing days will also increase the month, year. Same as minutes and hours. Changing the behaviour of the AM/PM to make it work as desirable is possible using the current implementation by handling the onChange callback
