### ISSUE TITLE
Stepper component animation not finishing on render

### ISSUE THREAD

**Issue by Cook1619** [telerik/kendo-react#836]
Stepper Component animation is not finishing on safari desktop and mobile. I'm referring to the blue line between steps, it stops half-way through between steps.

## I'm submitting a...
Bug

## Current behavior
 Opening your docs on safari yields this result https://www.telerik.com/kendo-react-ui/components/layout/stepper/
When you click the next step the blue line only fills in halfway until an event happens it seems

## Expected behavior

I would expect the stepper to fill in without having an event happen

## Minimal reproduction of the problem with instructions
Open this in Safari https://www.telerik.com/kendo-react-ui/components/layout/stepper/ and click around the stepper component from cart to delivery address to payment, then click all the way back to cart, the line renders oddly the whole time.

```

Browser:
<!-- Leave only the browsers that you tested the issue with. -->
- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- Edge version XX

System:


<!-- Add any additional information that might be relevant. -->

**Comment by silviyaboteva** [comment]
The issue was fixed in the following versions of the Kendo Themes:
 - @progress/kendo-theme-bootstrap@4.31.0
 - @progress/kendo-theme-classic@0.11.0
 - @progress/kendo-theme-default@4.33.0
 - @progress/kendo-theme-material@3.29.0
