### ISSUE TITLE
DropDownList doesn't scroll to the selected item correctly when popup is opened

### ISSUE THREAD

**Issue by arthurkok2** [telerik/kendo-react#838]
## I'm submitting a...

Bug report

## Current behavior
See: https://stackblitz.com/edit/react-pnyftb?file=app/main.jsx
After selection, opening the drop down again will not bring you to the right item.
The kendo control right now uses the height of the first item, and assumes that height for all other items in the list.
When it tries to scroll to the selected item, it uses this height to calculate the offset, but if you have any mutli-lined item in the list, the offset is calculated incorrectly.

## Expected behavior
It should scroll to the correct item in the list

## Minimal reproduction of the problem with instructions
See: https://stackblitz.com/edit/react-pnyftb?file=app/main.jsx

## Environment

Package versions:
@progress/kendo-react-dropdowns 4.3.0

Browser:
Any

**Comment by nstoychev** [comment]
Fixed in 4.6.0 - https://stackblitz.com/edit/react-pnyftb-ui54pv?file=app/main.jsx
