### ISSUE TITLE
ComboBox suggestions do not work when also filtering

### ISSUE THREAD

**Issue by thejroberts** [telerik/kendo-react#84]
## I'm submitting a...

* Regression report 

## Current behavior
**ComboBox**: When using both [suggestions](https://www.telerik.com/kendo-react-ui/components/dropdowns/combobox/suggestions/) and [filtering](https://www.telerik.com/kendo-react-ui/components/dropdowns/combobox/filtering/), part of the suggested text is left in the filter text box leading to the selection being cleared when focus is lost due to keyboard navigation.

## Expected behavior
The ComboBox should maintain the selection when focus is lost. Suggested text should be removed/ignored when an item is selected by keyboard.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-s5aths
https://react-s5aths.stackblitz.io

1. Type "x" in the filter text box.
2. Press the "down" arrow key to select "X-Large"
3. Notice the suggested text ("-Large") does not clear -- it is appended to the text.
4. Press "tab" to remove focus.
5. Notice the selection is cleared.

Browser:

- Chrome (desktop) version 68.0.3440.106

System:
- Platform:  Windows

## Notes

 This worked prior to the 2.0 release.

**Comment by nstoychev** [comment]
@thejroberts - we have published a fix in our development channel, under a @dev tag. Please refer to the following [article](https://www.telerik.com/kendo-react-ui/components/installation/development-builds/) on how to obtain the development builds.

**Comment by nstoychev** [comment]
Fixed in version [2.1.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/).
