### ISSUE TITLE
PanelBar Item - is it possible for expand collapse not unmounting the content inside?

### ISSUE THREAD

**Issue by Phibee** [telerik/kendo-react#840]
Is it possible we can only hide or show the content?

**Comment by simonssspirit** [comment]
This will be possible when we add a similar option for the PanelBar item:

https://www.telerik.com/kendo-react-ui/components/layout/api/TabStripProps/#toc-keeptabsmounted

I will mark this as an improvement and we will plan it based on the interest in it and the current workload.

**Comment by simonssspirit** [comment]
requested again in 1525981

**Comment by simonssspirit** [comment]
requested again in 1526335

**Comment by kspeyanski** [comment]
We've added the `keepItemsMountet` property to the PanelBar with version `4.11.0` of the `@progress/kendo-react-layout` package. Check the full changelog here: https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#be637ab5-74d0-5d30-b4cb-ecf78c7a32f2

I'm going to close this for now, but please let us know if you have any feedback about the feature.
