### ISSUE TITLE
<input> elements inside Sortable items cannot be focused because the items are draggable

### ISSUE THREAD

**Issue by arthurkok2** [telerik/kendo-react#842]
## I'm submitting a...
Bug

## Current behavior
If the sortable items being sorted contains <input>, they seem to be un-selectable, you cannot drag you mouse to make a selection inside the input

## Expected behavior
I should be able to select the text within the input

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-m4fr7k-ektdcz?file=app/main.jsx

## What is the motivation or use case for changing the behavior?
Poor user experience

## Environment

Package versions:
@progress/kendo-react-sortable 4.3.0

It seems that it needs the 'ignore' property similar to what's available in the jQuery version of Draggable

**Comment by Xizario** [comment]
The Ignore property sounds good, we should make this for the TileLayout as well

**Comment by Xizario** [comment]
In 4.8.0 dev the issue is fixed for the Sortable, and there is callback for the TileLayout that allows custom elements filtration
