### ISSUE TITLE
The events of the wrapper components that are not propagated correctly in React 17+

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#843]
The events of the wrapper components that are not propagated correctly in React 17+

Due to the changes introduced in React 17 events handling, the event attaches in the jQuery components used in the wrappers are not registered by React.

https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation

https://github.com/telerik/kendo-react-private/issues/1252

**Comment by simonssspirit** [comment]
reported again in 1514106

**Comment by mpirritano** [comment]
Any update on this?  It seems to only affect the window component (even the Kendo Schedule wrapper is working in react 17+)

**Comment by kdikov82** [comment]
Closing due to the deprecation of the wrappers
