### ISSUE TITLE
TileLayout Controlling the Position demo uses an undefined argument.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#844]
TileLayout Controlling the Position demo uses an undefined argument.

The demo uses `e.positions` where the correct argument is value.

**Comment by silviyaboteva** [comment]
Fixed in `4.6.0`. Link to the demo: https://www.telerik.com/kendo-react-ui/components/layout/tilelayout/tiles/#toc-controlling-the-position.
