### ISSUE TITLE
Overlaping items inside `WeekView` of the Scheduler

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#845]
In the following example, the items are not being shifted into the correct spot even when there is space. The item `Should not overlap` is sitting on top of another calendar item incorrectly:
[First Example](https://stackblitz.com/edit/react-u6wxmh-tjq5ou?file=package.json)

If we add one more day to `painting exterior 2` event, then there is no longer room in the top row and everything renders properly:
[Second Example](https://stackblitz.com/edit/react-u6wxmh-c8tgvt?file=app%2Fmain.jsx)

**Comment by kspeyanski** [comment]
The issue was fixed with version [`4.6.0`](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#26c39813-d3c9-50c9-9c29-f7078015de40) of the `@progress/kendo-react-scheduler` package.
