### ISSUE TITLE
Add the children prop to the components interfaces.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#848]
Add the children prop to the component's interfaces.

Since a recent change in the typings, children prop is not automatically added to the component's interfaces.

````
// React.Props<T> is now deprecated, which means that the `children`
 // property is not available on `P` by default, even though you can
 // always pass children as variadic arguments to `createElement`.
 // In the future, if we can define its call signature conditionally
 // on the existence of `children` in `P`, then we should remove this.
 readonly props: Readonly<P> & Readonly<{ children?: ReactNode }>;
````

**Comment by nstoychev** [comment]
Added in 5.3.0 and [v5.4.0-dev.202206081230](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#8b42fed6-2eb1-5d89-9562-bc60e8e659a0).
