### ISSUE TITLE
Add support for time in the DateRangePicker component.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#85]
Add support for "time" change in the DateRangePicker component.

Currently, the component value does not update if the time portion of the value is changed.

Please share your thoughts on this one.

**Comment by kspeyanski** [comment]
This is an interesting scenario, since the component is really called `DateRangePicker` and not `DateTimeRangePicker`, we can probably allow time format in the `DateInput`.

I'll prepare a PR!

**Comment by kspeyanski** [comment]
The fix has been published in version [2.5.0](https://www.npmjs.com/package/@progress/kendo-react-dateinputs) of `@progress/kendo-react-dateinputs`
