### ISSUE TITLE
TreeList does not apply the column width provided in the columns collection.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#850]
TreeList does not apply the column provided in the columns collection.

This can be seen in our demo:

https://www.telerik.com/kendo-react-ui/components/treelist/filtering/

Open the browser dev tools, inspect the columns, and noticed that none of them have the width that is set in the columns collection.

**Comment by Xizario** [comment]
It is about the particular configuration, and the reasoning behind is that people want to be able to set columns in percentages as well. You may see that the defined column width is not in pixels in the demo. We clearly need to expand the documentation with all the possible configurations and explanations when and how to use them, the TreeList header is a bit more flexible to the Grids, but it comes with additional details that need to be taken into account.

**Comment by simonssspirit** [comment]
This is explained here: https://www.telerik.com/kendo-react-ui/components/treelist/columns/widths/

The issue is in the demos where we use 200 instead of 200px. In the Grid setting, 200 is equivalent to setting 200px, where in the TreeList it has to be set explicitly.

We will update all demos of the TreeList to use px instead of numeric values.

**Comment by simonssspirit** [comment]
Fixed for all demos in dev https://www.telerik.com/kendo-react-ui-develop/components/treelist
