### ISSUE TITLE
The disabled property of the Date Picker is not changed dynamically based on the state value.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#86]
The disabled property of the Date Picker is not changed dynamically based on the state value.

The issue can be observed here: https://stackblitz.com/edit/react-3hsjfn?file=app/main.js

This was working in the 1.2 version of the component.

**Comment by nstoychev** [comment]
We have published a fix in our dev channel: https://www.npmjs.com/package/@progress/kendo-react-grid/v/2.2.0-dev.201810091021. Please refer to [this article](https://www.telerik.com/kendo-react-ui/components/installation/development-builds/) on how to obtain the development builds.

**Comment by kspeyanski** [comment]
The fix is not published in `v2.2.0` of `@progress/kendo-react-dateinputs`.
Changelog is [here](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#toc-bug-fixes)!
