### ISSUE TITLE
Scheduler custom editor is not applied in TimeLineView.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#860]
Scheduler custom editor is not applied in TimeLineView.

In the following demo, edit an item in DayView and then inside a TimeLineView and notice how the custom form is only shown for the DayView:

https://stackblitz.com/edit/react-aenms2-ftynbe?file=app/main.jsx

**Comment by simonssspirit** [comment]
reported again in 1511719

raising priority.

**Comment by kspeyanski** [comment]
The issue have been solved in the latest `dev` version of the `@progress/kendo-react-scheduler` package:
https://stackblitz.com/edit/react-aenms2-qhu873?file=app/main.jsx

For more information about obtaining development versions of the kendo packages, please refer to the [Obtaining Development Builds](https://www.telerik.com/kendo-react-ui/components/installation/development-builds/) article.

**Comment by Achill113** [comment]
@kspeyanski will this be entering a production build anytime in the near future?
