### ISSUE TITLE
Virtual Grid flickering when scrolling fast.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#861]
Virtual Grid flickering when scrolling fast.

The Grid content will shortly disappear (leave blank Grid) when scrolling fast.

The Grid should have visible records when scrolling (unless they are not received from the server). The case is for virtual scrolling with local data.

Use the demo and scroll very fast with the scrollbar and notice how the Grid is blank:

https://www.telerik.com/kendo-react-ui/components/grid/scroll-modes/virtual/

**Comment by dinomono** [comment]
Hi @simonssspirit, do you have an estimate when this will be done? This behaviour is better visible if you have more cells with custom rendering.

**Comment by nstoychev** [comment]
We published improvements in virtual scrolling and grid's performance in 5.11.0 - 5.12.0 versions.

If you still experience the issue, consider to add [debouncing of the pageChange event](https://www.telerik.com/kendo-react-ui/components/grid/scroll-modes/virtual/#toc-debouncing-pagechange-events).
