### ISSUE TITLE
Grid Firefox - Header text is selected when dragging a column for reordering.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#866]
Grid Firefox - Header text is selected when dragging a column for reordering.

This can be observed in our demo:

https://www.telerik.com/kendo-react-ui/components/grid/columns/reordering/

It could be connected to this issue as well: https://github.com/telerik/kendo-react/issues/773

**Comment by silviyaboteva** [comment]
Fixed in [`v4.5.0`](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#0efc49cf-fb41-5e8f-9773-5fc4a4663e58).
