### ISSUE TITLE
NumericTextBox typo in API reference

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-react#870]
https://www.telerik.com/kendo-react-ui/components/inputs/api/NumericTextBoxProps/#toc-format
The format can't be `null`. It is  `string | NumberFormatOptions`
Currently description says:
>If set to null or undefined, the default format will be used.

However setting it to null throws and error, the possible options are empty string or undefined.

**Comment by nstoychev** [comment]
Fixed in dev channel: https://www.telerik.com/kendo-react-ui-develop/components/inputs/api/NumericTextBoxProps/#toc-format
