### ISSUE TITLE
MultiSelect footer issue

### ISSUE THREAD

**Issue by matko-antunovic** [telerik/kendo-react#876]
MultiSelect footer feature is collapsing dropdown and not registering onClick event

https://stackblitz.com/edit/react-dq7cf3?file=app/main.jsx

**Comment by nstoychev** [comment]
The MultiSelect input has been blurred once you click on the footer and that's why the dropdown's collapsing. Preventing the mousedown event of the footer will resolve this - https://stackblitz.com/edit/react-dq7cf3-llkn5q?file=app/main.jsx.

**Comment by nstoychev** [comment]
@matko-antunovic I am closing this issue. In case of any questions, feel free to reopen it.
