### ISSUE TITLE
`Applying a mismatched transaction` error is shown in an empty Editor after using the InsertTable (Editon in Form)

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#877]
`Applying a mismatched transaction` error is shown in an empty Editor after using the InsertTable (Editon in Form)

The error is reproducible when using the controlled mode of the Editor inside a Form component and the Editor is empty:

https://stackblitz.com/edit/react-66ct4c-q6gygg?file=app/main.jsx

This is also predictable in a local example. More example and local example can be seen in the ticket 1507154

**Comment by nstoychev** [comment]
@simonssspirit - The problem is that the first `value` passed to the editor is `undefined`.  If the editor is used in controlled mode, its value prop should not be undefined.

```jsx
const MyCustomEditor = (fieldRenderProps) => {
    const {value = '', onChange, visited, validationMessage, valid} = fieldRenderProps;
```

Example: https://stackblitz.com/edit/react-66ct4c-vfmwt4?file=app/main.jsx

**Comment by nstoychev** [comment]
@simonssspirit no need to document this. The `value` prop of every react component in controlled mode should not be undefined.
