### ISSUE TITLE
ComboBox does not capture click event

### ISSUE THREAD

**Issue by thejroberts** [telerik/kendo-react#88]
## I'm submitting a...

Bug report 

## Current behavior
Clicking on the ComboBox button to open the dropdown propagates a click event to the ancestors.

## Expected behavior
The click event should be captured and not allowed to propagate.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-xsw138
https://react-xsw138.stackblitz.io

1. Click on the dropdown button.
2. Notice that the parent DIV's click event handler is fired (logs a message in the event log).

**Comment by Xizario** [comment]
I don't see a reason to stop the propagation.

**Comment by thejroberts** [comment]
I was under the (mistaken) impression that native dropdown elements prevent the click from propagating. Since it appears that is not the case, I agree. It doesn't make sense to capture the click event.
