### ISSUE TITLE
UI glitch with the search box/icon in grid filter menu

### ISSUE THREAD

**Issue by dtopuzov** [telerik/kendo-react#880]
## Bug report

There is a UI glitch with the search box/icon in the grid filter menu

## Current behavior
Search icon is below the input, over the separator
![image](https://user-images.githubusercontent.com/6651651/110075283-3a7b0900-7d8b-11eb-8113-44306f407b56.png)

## Expected behavior
Search icon to be on the same row as the input

## Minimal reproduction of the problem with instructions

1. Go to https://www.telerik.com/kendo-react-ui/components/grid/filtering/
2. Scroll to `Column Menu Filter` example
3. Click on `ProductName` filter icon

## Environment

Official demos, tested on 05.03.2021.

## Browser:
All

**Comment by simonssspirit** [comment]
@dtopuzov 

This is already logged in the theme and the progress can be monitored there as well: https://github.com/telerik/kendo-themes/issues/2277

**Comment by silviyaboteva** [comment]
Fixed in `4.6.0`. Link to the demo: https://www.telerik.com/kendo-react-ui/components/grid/filtering/#toc-column-menu-filter.
