### ISSUE TITLE
Editor raises an error on enter key

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-react#881]
The error is "RangeError: Can not convert <> to a Fragment (looks like multiple versions of prosemirror-model were loaded)".

Currently, it happens on the [KendoReact website](https://www.telerik.com/kendo-react-ui/components/editor/plugins/#toc-input-rules). If you open an example in StackBlitz, download it and run it locally, you will see that it works as expected. The error happens when different versions of [ProseMirror packages](https://www.telerik.com/kendo-react-ui/components/editor/get-started/#toc-dependencies) are loaded.

To prevent this error in your app, use the ProseMirror stuff from the '@progress/kendo-editor-common' package and install the same version as it is pointed in the editor's package.json file. For example, [for version 4.4.0., you should install version 1.1.5. of '@progress/kendo-editor-common'](https://unpkg.com/browse/@progress/kendo-react-editor@4.4.0/package.json). If you don't need to use the ProseMirror stuff to customize or extend the editor's functionality, you will not get such an error.

If you use yarn, define all the [ProseMirror packages](https://unpkg.com/browse/@progress/kendo-editor-common@1.1.6/package.json) versions in the [`resolutions`](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) section in package.json file.

![image](https://user-images.githubusercontent.com/13251479/110090901-808e9780-7da0-11eb-8724-ab50f75aafe2.png)

**Comment by dyabol** [comment]
Im using:
`
"@progress/kendo-editor-common": "1.1.5",
"@progress/kendo-react-editor": "4.4.0",
`
but error still persists.

**Comment by nstoychev** [comment]
@dyabol - Here is an example - [editor-yarn.zip](https://github.com/telerik/kendo-react/files/6502790/editor-yarn.zip). To run it, type `yarn install && yarn start` in the terminal. It uses `"@progress/kendo-editor-common": "1.1.7"` and `"@progress/kendo-react-editor": "4.6.0"`.

**Comment by simonssspirit** [comment]
we made a kb for this: https://www.telerik.com/kendo-react-ui-develop/knowledge-base/editor-error-on-enter-press/
