### ISSUE TITLE
Zooming the Bubble Chart to the end, will prevent it to zoom back out.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#883]
Zooming the Bubble Chart to the end will prevent it to zoom back out.

In the example, zoom in to the end, then try to zoon out and noticed the share are not visible:

https://stackblitz.com/edit/react-5vas7k-xvflht?file=app%2Fmain.jsx

The same is observed in the Angular version on the Chart:

https://stackblitz.com/edit/angular-og8act?file=app/app.component.ts

**Comment by jberrydev** [comment]
This was also noticed in React version.

**Comment by kdikov82** [comment]
The issue seems to be resolved in version 5.10.0:
https://stackblitz.com/edit/react-kzth3d?file=app%2Fmain.jsx
