### ISSUE TITLE
DatePicker issue with onFocus & onBlur

### ISSUE THREAD

**Issue by Nodios** [telerik/kendo-react#885]
https://stackblitz.com/edit/react-rnshrn?file=app/main.jsx

If you add onFocus and onBlur like in the example, you can't close calendar. You can only close it if you click outside current window.

**Comment by kspeyanski** [comment]
Hello @Nodios,

The reason you are experiencing this behavior is due to the propagation of the focus event from any internal component up to the `DatePicker`. From the provided description, what you aim to achieve is a `onFocusIn`/`onFocusOut` events, which are currently not supported in react. You can read more about them in the following issue: https://github.com/facebook/react/issues/6410

Please check out the following stackblitz example, where the `blur` event is called only once, and not every time a `blur` event propagates to the `DatePicker`:
https://stackblitz.com/edit/react-rnshrn-u8tuv7?file=app/main.jsx

I'm closing this issue for now, but please let me know if i can help you further.

**Comment by Nodios** [comment]
Hi @kspeyanski, 
I'd say this is an issue. If you look at the console, every time you click anywhere on the page, the element loses focus and then gains it back. What I want is an option to transparently add onFocus and onBlur without having to implement hacks around DatePicker internal logic.

**Comment by kspeyanski** [comment]
Hello @Nodios ,

Thank you for getting back to me. I'm always up for a discussion. 

If we are to add this behavior in some form of a callback, it would not be with the `onFocus` and `onBlur` names, but rather `onFocusIn` and `onFocusOut`. We are passing the exact same callbacks to the top-most react element in the DatePicker, and no further manipulation is done apart from attaching a `target`. 

To summarise it, this is how react handles the `onFocus`/`onBlur` events, and we do not apply any additional logic around them so they are as transparent as possible. 

If you would like to avoid writing the `hack` yourself, we've exposed the exact same behaviour in a standalone `hook` called [useAsyncFocusBlur](https://www.telerik.com/kendo-react-ui/components/utils/api/useAsyncFocusBlur/). It aims to resolve this exact problem we're facing with react's handling of `focus`/`blur` events. 

As always, let me know what you think, and we would consider it as part of a future version of `@progress/kendo-react-dateinputs` package.

**Comment by Nodios** [comment]
@kspeyanski
The desired functionality is onFocus to be called when you focus the element and onBlur when you lose focus. From my(developer) perspective I shouldn't worry about inner components(nor inner workings). In that way, your onFocus and onBlur callbacks are not really transparent. 

Bear in mind that if you don't attach onFocus/onBlur callbacks the component works as expected.

**Comment by kspeyanski** [comment]
@Nodios ,

I completely agree that attaching an `onFocus`/`onBlur` events should not intervene on how the components works. We're already working on a fix and i will be updating this issue once we have it ready.

I also agree that receiving `focus` and `blur` events only when the whole component receives/loses focus is the most intuitive behavior to a developer. Please allow me to try to showcase to you what i mean by saying that `we do not manipulate the onFocus and onBlur` events.

https://stackblitz.com/edit/react-rnshrn-n5zyck?file=app/main.jsx

In the example bellow, the `onFocus` and `onBlur` events are attacked to the parent `div` element. Whenever we click the first button we receive a `focus`, which is expected. However, when we click the second button, consecutive `blur` and `focus` events are thrown, even tho the focus never left the parent.

I'm in no way trying to argue that the described behavior is ideal, i'm just trying to argument the decisions we made for the DatePicker component.

Please let me know of any feedback you have.
