### ISSUE TITLE
Disable Grid scroll sync timeout for horizontal scroll and row virtualization.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#886]
Disable Grid scroll sync timeout for horizontal scroll and row virtualization.

Currently, when the row virtualization is on even if the user scrolls only horizontally we will sync the scroll with a small detail, which is only needed for the vertical scroll.

We should detect the scroll type (horizontal/vertical) and use the sync timeout only for vertical scrolling.

**Comment by nstoychev** [comment]
The virtual scroll has been refactored in 5.12.0 and scroll sync is removed.
