### ISSUE TITLE
Pressing Enter in the Grid ColumnMenu sort the column instead of submitting the form.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#888]
Pressing Enter in the Grid ColumnMenu sort the column instead of submitting the form.

This was working as expected in version 4.0.0

**Comment by kkapitanova** [comment]
reported again in 1517173

**Comment by simonssspirit** [comment]
reported again in 1519356 rasing priority

**Comment by ja321** [comment]
Any update on this issue?

**Comment by mdc-17** [comment]
Hi! Any update on this issue?

**Comment by simonssspirit** [comment]
I have now added this to our ToDo list. We will update the issue once we are a fix on a PR.

**Comment by nstoychev** [comment]
Fixed in [v4.11.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#be637ab5-74d0-5d30-b4cb-ecf78c7a32f2).
