### ISSUE TITLE
DropDownList valueField property was removed

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#89]
## I'm submitting a...
* Regression report
* Suggestion for improvement

## Current behavior
Dropdownlist no longer displays text based on ID on load, and changing the value causes errors in our application. This is due to the valueField property being removed which we were using heavily.

## Expected behavior
valueField or some equivalent being re-implemented.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-s5mclz

## What is the motivation or use case for changing the behavior?
We have a form which loads data from the database to be edited. We often have 'reference' fields e.g Foreign Keys. We allow our users to change these using a drop down list with the valid options. This has become more difficult since the removal of the valueField option.

It's definitely possible to work around this issue but it seems like a strange choice to remove the property.

## Environment
Browser:
- Chrome (desktop) Version 69.0.3497.100 (Official Build) (64-bit)

System:
- Node version: v8.9.3
- NPM version: 6.4.1
- Platform:  Windows

**Comment by Xizario** [comment]
After second look on your stackblitz example I see the trouble. The second `input` will not be needed if the `select` element and it's `option` had the correct key and values, and that seems the real issue.

**Comment by nstoychev** [comment]
We have released a [valueMap](https://www.telerik.com/kendo-react-ui/components/dropdowns/api/DropDownListProps/#toc-valuemap) prop to handle the case. Here it is in action: https://stackblitz.com/edit/react-s5mclz-2lkmj6?file=app%2Fmain.js. 

It can also be combined with the [withValueField](https://www.telerik.com/kendo-react-ui/components/dropdowns/dropdownlist/common-scenarios/#toc-using-data-fields-for-values) Higher-Order Component shown in our examples: https://stackblitz.com/edit/react-s5mclz-tfqlrk?file=app%2Fmain.js

**Comment by GeoMarkou** [comment]
Thank you, this property is perfect for our foreign key fields.
