### ISSUE TITLE
DatePicker scroll container when zooming in and out

### ISSUE THREAD

**Issue by AndrewGoupil** [telerik/kendo-react#890]
transform: translateY is set on the Calendar table element that's within k-calendar-view div. If opened individually at each different zoom, the value is the same, but if you keep the calendar open and zoom in then zoom out this value gets recalculated.

Reproducing this bug:
- With Calendar open, zoom in 300% and zoom out 100% (Edge, Chrome, Safari), not reproducible on Firefox. 
- After zooming in then back out the Calendar view will have scrolled, and previous month will come into view

Before starting scroll in, scroll out:
![image](https://user-images.githubusercontent.com/9603370/112010208-7d640d00-8afd-11eb-8c48-ec469b879153.png)

After:
![image](https://user-images.githubusercontent.com/9603370/112010157-70dfb480-8afd-11eb-96f6-5ab511b0bdaa.png)

Just as reference in my scenario at render transform was set to
transform: translateY(337300px);

Afterwards:
transform: translateY(336836px);

**Comment by Xizario** [comment]
Zooming affects the scroll position. Similar happens in the scrolled page when zoomed out/in even without any JS on the page.

You may want to use the other type of calendar that does not have scroll. Here is an example of it inside the DatePicker: https://www.telerik.com/kendo-react-ui/components/dateinputs/datepicker/custom-rendering/#toc-customizing-the-calendar
