### ISSUE TITLE
The Grid ColumnMenu icon should be part of the headerCell render.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#893]
The Grid ColumnMenu icon should be part of the headerCell render.

Currently, the icon is not part of the headerCell render.

This will allow customizing the icon.

**Comment by kdikov82** [comment]
The columnMenu icon is already part of the headerCell and can be used within a custom headerCell as shown in the following example:
https://stackblitz.com/edit/react-febfzz-vu4wcf?file=app%2Fmain.jsx
