### ISSUE TITLE
MultiColumnComboBox with single value has different column widths for the header and for the list

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#895]
An example of the behavior can be found here:
[https://stackblitz.com/edit/react-k97jyg?file=app/main.jsx](https://stackblitz.com/edit/react-k97jyg?file=app/main.jsx)

The issue is related to ticket: 1512728.

**Comment by jonteho** [comment]
Also, focus does not seem to work

https://stackblitz.com/edit/react-k97jyg-vkfrmc?file=app/main.jsx

**Comment by nstoychev** [comment]
@jonteho - Thanks, I'll check the focus as well.

**Comment by nstoychev** [comment]
Fixed in 4.6.0 - https://stackblitz.com/edit/react-k97jyg-pbu5gk?file=app/main.jsx,
and the focus as well - https://stackblitz.com/edit/react-k97jyg-qj2fvd?file=app/main.jsx.
