### ISSUE TITLE
TreeList / Multi-column headers doesn`t work / try to expand row!

### ISSUE THREAD

**Issue by skopalj** [telerik/kendo-react#896]
https://www.telerik.com/kendo-react-ui/components/treelist/columns/headers/

## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by aherncm** [comment]
We're having this problem too. Very obvious bug! Here's a stackblitz of an older version rendering properly:  https://stackblitz.com/edit/react-xp1chh-ywq79t?file=app%2Fmain.jsx

**Comment by nstoychev** [comment]
Thanks @skopalj @aherncm. The fix for this is on a Pull Request and will be merged in our dev channel in the next few days.

**Comment by nstoychev** [comment]
Fixed in 4.6.0
