### ISSUE TITLE
Can't enter "-" in NumericTextBox for Swedish locale

### ISSUE THREAD

**Issue by idrydi** [telerik/kendo-react#897]
## I'm submitting a...

* Bug report 

## Current behavior

When using `<IntlProvider locale="sv" >` it is not possible to enter "-" as the first character in the NumericTextBox (for negative values). It can however be added after typing the number or by using the spinner. If the locale is changed to "en" it is possible to enter "-" as the first character.

## Expected behavior

It should be possible to enter negative values in the Swedish locale similar to the English one, where you can type "-" as the first character.

## Minimal reproduction of the problem with instructions

  1. Use NumericTextBox inside  `<IntlProvider locale="sv" >`
  2. Try to type a negative value, with "-" as the first character
  3. The NumericTextBox remains empty

It can also be reproduced by changing the example at [https://www.telerik.com/kendo-react-ui/components/grid/globalization](https://www.telerik.com/kendo-react-ui/components/grid/globalization) in StackBlitz to use sv-SE locale instead of es-ES. The Spanish locale allows "-" as the first character in the filter for the UnitPrice column, while the Swedish locale does not.

## What is the motivation or use case for changing the behavior?

We want to be able to type in negative values in the Swedish locale similar to the English and Spanish ones.

## Environment

Browser:

- Chrome (desktop) version 89

**Comment by simonssspirit** [comment]
will be addressed with https://github.com/telerik/kendo-react/issues/913
