### ISSUE TITLE
Checkbox doesn't work with Formik

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-react#899]
## I'm submitting a...
* Bug report

## Current behavior
https://stackblitz.com/edit/react-teb6ld-ofnqzq?file=app/main.jsx

## Expected behavior
The value to be correctly updated.

**Comment by InaGlushkova** [comment]
The Checkbox component is working with Formik when the setup is correct.

But it is throwing the following warning:
_'Formik called `handleBlur`, but you forgot to pass an `id` or `name` attribute to your input:
undefined'_

For reference, please check:
https://stackblitz.com/edit/react-teb6ld-3ka1dh?file=app/main.jsx

**Comment by Xizario** [comment]
Fixed in 4.8.0
