### ISSUE TITLE
Fix DatePicker and DateInput manual input navigation

### ISSUE THREAD

**Issue by derekgreer** [telerik/kendo-react#900]
## I'm submitting a...

* Suggestion for improvement

Fix the react version of the datapicker just as this corrected the angular version: https://github.com/telerik/kendo-angular/issues/910

## Current behavior
Kendo DatePicker and DateInput, you go to type 02022020 and you get stuck on the month.  You have to use the arrows to navigate to the day, year fields.

## Expected behavior
Type in 02022020 and you get 02/02/2020 in the date input.

## What is the motivation or use case for changing the behavior?

Input is hard to use.  There is no way usability was done on this input and found to be the way most would want to manually type in a date.  Using arrows to navigate?  Really?  Absolutely no way anyone wants this.

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by Xizario** [comment]
It actually does not work in angular https://github.com/telerik/kendo-angular/issues/1814
Auto-switch of the parts is [purposely removed](https://github.com/telerik/kendo-react/issues/705) and we don't have plans to re-add it.
You don't need to use arrows, typing the separator or pressing space will move the active parts as well. So typing "02/02/2020" will work.

"02022020" is not formatted in the first place and even if MM/dd/yyyyy format is common it is still only a corner case, as the DateInput is made to support all formats in all cultures. Hardcoding navigation rules for single format and culture brakes others cultures and formats. 

There are alternatives: you can place MaskedTextBox, multiple Inputs, or Input with any custom logic inside the picker: https://www.telerik.com/kendo-react-ui/components/dateinputs/datepicker/custom-rendering/
