### ISSUE TITLE
Missing onSeriesLeave event of Charts

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-react#902]
React - https://www.telerik.com/kendo-react-ui/components/charts/api/ChartProps/
Angular version - https://stackblitz.com/edit/angular-h3vp63

**Comment by kdikov82** [comment]
https://github.com/telerik/kendo-react/issues/748

**Comment by kdikov82** [comment]
duplicated https://github.com/telerik/kendo-react/issues/748
