### ISSUE TITLE
Grid with optional column is not resized properly - so empty space appears when there should not be any.

### ISSUE THREAD

**Issue by ikos23** [telerik/kendo-react#905]
## I'm submitting a bug for Grid component

* Bug report 

## Current behavior
I have a grid with a column that is being rendered only when certain condition is TRUE - let's call it "an optional column". When this column is rendered - grid probably "recalculates" its width and that calculation is not correct - so some empty space appears (_maybe the whole Grid is not re-rendered in this case and that's why I am getting this_):

![image](https://user-images.githubusercontent.com/5758938/113919494-57708500-97ec-11eb-87fe-6bcaea286fbe.png)

I have checked markup generated by this component and noticed that style="width: 490px;" is added in my case - this is not something I set somewhere. 
```
<table tabindex="-1" class="k-grid-table" role="presentation" style="width: 490px;">
```

## Expected behavior
I'd say that having optional columns (rendered when some condition is true) for the grid is quite common case and this is often used feature - so **grid should works fine** in this case - optional column should appear/disappear and grid should re-render its structure properly without any empty space.

## Minimal reproduction of the problem with instructions

Demo is here : https://stackblitz.com/edit/react-asnisb-nxikp9?file=app%2Fmain.jsx

The code (check the demo) is as simple as this one:
```
<Grid
    style={{ height: "400px" }}
    className="my-grid"
    data={[...products]}
>
    {this.state.showIDCol && (<Column field="ProductID" title="ID" width="40px" />)}
    <Column field="ProductName" title="Name" width="250px" />
    <Column field="Category.CategoryName" title="CategoryName" />
    <Column field="UnitPrice" title="Price" width="100px" />
</Grid>
```

## What is the motivation or use case for changing the behavior?
Grid component is probably used by anyone who is using Kendo React. 
The described behavior is not acceptable.

## Environment

Package versions:
Any

Browser:
Any
I checked on latest Chrome

System:
Windows

**Comment by Xizario** [comment]
Fixed in 4.7.0
