### ISSUE TITLE
Add ability to disable dates in the DatePicker.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#91]
We can expose a Date render that will allow disabling dates based on specific criteria. This will also allow customizing the appearance of the date.

**Comment by ahitrov** [comment]
Can we have this for Calendar as well?

**Comment by Xizario** [comment]
I think the request is really about the Calendar itself, and not the DatePicker.

**Comment by bkniffler** [comment]
I think it would be nice to have a prop that would allow to add className to individual days, like dayClassName `date => "disabled"`, so we can add more stuff. Or onDayRender to control the markup of a day.

**Comment by bkniffler** [comment]
In fact, I think you guys should look at http://react-day-picker.js.org/ since that project has nice customization.

**Comment by kspeyanski** [comment]
Hello @bkniffler ,
We're working on a render prop for maximum customisability. 

As the Items of the calendar are not limited to `days`, (but also `months`,`years`,`decades`) due to the [active view feature](https://www.telerik.com/kendo-react-ui/components/dateinputs/calendar/active-view/), we will probably name it something different than `onDayRender`.

I will let you know once we have this feature published in our `dev` channel.

**Comment by kspeyanski** [comment]
The custom rendering of child components has been released in our `dev` channel. More info about it's usage can be found in the corresponding `Customization` articles of the components.

- [Calendar Custom Rendering](https://www.telerik.com/kendo-react-ui-develop/components/dateinputs/calendar/custom-rendering/#toc-customization)
- [DatePicker Custom Rendering](https://www.telerik.com/kendo-react-ui-develop/components/dateinputs/datepicker/custom-rendering/)
- [DateRangePicker Custom Rendering](https://www.telerik.com/kendo-react-ui-develop/components/dateinputs/daterangepicker/custom-rendering/)
- [MultiViewCalendar Custom Rendering](https://www.telerik.com/kendo-react-ui-develop/components/dateinputs/multiviewcalendar/custom-rendering/)

**Comment by Xizario** [comment]
`v2.6.0` is published.
