### ISSUE TITLE
DatePicker: Pass Additional Props to the Week Cell

### ISSUE THREAD

**Issue by kkapitanova** [telerik/kendo-react#910]
Add additional information in the props that are passed to the weekCell in the DatePicker, such as, for example, the date range of the current week, the first date of the current week, etc.

More details in ticket 1514608

**Comment by kspeyanski** [comment]
Additional `firstDate` property is now properly being passed to the `CalendarWeekCell`, since [`v4.6.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#26c39813-d3c9-50c9-9c29-f7078015de40) of the `@progress/kendo-react-dateinputs` package.
