### ISSUE TITLE
Scheduler MonthViewProps itemsPerSlot does does not work

### ISSUE THREAD

**Issue by jerome-smith** [telerik/kendo-react#911]
I'm submitting a bug

* Bug report 

## Current behaviour
Setting the value of itemsPerSlot has no effect on the view.
Docs state : "Sets the maximum number of items to be rendered in a single slot, before adding the show-more button."

## Expected behaviour
I should see more than 2 (two ) items for a given slot if there are more than 2 items present in the dataset.
Docs state : "Sets the maximum number of items to be rendered in a single slot, before adding the show-more button."

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/react-qqrl5q?file=app%2Fmain.jsx

## What is the motivation or use case for changing the behavior?

The expected behaviour does not exist and should exist i.e.  more than 2 items must be displayed when the property itemsPerSlot is passed to the MonthView component of the Scheduler.
Problem is reproducible on our demo site

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX

System:
- TypeScript version: 4.2.4 
- Node version: 14.6.1 and 7.9.0  
- Platform:  Mac

**Comment by kspeyanski** [comment]
Hello @jerome-smith 

The `itemsPerSlot` property is available in the [`v4.6.0@dev`](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#0c9c255c-0f72-5794-adff-f5a9e4f39baa) of the `@progress/kendo-react-scheduler` package and will soon be released as an official version. Please checkout the updated stackblitz example: 
https://stackblitz.com/edit/react-qqrl5q-7a9h39?file=app%2Fmain.jsx

For more information , please refer to the [Obtaining development build](https://www.telerik.com/kendo-react-ui/components/installation/development-builds/) article.
