### ISSUE TITLE
Buttons in the Filter component should be of type="button"

### ISSUE THREAD

**Issue by kkapitanova** [telerik/kendo-react#912]
The Buttons in the Filter component should be of type="button"
Currently, clicking those buttons trigger the ASP.NET PostBack: https://stackblitz.com/edit/react-mrg6oo-872na1?file=app%2Fmain.jsx 

Related to ticket 1514910

**Comment by nstoychev** [comment]
Fixed in 4.6.0 - https://stackblitz.com/edit/react-mrg6oo-2kc2s1?file=app%2Fmain.jsx
