### ISSUE TITLE
Fix DialogActionBar type

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#922]
Currently, we are setting the DialogActionBar to a Functional component type, and we are setting the props types directly to the props in the function instead directly to the component.

This:

````
export const DialogActionsBar: React.FunctionComponent = (props: DialogActionsBarProps): React.ReactElement<any> => {
````

Should become this:

````
export const DialogActionsBar: React.FunctionComponent<DialogActionsBarProps> = (props): React.ReactElement<any> => {
````

We should check if similar cases occur in order functional components.

**Comment by silviyaboteva** [comment]
As of `4.7.0-dev.202105181427` the type is fixed.
