### ISSUE TITLE
A Checkbox in Form stops updating visually (checked/unchecked)

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#925]
A checkbox in Form stops updating visually (checked/unchecked).

https://stackblitz.com/edit/react-ihwtcx?file=app/form-components.jsx

Click the Checkbox to check it, then try to uncheck it.

**Comment by simonssspirit** [comment]
reported again in 1521470

**Comment by simonssspirit** [comment]
reported again 1523144

**Comment by vladimirivanoviliev** [comment]
Please note that this behavior is related to the `input` element inside the Checkbox. When there is no initial value set (e.g.: Form component `initialValues`), supplied `undefined` value makes the component to start working as uncontrolled mode. We will look for solution and follow up in current thread. Until better solution is found, please make sure you set the initial value for the field bound to the checkboxes.

**Comment by InaGlushkova** [comment]
The fix can be found in the latest dev version - `v4.8.0-dev.202107231243`
