### ISSUE TITLE
Scheduler returns undefined as resource array.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#927]
Scheduler returns undefined as resource array.

https://stackblitz.com/edit/react-bhjlzf?file=app%2Fmain.jsx

Steps:
 - Create a new event
 - Choose two Persons in the Edit Form.
 - Save the Form.
 - Notice how personId is undefined

**Comment by kspeyanski** [comment]
The issue has been fixed in the latest `dev` version of `@progress/kendo-react-scheduler` package.
https://stackblitz.com/edit/react-bhjlzf-zrptea?file=app/main.jsx
