### ISSUE TITLE
Tabstrip inactive or hidden tab content initially not mounted or rendered

### ISSUE THREAD

**Issue by Phibee** [telerik/kendo-react#931]
Is there way we can accessed child elements of TabStrip?. Coz currently other tabs is hidden or not rendered so there's no way we can find elements inside that tab content unless tab was clicked.  Coz we're trying to move one tab to another were if there's an element with error/ required field inside that tab.

**Comment by Xizario** [comment]
It is up to the developer to place content inside the tabs, so he already know what each tab contains on app level.

**Comment by Tommuh** [comment]
Not sure if @Phibee means the same.

I have a problem where the other tabs content are not rendered. This obviously because they are hidden.
After clicking the tab the content gets initialized. But I want to initialize every tab at once because I need it for various reasons.

I use the property "keepTabsMounted" but those content containers are empty at start.
To overcome this I "extended" the original tabstrip so I can load all tabs by myself. It works for me but I do not know if this is the correct way to do it or that there is something I don't know yet?

```
import { useEffect, useState, cloneElement } from 'react';
import { TabStrip } from '@progress/kendo-react-layout';

export const Tabs = props => {
    const [selected, setSelected] = useState(0);
    const [index, setIndex] = useState(0);

    const setSelectedTab = event => {
        setSelected(event.selected);
    };

    const BasicProps = cloneElement({
        props: {            
            className: '',
            selected: selected,
            onSelect: setSelectedTab,
            keepTabsMounted: true,
            style: {
                visibility: ((index + 1) === props.children.length) ? 'visible' : 'hidden'
            }
        }
    }, props); 
    
    const handleRender = index => {        
        const nextIndex = (index + 1);
        
        if(nextIndex < props.children.length) {
            setSelected(nextIndex);
            setIndex(nextIndex);
        }
        else {
            setSelected(0);
        }
    };

    useEffect(() => {
        handleRender(index);        
    }, [index]);

    return (
        <TabStrip {...BasicProps.props}
                  className={BasicProps.props.className + ' selected-tab-' + selected}>
            {props.children}
        </TabStrip>
    );
};
```

**Comment by Phibee** [comment]
> Not sure if @Phibee means the same.
> 
> I have a problem where the other tabs content are not rendered. This obviously because they are hidden. After clicking the tab the content gets initialized. But I want to initialize every tab at once because I need it for various reasons.
> 
> I use the property "keepTabsMounted" but those content containers are empty at start. To overcome this I "extended" the original tabstrip so I can load all tabs by myself. It works for me but I do not know if this is the correct way to do it or that there is something I don't know yet?
> 
> ```
> import { useEffect, useState, cloneElement } from 'react';
> import { TabStrip } from '@progress/kendo-react-layout';
> 
> export const Tabs = props => {
>     const [selected, setSelected] = useState(0);
>     const [index, setIndex] = useState(0);
> 
>     const setSelectedTab = event => {
>         setSelected(event.selected);
>     };
> 
>     const BasicProps = cloneElement({
>         props: {            
>             className: '',
>             selected: selected,
>             onSelect: setSelectedTab,
>             keepTabsMounted: true,
>             style: {
>                 visibility: ((index + 1) === props.children.length) ? 'visible' : 'hidden'
>             }
>         }
>     }, props); 
>     
>     const handleRender = index => {        
>         const nextIndex = (index + 1);
>         
>         if(nextIndex < props.children.length) {
>             setSelected(nextIndex);
>             setIndex(nextIndex);
>         }
>         else {
>             setSelected(0);
>         }
>     };
> 
>     useEffect(() => {
>         handleRender(index);        
>     }, [index]);
> 
>     return (
>         <TabStrip {...BasicProps.props}
>                   className={BasicProps.props.className + ' selected-tab-' + selected}>
>             {props.children}
>         </TabStrip>
>     );
> };
> ```

Yes @Tommuh . same problem. coz i need to scan the element each tab item. I can't do that if not yet rendered all at once.  Here's the scenario, I need to get all inputs, dropdownlist, and etc. with `k-state-invalid`. but since other tabs is not yet rendered i cannot get it unless i clicked it first all tabs.

**Comment by silviyaboteva** [comment]
In order to render the content of all tabs on TabStrip's initialization and persist in the DOM no matter the current selection, set the [renderAllContent](https://www.telerik.com/kendo-react-ui-develop/components/layout/api/TabStripProps/#toc-renderallcontent/) property to `true`.

Duplicated issue: https://github.com/telerik/kendo-react/issues/1988#issuecomment-2020095833
