### ISSUE TITLE
Grid: getSelectedState is not exported from '@progress/kendo-react-grid' 

### ISSUE THREAD

**Issue by cr7yash** [telerik/kendo-react#934]
## I'm submitting a...
* Bug report 

## Current behavior
I am getting this error
```
Attempted import error: 'getSelectedState' is not exported from '@progress/kendo-react-grid'.
```
Every time I am importing getSelectedState in this line:
```
import {
  Grid,
  getSelectedState,
  GridColumn as Column,
  GridNoRecords,
} from "@progress/kendo-react-grid";
```
## Expected behavior
getSelectedState should be imported successfully

## Minimal reproduction of the problem with instructions
Download a sample [stackblitz example]( https://stackblitz.com/edit/react-r3fsfm?file=app/main.jsx) I am referring to. Unzip solution. No changes required, I got error from a box.
Run npm i
Run npm start
It shows- Attempted import error: 'getSelectedState' is not exported from '@progress/kendo-react-grid'.

## What is the motivation or use case for changing the behavior?
I am trying to implement multi select column cells as in the example

## Environment

Package versions:

```
"@progress/kendo-react-grid": "^3.6.0"
```

Browser:
- Edge Version 90.0.818.62 (Official build) (64-bit)

System:
- TypeScript version: not using
- Node version: v14.16.1
- Platform:  Windows 10 pro

**Comment by cr7yash** [comment]
https://stackblitz.com/run/?file=app/main.jsx

In the above example, I can only select one row at a time which is against the notion that I can select multiple rows. This example deletes the previous selection. I even tried with CTRL and SHIFT key.

**Comment by kkapitanova** [comment]
Hello, @cr7yash!
I see that you are using version 3.6.0 of the Grid, which is why this error occurs - getSelectedState is available with the latest version - 4.6.0. Please update the Grid to use that version and this issue should be sorted :)

**Comment by cr7yash** [comment]
Hi Kristina, I had sorted out that issue. I reopened with the issue of selection example that has been provided.

It doesn't allow multi checkbox selection which I have mentioned in my reopen comment.

**Comment by kkapitanova** [comment]
@cr7yash The example you have provided links to the main page of StackBlitz, could you please send the correct one so that I am able to investigate the issue?

**Comment by cr7yash** [comment]
This link might help you- https://stackblitz.com/edit/react-r3fsfm?file=app/main.jsx

**Comment by kkapitanova** [comment]
@cr7yash I believe that this is connected to the following issue: https://github.com/telerik/kendo-react/issues/937 which is why I will close this one, as there is alredy an issue made for this case and we will keep track of its progress there
