### ISSUE TITLE
[KB] [Grid] Add an example with Grid cell state editing.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#938]
Add an example with Grid cell state editing.

This can be used for performance optimization to update the entire Grid only when the user stops editing instead of one each keypress.

**Comment by simonssspirit** [comment]
follow up in ticket: 1518255

**Comment by Xizario** [comment]
Ideally 2 versions:
- Statefull cells that manage their own values.
- Fields inside the cells that are managed by Form

**Comment by simonssspirit** [comment]
This is the example with cells managing their own state: https://stackblitz.com/edit/react-78t8gs-zfvdz1?file=app%2Fmain.jsx
