### ISSUE TITLE
Checking state inside DropDownList handleChange returns old state

### ISSUE THREAD

**Issue by madani2010** [telerik/kendo-react#94]
Hi,
I followed the example at : 
https://www.telerik.com/kendo-react-ui/components/dropdowns/dropdownlist/binding/#toc-datasets-of-objects
If I try to do console.log(this.state) inside the handleChange method, I would get the old selected value.Adding setTimeout with 0 ms delay would work.Any idea why this is not working?
`handleChange = (event) => {
        this.setState({
            value: event.target.value
        });
        //this would give old state 
      console.log(JSON.stringify(this.state));
      // this works
 that = this;
setTimeout(function () {
          console.log(JSON.stringify(that.state));
      }, 0);
    }`

**Comment by nstoychev** [comment]
State update in React is async. See the following thread: https://stackoverflow.com/questions/36085726/why-is-setstate-in-reactjs-async-instead-of-sync
