### ISSUE TITLE
[BUG][DropDowns] popupSettings not working as expected

### ISSUE THREAD

**Issue by kkapitanova** [telerik/kendo-react#945]
The popupSettings do not apply some of the properties to certain components, for example:
- width is not applied to the DropDownTree's popup (reported in 1521089)
- height is not applied to all dropdowns' popups

This is visible in the following demo: https://stackblitz.com/edit/react-ty6qkx?file=app/main.jsx

**Comment by ksdc-andreo** [comment]
Are there any workarounds for this issue while it's being fixed?

**Comment by ksdc-andreo** [comment]
For anyone else having this issue, we found the following workaround:

```
<DropDownTree
    ...
    popupSettings={{ className: 'dropDownTree' }}
/>
```

using the following CSS:

```
.dropDownTree {
  width: 400px !important;
  height: 650px !important;
  overflow: auto !important;
}
```

**Comment by simonssspirit** [comment]
reported again in 1559018 for DropDownTree's

**Comment by vveesseelliinnaa** [comment]
Reported again in Ticket ID: 1578471 (for MultiSelect)

**Comment by vveesseelliinnaa** [comment]
Reported again in Ticket ID: 1583249

**Comment by WissamProgress** [comment]
Reported in Ticket ID: 1602612

**Comment by ppseafield** [comment]
I've also noticed this in MultiSelectTree.

**Comment by WissamProgress** [comment]
Reported in Ticket ID: 1623884

**Comment by surajts** [comment]
Is it possible to up the priority for this bug? This is a show stopper for us.

**Comment by WissamProgress** [comment]
@surajts I increased this bug's priority based on the number of times it was reported (9 times). It is now among the top 10 bugs with the highest priority.

**Comment by WissamProgress** [comment]
Reported in Ticket ID: 1638197 for the MultiSelectTree
