### ISSUE TITLE
Use MultiColumnComboBox with Formik

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#950]
MultiColumnComboBox is giving the following error:

Warning: Formik called `handleChange`, but you forgot to pass an `id` or `name` attribute to your input:
    undefined..

For more information: 
[https://stackblitz.com/edit/react-cgbtoa-mmoibf?file=app/main.jsx](https://stackblitz.com/edit/react-cgbtoa-mmoibf?file=app/main.jsx)

ComboBox behavior:
[https://stackblitz.com/edit/react-cgbtoa?file=app/main.jsx](https://stackblitz.com/edit/react-cgbtoa?file=app/main.jsx)

Reported under: 1521297.

**Comment by Xizario** [comment]
The `name` getter is available in v4.7.0-dev.202106010659 version,

**Comment by Xizario** [comment]
Fixed in 4.7.0
