### ISSUE TITLE
Resizable breaks when used along with selectable.

### ISSUE THREAD

**Issue by vaisakhcp** [telerik/kendo-react#956]
I am using kendo grid to create a table with resizable property. When I added selectable enabled, resizable seems to be breaking when I reduce a column size. The size of the headers was not in align with size of the column data. A screenshot for the same is attached here.
The version of kendo I am using is 4.6.0.
Options I have used is 
`resizable={true}
    selectable={{
      enabled: true,
      drag: dragEnabled,
      cell: cellEnabled,
      mode: selectionMode
    }}`
![Screenshot (396)](https://user-images.githubusercontent.com/9795456/120341850-ded20480-c314-11eb-927d-b1d7b14f48c2.png)

**Comment by Xizario** [comment]
Fixed in latest dev 4.7.0-dev.202106090653 https://stackblitz.com/edit/react-h2vs1s?file=app/main.jsx
