### ISSUE TITLE
Provide an option to customize the ColumnMenu from the headerCellRender or headerCell props.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#957]
Provide an option to customize the ColumnMenu from the headerCellRender or headerCell props.

Currently, even if one of those props is used to customize the rendering of the header, the column menu element will still be rendered even if we do not return it from the render props:

https://stackblitz.com/edit/react-s5jydi?file=app/main.jsx

**Comment by simonssspirit** [comment]
requested again in 1522575

**Comment by simonssspirit** [comment]
requested again in 1522596

**Comment by simonssspirit** [comment]
requested again in 1530508

**Comment by rebmullin** [comment]
After reading the docs, as far as I can tell, we can't override the markup for the Menu (the 3 dots which opens the ColumnMenu). Ideally, if we could make this a button and add an onKeyDown event which can also open the menu I believe that would help make this more accessible. Right now I can't seem to open this unless I click on this menu. I see it's marked as an enhancement which is great but is there a way to get an idea of when this will be added?

**Comment by simonssspirit** [comment]
@rebmullin Yes, this is correct. At this point, the headerCellRender only provides the render for the text. This is why we have added this item to the extent the functionality and allow achieving cases like the one you have described.

**Comment by kdikov82** [comment]
Requested ColumnMenu position change in ticket 1542843

**Comment by vladimirivanoviliev** [comment]
This is now possible with latest changes in rendering of the column menu and exposing the new `GridColumnMenuWrapper`. Please check the following post for more information:
- https://github.com/telerik/kendo-react/issues/1123#issuecomment-976285794
