### ISSUE TITLE
Font sizes/weight not being maintained in Kendo-react-pdf

### ISSUE THREAD

**Issue by SarathSantoshDamaraju** [telerik/kendo-react#958]
## I'm submitting a...
* Bug report 

## Current behavior
 When you try to export fonts with **different sizes and weights** by the `kendo-react-pdf`. All fonts are exported in a same size and weight in the PDF. I am not using any external fonts, but even without external fonts, i was expecting the fonts with given size should be exported. 

## Expected behavior
Export fonts with size and weight styles

## Minimal reproduction of the problem with instructions
[reproduction url](https://react-3hvfaj.stackblitz.io)
- Set a font size to any text and
- try exporting

## What is the motivation or use case for changing the behavior?
To maintain the typography styles in the exported pdf.

## Environment

Package versions:
```
    "@progress/kendo-drawing": "^1.10.1",
    "@progress/kendo-licensing": "^1.1.4",
    "@progress/kendo-react-pdf": "^4.6.0",
```

Browser:
- Any browser

System:
- TypeScript version: ^4.2.4
- Node version: v16.0.0
- Platform:  Mac

**Comment by Xizario** [comment]
The .k-pdf-export class that comes with some default font-size is added to the wrapped content during the export. If you want font-size to the exported document to match this of the page, use styles with higher specificity in the page. 
Here is simplified version of your app that export the 2 paragraphs exactly as visible on the screen:
https://stackblitz.com/edit/react-3hvfaj-wwjmxc?file=app%2Fmain.jsx

@simonssspirit, can you update the https://www.telerik.com/kendo-react-ui/components/pdfprocessing/content-styling/ article to contain a bit more details.

**Comment by prabha024** [comment]
@SarathSantoshDamaraju i am also facing the same issue. have you fixed it?
