### ISSUE TITLE
Grid text filters throw error when changing comparison operator with no string

### ISSUE THREAD

**Issue by jmeyer11** [telerik/kendo-react#96]
## I'm submitting a...
* Bug report

## Current behavior
If you change the operator on a string filter without a string value populated you get the error Cannot read property 'replace' of null.

## Expected behavior
It should not throw an error and recognize it as an null string.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-byxuyp?file=app/main.js
this is a direct copy of the demo on your site. Change the operator on the product name column without any text in the textbox and an error is thrown.

## What is the motivation or use case for changing the behavior?
Errors should not be thrown for no reason.

## Environment

Package versions:
reproducible on demo site.

Browser:

- Chrome (desktop) version 69

System:
reproducible on demo site.

**Comment by jmeyer11** [comment]
Only happens with "Contains", "Does not contain", "Starts with", and "Ends with"

**Comment by Xizario** [comment]
Fixed in `v2.3.0-dev.201810171100`

**Comment by Xizario** [comment]
`v2.3.0` is now live
