### ISSUE TITLE
Grid: Setting the Column width to 0 still makes that Column visible when grouping is made

### ISSUE THREAD

**Issue by kkapitanova** [telerik/kendo-react#960]
Setting the Column width to 0 still makes that Column visible when grouping is made

Reported in ticket 1523263

Visibile in the demo below - see how the width of the "ProductID" column is set to 0, however the column is fully visible when grouping is made, although the header for "ProductID" is not shown: 
https://stackblitz.com/edit/react-gztw62?file=app/main.jsx

Workaround available by setting the column width to "1px": 
https://stackblitz.com/edit/react-kk6phz?file=app/main.jsx

**Comment by kdikov82** [comment]
Seems to work as expected with version 5.10.0:
[https://stackblitz.com/edit/react-nxjmyh?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-nxjmyh?file=app%2Fmain.jsx)
