### ISSUE TITLE
The request for "data:font/ttf;base64" font when multiple Editor React wrappers are slow

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#97]
The request for "data:font/ttf;base64" font when multiple Editor React wrappers are slow. It takes 5-7 seconds compare less than a second for the standard jQuery version:

Wrapper: https://stackblitz.com/edit/react-bjv5s9?file=app%2Fmain.js
jQuery: https://dojo.telerik.com/oQaYoLiT/2

**Comment by Xizario** [comment]
Since we are having new pure Editor for react as 2.7.0, I am closing this wrappers related issue.
