### ISSUE TITLE
GridColumnMenuFilter the filter button has to be on the left side.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#970]
GridColumnMenuFilter the filter button has to be on the left side.

Currently, the button is on the right side:

![image](https://user-images.githubusercontent.com/11087921/122400350-4ed2c280-cf84-11eb-9e85-30bc91f43c68.png)

**Comment by kdikov82** [comment]
https://github.com/telerik/kendo-react/issues/1208
