### ISSUE TITLE
Scheduler, creating an event after business hours is not shown even after clicking 'SHOW FULL DAY' button.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#974]
Scheduler, creating an event after business hours is not shown even after clicking 'SHOW FULL DAY' button.

More details and a video can be seen in this forum post:

https://www.telerik.com/forums/scheduler---after-hours-appointment-bug

**Comment by kspeyanski** [comment]
I do suspect it might be related to: https://github.com/telerik/kendo-react/issues/1125 But will do further testing after we fix that one.

**Comment by kspeyanski** [comment]
After further testing, we've concluded that the two issues are connected, thus I'm closing this one as `fixed` with version `4.11.0` of the `@progress/kendo-react-scheduler` package.

For the full list of changes in this version, please refer to the changelog:
https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/

If you still encounter this issue even after updating, please let us know.
