### ISSUE TITLE
Allow Form submit with initial values

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#975]
Current behavior:
https://stackblitz.com/edit/react-wf5veh-pbgwyt?file=app/main.jsx 

Expected behavior:
The Form should be submitted when the initial values are present and none of the Fileds is modified.

Related to:
https://github.com/telerik/kendo-react/issues/617#issuecomment-864573195

**Comment by Xizario** [comment]
Fixed in 4.8.0

**Comment by InaGlushkova** [comment]
In order to allow Form submit when the initial values are present and none of the Fields is modified - the new `ignoreModified` property should be set to `true`.
