### ISSUE TITLE
Unable to enter fractions starting with .0 in NumericTextBox

### ISSUE THREAD

**Issue by georgeri** [telerik/kendo-react#98]
## I'm submitting a...

* Bug report 

## Current behavior

Entering fractions such as '.05' in NumericTextBox results in the value getting set to whole number -> .05 becomes '5'

## Expected behavior

The NumericTextBox should allow fractional inputs such as .05 .01 etc. It should not be required to input theses as 0.05, 0.01 etc as users tend to skip the '0.' part in most cases.

## Minimal reproduction of the problem with instructions

Go To:
https://www.telerik.com/kendo-react-ui/components/inputs/numerictextbox/#toc-basic-usage
In the basic usage example, input value .05 in the NumericTextBox input. It shows value as '5' instead of 0.05 or .05.

## What is the motivation or use case for changing the behavior?

User input is unexpectedly changed to incorrect value that many order of magnitude larger.

## Environment

Package versions:

```
    "@progress/kendo-react-inputs": "2.2.0"
```

Browser:

- Chrome (desktop) version 69.0.3497.100
- Firefox version 61.0.1
- IE version 11.0.9600.19035

System:
- Node version:  v6.11.5, v8.9.1 
- Platform:  Linux, Windows

**Comment by simonssspirit** [comment]
I made a test, but the value was still 0.05 after blur. Please refer to the video and advise if I missed something: https://www.screencast.com/t/RxjeLjYOvyDb

**Comment by georgeri** [comment]
@simonssspirit Please try typing in the input, instead of cut & pasting it.
Here is a screen cast to show the bug in action - see: https://www.youtube.com/watch?v=g7eXjxbOmPA

**Comment by simonssspirit** [comment]
@georgeri  Thank you for the clarification and apologize for being a bit late with the response.
This occurs because the value .0 is being automatically set to 0 and then 05 directly to 5.

We will research how we can optimize that to ensure that .0 is left .0 and not converted to 0.

**Comment by Xizario** [comment]
`v2.6.0` is published.

**Comment by georgeri** [comment]
I am still able to reproduce this bug at 
https://www.telerik.com/kendo-react-ui/components/inputs/numerictextbox/#toc-basic-usage 
Input .05 -> expected: 0.05, actual: 5.
The kendo demo page seems to be using "@progress/kendo-react-inputs": "2.6.1".
Did the fix regress between v2.6.0 and v2.6.1?

**Comment by Xizario** [comment]
@georgeri, I am sorry there were two very similar issues and I closed the wrong one.

**Comment by vladimirivanoviliev** [comment]
Fixed in latest dev version `3.10.0-dev.202001150733`.
