### ISSUE TITLE
Combobox in Dialog, pressing Esc to close the ComboBox closes the Dialog as well.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#983]
Combobox in Dialog, pressing Esc to close the ComboBox closes the Dialog as well.

This occurs as the event propagates to the Dialog.

Currently, we can add on logic to not close the Dialog when the event comes from the Combobox:

https://stackblitz.com/edit/react-oljpww?file=app%2Fmain.jsx

Still, this is not ideal, as it could be a similar component and we will need another check.

Also, if the application has multiple Dialogs, this solution does not scale well.

**Comment by nstoychev** [comment]
Here is a better solution - https://stackblitz.com/edit/react-oljpww-mnvagk?file=app%2Fmain.jsx

Calling syntheticEvent.stopPropagation(); in the ComboBox onClose event, and then in the Dialog's onClose will do nothing if syntheticEvent.isPropagationStopped() returns true.

@simonssspirit - I think we can close this issue.
