### ISSUE TITLE
Not possible to change the array of TileLayout#items without re-rendering

### ISSUE THREAD

**Issue by mkrauskopf** [telerik/kendo-react#984]
## Current behavior
It is not possible to change the array of `TileLayout#items` without existing tiles being rerendered. This is probably caused by using the array's indexes as keys for the internal tiles element.

## Expected behavior
It should be possible to manage items on the `TileLayout` without being forced to rerender existing items.

## Minimal reproduction of the problem with instructions

1. Use the Gist [here](https://gist.github.com/mkrauskopf/486addcd0b876e6f0bcffa963ad06bcc).
2. Open the dev console.
3. Hit the 'Remove Last' button - everything is fine.
4. Hit the 'Remove First' button - all tiles are remounted.

## What is the motivation or use case for changing the behavior?
This causes severe problems in real-world applications, like re-fetching data via the network, etc.

## Possible solution
Letting the API client pass its own `key` property via [TileLayoutItem](https://www.telerik.com/kendo-react-ui/components/layout/api/TileLayoutItem/) and use it internally instead of array index for the `key` should solve the problem.

## Environment
`"@progress/kendo-react-layout": "4.7.0"`

**Comment by silviyaboteva** [comment]
Requested again in Ticket ID: **1533806**

**Comment by InaGlushkova** [comment]
To change the array of the TileLayout items without re-rendering, set unique keys to the items.
For more information:
https://www.telerik.com/kendo-react-ui-develop/components/layout/tilelayout/configuration/
