### ISSUE TITLE
DateTimePicker sets an undefined title to its input element.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#988]
DateTimePicker sets an undefined title to its input element.

![image](https://user-images.githubusercontent.com/11087921/124076455-ee955380-da4e-11eb-9d7d-eafaac8ef04f.png)

**Comment by kspeyanski** [comment]
The issue has been fixed in version [4.9.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/) of the `@progress/kendo-react-scheduler` package.
