### ISSUE TITLE
React grid drag same column for grouping

### ISSUE THREAD

**Issue by Arsikod** [telerik/kendo-react#989]
At https://www.telerik.com/kendo-react-ui/components/grid/ page inside demo I can drag same column several times and it creates a grouping for the same column once again.

**Comment by Xizario** [comment]
Yes you can. 
If you need set groupable=false to columns that are already grouped, and they will not be dragged to the group panel again.

It is even more flexible, as the group descriptor is separated from the columns collection. You can group by fields that there are no such columns, and also make custom logic for when dragging columns into the groups to create additional or remove previous groups etc.

**Comment by simonssspirit** [comment]
Closing after a period of inactivity.
