### ISSUE TITLE
A warning is shown when passing props to the CalendarWeekCell component

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#995]
A warning is shown when passing props to the CalendarWeekCell component.

`Warning: React does not recognize the `firstDate` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `firstdate` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

https://stackblitz.com/edit/react-wrbnmd?file=app%2FcustomWeekCell.jsx

This occurs as all props are directly passed to the internal td element.

The current workaround will be to not pass this props to the CalendarWeekCell as it is not needed internally.

**Comment by kspeyanski** [comment]
The issue has been fixed in version [4.9.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/) of the `@progress/kendo-react-dateinputs` package.
