### ISSUE TITLE
Upload should not make requests if the removeUrl is not set

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#999]
Upload should not make requests if the removeUrl is not set:

https://stackblitz.com/edit/react-o9jta7?file=app/main.jsx

**Comment by kdikov82** [comment]
With the latest version (5.10.0), when the removeUrl is not set, the remove button is not rendered, so the file can't be removed from the UI and no request will be made:
https://stackblitz.com/edit/react-ry6a1f?file=app%2Fmain.tsx
